
= Εγχειρίδιο Slint (έκδοση 15.0)
:toc: left
:toclevels: 2
:toc-title: Content
:pdf-themesdir: themes
:pdf-theme: default

Note: this document will be updated to reflect recent changes - 21/06/2024

== Εισαγωγή στο Slint

=== Σχετικά Με Slint

Το Slint είναι μια https://en.wikipedia.org/wiki/Linux_distribution[διανομή Linux], βασισμένη στο http://www.slackware.com/[Slackware], polyglot, εύκολο στην εγκατάσταση, ευέλικτο, αρχάριος φιλικό και προσβάσιμο με τα άτομα με προβλήματα όρασης.

Ένα σύστημα Slint είναι λειτουργικό έξω από το κουτί και μπορεί να προσαρμοστεί για να χωρέσει τις περισσότερες απαιτήσεις υπολογιστών.

==== Χαρακτηριστικά

Προτείνονται δύο τρόποι εγκατάστασης: Αυτόματος (ο εγκαταστάτης προετοιμάζει τη μονάδα δίσκου που επιλέγει ο χρήστης και εγκαθιστά το Slint σε αυτό) και Χειροκίνητος (Ο εγκαταστάτης διαμορφώνει το διαμέρισμα Linux που επιλέγει ο χρήστης, μορφοποιήστε το και εγκαταστήστε το Slint σε αυτό). Ο εγκαταστάτης περιλαμβάνει μια τεκμηρίωση.

Το Slint είναι προσβάσιμο σε χρήστες με προβλήματα όρασης, με ομιλία και braille, από την εγκατάσταση έως τη χρήση σε μια κονσόλα όπως σε γραφικά περιβάλλοντα.

Μια ευρεία ποικιλία λογισμικού για διακομιστές, επιτραπέζιους υπολογιστές, και φορητούς υπολογιστές είναι εγκατεστημένο σε όλα τα συστήματα Slint, που περιλαμβάνουν δύο γραφικά περιβάλλοντα επιφάνειας εργασίας: MATE και LXQt, και ελαφρούς διαχειριστές παραθύρων. MATE και LXQt παρέχουν εύκολη πρόσβαση σε όλες τις εφαρμογές και λειτουργίες του συστήματος, με αυτόματη προσάρτηση αφαιρούμενων συσκευών, συν ειδοποιήσεις των διαθέσιμων ενημερώσεων του εγκατεστημένου λογισμικού, άμεση πρόσβαση στο Διαδίκτυο, σταμάτημα, επανεκκίνηση, και αδρανοποίηση του συστήματος.

Η επιλεγμένη γλώσσα θα χρησιμοποιηθεί για διεθνοποιημένες εφαρμογές.

Ο πίνακας ελέγχου Slint συγκεντρώνει πρόσβαση σε ρυθμίσεις υλικού και συστήματος, πακέτα, εργαλεία συστήματος, τεκμηρίωση και βοηθητικά προγράμματα.

Slint πλοία με πολλές εφαρμογές έξω από το πλαίσιο για να γράψει και να διαβάσει και να μετατρέψει έγγραφα σε διάφορες μορφές, επικοινωνούν με ηλεκτρονικό ταχυδρομείο, κείμενο και ηχητική συνομιλία, αναπαραγωγή ήχου και βίντεο, αποστολή και λήψη εγγράφων ομότιμος με ομότιμο, επεξεργασία ήχου, βίντεο και γραφικών εγγράφων, ανάπτυξη εφαρμογών. Είναι πλήρως χρησιμοποιήσιμο ως διακομιστής σε μια κονσόλα και χρησιμοποιώντας μία από τις πολλές περιλαμβάνονται desktops.

Πολλές εφαρμογές είναι προσβάσιμες σε χρήστες με προβλήματα όρασης, μια ευρεία επιλογή TTS και οι σχετικές φωνές περιλαμβάνονται, αν εξακολουθείτε να χρειάζεστε άλλους που είναι εύκολα εγκαταστάσιμοι, μπορούν να χρησιμοποιηθούν τόσο σε κειμενικό περιβάλλον (κονσόλα) όσο και στην επιφάνεια εργασίας.

Αρκετά εσωτερικά εργαλεία διευκολύνουν τη διαχείριση και τη διαμόρφωση του συστήματος Slint.

Πολλές περισσότερες εφαρμογές είναι εύκολα κατασκευασμένες ως πακέτα λογισμικού μέσω μιας απλής εντολής ή μερικά κλικ. Χιλιάδες πακέτα λογισμικού είναι στα χέρια σας!

Οι χρήστες του Slint ειδοποιούνται για αναβαθμίσεις εγκατεστημένων πακέτων μόλις είναι διαθέσιμα, εύκολα εγκατεστημένα κατόπιν αιτήματος. Αυτό διατηρεί το σύστημά σας ασφαλές.

Προεπιλεγμένες ρυθμίσεις εφαρμογών παρέχονται και μπορούν εύκολα να προσαρμοστούν.

==== Περιεχόμενο, εκδόσεις και μοντέλο απελευθέρωσης.

Το πρόγραμμα εγκατάστασης Slint παρέχει μόνο μια πλήρη εγκατάσταση.

Το Slint ακολουθεί ένα μοντέλο απελευθέρωσης "ημι-κύλισης", που σημαίνει ότι κατά τη διάρκεια του κύκλου ζωής μιας δεδομένης έκδοσης, εκτός από τις ενημερώσεις ως διορθώσεις ασφαλείας και σημαντικές διορθώσεις σφαλμάτων, μερικά λογισμικό ενημερώνονται επιλεκτικά για να φέρει βελτιώσεις, και προστίθενται για να φέρει νέα χαρακτηριστικά. Αυτή είναι η περίπτωση για το λογισμικό που συμβάλλει στο να κάνει το Slint προσιτό στους τυφλούς, όπως οι αναγνώστες οθόνης.

Συνιστούμε οι χρήστες να μεταβούν σε μια νέα έκδοση το συντομότερο δυνατό μετά την έκδοσή της. Συνιστούμε να κάνουν ένα πλήρες αντίγραφο ασφαλείας όλων των δεδομένων που θέλουν να διατηρήσουν ακολουθούμενη από μια νέα εγκατάσταση και μια αποκατάσταση του αντιγράφου ασφαλείας.

=== Σχετικά με αυτό το βιβλίο, άλλες πηγές πληροφοριών

Αυτό το βιβλίο προορίζεται για τον νεοφερμένο Slint τον οποίο καθοδηγεί μέσω της διαδικασίας εγκατάστασης και χρήσης του. Παρουσιάζονται οι έννοιες και οι συμβάσεις που αφορούν ειδικά το Slint και είναι κοινές στις διανομές του Linux και επισυνάπτεται ένα γλωσσάριο.

Προσπαθούμε να φιλοξενήσουμε λαούς που προέρχονται από Windows ή MacOS ως χρήστες μιας άλλης διανομής όπως το Ubuntu.

Τεκμηρίωση για εγκατεστημένο λογισμικό είναι γενικά διαθέσιμη σε ένα σύστημα Slint. Θα αναφέρουμε σε αυτό το βιβλίο πώς να έχει πρόσβαση σε αυτό.

Άλλες πηγές πληροφοριών είναι διαθέσιμες:

* Οι πληροφορίες που παρέχονται συχνά στην ιστοσελίδα τους από τους συγγραφείς του λογισμικού που περιλαμβάνονται στο Slint.
* http://docs.slackware.com/[Το έργο τεκμηρίωσης Slackware] και ιδιαίτερα τα άρθρα http://docs.slackware.com/howtos:start[HOWTO] Πολλά ισχύουν άμεσα για το Slint, μερικές προσαρμογές και ενημερώσεις μπορεί να είναι απαραίτητες.
* Πέρα από τη διανομή της Arch, το ArchWiki παρέχει συχνά χρήσιμο άρθρο για το λογισμικό που αποστέλλεται επίσης στο Slint. Για παράδειγμα η αναζήτηση του "archwiki mate" οδηγεί σε https://wiki.archlinux.org/index.php/MATE[αυτή τη σελίδα για το MATE]. Σεβώδης: οι παρεχόμενες πληροφορίες μπορούν να προσαρμοστούν καθώς οι Slint και Arch διαφέρουν από ορισμένες απόψεις. Για παράδειγμα το Arch χρησιμοποιεί το σύστημα ως init σύστημα και ένα δεδομένο λογισμικό μπορεί να ρυθμιστεί διαφορετικά από προεπιλογή στο Slint και την Arch.
* Και φυσικά μια μηχανή αναζήτησης στο Διαδίκτυο μπορεί συχνά να βοηθήσει στην εξεύρεση απαντήσεων σε ερωτήσεις και λύσεις σε ζητήματα.
// Support

=== Υποστήριξη

Μπορείτε να λάβετε βοήθεια μέσω αυτών των καναλιών:

* Η λίστα αλληλογραφίας του Slint είναι το κύριο κανάλι υποστήριξης. Για να εγγραφείτε, στείλτε email στο slint-request@freelists.org με θέμα 'εγγραφή' και μετά απαντήστε στο email επιβεβαίωσης που θα λάβετε. Στη συνέχεια, για να μάθετε περισσότερα email slint-request@freelists.org με θέμα «εντολές» ή «βοήθεια». Μετά την εγγραφή, email slint@freelists.org.
* Τα αρχεία της λίστας είναι διαθέσιμα https://www.freelists.org/archive/slint[εδώ].
* Στις IRC: συνομιλήστε στο κανάλι #slint, server irc.libera.chat, δεν απαιτείται εγγραφή.
* Mumble: server slint.fr (για ραντεβού που λήφθηκε μέσω ενός άλλου καναλιού).
* Το https://forum.salixos.org/viewforum.php?f=44[φόρουμ Slint] φιλοξενείται ευγενικά από τους φίλους μας στο Salix (άλλο παράγωγο Slackware. Απαιτείται εγγραφή.


To find out more, see the links under Information in the Slint Dashboard or just type: slint-doc in a terminal after installation.

=== Μετάφραση και άλλες συνεισφορές στο έργο Slint

Slint χρειάζονται μεταφραστές! Αν θέλετε να συμμετάσχετε στην προσπάθεια μετάφρασης, διαβάστε τις οδηγίες στο https://slint.fr/doc/translate_slint.html[Translate Slint].

Τα αρχεία μετάφρασης φιλοξενούνται στο https://crowdin.com/project/slint[Crowdin].

Αν θέλετε να συνεισφέρετε στο Slint για άλλες εργασίες, απλά δημοσιεύστε τη λίστα αλληλογραφίας ή αφήστε μια γραμμή στο: didieratslintdotfr. Φυσικά οι μεταφραστές είναι ευπρόσδεκτοι και στη λίστα αλληλογραφίας!
// Acknowledgments

=== Ευχαριστίες

Το έργο Slint υπάρχει κυρίως μέσω της σκληρής δουλειάς των μεταφραστών του Slint και άλλων συνεισφερόντων, χάρη σε όλους σας!

Χάρη στον George Vlahavas για τις συμβουλές και τα εργαλεία του, στους συνεισφέροντες στο έργο SlackBuilds.org, οι οποίοι βοηθούν στην κατασκευή τόσων πολλών πρόσθετων λογισμικών.

Το Slint βασίζεται στο Slackware, που έφερε ο Patrick J. Volkerding και οι συντελεστές του. Ευχαριστούμε! Ενθαρρύνω όλους τους χρήστες του Slint να συνεισφέρουν στη χρηματοδότηση του Slackware και επίσης να δωρίσουν στο έργο Salix.

Τα αποθετήρια του Slint φιλοξενούνται δωρεάν από τον Darren 'Tadgy' Austin. Ενθαρρύνω όλους τους χρήστες του Slint να συνεισφέρουν στη χρηματοδότηση του κεντρικού υπολογιστή https://slackware.uk/

Σύνδεσμοι για οικονομικές συνεισφορές: +
https://www.patreon.com/slackwarelinux[Γίνετε ένας Slackware patron] ή https://paypal.me/volkerdi[Support Slackware] +
Ακολουθήστε τις συνδέσεις στην κορυφή της σελίδας http://slackware.uk/slint/x86_64/slint-15.0/[this] για την υποστήριξη της Slackware UK +
https://salixos.org/donations.html[Donations στο Salix]

== Εγκατάσταση Γραμμής

Αυτό το μέρος του HandBook περπατά μέσα από τη διαδικασία λήψης του Slint, επαληθεύοντας την εικόνα ISO με ένα check-sum, γράφοντας το ISO σε ένα μέσο εγκατάστασης, διαμένοντας το σκληρό σας δίσκο, και περιγράφει εν συντομία τη διαδικασία εγκατάστασης.

=== Απαιτήσεις

Η τρέχουσα έκδοση του Slint μπορεί να εγκατασταθεί σε υπολογιστές που πληρούν αυτές τις απαιτήσεις:

* Αρχιτεκτονική: x86_64 (64-bit CPU), γνωστό και ως AMD64
* Σε λειτουργία αυτόματης κατάτμησης, ένας δίσκος μεγέθους τουλάχιστον 50G
* Στη λειτουργία Χειροκίνητης κατάτμησης ένα διαμέρισμα τύπου Linux μεγέθους τουλάχιστον 50G, ένα διαμέρισμα συστήματος EFI και/ή ένα διαμέρισμα εκκίνησης BIOS στην ίδια μονάδα δίσκου. Το διαμέρισμα EFI είναι υποχρεωτικό εάν οι το μηχάνημα εκκινεί σε λειτουργία EFI, το διαμέρισμα εκκίνησης BIOS εάν το μηχάνημα εκκινεί σε legacy mode, το να έχεις και τα δύο είναι καλύτερο να επιτρέπεις την εναλλαγή μεταξύ του EFI και του Legacy mode.
* Το Sint μπορεί να εγκατασταθεί σε αυτά τα είδη δίσκων: σκληρούς δίσκους, SSD, NVME, eMMC, USB sticks, κάρτες SD (κατά προτίμηση σε θήκες USB).
* RAM: τουλάχιστον 2G
* μια μονάδα DVD ή μια υποδοχή USB διαθέσιμη, με την ικανότητα του firmware να εκκινήσει ένα DVD ή USB stick. Ένα κενό DVD ή ένα 5G ή περισσότερο USB stick μπορεί να χρησιμοποιηθεί ως μέσο εγκατάστασης

NOTE: Η ασφαλής εκκίνηση πρέπει να απενεργοποιηθεί για την εγκατάσταση του Slint.

=== Χαρακτηριστικά του εγκαταστάτη

* Ο εγκαταστάτης είναι ένα "ζωντανό σύστημα", που εκτελείται στη μνήμη: δεν θα τροποποιήσει ένα εγκατεστημένο σύστημα, εκτός αν και μέχρι να το πείτε.
* Για τυφλούς χρήστες, ο εγκαταστάτης είναι πλήρως χρησιμοποιήσιμος με Braille, και ομιλία χρησιμοποιώντας τον αναγνώστη οθόνης speakup.
* Περιλαμβάνει όλα τα απαραίτητα βοηθητικά προγράμματα για την προετοιμασία των απαιτούμενων διαμερισμάτων πριν από την εγκατάσταση σε λειτουργία χειροκίνητης διαμέρισης.
* Η αυτόματη λειτουργία εγκατάστασης χρειάζεται μόνο το χρήστη για να απαντήσει σε ερωτήσεις και να παρέχει μια σχετική βοήθεια γι 'αυτούς.
* Εάν εγκατασταθεί μόνο σε μια αφαιρούμενη συσκευή συνδεδεμένη μέσω USB, το Slint είναι φορητό, δηλαδή χρησιμοποιήσιμο σε οποιονδήποτε υπολογιστή μπορεί να εκκινηθεί από μια μονάδα USB πέραν του υπολογιστή που χρησιμοποιήθηκε για την εγκατάσταση του. Για παράδειγμα, αν εγκαθιστάτε σε USB stick μπορείτε απλά να συνδέσετε το usb σε έναν υπολογιστή για να το εκκινήσετε.
* Ο εγκαταστάτης μπορεί να κρυπτογραφήσει τη μονάδα δίσκου όπου το Slint είναι εγκατεστημένο μόνο. Αυτό αποτρέπει την κλοπή των δεδομένων που περιέχει σε περίπτωση απώλειας ή κλοπής της μηχανής, ή μιας αφαιρούμενης κίνησης.
* Το Slint μπορεί να εγκατασταθεί στη δική του μονάδα δίσκου, και σε λειτουργία χειροκίνητης διαμέρισης παράλληλα με ένα άλλο σύστημα.

=== Προετοιμασία

<<download_and_verify,Download and verify a Slint ISO image>> +
<<write_the_iso,Write the ISO image on an Installation Medium>> +
<<prepare_partitions_for_Slint,Optionally, prepare partitions for Slint>>

[[download_and_verify]]
==== Κατεβάστε και επαληθεύστε μια εικόνα ISO Slint

Η τελευταία έκδοση της κατανομής Slint είναι 15.0

Η τελευταία εικόνα ISO εγκατάστασης είναι πάντα διαθέσιμη στο https://slackware.uk/slint/x86_64/slint-15.0/iso[αυτός ο κατάλογος]

Μπορείτε επίσης να κατεβάσετε αυτή την εικόνα ISO χρησιμοποιώντας έναν Πελάτη Torrent από αυτή τη σελίδα:

https://seedbox.slackware.uk/

Ο σύνδεσμος προς το torrent, μετά την ετικέτα "Slint Torrents", είναι:

https://seedbox.slackware.uk/torrents/slint64-15.0-5-iso.torrent

Παρέχεται επίσης μαγνήτης.

[TIP]
====
Εφόσον εκτελείτε την έκδοση 15.0 του Slint, δεν υπάρχει ανάγκη επανεγκατάστασης όταν παρέχεται ένα νέο ISO, καθώς φέρνει μόνο νέα χαρακτηριστικά του εγκαταστάτη και νέα ή και αναβαθμισμένα πακέτα που μπορείτε επίσης να πάρετε κρατώντας το σύστημά σας ενημερωμένο.
====

Το όνομα αρχείου του ISO που υποδεικνύεται παρακάτω είναι απλά ένα παράδειγμα, που θα προσαρμοστεί στο τρέχον όνομα κατά τη λήψη.

Εάν εκτελείτε Windows, ένα Internet με ως επιχείρημα "ελέγξτε sha256sum windows" θα σας πει τρόπους για να προχωρήσετε.

Εάν εκτελείτε Linux μπορείτε να κατεβάσετε την εικόνα ISO και το άθροισμα ελέγχου sha256 που πληκτρολογεί:
----
wget https://slackware.uk/slint/x86_64/slint-15.0/iso/slint64-15.0-5.iso
wget https://slackware.uk/slint/x86_64/slint-15.0/iso/slint64-15.0-5.iso.sha256
----

Για να ελέγξετε την ακεραιότητα των κατεβασμένων αρχείων πληκτρολογήστε αυτήν την εντολή: sha256sum -c slint64-14.2.1.4.iso.sha256 το αποτέλεσμα πρέπει να είναι: OK
----
sha256sum -c slint64-15.0-5.iso.sha256
----

Το αποτέλεσμα θα πρέπει να είναι: OK +
αλλιώς, επαναλάβετε τις λήψεις.

[[write_the_iso]]
==== Γράψτε την εικόνα ISO σε ένα μέσο εγκατάστασης

Μπορείτε να χρησιμοποιήσετε είτε ένα DVD είτε ένα USB stick ως μέσα εγκατάστασης.

[TIP]
====
Μπορείτε μόνο να αποθηκεύσετε την εικόνα ISO στο πρώτο διαμέρισμα ενός στικ Ventoy USB.

Σε αυτή την περίπτωση στην αρχή της εγκατάστασης, ο εγκαταστάτης θα ζητήσει να προσαρτήσετε αυτό το διαμέρισμα και στη συνέχεια να προσαρτήσετε το ίδιο το ISO.
====

[[make_a_bootable_usb_stick]]
===== Κάντε ένα Bootable USB Stick

Σε σύστημα ++Linux+++, συνδέστε το USB stick, και ελέγξτε ότι είναι όνομα με την ακόλουθη εντολή:

----
lsblk -o μοντέλο, όνομα, μέγεθος, fstype, σημείο τοποθέτησης
----

[WARNING]
====
Ελέγξτε προσεκτικά την έξοδο της εντολής για να βεβαιωθείτε ότι δεν θα πληκτρολογήσετε το όνομα ενός διαμερίσματος σκληρού δίσκου αντί για το όνομα του USB stick. Όλο το προηγούμενο περιεχόμενο του USB stick ή ενός λανθασμένου διαμερίσματος σκληρού δίσκου θα είναι **LOST** και **IRRECOVERABLE**.
====

Ας υποθέσουμε ότι το όνομα του USB stick είναι /dev/sdb. Θα μπορούσε να ονομαστεί διαφορετικά, οπότε μην αντιγράφεις τυφλά την ακόλουθη εντολή. Η σύνταξη της εντολής για την εγγραφή του Slint ISO σε ένα κλειδί USB που βρίσκεται στο /dev/sdb έχει ως εξής:

----
dd if=slint64-15.0-5.iso of=/dev/sdb bs=1M status=progress && sync
----

[NOTE]
====
Η παραπάνω εντολή υποθέτει **if=** δείχνει τη διαδρομή του Slint ISO και **of=** δείχνει το όνομα του USB stick. Αυτές οι τιμές μπορεί να διαφέρουν στο σύστημά σας.
====

Στο +Windows++ χρησιμοποιείται μια εφαρμογή όπως http://rufus.akeo.ie/[Rufus]. Είναι δωρεάν και ανοιχτού κώδικα.

[[make_a_bootable_DVD_disc]]
===== Κάντε ένα Bootable DVD Disc

Σε ένα σύστημα ++Linux++ εισάγετε το DVD και πληκτρολογήστε την ακόλουθη εντολή:

----
xorriso -as cdrecord -v dev=/dev/sr0 -eject slint64-15.0-5.iso
----

Σιγουρευτείτε ότι εισάγετε την πλήρη διαδρομή του ISO Slint στο σύστημα αρχείων σας.

Στο ++Microsoft Windows 2000/XP/Vista/7++ μπορείτε να γράψετε σε ένα DVD χρησιμοποιώντας την εφαρμογή http://infrarecorder.org/[InfraRecorder]. Είναι δωρεάν και ανοικτού κώδικα.

On ++Microsoft Windows 7/8/10++ you can use the utility that is shipped with Microsoft Windows.

* Κάντε δεξί κλικ στο αρχείο ISO και επιλέξτε Εγγραφή εικόνας δίσκου (στα Windows 11, επιλέξτε Εμφάνιση περισσότερων επιλογών πρώτα (Shift+f10)
* To make sure the ISO was burned without any errors, select Verify disc after burning.

[NOTE]
====
Instructions not checked by the writer.
====

// Prepare
[[prepare_partitions_for_Slint]]
==== Προαιρετικά, ετοιμάστε διαμερίσματα για το Slint

Σε αυτό το έγγραφο 'format' ένα διαμέρισμα σημαίνει: δημιουργήστε ένα σύστημα αρχείων σε αυτό για να διαχειριστείτε τα αρχεία που θα περιέχει.

Εάν αφού πληκτρολογήσετε 'start' πληκτρολογήσετε 'm' για χειροκίνητη κατάτμηση, θα επιλέξετε πρώτα το διαμέρισμα ριζικού συστήματος, το οποίο θα προσαρτηθεί ως "/", μετά τον τύπο του συστήματος αρχείων του μεταξύ: btrfs, ext4, xfs.

Το πρόγραμμα εγκατάστασης εμφανίζει μόνο διαμερίσματα μεγέθους τουλάχιστον 50G και Linux (μπορεί επίσης να ονομάζεται σύστημα αρχείων Linux), όχι κρυπτογραφημένο. Αυτό το διαμέρισμα μπορεί να διαμορφωθεί ή όχι, αλλά σε κάθε περίπτωση το περιεχόμενό του θα διαγραφεί και ένα νέο σύστημα αρχείων που θα δημιουργηθεί από το πρόγραμμα εγκατάστασης.

Επιπλέον, η χειροκίνητη λειτουργία διαχωρισμού απαιτεί την ίδια μανάδα δίσκου με το διαμέρισμα του ριζικού συστήματος:

* Ένα διαμέρισμα τύπου διαμερίσματος εκκίνησης BIOS, μεγέθους τουλάχιστον 3M και μη μορφοποιήσιμο εάν το μηχάνημα εκκινεί σε λειτουργία Legacy mode και ο δίσκος έχει ένα πίνακα χωρισμάτων τύπου GPT.
* Ένα διαμέρισμα συστήματος τύπου EFI, με τουλάχιστον 32M ελεύθερο χώρο σε αυτό, μορφοποιημένο με σύστημα αρχείων 'fat' (ή 'vfat') όπως απαιτείται από την προδιαγραφή UEFI εάν το μηχάνημα εκκινεί σε EFI mode

Είναι προτιμότερο να ρυθμίσετε και τα δύο χωρίσματα για να επιτρέπεται η εναλλαγή μεταξύ των καταστάσεων Legacy και EFI, εάν η μονάδα διαθέτει πίνακα χωρισμάτων τύπου GPT.

Χρησιμοποιώντας τις υπάρχουσες κατατμήσεις για το Slint ή η δημιουργία τους είναι στο χέρι του χρήστη. Τα ήδη εγκατεστημένα συστήματα που χρησιμοποιούν την εκκίνηση του BIOS και τα διαμερίσματα EFI δεν θα επηρεαστούν, μόνο το διαμέρισμα root θα (επανα)μορφοποιηθεί, και ένα υπάρχον /home διαμέρισμα μόνο εφόσον ζητηθεί.

Το πρόγραμμα εγκατάστασης περιλαμβάνει διάφορες εφαρμογές διαμερισμού: cfdisk, fdisk, sfdisk, cgdisk, gdisk, sgdisk, parted. Οι εφαρμογές με "g" στο όνομά τους μπορούν να χειριστείτε μόνο gpt, το parted μπορεί να χειριστεί πίνακες χωρισμάτων DOS, καθώς και GPT. Τα fdisk, cfdisk και sfdisk μπορoύν να χειριστουν πίνακες χωρισμάτων DOS. Επιπλέον, είναι διαθέσιμες οι wipefs (για τη διαγραφή των προηγούμενων υπογραφών του πίνακα χωρισμάτων και των υπογραφών του συστήματος αρχείων) και το patprobe (για την ενημέρωση του πυρήνα για τις αλλαγές ενός πίνακα χωρισμάτων). Οι εφαρμογές blkid και lsblk εμφανίζουν πληροφορίες σχετικά με συσκευές μπλοκ και χωρίσματα.

Φυσικά, μπορείτε επίσης να δημιουργήσετε τα διαμερίσματα από ένα άλλο σύστημα πριν από την έναρξη του εγκαταστάτη.
// Installation

=== Εγκατάσταση Slint
<<Start_of_the_installation,Start of the installation>> +
<<Overview_of_Slint_Installation,Overview of the installation process>> +
<<Usage_of_the_installer,Usage of the installer>> +
<<Encryption,Slint with an encrypted root partition>> +
<<Speakup,Key bindings for the Speakup screen reader>> +
<<first_steps_after_installation,First steps after installation>><Encryption,Slint with an encrypted root partition>

[[Start_of_the_installation]]
==== Έναρξη της εγκατάστασης

Εάν χρειάζεται, ρυθμίστε το firmware του μηχανήματος για να εκκινήσετε το DVD ή USB stick που έχετε ετοιμάσει.

Τοποθετήστε το μέσο εγκατάστασης (DVD ή USB stick) και επανεκκινήστε το μηχάνημά σας. Για να βοηθήσετε τυφλούς χρήστες ακούγεται μια μελωδία όταν εμφανίζεται το μενού εκκίνησης.

Ξεκινήστε τον εγκαταστάτη πατώντας το Enter.

Ο εγκαταστάτης θα εξετάσει πρώτα τις κάρτες ήχου.

Αυτό μπορεί να βοηθήσει στη ρύθμιση μιας λειτουργικής ως προεπιλογή, και επίσης χρησιμοποιείται για την ομιλία κατά την εγκατάσταση που χρησιμοποιείται από μερικούς τυφλούς χρήστες.

Εάν το πρόγραμμα εγκατάστασης βρει περισσότερες από μία κάρτες ήχου θα πει στα αγγλικά για κάθε: +
πατήστε Enter για να επιλέξετε αυτή τη κάρτα ήχου <sound card id> +
Πατήστε Enter μόλις το ακούσετε, για να επιβεβαιώσετε ότι η προτεινόμενη κάρτα ήχου λειτουργεί. Αυτή η ρύθμιση θα αποθηκευτεί στο νέο σύστημα στο αρχείο /etc/asound.conf.

Στο επόμενο βήμα, όταν σας ζητηθεί θα επιβεβαιώσετε (πληκτρολογήσεις) ή θα αρνηθείτε (απλά πατώντας Enter) ότι θέλετε ομιλία κατά την εγκατάσταση. Το Braille είναι πάντα διαθέσιμο κατά την εγκατάσταση.

Στη συνέχεια θα επιλέξετε, επιβεβαιώσετε ή αλλάξετε τη γλώσσα που χρησιμοποιήθηκε κατά την εγκατάσταση. Στη συνέχεια, όλες οι οθόνες θα είναι στην επιλεγμένη γλώσσα αν η μετάφραση σε αυτή τη γλώσσα είναι πλήρης.

Αν χρειαστεί να προσαρτήσετε πρόσθετες παραμέτρους πυρήνα στη γραμμή εντολών εκκίνησης, πριν πατήσετε Enter κάντε ό,τι ακολουθεί:
[NOTE]
====
Θα πρέπει να γνωρίζετε ότι ο χάρτης πληκτρολογίου των ΗΠΑ θα χρησιμοποιείται κατά την πληκτρολόγηση. +
Ctrl+x σημαίνει "Πατήστε και κρατήστε πατημένο το Ctrl ή το πλήκτρο Control όπως αν ήταν πλήκτρο Shift και στη συνέχεια πατήστε το πλήκτρο X"
====
----
Πατήστε το πλήκτρο e
Πατήστε το κάτω βέλος τρεις φορές
Πατήστε το πλήκτρο λήξης
Πατήστε το πλήκτρο διαστήματος
Πληκτρολογήστε τις παραμέτρους του πυρήνα (παραδείγματα παρακάτω)
Πατήστε Ctrl+X για εκκίνηση (δεν πατήσετε το πλήκτρο Enter!)
Πατήστε Enter για εκκίνηση.
----

Για παράδειγμα για να ρυθμίσετε το πρόγραμμα οδήγησης ομιλίας για το συνθέτη υλικού σας θα μπορούσατε να πληκτρολογήσετε μια παράμετρο πυρήνα όπως:
----
speakup.synth=apollo
----
Μπορείτε επίσης να συμπεριλάβετε στη γραμμή εντολών εκκίνησης τις ρυθμίσεις για τη συσκευή Braille σας, σε αυτή τη μορφή:
-----
brltty=<driver code>,<device>,<text table>
-----
Για παράδειγμα για να εγκαταστήσετε με μια συσκευή Papenmeier συνδεδεμένη μέσω USB με ένα γαλλικό τύπο πίνακα κειμένου:
-----
brltty=pm,usb:,fr_FR
-----
NOTE: Μια συσκευή braille που συνδέεται μέσω USB θα πρέπει πάντα να αναγνωρίζεται, ίσως μόνο ο πίνακας κειμένου δεν θα είναι ο καλός αν δεν εισαγάγετε τις ρυθμίσεις πρώτα.

Σε κάθε περίπτωση, καθώς δεν υπάρχει χρονικό όριο, η εκκίνηση θα ξεκινήσει μόνο όταν πατήσετε [Enter].

Η ομιλία και το Braille είναι διαθέσιμα στην αρχή της εγκατάστασης.
// Overview
[[Overview_of_Slint_Installation]]
==== Επισκόπηση της διαδικασίας εγκατάστασης

Το πρόγραμμα εγκατάστασης ελέγχει πρώτα τις υπάρχουσες μονάδες και διαμερίσματα για να αξιολογήσει τις δυνατότητες και τις επιλογές εγκατάστασης και να σας επιτρέψει να επιλέξετε μεταξύ μιας αυτόματης ή μη αυτόματης προετοιμασίας των διαμερισμάτων που χρησιμοποιούνται από το Slint.

Αν επιλέξετε το 'εγχειρίδιο' παρουσιάζονται τα διαμερίσματα Linux όπου μπορεί να εγκατασταθεί το Slint (μέγεθος τουλάχιστον 50G), επιλέξτε ένα από αυτά και επιλέξτε το είδος του συστήματος αρχείων που θα δημιουργήσει το πρόγραμμα εγκατάστασης σε αυτό: btrfs, ext4 ή xfs όπως αναφέρεται στο <<prepare_partitions_for_Slint,Optionally prepare partitions for Slint>>

Αν επιλέξετε 'auto' παρουσιάζονται οι μονάδες όπου θα μπορούσε να εγκατασταθεί το Slint (μέγεθος τουλάχιστον 50G), και το σύστημα αρχείων θα είναι τύπου btrfs.

Σε περίπτωση btrfs; υποτόμοι θα δημιουργηθούν για το "/" και το "/home" με συμπιεσμένα αρχεία, και /swap για να φιλοξενήσει ένα αρχείο swap. 'Αντιγραφή κατά την εγγραφή' θα διευκολύνει την πραγματοποίηση στιγμιότυπων και ενδεχομένως θα επανέλθει μια ελαττωματική ενημέρωση του συστήματος. Τα εργαλεία για τη διαχείριση των στιγμιότυπων περιλαμβάνονται στο Slint.

Και στις δύο λειτουργίες, ο χρήστης επιλέγει ποια υπάρχοντα διαμερίσματα Linux και Windows θα προσαρτηθούν αυτόματα μετά την εκκίνηση του Slint και τα ονόματα των σημείων προσάρτησής τους, διευκολύνοντας την πρόσβαση σε υπάρχοντα συστήματα και δεδομένα από το Slint.

Στη συνέχεια προτείνεται ο χρήστης να κρυπτογραφήσει το κύριο διαμέρισμα του συστήματος, για να αποτρέψει την κλοπή δεδομένων σε περίπτωση απώλειας ή κλοπής του μηχανήματος ή της μονάδας όπου είναι εγκατεστημένο το Slint. Αν γίνει αποδεκτό το πρόγραμμα εγκατάστασης καταγράφει τη φράση πρόσβασης που επιτρέπει το ξεκλείδωμα αυτού του διαμερίσματος. Ο χρήστης θα το πληκτρολογεί κατά την πληκτρολόγηση όταν ζητηθεί από τo GRUB για την εμφάνιση του μενού εκκίνησης.

Μετά από όλα αυτά ο εγκαταστάτης συνοψίζει τις επιλογές σας και σας επιτρέπει να τις επιβεβαιώσετε ή όχι. Μέχρι αυτό το σημείο δεν θα έχει γίνει καμία τροποποίηση στα εγκατεστημένα συστήματα και δεδομένα ώστε να μπορείτε να αρνηθείτε με ασφάλεια, στη συνέχεια πληκτρολογήστε να ξεκινήσετε ξανά ή απλά επανεκκινήστε χωρίς βλάβη.

Στη συνέχεια, η αυτόματη κατάτμηση γίνεται με περίπτωση, το διαμέρισμα Slint root κρυπτογραφείται αν ζητηθεί, το διαμέρισμα ρίζας είναι διαμορφωμένο και τα πρώτα πακέτα λογισμικού έχουν εγκατασταθεί.

Αν επιλέξατε έναν κρυπτογραφημένο δίσκο πληκτρολογείτε τη φράση πρόσβασης που θα χρησιμοποιηθεί για να ξεκλειδώσετε τη μονάδα δίσκου σε κάθε εκκίνηση επάνω.

Επιλέξτε έναν κωδικό πρόσβασης για το χρήστη "root". Αυτός είναι ο διαχειριστής συστήματος, ο οποίος έχει όλα τα δικαιώματα.

Μπορείτε επίσης να ορίσετε το όνομα σύνδεσης και τον κωδικό πρόσβασης ενός κανονικού χρήστη.

Δηλώνετε αν θα χρειαστείτε πρόσβαση στη γραφή Braille, και αν θέλετε να συνδεθείτε σε κείμενο ή σε κατάσταση γραφικών. Εάν χρησιμοποιήσατε την αγγλική γλώσσα (ΗΠΑ) κατά τη διάρκεια της εγκατάστασης, επιλέγετε τη γλώσσα που θα χρησιμοποιηθεί στο εγκατεστημένο σύστημα, διαφορετικά το πρόγραμμα εγκατάστασης ορίζει το ίδιο όπως κατά την εγκατάσταση.

Ο εγκαταστάτης προσπαθεί να δημιουργήσει μια σύνδεση στο Διαδίκτυο, και αν είναι επιτυχής προτείνει μια ζώνη ώρας που αντιστοιχεί στη γεωγραφική σας θέση που επιβεβαιώνετε, αλλιώς επιλέξτε ένα σε μια λίστα.

Θα σας ζητηθεί αν θα χρειαστείτε Braille, στη συνέχεια, αν προτιμάτε να ξεκινήσετε σε μια κονσόλα ή σε ένα γραφικό εκτός αν χρησιμοποιήσατε λόγο κατά την εγκατάσταση ή χρειάζεστε Braille: τότε θα προσγειωθεί σε μια κονσόλα μετά την επανεκκίνηση, για την ασφάλεια.

Ο εγκαταστάτης δημιουργεί ένα αρχείο swap. Αυτό μπορεί να διαρκέσει πολύ, παρακαλώ να είστε υπομονετικοί.

Τα πακέτα είναι εγκατεστημένα στη μονάδα. Αν έχει δημιουργηθεί σύνδεση στο Internet, μεταφορτώνει και εγκαθιστά την πιο πρόσφατη έκδοση κάθε πακέτου, συμπεριλαμβανομένων αυτών που παρέχονται από την έκδοση της εικόνας ISO.

Η εγκατάσταση όλων των πακέτων διαρκεί περίπου 10 έως 40 λεπτά ανάλογα με το υλικό.

Θα σας ζητηθεί να επιλέξετε μια επιφάνεια εργασίας (ακόμα και αν ξεκινήσετε σε μια κονσόλα πρώτα) μεταξύ fvm, lxqt, mate και wmaker. Άλλες επιλογές θα είναι διαθέσιμες μετά την πληκτρολόγηση της εγκατάστασης 'xwmconfig' αν ξεκινήσετε σε μια κονσόλα

Στη συνέχεια, το σύστημα έχει ρυθμιστεί και ο διαχειριστής εκκίνησης GRUB εγκατεστημένος. Το Slint μπορεί να εκκινήσει σε λειτουργίες Legacy και EFI. Το μενού εκκίνησης θα περιλαμβάνει μια καταχώρηση εκκίνησης "διάσωση" για να εντοπίσει και να επιτρέψει την εκκίνηση οποιουδήποτε εγκατεστημένου λειτουργικού συστήματος.

Μπορείτε να εμφανίσετε μια προεπισκόπηση του μενού εκκίνησης πριν την επανεκκίνηση.

Στη συνέχεια, αφαιρέστε τα μέσα εγκατάστασης και επανεκκινήστε το νέο σύστημα Slint.
// Usage_installer
[[Usage_of_the_installer]]
==== Χρήση του εγκαταστάτη

Αν είστε εξοικειωμένοι με τη γραμμή εντολών, μπορείτε να παραλείψετε αυτό το θέμα.

Το κύριο μενού εγκατάστασης εμφανίζεται παρακάτω:
....
Καλώς ήλθατε στο πρόγραμμα εγκατάστασης του Slint! (έκδοση 15)

Μπορείτε τώρα να πληκτρολογήσετε (χωρίς τα εισαγωγικά):

'doc' για να γνωρίζετε τα χαρακτηριστικά και τη χρήση του εγκαταστάτη.
'start' για να ξεκινήσετε την εγκατάσταση.

Ο εγκαταστάτης μπορεί να προετοιμάσει τη μονάδα δίσκου όπου θα εγκατασταθεί το Slint,
δημιουργώντας τα απαραίτητα διαμερίσματα. Αν προτιμάτε να μπορείτε να το κάνετε μόνοι σας
χρησιμοποιώντας βοηθητικά προγράμματα γραμμής εντολών διαθέσιμα στο πρόγραμμα εγκατάστασης, στη συνέχεια, πληκτρολογήστε 'έναρξη'
όταν τελειώσετε. Μπορείτε επίσης να αφήσετε τον εγκαταστάτη και να χρησιμοποιήσετε ένα εργαλείο όπως το gparted
για να το κάνετε και στη συνέχεια να εκκινήσετε ξανά το πρόγραμμα εγκατάστασης.

Σας συνιστούμε να πληκτρολογήσετε πρώτα το 'doc' σε αυτή την περίπτωση ή αν θέλετε να
κρυπτογραφήσετε το ριζικό διαμέρισμα Slint.
Όταν ολοκληρώσετε την ανάγνωση αυτού του μενού θα εμφανιστεί ξανά.
....

Μόλις εμφανιστεί αυτό το μενού, έχετε το χέρι στη διαδικασία εγκατάστασης.

Μπορείτε να διαβάσετε την οθόνη και πληκτρολογήστε εντολές σε ένα <<virtual_terminal,virtual terminal>>. Ο εγκαταστάτης περιλαμβάνει 4 εικονικά τερματικά που μοιράζονται το ίδιο φυσικό πληκτρολόγιο και οθόνη, που μπορούν να χρησιμοποιηθούν παράλληλα.

Ο εγκαταστάτης ξεκινά στο εικονικό τερματικό 1 που ονομάζεται *tty1* αλλά μπορείτε να μεταβείτε σε άλλο. Για παράδειγμα, μπορείτε να αλλάξετε σε *tty2* πατώντας *Alt-F2* και έπειτα Enter για να το ενεργοποιήσετε και αργότερα να επιστρέψετε στο *tty1* πατώντας *Alt-F1*, χωρίς διαγραφή πληροφοριών που εμφανίζονται και στα δύο τερματικά. *Alt-F1* σημαίνει: πατήστε και κρατήστε πατημένο το πλήκτρο *Alt* και μετά πατήστε το πλήκτρο *F1*.

This can be useful to continue reading the documentation during installation: for instance you can switch to *tty2* to begin installation, switch to *tty1* to continue reading the documentation, then switch to *tty1* again to proceed to the next installation step.

Αυτό μπορεί επίσης να χρησιμοποιηθεί για να συμβουλευτείτε το γλωσσάριο κατά την ανάγνωση άλλων εγγράφων.

Ο εγκαταστάτης έχει διάφορους τρόπους αλληλεπίδρασης με εσάς, τον χρήστη:

* Πληκτρολογείτε εντολές στην προτροπή και διαβάστε την έξοδο.
* Ο εγκαταστάτης κάνει μια ερώτηση, πληκτρολογείτε την απάντηση και την επιβεβαιώνετε πατώντας Enter.
* Το πρόγραμμα εγκατάστασης εμφανίζει ένα μενού επιλογών ή επιλογών: επιλέγετε μία από αυτές χρησιμοποιώντας τα βελάκια πάνω και κάτω, στη συνέχεια, επιβεβαιώστε την επιλογή σας πατώντας Enter, ή ακυρώστε πατώντας Escape.
* Ο εγκαταστάτης εμφανίζει πληροφορίες σε μια σελίδα. Στη συνέχεια, χρησιμοποιήστε τα πλήκτρα βέλους για να διαβάσετε την επόμενη ή προηγούμενη γραμμή, πατήστε το πλήκτρο διαστήματος για να εμφανίσετε την επόμενη σελίδα, Q για να σταματήσετε την ανάγνωση του εγγράφου.

// Encryption
[[Encryption]]
==== Το Slint με ένα κρυπτογραφημένο ριζικό διαμέρισμα.

Σε λειτουργία Auto, το πρόγραμμα εγκατάστασης προτείνει την κρυπτογράφηση του κεντρικού διαμερίσματος του συστήματος. Εάν συμφωνείτε, σε κάθε εκκίνηση ο φορτωτής εκκίνησης GRUB θα σας ρωτήσει τη φράση πρόσβασης που θα έχετε πληκτρολογήσει κατά τη διάρκεια της εγκατάστασης για να ξεκλειδώσετε τη μονάδα, πριν εμφανιστεί το μενού εκκίνησης. Έχετε υπόψη ότι το ξεκλείδωμα της μονάδας θα διαρκέσει μερικά δευτερόλεπτα (περίπου δέκα δευτερόλεπτα).

Έχοντας ένα κρυπτογραφημένο ριζικό σύστημα αποτρέπει την κλοπή δεδομένων που περιέχει σε περίπτωση απώλειας ή κλοπής του μηχανήματος, ή μιας αφαιρούμενης κίνησης. Αλλά αυτό δεν θα σας προστατεύσει αν ο υπολογιστής παραμείνει σε λειτουργία και χωρίς παρακολούθηση, μόνο αν το μηχάνημα έχει απενεργοποιηθεί εντελώς!

Κατά την εγκατάσταση, η κατάτμηση του συστήματος Slint θα κρυπτογραφηθεί και επίσης η πρόσθετη κατάτμηση που μπορείτε να ζητήσετε.

Ένα διαμέρισμα συστήματος (ή root) θα ονομαστεί ως εξής: /dev/mapper/cryproot μία φορά το άνοιξε, αν έχει κρυπτογραφηθεί.

Αυτό φαίνεται από αυτήν την εντολή:

----
lsblk -lpo όνομα,fstype,σημείο ανάρτησης - grep /$
----

Ποια δίνει ένα ouptut όπως:
----
/dev/mapper/cryptroot ext4 /
----

Αυτή η εντολή:

----
lsblk -lpo όνομα,fstype,mountpoint ±grep /dev/sda3
----

δόσεις:

----
/dev/sda3             cryptoLUKS
----

/dev/sda3 είναι τώρα ένα "raw" διαμέρισμα που περιλαμβάνει την λεγόμενη "κεφαλίδα LUKS" που δεν θα χρειαστείτε ποτέ ούτε θα πρέπει ποτέ να έχετε άμεση πρόσβαση. Φιλοξενεί όλα όσα απαιτούνται για την κρυπτογράφηση ή αποκρυπτογράφηση του διαμερίσματος /dev/mapper/cryptroot, που φιλοξενεί πραγματικά τα δεδομένα σας (σε αυτό το παράδειγμα το σύστημα Slint).

[WARNING]
====
Εάν ξεχάσετε τη συνθηματική φράση όλα τα δεδομένα στη μονάδα δίσκου θα χαθούν ανεπανόρθωτα! Έτσι γράψτε ή καταγράψτε αυτό το συνθηματικό και βάλτε το ρεκόρ σε ασφαλές μέρος όσο μόλις γίνεται.

Δίσκοι πεθαίνουν. Αν συμβεί αυτό και είναι κρυπτογραφημένο τα δεδομένα σας θα χαθούν. Έτσι, τακτικά αντίγραφα ασφαλείας σημαντικά δεδομένα σας δεν είναι προαιρετικό.

Επίσης, κάντε ένα αντίγραφο ασφαλείας της κεφαλίδας luks που θα είστε σε θέση να επαναφέρετε το διαμέρισμα luks να καταστραφεί για οποιοδήποτε λόγο. Η εντολή θα μπορούσε να είναι στο παράδειγμα μας :
----
luksHeaderBackup /dev/sda3 --header-backup-file <file>
----
όπου <file> είναι το όνομα του αρχείου αντιγράφων ασφαλείας, που θα αποθηκεύσετε σε ασφαλές μέρος.

Τότε θα πρέπει να επαναφέρετε το αντίγραφο ασφαλείας, πληκτρολογήστε:
----
luksHeaderRestore /dev/sda3 --header-backup-file <file>
----

Don't να αλλάξετε το μέγεθος ενός διαμερίσματος κρυπτογραφημένης μονάδας δίσκου όπως μετά από αυτό θα ήταν οριστικά κλειδωμένο και όλα τα δεδομένα που περιέχει θα χαθούν! Αν χρειάζεστε πραγματικά περισσότερο χώρο, θα πρέπει να δημιουργήσετε αντίγραφα ασφαλείας όλων των αρχείων που θέλετε να κρατήσετε, στη συνέχεια εγκαταστήστε εκ νέου και να επαναφέρετε τα αντίγραφα ασφαλείας.

Επιλέξτε μια ισχυρή φράση πρόσβασης, έτσι ώστε θα πάρει πάρα πολύ χρόνο για έναν ληστή να ανακαλύψετε για να αξίζει τον κόπο.

Ποτέ ποτέ βιολί με τη λεγόμενη "κεφαλίδα LUKS" που βρίσκεται στην πρώτη κατάτμηση (η τρίτη, όπως π.χ. /dev/sda3 για την πρώτη κατάτμηση πάνω από το διαμέρισμα του συστήματος Slint). Πρακτικά: μην δημιουργήσετε ένα σύστημα αρχείων σε αυτό το χώρισμα, μην το κάνετε μέρος ενός RAID πίνακα και γενικά δεν γράφουν σε αυτό: όλα τα δεδομένα θα χαθούν ανεπανόρθωτα!
====

Για να αποφύγετε τις αδύναμες φράσεις πρόσβασης, ο εγκαταστάτης απαιτεί η φράση πρόσβασης να περιλαμβάνει:

. Τουλάχιστον 8 χαρακτήρες.
. Μόνο μη τονισμένα πεζά και κεφαλαία γράμματα, ψηφία από 0 έως 9, κενό και τους ακόλουθους χαρακτήρες στίξης:
+
----
 ' ! " # $ % & ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~
----
+
Αυτό εγγυάται ότι ακόμη και ένα νέο πληκτρολόγιο θα έχει όλους τους χαρακτήρες που απαιτούνται για να πληκτρολογήστε τη φράση πρόσβασης.

. Τουλάχιστον ένα ψηφίο, ένα πεζό γράμμα, ένα κεφαλαίο γράμμα και ένα χαρακτήρα στίξης.

Το GRUB υποθέτει ότι το πληκτρολόγιο "εμάς" χρησιμοποιείται όταν πληκτρολογείτε τη φράση πρόσβασης. Για το λόγο αυτό, εάν κατά τη διάρκεια της εγκατάστασης χρησιμοποιείτε άλλο χάρτη πληκτρολογίου, πριν από ζητώντας τη φράση συνθηματικού ο εγκαταστάτης θα ορίσει το χάρτη πληκτρολογίου σε "εμάς", και αφού την καταγράψουν, επαναφέρετε το παλαιότερα χρησιμοποιούμενο. Σε αυτή την περίπτωση ο εγκαταστάτης θα ορθογραφήσει επίσης κάθε πληκτρολογημένο χαρακτήρα της φράσης πρόσβασης, καθώς μπορεί να διαφέρει από εκείνη που γράφτηκε στο κλειδί.

Η εφαρμογή cryptsetup χρησιμοποιείται για την κρυπτογράφηση του δίσκου. Για να μάθετε περισσότερους τύπους μετά την εγκατάσταση: +
-----
man cryptsetup
-----
// Speakup
[[Speakup]]
==== Συντομεύσεις πλήκτρων για τον αναγνώστη οθόνης Speakup

Αυτό το κεφάλαιο προορίζεται για χρήστες που χρειάζονται αναγνώστη οθόνης αλλά δεν είναι εξοικειωμένοι με το Speakup.

Κρατήστε το numlock απενεργοποιημένο για να χρησιμοποιήσετε το Speakup.

Το πλήκτρο CapsLock χρησιμοποιείται ως πλήκτρο shift. Για παράδειγμα, το "CapsLock 4" σημαίνει: +
κρατήστε πατημένο το πλήκτρο CapsLock όπως ένα πλήκτρο shift και πατήστε 4.

 Πρώτες συνδέσεις πλήκτρων για να θυμάστε:
 PrintScreen Toggle speakup on/off.
 CapsLock F1 Speakup Help (πατήστε το πλήκτρο Space για έξοδο από τη βοήθεια).

 Συντομεύσεις πλήκτρων για να αλλάξετε τις ρυθμίσεις:
 CapsLock 1/2 Μείωση/Αύξηση της έντασης του ήχου.
 CapsLock 5/6 Μείωση/Αύξηση του ρυθμού ομιλίας.

 Βασικοί δεσμοί για να ελέγξετε την οθόνη:
 CapsLock j/k/l Πείτε Προηγούμενη/Τρέχουσα/Επόμενη λέξη.
 CapsLock k (δύο φορές) Ορθογραφική τρέχουσα λέξη.
 CapsLock u/i/o Πείτε Προηγούμενη/Τρέχουσα/Επόμενη γραμμή.
 CapsLock y Πείτε από το πάνω μέρος της οθόνης στην ανάγνωση του δρομέα.
 CapsLock p Πείτε από την ανάγνωση γραμμής δρομέα στο κάτω μέρος της οθόνης.
// First_steps
[[first_steps_after_installation]]
==== Πρώτα βήματα μετά την εγκατάσταση

Εδώ είναι οι πρώτες εργασίες που θα εκτελεστούν μετά την εγκατάσταση

Σε αυτό το έγγραφο, όλο το κείμενο μετά από ένα χαρακτήρα # είναι σχόλια από τις προτεινόμενες εντολές, για να μην πληκτρολογηθεί.

===== Αρχική ενημέρωση λογισμικού

Μετά την εγκατάσταση, το σύστημα πρέπει να ενημερωθεί για να πάρει την πιο πρόσφατη παρεχόμενη έκδοση του κάθε λογισμικού, καθώς και νέο λογισμικό που παρέχεται από την έκδοση του ISO. Αυτό είναι ιδιαίτερα απαραίτητο αν δεν υπήρχε σύνδεση δικτύου κατά την εγκατάσταση, ως τότε εγκαταστάθηκαν μόνο τα πακέτα που περιλαμβάνονταν στα μέσα διανομής και θα μπορούσαν να είναι ξεπερασμένα.

Οι περισσότερες εντολές που πληκτρολογήθηκαν κάτω από το δικαίωμα διαχείρισης αίτησης που σχετίζεται με έναν συγκεκριμένο λογαριασμό που ονομάζεται 'root', για τον οποίο έχετε καταγράψει έναν κωδικό πρόσβασης κατά την εγκατάσταση.

Για να εκδώσετε μια εντολή ως 'ρίζα', πρώτος τύπος
----
su -
----
στη συνέχεια, εκδίδει τον κωδικό πρόσβασης για το root και πατήστε Enter πριν πληκτρολογήσετε την εντολή.

Όταν τελειώσετε την έκδοση εντολών ως 'ρίζα', πατήστε Ctrl+d ή πληκτρολογήστε 'έξοδο' για να λάβετε πίσω την κατάσταση του "κανονικού χρήστη".

Εναλλακτικά, ο χρήστης που έχει εγγραφεί κατά την εγκατάσταση και τα άλλα μέλη της ομάδας "wheel" μπορούν να πληκτρολογήσουν:
----
sudo <command>
----
τότε επίσης ο κωδικός για τον root.

Για ενημέρωση, πληκτρολογήστε ως ρίζα σε μια κονσόλα ή ένα γραφικό τερματικό:
----
slapt-get --add-keys # ανακτήστε τα πλήκτρα για τον έλεγχο ταυτότητας των πακέτων
slapt-get -u # να ενημερώσετε τη λίστα των πακέτων στους καθρέπτες
slapt-get --install-set slint # να πάρει τα νέα πακέτα
slapt-get --upgrade # Πάρτε τις νέες εκδόσεις των εγκατεστημένων πακέτων
dotnew # απαριθμεί τις αλλαγές στα αρχεία ρυθμίσεων
----
Όταν εκτελείτε dotnew, αποδεχτείτε να αντικαταστήσετε όλα τα παλιά αρχεία ρύθμισης παραμέτρων με νέα. Αυτό είναι ασφαλές όπως κάνατε't κάνει οποιαδήποτε προσαρμογή ακόμα.

Εναλλακτικά, μπορείτε να χρησιμοποιήσετε αυτά τα γραφικά μπροστινά άκρα: gslapt αντί slapt-get, και dotnew-gtk αντί dotnew.

Για να μάθετε περισσότερα για το slapt-get, πληκτρολογήστε:
----
man slapt-get
----
ή ως ρίζα:
----
slapt-get --help
----
και διαβάστε το /usr/doc/slapt-get*/README.slaptgetrc.Slint

// Usage
== Χρήση επίδεσμου

Αυτό το κεφάλαιο παρουσιάζει τους τρόπους με τους οποίους μπορείτε να αλληλεπιδράσετε με το σύστημα Slint για να έχετε κάνει αυτό που θέλετε.

=== Τι είναι ένα σύστημα Slint?

Slint είναι ένα σύνολο λογισμικού που κατά προσέγγιση εμπίπτουν σε αυτές τις κατηγορίες:

* Το λειτουργικό σύστημα, από τον πυρήνα <<kernel, Linux>> και <<utilities, βοηθητικά προγράμματα>>. Δρα ως διεπαφή μεταξύ του χρήστη, των εφαρμογών και του υλικού
* Οι <<Applications, εφαρμογές>> που εκτελούν τις εργασίες που οι χρήστες θέλουν να εκπληρώσουν.

Το Slint μπορεί να χρησιμοποιηθεί σε δύο τρόπους που διακρίνονται από την εμφάνιση της οθόνης και τον τρόπο αλληλεπίδρασης με το σύστημα:

* Στη λειτουργία κειμένου πληκτρολογείτε εντολές που ερμηνεύονται από ένα <<shell, κέλυφος>>. Αυτές οι εντολές μπορούν να ξεκινήσουν ένα βοηθητικό πρόγραμμα ή μια εφαρμογή. Η λειτουργία κειμένου ονομάζεται επίσης λειτουργία <<console, κονσόλας>>. Σε αυτή τη λειτουργία η οθόνη εμφανίζει μόνο τις εντολές και την έξοδο τους σε ένα (συνήθως μαύρο) φόντο.
* Στην γραφική λειτουργία εμφανίζονται στην οθόνη γραφικά στοιχεία, όπως παράθυρα, πάνελ ή εικονίδια, που σχετίζονται γενικά με εφαρμογές ή επιχειρήσεις κοινής ωφέλειας. Ο χρήστης αλληλεπιδρά με αυτά τα στοιχεία χρησιμοποιώντας ένα ποντίκι ή ένα πληκτρολόγιο.

Οι εντολές μπορούν επίσης να πληκτρολογηθούν σε γραφική λειτουργία μέσα σε ένα παράθυρο που σχετίζεται με ένα <<terminal, τερματικό>> στο οποίο εκτελείται ένα κέλυφος.

=== Παρεχόμενα βοηθητικά προγράμματα

Πέρα από τα βοηθητικά προγράμματα που βρέθηκαν στις περισσότερες διανομές Linux, το Slint περιλαμβάνει εργαλεία που γράφονται για αυτό, κληρονόμησε από το Slackware και δανείστηκε στο Salix.

Εδώ είναι τα βοηθητικά προγράμματα που μπορείτε να χρησιμοποιήσετε για να (ξανά) ρυθμίσετε το σύστημα Slint μετά την εγκατάσταση. Η χρήση απλούστερων είναι αυτονόητη, τα περισσότερα έχουν μια συσχετιζόμενη επιλογή --help, μερικά παρουσιάζονται σε περαιτέρω λεπτομέρειες στο κεφάλαιο <<Manage_your_system,Manage your system>>.

Εκτός αν άλλως σημειώνεται αυτά τα βοηθητικά προγράμματα θα πρέπει να χρησιμοποιούνται ως ρίζα. Για να γίνει ρίζα, π.χ. να πάρει την κατάσταση 'διαχειριστή' και τα προνόμια πληκτρολογήστε "su -" τότε κωδικό πρόσβασης root's. Για να επιστρέψετε στην κανονική κατάσταση του χρήστη pres Ctrl+d ή πληκτρολογήστε έξοδο.

Εναλλακτικά μπορείτε να εκτελέσετε εντολές που χρειάζονται προνόμια ρίζας πληκτρολογώντας "sudo <command>"

Τα περισσότερα βοηθητικά προγράμματα έχουν μια γραμμή εντολών και μια γραφική έκδοση. Η έκδοση της γραμμής εντολών παρατίθεται παρακάτω. Εκτός αν ορίζεται διαφορετικά, όλες οι εντολές θα πρέπει να είναι τύποι ως root.

*General settings*

* Για τη διαχείριση χρηστών: usersetup ή gtkusersetup
* Για να αλλάξετε τη γλώσσα και την περιοχή: localesetup ή gtklocalesetup
* Για να αλλάξετε τη ρύθμιση του πληκτρολογίου και τη μέθοδο εισόδου: keyboardsetup ή gtkkeyboardsetup
* Για να ρυθμίσετε την ημερομηνία, την ώρα ή τη ζώνη ώρας: ρολόι setup και gtkclocksetup.
* Για να επιλέξετε ποιες υπηρεσίες ξεκινούν κατά την εκκίνηση: servicesetup και gtkservicesetup.
* Για να (επανα)ρυθμίσετε το δίκτυο: netsetup.
* Για να επιλέξετε να ξεκινήσετε σε λειτουργία κειμένου ή γραφικής παράστασης και στη μεταγενέστερη περίπτωση ο γραφικός διαχειριστής σύνδεσης:
* Για να επιλέξετε μια επιφάνεια εργασίας μεταξύ FVWM, i3, LXQt, MATE και WindowMaker: session-chooser (ως κανονικός χρήστης)
* Για να επιλέξετε μία από αυτές τις επιφάνειες εργασίας ή μία από τις ανεξάρτητες λειτουργίες διαχείρισης παραθύρου: xwmconfig (ως κανονικός χρήστης)
* Για να εμφανίσετε ή όχι τις εφαρμογές που αφορούν μια επιφάνεια εργασίας σε άλλες επιφάνειες: show-desktop ή hide-desktop (ως κανονικός χρήστης)
* Για να ενεργοποιήσετε ή όχι την ομιλία σε γραφική λειτουργία: orca-on ή orca-off (ως τακτικός χρήστης)
* Για να επιλέξετε και να ενεργοποιήσετε έναν αναγνώστη οθόνης κονσόλας ή να απενεργοποιήσετε όλα αυτά: speak-with
* Για να εμφανίσετε ή όχι καταχωρήσεις εκκίνησης ειδικά για το MATE και/ή LXQt σε γραφικά περιβάλλοντα: dispaly-desktop ή hide-desktop (ως τακτικός χρήστης)
* Για ενεργοποίηση ή απενεργοποίηση του emacspeak ή του speechd-el: switch-on ή switch-off (ως τακτικός χρήστης)
* Για να δείτε τη διάταξη του μενού εκκίνησης GRUB όπως θα εμφανιστεί στην επόμενη εκκίνηση: list_boot_entries
* Για να γράψετε ένα usb boot εκκίνησης, επιτρέποντας την εκκίνηση εάν αποτύχει διαφορετικά: rescuebootstick
* Για να αποθηκεύσετε/επαναφέρετε τις ρυθμίσεις: speakup-save ή speakup-restore
* Για να απαριθμήσετε τις φωνές για espeak-ng, συμπεριλαμβανομένων των mbrola: list-espeak-ng-φωνές (ως κανονικός χρήστης)
* Για να απαριθμήσετε τις κάρτες ήχου ως: list-cards (ως κανονικός χρήστης)
* Για να απαριθμήσετε τους συνθέτες ομιλίας και τις σχετικές γλώσσες που είναι διαθέσιμες μέσω του speech-dispatcher: spd-list (ως κανονικός χρήστης)
 
=== Πώς ξεκινά το Slint

Κατά την εγκατάσταση, το λογισμικό που αποστέλλεται στο ISO εγκατάστασης ή κατεβασμένο από απομακρυσμένα αποθετήρια είναι εγκατεστημένο σε μονάδα δίσκου <<drive, >>.

Κατά την εκκίνηση του Slint, το <<firmware, firmware>> πρώτα ελέγχει το υλικό και στη συνέχεια ψάχνει για ένα πρόγραμμα που ονομάζεται OS loader (συνήθως ονομάζεται φορτωτής εκκίνησης) που ξεκινάει .

Μπορεί να υπάρχουν αρκετοί φορτωτές OS στο μηχάνημα. Σε αυτή την περίπτωση το firmware επιτρέπει στο χρήστη να επιλέξει ποιος θα ξεκινήσει σε ένα μενού.

Στο Slint το λογισμικό που κάνει και να εγκαταστήσετε ένα φορτωτή εκκίνησης είναι GRUB. σχεδόν ο φορτωτής εκκίνησης που κατασκευάστηκε από το GRUB είναι επίσης ένας διαχειριστής εκκίνησης, καθώς επιτρέπει να επιλέξετε ποιο λειτουργικό σύστημα θα ξεκινήσει αν έχουν εγκατασταθεί πολλά.

Ο φορτωτής OS που κατασκευάστηκε από την GRUB μπορεί να εγκατασταθεί σε έναν τομέα εκκίνησης (σε περίπτωση Legacy εκκίνησης) ή σε ένα χώρισμα συστήματος EFI ή ESP (σε περίπτωση εκκίνησης EFI).

Ο στόχος του φορτωτή Slint είναι να ξεκινήσει το σύστημα Slint. Για να το κάνετε αυτό πρώτα φορτώνει το RAM ο <<kernel, πυρήνας>>, τότε το <<initrd, initrd>>, το οποίο με τη σειρά του προετοιμάζει το σύστημα Slint.

Στο τελευταίο βήμα αυτής της αρχικοποίησης ο χρήστης καλείται να "συνδεθεί", in other words to connect oneself to the system and take the hand on it. Για να κάνετε ότι ο χρήστης πρώτα πληκτρολογήστε ένα's όνομα χρήστη (ή όνομα σύνδεσης) και στη συνέχεια τον κωδικό πρόσβασης, από τον οποίο εγκυρότητα ελέγχεται. Το Slint όπως και άλλες διανομές Linux που είναι πολλοί χρήστες αυτό επιτρέπει σε αυτόν το χρήστη να έχει πρόσβαση σε ένα's αρχεία, αλλά όχι εκείνα των άλλων χρηστών.

Τη στιγμή της εγκατάστασης επιλέξατε να ξεκινήσετε το Slint είτε σε λειτουργία κειμένου είτε σε γραφική λειτουργία.

* Αν επιλέξατε το C για <<console, κονσόλα>> μετά την αρχικοποίηση του συστήματος πληκτρολογείτε το όνομα χρήστη (ή συνδεθείτε) τότε τον κωδικό πρόσβασής σας, κάθε εισαγωγή που επιβεβαιώνεται πατώντας το πλήκτρο Enter τότε μπορείτε να πληκτρολογήσετε εντολές.
* Εάν επιλέξετε G (γραφικά) πληκτρολογείτε τις ίδιες πληροφορίες σε έναν <<display_manager, διαχειριστή εμφάνισης>> ή διαχειριστή σύνδεσης, που στη συνέχεια ξεκινά το <<graphical_environment, γραφικό περιβάλλον>>.

Μετά την εγκατάσταση, αν μπορείτε να αλλάξετε τη λειτουργία πληκτρολόγηση ως root `login-chooser`, σε κατάσταση λειτουργίας κονσόλας καθώς και σε γραφική λειτουργία (σε ένα <<terminal, τερματικό>>). Αυτή η εντολή σας επιτρέπει να επιλέξετε `κείμενο` (συνώνυμο λειτουργίας κονσόλας), ή, για γραφική λειτουργία, μεταξύ πολλών διαχειριστών οθόνης. Η επιλογή σας θα είναι αποτελεσματική στην επόμενη εκκίνηση του υπολογιστή.

Τώρα θα παρουσιάσουμε τα γραφικά περιβάλλοντα, στη συνέχεια πώς να χρησιμοποιήσετε ένα κέλυφος.

=== Το Γραφικό Περιβάλλον

<<the_windows, The windows>> +
<<the_work_spaces,The work spaces>> +
<<the_desktop,The desktop>> +
<<the_top_panel,The top panel>> +
<<the_bottom_panel, The bottom panel>> +
<<the_slint_control_center,The Slint Control Center>> +
<<graphical_terminals,Graphical terminals>> +
<<key_bindings,Key bindings>>

Ένα πλήρες γραφικό περιβάλλον περιλαμβάνει διάφορα συστατικά, μεταξύ των οποίων ένας διαχειριστής παραθύρων που σχεδιάζει τα παράθυρα στην οθόνη που σχετίζονται με τις εφαρμογές, μετακίνηση, αλλαγή μεγέθους και κλείσιμο αυτών των παραθύρων.

Το Slint παρέχει διάφορα γραφικά περιβάλλοντα: BlackBox, Fluxbox, FVWM, i3, LXQt, MATE, TWM και WindowMaker. Είναι θέμα προτίμησης ποιο επιλέγεις.

Το LXQt και το MATE είναι πλήρεις επιφάνειες εργασίας, FVWM και WindowMaker προσφέρουν μοναδικά χαρακτηριστικά και μπορούν να επιλεγούν με το γραφικό lightdm login επίσης και να ξεκινησουν από μια κονσόλα πληκτρολογώντας "startx". Οι άλλοι είναι κυρίως διαχειριστές παραθύρων που μπορούν να ξεκινήσουν μόνο από μια κονσόλα. Όλoi σας επιτρέπουν να έχετε πρόσβαση στα έγγραφα και τις εφαρμογές σας, γενικά ανοιχτά σε ένα παράθυρο.

Μπορείτε να επιλέξετε μεταξύ FVWM, i3, LXQt, MATE και WindowMaker πληκτρολογώντας ως κανονικός χρήστης `session-chooser`. Στη γραφική λειτουργία μπορείτε επίσης να επιλέξετε οne κατά τη σύνδεση.

Για να επιλέξετε ένα από τα άλλα γραφικά περιβάλλοντα, πρέπει να χρησιμοποιήσετε την εντολή "xwmconfig".

[NOTE]
====
if you want to use i3 and need speech we recommend that you login in text mode and run **i38** before **startx**.
====

Θα περιγράψουμε τώρα εν συντομία τα στοιχεία της επιφάνειας εργασίας Mate, η οποία είναι η προεπιλογή και είναι επίσης η πιο προσιτή με ομιλία και braille.

Χρησιμοποιώντας το ποντίκι μπορείτε να ανακαλύψετε τα χαρακτηριστικά κάθε στοιχείου που κάνει ή προσομοιώνει ένα δεξί, μεσαίο ή αριστερό κλικ. Μετακινήστε ή διαγράψτε τα περισσότερα από τα συστατικά, τροποποιήστε τα και προσθέστε νέα μπορούν να γίνουν με τον ίδιο τρόπο.

Αυτά τα συστατικά μπορεί να φτάσει τη μετακίνηση του ποντικιού και επίσης μέσω συντομεύσεων πληκτρολογίου. Δηλώνουμε παρακάτω μέσα σε παρένθεση τις συντομεύσεις πληκτρολογίου που επιτρέπουν να επιτευχθεί, με άλλα λόγια να δοθεί έμφαση σε κάθε στοιχείο. Θα συνοψίσουμε επίσης τις <<key_bindings, συντομεύσεις κλειδιού>> για την επιφάνεια εργασίας Mate (χρησιμοποιώντας τον προεπιλεγμένο διαχειριστή παραθύρων Marco) και για τον διαχειριστή παραθύρων Compiz.

[TIP]
====
Μπορείτε να ανακαλύψετε τα περισσότερα από τα χαρακτηριστικά των εφαρμογών και άλλων στοιχείων του Slint με ένα κλικ δεξί, μεσαίο ή αριστερό κλικ του ποντικιού. Για παράδειγμα, κάνοντας κλικ στο panel, τη γραμμή τίτλου, τα πλήκτρα αριστερά και δεξιά του κάθε παραθύρου, ένα εικονίδιο στον πίνακα ή σε κενό χώρο της οθόνης.
====
[[the_windows]]
==== Τα παράθυρα

Ένα παράθυρο είναι μια ορθογώνια περιοχή που σχετίζεται με μια εφαρμογή. Τα Windows μπορούν να μετακινηθούν, να αλλάξουν μέγεθος, να μεγιστοποιηθούν, να αποκατασταθούν, να κλείσουν (τερματισμός της εφαρμογής που χειρίζεται) χρησιμοποιώντας το ποντίκι ή συντομεύσεις πληκτρολογίου.

[[the_work_spaces]]
==== Οι χώροι εργασίας

Για να είναι δυνατή η ομαλή λειτουργία πολλών παραθύρων, το γραφικό περιβάλλον παρέχει αρκετούς χώρους εργασίας και επιτρέπει την εναλλαγή μεταξύ τους. Κάθε χώρος εργασίας θα εμφανίζει την ίδια επιφάνεια εργασίας και πίνακες, αλλά τα παράθυρα μπορούν να τοποθετηθούν σε συγκεκριμένο χώρο εργασίας ή σε όλα αυτά. Αυτή η ρύθμιση είναι διαθέσιμη με δεξί κλικ στην επάνω άκρη του παραθύρου. Εναλλαγή σε άλλο χώρο εργασίας μπορεί να γίνει κάνοντας κλικ στη θέση του στο κάτω μέρος του πίνακα της οθόνης, στον εναλλάκτη χώρου εργασίας, όπως υποδεικνύεται παρακάτω.

[[the_desktop]]
==== Η επιφάνεια εργασίας

Η επιφάνεια εργασίας περιλαμβάνει ολόκληρη την οθόνη, στην οποία μπορούν να τοποθετηθούν άλλα στοιχεία, στην περίπτωση του Mate και όπως αποστέλλεται στο Slint μια κορυφή και ένα κάτω μέρος, και τέσσερα εικονίδια που από πάνω προς τα κάτω επιτρέπουν το άνοιγμα στα παράθυρα:

* ο ριζικός κατάλογος στον διαχειριστή αρχείων
* τον αρχικό σας κατάλογο στον διαχειριστή αρχείων
* το Κέντρο Ελέγχου Slint
* τα σκουπίδια μπορούν, όπου τοποθετούνται αρχεία που σκοπεύετε να διαγράψετε, αλλά didn't ακόμα.

Παράθυρα της εφαρμογής που αρχίζετε, όπως επίσης τοποθετείτε στην επιφάνεια εργασίας.

Mate περιλαμβάνει δύο πάνελ, η οποία παρουσιάζεται ως λεπτή ορθογώνια οριζόντια περιοχές, μία στην κορυφή και μία στο κάτω μέρος της οθόνης.

Πατώντας το Ctrl+Alt+Tab επιτρέπεται ο κύκλος μεταξύ της επιφάνειας εργασίας, της κορυφής και των κάτω πινάκων

Πατώντας το Alt+Tab επιτρέπεται ο κύκλος μεταξύ των παραθύρων στην επιφάνεια εργασίας.

[[the_top_panel]]
==== Ο επάνω πίνακας

#-#-#-#-# el_GR.HandBook.adoc:933 #-#-#-#-# Παρουσιάζει, από αριστερά προς τα δεξιά, #-#-#-#-# el_GR.HandBook.adoc:956 #-#-#-#-# Παρουσιάζει, από αριστερά προς δεξιά:

* Τρία μενού:
** Ένα μενού εφαρμογών που μπορεί να ανοίξει πατώντας Alt+F1. Από εκεί μπορείτε να ανοίξετε τα άλλα μενού χρησιμοποιώντας το δεξί βέλος. Μπορείτε να χρησιμοποιήσετε τα βελάκια για να πλοηγηθείτε σε κάθε μενού.
** Ένα μενού τοποθεσιών.
** Ένα μενού συστήματος που δίνει πρόσβαση σε ένα υπομενού προτιμήσεων, το Κέντρο Ελέγχου Mate και τα κουμπιά για να λάβετε βοήθεια σχετικά με την επιφάνεια εργασίας, κλειδώστε την οθόνη, κλείστε τη συνεδρία και τερματίστε τον υπολογιστή.
* Εφαρμογές εκτοξευτές για mate-terminal, ο διαχειριστής αρχείων caja, ο πελάτης ηλεκτρονικού ταχυδρομείου thunderbird, το πρόγραμμα περιήγησης web firefox, ο συντάκτης κειμένου Geany.
* Μια ειδοποίηση που μπορεί να συγκεντρώσει μικροεφαρμογές όπως ένας διαχειριστής Bluetooth, ένας μίκτης ήχου, ένας διαχειριστής δικτύου και ένας "διαθέσιμος" κοινοποιών.
* Ένα ρολόι και ημερολόγιο.
* Ένα κλείδωμα οθόνης.
* Ένας στενός διάλογος συνεδρίας.
* Ένας διάλογος τερματισμού.

[TIP]
====
* Για να προσαρμόσετε τον πίνακα με τις προτιμήσεις σας: κάντε δεξί κλικ σε ένα κενό χώρο στον πίνακα.
* Αν θέλετε να μετακινήσετε ένα αντικείμενο στον πίνακα: Μεσαίο κλικ στο στοιχείο, σύρετε το ποντίκι σας και θα ακολουθήσει το ποντίκι μέχρι να απελευθερωθεί το μεσαίο κουμπί.
* Για μια σχετική βοήθεια πατήστε F1
====

[[the_bottom_panel]]
==== Ο κάτω πίνακας

#-#-#-#-# el_GR.HandBook.adoc:933 #-#-#-#-# Παρουσιάζει, από αριστερά προς τα δεξιά, #-#-#-#-# el_GR.HandBook.adoc:956 #-#-#-#-# Παρουσιάζει, από αριστερά προς δεξιά:

* Μια λίστα παραθύρων που μπορεί να ρυθμιστεί με ένα δεξί κλικ στη γραμμή των τριών κάθετων κουκκίδων στην αρχή και επιλέγοντας τις προτιμήσεις. Αυτό επιτρέπει επίσης την εκκίνηση της οθόνης συστήματος σε ένα παράθυρο.
* Ένα κουμπί *εμφάνισης επιφάνειας εργασίας*. Ένα αριστερό θα ελαχιστοποιήσει ή θα αποκρύψει όλα τα παράθυρα, κάνοντας κλικ για άλλη μια φορά θα επαναφέρετε τα παράθυρα στην προηγούμενη κατάστασή τους.
* Ένας διακόπτης χώρου εργασίας, ή pager. Επιτρέπει να μεταβείτε από ένα χώρο εργασίας σε ένα άλλο και επίσης να μετακινήσετε τα παράθυρα από ένα χώρο εργασίας σε ένα άλλο με σύρσιμο και πτώση.

[[the_slint_control_center]]
==== Το Κέντρο Ελέγχου Slint

Θα ολοκληρώσουμε αυτή την εισαγωγή στη χρήση Slint's παρουσιάζοντας το Κέντρο Ελέγχου Slint. Μπορείτε να το εμφανίσετε από το μενού της εφαρμογής στον επάνω πίνακα ή κάνοντας κλικ στο εικονίδιό του στην επιφάνεια εργασίας ή πληκτρολογώντας qcontrolcenter σε ένα διάλογο "Εκτέλεση..." υψωμένο με Alt+F2

Στόχος του πίνακα ελέγχου είναι η συλλογή εφαρμογών που είναι χρήσιμες για τη διαχείριση του συστήματος, την τεκμηρίωση και τις ρυθμίσεις με συνεπή τρόπο σε όλους τους διαχειριστές παραθύρων. Κάνοντας κλικ σε μια κατηγορία στο αριστερό μενού, μπορείτε να εμφανίσετε τις αντίστοιχες εφαρμογές στο δεξί πλαίσιο. Θα τους παρουσιάσουμε σε μορφή πίνακα. Αυτό θα μας δώσει την ευκαιρία να παρουσιάσουμε τα εργαλεία διαχείρισης που έχουν ένα γραφικό περιβάλλον χρήστη.

Τα περισσότερα εργαλεία διαχείρισης πρέπει να χρησιμοποιούνται με δικαιώματα διαχείρισης. Θα σας ζητηθεί ο κωδικός πρόσβασης του λογαριασμού root για να ξεκινήσει ένα εργαλείο.

[options="autowidth"]
|====
<|**Κατηγορία** <|**Εργαλείο** <|**Σκοπός και σχόλια**
<|Εφαρμογές <|Dotnew <|Αυτό το εργαλείο σάς επιτρέπει να διαχειρίζεστε τα νέα (με το όνομα __something.new__ εξ ου και το όνομα του εργαλείου) έναντι των παλαιών αρχείων διαμόρφωσης αφού έχετε αναβαθμίσει ορισμένα πακέτα. Είναι καλή συνήθεια να τρέχεις αν μετά από αναβάθμιση. Θα σας πει εάν υπάρχει κάτι να φροντίσετε και στη συνέχεια θα σας παρουσιάσει μια επιλογή ενεργειών.
<|Εφαρμογές <|Gslapt Package Manager <|Το Gslapt είναι ένα γραφικό front-end για το slapt-get. Είναι ένα εύχρηστο εργαλείο για την εκτέλεση <<software_management,software management in Slint>>. Σας επιτρέπει να αναζητήσετε, να εγκαταστήσετε, να αφαιρέσετε, να αναβαθμίσετε και να διαμορφώσετε πακέτα λογισμικού.
<|Εφαρμογές <|Sourcery SlackBuild Manager <|Το Source είναι ένα γραφικό front-end για το slapt-src. Σας επιτρέπει να αναζητήσετε σενάρια SlackBuilds που μπορεί στη συνέχεια να χρησιμοποιήσει για να αυτοματοποιήσει τη διαδικασία κατασκευής και εγκατάστασης πακέτων λογισμικού. Μπορεί επίσης να αφαιρέσει και να επανεγκαταστήσει πακέτα στο σύστημά σας.
<|Εφαρμογές <|Εύρεση εφαρμογών <|Βρείτε και εκκινήστε τις εφαρμογές που είναι εγκατεστημένες στο σύστημά σας. Το πεδίο αναζήτησης είναι πολύ βολικό για την εύρεση εφαρμογών σε σύγκριση με τη μη αυτόματη αναζήτηση στο μενού της εφαρμογής.
<|Πληροφορίες <|Ιστότοπος SlackDocs <|Τα έγγραφα σε αυτό το wiki προορίζονται κυρίως για έναν χρήστη του Slackware, αλλά πολλά από αυτά είναι χρήσιμα για έναν χρήστη του Slint. **Προσοχή:** Ορισμένα από τα αναφερόμενα εργαλεία, όπως το slackpkg, **δεν** πρέπει να χρησιμοποιούνται στο Slint.
<|Πληροφορίες <|Τεκμηρίωση Slackware <|Αυτή η τεκμηρίωση μπορεί επίσης να είναι χρήσιμη για τους χρήστες του Slint. Το Slint βασίζεται στο Slackware.
<|Πληροφορίες <|Οθόνη συστήματος MATE <|Αυτό το εργαλείο εμφανίζει πληροφορίες σχετικά με το σύστημα, όπως τη διαδικασία, τη χρήση πόρων (RAM, CPU, κίνηση δικτύου) και τη χρήση συστημάτων αρχείων.
<|Πληροφορίες <|Τεκμηρίωση Slint <|Αυτό παρέχει τοπική πρόσβαση σε έγγραφα που είναι επίσης διαθέσιμα στον ιστότοπο του Slint.
<|Πληροφορίες <|Φόρουμ Slint <|Τα άτομα των οποίων η μητρική γλώσσα δεν είναι τα Αγγλικά μπορούν επίσης να δημοσιεύουν δημοσιεύσεις στα τοπικά φόρουμ του Salix.
<|Πληροφορίες <|Ιστότοπος Slint <|Ο ιστότοπος Slint παρέχει τεκμηρίωση, συνδέσμους και έναν τρόπο εύρεσης των ISO και των πακέτων.
<|Πληροφορίες <|Πληροφορίες συστήματος <|Αυτό το εργαλείο συλλέγει πληροφορίες σχετικά με τον υπολογιστή σας, όπως τις συνδεδεμένες συσκευές του (εσωτερικές και εξωτερικές), και τις εμφανίζει όλες σε ένα μέρος. Μπορεί επίσης να κάνει σήμανση πάγκου συστήματος.
<|Σύστημα <|Εμφάνιση μενού εκκίνησης <|Εμφάνιση της διάταξης του μενού εκκίνησης όπως θα παρουσιαστεί στην επόμενη εκκίνηση
<|Σύστημα <|Ρολόι συστήματος <|Αυτό το εργαλείο σας επιτρέπει να ρυθμίσετε το ρολόι του συστήματος.
<|Σύστημα <|Πληκτρολόγιο <|Αυτό το εργαλείο σάς επιτρέπει να ρυθμίσετε τη διάταξη του πληκτρολογίου.
<|Σύστημα <|Γλώσσα συστήματος <|Αυτό το εργαλείο σάς επιτρέπει να ορίσετε τις τοπικές ρυθμίσεις του συστήματος (γλώσσα και γεωγραφικές ιδιαιτερότητες), έτσι ώστε οι εφαρμογές που χρησιμοποιείτε να εμφανίζουν πληροφορίες σε αυτήν την τοπική ρύθμιση (εάν είναι διαθέσιμη).
<|Σύστημα <|Ρολόι συστήματος <|Αυτό το εργαλείο σάς επιτρέπει να ορίσετε τη ζώνη ώρας, να επιλέξετε εάν το ρολόι θα πρέπει να συγχρονιστεί με διακομιστές Διαδικτύου (αυτό συνιστάται, αλλά φυσικά χρειάζεται σύνδεση στο Διαδίκτυο) και αν όχι, ορίστε την ημερομηνία και χρόνος.
<|Σύστημα <|Υπηρεσίες συστήματος <|Αυτό το εργαλείο σάς επιτρέπει να επιλέξετε ποιες υπηρεσίες θα ενεργοποιηθούν κατά την εκκίνηση. Για παράδειγμα, το Bluetooth, ο διακομιστής εκτύπωσης CUPS ή ένας διακομιστής web. Χρησιμοποιήστε το για να αλλάξετε τις προεπιλεγμένες ρυθμίσεις μόνο εάν γνωρίζετε τι κάνετε.
<|Σύστημα <|Χρήστες και Ομάδες <|Αυτό το εργαλείο σάς επιτρέπει να προσθέτετε, να αφαιρείτε και να δημιουργείτε λογαριασμούς και ομάδες χρηστών. Είναι κυρίως χρήσιμο σε συστήματα πολλών χρηστών.
<|Σύστημα <|GUEFI Boot Manager <|Αυτό το εργαλείο είναι μια γραφική διεπαφή της εντολής efibootmanager. Επιτρέπει την επεξεργασία του μενού εκκίνησης του υλικολογισμικού EFI με ενέργειες όπως προσθήκη, αφαίρεση στοιχείων ή αλλαγή σειράς στοιχείων μενού.
<Σύστημα <|Rescue boot stick <|Αυτό το εργαλείο επιτρέπει να τοποθετήσετε σε ένα USB stick ό,τι χρειάζεται για την εκκίνηση του Slint, εάν δεν είναι δυνατό με τον συνήθη τρόπο

|====

[[graphical_terminals]]
==== Τερματικά

Μπορείτε να πληκτρολογήσετε εντολές σε γραφική λειτουργία όπως στη λειτουργία κονσόλας, αν ανοίξετε ένα παράθυρο με ένα τερματικό σε αυτό. Στο Mate μπορείτε απλά να πατήσετε Ctrl+Alt+t, ή κάντε κλικ στο στο εικονίδιο mate-terminal στον επάνω πίνακα, ή ανοίξτε ένα διάλογο "Εκτέλεση... " πατώντας Alt+F2 και στη συνέχεια πληκτρολογώντας `mate-terminal` στο μικρό παράθυρο που ανοίγει.

Οι περισσότερες από τις παρακάτω πληροφορίες σχετικά με τη γραμμή εντολών και το κέλυφος στη λειτουργία Κονσόλας ισχύουν επίσης για την πληκτρολόγηση εντολών σε ένα τερματικό. Μπορείτε να κλείσετε mate-τερματικό πατώντας Alt+F4 όπως με οποιοδήποτε άλλο παράθυρο.

[[key_bindings]]
==== Συντομεύσεις πλήκτρων

Παρουσιάζουμε εδώ τις προεπιλεγμένες συνδέσεις πλήκτρων για τον διαχειριστή παραθύρων Compiz και την επιφάνεια εργασίας Mate, και πώς να τις προσαρμόσετε.

[NOTE]
====
Όταν ένα δεσμευτικό κλειδί περιλαμβάνει ένα ή περισσότερα σύμβολα *+* , πατήστε παρατεταμένα από αριστερά προς τα δεξιά τα πλήκτρα πριν το τελευταίο σαν πλήκτρο `Shift` , στη συνέχεια πατήστε το τελευταίο πλήκτρο.
====
===== Συντομεύσεις πλήκτρων για την επιφάνεια εργασίας Mate

Όταν χρησιμοποιείτε το Mate στο Slint, μερικές συντομεύσεις πλήκτρων είναι ίδιες είτε με τους διαχειριστές παραθύρων Marco ή Compiz. Παρακάτω αναφέρονται:
----
Κύκλος Alt+Tab μεταξύ παραθύρων
Κύκλος Shift+Alt+Tab πίσω μεταξύ παραθύρων
Έλεγχος + Κύκλος Alt+Tab μεταξύ πινάκων και επιφάνειας εργασίας
Shift+Control+Alt+Tab Κύκλος προς τα πίσω μεταξύ πινάκων και επιφάνειας εργασίας
----
Μόλις είστε σε ένα γραφικό περιβάλλον, μπορείτε να κάνετε εναλλαγή μεταξύ αυτού και μιας κονσόλας. Ας πούμε ότι θέλετε να χρησιμοποιήσετε tty2 (tty1 ενώ είστε απασχολημένος): Πατήστε ` Ctrl + Alt + F2 `, στη συνέχεια συνδεθείτε. +
Πατήστε ` Alt + F7 ' για να επιστρέψετε στο γραφικό περιβάλλον.

Οι ίδιες γενικές συντομεύσεις πλήκτρων χρησιμοποιούνται σε όλα τα γραφικά περιβάλλοντα, με λίγες εξαιρέσεις, το Mod1 είναι γενικά το αριστερό πλήκτρο Alt: +
----
Mod1+F1 αυξάνει το μενού εφαρμογής του πίνακα.
Το Mod1+F2 δημιουργεί ένα διάλογο 'run...', αλλά στο Fluxbox (ξεκινά το lxterminal αντίστοιχα).
----
Επίσης στο Fluxbox:
----
Mod1+F3 restarts Fluxbox.
Το Mod1+F4 κλείνει το εστιασμένο παράθυρο.
----

Στο Mate, οι χρήστες με μειωμένη όραση μπορούν να χρησιμοποιήσουν τον διαχειριστή παραθύρων Compiz αντί αυτού ή τον Marco που είναι η προεπιλογή.

Ως τακτικός χρήστης, πληκτρολογήστε:
----
gsettings set org.mate.session.required-components windowmanager compiz
----
Για να επιστρέψετε στο μάρκο:
----
gsettings set org.mate.session.required-components windowmanager marco
----
Αυτή η ρύθμιση θα τεθεί σε ισχύ στην επόμενη έναρξη μιας συνεδρίας Mate.

Ή για να κάνετε την αλλαγή μόνο για τον τρέχοντα τύπο συνεδρίας:
----
compiz --replace, &
----
and to go back to marcomarco:
----
marco -- replace &
----
Η αντικατάσταση θα είναι αποτελεσματική αμέσως

Αυτή η ρύθμιση είναι επίσης διαθέσιμη γραφικά από mate-tweak, στην κατηγορία Windows.

Μπορείτε να αποκτήσετε πρόσβαση σε συγκεκριμένες ρυθμίσεις Compiz απλά πληκτρολογήστε:
----
ccsm &
----
===== Συντομεύσεις πλήκτρων για τον διαχειριστή παραθύρων Compiz

Στις προεπιλεγμένες ρυθμίσεις που αναφέρονται παρακάτω τα πλήκτρα ή τα πλήκτρα του ποντικιού ονομάζονται ως εξής:

Super: Κλειδί των Windows στα περισσότερα πληκτρολόγια +
Button1: Αριστερό κουμπί ποντικιού (αν χρησιμοποιείται με το δεξί χέρι) +
Κουμπί2: Κέντρο Ποντικιού, ή κάντε κλικ με τον τροχό κύλισης) +
Κουμπί3: Δεξί κουμπί Ποντικιού (αν χρησιμοποιείται με το δεξί χέρι) +
Κουμπί4: Κύλιση Τροχός Επάνω +
Κουμπί5: Κύλιση Τροχού Κάτω Κουμπί6: (Δεν ξέρω, Νόμιζα ότι ήταν σε ποντίκια για gamers) +

Οι προεπιλεγμένες ρυθμίσεις που παρατίθενται παρακάτω ανά κατηγορία μπορούν να αλλάξουν από το CCSM. Δίνουμε το σύντομο όνομα του πρόσθετου μεταξύ των αγκύλων των τετραγώνων.

. Κατηγορία Γενικά
+
[core] Γενικές επιλογές, καρτέλα "δεσμοί πλήκτρων": +
close_window_key = Alt + F4 +
raise_window_button = Control + Button6 +
lower_window_button = Alt + Button6 +
minimize_window_key = Alt + F9 +
maximize_window_key = Alt + F10 +
unmaximize_window_key = Alt + F5 +
window_key = Alt + F5  +
 window_menu_key = Alt + πλήκτρο +
window_button = Alt + Button3 +
show_desktop_key = Control + Alt + d +
toggle_window_shaded_key = Control + Alt + s +
+
[matecompat] Mate Συμβατότητα +
main_menu_key = Alt+F1 +
run_key = Alt+F2 +

. Προσβασιμότητα Κατηγορίας
+
[addhelper] Dim Ανενεργό (λιγότερο φως σε μη εστιασμένα παράθυρα) + toggle_key = Super + p +
+
[colorfilter] (χρώμα φίλτρου για σκοπούς προσβασιμότητας) +
toggle_window_key = Super + Alt + f +
toggle_screen_key = Super + Alt + d +
switch_filter_key = Super + Alt + s +
+
[ezoom] Ενισχυμένο Zoom Desktop +
zoom_in_button = Super + Button4 +
zoom_out_button = Super + Button5 +
zoom_box_button = Super + Button2 (zoom out to go back to normal) +
+
[neg] Αρνητική (εναλλαγή αντίστροφων χρωμάτων του παραθύρου ή της οθόνης) +
window_toggle_key = Super+n +
screen_toggle_key = Super+m +
+
[obs] Ρυθμίσεις αδιαφάνειας, φωτεινότητας και κορεσμού +
opacity_increase_button = Alt+Button4 +
opacity_decrease_button = Alt+Button5 +
+
[showmouse] (Αύξηση της ορατότητας του δείκτη του ποντικιού) +
initiate = Super+k +

. Διαχείριση Παραθύρων Κατηγοριών
+
[move] Μετακίνηση παραθύρου +
initiate_button = Alt+Button1 (κρατήστε πατημένο το κουμπί 1 ενώ μετακινείτε το ποντίκι) +
initiate_key = Alt+F7 (Esc to stop moving) +
+
[resize] Αλλαγή μεγέθους παραθύρου +
initiate_button = Alt+Button 2 (κρατήστε πατημένο το κουμπί 2 ενώ μετακινείτε το ποντίκι) +
initiate_key = Alt+F8 (Esc to stop moving) +
+
[switcher] Εναλλαγή εφαρμογής (εναλλαγή μεταξύ παραθύρων ή πινάκων και
                                 της επιφάνειας εργασίας) +
next_window_key = Alt+Tab (κύκλος μεταξύ παραθύρων) +
prev_window_key = Shift+Alt+Tab +
next_panel_key = Control+Alt+Tab (κύκλος μεταξύ πινάκων και desktop) +
prev_panel_key = Shift+Control+Alt+Tab +

===== Πώς να προσθέσετε μια προσαρμοσμένη σύνδεση κλειδιών για το Mate.

Let's take an example: we want that Alt+F3 starts firefox. πληκτρολογήστε σε ένα τερματικό ή σε εντολή Run (σφυρήλατο πατώντας Alt+F2):
----
ιδιότητες mate-keybinding-
----
Στο νέο παράθυρο μπορείτε να χρησιμοποιήσετε το πάτημα των κάτω και πάνω πλήκτρων βέλους για να πλοηγηθείτε στη λίστα με τις υπάρχουσες συνδέσεις πλήκτρων.

Για να ορίσετε ένα νέο πλήκτρο σύνδεσης, πατήστε Καρτέλα δύο φορές για να βάλετε το δρομέα στο Add, στη συνέχεια, πατήστε Enter. Στο μικρό παράθυρο διαλόγου έφερε επάνω πληκτρολογήστε το όνομα του προσαρμοσμένου κλειδιού σύνδεσης, όπως firefox, πατήστε Tab, πληκτρολογήστε το όνομα στη σχετική εντολή , σε αυτή την περίπτωση το firefox, στη συνέχεια, πατήστε Καρτέλα δύο φορές στο βάλτε το δρομέα στο Εφαρμογή και πατήστε Enter.

Για να ενεργοποιήσετε τη νέα σύνδεση πλήκτρων, πλοηγηθείτε μέχρι να τη βρείτε στο κάτω μέρος της λίστας, κάντε κλικ στο πλήκτρο Alt+F3.

Την επόμενη φορά που θα πατήσετε το Alt+F3 που θα ξεκινήσει το firefox

=== Το κέλυφος

NOTE: Αυτό το κεφάλαιο είναι μια σύντομη εισαγωγή. Περισσότερες σε βάθος πληροφορίες παρέχονται στο έγγραφο https://slint.fr/doc/shell_and_bash_scripts.html[Σενάρια Shell και bash], κυρίως δανεισμένες από SUSE.

Όταν ο υπολογιστής ξεκινά σε λειτουργία κονσόλας, αφού συνδεθεί πληκτρολογώντας το όνομα χρήστη και τον κωδικό πρόσβασης, το <<shell,shell>> εμφανίζει μια "προτροπή" όπως αυτή που ακολουθεί: +
`didier@darkstar:~$` +
Σε αυτό το παράδειγμα:

* `didier` είναι το όνομα χρήστη
* `σκούρο αστέρι` το όνομα του μηχανήματος
* το tilde `~` αντιπροσωπεύει τον αρχικό κατάλογο του χρήστη, σε αυτό το παράδειγμα `/home/didier`
* το σύμβολο του δολαρίου `$` δείχνει ότι ο χρήστης είναι ένα "κανονικό" όχι ένα "σούπερ χρήστη" (βλ. παρακάτω).

Ο δρομέας τοποθετείται στη συνέχεια μετά την προτροπή.

Ο χρήστης μπορεί τώρα να πληκτρολογήσει μια εντολή στη γραμμή (εξ ου και το όνομα "γραμμή εντολών") και να επιβεβαιώσει το πάτημα Enter. Το κέλυφος then analyzes the command and execute it if valid, else output a message like for instance "command not found". Μπορείτε να επεξεργαστείτε την εντολή πριν πατήσετε το Enter χρησιμοποιώντας τα αριστερά και δεξιά βέλη και τα πλήκτρα Backspace, Home, End and Del.

Κατά την εκτέλεσή της, οι εντολές μπορούν να εμφανίσουν μια έξοδο στην οθόνη ή όχι. Σε όλες τις περιπτώσεις μετά την εκτέλεσή της, η προτροπή θα εμφανιστεί ξανά σε μια νέα γραμμή, που σημαίνει ότι το κέλυφος περιμένει να πληκτρολογηθεί η επόμενη εντολή.

Για να λειτουργήσει αυτό, ο χρήστης πρέπει να γνωρίζει ποιες εντολές είναι διαθέσιμες και η σύνταξή τους. Μερικές εντολές εκτελούνται από το ίδιο το κέλυφος, άλλες ξεκινούν εξωτερικά προγράμματα. Θα δώσει παρακάτω πολλά παραδείγματα εντολών, περισσότερα παρατίθενται σε https://slint.fr/doc/shell_and_bash_scripts.html[Σενάρια Shell και bash]

Υπάρχουν πολλά κελύφη διαθέσιμα για να διαλέξετε. Στο Slint το κέλυφος που χρησιμοποιείται από προεπιλογή ονομάζεται *bash*.

Για να επιτρέψετε την εκτέλεση πολλών προγραμμάτων ταυτόχρονα το Linux παρέχει αρκετές "εικονικές κονσόλες" που μοιράζονται το ίδιο πληκτρολόγιο και οθόνη, αριθμημένες από ένα. Αρχικά το σύστημα ξεκινά στην κονσόλα (ή στο εικονικό τερματικό) νούμερο ένα ονομάζεται επίσης *tty1* (το όνομα tty είναι μια συντομογραφία του "τηλετύπου"). Από εκεί ο χρήστης μπορεί να μεταβεί σε άλλη κονσόλα ή tty; για παράδειγμα μεταβείτε στον αριθμό αριθμό δύο πατώντας Alt+F2, όπου ένα άλλο κέλυφος θα ζητήσει και πάλι το όνομα χρήστη's και τον κωδικό πρόσβασης. Για να επιστρέψετε σε tty1, απλά πατήστε Alt+F1. Από προεπιλογή στο Slint έξι tty είναι διαθέσιμα, αλλά αυτό μπορεί να αλλάξει την επεξεργασία του αρχείου /etc/inittab.

Όταν το κέλυφος χρησιμοποιείται σε ένα γραφικό περιβάλλον (σε ένα γραφικό τερματικό), συμπεριφέρεται με τον ίδιο τρόπο, αλλά η προτροπή είναι ελαφρώς διαφορετική, όπως φαίνεται παρακάτω: +
`didier[~]$` +

Μπορείτε να μεταβείτε μεταξύ της κονσόλας και ενός γραφικού περιβάλλοντος:

* Από το γραφικό περιβάλλον πατώντας για παράδειγμα Ctrl+Alt+F3 για να μεταβείτε στο tty3. Την πρώτη φορά που θα πάτε σε ένα Όμορφο θα πρέπει να πληκτρολογήσετε το όνομα χρήστη και τον κωδικό πρόσβασής σας.
* Από μια κονσόλα ή Όμορφο πάτημα Alt+F7 αν το γραφικό περιβάλλον εκτελείται ήδη, αλλιώς πληκτρολογώντας `startx` για να ξεκινήσετε.

==== Πληκτρολογώντας εντολές ως root

*root* is the conventional name of the "super user" which have all rights to do administrative tasks, including those that could harm or even destroy the system.

Μπορείτε (αλλά αυτό δεν συνιστάται για αρχάριους) συνδεθείτε άμεσα ως root. Για να κάνετε αυτόν τον τύπο πληκτρολογήστε *root* ως χρήστης, και κατόπιν τον κωδικό πρόσβασης του root. Για να σας ενημερώσουμε (και να σας προειδοποιήσουμε για τους σχετικούς κινδύνους και ευθύνες), η προτροπή θα μοιάζει κάπως έτσι: +
*root@darkstar:s~#* +
ο χαρακτήρας # (σύμβολο αριθμού, επίσης συνήθως ονομάζεται hash) δείχνει ότι οι εντολές θα πληκτρολογηθούν ως root (όχι ως τακτικός χρήστης), με τα σχετικά δικαιώματα, αλλά και κινδύνους και ευθύνες.

Αν έχετε ήδη συνδεθεί ως κανονικός χρήστης, μπορείτε να πληκτρολογήσετε: +
* su - * +
και στη συνέχεια να πατήσετε Enter. Σε αυτή την εντολή, ` su ` (που σημαίνει "Super User") είναι το όνομα της εντολής, και ο χαρακτήρας *-* (hyphen-minus, επίσης με το όνομα μείον) λέει ότι ανοίγετε ένα "κέλυφος σύνδεσης": θα σας ζητηθεί πρώτα ο κωδικός πρόσβασης root, στη συνέχεια να κατευθυνθείτε στον αρχικό κατάλογο /home/root, σαν να είχατε συνδεθεί ως root κατά την εκκίνηση. Αυτό θα αποτρέψει την ακούσια εγγραφή αρχείων στον αρχικό σας κατάλογο ως τακτικός χρήστης (/home/didier στο παράδειγμα) που προκαλούν προβλήματα αργότερα.

Ο τακτικός χρήστης που καταχωρήθηκε κατά την εγκατάσταση και άλλοι χρήστες της ομάδας 'wheel' μπορεί επίσης να πληκτρολογεί εντολές που προορίζονται για τον root πριν από το όνομα της εντολής με το 'sudo' έτσι για παράδειγμα: +
* sudo update-grub *

=== Πώς να επιλύσετε ζητήματα αποκλεισμού

Με το "μπλοκάρισμα ζητήματος" εννοούμε "ένα ζήτημα που αποτρέπει τη χρήση του Slint" όπως:

* Το σύστημα αποτυγχάνει να εκκινήσει.
* Το σύστημα μπότες, αλλά η σειρά εκκίνησης διακόπτεται πριν από την ολοκλήρωση. Αυτό μπορεί να συμβεί για παράδειγμα εάν το διαμέρισμα του ριζικού συστήματος μπορεί't να τοποθετηθεί λόγω σφάλματος στο /etc/fstab, ένα κατεστραμμένο ριζικό σύστημα αρχείων ή ένα πρόσθετο πυρήνα που λείπει για να προσαρτήσετε την κατάτμηση root, or the system bootsμπότες successfully but you don't remember the password for root.

Αν το σύστημα αποτύχει εντελώς να ξεκινήσει, δοκιμάστε κάθε μία από τις παρακάτω λύσεις σε σειρά, μέχρι να δουλέψει.

. Αν αυτό συμβεί μετά την αναβάθμιση του πυρήνα, δοκιμάστε τη δεύτερη καταχώρηση εκκίνησης αντί για την πρώτη.
. Προσπαθήστε να εκκινήσετε από το ραβδί εκκίνησης διάσωσης που έχετε ζητήσει στο τέλος της εγκατάστασης.
. Μετάβαση σε Slint για να το επισκευάσει, όπως εξηγείται παρακάτω.

Μπορείτε πάντα να λάβετε βοήθεια μέσω ηλεκτρονικού ταχυδρομείου slint@freelists.org παρέχοντας όλες τις πληροφορίες που θα μπορούσαν να βοηθήσουν στη διερεύνηση του προβλήματος. Αν δεν γίνει ήδη, εγγραφείτε πρώτα στη λίστα στέλνοντας email στο slint-request@freelists.org με το θέμα 'εγγραφή', στη συνέχεια, απαντήστε στο email που θα λάβετε. Μόνο αν έχετε κάποιο πρόβλημα χρησιμοποιώντας email, ζητήστε βοήθεια στο IRC κανάλι #slint, στο διακομιστή irc.libera.chat και μείνετε στο κανάλι μέχρι κάποιος να απαντήσει.

Τώρα θα εξηγήσουμε πώς να μεταβείτε στο Slint για να το επισκευάσετε.

<<Start_the_installer,Start the installer and identify Slint's root partition>> +
<<Issue_the_needed_commands,Issue the needed commands to jump into Slint>>. +
<<Repair_Slint,Repair Slint from Slint.>>

[[Start_the_installer]]
==== Εκκινήστε το πρόγραμμα εγκατάστασης και προσδιορίστε το ριζικό διαμέρισμα του Slint

Αν η ακολουθία εκκίνησης διακοπεί, μεταβείτε στο Slint από τον εγκαταστάτη του για να προσπαθήσετε να λύσετε το πρόβλημα. Τοποθετήστε ή συνδέστε τα μέσα εγκατάστασης (USB stick ή DVD όπου έχετε γράψει το ISO) και ακολουθήστε τις παρακάτω οδηγίες.

. Ξεκινήστε τον εγκαταστάτη.
. Μόλις συνδεθείτε ως root, για να απαριθμήσετε τους δίσκους και τα διαμερίσματα, πληκτρολογήστε:
+
----
lsblk -lpo name,size,fstype
----
. Βρείτε στην έξοδο το όνομα του ριζικού διαμερίσματος Slint, ελέγχοντας το μέγεθος και τον τύπο του συστήματος αρχείων, με ετικέτα FSTYPE.
. Προσάρτηση αυτού του διαμερίσματος
+
----
mount /dev/sda3 /mnt
----
+
[NOTE]
====
Αν το ριζικό σύστημα αρχείων Slint είναι btrfs (όπως υποδεικνύεται από την έξοδο του "lsblk") θα πρέπει να το προσαρτήσετε χρησιμοποιώντας τις επιλογές που αναφέρονται στο /etc/fstab.

Σε αυτή την περίπτωση πρέπει να χρησιμοποιήσετε τις ίδιες επιλογές όπως στο Slint σε btrfs, συνεπώς πληκτρολογήστε:
----
mount /dev/sda3 /mnt -o subvol=/@,compress=zstd:3
----
====
. Ελέγξτε ότι το διαμέρισμα είναι το σωστό. Για παράδειγμα, αν είναι /dev/sda3, πληκτρολογήστε:
+
----
cat /etc/mnt/etc/slint-version
----
+
Υποθέτοντας ότι έχετε εγκαταστήσει το Slint64-15.0 η έξοδος πρέπει να είναι: *Slint 15.0*
+
Αν η έξοδος είναι "αρχείο δεν βρέθηκε" η κατάτμηση δεν είναι αυτή που αναζητήσατε. Σε αυτή την περίπτωση μόνο, πληκτρολογήστε:
+
----
umount /mnt
----
+
τότε δοκιμάστε ένα άλλο, πηγαίνοντας πίσω στη λίστα δίσκων και κατατμήσεων.

[[Issue_the_needed_commands]]
==== Εκτελέστε τις απαραίτητες εντολές για να μεταβείτε στο Slint

. προσαρτήστε τα συστήματα αρχείων /proc/sys and /dev πληκτρολογώντας:
+
----
mount -B /dev /mnt/dev
mount -B /proc /mnt/proc
mount -B /dev /mnt/sys
----
+
. Εκτελέστε την επόμενη εντολή για να "μεταβείτε στο" Slint " και να συνδέσετε όλες τις συσκευές που αναφέρονται στο αρχείο /etc/fstab:
+
----
chroot /mnt
mount -a
----

[[Repair_Slint]]
==== Επισκευή Slint από το Slint

Από το Slint μπορείτε να τροποποιήσετε το σύστημα για να λύσετε το ζήτημα. Εδώ είναι μερικά παραδείγματα:

* Εκτέλεση "update-grub". +
* Εκτέλεση "grub-emu" ή "list_boot_entries" +
* Επανεγκαταστήστε το GRUB χρησιμοποιώντας την εντολή "grub-install drivename", drivename είναι η μονάδα δίσκου όπου θα εγκατασταθεί το Slint. +
* Πληκτρολογήστε "passwd" για να αλλάξετε τον κωδικό πρόσβασης για root. +
* Κατάργηση, εγκατάσταση ή αναβάθμιση πακέτων.

. Όταν τελειώσετε, αφαιρέστε τα μέσα εγκατάστασης και πληκτρολογήστε:
+
----
έξοδος
επανεκκίνηση
----

[[Accessibility]]
== Προσβασιμότητα

Αν επιλέξατε να κρατήσετε ομιλία όταν ρωτήσετε στην αρχική εγκατάσταση, θα ενεργοποιηθεί από την εκκίνηση σε μια κονσόλα όπως σε γραφικά περιβάλλοντα.

=== Χρησιμοποιήστε Slint με braille

Slint περιλαμβάνει το λογισμικό brltty για να χειριστεί οθόνες braille.

Οι ρυθμίσεις σας, που έγιναν πριν από την εκκίνηση στη γραμμή εντολών ή αργότερα, καταγράφονται στο εγκατεστημένο σύστημα στο /etc/brltty.conf.

Ένα ολοκληρωμένο εγχειρίδιο για brltty είναι διαθέσιμο στα αγγλικά, Γαλλικά και Πορτογαλικά σε διάφορες μορφές, συμπεριλαμβανομένου απλού κειμένου (txt) σε αυτό το URL: https://mielke.cc/brltty/doc/Manual-BRLTTY/

Εάν το braille δεν ήταν ενεργοποιημένο κατά την εγκατάσταση ή έχει απενεργοποιηθεί, για να το ενεργοποιήσετε αυτό:

. Κάνε το /etc/rc.d/rc.brltty εκτελέσιμη πληκτρολόγηση ως root:
+
----
chmod 755 /etc/rc.d/rc.brltty
----
. Κάνε τον εαυτό σου μέλος της ομάδας braille, πληκτρολογώντας ως ρίζα:
+
----
usermod -G braille -a όνομα χρήστη
----
+
Στην παραπάνω εντολή, αντικαταστήστε το όνομα χρήστη με το όνομα σύνδεσής σας.

Για να απενεργοποιήσετε τον τύπο braille ως root:
----
chmod 644 /etc/rc.d/rc.brltty
----

=== Ομιλία σε γραφικά περιβάλλοντα

Ως μια ομιλία υπενθύμισης σε γραφικά περιβάλλοντα με χρήση της συσκευής ανάγνωσης οθόνης Orca είναι ενεργοποιημένη η πληκτρολόγηση:
----
orca-on
----

Για να μάθετε πώς να χρησιμοποιήσετε το Orca, συμπεριλαμβανομένων των συγκεκριμένων δεσμών πλήκτρων, πληκτρολογήστε:
----
άνδρας όρκα
----

Εν συντομία, σε ένα γραφικό περιβάλλον:
----
Insert+Space: display the Orca Preferences dialog.
Insert+S: activate or deactivate the vocal synthesis.
Insert+H: activate the learning mode. In this mode:
   Press a key to hear its function
   F1: to hear the documentation of the screen reader
   F2: list the keyboard shortcuts for Orca
   F3: list the keyboard for the current application
   Esc: end of the learning mode
----

=== Φωνές και TTS στο Slint.

Μετά την TTS (Κείμενο σε Συνθέτες Ομιλίας) αποστέλλονται στο Slint64-15.0.2, το καθένα με μια σειρά από φωνές, δηλαδή: +
espeak-ng +
flite +
pico +
mbrola +
RHVoice +

Τις περισσότερες φορές αυτές οι TTS και οι σχετικές φωνές και γλώσσες είναι υπό τη διαχείριση του λόγου μέσω των λεγόμενων "ενοτήτων" (περίπου, ένα πρόσθετο σχετίζεται με ένα TTS).

Η προσαρμοσμένη λίστα spd-list χρησιμότητας μπορεί να απαντήσει σε αρκετές ερωτήσεις σχετικά με τους συνθέτες, φωνές και γλώσσες. Πληκτρολογώντας spd-list εμφανίζει αυτό:
----
Αυτό το σενάριο εμφανίζει γλώσσες και συνθέτες διαθέσιμες για εφαρμογές
βασιζόμενοι στον Αποστολέα Ομιλίας, όπως Orca ή ομιλία επάνω. Κάθε εντολή παρακάτω απαντά στην ερώτηση μετά από αυτό.
Μην πληκτρολογήσετε τα εισαγωγικά γύρω από την εντολή.
"/usr/bin/spd-list" χρήση?
"/usr/bin/spd-list -s" διαθέσιμοι συνθέτες?
"/usr/bin/spd-list -l" διαθέσιμοι κωδικοί γλωσσών?
"/usr/bin/spd-list -ls <synthesizer>" γλώσσες διαθέσιμες για αυτόν τον συνθέτη?
"/usr/bin/spd-list -sl <language code>" συνθέτες που παρέχουν φωνές σε αυτή τη γλώσσα?
Ο κωδικός γλώσσας έχει συνήθως δύο χαρακτήρες, όπως 'en' '' ή 'fr'
----
Όλες οι φωνές που αναφέρονται είναι διαθέσιμες σε Orca και ομιλίαd-up, και επίσης fenrir αν έχει ρυθμιστεί για να χρησιμοποιήσει ομιλία-αποστολέα.

Μπορείτε να πάρετε πρόσθετες φωνές για flite και mbrola, που συνδέονται με τις ενότητες flite-γενικό και espeak-ng-mbrola-generic.

Μπορείτε πάντα να γνωρίζετε ποιες είναι εγκατεστημένες ή όχι πληκτρολογώντας ως root μία από αυτές τις εντολές:
----
slapt-get --search mbrola-voice
slapt-get --search flite-voice
----
τότε εγκαταστήστε ένα από τα όχι ακόμη εγκατεστημένα ένα, όπως π.χ.
----
slapt-get -i mbrola-voice-it2
----
Εκτός από τις φωνές δωρεάν (όπως στην ελεύθερη μπύρα) που αποστέλλονται στο Slint, μπορείτε να αγοράσετε φωνές για: +
voxin, https://oralux. rg/voice.php +
voxygen, στέλνοντας ένα email στο contact@hypra.fr

Περισσότερες φωνές και συνθέτες θα μπορούσαν να διατεθούν αργότερα, αυτό θα ανακοινωθεί στη λίστα αλληλογραφίας του Slint και αυτό το http://slackware.uk/slint/x86_64/slint-15.0/ChangeLog.txt[ChangeLog]

Οι συντομεύσεις πληκτρολογίου για γραφικά περιβάλλοντα εμφανίζονται σε <<key_bindings, Συντομεύσεις πλήκτρων>>.

=== Χρησιμοποιήστε το lightdm login manager με ομιλία

Με ελαφρύ φως, πιέζοντας το F4 εναλλαγή του ήχου ενεργοποιημένο ή απενεργοποιημένο. Αρχικά ο δρομέας είναι στο πεδίο κωδικός. Πατήστε Καρτέλα οδηγεί στο "login push button", στη συνέχεια στον χρήστη's λίστα ή "combo box". Σε αυτή τη λίστα, πατώντας χώρο εμφανίζει τον τρέχοντα επιλεγμένο χρήστη. Χρησιμοποιήστε τα βελάκια για να επιλέξετε ένα άλλο και στη συνέχεια πληκτρολογήστε τον αντίστοιχο κωδικό πρόσβασης. Αντ 'αυτού, η επιλογή "Other..." προσθέτει ένα πεδίο στο οποίο μπορείτε να πληκτρολογήσετε το όνομα σύνδεσης ενός μη εισηγμένου χρήστη. Ακόμα στο φως, το F10 φέρνει ένα μενού που επιτρέπει την επανεκκίνηση ή τερματισμό, και Alt+F4 φέρνει απευθείας ένα UI με κουμπιά τερματισμού ή ακύρωσης.

=== Επιλέξτε έναν αναγνώστη οθόνης κονσόλας

Το Slint παρέχει αυτές τις συσκευές ανάγνωσης οθόνης: +
espeakup +
speehchd-up +
fenrir

Επιπλέον, αρκετοί συνθέτες ομιλίας υλικού μπορούν να χρησιμοποιηθούν σε λειτουργία κονσόλας, χρησιμοποιώντας speakup.

Για να επιλέξετε έναν αναγνώστη οθόνης εκτελέστε ως root αυτήν την εντολή:
----
μιλάν-μεName
----
Εδώ είναι η έξοδος του χωρίς παράμετρο:
----
root[~]# speak-with
Χρήση: /usr/sbin/speak-with <screen reader> ή <hard synthesizer> ή none
Επιλέξτε έναν αναγνώστη οθόνης κονσόλας για να μιλήσετε με ανάμιξη:
  espeakup (ανάγνωση οθόνης κονσόλας που συνδέει espeak-ng και speakup)
  fenrir (Modular, flexible and fast console screen reader)
  speechd-up (Console screen reader connecting Speech Dispatcher and speakup)
ή χρησιμοποιήστε έναν από τους υποστηριζόμενους σκληρούς synthesizers:
  acntsa apollo audptr bns dectlk decext ltlk soft spkout txprt
ή πληκτρολογήστε "/usr/sbin/speak-with none" για σίγαση όλων των αναγνωστών οθόνης.
ρίζα[~]#
----
Οι συνθέτες ομιλίας υλικού είναι αυτοί που είναι διαθέσιμοι στον εκτελούμενο πυρήνα ή αποστέλλονται ως ενότητες.

Παράδειγμα εντολών και σχετικής εξόδου:

----
root[~]# ομιλία-με ομιλία-up
Ξεκινώντας ομιλία-up
Θα πρέπει επίσης να ξεκινήσει κατά την επόμενη εκκίνηση? [Y/n]
OK
root[~]# Done.
----
Μόλις πληκτρολογήσετε την εντολή, θα σταματήσει η προηγούμενη χρήση ανάγνωσης οθόνης και το speechd-up θα αρχίσει να μιλάει.

Αν απαντήσετε Y (η προεπιλογή) στην ερώτηση: +
Θα πρέπει το spechd-up επίσης να ξεκινήσει κατά την επόμενη εκκίνηση? +
spechd-up θα συνεχίσει να χρησιμοποιείται στην επόμενη εκκίνηση. +
Αν αντιθέτως απαντήσετε n ο αναγνώστης οθόνης που χρησιμοποιήθηκε πριν την πληκτρολόγηση speak-with speechd-up θα χρησιμοποιηθεί μετά την επόμενη εκκίνηση.

Άλλα παραδείγματα:

----
root[~]# μιλώ με apollo
Διακοπή ομιλίας-επάνω...
Θα πρέπει να χρησιμοποιείται επίσης apollo κατά την επόμενη εκκίνηση? [Y/n]
OK
root[~]# Done.

root[~]# μιλώντας-με κανένα
Θέλετε επίσης μια κονσόλα σίγασης στο επόμενο boot? [Y/n]
OK
root[~]#
----

=== Ρυθμίστε ένα πρόγραμμα ανάγνωσης οθόνης κονσόλας.

Το Slint χειρίζεται συνθέτες υλικού ομιλίας χρησιμοποιώντας το speakup και παρέχει τους αναγνώστες οθόνης espeakup και speechdup.

Μπορείτε να αποθηκεύσετε τις ρυθμίσεις που κάνετε, για παράδειγμα για να αυξήσετε ή να μειώσετε το ρυθμό της τεχνολογίας ή την ένταση του ήχου. Ακριβώς όπως η ρίζα: speakup-save. Αυτό αποθηκεύει όλες τις τρέχουσες ρυθμίσεις, συμπεριλαμβανομένων εκείνων που είναι ειδικά για το συνθέτη υλικού σε χρήση, περίπτωση που εμφανίζεται.

Όλες αυτές οι ρυθμίσεις θα αποκατασταθούν κατά την επόμενη εκκίνηση: τα σενάρια εκκίνησης rc.espeakup και rc.speechd-up εκτελέσετε την εντολή speakup-επαναφορά για εσάς.

Αν δεν θέλετε να επαναφέρετε τις αποθηκευμένες ρυθμίσεις, πληκτρολογήστε σαν root: +
chmod -x /usr/sbin/speakup-restore

Αν θέλετε να επαναφέρετε τις αποθηκευμένες ρυθμίσεις πληκτρολογήστε σαν root: +
chmod +x /usr/sbin/speakup-restore

Εδώ είναι μερικές συντομεύσεις πλήκτρων για τις ρυθμίσεις ομιλίας καθώς και ομιλία:
----
spk_f9   punctuation_level_decrease
spk_f10  punctuation_level_increase
spk_f11  reading_punctuation_decrease
spk_f12  reading_punctuation_increase
spk_1    volume_decrease (doesn't work with speechd-up)
spk_2    volume_increase (doesn't work with speechd-up)
spk_3    pitch_decrease (doesn't work with speechd-up)
spk_4    pitch_increase (doesn't work with speechd-up)
spk_5    rate_decrease
spk_6    rate_increase
----
Στον παραπάνω πίνακα το spk είναι το πλήκτρο CapLock, ή Ins/0 σε ένα αριθμητικό πληκτρολόγιο. Για παράδειγμα για να αυξήσετε το ποσοστό που θα μπορούσατε να πατήσετε και κρατήστε πατημένο το CapsLock πλήκτρο στη συνέχεια πατήστε το πλήκτρο 6.

Ορισμένες ρυθμίσεις που είναι διαθέσιμες μόνο σε συγκεκριμένους συνθέτες υλικού δεν έχουν συσχετισμένες συντομεύσεις πλήκτρων. Στη συνέχεια, για να ορίσετε μια νέα τιμή την επαναλαμβάνετε στο /sys/accessibility/speakup/<synth>/<parameter>

Για παράδειγμα, για να αλλάξετε τη φωνή που χρησιμοποιείται από ένα apollo 2 μπορείτε να γράψετε: +
echo 2 > /sys/accessibility/speakup/apollo/voice

speakup-save θα αποθηκεύσετε επίσης αυτή τη ρύθμιση.

Caveat: Ποτέ δεν χρησιμοποίησα ένα συνθέτη ομιλία υλικού, έτσι ώστε η παρακάτω εξήγηση είναι μόνο μια υπόθεση που βασίζεται στον οδηγό speakup_apollo, σύμφωνα με αυτό το εγχειρίδιο, που βρέθηκε στο: +
https://archive. rg/stream/DolphinApollo2Manual/Dolphin_Apollo_2_Manual_djvu.txt

[[desktop_keys]]
==== Speakup πλήκτρα επιφάνειας εργασίας

Σχεδόν όλα τα πλήκτρα που παρατίθενται παρακάτω βρίσκονται στο αριθμητικό πληκτρολόγιο. Το πλήκτρο Insert ή 0 στο πληκτρολόγιο ενεργεί όπως ένα πλήκτρο shift . Για παράδειγμα, Ins 2 σημαίνει "κρατήστε πατημένο το πλήκτρο Insert όπως ένα πλήκτρο shift και πατήστε 2". Κρατήστε το numlock απενεργοποιημένο για να χρησιμοποιήσετε το Speakup.

Πεδίο εφαρμογής: αυτοί οι δεσμοί πλήκτρων μπορούν να χρησιμοποιηθούν με σκληρά synthesizers και με espeakup, καθώς και με speechd-up.

Πρώτα κλειδιά για να θυμάστε:
----
Οθόνη εκτύπωσης Ενεργοποίηση/απενεργοποίηση
Ins F1 Speakup Βοήθεια (πατήστε Διάστημα για να βγείτε από τη βοήθεια)
----

Πλήκτρα που χρησιμοποιούνται για την αναθεώρηση της οθόνης:
----
1/2/3 Πείτε Προηγούμενο/Τρέχον/Επόμενο χαρακτήρα
Shift PageUp Πείτε τον πρώτο χαρακτήρα
Shift PageDown Πείτε τον τελευταίο χαρακτήρα
4/5/6 Πείτε Προηγούμενη/Τρέχουσα/Επόμενη λέξη
5 Δις Ορθογραφία της τρέχουσας λέξης
Ins 5 Συλλαβισμός τρέχουσας λέξη φωνητικά
7/8/9 Πείτε Προηγούμενη/Τρέχουσα/Επόμενη γραμμή
Ins 4 Πείτε από την αριστερή άκρη της γραμμής μέχρι τον δρομέα ανάγνωσης
Ins 6 Πείτε από την ανάγνωση του δρομέα στη δεξιά άκρη της γραμμής
Ins 8 Πείτε από την κορυφή της οθόνης μέχρι τον δρομέα ανάγνωσης
Ins plus Πείτε από την ανάγνωση της γραμμής του δρομέα στο κάτω μέρος της οθόνης
συν Πείτε ολόκληρη την οθόνη.
Ins r Πείτε όλο το έγγραφο
τελεία Πείτε θέση
Χαρακτηριστικά Ins dot Say
Ins μείον Say χαρακτήρα εξαγωνικό και δεκαδική τιμή.
minus  στάθμευση δρομέα ανάγνωσης (εναλλαγή)
Ins 9 Μετακίνηση του δρομέα ανάγνωσης στο επάνω μέρος της οθόνης (insert pgup)
Ins 3 Μετακίνηση του δρομέα ανάγνωσης στο κάτω μέρος της οθόνης (insert pgdn)
Ins 7 Μετακίνηση του δρομέα ανάγνωσης στο αριστερό άκρο της οθόνης (insert home)
Ins 1 Μετακίνηση του δρομέα ανάγνωσης στη δεξιά άκρη της οθόνης (insert end)
Control 1 Μετακινήστε τον κέρσορα ανάγνωσης στον τελευταίο χαρακτήρα στην τρέχουσα γραμμή.
asterisk Εναλλαγή δρομέα
ins asterisk n<x|y μεταβείτε στη γραμμή (y) ή στη στήλη (x). Όπου το 'n' είναι οποιοδήποτε
               επιτρεπόμενη τιμή για τη γραμμή ή τη στήλη για την τρέχουσα οθόνη σας.
Ins f2 Set παράθυρο
Ins f3 Εκκαθάριση παραθύρου
Ins f4 Ενεργοποίηση παραθύρου
----

Άλλα κλειδιά:
----
Ins f5 Edit some
Ins f6 Edit most
Ins f7 Edit delim
Ins f8 Edit repeat
Ins f9 Edit exnum

Enter Shut up (until another key is hit) and sync reading cursor.
Ins Enter Κλείστε (μέχρι να επαναφέρετε επάνω)

κάθετο Mark και περικοπή περιοχή οθόνης.
Ins slash Επικόλληση περιοχή οθόνης σε οποιαδήποτε κονσόλα.
----
==== Speakup πλήκτρα φορητού υπολογιστή

Αυτές οι συντομεύσεις πλήκτρων (για διάταξη πληκτρολογίου ΗΠΑ) don't χρειάζονται ένα αριθμητικό πληκτρολόγιο. Αν έχετε ένα, χρησιμοποιήστε τα <<desktop_keys, πλήκτρα επιφάνειας εργασίας speakup>> ευκολότερα στη χρήση, ειδικά αν χρησιμοποιείτε μια άλλη διάταξη πληκτρολογίου από τις ΗΠΑ.

Το κλειδί CapsLock λειτουργεί ως πλήκτρο Shift. +
Για παράδειγμα, CapsLock 2 σημαίνει "κρατήστε πατημένο το πλήκτρο CapsLock όπως ένα πλήκτρο shift και πατήστε 2". +
Κρατήστε το numlock off για να χρησιμοποιήσετε το Speakup.

Πεδίο εφαρμογής: αυτοί οι δεσμοί πλήκτρων μπορούν να χρησιμοποιηθούν με σκληρά synthesizers και με espeakup, καθώς και με speechd-up.

Πρώτα κλειδιά για να θυμάστε:
----
Ενεργοποίηση/απενεργοποίηση της οθόνης εκτύπωσης
Βοήθεια Ομιλίας CapsLock F1 (πατήστε το Διάστημα για έξοδο)
----

Κλειδί που χρησιμοποιείται για την αξιολόγηση της οθόνης:
----
CapsLock m/comma/dot Say Previous/Current/Next character
CapsLock PageUp      Say First character
CpasLock PageDown    Say Last character
CapsLock j/k/l       Say Previous/Current/Next word
CpasLock k twice     Spell current word
CapsLock u/i/o       Say Previous/Current/Next line
CapsLock h           Say from left edge of line to reading cursor.
CapsLock semicolon   Say from reading cursor to right edge of line
CapsLock y           Say from top of screen to reading cursor
CapsLock p           Say from reading cursor line to bottom of screen
CapsLock apostrophe  Say entire screen.
Capslock r           Read all document
CapsLock n           Say position
CapsLock slash       Say attributes
CapsLock minus       park reading cursor (toggle)
CapsLock f2          Set window
CapsLock f3          Clear window
CapsLock f4          Enable window
----
Άλλα κλειδιά:
----
CapsLock f5 Επεξεργαστείτε μερικά
CapsLock f6 Επεξεργασία περισσότερα
CapsLock f7 Επεξεργασία οριοθέτη
CapsLock f8 Επαναλάβετε την επεξεργασία
shift CapsLock f9 Επεξεργασία exnum
----

=== Κάντε τις emacs να μιλούν

Μπορείτε να χρησιμοποιήσετε είτε emacspeak, είτε ομιλίας. Για να ενεργοποιήσετε ή να απενεργοποιήσετε μία από τις πληκτρολογήστε μια από αυτές τις εντολές:

switch-on emacspeak +
switch-on speechd-el +
switch-off emacspeak +
switch-off speechd-el +

Στη συνέχεια πληκτρολογήστε: +
emacs

Η ενεργοποίηση ενός από αυτά τα λογισμικά απενεργοποιεί το άλλο.

[[Manage_your_system]]
== Διαχείριση του συστήματός σας

[[software_management]]
=== Διαχείριση λογισμικού στο Slint.

<<The_basics,The basics>> +
<<Keep_your_system_up_to_date,Keep your system up to date>> +
<<Kernel_upgrades,Kernel upgrades>> +
<<Get_additional_applications,Get additional applications>> +
<<slapt_src,Usage of slapt-src>>

[[The_basics]]
==== Τα βασικά

Στο λογισμικό Slint παρέχεται με τη μορφή πακέτων. Ένα πακέτο είναι μια δέσμη αρχείων που παρέχονται σε ένα συμπιεσμένο αρχείο αρχείο, που μαζί για να παρέχει όλα όσα είναι απαραίτητα για να τρέξει το λογισμικό. Τα πακέτα περιλαμβάνονται στο ISO εγκατάστασης και αποθηκεύονται σε απομακρυσμένους διακομιστές από τους οποίους μπορούν να μεταφορτωθούν και να εγκατασταθούν. Εγκατάσταση ενός πακέτου σημαίνει εξαγωγή των αρχείων από το αρχείο αρχειοθήκης και αντιγραφή τους σε κάποιο κατάλογο του συστήματος.

Εγκατάσταση και αφαίρεση του λογισμικού καταγράφονται σε μια βάση δεδομένων που αποτελείται από αρχεία κειμένου σε αυτούς τους καταλόγους:
----
/var/lib/pkgtools/packages
/var/log/removed_packages
/var/lib/pkgtools/scripts
/var/log/removed_scripts
----
Τα αρχεία στον κατάλογο καταγράφουν πληροφορίες σχετικά με τα πακέτα, κυρίως το περιεχόμενό τους: τη λίστα των αρχείων που περιλαμβάνουν και όπου είναι εγκατεστημένα.

Οι κύριες εντολές διαχείρισης των πακέτων παρατίθενται παρακάτω. Όλοι τους έχουν συσχετίσει σελίδες ατόμων.

Αυτές οι εντολές απαιτούν δικαιώματα διαχείρισης, που σχετίζονται με έναν συγκεκριμένο λογαριασμό που ονομάζεται 'root', για τον οποίο έχετε ορίσει έναν κωδικό πρόσβασης κατά την εγκατάσταση του Slint.

Για να εκτελέσετε μια εντολή ως 'root', πληκτρολογήστε πρώτα su - στη συνέχεια, εισάγετε τον κωδικό πρόσβασης για το root και πληκτρολογήστε την εντολή.+ ή χρησιμοποιήστε sudo.

Οι παρακάτω εντολές μπορούν να εκτελεστούν από ένα γραφικό τερματικό ή σε μια κονσόλα, αλλά χάσμα που λειτουργεί μόνο σε ένα γραφικό περιβάλλον.
----
installpkg # για να εγκαταστήσετε ένα πακέτο αποθηκευμένο τοπικά.
αφαίρεσε # για να αφαιρέσεις ένα εγκατεστημένο πακέτο.
upgradepkg # για να αντικαταστήσει ένα εγκατεστημένο πακέτο με ένα άλλο (γενικά με το ίδιο όνομα αλλά σε άλλη έκδοση).
slapt-get # για εγκατάσταση, αφαίρεση, αναβάθμιση πακέτων αποθηκεύονται σε αποθετήρια που αναφέρονται στο /etc/slapt-get/slap-getrc
----
Τα πακέτα που αποστέλλονται στο ISO της εγκατάστασης προέρχονται από τα αποθετήρια που αναφέρονται στο /etc/slapt-get/slapt-getrc

Κάνετε στον εαυτό σας μια ευνοία: διαβάστε τα σχόλια στο /etc/slapt-get/slapt-getrc και /usr/doc/slapt-get-0.10.2t/README.slapgetrc.Slint στο εγκατεστημένο σύστημα.

Μετά την εγκατάσταση του Slint, θα ειδοποιηθείτε'για ενημερώσεις εγκατεστημένων πακέτων που προέρχονται από αποθετήρια που αναφέρονται στο /etc/slapt-get/slapt-getrc

Μπορείτε να εγκαταστήσετε πρόσθετα πακέτα χρησιμοποιώντας το slapt-get εντολών ή το γραφικό χάσμα εφαρμογής, εάν αποθηκευτεί σε ένα αποθετήριο που αναφέρεται στο /etc/slapt-get/slapt-getrc

slapt-get και gslapt παρέχουν μια λειτουργία αναζήτησης που σας βοηθά να βρείτε τα πακέτα.

WARNING: μπορείτε να χρησιμοποιήσετε slapt-get, gslapt και removepkg για να αφαιρέσετε τα εγκατεστημένα πακέτα αλλά μην αφαιρέσετε τα πακέτα που αποστέλλονται στο Slint ISO, ακόμη κι αν δεν τα χρησιμοποιείτε καθόλου. Η αφαίρεση ενός συμπεριλαμβανόμενου πακέτου θα οδηγήσει σε καμία αύξηση της απόδοσης και θα μπορούσε να αποτρέψει άλλες εφαρμογές να λειτουργήσουν. Επίσης, αν έχετε προσθέσει ένα πακέτο που δεν περιλαμβάνεται στο Slint μπορείτε να το αφαιρέσετε, αλλά να είστε προσεκτικοί ότι το αφαιρεθεί πακέτο δεν είναι μια εξάρτηση από άλλα που επίσης εγκαταστήσατε και σκοπεύετε να συνεχίσετε να χρησιμοποιείτε.

[[Keep_your_system_up_to_date]]
==== Κρατήστε το σύστημά σας ενημερωμένο

Κρατήστε το σύστημά σας ασφαλή εγκατάσταση των ενημερώσεων λογισμικού που παρέχονται από Slint μόλις'εκ νέου διαθέσιμα.

Όλες οι ενημερώσεις παρατίθενται στο ChangeLog: http://slackware.uk/slint/x86_64/slint-15.0/ChangeLog.txt

Μετά την εγκατάσταση Slint ή οποιαδήποτε αλλαγή στο αρχείο /etc/slapt-get/slapt-getr εκτελέστε αυτή την εντολή μία φορά:
----
slapt-get --add-keys
----

Για να συγχρονίσετε την τοπική λίστα των διαθέσιμων πακέτων με εκείνη του αποθετηρίου, αυτή η εντολή εκτελείται αυτόματα κάθε δύο ώρες:
----
slapt-get -u
----
Μπορείτε επίσης να το εκτελέσετε χειροκίνητα.

Αυτό φυσικά απαιτεί η μηχανή να συνδεθεί στο διαδίκτυο.

Για να κατεβάσετε και να εγκαταστήσετε τα αναβαθμισμένα ή αναδομημένα πακέτα εκτελέστε ως ρίζα την ακόλουθη εντολή:
----
slapt-get --αναβάθμιση
----
Εναλλακτικά θα μπορούσατε επίσης να χρησιμοποιήσετε gslapt, ένα γραφικό front-end για slapt-get.

Για να λάβετε νέα πακέτα στο Αρχείο καταγραφής αλλαγών ως "Προστέθηκε", πληκτρολογήστε:
----
slapt-get -i <package name>
----
ή για να βεβαιωθείτε ότι έχετε εγκαταστήσει όλα τα πακέτα που αποστέλλονται στο Slint, συμπεριλαμβανομένων εκείνων που προστίθενται στο χώρο αποθήκευσης μετά την εγκατάσταση του Slint, πληκτρολογήστε:
----
slapt-get --install-set slint
----

Στις επιφάνειες εργασίας, ένα μικρό εικονίδιο εμφανίζεται στην περιοχή ειδοποίησης ενός πάνελ (το άνω πάνελ στο MATE) για την κοινοποίηση των διαθέσιμων ενημερώσεων λογισμικού. Απλά κάντε ένα αριστερό κλικ σε αυτό και ακολουθήστε τις οδηγίες που αναφέρονται εκεί.

Θα πρέπει να γνωρίζετε ότι ορισμένα πακέτα είναι στη μαύρη λίστα στο /etc/slapt-get/slapt-getrc, δηλαδή δεν μπορούν να αναβαθμιστούν αυτόματα ή να εγκατασταθούν.

[[Kernel_upgrades]]
==== Αναβαθμίσεις πυρήνα

Παρέχονται νέοι πυρήνες όποτε χρειάζεται, είτε για να φέρουν διορθώσεις ασφαλείας είτε για βελτιώσεις.

Συνήθως δεν απαιτείται χειροκίνητη παρέμβαση από τον χρήστη όταν συμβαίνει αυτό, but it can be useful to know how the kernel upgrade is done and what to do if something unexpected occurs.

Διάφορα πακέτα περιλαμβάνουν αρχεία που σχετίζονται με κάθε πυρήνα, δηλαδή: γενικός-πυρήνας-modules, πυρήνας-πηγή, κεφαλίδες πυρήνα. Η πηγή πυρήνα και οι κεφαλίδες πυρήνα περιλαμβάνουν αρχεία που χρησιμοποιούνται για την κατασκευή λογισμικού, απαιτούνται μόνο γενικές πυρήνα και μονάδες πυρήνα για την εκτέλεση ενός συστήματος Slint.

Οι ενότητες πυρήνα πακέτου στέλνουν αρχεία που ονομάζονται ενότητες, τα οποία είναι κομμάτια κώδικα που είναι "συνδεδεμένα" στον πυρήνα για να παρέχει ένα συγκεκριμένο χαρακτηριστικό ή να χειρίζεται ένα συγκεκριμένο υλικό.

Μόλις εγκατασταθούν τόσο ένα πακέτο πυρήνα όσο και το σχετικό πακέτο μονάδων πυρήνα, το script /sbin/wrapupgradepkg χτίζει ένα <<initrd, initrd>> που σχετίζεται με αυτόν τον πυρήνα (με πρόσθετα που λαμβάνονται από τα modules kernel-modules) και το εγκαθιστά παράλληλα με τον πυρήνα στον κατάλογο /boot.

Στη συνέχεια, οι προηγούμενοι πυρήνες (όχι σε χρήση κατά τη στιγμή της αναβάθμισης) αφαιρούνται.

Στη συνέχεια, το σενάριο ενημερώνει το αρχείο ρυθμίσεων GRUB /boot/grub/grub.cfg, που διαβάζεται από τον φορτωτή OS για να δομήσει το μενού εκκίνησης.

Αυτό το μενού εκκίνησης θα περιλαμβάνει στη συνέχεια τουλάχιστον δύο καταχωρήσεις εκκίνησης κάθε ένδειξη, για την ένδειξη ενός πυρήνα και της συσχετιζόμενης initrd του που θα χρησιμοποιηθεί. Από πάνω:

* Μια καταχώρηση εκκίνησης για την εκκίνηση του Slint χρησιμοποιώντας το νέο πυρήνα που μόλις έχει εγκατασταθεί.
* Μια καταχώρηση εκκίνησης για την εκκίνηση του Slint χρησιμοποιώντας τον πυρήνα που χρησιμοποιείται κατά τη στιγμή της αναβάθμισης.

Αυτό παρέχει ένα "δίχτυ ασφαλείας" σε περίπτωση που Slint wouldn't εκκίνησης με το νέο πυρήνα: σε αυτή την περίπτωση απλά βέλος κάτω μία φορά όταν εμφανίζεται το μενού εκκίνησης για να ξεκινήσει το Slint με τον προηγούμενο πυρήνα

Μπορείτε να κάνετε προεπισκόπηση του νέου μενού εκκίνησης πριν την επανεκκίνηση, πληκτρολογώντας ως root:
----
grub-emu
----
Στη συνέχεια εμφανίζεται ένα προσομοιωμένο ή "ψεύτικο" μενού εκκίνησης, με την ίδια διάταξη με την πραγματική που θα εμφανιστεί στην επόμενη εκκίνηση.

Μπορείτε να περιηγηθείτε σε αυτό με τα κάτω και πάνω βέλη για να επισημάνετε (να βάλετε την εστίαση) μια καταχώρηση εκκίνησης της οποίας μπορείτε να εμφανίσετε τις λεπτομέρειες πατώντας 'e'. Μπορείτε να επιστρέψετε στο μενού πατώντας Escape.

Για να βγείτε από το grub-emu πατήστε c και στη συνέχεια πληκτρολογήστε *Έξοδος* και πατήστε Enter.

Εναλλακτικά, μπορείτε να πληκτρολογήσετε ως root:
----
list_boot_entries
----

[[Get_additional_applications]]
==== Λήψη πρόσθετων εφαρμογών

Ο ευκολότερος και συνιστώμενοι τρόπος για να πάρετε πρόσθετες εφαρμογές που δεν αποστέλλονται στο Slint είναι να χρησιμοποιήσετε slapt-get ή το γραφικό front-end gslapt. Αυτό σας παρέχει πρόσβαση σε όλα τα πακέτα σε χώρους αποθήκευσης που ενεργοποιούνται στο /etc/slapt-get/slapt-getrc από προεπιλογή, επιπλέον του χώρου αποθήκευσης Slint: +

* Το αποθετήριο Slackware, με πληροφορίες εξάρτησης: SOURCE=https://slackware.uk/salix/x86_64/slackware-15.0/:OFFICIAL
* Το επιπλέον αποθετήριο του Salix, τροφοδοτείται για τη διανομή του Salix από τον συντηρητή του George Vlahavas aka gapan αλλά μπορεί να χρησιμοποιηθεί και στο Slint: SOURCE=https://slackware.uk/salix/x86_64/extra-15.0/:OFFICIAL

Εάν η εφαρμογή που θέλετε δεν είναι εγκατεστημένη και επίσης δεν είναι διαθέσιμη σε ένα από τα αποθετήρια ενεργοποιημένα στο /etc/slapt-get/slapt-getrc θα μπορούσατε να κάνετε ένα πακέτο γι 'αυτό, χρήση οικοδομικού υλικού που παρέχεται από εθελοντές @ https://slackbuilds.org. Για να μάθετε πώς-να συνεχίσετε, διαβάστε https://slackbuilds.org/howto/ και https://slackbuilds.org/faq/

Τα πακέτα που κατασκευάζονται με αυτόν τον τρόπο πρέπει να είναι συμβατά με το Slint.

Η εφαρμογή *slapt-src* και το γραφικό της front-end *sourcery* σας επιτρέπει να κατασκευάζετε και να εγκαθιστάτε πακέτα χρησιμοποιώντας το υλικό κατασκευής που παρέχεται στο https://slackbuilds.org, το οποίο θα χρησιμοποιηθεί ως root ή με χρήση sudo.

Θα περιγράψουμε το slapt-src με περισσότερες λεπτομέρειες.

[NOTE]
====
Προκατασκευασμένα πακέτα για τις περισσότερες εφαρμογές που μπορούν να κατασκευαστούν με slap-src ή sourcery είναι διαθέσιμα στο επιπλέον αποθετήριο Salix. Κατά προτίμηση, εγκαταστήστε αυτά τα προκατασκευασμένα πακέτα χρησιμοποιώντας slapt-get ή gslapt, εκτός αν χρειάζεστε συγκεκριμένες επιλογές κατασκευής ή διαφορετική έκδοση από αυτή που παρέχεται.
====

[[slapt_src]]
===== Χρήση του slapt-srcrc

Το προεπιλεγμένο σενάριο ρύθμισης παραμέτρων για το slapt-src είναι το /etc/slapt-get/slap-getrc και έχει αυτό το περιεχόμενο:
----
BUILDDIR=/var/lib/slapt-src
PKGEXT=txz
SOURCE=https://slackbuilds.org/slackbuilds/15.0/
----
Οπότε:

* Όλο το υλικό κατασκευής και οι συσκευασίες θα πάνε στο /var/lib/slapt-src
* Τα ονόματα των πακέτων που κατασκευάζονται τελειώνουν στο .txz
* Το δομικό υλικό λαμβάνεται από το αποθετήριο https://slackbuilds.org/slackbuilds/15.0/

Εδώ είναι η έξοδος της εντολής *slapt-src --help*:
----
Χρήση: slapt-src [επιλογή(-ές)] [action] [slackbuild(s)]
  -u, --update update local cache of remote slackbuilds
  -U, --upgrade-all upgrade all installed slackbuilds
  -l, --list list available slackbuilds
  -e, --clean build directory
  -s, --search search available slackbuilds
  -w, --show show specified slackbuilds
  -i, --εγκατάσταση ανάκτησης, κατασκευάζει και εγκαθιστά τα καθορισμένα slackbuild(s)
  -b, --build μόνο λήψη και κατασκευή των καθορισμένων slackbuild(s)
  -f, --λήψη μόνο των καθορισμένων slackbuild(s)
  -v, --version
  -h, --help
 Επιλογές:
  -y, --yes do not prompt
  -t, --προσομοίωση δείχνουν τι θα γίνει
  -c, --config=FILE χρησιμοποιήστε το καθορισμένο αρχείο ρυθμίσεων
  -n, --no-dep δεν ψάχνει για εξαρτήσεις
  -p, --postprocess=CMD εκτέλεση καθορισμένης εντολής στο δημιουργημένο πακέτο
  -B, --ισχύει μόνο για το --upgrade-all
  -F, --φέρει-μόνο εφαρμόσιμη μόνο στο --upgrade-all
----

Let's σχολιάσει μερικές από αυτές τις επιλογές:

* Χρησιμοποιήστε -u ή --update κάθε φορά για να ενημερώσετε τη λίστα των πακέτων που μπορούν να κατασκευαστούν και να εγκατασταθούν. Αυτή η εντολή γράφει το αρχείο /tmp/slapt-src/slackbuilds_data, αντικαθιστώντας την προηγούμενη περίπτωση που εμφανίζεται.
* Χρησιμοποιήστε -e για να εξοικονομήσετε χώρο στο δίσκο, αφαιρώντας τα περισσότερα αρχεία στο /tmp/slapt-src/
* *δεν* χρησιμοποιήτε -U εκτός από την λίστα των πιθανών αναβαθμίσεων ή υποβαθμίσεων, χωρίς επιβεβαίωση: η επιβεβαίωση θα οδηγήσει σε αντικατάσταση όλων των πακέτων Slint από το ένα στην άλλη έκδοση, εάν είναι διαθέσιμα στο απομακρυσμένο αποθετήριο, ενδεχομένως το σπάσιμο λογισμικού δεν είναι συμβατό με αυτή την άλλη έκδοση.
* -i μπορεί επίσης να αναβαθμίσει ένα πακέτο που έχει ήδη εγκατασταθεί από https://slackbuilds.org, αν ένας συντηρητής του σεναρίου SlackBuild το έχει αναβαθμίσει, αλλάζοντας τη μεταβλητή VERSION.
* Χρησιμοποιήστε -f για να κατεβάσετε μόνο τα αρχεία στο https://slackbuilds.org για το λογισμικό προορισμού. Αυτό μπορεί να είναι χρήσιμο αν θέλετε να ελέγξετε το οικοδομικό υλικό ή να προσαρμόσετε την κατασκευή. Για παράδειγμα let's υποθέτουν ότι θέλετε να φέρετε το δομικό υλικό για το λογισμικό *mxml*. Η παρακάτω εντολή δίνει κάποιες πληροφορίες σχετικά με το λογισμικό και τα αρχεία που αποθηκεύονται στο https://slackbuilds.org για αυτό:
+
----
slapt-src --show mxml
SlackBuild Όνομα: mxml
SlackBuild Version: 3.
SlackBuild Κατηγορία: libraries/mxml/
SlackBuild Περιγραφή: mxml (Lightweight xml parsing library)
SlackBuild Files:
 README
 mxml. lackBuild
 mxml.info
 slack-desc
----
+
Τώρα ανακτά τα αρχεία διαστάσεων και επίσης το πηγαίο αρχείο από το ανάντη αποθετήριο με την επόμενη εντολή:
+
----
slapt-get -f mxml
----
+
Γνωρίζοντας από την έξοδο της προηγούμενης εντολής ότι τα αρχεία αποθηκεύονται στις βιβλιοθήκες υποκαταλόγου/mxml, μπορείτε να ελέγξετε ποια αρχεία έχουν ληφθεί με αυτήν την εντολή:
+
----
ls -1 /var/lib/slapt-src/libraries/mxml
mxml-3.1.tar.gz
mxml.SlackBuild
mxml.info
slack-desc
----
* Χρησιμοποιήστε το -b αν θέλετε να δημιουργήσετε ένα πακέτο αλλά μην το εγκαταστήσετε ακόμα. Στο παραπάνω παράδειγμα θα αποθηκευτεί στο /tmp/slapt-src/libraries/mxml, έτσι θα είστε σε θέση να το εγκαταστήσετε αργότερα απλά πληκτρολογήστε:
+
----
upgradepkg --install-new /tmp/slapt-src/libraries/mxml/xml*txz
----
+
* Χρησιμοποιήστε -c αν θέλετε να χρησιμοποιήσετε ένα προσαρμοσμένο αρχείο ρυθμίσεων αντί για το προεπιλεγμένο /etc/slapt-get/slap-getrc

=== Διαχείριση χρηστών και ομάδων.

Παρέχονται δύο εντολές για τη διαχείριση χρηστών και ομάδων:

* Η εντολή _usersetup_ (TUI)
* Η εντολή _gtkusersetup_ (GUI), με ένα εικονίδιο στο Κέντρο Ελέγχου Σλιντ, κατηγορία Συστήματος)

Αυτές οι εντολές σας επιτρέπουν να προσθέσετε ή να διαγράψετε χρήστες και ομάδες χρηστών και να προσθέσετε χρήστες σε ομάδες.

Να θυμάστε ότι κάθε λογαριασμός χρήστη συνδέεται από προεπιλογή με το χώρο στο /home directory. Για παράδειγμα αν προσθέσετε ένα χρήστη *leonie*, θα δημιουργηθεί ένας φάκελος /home/leonie, στην οποία μόνο αυτός ο χρήστης (και ρίζα) θα επιτρέπεται να έχει πρόσβαση.

=== Αλλάξτε την προεπιλεγμένη γλώσσα του συστήματος

Παρέχονται δύο εντολές για αυτό:

* Η εντολή _localesetup_ (TUI).
* Η εντολή _gtklocalesetup_ (GUI), με ένα εικονίδιο στο Κέντρο Ελέγχου Σλιντ, κατηγορία Ρυθμίσεων.

Να θυμάστε ότι αυτές οι ρυθμίσεις αλλάζουν τη γλώσσα που χρησιμοποιείται από τις διεπαφές των εφαρμογών αν διεθνοποιηθούν, όχι τον χάρτη πληκτρολογίου (δείτε παρακάτω).

Επίσης, τα μεταφρασμένα πακέτα (αν είναι διαθέσιμα) που ταιριάζουν στην επιλεγμένη γλώσσα έχουν ήδη εγκατασταθεί στο τέλος της εγκατάστασης του Slint. Αν αλλάξετε την προεπιλεγμένη γλώσσα στη συνέχεια, θα πρέπει να εγκαταστήσετε τα αντίστοιχα μεταφρασμένα πακέτα αν θέλετε.

Τοπική σημαίνει "παρέχεται σε μια δεδομένη τοπική", το τοπικό είναι μια γλώσσα συν ιδιαιτερότητες που συνδέονται με μια γεωγραφική περιοχή. Για παράδειγμα, τα πορτογαλικά που ομιλούνται στην Πορτογαλία και τη Βραζιλία διαφέρουν. Στα τοπικοποιημένα ονόματα πακέτων, l10n είναι μια συντομογραφία του "τοπικοποίηση" που σημαίνει "γράμμα l, 10 άλλα γράμματα, γράμμα n".

Τα μεταφρασμένα πακέτα περιλαμβάνονται για πολλές γλώσσες. Το όνομά τους περιλαμβάνει το βασικό όνομα πακέτου, μια παύλα, τότε ο κωδικός γλώσσας. Παραθέτουμε κάτω από τα βασικά ονόματα των τοπικών πακέτων:
[options="autowidth"]
|====
| Όνομα πακέτου βάσης | Περιγραφή
| aspell | λίστες λέξεων για το ορθογραφικό έλεγχο
| libreoffice-l0n | τοπικοποιημένο γραφείο LibreOffice
| libreoffice-help | τοπική βοήθεια για το LibreOffice
|====

Για να βρείτε ένα μεταφρασμένο πακέτο, πληκτρολογήστε σε έναν τερματικό εξομοιωτή ως root (παράδειγμα για libreoffice-l10n): +
`spi libreoffice-l10n`

Αυτό θα εμφανίσει τη λίστα όλων των μεταφρασμένων πακέτων LibreOffice. Βρείτε αυτό που θέλετε και εγκαταστήστε το. Για παράδειγμα για τα περσικά ο κωδικός γλώσσας είναι `fa` (συντομία για το Farsi), έτσι ώστε για να τον εγκαταστήσετε πληκτρολογήστε: +
`spi -i libreoffice-l0n-fa`

Αν προτιμάτε μπορείτε να χρησιμοποιήσετε `gslapt`. Στη συνέχεια, πληκτρολογήστε το όνομα του πακέτου στο πεδίο αναζήτησης για να εμφανίσετε όλα τα μεταφρασμένα πακέτα libreOffice.

=== Αλλαγή του χάρτη πληκτρολογίου

Μπορείτε να αλλάξετε το προεπιλεγμένο keymap που χρησιμοποιείται σε γραφική λειτουργία χρησιμοποιώντας:

* Η εντολή _keyboardsetup_ (TUI)
* Η εντολή _gtkkeyboardsetup_ (GUI), με ένα εικονίδιο στο Κέντρο Ελέγχου Σλιντ, στην κατηγορία Υλικού.

Αυτές οι εντολές σας επιτρέπουν επίσης να επιλέξετε αν το numlock θα πρέπει να ενεργοποιηθεί κατά την εκκίνηση του συστήματος, και εάν η SCIM (μέθοδος εισόδου) πρέπει να ενεργοποιηθεί κατά την εκκίνηση του συστήματος.

Εάν χρησιμοποιείτε έναν διαχειριστή παραθύρων με έναν πίνακα, μπορείτε επίσης να κάνετε αυτή τη ρύθμιση μέσω ενός δεξιού κλικ στην μικροεφαρμογή πληκτρολογίου (εμφανίζεται από προεπιλογή ως ο κωδικός δύο γραμμάτων γλώσσα του χάρτη πληκτρολογίου σε χρήση).

Στη γραμμή εντολών αλλά για τη γραφική λειτουργία χρησιμοποιήστε αντί αυτού την εντολή `setxbmap`

Για παράδειγμα, για να ορίσετε τη διάταξη πληκτρολογίου στην ουκρανική σε γραφική λειτουργία, απλά πληκτρολογήστε ως κανονικός χρήστης: +
`setxkbmap -layout ua`

Για να μάθετε περισσότερα, διαβάστε τη σελίδα man για setxkbmap.

=== Εγκατάσταση εκτυπωτή

Στο Slint ο εξυπηρετητής εκτυπώσεων CUPS διαχειρίζεται εκτυπωτές και εκτυπωτικές εργασίες. Στην προεπιλεγμένη διαμόρφωση, η οποία καταγράφεται στο αρχείο /etc/cupsd. onf, μόνο οι χρήστες που ανήκουν στην ομάδα `sys` (σύντομη για _σύστημα_) επιτρέπεται να εκτελούν εργασίες διαχείρισης, όπως προσθήκη ή αφαίρεση ενός εκτυπωτή.

Για μια απλή ρύθμιση (εκτυπωτής συνδεδεμένος σε επιτραπέζιο ή φορητό υπολογιστή και δεν μοιράζεται μεταξύ μηχανών), απλά πρέπει να προσθέσετε έναν χρήστη (ο οποίος θα διαχειρίζεται τους εκτυπωτές) στην ομάδα `sys`. Για παράδειγμα η προσθήκη του χρήστη didier_στην ομάδα `sys` μπορεί να γίνει δύο τρόπους:

* Σε λειτουργία κονσόλας ή χρησιμοποιώντας έναν εξομοιωτή τερματικού, γίνετε root με `su -` και μετά πληκτρολογήστε:
+
`gpasswd --add didier sys`
+
* Στη γραφική λειτουργία από το Κέντρο Ελέγχου Slint κάντε κλικ στους χρήστες και τις ομάδες (κατηγορία του συστήματος), επιλέξτε το χρήστη και κάντε κλικ στις Ιδιότητες και, στη συνέχεια, στην καρτέλα Ομάδες ελέγξτε `sys`. Ή τον αντίστροφο γύρο (επιλέξτε την ομάδα και στη συνέχεια προσθέστε το χρήστη σε αυτό).

Υπάρχουν διάφοροι τρόποι για να προσθέσετε και να ρυθμίσετε έναν εκτυπωτή (αυτό πρέπει να γίνει από ένα μέλος του χρήστη της ομάδας `sys`):

* Από το Κέντρο Ελέγχου Slint, κατηγορία Hardware, κάντε κλικ στο Ρύθμιση εκτυπωτή για να εμφανίσετε ένα γραφικό περιβάλλον που επιτρέπει μια απλή ρύθμιση...
* ... Ή κάντε κλικ στο Cups Print Control η εμφάνιση ενός web interface στον εξυπηρετητή CUPS. Μπορείτε επίσης να εμφανίσετε τη διεπαφή ιστού στον εξυπηρετητή CUPS πληκτρολογώντας `localhost:631` στο πεδίο διεύθυνσης ενός περιηγητή ιστού.
* Αν έχετε μια συσκευή Hewlett Packard, κάντε δεξί κλικ στο λογότυπο *hp* στην περιοχή ειδοποιήσεων του πίνακα.

NOTE: Για να κάνετε οποιαδήποτε ρύθμιση εκτύπωσης θα πρέπει να εκτελείται ο εξυπηρετητής CUPS. Ξεκινά όταν ξεκινάτε το Slint εάν η υπηρεσία `φλιτζάνια` ελέγχεται μεταξύ των Υπηρεσιών Συστήματος (ελέγχεται από προεπιλογή στο Slint).

=== Ρύθμιση ήχου

Σε εφαρμογές Slint είτε στέλνουν την ηχητική τους παραγωγή είτε στην ALSA είτε στο PulseAudio.

Στην τελευταία περίπτωση το PulseAudio με τη σειρά του στέλνει το ρεύμα εξόδου σε ένα μίξερ ALSA που το κατευθύνει στις κάρτες ήχου.

Ως αποτέλεσμα, μια ρύθμιση όπως μια ένταση ήχου εξόδου μπορεί πάντα να γίνει από ένα μίξερ ALSA, και επίσης από ένα μίξερ PulseAudio αλλά μόνο σε περίπτωση που η εφαρμογή στέλνει την έξοδο ήχου του στο PulseAudio.

Τώρα θα παρουσιάσουμε εφαρμογές που μπορούν να χρησιμοποιηθούν για την τροποποίηση των ρυθμίσεων ήχου

==== pavucontrol (για PulseAudio)

`pavucontrol` σημαίνει PulseAudio Volume Control και είναι μια γραφική εφαρμογή. Μπορείτε να το ξεκινήσετε από ένα μενού τερματικού ή εφαρμογής, ή κάνοντας δεξί κλικ στο εικονίδιο μίξερ ήχου στην κορυφή του πίνακα του Mate. Στην πραγματικότητα επιτρέπει περισσότερες ρυθμίσεις από το μόνο έλεγχο της έντασης, αφιερώστε χρόνο για να εξερευνήσετε όλες τις λειτουργίες της.

Μπορείτε επίσης να χρησιμοποιήσετε την μικροεφαρμογή ελέγχου έντασης στην περιοχή ειδοποιήσεων του πίνακα: ένα αριστερό κλικ επιτρέπει να ρυθμίσετε την ένταση, ένα δεξί κλικ δίνει πρόσβαση σε άλλες ρυθμίσεις και επιτρέπει να ξεκινήσει το μίξερ pavucontrol.

[[Sound_on_the_command_line]]

==== alsamixer (for ALSA)

alsamixer είναι μια εφαρμογή ncurses, που παρέχει μια ημι-γραφική διεπαφή χρήστη.

Για να το χρησιμοποιήσετε πληκτρολογήστε σε μια κονσόλα ή σε ένα γραφικό τερματικό:
----
alsamixer
----
τότε:

* Χρησιμοποιήστε τη σελίδα πάνω από το κλειδί για να αυξήσετε την ένταση κατά 5%
* Χρησιμοποιήστε το πλήκτρο κάτω από τη σελίδα για να μειώσετε την ένταση κατά 5%
* πιέστε το Esc για να αφήσετε την εφαρμογή.

==== amixer (για ALSA)
Η εντολή είναι της μορφής:
----
amixer <arguments>
----
Για παράδειγμα για να ορίσετε τον κύριο όγκο σε 70% τύπο:
----
amixer sset Master 70%
----
Για να μάθετε περισσότερα, πληκτρολογήστε μία από αυτές τις εντολές:
----
άνθρωπος amixer
amixer -h
----
==== Sam (Ο Μίξερ Άλσα Φιλικός)
ο Sam επιτρέπει την επιλογή της κάρτας ήχου για εργασία όταν υπάρχουν περισσότερες από μία τέτοιες συσκευές στον υπολογιστή σας. +
Όταν υπάρχει μόνο μία, παρουσιάζει απευθείας τους διαφορετικού μίκτες για τη διαμόρφωση.

Όλες οι επιλογές, είτε πρόκειται για κάρτες ήχου, οι αναμικτήρες ή ένα συγκεκριμένο χαρακτηριστικό ενός
 συγκεκριμένου αναμείκτη επιλέγονται με κύλιση μέσα από τις διαθέσιμες επιλογές χρησιμοποιώντας τα βέλη πάνω και κάτω, στη συνέχεια, εισάγοντας στο επιθυμητό: +
`q` αφήστε τη λίστα επιλογής και/ή τερματίζει. +
`Shift-q` βγαίνει από το πρόγραμμα από οπουδήποτε. +
`F1` Εμφανίζει τυχόν επιπλέον πληροφορίες εάν είναι διαθέσιμες.

Όταν είναι γνωστό το όνομα της επιθυμητής επιλογής, μπορεί κανείς να πατήσει το πρώτο γράμμα. Η πλοήγηση με πρώτο γράμμα δεν είναι ευαίσθητη στην περίπτωση. Αυτό θα σας μεταφέρει στην πρώτη επιλογή ξεκινώντας με το πατημένο γράμμα. Πατώντας ξανά το ίδιο γράμμα, θα μετακινηθείτε στην επόμενη επιλογή ξεκινώντας με αυτό το γράμμα ifmore από μία επιλογή όπως αυτή υπάρχει. Η επανάληψη του γράμματος θα κάνει κύκλο μεταξύ όλων αυτών των επιλογών που ξεκινούν με αυτό το γράμμα.

Τα ρυθμιζόμενα χαρακτηριστικά ενός μίξερ μπορούν να εμφανισθούν πατώντας F1. +
Παρουσιάζονται ως ένας κατάλογος επιλογών, παρουσιάζοντας εν συντομία όλες τις σχετικές πληροφορίες, π.χ. η "playback volume down from 84 percent" είναι η επιλογή να μειωθεί η ένταση αναπαραγωγής. Όπως μπορείτε να δείτε, σας λέει επίσης ποια είναι η τρέχουσα ρύθμιση.

NOTE: sam δεν λειτουργεί σωστά σε ένα γραφικό τερματικό. Χρησιμοποιήστε το σε μια κονσόλα.

==== pamixer και ponymix (για PulseAudio)
Αυτά τα βοηθήματα είναι παρόμοια, με εντολές σε αυτή τη φόρμα:
----
pamixer <arguments>
ponymix <arguments>
----
Για παράδειγμα για να ορίσετε τον όγκο στο 70% για την προεπιλεγμένη νεροχύτη πληκτρολογήστε μία από αυτές τις εντολές:
----
pamixer --set-volume 7
ponymix set-volume 7O
----
Για να μάθετε περισσότερα, πληκτρολογήστε:
----
pamixer -h
ponymix --help
----

==== pacmd και pactl (για PulseAudio)

Και οι δύο αυτές εφαρμογές γραμμής εντολών ελέγχουν ένα ενεργό δαίμονα PulseAudio.

WARNING: pacmd πληκτρολογήθηκε μόνο φέρνει ένα διαδραστικό διάλογο. Πατήστε Ctrl+d για να βγείτε από αυτό, αλλά μην πληκτρολογήσετε έξοδο, καθώς αυτό θα σκοτώσει το PulseAudio!

Για να ξέρετε περισσότερα:
----
man pactl
man pacmd
pactl --help
pacmd --help
----

==== Αποθήκευση και επαναφορά της στάθμης ήχου

Απλά κάντε το αρχείο /etc/rc.d/rc.alsa εκτελέσιμο. Ως ρίζα:
----
chmod /etc/rc.d/rc.alsa
----
Κατά την εκκίνηση, αυτό το σενάριο θα επαναφέρει τις προηγούμενες ρυθμίσεις ήχου αν αποθηκευτεί, αλλιώς θα θέσει προεπιλεγμένους τόμους και θα τους αποθηκεύσει, έτσι ώστε να αποκατασταθούν κατά την επόμενη επανεκκίνηση.

Αν don't θέλετε αυτό το σενάριο να ορίσει τον προεπιλεγμένο τύπο τόμου ως root:
----
αφή /var/lib/alsa/no.asound.state
----

Μπορείτε να αλλάξετε αυτά τα προεπιλεγμένα επίπεδα ήχου με alsamixer ή amixer και στη συνέχεια πληκτρολογώντας ως root:
----
κατάστημα alsactl
----
Στη συνέχεια, κατά την επόμενη εκκίνηση το σενάριο θα τους επαναφέρει.

Για να ξέρετε περισσότερα:
----
man alsactl
----

=== Ρύθμιση παραμέτρων δικτύου

Εάν κάνατε't ρυθμίσατε τις ρυθμίσεις δικτύου σας κατά την εγκατάσταση του Slint, πρώτα γίνει ρίζα πληκτρολογώντας `su -` είτε σε μια κονσόλα είτε σε γραφικό τερματικό όπως το mate-terminal, στη συνέχεια, πληκτρολογήστε τον κωδικό πρόσβασης root.

Η εγκατάσταση του δικτύου γίνεται με το σενάριο `netsetup`. Έτσι, απλά πληκτρολογήστε την εντολή `netsetup` σε αυτό το ίδιο τερματικό, όπου'έχετε μόλις επικαλεσμένα δικαιώματα root. Θα σας ζητηθεί για πρώτη φορά το όνομα του υπολογιστή σας. μπορείτε να επιλέξετε οποιοδήποτε όνομα, αλλά το μυαλό ότι πρέπει να είναι μια μόνο λέξη. Στη συνέχεια, σας ζητείται το όνομα τομέα. Εάν το μηχάνημα δεν είναι διακομιστής μπορείτε να επιλέξετε κανέναν. Μετά από αυτό θα ερωτηθείτε πώς το μηχάνημά σας συνδέεται με το δίκτυο. Εκτός αν έχετε έναν καλό λόγο να μην (και ξέρετε τι κάνετε), κρατήστε τον προεπιλεγμένο `Διαχειριστή δικτύου` για να ρυθμίσετε αυτόματα το δίκτυο.

Για ενσύρματες συνδέσεις, αυτό θα πρέπει να είναι αρκετό για να συνδεθεί στην επόμενη εκκίνηση αυτόματα.

Για να ρυθμίσετε μια ασύρματη σύνδεση, διατίθενται δύο εντολές χρησιμοποιώντας τη γραμμή εντολών.

Και πάλι, μπορείτε να πληκτρολογήσετε τις εντολές απευθείας στην κονσόλα ή σε ένα γραφικό τερματικό όπως το mate-terminal. Πληκτρολογήστε τους ως τακτικό χρήστη όχι ως root. Αν ακολουθήσατε αυτές τις οδηγίες και αρχίσατε ήδη τη ρίζα, απλά πληκτρολογήστε `έξοδο` για να επιστρέψετε στην κανονική κατάσταση χρήστη.

Οι δύο προαναφερθείσες εντολές είναι `nmtui` (πλαίσια διαλόγου) ή `nmcli` (καθαρή γραμμή εντολών), και οι δύο είναι προσβάσιμες.

Αν προτιμάτε να εργάζεστε σε μια γραμμή εντολών, φροντίστε να διαβάσετε πρώτα την τεκμηρίωση nmcli. Απλά πληκτρολογήστε `nmcli --help` και `man nmcli` για να μάθετε όλες τις λεπτομέρειες. Ενώ το `nmcli` προσφέρει περισσότερες δυνατότητες, στις περισσότερες περιπτώσεις χρήσης η λειτουργικότητα του `nmtui` θα είναι επαρκής για τη δημιουργία του ασύρματου δικτύου σας, έτσι θα το περιγράψουμε εδώ:

Χρησιμοποιώντας το `nmtui`, μπορείτε να πλοηγηθείτε με τα πλήκτρα Tab και βέλους. Θα σας προτείνουν τρεις επιλογές: +
`Edit a connection` +
`Activate a connection` +
`Set system hostname` +

Εάν δεν έχει οριστεί ασύρματη σύνδεση επιλέξτε `Ενεργοποίηση σύνδεσης`. Ξεκινώντας από πάνω προς τα κάτω, πρώτα θα προτείνονται οι ενσύρματες συνδέσεις (αν υπάρχουν), μετά από αυτό θα εμφανίζονται όλα τα προσβάσιμα ασύρματα δίκτυα. Πλοηγηθείτε με τα κάτω και πάνω βέλη για να επιλέξετε το δίκτυο που θέλετε, τότε απλά πληκτρολογήστε Enter: πιθανότατα θα σας ζητηθεί το κλειδί κωδικού πρόσβασης ή κρυπτογράφησης. Πληκτρολογήστε το, χρησιμοποιήστε το πλήκτρο Tab για να το επιβεβαιώσετε, στη συνέχεια, βγείτε και τελειώσατε.

Μόνο σε γραφική λειτουργία, αντί για `nmcli` ή `nmtui` μπορείτε να χρησιμοποιήσετε την εφαρμογή `nm-connection-editor`.

=== Διαμόρφωση υπηρεσιών

Μπορείτε να αλλάξετε τις προεπιλεγμένες ρυθμίσεις με διάφορους τρόπους:

* Εκτέλεση ως root της εντολής `servicesetup` (TUI)
* Σε κατάσταση γραφικών μόνο, με τη χρήση του "gtkervicesetup", το οποίο είναι προσβάσιμο από το Slint Control Center, το σύστημα κατηγοριών ή την πληκτρολόγηση Alt + F2 για την αύξηση ενός διαλόγου "Εκτέλεση..." στη συνέχεια, πληκτρολογώντας * gtkservicesetup *.
* Ως ρίζα καθιστώντας το σχετικό σενάριο εκτελέσιμο (chmod 755 <path to the script> ή μη εκτελέσιμο (chmod 644 <path to the script>). Για παράδειγμα για να κάνετε εκτελέσιμο το fail2ban θα πληκτρολογήσετε: `chmod 755 /etc/rc.d/rc.fail2ban`

IMPORTANT: Αλλάξτε τις προεπιλεγμένες ρυθμίσεις μόνο αν γνωρίζετε τι κάνετε.

Οι υπηρεσίες διαχειρίζονται σενάρια των οποίων το όνομα αρχίζει με `rc.` στον κατάλογο /etc/rc.d/. Για παράδειγμα, η υπηρεσία acpi διαχειρίζεται από το σενάριο κελύφους /etc/rc.d/rc.acpi. Οι περισσότερες από τις υπηρεσίες είναι ενεργοποιημένες κατά την εκκίνηση αν το αντίστοιχο σενάριο είναι εκτελέσιμο. Στον παρακάτω πίνακα δηλώνουμε αν είναι ενεργοποιημένο κατά την εκκίνηση (`on` στη στήλη A) ή όχι (`off` στη στήλη A). Εάν η στήλη είναι κενή, η ενεργοποίηση των υπηρεσιών εξαρτάται από μια επιλογή που έγινε κατά την εγκατάσταση. Ένα `Α` στη στήλη δείχνει ότι η υπηρεσία είναι ενεργοποιημένη σε λειτουργία αυτόματης εγκατάστασης, αλλιώς ενεργοποιείται αν επιλεγεί από το χρήστη κατά τη διάρκεια της εγκατάστασης. Η στήλη πακέτου υποδεικνύει ποιο πακέτο λογισμικού παρέχει το σενάριο που αντιστοιχεί στην υπηρεσία, περίπτωση που συμβαίνει

[options="autowidth"]
|====
| *Service* | *A* | *Package* | *Purpose and comments*
| acpi | on | acpid | Advanced Configuration and Power Interface, allows for instance to manage power or reboot pressing a button
| alsa | on | alsa-utils | Provide default sound settings or restore those saved
| alsa-oss | off | alsa-utils | ALSA OSS kernel modules. Not useful in most cases, not enabled by default in Slint.
| atalk | off | netatalk | Allows Unix-like operating systems to serve as file, print and time servers for Macintosh computers.
| atd | off | at | at and batch read shell commands from standard input (or a specified file) storing them as a job to be scheduled for execution at a later time
| autofs | off | autofs | AutoFS provides automounting of removable media or network shares when they are inserted or accessed.
| bind | off | bind | Name server. Most users will rely on a remote one. Enable it if you want to run a name server in this system.
| bitlbee | on | bitlbee | BitlBee is an IRC daemon that can talk to instant messaging networks
       and acts as a gateway. Users can connect to the server with any normal
       IRC client and see their 'buddy list' in bitlbee.
| bluetooth | on | bluez | Allows to communicate with bluetooth devices
| brltty| | brltty | Allows to communicate with Braille terminal or screen reader. Activated if requested during installation
| cgconfig | on | libcgroups | Runs the cgconfigparser utility that parses /etc/cgconfig.conf to setup the control group hierarchy, including setting the permissions (UID and GID) of the groups and possibly tunable parameters of the controllers. This alleviates doing that ourselves at every startup, for instance running a separate shell script. This script is executable by default but anyway won't do anything until /etc/cgconfig.conf be edited (all lines are commented out as shipped)
| cgred | on | libcgroups | The control groups are a way to control the allocation of system resources like CPU or RAM to "groups" of users and/or processes. This script starts the cgroups rules engine daemon that automatically distributes to appropriate control groups the processes that changes their effective UID or GID. It is executable by default but to make it work you need to set rules in /etc/cgrules.conf.
| consolekit | on | ConsoleKit2 | This daemon is used by polkit's auth agent, to check privileges of user wanting to reboot or shutdown the system, for instance.
| cpufreq | on | sysvinit-scripts | Settings for CPU frequency and voltage scaling in the kernel.
| crond | on | crond |The cron daemon runs in the background and executes tasks on behalf of users at the appropriate time.
| cups | on | cups | Startup/shutdown script for the CUPS print server.
| cups-browsed | off | cups-filters | Makes remote printers available locally.
| dnsmask | off | dnsmask | Start/stop/restart dnsmasq (a small DNS/DHCP server)
| dovecot | off | dovecot | Dovecot is an open source IMAP and POP3 server for Linux/UNIX-like systems, written with security foremost in mind. 
| elogind | on | elogind | elogind is the systemd project's logind, extracted to a standalone  package.
| espeakup | | espeakup | starts/stop/restart the espeakup console screen reader. On if user requested speech during installation or later typed speak-with espeakup
| fail2ban | off | fail2ban | start/stops fail2ban which scans log files like /var/log/pwdfail and bans IP that makes too many password failures, and also updates firewall rules to reject the IP address.
| fenrir | off | fenrir | starts/stop/restart the fenrir screen reader, which can be started after installation typing speak-with fenrir.
| font | off | kbd | Sets the console font (used in Console mode, not in Graphical mode)
| fuse | on | fuse | Load the fuse module and mount the fuse control filesystem. FUSE is a simple interface for userspace programs to export a virtual filesystem to the Linux kernel. FUSE also aims to provide a secure method for non privileged users to create and mount their own filesystem implementations.
| fuse3 | on | fuse3 | Like fuse, but version 3 
| gpm | on | gpm | The General Purpose Mouse server allows to cut and paste text from the screen on a Linux console.
| haveged | on | haveged | The haveged project is an attempt to provide an easy-to-use, unpredictable random number generator based upon an adaptation of the HAVEGE algorithm.
| httpd | off | httpd | Starts or stop the Apache web server
| icecc-scheduler | off | icecream | Start/stop/restart the icecream (distributed compiler) scheduler
| iceccd | off | icecream | Start/stop/restart the icecream (distributed compiler) daemon
| inet1 | on | network-scripts | This script is used to bring up the various network interfaces.
| inet2 | on | network-scripts | This shell script boots up the entire network system.
| inetd | on | inetd | BSD "super-server" daemon. The user needs to edit /etc/inetd.conf for the services to be actually used.
| ip_forward | off | network-scripts | Start/stop IP packet forwarding, needed for your computer to act as a router.
| kadmind | off | krb5 | Start the Kerberos administration server
| kprprod | off | krb5 | Start the Kerberos V5 slave KDC update server. 
| krb5kdc |off | krb5 | Start krb5kdc, which is the Kerberos version 5 Authentication Service and Key Distribution Center (AS/KDC). This needs to run first on both master and secondary KDCs.
| local | off | sysvinit-scripts | starts daemons not started by /etc/rc.d/rc.M at boot time.
| loop | on | sysvinit-scripts | Loads the loop device kernel module.
| lxc | off | lxc | This scripts starts (if configured to be auto-started) and stops lxc containers.
| mcelog | off | mcelog | Starts the mcelog hardware error logging. This logs and handles CPU hardware errors on x86 systems
| messagebus | on | dbus | The D-BUS systemwide message bus. This is a daemon which broadcasts notifications of system events and other messages, providing inter-processes communication.
| modules | on | sysvinit-scripts | Compute the kernel modules dependencies and start other scripts that load modules not automatically loaded by eudev, possibly for specific kernel versions
| modules.local | on | sysvinit-scripts | Load modules not automatically loaded by eudev
| mysqld | off | mariadb | Starts/stop the MariaDB server. MariaDB is a fork of MySQL fully compatible with it
| networkmanager| | NetworkManager | This is a daemon for automatically switching network connections to the best available connection. Activated if NetworkManager is chosen to configure the network, during or after installation
| nfsd | off | nfs-utils | Starts/stop a nfs (Network File Server)
| ntpd | on | ntp | Starts stop an ntp ( Net'work Time Protocol) daemon.
| numlock| | salixtools | Activate numlock on the console
| openldap | off | openldap | Start the ldap (Lightweight Directory Access Protocol) server
| openvpn | off | openvpn | Start the OpenVPN (secure IP tunnel) daemon
| pcmcia | off | pcmciautils | Script to initialize PCMCIA subsystem.
| php-fpm | off | php | Starts the PHP FastCGI Process Manager daemon.
| postfix | off | postfix | start Postfix, mail transport and submission agent.
| pulseaudio | off | pulseaudio | Starts pulseaudio system-wide. This is not recommended in Slint.
| rpc | off | rpcbind | Start/stop/restart RPC (remote process communications) daemons needed to use NFS. To run an NFS server, starting these is mandatory.
| samba | off | samba | Start/stop/restart the Samba SMB CIFS file and print server for CIFS clients. It allows you to manage a file space or printers on a Samba host available to CIFS clients (such as PCs running Windows).
| saslauthd | off | cyrus-sasl | saslauthd is a daemon process that handles plaintext authentication requests on behalf of the SASL library. The CMU Cyrus SASL library is mostly used to authenticate to mail servers.
| serial | off | util-linux | Initializes and sets the serial ports on your system
| setterm | on |util-linux | Provides the command line for the setterm utility to set the terminal attributes (primarily used for screen blanking and power management).
| smartd | off | smartmontools | Start/stop/restart the smartd daemon, which monitors the status of S.M.A.R.T. compatible hard drives and reports any problems.
| snmpd | off | net-snmp |Start/stop the net-snmp SNMP (Simple Network Management Protocol) daemon
| speechd-up | | speechd-up | starts/stop/restart the speechd-up screen reader, which can be started after installation typing speak-with speechd-up.
| sshd | on | openssh | Start/stop/restart the secure shell daemon.
| swapinzram | on | swapinzram | Configure a swap block device in RAM using zram
| syslog | on | sysklogd | Start/stop/restart the system logging daemons, that logs both kernel and system's messages.
| sysstat | off | systat | Reset the system activity logs, used to compute performance statistics
| sysvinit | on | sysvinit-scripts | This file provides basic compatibility with SystemV style startup scripts found in many binary packages
| timidity | off | TiMidity++ | Start/stop/restart the TiMidity++ daemon. TiMidity++ is a software synthesizer. It can play MIDI files by converting them into PCM waveform data or other various audio file formats.
| udev | on | eudev | This script initializes udev, which populates the /dev directory with device nodes, scans for devices,
loads the appropriate kernel modules, and configures the devices.
| ulogd | on | ulogd | starts the userspace ulogd daemon for netfilter/iptables related logging.
| vde2 | on | vde2 | Start/stop/restart the VDE daemon. VDE is an ethernet compliant virtual network which includes tools such as 'vde_switch' and 'vdeqemu'.
| wireless | on | wireless-tools|This script sets up PCI, USB, and 32-bit Cardbus wireless devices. Normally this script is called from rc.inet1 rather than run directly
| yp | on | yptools | Start NIS (Network Information Services). NIS provides network-wide distribution of hostname, username, and other information databases.
|====

Μπορείτε να ξεκινήσετε ή να σταματήσετε μια υπηρεσία χρησιμοποιώντας ως root την εντολή `υπηρεσία`. Για να μάθετε περισσότερα τύπου `man service`.
// Glossary

== Γλωσσάριο

Several definitiενεργόs in this glossary are taken or adapted from https://en.wikipedia.org/wiki/Main_Page[Wikipedia] and https://pubs.opengroup.org/onlinepubs/9699919799/[POSIX]

[[applicatiενεργό]]Εφαρμογή:: An applicatiενεργό program (applicatiενεργό for short) is a computer program designed to carry out a specific task typically requested by end-users.
+
Οι εφαρμογές δεν θεωρούνται γενικά ως μέρος του λειτουργικού συστήματος, πράγμα που σημαίνει ότι μπορούν να προστεθούν στο σύστημα μετά την εγκατάστασή του. Εκτελούν λειτουργίες που δεν σχετίζονται με το σύστημα, όπως επεξεργασία κειμένων, αρχιτεκτονικός σχεδιασμός, μηχανικός σχεδιασμός, έκδοση ή οικονομική ανάλυση.


[[boot]]Εκκίνηση::
Boot means switch-ενεργό a computer to start an operating system. Αρκετά λειτουργικά συστήματα μπορούν να εγκατασταθούν στον ίδιο υπολογιστή. Select which one to load into RAM and run can be dενεργόe either by the firmware or by a software named boot manager (GRUB in Slint's case). The firmware of a computer can support ενεργόe of following booting mode, or both:
+
* In the Legacy or BIOS mode the OS is loaded executing the instructiενεργόs written in a boot sector.
* Στη λειτουργία EFI το OS loader είναι ένα πρόγραμμα που αποθηκεύεται σε ένα εκτελέσιμο αρχείο, που βρίσκεται σε έναν κατάλογο ενός διαμερίσματος συστήματος EFI (ESP).

[[Επεξεργαστής]]CPU::
Η CPU ή Κεντρική Μονάδα Επεξεργασίας εκτελεί τις οδηγίες των προγραμμάτων.

[[command]]Εντολή:: Η εντολή ορίζεται από τον https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_104[POSIX] ως "οδηγία για ένα <<shell, κέλυφος>> για να εκτελέσει μια συγκεκριμένη εργασία".
+
Η εργασία που θα εκτελεστεί μπορεί να είναι μια <<application, εφαρμογή>> ή ένα <<utility, βοηθητικό πρόγραμμα>>.
+
Η βασική δομή των εντολών κελύφους ορίζεται στο κεφάλαιο https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09[2.9 Εντολές κελύφους] της προδιαγραφής POSIX.
+
Παραδείγματα εντολών παρέχονται στο <<bash shell, [κελύφος bash]>>.

[[console]]Κονσόλα:: Η λέξη "κονσόλα" αναφέρεται στην αρχή του υπολογιστή συστήματα, όταν ο διαχειριστής του συστήματος πληκτρολόγησε εντολές σε μια συσκευή, συμπεριλαμβανομένου ενός πληκτρολογίου και ενός εκτυπωτή, συνδεδεμένες με τον υπολογιστή, τις εντολές που πληκτρολογήθηκαν και την έξοδο από τον υπολογιστή που εκτυπώνεται στην κονσόλα, παρέχοντας ένα αρχείο καταγραφής και των δύο.
+
Σε προσωπικούς υπολογιστές, ο χρήστης πληκτρολογεί τις εντολές στο πληκτρολόγιο και η έξοδος τους εκτυπώνεται σε μια οθόνη, που μπορούν να διαχωριστούν από τον υπολογιστή ή να ενσωματωθούν στον υπολογιστή όπως σε ένα φορητό υπολογιστή.

[[device]]Συσκευή::

Ένας υπολογιστής περιφερειάρχης ή ένα αντικείμενο που εμφανίζεται στην εφαρμογή ως τέτοιο.[POSIX]

[[directory]]Κατάλογος::
Ένας κατάλογος είναι ένα άλλο όνομα για ένα φάκελο. Τα συστήματα αρχείων χρησιμοποιούν καταλόγους για να οργανώσουν αρχεία μέσα σε κατατμήσεις.
+
Οι κατάλογοι μπορούν να περιέχουν αρχεία καθώς και άλλους καταλόγους. Η δομή που προκύπτει μπορεί να αναπαρίσταται ως ανεστραμμένο δέντρο. Ο κατάλογος πρώτου επιπέδου μιας μονάδας ονομάζεται κεντρικός κατάλογος. Στο Linux ο χαρακτήρας / χωρίζει τα επίπεδα του δέντρου. / Μόνο αντιπροσωπεύει τον κεντρικό κατάλογο, /home φιλοξενεί τα αρχεία που ανήκουν στους χρήστες, /home/didier φιλοξενεί τα αρχεία που ανήκουν στο χρήστη didier. /root φιλοξενεί τα αρχεία του χρήστη root (ο διαχειριστής του συστήματος). Σημείωση: 'root' μπορεί να παραπέμπει στον κατάλογο πρώτου επιπέδου ή στο διαχειριστή του συστήματος.

[[drive]]Οδηγός::
Μια μονάδα δίσκου είναι μια συσκευή που αποθηκεύει μη πτητικά δεδομένα, πράγμα που σημαίνει ότι τα δεδομένα δεν είναι σβησμένα όταν η ισχύς είναι απενεργοποιημένη. Παραδείγματα: σκληροί δίσκοι, SSD, USB sticks, SD κάρτες αναγνώστες, eMMC.
+
Τα μέσα αποθήκευσης των δεδομένων μπορεί να συνδεθεί μόνιμα με τη μονάδα δίσκου ή αφαιρούμενα όπως κάρτες SD, USB sticks και δίσκους που συνδέονται μέσω USB.
+
Ένα λειτουργικό σύστημα εγκατεστημένο σε αφαιρούμενο μέσο ή μια εξωτερική μονάδα δίσκου λέγεται φορητό: μπορεί να μετακινηθεί από έναν υπολογιστή σε άλλο.

[[display_manager]]Διαχειριστής οθόνης::
Ένας διαχειριστής εμφάνισης (ή διαχειριστής σύνδεσης) είναι ένα λογισμικό που εμφανίζει ένα παράθυρο στην οθόνη στο οποίο ζητά το όνομα σύνδεσης και τον κωδικό πρόσβασης του χρήστη, ξεκινά το γραφικό περιβάλλον που επιλέγεται από τον εν λόγω χρήστη.

[[encryption]]Κρυπτογράφηση::
Η κρυπτογράφηση είναι η διαδικασία μετατροπής δεδομένων σε μια μη αναγνωρίσιμη («κρυπτογραφημένη») μορφή. Χρησιμοποιείται συνήθως για την προστασία ευαίσθητων πληροφοριών, έτσι ώστε μόνο εξουσιοδοτημένα πρόσωπα να μπορούν να τις δουν. Ένα ενιαίο αρχείο ή κατάλογος, ένα διαμέρισμα καθώς και ως ολόκληρη μονάδα δίσκου μπορεί να κρυπτογραφηθεί, which make it accessible only after having typed a small text called a passphrase, kept secret.

[[file]]Αρχείο::
Ένα αρχείο υπολογιστή είναι ένα σύνολο ψηφιακών δεδομένων που συλλέγονται με το ίδιο όνομα, που καταγράφονται σε ένα μόνιμο μέσο αποθήκευσης, ονομάζεται μαζική αποθήκευση, όπως ένας σκληρός δίσκος, ένα SSD, ένα DVD, μια κάρτα SD ή ένα USN stick και χειρίζεται ως μονάδα.
+
Τα αρχεία μπορούν να περιέχουν δεδομένα όπως κείμενα, εικόνες, ήχους, βίντεο ή προγράμματα υπολογιστών.

[[file_system]]Σύστημα Αρχείων::
Ένα σύστημα αρχείων είναι ένα λογισμικό που διαχειρίζεται τα αρχεία και τους καταλόγους σε μια κατάτμηση. Απομνημονεύει τη θέση στα φυσικά μέσα των δεδομένων που περιέχονται στα αρχεία, επιτρέποντας να τα διαβάσει ή να τα γράψει. Παραδείγματα κοινώς χρησιμοποιούμενων συστημάτων αρχείων είναι vfat, ntfs, ext4, f2fs. Αυτή η εντολή εμφανίζει όλα τα συστήματα αρχείων που επιτρέπουν την ανάγνωση δεδομένων που περιέχονται σε ένα διαμέρισμα από το Linux:
+
----
cat /proc/filesystems±grep -v nodev
----

[[firmware]]Υλικολογισμικό::
Ένα υλικολογισμικό είναι ένα λογισμικό που αρχικοποιεί και ελέγχει το υλικό, τότε είτε επιλέγει και φορτώνει σε RAM το λειτουργικό σύστημα, ή ξεκινά ένα λογισμικό που ονομάζεται διαχειριστής εκκίνησης που θα το κάνει αυτό. Το υλικολογισμικό διατηρείται σε μη-πτητική μνήμη συσκευές, όπως ROM, EPROM, ή μνήμη flash. Είναι το πρώτο λογισμικό που εκτελείται κατά την εκκίνηση ενός υπολογιστή. Παρέχει ένα μενού που επιτρέπει να ρυθμίσετε το υλικό και επιλέξτε σε ποια κατάσταση (Legacy ή EFI) για εκκίνηση, και με την οποία να αναζητήσετε το λειτουργικό σύστημα ή άλλη εφαρμογή (όπως ο διαχειριστής εκκίνησης GRUB) για να εκτελέσετε.

[[kernel]]Πυρήνας::
Ένας πυρήνας Linux είναι το λογισμικό στον πυρήνα ενός συστήματος Slint που χειρίζεται τις αλληλεπιδράσεις μεταξύ των εφαρμογών και του υλικού.
+
Παρουσιάζεται ως ένα μόνο αρχείο, εγκατεστημένο στον κατάλογο /boot. Για παράδειγμα το αρχείο /boot/vmlinuz-generic-5.12.11 είναι ένας πυρήνας, που προέρχεται από το γενικό πακέτο πυρήνα.
+
Κατά την εκκίνηση ο πυρήνας αντιγράφεται στη μνήμη RAM.

[[initrd]]Initrd::
Ένα initrd (ακριβέστερα ένα initramfs ή ένα αρχικό σύστημα αρχείων RAM για Slint) είναι ένα σύστημα Linux που παρέχεται ως συμπιεσμένο αρχείο αρχείου. Κατά την εκκίνηση, αμέσως μετά την φόρτωση του πυρήνα στη μνήμη RAM το initrd φορτώνεται και στη μνήμη RAM. Το αρχείο /init τρέχει: φορτώνει τις απαιτούμενες ενότητες πυρήνα στη μνήμη RAM, καταχωρεί τις συσκευές, ενδεχομένως ξεκλειδώνει τη root συσκευή, προσαρτά τα ψευδο-συστήματα αρχείων έπειτα μεταβαίνει στο ριζικό σύστημα αρχείων για να ξεκινήσετε πραγματικά το σύστημα.
+
Ένα initrd παρουσιάζεται ως ένα μόνο αρχείο, εγκατεστημένο στην εκκίνηση του καταλόγου. Για παράδειγμα, το αρχείο initrd-generic-5.12.11 είναι initrd

[[live_system]]Ζωντανό σύστημα::
Ένα ζωντανό σύστημα είναι ένα λειτουργικό σύστημα που, αντί να εγκατασταθεί σε μια συσκευή όπως ένας σκληρός δίσκος ή SSD, βρίσκεται εξ ολοκλήρου σε <<RAM>>.
+
An initrd is also a live system, and so is a Slint εγκαταστάτης wich is basically an initrd.

[[partition]]Διαμέρισμα::
Ένα διαμέρισμα είναι ένα τμήμα ενός μέσου αποθήκευσης, όπως ένας σκληρός δίσκος ή SSD. Αντιμετωπίζεται από το λειτουργικό σύστημα ως ξεχωριστός λογικός τόμος, ο οποίος καθιστά τη λειτουργία παρόμοια με μια ξεχωριστή συσκευή.

[[partition_table]]Πίνακας χωρισμάτων::
Ένας πίνακας διαμερισμάτων είναι η μόνιμη δομή που καταγράφει τον τρόπο με τον οποίο οι πληροφορίες παρέχονται σε ένα μέσο, κυρίως καταγραφή της αρχής και του τέλους κάθε διαμερίσματος στα μέσα ενημέρωσης.
+
Οι πιό κοινοί τύποι πινάκων κατατμήσεων είναι ο πίνακας κατατμήσεων DOS, που χρησιμοποιήθηκε αρχικά από το λειτουργικό σύστημα MS-DOS, και ο πίνακας κατατμήσεων GUID ή GPT, το οποίο επιτρέπει να χειριστεί περισσότερες κατατμήσεις και μεγαλύτερες κινήσεις.

[[program]]Πρόγραμμα::
Μια προετοιμασμένη ακολουθία οδηγιών προς το σύστημα για να ολοκληρώσει μια καθορισμένη εργασία. Ο όρος "πρόγραμμα" περιλαμβάνει εφαρμογές που είναι γραμμένες στη γλώσσα εντολών της Shell, σύνθετες γλώσσες εισαγωγής βοηθητικών προγραμμάτων (για παράδειγμα, awk, lex, sed, και ούτω καθεξής), και υψηλού επιπέδου γλώσσες. [POSIX]

[[RAM]]RAM::
RAM σημαίνει μνήμη τυχαίας πρόσβασης. Αυτό το είδος συσκευής αποθηκεύει πτητικά δεδομένα, που σημαίνει ότι τα δεδομένα διαγράφονται όταν η ισχύς είναι απενεργοποιημένη.

[[shell]]Κέλυφος:: Ένα πρόγραμμα που ερμηνεύει ακολουθίες από την είσοδο κειμένου ως εντολές. Μπορεί να λειτουργεί σε μια ροή εισόδου ή μπορεί να παρακινεί και να διαβάζει εντολές από ένα τερματικό. Η σύνταξη των εντολών που μπορούν να ερμηνευτούν από το κέλυφος μπορεί να διαφέρει ανάλογα με το κέλυφος που χρησιμοποιείται αλλά ορίζεται κυρίως στο κεφάλαιο https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html [2. Γλώσσα εντολών κελύφη] των προδιαγραφών POSIX.
+
Το Slint στέλνει διάφορα προγράμματα που ενεργούν ως κέλυφος, που απαριθμούνται στο αρχείο /etc/shells. Το κέλυφος *bash* χρησιμοποιείται από προεπιλογή.

[[swap]]Εναλλαγή::
Ένας χώρος ανταλλαγής swap space χρησιμοποιείται για την αποθήκευση δεδομένων προγενέστερα στο RAM σε μια συσκευή όπως ένας σκληρός δίσκος ή SSD, είτε επειδή αλλιώς η RAM θα γινόταν πλήρης, είτε για να ελευθερώσει χώρο στο RAM για να αποθηκεύσει εκεί τα πιο συχνά χρησιμοποιούμενα δεδομένα. Ο χώρος ανταλλαγής μπορεί να είναι ένα διαμέρισμα σε μια μονάδα τύπου 'Linux swap' ή ένα κανονικό αρχείο που αποθηκεύεται σε ένα υπάρχον διαμέρισμα. Υπάρχει επίσης το "swap in zram": σε αυτή την περίπτωση τα δεδομένα αποθηκεύονται στο RAM αλλά σε συμπιεσμένη μορφή.

[[terminal]]Τερματικό::
Ιστορικά ένα τερματικό ήταν μια φυσική συσκευή που αποτελείται από ένα πληκτρολόγιο και μια οθόνη που χρησιμοποιείται για τον τύπο εντολών και λαμβάνει απαντήσεις από έναν απομακρυσμένο υπολογιστή.
+
Σήμερα οι εντολές μπορούν να πληκτρολογηθούν σε λειτουργία κονσόλας (ή κειμένου) ή σε γραφική λειτουργία.

[[utility]]Εργαλείο::
Ένα βοηθητικό πρόγραμμα είναι ένα πρόγραμμα που μπορεί να κληθεί από ένα κέλυφος (αυτό είναι επίσης η περίπτωση του <<application,applications>>).
+
Τα βοηθητικά προγράμματα αποτελούν μέρος του λειτουργικού συστήματος (αλλά όχι του πυρήνα). Εκτελούν λειτουργίες που σχετίζονται με το σύστημα, όπως περιεχόμενο καταλόγου καταλόγου, έλεγχο συστημάτων αρχείων, επισκευή συστημάτων αρχείων, ή εξαγωγή πληροφοριών κατάστασης συστήματος.
+
Ένα βοηθητικό πρόγραμμα μπορεί να κληθεί ως ξεχωριστό πρόγραμμα που εκτελεί σε διαφορετική διαδικασία από το διερμηνέα της γλώσσας εντολής, ή μπορεί να υλοποιηθεί ως μέρος του διερμηνέα της γλώσσας εντολής.
+
Για παράδειγμα, η εντολή echo (η οδηγία για την εκτέλεση μιας συγκεκριμένης εργασίας) μπορεί να υλοποιηθεί έτσι ώστε το βοηθητικό πρόγραμμα echo (η λογική που εκτελεί την εργασία της απήχησης) να βρίσκεται σε ένα ξεχωριστό πρόγραμμα. Ως εκ τούτου, εκτελείται σε μια διεργασία που διαφέρει από τον ερμηνευτή γλώσσας εντολών. Πρακτικά αυτό σημαίνει ότι σε αυτή την περίπτωση το βοηθητικό πρόγραμμα είναι ένα πρόγραμμα διαφορετικό από το κέλυφος
+
Αντιστρόφως, η λογική που εκτελεί το βοήθημα echo θα μπορούσε να ενσωματωθεί στον ερμηνευτή γλώσσας εντολών. Ως εκ τούτου, θα μπορούσε να εκτελεστεί στην ίδια διεργασία με τον ερμηνευτή γλώσσας εντολών. Ένα τέτοιο βοηθητικό πρόγραμμα λέγεται "ενσωματωμένη" το κέλυφος.

[[virtual_terminal]]Εικονικό τερματικό::
Ένα εικονικό τερματικό είναι ένα λογισμικό που προσομοιώνει ένα φυσικό τερματικό, συσκευή που αποτελείται από ένα πληκτρολόγιο και μια οθόνη που επιτρέπει την απομακρυσμένη επικοινωνία με έναν υπολογιστή .
