
= Manual do Slint (versão 15.0)
:toc: left
:toclevels: 2
:toc-title: Content
:pdf-themesdir: themes
:pdf-theme: default

Note: this document will be updated to reflect recent changes - 21/06/2024

== Introdução ao Slint

=== Acerca do Slint

O Slint é uma https://en.wikipedia.org/wiki/Linux_distribution[distribuição Linux], baseada no http://www.slackware.com/[Slackware], que é fácil de instalar, versátil, poliglota, amigável para iniciantes e acessível a invisuais.

Um sistema Slint é funcional assim que instalado e pode ser adaptado para atender à maioria dos requisitos informáticos.

==== Funcionalidades

São propostos dois modos de instalação: Automático (o instalador prepara a unidade escolhida pelo utilizador e instala o Slint) e Manual (o instalador formata a partição Linux escolhida pelo utilizador e instala o Slint). O instalador inclui uma documentação.

O Slint é acessível para utilizadores com deficiência visual, com voz e braile, desde a instalação à utilização tanto numa consola como em ambientes gráficos.

Uma vasta gama de software para servidores, desktops e computadores portáteis está instalado em todos os sistemas Slint, que incluem dois ambientes de trabalho gráficos: MATE e LXQt, e gestores de janelas leves. MATE e LXQt fornecem acesso fácil a todas as aplicações e operações do sistema, com montagem automática de dispositivos removíveis, mais notificações de atualizações disponíveis do software instalado, acesso imediato à Internet, paragem, reinício, e hibernação do sistema.

O idioma escolhido será utilizado para aplicações internacionalizadas.

O painel de controlo do Slint centraliza o acesso a definições de hardware e sistema, pacotes, ferramentas de sistema, documentação e utilitários.

O Slint vem com muitas aplicações prontas a utilizar para gravar e ler e converter documentos em vários formatos, comunicar por e-mail, texto e conversa áudio, reproduzir áudio e vídeo, enviar e receber documentos ponto-a-ponto, editar áudio, vídeo e documentos gráficos, desenvolver aplicações. É totalmente utilizável como servidor numa consola e usando um dos vários ambientes de trabalho.

Muitas aplicações são acessíveis a utilizadores com deficiência visual, uma grande escolha de TTS e vozes associadas está incluída, se ainda precisar de outras, elas são facilmente instaláveis, utilizáveis tanto num ambiente de texto (consola), como no ambiente gráfico.

Várias ferramentas internas facilitam a administração e configuração do seu sistema Slint.

Muitas outras aplicações são facilmente instaladas como pacotes de software através de um comando simples ou alguns cliques. Milhares de pacotes de software estão ao seu alcance!

Os utilizadores do Slint são notificados sobre atualizações de pacotes instalados assim que disponível, instalados facilmente após solicitação. Isso mantém o sistema seguro.

As definições predefinidas das aplicações preferidas são fornecidas e podem ser facilmente personalizadas.

==== Conteúdo, versões e modelo de lançamento

O instalador do Slint fornece apenas uma instalação completa.

O Slint segue um modelo de lançamento "semi-rolling", o que significa que durante o ciclo de vida de uma dada versão, para além de atualizações como correções de segurança e correções de problemas, algum software é seletivamente atualizado para trazer melhorias e adicionado para trazer novas funcionalidades. Este é o caso do software que contribui para tornar o Slint acessível aos invisuais, como os leitores de ecrã.

Recomendamos que os utilizadores mudem para uma nova versão o mais rapidamente possível após o seu lançamento. Recomendamos que façam uma cópia de segurança completa de todos os dados que desejam manter, seguida de uma nova instalação e um restauro da cópia de segurança.

=== Acerca deste livro e outras fontes de informação

Este livro é destinado ao iniciante do Slint, a quem orienta através do seu processo de instalação e utilização. Os conceitos e convenções específicos do Slint e comuns nas distribuições Linux são apresentados e um glossário é anexado.

Tentamos acomodar pessoas que vêm do Windows ou do MacOS como utilizadores de outra distribuição como o Ubuntu.

Documentação sobre o software instalado geralmente está disponível num sistema Slint. Vamos dizer neste livro como acedê-la.

Outras fontes de informação estão disponíveis:

* A informação frequentemente fornecida no seu website pelos autores do software incluído no Slint.
* http://docs.slackware.com/[O projeto de documentação do Slackware] e particularmente os seus http://docs.slackware.com/howtos:start[artigos HOWTO] Muitos são aplicáveis diretamente ao Slint, algumas adaptações e atualizações podem ser necessárias.
* Além da distribuição Arch, a ArchWiki fornece frequentemente artigos úteis sobre software também instalado no Slint. Por exemplo procurar "arch wiki mate" leva a https://wiki.archlinux.org/index.php/MATE[esta página sobre o MATE]. Atenção: a informação fornecida pode precisar de ser adaptada, uma vez que Slint e o Arch diferem em alguns aspetos. Por exemplo, o Arch usa o systemd como sistema "init" e um determinado software pode ser configurado de forma diferente por padrão no Slint e Arch.
* E, como é evidente, um motor de busca de Internet pode muitas vezes ajudar a encontrar respostas para perguntas e soluções para problemas.
// Support

=== Suporte

Pode obter ajuda através destes canais:

* A lista de correio Slint é o canal de suporte principal. Para se registar, envie um e-mail para slint-request@freelists.org com o assunto: 'subscribe' e depois responda ao e-mail de confirmação que receberá. Depois, para saber mais, envie um e-mail para slint-request@freelists.org com o assunto 'commands' ou 'help'. Após o registo, envie um e-mail para slint@freelists.org.
* Os ficheiros da lista de correio estão disponíveis https://www.freelists.org/archive/slint[aqui].
* No IRC: converse no canal #slint, servidor irc.libera.chat, nenhum registo é necessário.
* Mumble: servidor slint.fr (por nomeação tomada através de outro canal).
* O https://forum.salixos.org/viewforum.php?f=44[Fórum do Slint] generosamente hospedado pelos nossos amigos do Salix (outro derivado de Slackware). O registo é necessário.


Para saber mais, veja as ligações no separador de Informação no Painel de Controlo do Slint ou apenas escreva: slint-doc num terminal após instalação.

=== Tradução e outras contribuições para o projeto Slint

O Slint precisa de tradutores! Se quiser participar no esforço da tradução, leia as instruções em https://slint.fr/doc/translate_slint.html[Traduzir o Slint].

Os ficheiros de tradução estão alojados no https://crowdin.com/project/slint[Crowdin].

Se quiser contribuir para o Slint para outras tarefas, basta publicar na lista de correio ou escrever algo para: didieratslintdotfr. Claro que os tradutores também são bem-vindos na lista de correio!
// Acknowledgments

=== Agradecimentos

O projeto Slint existe principalmente através do trabalho árduo dos tradutores do Slint e outros colaboradores, obrigado a todos!

Obrigado a George Vlahavas pelos seus conselhos e ferramentas, aos colaboradores do projeto SlackBuilds.org, que ajudam a compilar software adicional.

O Slint é baseado no Slackware, trazido por Patrick J. Volkerding e colaboradores. Obrigado! Encorajo todos os utilizadores do Slint a contribuir para o financiamento da Slackware e também a doar ao projeto Salix.

Os repositórios do Slint são generosamente hospedados gratuitamente por Darren 'Tadgy' Austin. Encorajo todos os utilizadores do Slint a contribuir para o financiamento do alojamento https://slackware.uk/

Links para as contribuições financeiras: +
https://www.patreon.com/slackwarelinux[Torne-se um patrono do Slackware] ou https://paypal.me/volkerdi[Suporte o Slackware] +
Siga os links acima http://slackware.uk/slint/x86_64/slint-15.0/[desta página] para apoiar o Slackware UK +
https://salixos.org/donations.html[Doações ao Salix]

== Instalar o Slint

Esta parte do Manual acompanha o processo de transferência do Slint, a verificar a imagem ISO com um "check-sum", a gravar a ISO num suporte de instalação, a particionar o disco rígido e descreve brevemente o processo de instalação.

=== Requisitos

A versão atual do Slint pode ser instalada em computadores que atendam a estes requisitos:

* Arquitetura: x86_64 (CPU 64-bit), também conhecida como AMD64
* No modo de particionamento Auto uma unidade de disco com o tamanho mínimo de 50G
* No modo de particionamento manual, uma partição do tipo Linux com um tamanho mínimo de 50G, uma partição de sistema EFI e/ou uma partição de arranque da BIOS na mesma unidade de disco. A partição EFI é obrigatória se a máquina arrancar em modo EFI, a partição de arranque da BIOS se a máquina arrancar em modo Legacy, sendo preferível ter ambas para permitir alternar entre os modos EFI e Legacy.
* O Slint pode ser instalado neste tipo de unidades: discos rígidos, SSD, NVME, eMMC, pens USB, cartões SD (de preferência em caixas USB).
* RAM: no mínimo 2G
* uma unidade de DVD ou uma entrada de USB disponível, com a capacidade do firmware para arrancar numa pen USB ou DVD. Um DVD em branco ou uma unidade USB de 5G ou mais pode ser utilizado como suporte de instalação

NOTE: O Arranque Seguro deve ser desativado para instalar o Slint.

=== Funcionalidades do instalador

* O instalador é um sistema 'live', executado na memória: não modificará um sistema instalado, a menos que e até que o diga para o fazer.
* Para os utilizadores invisuais, o instalador é totalmente utilizável com Braille e voz usando o leitor de ecrã "Speakup".
* Inclui todos os utilitários necessários para preparar as partições necessárias antes de uma instalação em modo de particionamento Manual.
* O modo de instalação Auto, ao invés disso, necessita apenas de um utilizador para responder a perguntas e fornecer uma ajuda contextual sobre as mesmas.
* Se instalado sozinho num dispositivo removível ligado através de USB, o Slint é portátil, ou seja, utilizável em qualquer computador capaz de iniciar uma unidade USB para além do computador utilizado para o instalar. Por exemplo, se instalar numa pen USB, basta ligar a pen num computador para a executar.
* O instalador pode encriptar a unidade onde o Slint está instalado sozinho. Isto evita o roubo de dados que contém em caso de perda ou roubo da máquina, ou de uma unidade removível.
* O slint pode ser instalado na sua própria unidade e em modo de particionamento manual ao lado de outro sistema.

=== Preparação

<<download_and_verify,Transferir e verificar uma imagem ISO Slint>> +
<<write_the_iso,Gravar a imagem ISO num suporte de instalação>> +
<<prepare_partitions_for_Slint,Opcionalmente, preparar partições para o Slint>>

[[download_and_verify]]
==== Transferir e verificar uma imagem ISO do Slint

A versão mais recente da distribuição Slint é a 15.0

A última imagem ISO de instalação está sempre disponível https://slackware.uk/slint/x86_64/slint-15.0/iso[neste diretório]

Esta imagem ISO também pode ser descarregada utilizando um cliente Torrent a partir desta página:

https://seedbox.slackware.uk/

O link para o torrent, após o nome "Slint Torrents", é:

https://seedbox.slackware.uk/torrents/slint64-15.0-5-iso.torrent

É igualmente fornecido um "magnet".

[TIP]
====
Desde que esteja a executar a versão 15.0 do Slint não é necessário reinstalar quando for fornecida uma nova ISO, visto que apenas traz novas funcionalidades do instalador e de pacotes novos ou atualizados que também pode ter se manter o sistema atualizado.
====

O nome do ficheiro da ISO indicado abaixo é apenas um exemplo, que irá adaptar-se ao nome atual ao transferir.

Se estiver a executar o Windows, uma pesquisa na Internet com o argumento "check sha256sum windows" dir-lhe-á como deve proceder.

Se estiver a executar o Linux, pode transferir a imagem ISO e o seu checkum sha256 escrevendo:
----
wget https://slackware.uk/slint/x86_64/slint-15.0/iso/slint64-15.0-5.iso
wget https://slackware.uk/slint/x86_64/slint-15.0/iso/slint64-15.0-5.iso.sha256
----

Para verificar a integridade dos ficheiros transferidos, escreva este comando:
----
sha256sum -c slint64-15.0-5.iso.sha256
----

O resultado deve ser: OK +
Caso contrário, refaça as transferências.

[[write_the_iso]]
==== Gravar a imagem ISO num Suporte de instalação

Pode usar um DVD ou uma pen USB como meio de instalação.

[TIP]
====
Pode simplesmente guardar a imagem ISO na primeira partição de uma pen USB Ventoy.

Neste caso, no início da instalação, o instalador pedirá para montar esta partição e, em seguida, montar a própria ISO.
====

[[make_a_bootable_usb_stick]]
===== Crie uma pen USB de arranque

Num sistema ++Linux++, ligue a pen USB e verifique o seu nome com o seguinte comando:

----
lsblk -o model,name,size,fstype,mountpoint
----

[WARNING]
====
Reveja cuidadosamente o resultado do comando para ter a certeza de que não irá escrever o nome de uma partição de disco rígido em vez do nome da sua pen USB. Todo o conteúdo anterior da pen USB ou de uma partição do disco rígido incorreta será **PERDIDO** e **IRRECUPERÁVEL**.
====

Vamos supor que o nome da pen USB seja /dev/sdb. Poderia ser nomeado de outra forma, por isso não copie cegamente o seguinte comando. A sintaxe de comando para gravar a ISO do Slint numa pen USB que reside em /dev/sdb é a seguinte:

----
dd if=slint64-15.0-5.iso of=/dev/sdb bs=1M status=progress && sync
----

[NOTE]
====
O comando acima assume que **if=** aponta para a localização da ISO do Slint e **of=** aponta para o nome da pen USB. Estes valores podem diferir no seu sistema.
====

No ++Windows++ use um programa como o http://rufus.akeo.ie/[Rufus]. É gratuito e de código aberto.

[[make_a_bootable_DVD_disc]]
===== Crie um DVD de arranque

Num sistema ++Linux++ insira o DVD e escreva o seguinte comando:

----
xorriso -as cdrecord -v dev=/dev/sr0 -eject slint64-15.0-5.iso
----

Certifique-se de inserir a localização completa para a ISO do Slint no seu sistema de ficheiros.

No ++Microsoft Windows 2000/XP/Vista/7++ pode gravar para um DVD usando o programa http://infrarecorder.org/[InfraRecorder]. É gratuito e de código aberto.

No ++Microsoft Windows 7/8/10+++ pode utilizar o utilitário que vem com o Microsoft Windows.

* Clique com o botão direito do rato no ficheiro ISO e selecione Gravar imagem de disco (se estiver no Windows 11, selecione Mostrar mais opções primeiro (Shift+f10)
* Para garantir que a ISO foi gravada sem quaisquer erros, selecione Verificar disco após gravação.

[NOTE]
====
Instruções não verificadas pelo gravador.
====

// Prepare
[[prepare_partitions_for_Slint]]
==== Opcionalmente, prepare as partições para o Slint

Neste documento 'formatar' uma partição significa: criar nela um sistema de ficheiros para gerir os ficheiros que irá conter.

Se depois de ter introduzido 'start' escreva 'm' para particionamento manual, primeiro selecionará a partição root do sistema, que será montada como "/", depois o tipo do seu sistema de ficheiros entre: btrfs, ext4, xfs.

O instalador lista para seleção apenas partições de tamanho mínimo de 50G e de Linux (também pode ser nomeado sistema de ficheiros Linux), não encriptados. Esta partição pode ser formatada ou não, mas em qualquer caso o seu conteúdo será eliminado e um novo sistema de ficheiros gerado pelo instalador.

Além disso, o modo de particionamento Manual requer na mesma unidade que a partição root do sistema:

* Uma partição do tipo partição de arranque BIOS, com um tamanho mínimo de 3M e não formatada, se a máquina arrancar em modo Legacy e a unidade tiver uma tabela de partições do tipo GPT.
* Uma partição do tipo sistema EFI, com pelo menos 32M de espaço livre, formatada com um sistema de ficheiros 'fat' (ou 'vfat'), conforme exigido pela especificação UEFI, se a máquina arrancar no modo EFI

É melhor configurar ambas as partições para permitir a troca entre os modos Legacy e EFI se a unidade tiver uma tabela de partições do tipo GPT.

A utilização ou criação de partições existentes para o Slint fica ao critério do utilizador. Os sistemas já instalados que utilizam o arranque da BIOS e as partições EFI não serão afectados, apenas a partição root será (re)formatada, e uma partição /home existente apenas se for solicitada.

O instalador inclui várias aplicações de partição: cfdisk, fdisk, sfdisk, cgdisk, gdisk, sgdisk, parted. As aplicações com "g" no seu nome só podem lidar com gpt, parted pode lidar com tabelas de partição DOS assim como GPT. fdisk, cfdisk e sfdisk podem lidar com tabelas de partição DOS. Além disso, estão disponíveis wipefs (para apagar as assinaturas anteriores da tabela de partições e do sistema de ficheiros) e partprobe (para informar o kernel das alterações de uma tabela de partições). As aplicações blkid e lsblk exibem informação sobre dispositivos e partições de blocos.

Claro que também pode criar as partições a partir de outro sistema antes de iniciar o instalador.
// Installation

=== Instalação do Slint
<<Start_of_the_installation,Início da instalação>> +
<<Overview_of_Slint_Installation,Resumo do processo de instalação>> +
<<Usage_of_the_installer,Utilização do instalador>> +
<<Encryption,Slint com uma partição root encriptada>> +
<<Speakup,Combinação de teclas para o leitor de ecrã Speakup>> +
<<first_steps_after_installation,Primeiros passos após a instalação>>

[[Start_of_the_installation]]
==== Início da instalação

Se necessário, configure o firmware da máquina para arrancar do DVD ou pen USB que preparou.

Insira o meio de instalação (DVD ou pen USB) e reinicie a máquina. Para ajudar os utilizadores invisuais, um som é ouvido quando o menu de arranque é apresentado.

Inicie o instalador apenas premindo Enter.

O instalador irá primeiro sondar as placas de som.

Isso pode ajudar a definir uma que funcione como predefinida e também é usado para a voz durante a instalação usado por alguns utilizadores invisuais.

Se o instalador encontrar mais de uma placa de som dirá em Inglês para cada uma: +
prima Enter para escolher esta placa de som <sound card id> +
Prima Enter assim que ouvir isso, para confirmar que a placa de som proposta está a funcionar. Esta definição será guardada no novo sistema em /etc/asound.conf.

Na etapa seguinte, quando perguntado, irá confirmar (escrevendo s) ou negar (apenas premindo Enter) que deseja voz durante a instalação. O Braile está sempre disponível durante a instalação.

Irá depois escolher, confirmar ou alterar o idioma usado durante a instalação. Depois todos os ecrãs estarão no idioma escolhido se a tradução para este idioma estiver completa.

Se precisar de acrescentar parâmetros adicionais à linha de comandos de arranque do kernel antes de premir Enter faça o seguinte:
[NOTE]
====
Esteja ciente de que o mapa do teclado US estará em uso quando escrever +
Ctrl+x significa "Premir e manter a tecla Ctrl ou Control como se fosse uma tecla Shift e pressione a tecla X"
====
----
Prima a tecla
Prima a seta para baixo três vezes
Prima a tecla End
Prima a barra de espaço
Escreva os parâmetros do kernel (exemplos abaixo)
Prima Ctrl+X para arrancar (não prima Enter!)
Prima Enter para arrancar.
----

Por exemplo, para configurar o controlador "speakup" para o equipamento sintetizador, pode escrever um parâmetro do kernel como:
----
speakup.synth=apollo
----
Também pode incluir na linha de comandos de arranque as definições para o seu dispositivo Braille, desta forma:
-----
brltty=<driver code>,<device>,<text table>
-----
Por exemplo, para instalar com um dispositivo Papenmeier ligado por USB com uma tabela de texto Francês, escreva:
-----
brltty=pm,usb:,fr_FR
-----
NOTE: Um dispositivo braile ligado através de USB deve ser sempre reconhecido, talvez apenas a tabela de texto não seja a boa se não tiver introduzido as definições no início.

De qualquer forma, como não há nenhum tempo limite, o arranque só irá começar quando premir [Enter].

A Voz e o Braille estão disponíveis no início da instalação.
// Overview
[[Overview_of_Slint_Installation]]
==== Resumo do processo de instalação

O instalador analisa primeiro as unidades e partições existentes para avaliar as possibilidades e opções de instalação e deixa-lhe escolher entre uma preparação automática ou manual das partições utilizadas pelo Slint.

Se escolher 'manual' são-lhe apresentadas as partições Linux onde o Slint poderia ser instalado (tamanho mínimo 50G), selecione uma delas e escolha o tipo de sistema de ficheiros que o instalador irá criar no mesmo: btrfs, ext4 ou xfs como mencionado em <<prepare_partitions_for_Slint,Opcionalmente prepare partições para o Slint>>

Se escolher 'auto' são-lhe apresentadas as unidades onde o Slint poderia ser instalado (com o tamanho de pelo menos 50G), e o sistema de ficheiros será do tipo btrfs.

No caso do btrfs serão criados sub-volumes para "/" e "/home" com ficheiros comprimidos, e /swap para alojar um ficheiro swap. 'Copy on write' facilitará a criação de "snapshots" e possivelmente reverterá uma atualização de sistema defeituosa. Ferramentas para gerir os "snapshots" estão incluídas no Slint.

Em ambos os modos, o utilizador escolhe quais as partições Linux e Windows existentes que serão automaticamente montadas após o arranque do Slint, e os seus nomes dos pontos de montagem, facilitando o acesso aos sistemas de saída e aos dados do Slint.

Depois é proposto ao utilizador encriptar a partição root do sistema, para evitar o roubo de dados em caso de perda ou roubo da máquina, ou da unidade onde Slint está instalado. Se aceite, o instalador regista a palavra-passe que permite desbloquear esta partição. O utilizador irá ao introduzi-la no momento do arranque quando solicitado pelo GRUB para exibir o menu de arranque.

Depois de tudo, o instalador resume as suas escolhas e deixa-lhe confirmá-las ou não. Até este ponto, nenhuma modificação terá sido feita aos sistemas e dados instalados que possa negar em segurança, depois escreva start novamente ou apenas reinicie sem qualquer dano.

Depois o particionamento auto é feito caso ocorra, a partição root do Slint é encriptada se solicitada, a partição root é formatada e os primeiros pacotes de software são instalados.

Se optou por um disco encriptado, escreva a palavra-passe que será usada para desbloquear a unidade em cada arranque.

Escolhe uma palavra-passe para o utilizador "root". Este é o administrador do sistema, que tem todos os privilégios.

Também se define o nome de acesso e palavra-passe de um utilizador padrão.

Indica se necessitará de uma saída em Braile acessível, e se deseja entrar no modo texto ou gráfico. Se utilizou o idioma Inglês (EUA) durante a instalação, escolha o idioma a utilizar no sistema instalado, caso contrário o instalador define o mesmo que durante a instalação.

O instalador tenta estabelecer uma ligação à Internet, e se tiver sucesso, propõe um fuso horário correspondente à sua localização geográfica que confirma, caso contrário selecione uma numa lista.

É-lhe perguntado se vai precisar de Braille, depois se prefere começar numa consola ou num gráfico, a menos que tenha usado a voz durante a instalação ou precise de Braille: de seguida será deixado numa consola após reiniciar, por segurança.

O instalador cria então um ficheiro swap. Isto pode demorar muito tempo. Seja paciente.

Os pacotes são instalados na unidade. Se tiver sido estabelecida uma ligação à Internet, descarrega e instala a versão mais recente de cada pacote, incluindo os fornecidos desde o lançamento da imagem ISO.

A instalação de todos os pacotes leva cerca de 10 a 40 minutos, dependendo do equipamento.

Ser-lhe-á pedido que selecione um ambiente de trabalho (mesmo que comece numa consola no início) entre fvm, lxqt, mate e wmaker. Outras escolhas estarão disponíveis após a instalação, escrevendo 'xwmconfig', se iniciar numa consola

Em seguida, o sistema é configurado e o gestor de arranque GRUB instalado. O Slint pode arrancar nos modos Legacy e EFI. O menu de arranque incluirá uma entrada de arranque "rescue" para detetar e permitir que qualquer SO instalado seja iniciado.

Pode obter uma pré-visualização do menu de arranque antes de reiniciar.

Depois, remova o meio de instalação e reinicie para iniciar o seu novo sistema Slint.
// Usage_installer
[[Usage_of_the_installer]]
==== Utilização do instalador

Se está à vontade na linha de comandos, pode ignorar este tópico.

O menu principal da instalação é apresentado abaixo:
....
Bem-vindo ao instalador Slint! (versão 15)

Pode agora introduzir (sem os apóstrofos):

'doc' para conhecer as funcionalidades e utilização do instalador.
'start' para iniciar a instalação.

O instalador pode preparar a unidade onde o Slint será instalado criando,
as partições necessárias. Se preferir, pode fazê-lo sozinho/a usando
utilitários de linha de comandos disponíveis no instalador, e depois
escreva 'start' quando concluído. Também pode deixar o instalador e usar uma
ferramenta como o gparted para o fazer, depois inicie o instalador novamente.

Recomendamos que escreva 'doc' primeiro neste caso, ou se quiser
encriptar a partição root do Slint.
Quando terminar de ler, este menu será novamente exibido.
....

Assim que este menu for apresentado, fica responsável do processo de instalação.

Leia o ecrã e escreva comandos num <<virtual_terminal,terminal virtual>>. O instalador inclui 4 terminais virtuais que partilham o mesmo teclado físico e ecrã, que podem ser usados em paralelo.

O instalador começa no terminal virtual 1 chamado *tty1* mas pode trocar para outro. Por exemplo, pode mudar para *tty2* ao premir *Alt-F2,* depois prima Enter para ativá-lo e depois voltar para *tty1* ao premir *Alt-F1,* sem apagar informações apresentadas em ambos os terminais. *Alt-F1* significa: pressione e mantenha a tecla *Alt* e depois prima a tecla *F1*.

Isto pode ser útil para continuar a ler a documentação durante a instalação: por exemplo, pode mudar para *tty2* para iniciar a instalação, mudar para *tty1* para continuar a ler a documentação, depois mudar para *tty1* novamente para prosseguir para a próxima etapa de instalação.

Isso também pode ser usado para consultar o glossário ao ler outros documentos.

O instalador tem vários modos de interação consigo, o utilizador:

* Ecreva comandos no "prompt" e leia o resultado.
* O instalador faz uma pergunta, escreva a resposta e a confirme premindo Enter.
* O instalador mostra um menu de escolhas ou opções: selecione uma delas usando as setas para cima ou para baixo, depois confirme sua escolha premindo Enter, ou cancele premindo Esc.
* O instalador apresenta informações num paginador. Depois, utilize teclas de setas para ler a linha seguinte ou anterior, prima espaço para visualizar a página seguinte, Q para parar de ler o documento.

// Encryption
[[Encryption]]
==== Slint com uma partição root encriptada.

No modo Auto, o instalador propõe encriptar a partição root do sistema. Se estiver de acordo, em cada arranque o carregador de arranque GRUB irá perguntar-lhe a palavra-passe que terá introduzido durante a instalação para desbloquear a unidade, antes de mostrar o menu de arranque. Tenha em atenção que o desbloqueio da unidade demorará alguns segundos (cerca de dez segundos).

Ter um sistema root encriptado impede o roubo de dados que contém em caso de perda ou roubo da máquina, ou de uma unidade removível. Mas isto não o protegerá se o computador continuar a funcionar e sem vigilância, apenas se a máquina tiver sido completamente desligada!

Durante a instalação, a partição do sistema Slint será encriptada e também a partição adicional que poderá solicitar.

Uma partição Slint (ou root) será nomeada: /dev/mapper/cryproot uma vez aberta, se ela tiver sido encriptada.

Isso é mostrado por este comando:

----
lsblk -lpo name,fstype,mountpoint | grep /$
----

Que dá um resultado como:
----
/dev/mapper/cryptroot ext4    /
----

Em vez disso, este comando:

----
lsblk -lpo name,fstype,mountpoint | grep /dev/sda3
----

dá:

----
/dev/sda3             cryptoLUKS
----

/dev/sda3 é agora uma partição "raw" que inclui o chamado "LUKS header" que nunca precisará nem nunca deverá aceder diretamente. Aloja tudo que é necessário para encriptar ou desencriptar a partição /dev/mapper/cryptroot, que na verdade aloja os seus dados (neste exemplo, o sistema Slint).

[WARNING]
====
Se se esquecer da palavra-passe, todos os dados na unidade serão irreversivelmente perdidos! Por isso, anote ou grave esta palavra-passe e coloque o registo num lugar seguro, assim que terminar.

As unidades falham. Se isso acontecer e forem encriptados, os seus dados serão perdidos. Por isso, fazer cópias de segurança dos seus dados regularmente não é opcional.

Além disso, faça uma cópia de segurança do luks header da qual poderá restaurar no caso da partição luks se danificar por qualquer motivo. O comando pode ser como no nosso exemplo:
----
luksHeaderBackup /dev/sda3 --header-backup-file <file>
----
onde <file> é o nome do ficheiro da cópia de segurança, que guardará num local seguro.

Depois, precisaria de restaurar a cópia de segurança, escreva:
----
luksHeaderRestore /dev/sda3 --header-backup-file <file>
----

Não redimensione uma partição de uma unidade encriptada porque depois disso seria definitivamente bloqueada e todos os dados que contém serão perdidos! Se realmente precisa de mais espaço, precisará de fazer uma cópia de segurança de todos os ficheiros que deseja manter, por isso instale novamente e restaure os ficheiros da cópia de segurança.

Escolha uma palavra-passe forte, para que um ladrão demore demasiado tempo a descobrir para que valha a pena.

Nunca mexa com o chamado "LUKS header" localizado na partição raw (a terceira, como por ex. /dev/sda3 para a partição raw em cima da partição do sistema Slint). Na prática: não crie um sistema de ficheiros nesta partição, não o faça parte de uma matriz RAID e por norma, não grave: todos os dados seriam irreversivelmente perdidos!
====

Para evitar palavras-passe fracas o instalador requer que a palavra-passe inclua:

. Pelo menos 8 caracteres.
. Apenas letras minúsculas e maiúsculas não acentuadas, dígitos de 0 a 9, espaço e os seguintes caracteres de pontuação:
+
----
 ' ! " # $ % & ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~
----
+
Isso garante que até mesmo um novo teclado tenha todos os caracteres necessários para introduzir a palavra-passe.

. Pelo menos um dígito, uma letra minúscula, uma letra maiúscula e um carácter de pontuação.

O GRUB assume que o teclado "us" está em uso quando introduz a palavra-passe. Por esta razão, se durante a instalação usar um outro mapa de teclado, antes de perguntar a palavra-passe o instalador irá definir o mapa do teclado como "us" e depois de ter gravado ele restaura o usado anteriormente. Neste caso o instalador também introduzirá cada carácter digitado da palavra-passe, como pode ser diferente daquela apresentada na tecla.

A aplicação criptsetup é usada para encriptar a unidade. Para saber mais, escreva após a instalação: +
-----
man cryptsetup
-----
// Speakup
[[Speakup]]
==== Combinação de teclas para o leitor de ecrã Speakup

Este capítulo destina-se a utilizadores que necessitam de um leitor de ecrã mas não conhecem o Speakup.

Mantenha o numlock desligado para usar o Speakup.

A tecla CapsLock é utilizada como uma tecla shift. Por exemplo, "CapsLock 4" significa: +
manter premida a tecla CapsLock como uma tecla shift e premir 4.

 Primeiras combinações de teclas a lembrar:
 PrintScreen         Alternar speakup on/off.
 CapsLock F1         Ajuda do Speakup (prima Espaço para sair da ajuda).

 Combinação de teclas para alterar definições:
 CapsLock 1/2        Diminuir/Aumentar o volume de som.
 CapsLock 5/6        Diminuir/Aumentar a frequência da voz.

 Combinação de teclas para rever o ecrã:
 CapsLock j/k/l      Dizer Anterior/Atual/Seguinte palavra.
 CapsLock k (twice)  Soletrar palavra atual.
 CapsLock u/i/o      Dizer Anterior/Atual/Seguinte linha.
 CapsLock y          Dizer do topo do ecrã para o cursor de leitura.
 CapsLock p          Dizer da leitura da linha do cursor ao fundo do ecrã.
// First_steps
[[first_steps_after_installation]]
==== Primeiros passos após a instalação

Aqui estão as primeiras tarefas a serem executadas após a instalação

Neste documento, todo o texto depois de um carácter # são comentários dos comandos sugeridos, não a serem introduzidos.

===== Atualização inicial do software

Após a instalação, o sistema deve ser atualizado para obter a mais recentemente fornecida versão de cada software, assim como o novo software fornecido desde a versão da ISO. Isto é especialmente necessário se nenhuma ligação de rede estiver disponível durante a instalação, como então apenas os pacotes incluídos no suporte da distribuição foram instalados, e eles podem estar desatualizados.

A maioria dos comandos introduzidos abaixo solicita um direito administrativo associado a uma conta específica chamada 'root', para o qual gravou uma palavra-passe durante a instalação.

Para emitir um comando como 'root', primeiro escreva
----
su -
----
de seguida, emita a palavra-passe para o root e prima Enter antes de escrever o comando.

Quando terminar de emitir comandos como 'root', pressione Ctrl+d ou escreva 'exit' para obter de volta o estado de "utilizador".

Em alternativa, o utilizador registado durante a instalação e outros membros do grupo 'wheel' podem escrever:
----
sudo <command>
----
depois também a palavra-passe para o root.

Para atualizar, escreva como root numa consola ou terminal gráfico:
----
slapt-get --add-keys # recupera as chaves para autenticar os pacotes
slapt-get -u # atualiza a lista de pacotes nos "mirrors"
slapt-get --install-set slint # obtêm os novos pacotes
slapt-get --upgrade # obtêm as novas versões dos pacotes instalados
dotnew # mostra as alterações nos ficheiros de configuração
----
Quando estiver a executar o dotnew, aceite substituir todos os ficheiros de configuração antigos pelos novos. Isto é seguro, pois ainda não fez nenhuma personalização.

Em alternativa, pode usar estes front-ends gráficos: gslapt em vez do slapt-get, e dotnew-gtk em vez do dotnew.

Para saber mais sobre o slapt-get, escreva:
----
man slapt-get
----
ou como root:
----
slapt-get --help
----
e leia o /usr/doc/slapt-get*/README.slaptgetrc.Slint

// Usage
== Utilização do Slint

Este capítulo apresenta as formas como pode interagir com o seu sistema Slint para que este faça o que deseja.

=== O que é um sistema Slint?

O Slint é um conjunto de softwares que se enquadram aproximadamente nessas categorias:

* O sistema operativo, feito do <<kernel,kernel>> Linux e <<utilities,utilitários.>>. Funciona como uma interface entre o utilizador, as aplicações e o hardware.
* As <<Applications,aplicações>> que executam as tarefas que os utilizadores querem realizar.

O Slint pode ser usado em dois modos distintos pela aparência do ecrã e pela maneira de interagir com o sistema:

* No modo de texto você introduz comandos interpretados por uma <<shell,shell>>. Estes comandos podem iniciar um utilitário ou uma aplicação. O modo de texto também é chamado de modo de <<console,consola>>. Neste modo, o ecrã apenas mostra os comandos e o resultado num fundo (geralmente preto).
* No modo gráfico, elementos gráficos como janelas, painéis ou ícones são exibidos no ecrã, geralmente associados a aplicações ou utilitários. O utilizador interage com estes elementos utilizando um rato ou um teclado.

Os comandos também podem ser introduzidos em modo gráfico dentro de uma janela associada a um <<terminal,terminal>> que executa uma shell.

=== Utilitários fornecidos

Para além dos utilitários encontrados na maioria das distribuições Linux, o Slint inclui ferramentas próprias, herdadas do Slackware e emprestadas ao Salix.

Aqui estão os utilitários que pode utilizar para (re)configurar o seu sistema Slint após a instalação. A utilização de utilitários mais simples é auto-explicativa, a maioria tem uma opção de --help associada, alguns são apresentados em mais detalhes no capítulo <<Manage_your_system,Gerir o seu sistema>>.

Salvo indicação em contrário, estes utilitários devem ser usados como root. Para se tornar root, i.e. obter o estado e privilégios de 'admin' escreva "su -" e depois a palavra-passe do root. Para recuperar o estado de utilizador prima Ctrl+d ou escreva exit.

Em alternativa, pode executar comandos que necessitem de privilégios root, escrevendo "sudo <command>"

A maioria dos utilitários tem uma linha de comandos e uma versão gráfica. A versão da linha de comando será apresentada primeiro abaixo. A menos que todos os comandos referidos de outro modo devem ser introduzidos como root.

*General settings*

* Para gerir utilizadores: usersetup ou gtkusersetup
* Para alterar o idioma e região: localesetup ou gtklocalestup
* Para alterar a configuração do teclado e o método de entrada: keyboardsetup ou gtkkeyboardsetup
* Para configurar a data, a hora ou o fuso horário: clocksetup e gtkclocksetup.
* Para escolher quais serviços iniciam no arranque: servicesetup e gtkservicesetup.
* Para (re)configurar a rede: netsetup.
* Para optar por iniciar no modo texto ou gráfico e posteriormente no gestor de acesso gráfico: login-chooser
* Para escolher um ambiente de trabalho entre FVWM, i3, LXQt, MATE e WindowMaker: session-chooser (como utilizador padrão)
* Para escolher um destes ambientes de trabalho ou um dos gestores de janelas: xwmconfig (como utilizador padrão)
* Para mostrar ou não as aplicações específicas de um ambiente de trabalho noutros ambientes: show-desktop ou hide-desktop (como utilizador padrão)
* Para ativar ou não a voz em modo gráfico: orca-on ou orca-off (como utilizador padrão)
* Para escolher e ativar um leitor de ecrã de consola ou desativar todos eles: speak-with
* Para mostrar ou não entradas de arranque específicas do MATE e/ou LXQt noutros ambientes gráficos: display-desktop ou hide-desktop (como utilizador padrão)
* Para ativar ou desativar o emacspeak ou speechd-el: switch-on ou switch-off (como utilizador padrão)
* Para ver a disposição do menu de arranque do GRUB, visto que será apresentado no próximo arranque: list_boot_entries
* Para gravar uma pen de arranque de recuperação, permitindo o arranque em caso de falha: rescuebootstick
* Para gravar/restaurar as definições do speakup: speakup-save ou speakup-restore
* Para listar as vozes para o espeak-ng, incluindo as do mbrola: list-espeak-ng-voices (como utilizador padrão)
* Para listar as placas de som como: list-cards (como utilizador padrão)
* Para listar os sintetizadores de voz e idiomas associados disponíveis através do speech-dispatcher: spd-list (como utilizador padrão)
 
=== Como inicia o Slint

Após a instalação, o software inserido na ISO de instalação ou transferido de repositórios remotos é instalado numa <<drive,unidade>>.

Quando iniciar o Slint, o <<firmware,firmware>> primeiro verifica o hardware e depois procura por um programa chamado carregador do sistema operativo (vulgarmente chamado de carregador de arranque) que inicia.

Pode haver vários carregadores de SO na máquina. Neste caso o firmware permite ao utilizador escolher qual começar num menu.

No Slint o software que faz e instala um carregador de arranque é o GRUB. Na verdade, o carregador de arranque criado pelo GRUB é também um gestor de arranque, uma vez que permite escolher qual o SO para iniciar se vários estão instalados.

O carregador do SO compilado pelo GRUB pode ser instalado num setor de arranque (no caso de arranque "Legacy") ou num sistema de partição EFI ou ESP (em caso de arranque EFI).

O objetivo do carregador Slint é iniciar o sistema Slint. Para fazer isso primeira carrega o <<kernel,kernel>> na RAM, depois o <<initrd,initrd>>, que por sua vez inicializa o sistema Slint.

Na última etapa desta inicialização, o utilizador foi convidado para "iniciar sessão", noutras palavras para se ligar ao sistema e levar a mão nele. Para fazer isso o utilizador primeiro escreve o nome de utilizador (ou acesso), depois a palavra-passe, de qual a validade é verificada. O Slint como outras distribuições Linux sendo multi-utilizadores, isto permite que este utilizador aceda a um ficheiro, mas não o de outros utilizadores.

No momento da instalação, escolheu iniciar o Slint no modo texto ou gráfico.

* Se escolheu C para o consola <<consola,consola>> após a inicialização do sistema escreva o seu nome de utilizador (ou acesso), depois a palavra-passe, cada entrada sendo confirmada premindo a tecla Enter e depois pode escrever comandos.
* Se escolheu o G (gráfico) escreva as mesmas informações num <<display_manager, gestor de acesso>> ou o gestor de início de sessão, que então inicia o <<graphical_environment,ambiente gráfico>>.

Após a instalação, pode alterar o modo de digitação escrevendo como root `login-chooser`, no modo de consola, bem como no modo gráfico (num <<terminal,terminal>>). Este comando permite escolher `texto` (sinónimo do modo consola), ou, para o modo gráfico, entre vários gestores de acesso. A sua escolha efetivada no próximo arranque do computador.

Agora apresentaremos os ambientes gráficos, e depois como usar uma shell.

=== Os Ambientes Gráficos

<<the_windows,As janelas>> +
<<the_work_spaces,As áreas de trabalho>> +
<<the_desktop,O ambiente de trabalho>> +
<<the_top_panel,O painel superior>> +
<<the_bottom_panel, O painel inferior>> +
<<the_slint_control_center,O Centro de Controlo do Slint>> +
<<graphical_terminals,Terminais gráficos>> +
<<key_bindings,Combinação de teclas>>

Um ambiente gráfico completo inclui vários componentes, entre os quais um gestor de janelas que desenha janelas no ecrã associadas a aplicações, move, redimensiona e fecha estas janelas.

O Slint inclui vários ambientes gráficos: BlackBox, Fluxbox, FVWM, i3, LXQt, MATE, TWM e WindowMaker. É uma questão de preferência qual deles escolher.

O LXQt MATE e o XFCE são ambientes de trabalho completos, o FVWM e o WindowMaker oferecem funcionalidades únicas e podem ser selecionados com o gestor de sessões gráfico do lightdm e também iniciados a partir de uma consola escrevendo "startx". Os outros são principalmente gestores de janelas que só podem ser iniciados a partir de uma consola. Todos permitem aceder aos seus documentos e aplicações, geralmente abertos numa janela.

Pode escolher entre FVWM, i3, LXQt, MATE e WindowMaker ao escrever `session-chooser` como utilizador padrão. No modo gráfico, também é possível escolher um ao iniciar sessão.

Para escolher um dos outros ambientes gráficos, é necessário utilizar o comando "xwmconfig".

[NOTE]
====
se quiser usar o i3 e necessitar de voz, recomendamos que inicie sessão em modo de texto e execute **i38** antes de **startx**.
====

Iremos agora descrever brevemente os componentes do ambiente de trabalho Mate, que é o predefinido e também o mais acessível com voz e braille.

Utilizando o rato, pode descobrir as funcionalidades de cada componente fazendo ou simulando um clique direito, meio ou esquerdo. Mova ou elimine a maioria dos componentes, modifique-os e adicione novos componentes.

Estes componentes podem ser alcançados ao mover o rato e também através das teclas de atalho. Nós indicamos abaixo entre parênteses as teclas de atalho que permitem alcançar, por outras palavras, colocamos o foco em cada elemento. Também vamos resumir as <<key_bindings,combinação de teclas>> para o ambiente de trabalho Mate (ao usar o gestor de janelas padrão Marco) e as do gestor de janelas do Compiz.

[TIP]
====
Pode descobrir a maioria das funcionalidades de aplicações e outros componentes do Slint com um clique no botão direito ou esquerdo do rato. Por exemplo, ao clicar no painel, a barra de título, os botões à esquerda e direita de qualquer janela, um ícone no painel ou num espaço vazio do ecrã.
====
[[the_windows]]
==== As janelas

Uma janela é uma área retangular associada a uma aplicação. As janelas podem ser movidas, redimensionadas, maximizadas, restauradas reduzidas, fechadas (terminando a aplicação que lidam) usando os atalhos do rato ou teclado.

[[the_work_spaces]]
==== As áreas de trabalho

Para permitir ter um monte de janelas abertas de forma ordenada, o ambiente gráfico fornece várias áreas de trabalho e permite alternar entre elas. Cada área de trabalho mostrará a mesma área de trabalho e painéis, mas as janelas podem ser colocadas numa área de trabalho específica ou em todas elas. Esta configuração está disponível com um clique no botão direito do canto superior da janela. Mudar para outra área de trabalho pode ser feito clicando na sua posição no painel inferior do ecrã, no área de trabalho, conforme indicado abaixo.

[[the_desktop]]
==== A área de trabalho

A área de trabalho engloba todo o ecrã, para onde outros componentes podem ser inseridos, no caso do Mate e como incluído no Slint um painel superior e inferior e quatro ícones que de cima para baixo permitem abrir nas janelas:

* o diretório root no gestor de ficheiros
* a sua pasta pessoal no gestor de ficheiros
* o Centro de Controlo do Slint
* o lixo, onde são colocados os ficheiros que pretende eliminar, mas não ainda.

Janelas de aplicação que se iniciam como também colocadas na área de trabalho.

O Mate inclui dois painéis, que se apresentam como áreas horizontais retangulares finas, um na parte superior e outro na parte inferior do ecrã.

Pressionar Ctrl+Alt+Tab permite alternar entre as áreas de trabalho, a parte superior e a parte inferior dos painéis

Pressionar Alt+Tab permite percorrer entre as janelas na área de trabalho.

[[the_top_panel]]
==== O painel superior

Apresenta, da esquerda para a direita:

* Três menus:
** Um menu de Aplicações que pode ser aberto premindo Alt+F1. A partir daí, pode abrir os outros menus usando a tecla de seta para a direita. Pode utilizar as teclas de seta para baixo e para cima para navegar em cada menu.
** Um menu de Locais.
** Um menu do sistema que dá acesso a um sub-menu de preferências, o Centro de Controlo do Mate e botões para obter ajuda sobre o ambiente de trabalho, bloquear o ecrã, terminar a sessão e desligar o computador.
* Lançadores de aplicações para o terminal-mate, o gestor de ficheiros Caja, o cliente de e-mail Thunderbird, o navegador Firefox, o editor de texto Geany.
* Uma área de notificações que pode juntar mini-aplicações como um gestor de Bluetooth, um misturador de som, um gestor de rede e um notificador de "atualizações disponíveis".
* Um relógio e calendário.
* Um bloqueador de ecrã.
* Uma caixa de diálogo de terminar sessão.
* Uma caixa de diálogo para encerrar.

[TIP]
====
* Para personalizar o painel conforme o seu gosto: clique com o botão direito num espaço vazio do painel.
* Se deseja mover um item no painel: Dê duplo clique com o botão do meio no elemento, arraste o rato e ele seguirá o rato até que o botão do meio seja largado.
* Para uma ajuda contextual prima F1
====

[[the_bottom_panel]]
==== O painel inferior

Apresenta, da esquerda para a direita:

* Uma lista de janelas que pode ser configurada com um clique direito na linha de três pontos verticais no início e na escolha de preferências. Isto também permite iniciar o monitor do sistema numa janela.
* Um botão *mostrar a área de trabalho*. Um clique com o botão esquerdo vai minimizar ou ocultar todas as janelas, ao clicar novamente irá restaurar as janelas no seu estado anterior.
* Um alternador de área de trabalho, ou paginador. O mesmo permite mudar de uma área de trabalho para outra e também mover as janelas de uma área de trabalho para outra ao arrastar e largar.

[[the_slint_control_center]]
==== O Centro de Controlo do Slint

Terminaremos esta introdução ao uso do Slint apresentando o Centro de Controlo do Slint. Pode vê-lo a partir do menu de aplicações no painel superior ou clicar no seu ícone na área de trabalho ou escrever qcontrolcenter numa caixa de diálogo "Executar..." invocada com Alt+F2

O objetivo do painel de controlo é reunir aplicações que sejam úteis para a administração do sistema. documentação e definições de forma consistente em todos os gestores de janelas. Ao clicar numa categoria no menu à esquerda, pode mostrar as aplicações correspondentes no painel à direita. Iremos apresentá-las em formato de tabela. Isto dá-nos a oportunidade de apresentar as ferramentas de administração que também possuem uma interface gráfica.

A maioria das ferramentas administrativas deve ser utilizada com privilégios administrativos. Será requisitada a palavra-passe da conta root para iniciar uma ferramenta.

[options="autowidth"]
|====
<|**Categoria <|**Ferramenta** <|**Propósito e comentários**
<|Aplicações <|Dotnew <|Esta ferramenta permite-lhe gerir o novo (chamado __something.new__ daí o nome da ferramenta) versus os ficheiros de configuração antigos depois de ter actualizado alguns pacotes. É um bom hábito executá-lo depois de uma atualização. Dir-lhe-á se há algo a tratar e depois apresentar-lhe-á uma escolha de ações.
<|Aplicações <|Gestor de Pacotes Glapt <|O Gslapt é um front-end gráfico para slapt-get. É uma ferramenta útil para realizar <<software_management,gestão de software no Slint>>. Permite-lhe procurar, instalar, remover, actualizar e configurar pacotes de software.
<|Aplicações <|Gestor de SlackBuild Sourcery <|O Sourcery é um front-end gráfico para slapt-src. Permite-lhe procurar por scripts SlackBuilds que pode depois utilizar para automatizar o processo de construção e instalação de pacotes de software. Pode também remover e reinstalar pacotes no seu sistema.
<|Aplicações <|Localizador de Aplicações <|Localizar e iniciar as aplicações instaladas no sistema. O campo de pesquisa é muito útil para encontrar aplicações em comparação com a pesquisa manual no menu de aplicações.
<|Informação <|SlackDocs Website <|Os documentos nesta wiki destinam-se principalmente a um utilizador de Slackware, mas muitos deles são úteis para um utilizador do Slint. **Cuidado:** Algumas das ferramentas listadas, como o slackpkg, **não** devem ser usadas no Slint.
<|Informação <|Documentação de Slackware <|Esta documentação também pode ser útil para os utilizadores do Slint. O Slint é baseado no Slackware.
<|Informação <|Monitor de Sistema MATE <|Esta ferramenta exibe informação sobre o sistema, como o processo, utilização de recursos (RAM, CPU, tráfego de rede) e utilização do sistema de ficheiros.
<|Informação <|Documentação do Slint <|Isto dá acesso local a documentos também disponíveis no website do Slint.
<|Informação <|Fórum do Slint <|Pessoas cuja língua materna não seja o Inglês podem também publicar nos fóruns localizados do Salix.
<|Informação <|Slint Website <|O website do Slint fornece documentação, ligações e uma forma de encontrar as ISOs e pacotes.
<|Informação <|Informação do sistema <|Esta ferramenta recolhe informações sobre o computador, tais como os seus dispositivos ligados (internos e externos), e apresenta tudo num único local. Pode também efetuar um "benchmarking" do sistema.
<|Sistema <|Mostrar menu de arranque <|Mostra a disposição do menu de arranque como será apresentado no próximo arranque
<|Sistema <|Relógio do Sistema <|Esta ferramenta permite-lhe definir o relógio do sistema.
<|Sistema <|Teclado <|Esta ferramenta permite-lhe configurar a disposição do teclado.
<|Sistema <|Idioma do Sistema <|Esta ferramenta permite-lhe definir o "locale" do sistema (peculiaridades linguísticas e geográficas), para que as aplicações que utiliza exibam informação neste "locale" (se disponível).
<|Sistema <|Relógio do Sistema <|Esta ferramenta permite-lhe definir o fuso horário, escolher se o relógio deve ser sincronizado com servidores de Internet (isto é recomendado mas, claro, necessita de uma ligação à Internet), e se não, definir a data e a hora.
<|Sistema <|Serviços do Sistema <|Esta ferramenta permite-lhe escolher quais os serviços que serão ativados no arranque. Por exemplo, o Bluetooth, o servidor de impressão CUPS, ou um servidor Web. Utilize-o apenas para alterar as definições predefinidas se souber o que está a fazer.
<|Sistema <|Utilizadores e Grupos <|Esta ferramenta permite-lhe adicionar, remover, e configurar contas de utilizador e grupos. É sobretudo útil em sistemas multi-utilizador.
<|Sistema <|Gestor de arranque GUEFI <|Esta ferramenta é um front end gráfico para o comando efibootmanager. Permite a edição do menu de arranque do firmware EFI com acções como adicionar, remover itens ou alterar a ordem dos itens do menu.
<Sistema <|Pen de recuperação de arranque <|Esta ferramenta permite colocar numa pen USB tudo o que é necessário para arrancar o Slint se não o for possível da forma habitual

|====

[[graphical_terminals]]
==== Terminais

Pode escrever comandos em modo gráfico como em modo de consola, se abrir uma janela com um terminal dentro. No Mate basta apenas pressionar Ctrl+Alt+t, ou clicar no ícone do mate-terminal no painel superior, ou abra uma caixa de diálogo "Executar... " pressionando Alt+F2, e depois ao escrever `mate-terminal` na pequena janela que se abre.

A maioria das informações abaixo sobre a linha de comandos e a shell no modo Consola também se aplicam a comandos de digitação num terminal. Pode de fechar o mate-terminal premindo Alt+F4 como em qualquer outra janela.

[[key_bindings]]
==== Combinação de teclas

Apresentamos aqui as combinações de teclas predefinidas para o gestor de janelas Compiz e ambiente de trabalho Mate e como personalizá-las.

[NOTE]
====
Quando a combinação de teclas inclui um ou mais sinais de **+**, pressione e mantenha da esquerda para a direita as teclas antes da última, como uma tecla `Shift` e depois pressione a última tecla.
====
===== Combinação de teclas para o ambiente de trabalho Mate

Ao usar o Mate no Slint, algumas combinações de teclas são as mesmas ao usar os gestores da janela Marco ou Compiz. As mesmas estão listadas abaixo:
----
Alt+Tab               Percorrer entre janelas
Shift+Alt+Tab         Percorrer de trás para a frente entre janelas
Control+Alt+Tab       Percorrer entre painéis e a área de trabalho
Shift+Control+Alt+Tab Percorrer de trás para a frente entre painéis e a área de trabalho
----
Uma vez num ambiente gráfico, pode alternar entre o mesmo e uma consola. Digamos que quer usar o tty2 (estando o tty1 ocupado): Prima `Ctrl+Alt+F2` e depois inicie sessão. +
Prima `Alt+F7` para voltar ao ambiente gráfico.

As mesmas combinações de teclas são usadas em todos os ambientes gráficos, com algumas exceções, sendo o Mod1 geralmente a tecla esquerda Alt: +
----
Mod1+F1 apresenta o menu de aplicações do painel.
Mod1+F2 apresenta uma caixa de diálogo 'executar..', mas no Fluxbox (inicia o lxterminal ao invés).
----
Também no Fluxbox:
----
Mod1+F3 reinicia o Fluxbox.
Mod1+F4 fecha a janela focada.
----

No Mate, os utilizadores com visão parcial podem usar o gestor de janelas Compiz ou o Marco que é o padrão.

Como utilizador, escreva:
----
gsettings set org.mate.session.required-components windowmanager compiz
----
Para voltar ao Marco:
----
gsettings set org.mate.session.required-components windowmanager marco
----
Esta configuração terá efeito no próximo início de uma sessão Mate.

Ou para fazer a alteração apenas para o tipo de sessão atual:
----
compiz --replace &
----
e voltar para o Marco:
----
marco --replace &
----
A substituição terá efeito imediatamente.

Essa configuração também está disponível graficamente no mate-tweak, na categoria de Janelas.

Pode aceder às definições específicas do Compiz ao escrever:
----
ccsm &
----
===== Combinação de teclas para o gestor de janelas Compiz

Nas definições predefinidas indicadas abaixo, os botões das teclas ou do rato são assim nomeados:

Super: Tecla Windows na maioria dos teclados +
Botão1: Botão esquerdo do rato (se usado com a mão direita) +
Botão2: Botão central do rato (ou clique com a roda do rato)  +
Botão3: Botão direito do rato (se usado com a mão direita) +
Botão4: Roda do rato para cima +
Botão5: Roda do rato para baixo Botão6: (Não sei, pensei que fosse em ratos para jogadores) +

As definições predefinidas listadas abaixo por categoria podem ser alteradas a partir do CCSM. Indicamos o nome abreviado do plugin entre parênteses retos.

. Categoria Geral
+
[core] General options, tab "key bindings": +
close_window_key = Alt+F4 +
raise_window_button = Control+Button6 +
lower_window_button = Alt+Button6 +
minimize_window_key = Alt+F9 +
maximize_window_key = Alt+F10 +
unmaximize_window_key = Alt+F5 +
window_menu_key = Alt+space +
window_menu_button = Alt+Button3 +
show_desktop_key = Control+Alt+d +
toggle_window_shaded_key = Control+Alt+s +
+
[matecompat] Compatibilidade Mate +
main_menu_key = Alt+F1 +
run_key = Alt+F2 +

. Categoria Acessibilidade
+
[addhelper] Escurecimento inativo (menos luz em janelas não focadas) +
toggle_key = Super+p +
+
[colorfilter] (Filtro de cor para fins de acessibilidade) +
toggle_window_key = Super+Alt+f +
toggle_screen_key = Super+Alt+d +
switch_filter_key = Super+Alt+s +
+
[ezoom] Ampliação do ambiente gráfico +
zoom_in_button = Super+Button4 +
zoom_out_button = Super+Button5 +
zoom_box_button = Super+Button2 (diminuir a ampliação para voltar ao normal) +
+
[neg] Negativo (alternar as cores inversas da janela ou ecrã) +
window_toggle_key = Super+n +
screen_toggle_key = Super+m +
+
[obs] Ajustes de opacidade, brilho e saturação +
opacity_increase_button = Alt+Button4 +
opacity_decrease_button = Alt+Button5 +
+
[showrato] (Aumentar a visibilidade do cursor do rato) +
initiate = Super+k +

. Categoria Gestão de Janelas
+
[move] Mover janela +
initiate_button = Alt+Botão1 (manter pressionado o Botão1 enquanto se move o rato) +
initiate_key = Alt+F7 (Esc para parar de se mover) +
+
[resize] Redimensionar janela +
initiate_button = Alt+Botão2 (manter pressionado o Botão2 enquanto move o rato) +
initiate_key = Alt+F8 (Esc para parar de se mover) +
+
[switcher] Comutador de aplicações (troque entre janelas ou painéis e
                                 a área de trabalho) +
next_window_key = Alt+Tab (percorrer entre janelas) +
prev_window_key = Shift+Alt+Tab +
next_panel_key = Control+Alt+Tab (percorrer entre janelas e áreas de trabalho) +
prev_panel_key = Shift+Control+Alt+Tab +

===== Como adicionar uma combinação de teclas personalizadas para o Mate.

Vamos dar um exemplo: queremos que Alt+F3 inicie o Firefox. Escreva num terminal ou no comando Executar (invocado ao pressionar Alt+F2):
----
mate-keybinding-properties
----
Na nova janela é possível usar as teclas de setas para baixo e para cima para navegar na lista de teclas de atalho existentes.

Para definir uma nova combinação de teclas, prima Tab duas vezes para colocar o cursor no Adicionar, de seguida prima Enter. Na pequena caixa de diálogo que é apresentada escreva o nome da tecla personalizada tal como o Firefox, prima Tab, escreva o nome para o comando associado neste caso, Firefox, e depois prima Tab duas vezes para colocar o cursor no Aplicar e prima Enter.

Para ativar a nova combinação de teclas, navegue até encontrá-la na parte inferior da lista, prima Enter e depois Alt+F3.

Da próxima vez que premir Alt+F3 deverá iniciar o firefox

=== A shell

NOTE: Este capítulo é uma breve introdução. Informações mais aprofundadas são fornecidas no documento https://slint.fr/doc/shell_and_bash_scripts.html[Shell e bash scripts], na sua maioria emprestado do SUSE.

Quando o computador inicia em modo de consola, depois de ter iniciado sessão com o seu nome de utilizador e palavra-passe, a <<shell,shell>> mostra uma "janela" como a que se segue: +
`hugo@darkstar:~$` +
Neste exemplo:

* `hugo` é o nome do utilizador
* `darkstar` o nome da máquina
* o til `~` representa a pasta pessoal do utilizador, neste exemplo `/home/hugo`
* o sinal de dólar `$` indica que o utilizador é um "comum" e não um "super utilizador" (veja abaixo).

O cursor é posicionado depois da "janela".

O utilizador agora pode escrever um comando na linha (aqui o nome de "linha de comandos") e confirmar ao premir Enter. A shell analisa então o comando e executa-o se for válido, caso contrário emite uma mensagem como, por exemplo, "comando não encontrado". Pode editar o comando antes de premir Enter usando as setas esquerda e direita e as teclas Backspace, Home, End e Del.

Durante a sua execução, os comandos podem exibir um resultado no ecrã ou não. Em todos os casos, após a sua execução, o "prompt" será exibido novamente numa nova linha. significando que a shell está à espera do próximo comando a ser introduzido.

Para que isto funcione, o utilizador precisa de saber quais comandos estão disponíveis e sua sintaxe. Alguns comandos são executados pela própria Shell, outros iniciam programas externos. Em baixo vários exemplos de comandos são dados, mais são listados em https://slint.fr/doc/shell_and_bash_scripts.html[Shell e bash scripts]

Existem várias shells disponíveis para Linux à escolha; no Slint a shell utilizada por padrão chama-se *bash*.

Para permitir a execução de vários programas ao mesmo tempo, o Linux fornece várias "consolas virtuais" partilhando depois o mesmo teclado e ecrã, numerados a partir de um. Inicialmente, o sistema inicia na consola (ou terminal virtual) número um, também chamado *tty1* (o nome tty é uma abreviatura de "teletype"). A partir de lá, o utilizador pode mudar para outra consola ou tty; por exemplo, mude para o número tty dois pressionando Alt+F2, onde outra shell irá perguntar novamente o nome e palavra-passe do utilizador. Para alternar para tty1, basta pressionar Alt+F1. Por padrão no Slint, seis tty estão disponíveis, mas isto pode ser alterado editando o ficheiro /etc/inittab.

Quando a shell é utilizada num ambiente gráfico (num terminal gráfico), o seu comportamento é o mesmo, mas a janela é ligeiramente diferente, como ilustrado abaixo: +
`hugo[~]$` +

Pode alternar entre a consola e o ambiente gráfico:

* Do ambiente gráfico premindo por exemplo Ctrl+Alt+F3 para ir para tty3. Na primeira vez que for a um tty, terá que escrever o nome de acesso e palavra-passe.
* De uma consola ou tty pressionando Alt+F7 se o ambiente gráfico já estiver em execução, caso contrário escreva `startx` para o iniciar.

==== Introduzindo comandos como root

*root* is the conventional name of the "super user" which have all rights to do administrative tasks, including those that could harm or even destroy the system.

Pode (mas isto não é recomendado para principiantes) iniciar sessão diretamente como root. Para fazer isto, escreva *root* como utilizador e depois a palavra-passe do root. Para o informar (e avisá-lo sobre os riscos e responsabilidades associados), a janela vai-se parecer com isto: +
*root@darkstar:s~#* +
o carácter # (sinal de número, vulgarmente chamado de cardinal) indica que os comandos serão introduzidos como root (não como utilizador padrão), com os direitos que lhe estão associados, mas também com riscos e responsabilidades.

Se já tem sessão iniciada como utilizador, pode-se "tornar-se root" escrevendo: +
*su -* +
e depois prima Enter. Neste comando, `su` (que significa "Super Utilizador") é o nome do comando, e o carácter *-* (hífen, também chamado de menos) informa que está a abrir uma "shell de acesso": primeiro ser-lhe-á perguntado pela palavra-passe do root, depois será direcionado para o diretório /home/root como se tivesse acedido como root no arranque. Isto irá evitar gravar ficheiros no seu diretório inicial inadvertidamente como utilizador padrão(/home/hugo no exemplo) que causam problemas mais tarde.

O utilizador padrão registado durante a instalação e outros membros do grupo 'wheel' também podem escrever comandos reservados ao root antes do nome do comando ao escrever 'sudo' como este, por exemplo: +
*sudo update-grub*

=== Como resolver problemas de bloqueio

O "bloquear o problema" significa "um problema que evita o uso do Slint" como:

* O sistema falha ao arrancar.
* O sistema inicia, mas a sequência de inicialização é interrompida antes da conclusão. Isto pode acontecer por exemplo, se a partição do sistema root não puder ser montada por causa de um erro em /etc/fstab, um sistema de ficheiros root corrompido ou um módulo kernel em falta para montar a partição root, ou o sistema arranca com sucesso, mas não se lembra da palavra-passe do root.

Se o sistema falha completamente ao arrancar, tente cada uma das soluções abaixo em sequência, até que uma funcione.

. Se isto ocorrer após uma atualização do kernel, tente a segunda entrada de arranque ao invés da primeira.
. Tente reiniciar a partir da pen USB de recuperação que solicitou no fim da instalação.
. Vá ao Slint para repará-lo, conforme explicado abaixo.

Pode sempre obter ajuda por correio eletrónico slint@freelists.org fornecendo toda a informação que possa ajudar a investigar o problema. Se ainda não o fez, primeiro subscreva a lista por e-mail slint-request@freelists.org com o assunto 'subscribe', depois responda ao e-mail que irá receber. Apenas se tiver um problema utilizando o e-mail, solicite ajuda no canal IRC #slint, server irc.libera.chat e permaneça no canal até alguém responder.

Vamos agora explicar como ir para o Slint afim de o reparar.

<<Start_the_installer,Inicia o instalador e identifica a partição root do Slint>> +
<<Issue_the_needed_commands,Emita os comandos necessários para ir para o Slint>>. +
<<Repair_Slint,Reparar o Slint a partir do Slint.>>

[[Start_the_installer]]
==== Iniciar o instalador e identificar a partição root do Slint

Se a sequência inicial for interrompida, vá ao Slint a partir do seu instalador para tentar resolver o problema. Insira ou ligue o suporte de instalação (pen USB ou DVD onde gravou a instalação ISO) e siga as instruções abaixo.

. Inicie o instalador.
. Assim que tiver iniciado sessão como root, para listar as unidades e partições, escreva:
+
----
lsblk -lpo name,size,fstype
----
. Encontre no resultado o nome da partição root do Slint, verificando o tamanho e tipo de sistema de ficheiros, legendado como FSTYPE.
. Montar esta partição
+
----
mount /dev/sda3 /mnt
----
+
[NOTE]
====
Se o sistema de ficheiros root do Slint for btrfs (como indicado pelo resultado de "lsblk") é necessário montá-lo usando as opções mencionadas no seu /etc/fstab.

Neste caso é necessário utilizar as mesmas opções que em Slint em btrfs, por isso escreva ao invés:
----
mount /dev/sda3 /mnt -o subvol=/@,compress=zstd:3
----
====
. Verifique se a partição é a correta. Por exemplo, se for /dev/sda3, escreva:
+
----
cat /etc/mnt/etc/slint-version
----
+
Assumindo que instalou o Slint64-15.0, o resultado deve ser: *Slint 15.0*
+
Se o resultado for "ficheiro não encontrado", a partição não é aquela que procurava. Apenas neste caso, escreva:
+
----
umount /mnt
----
+
depois tente outra, voltando à lista de unidades e partições.

[[Issue_the_needed_commands]]
==== Emita os comandos necessários para ir para o Slint

. montar os sistemas de ficheiros /proc /sys e /dev escrevendo:
+
----
mount -B /dev /mnt/dev
mount -B /proc /mnt/proc
mount -B /dev /mnt/sys
----
+
. Emita os próximo comandos para "ir para" o seu Slint e montar todos os dispositivos mencionados no seu /etc/fstab:
+
----
chroot /mnt
mount -a
----

[[Repair_Slint]]
==== Reparar o Slint a partir do Slint

A partir do Slint pode modificar o sistema para resolver o problema. Aqui estão alguns exemplos:

* Executar "update-grub". +
* Executar "grub-emu" ou "list_boot_entries" +
* Reinstalar o GRUB usando o comando "grub-install nome_da_unidade", sendo o nome da_unidade a unidade onde instalar o Slint. +
* Escreva "passwd" para alterar a palavra-passe do root. +
* Remova, instale ou atualize pacotes.

. Quando terminar, remova o suporte de instalação e depois escreva:
+
----
exit
reboot
----

[[Accessibility]]
== Acessibilidade

Se escolheu manter a voz quando solicitado no início da instalação, será ativado no iniciar numa consola como em ambientes gráficos.

=== Usar o Slint com braile

O Slint inclui o software brltty para lidar com ecrãs de braile.

As suas definições, feitas antes de iniciar na linha de comandos ou depois, são registadas no sistema instalado em /etc/brltty.conf.

Um manual abrangente para brltty está disponível em Inglês, Francês e Português em vários formatos, incluindo em texto simples (txt) neste URL: https://mielke.cc/brltty/doc/Manual-BRLTTY/

Se o braile não foi ativado durante a instalação ou foi desativado, para o ativar faça isto:

. Tornar o /etc/rc.d/rc.brltty executável escrevendo como root:
+
----
chmod 755 /etc/rc.d/rc.brltty
----
. Torne-se membro do grupo braile, escrevendo como root:
+
----
usermod -G braille -a nome_do_utilizador
----
+
No comando acima, substitua o nome de utilizador pelo seu nome de utilizador.

Para desativar o braile, escreva como root:
----
chmod 644 /etc/rc.d/rc.brltty
----

=== Voz em ambientes gráficos

Como um lembrete de voz em ambientes gráficos usando o leitor de ecrã Orca é ativado ao escrever:
----
orca-on
----

Para saber como usar o Orca, incluindo as suas combinações de teclas específicas, escreva:
----
man orca
----

Em suma, num ambiente gráfico:
----
Insert+Space: mostraa a janela de Preferências do Orca.
Insert+S: ativa ou desativa a síntese vocal.
Insert+H: ativa o modo de aprendizagem. Neste modo:
   Prima uma tecla para ouvir a sua função
   F1: para ouvir a documentação do leitor de ecrã
   F2: lista as teclas de atalho do Orca
   F3: lista o teclado da aplicação atual
   Esc: fim do modo de aprendizagem
----

=== Vozes e TTS no Slint

Os seguintes TTS (sintetizadores de Texto para Voz) são disponibilizados com o Slint64-15.0 cada um com um conjunto de vozes, nomeadamente: +
espeak-ng +
flite +
pico +
mbrola +
RHVoice +

Na maioria das vezes este TTS e vozes e linguagens associadas são geridas pelo "speech-dispatcher" (expedidor de voz) através de seus chamados "módulos" (aproximadamente, um módulo está associado a um TTS).

O utilitário personalizado spd-list pode responder a várias perguntas sobre os sintetizadores, vozes e idiomas disponíveis. Ao introduzir spd-list isto é exibido:
----
Este "script" lista idiomas e sintetizadores disponíveis para aplicações
baseado no "Speech Dispatcher", tais como o Orca ou Speech-up. Cada comando abaixo responde à pergunta que se lhe segue.
Não escreva as aspas que rodeiam o comando.
"/usr/bin/spd-list" utilização?
"/usr/bin/spd-list -s" sintetizadores disponíveis?
"/usr/bin/spd-list -l" códigos de idioma disponíveis?
"/usr/bin/spd-list -ls <synthesizer>" idiomas disponíveis para este sintetizador?
"/usr/bin/spd-list -sl <language code>" sintetizadores que fornecem vozes neste idioma?
O código do idioma tem na maioria das vezes dois caracteres, como 'en' 'es' ou 'fr'
----
Todas as vozes listadas estão disponíveis no Orca e speechd-up e também no Fenrir se configurado para usar o "speech-dispatcher".

Pode obter vozes adicionais para o flite e mbrola, associadas aos módulos flite-generic e espeak-ng-mbrola-generic.

Pode sempre saber quais estão instalados ou não escrevendo como root um destes comandos:
----
slapt-get --search mbrola-voice
slapt-get --search flite-voice
----
depois instale um dos ainda não instalados, como por ex.
----
slapt-get -i mbrola-voice-pt1
----
Além das vozes gratuitas incluídas no Slint, pode comprar vozes para: +
voxin, https://oralux.org/voice.php +
voxygen, enviando um e-mail para contact@hypra.fr

Mais vozes e sintetizadores podem ser disponibilizados mais tarde, isto será anunciado na lista de correio do Slint e neste http://slackware.uk/slint/x86_64/slint-15.0/ChangeLog.txt[Registo de alterações]

As teclas de atalho para ambientes gráficos estão listados em <<key_bindings,Combinação de teclas>>.

=== Use o gestor de sessões lightdm com voz

No lightdm, premir F4 liga ou desliga o som. Inicialmente, o cursor está no campo da palavra-passe. Premir Tab leva ao "botão de acesso", e depois para a lista de utilizadores ou "caixa de seleção". Nesta lista, premir espaço mostra o utilizador selecionado atualmente. Use as teclas de setas para escolher outro e escreva a palavra-passe correspondente. Em vez disso, escolha "Outro..." adiciona um campo onde pode escrever o nome de acesso de um utilizador não listado. Ainda no lightdm, o F10 abre um menu permitindo reiniciar ou encerrar e Alt+F4 abre diretamente uma interface(UI) com os botões para encerrar ou cancelar.

=== Escolha um leitor de ecrã de consola

Slint fornece estes leitores de ecrã de consola: +
espeakup +
speehchd-up +
fenrir

Além disso, vários equipamentos de sintetizadores de voz podem ser usados no modo de consola, ao usar o speakup.

Para escolher um leitor de ecrã, execute como root este comando:
----
speak-with
----
Aqui está o resultado sem argumento:
----
root[~]# speak-with
Utilização: /usr/sbin/speak-with <screen reader> or <hard synthesizer> ou nenhum
Escolher um leitor de ecrã de consola para falar com:
  espeakup (Leitor de ecrã de consola a ligar o espeak-ng e speakup)
  fenrir (Leitor de ecrã de consola modular, flexível e rápido)
  speechd-up (Leitor de ecrã de consola a ligar o Speech Dispatcher e speakup)
ou utilizar um dos sintetizadores suportados:
  acntsa apollo audptr bns dectlk decext ltlk soft spkout txprt
ou escreva "/usr/sbin/speak-with none" para silenciar todos os leitores de ecrã.
root[~]#
----
Os equipamentos de sintetizadores de voz listados estão disponíveis no kernel em execução ou incluídos como módulos.

Exemplo de comandos e resultados associados:

----
root[~]# speak-with speechd-up
A iniciar o speechd-up
O speechd-up também deve ser iniciado no próximo arranque? [Y/n]
OK
root[~]# Concluído.
----
Assim que escrever o comando, os leitores de ecrã previamente utilizados serão interrompidos e o speechd-up começará a falar.

Se responder Y (sim) (o padrão), à pergunta: +
Deve o speechd-up ser iniciado no próximo arranque? +
o speechd-up continuará a ser usado no próximo arranque. +
Se, em vez disso, responder n (não) ao leitor de ecrã usado, antes de escrever speak-with speechd-up o mesmo será usado após o próximo arranque.

Outros exemplos:

----
root[~]# speak-with apollo
A parar o speechd-up...
O apollo também deve ser utilizado no próximo arranque? [Y/n]
OK
root[~]# Concluído.

root[~]# speak-with none
Também quer uma consola muda no próximo arranque? [Y/n]
OK
root[~]#
----

=== Configurar um leitor de ecrã de consola

O Slint gere os equipamentos de sintetizadores de voz utilizando o speakup e fornece os leitores de ecrã espeakup e speechd-up.

Pode gravar as definições que faz, por exemplo, para aumentar ou diminuir a taxa do seech ou o volume do som. Basta escrever como root: speakup-save. Iso grava todas as definições atuais, incluindo as específicas para o equipamento sintetizador em uso, caso ocorra.

Todas essas definições serão restauradas no próximo arranque: os scripts de inicialização rc.espeakup e rc.speechd-up executam o comando speakup-restore por si.

Se não quiser restaurar as definições gravadas, escreva como root: +
chmod -x /usr/sbin/speakup-restore

Se as tiver restaurado, escreva novamente como root: +
chmod +x /usr/sbin/speakup-restore

Aqui estão algumas combinações de teclas para as definições do speakup, bem como as do speechd-up:
----
spk_f9   punctuation_level_decrease
spk_f10  punctuation_level_increase
spk_f11  reading_punctuation_decrease
spk_f12  reading_punctuation_increase
spk_1    volume_decrease (não funciona como speechd-up)
spk_2    volume_increase (não funciona como speechd-up)
spk_3    pitch_decrease (não funciona como speechd-up)
spk_4    pitch_increase (não funciona como speechd-up)
spk_5    rate_decrease
spk_6    rate_increase
----
Na tabela acima do spk está a tecla do speakup CapLock, ou Ins/0 num teclado numérico. Por exemplo, para aumentar a taxa poderia premir e manter pressionada a tecla CapsLock e depois premir a tecla 6.

Algumas definições disponíveis apenas para equipamentos de sintetizadores específicos não têm combinação de teclas associadas. Depois para definir um novo valor echo em /sys/accessibility/speakup/<synth>/<parameter>

Por exemplo, para alterar a voz em uso por um apollo 2, pode escrever: +
echo 2 > /sys/accessibility/speakup/apollo/voice

speakup-save também irá gravar esta definição.

Atenção: Eu nunca usei um equipamento de sintetizador de voz, por isso a explicação abaixo é apenas uma suposição baseada no controlador speakup_apollo, coerente com o seu manual, localizado em: +
https://archive.org/stream/DolphinApollo2Manual/Dolphin_Apollo_2_Manual_djvu.txt

[[desktop_keys]]
==== Teclas da área de trabalho do speakup

Quase todas as teclas listadas abaixo estão localizadas no teclado numérico. A tecla Insert ou 0 do teclado atua como uma tecla shift. Por exemplo, Ins 2 significa "mantenha pressionada a tecla Insert como uma tecla shift e prima 2". Mantenha o numlock desligado para usar o Speakup.

Âmbito: esta combinação de teclas pode ser utilizada com sintetizadores e com o espeakup, e também com o speechd-up.

Primeiras teclas a memorizar:
----
PrintScreen    Liga/Desliga o speakup
Ins F1         Ajuda do Speakup (prima Espaço para sair da ajuda)
----

Teclas utilizadas para a revisão do ecrã:
----
1/2/3          Say Previous/Current/Next character
Shift PageUp   Say first character
Shift PageDown Say last character
4/5/6          Say Previous/Current/Next word
5 twice        Spell current word
Ins 5          Spell Current Word phonetically
7/8/9          Say Previous/Current/Next line
Ins 4          Say from left edge of line to reading cursor
Ins 6          Say from reading cursor to right edge of line
Ins 8          Say from top of screen to reading cursor
Ins plus       Say from reading cursor line to bottom of screen
plus           Say entire screen.
Ins r          Say all document
dot            Say position
Ins dot        Say attributes
Ins minus      Say character hex and decimal value.
minus          Park reading cursor (toggle)
Ins 9          Move reading cursor to top of screen (insert pgup)
Ins 3          Move reading cursor to bottom of screen (insert pgdn)
Ins 7          Move reading cursor to left edge of screen (insert home)
Ins 1          Move reading cursor to right edge of screen (insert end)
Control 1      Move reading cursor to last character on current line.
asterisk       Toggle cursoring
Ins asterisk   n<x|y go to line (y) or column (x). Where 'n' is any
               allowed value for the row or column for your current screen.
Ins f2         Set window
Ins f3         Clear window
Ins f4         Enable window
----

Outras teclas:
----
Ins f5         Editar algumas
Ins f6         Editar maioria
Ins f7         Editar delim
Ins f8         Editar repetição
Ins f9         Editar exnum

Enter          Calar-se (até que outra tecla seja premida) e sincronizar o cursor de leitura.
Ins Enter      Calar-se (até que seja novamente ligado)

barra invertida          Marcar e Cortar a região do ecrã.
Ins barra invertida      Colar a região do ecrã em qualquer consola.
----
==== Teclas do Speakup para computador portátil

Estas teclas de atalho (para o esquema de teclado US) não precisa de um teclado numérico. Se tiver um, utilize as <<desktop_keys,teclas do ambiente gráfico speakup>> mais fáceis de utilizar, especialmente se utilizar outro esquema de teclado para além do US.

A tecla CapsLock age como uma tecla Shift. +
Por exemplo, CapsLock 2 significa "mantenha pressionada a tecla CapsLock como uma tecla shift e prima 2". +
Mantenha o numlock desligado para usar o Speakup.

Âmbito: esta combinação de teclas pode ser utilizada com sintetizadores e com o espeakup, e também com o speechd-up.

Primeiras teclas a memorizar:
----
PrintScreen          Liga/Desliga o speakup
CapsLock F1          Ajuda do Speakup (prima Espaço para sair)
----

Tecla utilizada para revisão do ecrã:
----
CapsLock m/comma/dot Say Previous/Current/Next character
CapsLock PageUp      Say First character
CpasLock PageDown    Say Last character
CapsLock j/k/l       Say Previous/Current/Next word
CpasLock k twice     Spell current word
CapsLock u/i/o       Say Previous/Current/Next line
CapsLock h           Say from left edge of line to reading cursor.
CapsLock semicolon   Say from reading cursor to right edge of line
CapsLock y           Say from top of screen to reading cursor
CapsLock p           Say from reading cursor line to bottom of screen
CapsLock apostrophe  Say entire screen.
Capslock r           Read all document
CapsLock n           Say position
CapsLock slash       Say attributes
CapsLock minus       park reading cursor (toggle)
CapsLock f2          Set window
CapsLock f3          Clear window
CapsLock f4          Enable window
----
Outras teclas:
----
CapsLock f5          Editar algumas
CapsLock f6          Editar maioria
CapsLock f7          Editar delimitador
CapsLock f8          Repetir o editar
shift CapsLock f9    Editar exnum
----

=== Fazer o emacs falar

Pode usar o emacspeak ou o speechd-el. Para ativar ou desativar um deles, escreva como utilizador um destes comandos:

switch-on emacspeak +
switch-on speechd-el +
switch-off emacspeak +
switch-off speechd-el +

Depois basta escrever: +
emacs

Ativar um destes softwares desativa o outro.

[[Manage_your_system]]
== Faça a gestão do sistema

[[software_management]]
=== Gestão de software no Slint

<<The_basics,O básico>> +
<<Keep_your_system_up_to_date,Mantenha o sistema atualizado>> +
<<Kernel_upgrades,Atualizações do Kernel>> +
<<Get_additional_applications,Obtenha aplicações adicionais>> +
<<slapt_src,Utilização do slapt-src>>

[[The_basics]]
==== O básico

No Slint o software é fornecido sob a forma de pacotes. Um pacote é um conjunto de ficheiros fornecidos num ficheiro comprimido, composto para fornecer tudo o que é necessário para executar o software. Os pacotes são incluídos na instalação ISO e armazenados em servidores remotos dos quais podem ser transferidos e instalados. Instalar um pacote significa extrair os ficheiros do ficheiro de arquivo e copiá-los para algum diretório do sistema.

A instalação e remoção de software são gravadas numa base de dados feita de ficheiros de texto, nestes diretórios:
----
/var/lib/pkgtools/packages
/var/log/removed_packages
/var/lib/pkgtools/scripts
/var/log/removed_scripts
----
Os ficheiros em /var/lib/pkgtools/pacotes registam informação sobre os pacotes, principalmente o seu conteúdo: a lista de ficheiros que incluem e onde estão instalados.

Os comandos principais para gerir os pacotes estão listados abaixo. Todos eles têm páginas de manual(man) associadas.

Estes comandos requerem direitos administrativos, associados a uma conta específica chamada 'root', para a qual especificou uma palavra-passe durante a instalação do Slint.

Para emitir um comando como 'root', primeiro escreva su - e depois introduza a palavra-passe do root e escreva o comando.+ ou use o sudo.

Os comandos abaixo podem ser executados a partir de um terminal gráfico ou numa consola, mas o gslapt que apenas funciona num ambiente gráfico.
----
installpkg # para instalar um pacote armazenado localmente.
removepkg # para remover um pacote instalado.
upgradepkg # para substituir um pacote instalado por outro (geralmente com o mesmo nome, mas noutra versão).
slapt-get # para instalar, remover e atualizar pacotes armazenados em repositórios listados em /etc/slapt-get/slap-getrc
----
Os pacotes incluído na ISO de instalação vêm dos repositórios listados em /etc/slapt-get/slapt-getrc

Faça um favor a si próprio: leia os comentários em /etc/slapt-get/slapt-getrc e /usr/doc/slapt-get-0.10.2t/README.slapgetrc.Slint no sistema instalado.

Depois de ter instalado o Slint, será notificado de atualizações de pacotes instalados provenientes dos repositórios listados em /etc/slapt-get/slapt-getrc

Pode instalar pacotes adicionais usando os comandos slapt-get ou a aplicação gráfica gslapt, se armazenada num repositório listado em /etc/slapt-get/slapt-getrc

O slapt-get e o gslapt fornecem uma funcionalidade de pesquisa que te ajuda a encontrar pacotes.

WARNING: Pode usar o slapt-get, gslapt e removepkg para remover pacotes instalados, mas não remover pacotes incluídos na ISO do Slint, mesmo que não os utilizemos de todo. Remover um pacote incluído não resultará em aumento de desempenho e poderia impedir que outras aplicações fossem executadas. Além disso, se tiver adicionado um pacote não incluído no Slint, pode removê-lo mas tenha cuidado para que o pacote removido não seja uma dependência de outros que também instalou e pretende continuar a usar.

[[Keep_your_system_up_to_date]]
==== Mantenha o seu sistema atualizado

Mantenha o sistema seguro ao instalar as atualizações de software fornecidas pelo Slint assim que estejam disponíveis.

Todas as atualizações estão listadas no Registo de alterações: http://slackware.uk/slint/x86_64/slint-15.0/ChangeLog.txt

Após a instalação do Slint ou qualquer alteração no ficheiro /etc/slapt-get/slapt-getr executa este comando uma vez:
----
slapt-get --add-keys
----

Para sincronizar a lista local do pacote disponível com o repositório, este comando é executado automaticamente a cada duas horas:
----
slapt-get -u
----
Também pode executá-lo manualmente.

Isto requer, naturalmente, que a máquina esteja ligada à Internet.

Para transferir e instalar pacotes atualizados ou recompilados, executa como root o seguinte comando:
----
slapt-get --upgrade
----
Como alternativa, também poderia usar o gslapt, um front-end gráfico para o slapt-get.

Para obter novos pacotes listados no Changelog (Registo de alterações) como "Added" (Adicionado), escreva:
----
slapt-get -i <package name>
----
ou para ter certeza de que instalou todos os pacotes incluídos no Slint, incluindo aqueles adicionados ao repositório depois que instalou o Slint, escreva:
----
slapt-get --install-set slint
----

Nos ambientes de trabalho, um pequeno ícone é exibido na área de notificação de um painel (o painel superior no MATE) para notificar as atualizações disponíveis do software. Basta clicar com o botão esquerdo e seguir as instruções ali mencionadas.

Esteja ciente de que alguns pacotes estão na lista negra /etc/slapt-get/slapt-getrc, ou seja, não podem ser atualizados automaticamente ou instalados.

[[Kernel_upgrades]]
==== Atualizações do kernel

Quando necessário, são fornecidos novos kernels, quer para trazer correções de segurança, quer para melhoramentos.

Geralmente, não é necessária uma intervenção manual por parte do utilizador quando isto acontece, mas pode ser útil saber como a atualização do kernel é feita e o que fazer se algo inesperado acontecer.

Vários pacotes incluem ficheiros associados a cada kernel, nomeadamente: kernel-generic, kernel-modules, kernel-source, kernel headers. kernel-source e kernel-headers incluem ficheiros usados para compilar software, apenas o kernel-generic e o kernel-modules são necessários para executar um sistema Slint.

Os ficheiros dos módulos kernel, são fornecidos como módulos, que são pedaços de código que estão "ligados no" kernel para fornecer um recurso específico ou lidar com um hardware específico.

Assim que um pacote kernel e o pacote kernel associado são instalados, o script /sbin/wrapupgradepkg compila um <<initrd,initrd>> associado a este kernel (com módulos retirados do pacote kernel-modules) e instala-o junto com o kernel no diretório /boot.

Depois os kernels anteriores (não estão em utilização no momento da atualização) são removidos.

De seguida, o script atualiza o ficheiro de configuração do GRUB /boot/grub/grub.cfg, lido pelo carregador do sistema operativo para compilar o menu de arranque.

Este menu de arranque incluirá pelo menos duas entradas, cada uma indicando um kernel e seu initrd associado a utilizar. Do topo:

* Uma entrada de arranque para iniciar o Slint utilizando o novo kernel que acabou de ser instalado.
* Uma entrada de arranque para começar o Slint utilizando o kernel em uso no momento da atualização.

Isto fornece um tipo de "rede de segurança" no caso do Slint não arrancar com o novo kernel: neste caso, apenas prima a seta para baixo uma vez quando o menu de arranque é exibido para iniciar o Slint com o kernel anterior

Pode pré-visualizar o novo menu de arranque antes de reiniciar, escrevendo como root:
----
grub-emu
----
Depois um menu de arranque emulado ou "falso" é apresentado, com a mesma disposição que será apresentada no próximo arranque.

Pode navegar no menu com as setas para baixo e para cima para destacar (colocar o foco em) uma entrada de arranque na qual pode exibir os detalhes premindo 'e'. Pode voltar ao menu premindo Esc.

Para sair do grub-emu prima c e depois escreva *exit* e prima Enter.

Em alternativa pode introduzir como root:
----
list_boot_entries
----

[[Get_additional_applications]]
==== Obtenha aplicações adicionais

A maneira mais fácil de obter aplicações adicionais não disponibilizadas no Slint é utilizar o slapt-get ou o seu front-end gráfico gslapt. Isto dá-lhe acesso a todos os pacotes em repositórios ativados em /etc/slapt-get/slapt-getrc por padrão, para além do repositório Slint: +

* O repositório Slackware, com informação de dependências: SOURCE=https://slackware.uk/salix/x86_64/slackware-15.0/:OFFICIAL
* O repositório extra Salix, fornecido para a distribuição Salix pelo seu responsável George Vlahavas também conhecido como gapan mas utilizável no Slint também: SOURCE=https://slackware.uk/salix/x86_64/extra-15.0/:OFICIAL

Se a aplicação que deseja não estiver instalada e também não estiver disponível num dos repositórios ativados em /etc/slapt-get/slapt-getrc pode criar um pacote para o mesmo, usando material de compilação fornecido por voluntários @ https://slackbuilds.org. Para saber como prosseguir, leia https://slackbuilds.org/howto/ e https://slackbuilds.org/faq/

Os pacotes compilados desta forma devem ser compatíveis com o Slint.

A aplicação *slapt-src* e o seu front-end gráfico *sourcery* permite-lhe compilar e instalar pacotes utilizando o material de compilação fornecido em https://slackbuilds.org, para ser usado como root ou usando sudo.

Descreveremos o slapt-src em mais detalhes.

[NOTE]
====
Os pacotes pré-compilados para a maioria das aplicações que podem ser compiladas com o slap-src ou o sourcery estão disponíveis no repositório extra do Salix. De preferência instale estes pacotes pré-compilados usando slapt-get ou o gslapt, a menos que precise de opções de compilação específicas ou de uma versão diferente da fornecida.
====

[[slapt_src]]
===== Utilização do slapt-srcrc

O script de configuração padrão para o slapt-src é /etc/slapt-get/slap-srcrc e tem este conteúdo:
----
BUILDDIR=/var/lib/slapt-src
PKGEXT=txz
SOURCE=https://slackbuilds.org/slackbuilds/15.0/
----
Por isso:

* Todo material de compilação e pacotes irão para /var/lib/slapt-src
* Os nomes de pacotes compilados terminam em .txz
* O material de compilação é obtido do repositório https://slackbuilds.org/slackbuilds/15.0/

Aqui está o resultado do comando *slapt-src --help*:
----
Usage: slapt-src [option(s)] [action] [slackbuild(s)]
  -u, --update           update local cache of remote slackbuilds
  -U, --upgrade-all      upgrade all installed slackbuilds
  -l, --list             list available slackbuilds
  -e, --clean            clean build directory
  -s, --search           search available slackbuilds
  -w, --show             show specified slackbuilds
  -i, --install          fetch, build, and install the specified slackbuild(s)
  -b, --build            only fetch and build the specified slackbuild(s)
  -f, --fetch            only fetch the specified slackbuild(s)
  -v, --version
  -h, --help
 Options:
  -y, --yes              do not prompt
  -t, --simulate         show what will be done
  -c, --config=FILE      use the specified configuration file
  -n, --no-dep           do not look for dependencies
  -p, --postprocess=CMD run specified command on generated package
  -B, --build-only       applicable only to --upgrade-all
  -F, --fetch-only       applicable only to --upgrade-all
----

Vamos comentar algumas destas opções:

* Utilize -u ou --update sempre que se pretenda atualizar a lista de pacotes que podem ser compilados e instalados. Este comando grava o ficheiro /tmp/slapt-slapt-src/slackbuilds_data, substituindo o caso anterior que ocorreu.
* Use -e para economizar espaço no disco, removendo a maioria dos ficheiros em /tmp/slapt-src/
* *não* use -U a menos que seja para listar as possíveis atualizações ou desatualizações, sem confirmar: confirmar levaria a substituir todos os pacotes Slint por uma outra versão, se disponível no repositório remoto, possivelmente quebrando o software não compatível com esta outra versão.
* -i também pode atualizar um pacote já instalado a partir do https://slackbuilds.org, se um responsável do script SlackBuild o atualizou, mudando a variável VERSON.
* Use -f para transferir apenas os ficheiros no https://slackbuilds.org para o software de destino. Isto pode ser útil se quiser verificar o material de compilação, ou personalizar a compilação. Por exemplo, vamos supor que quer ir buscar o material de compilação para o software *mxml*. O comando abaixo dá algumas informações sobre o software e quais ficheiros são armazenados no https://slackbuilds.org para isso:
+
----
slapt-src --show mxml
SlackBuild Name: mxml
SlackBuild Version: 3.
SlackBuild Category: libraries/mxml/
SlackBuild Description: mxml (Light xml parsing library)
SlackBuild Files:
 README
 mxml. lackBuild
 mxml.info
 slack-desc
----
+
Agora, procure estes ficheiros e também o ficheiro de origem do repositório "upstream" com o próximo comando:
+
----
slapt-get -f mxml
----
+
Sabendo pelo resultado do comando anterior que os ficheiros são armazenados nas bibliotecas de subdiretório/mxml, pode verificar quais ficheiros foram transferidos com este comando:
+
----
ls -1 /var/lib/slapt-src/libraries/mxml
mxml-3.1.tar.gz
mxml.SlackBuild
mxml.info
slack-desc
----
* Use -b se quer compilar um pacote mas não instalá-lo ainda. No exemplo acima o mesmo será armazenado em /tmp/slapt-src/libraries/mxml, então poderá instalá-lo depois de escrever:
+
----
upgradepkg --install-new /tmp/slapt-src/libraries/mxml/xml*txz
----
+
* Use -c se quiser usar um ficheiro de configuração personalizado ao invés do padrão /etc/slapt-get/slap-getrc

=== Gerir utilizadores e grupos

Dois comandos são fornecidos para gerir utilizadores e grupos:

* O comando _usersetup_ (TUI)
* O comando _gtkusersetup_ (GUI), com um ícone no Centro de Controlo Slint, Categoria do sistema)

Estes comandos permitem adicionar ou eliminar utilizadores e grupos de utilizadores e adicionar utilizadores a grupos.

Tenha em mente que cada conta de utilizador é associada por padrão ao seu espaço no diretório /home. Por exemplo, se adicionar um utilizador *hugo*, será criada uma pasta /home/hugo, à qual apenas este utilizador (e root) terá permissão de acesso.

=== Alterar o idioma predefinido do sistema

Estão previstos dois comandos para o efeito:

* O comando _localesetup_ (TUI).
* O comando _gtklocalesetup_ (GUI), com um ícone no Centro de Controlo Slint, categoria Definições.

Tenha em mente que estas definições alteram o idioma usado pelas interfaces das aplicações caso sejam internacionalizadas, não o mapa de teclado (veja abaixo).

Além disso, os pacotes localizados (se disponíveis) que correspondem ao idioma escolhido já foram instalados no final da instalação do Slint. Se alterar o idioma predefinido depois, irá precisar de instalar os pacotes de localização correspondentes, se quiser.

Localizado significa "fornecido numa determinada localização", sendo a localização um idioma mais as peculiaridades associadas a uma área geográfica. Por exemplo, o Português falado em Portugal e no Brasil é diferente. Nos nomes dos pacotes localizados, l10n é uma abreviação de "localização" que significa "letra, 10 outras letras, letra n".

Os pacotes localizados são incluídos em vários idiomas. O seu nome inclui o nome base do pacote, um hífen e depois o código do idioma. Nós listamos abaixo os nomes básicos dos pacotes localizados:
[options="autowidth"]
|====
| Nome do pacote base | Descrição
| aspell | listas de palavras para verificação ortográfica
| libreoffice-l0n | suite de escritório LibreOffice localizado
| libreoffice-help | ajuda localizada para o LibreOffice
|====

Para encontrar um pacote localizado, escreva num emulador de terminal como root (exemplo para libreoffice-l10n): +
`spi libreoffice-l10n`

Isto irá mostrar a lista de todos os pacotes localizados do LibreOffice. Encontre o que deseja e instale. Por exemplo, para o Persa, o código do idioma é `fa` (abreviação de Farsi), por isso para o instalar escreva: +
`spi -i libreoffice-l10n-fa`

Se preferir pode usar o `gslapt`. De seguida, escreva o nome do pacote no campo de pesquisa para mostrar todos os pacotes de libreoffice localizados.

=== Mudar o mapa do teclado

Pode alterar o mapa de teclado predefinido usado no modo gráfico, usando:

* O comando _keyboardsetup_ (TUI)
* O comando _gtkkeyboardsetup_ (GUI), com um ícone no Centro de Controlo Slint, categoria de Hardware.

Estes comandos também permitem escolher se o numlock deve ser ativado quando o sistema é iniciado, e se o SCIM (método de entrada) deve ser ativado no arranque do sistema.

Se usar um gestor de janelas com um painel, também pode fazer esta configuração através de um clique com o botão direito do rato no ícone do teclado da área de notificação (exibida por padrão como o código de idioma de duas letras do mapa do teclado em uso).

Na linha de comandos mas ainda para o modo gráfico utilizar em vez disso o comando `setxbmap`

Por exemplo, para definir a disposição do teclado para Português em modo gráfico, basta escrever como utilizador padrão: +
`setxkbmap -layout pt`

Para saber mais, leia a página do manual do setxkbmap.

=== Instalar uma impressora

No Slint o servidor de impressão CUPS gere impressoras e tarefas de impressão. Na sua configuração predefinida, registada no ficheiro /etc/cups/cupsd. onf, apenas os utilizadores pertencentes ao grupo `sys` (abreviação para _system_) estão autorizados a executar tarefas administrativas, como adicionar ou remover uma impressora.

Para uma configuração simples (impressora anexada a um computador de secretária ou portátil e não partilhada entre as máquinas), apenas precisa de adicionar um utilizador (que irá gerir as impressoras) para o grupo `sys`. Por exemplo, adicionar o utilizador hugo ao grupo `sys` pode ser feito de duas maneiras:

* No modo de consola ou usando um emulador de terminal, torne-se root com `su -` e depois escreva:
+
`gpasswd --add hugo sys`
+
* No modo gráfico a partir do Centro de Controlo do Slint clique em Utilizadores e Grupos (categoria do Sistema), selecione o utilizador e clique em Propriedades, no separador de Grupos, verifique `sys`. Ou o inverso (selecione o grupo e adicione o utilizador ao mesmo).

Existem várias maneiras de adicionar e configurar uma impressora (isto tem que ser feito por um membro de utilizador do grupo `sys`):

* A partir do Centro de Controlo Slint, categoria de Equipamento, clique na Configuração da Impressora para exibir uma GUI permitindo uma configuração simples...
* ... Ou clique em Controlo de impressão Cups que exibe uma interface da web para o servidor CUPS. Também pode exibir a interface da web para o servidor CUPS escrevendo `localhost:631` no campo de endereço de um navegador web.
* Se tiver um dispositivo Hewlett Packard, clique no logotipo da *hp* na área de notificação do painel.

NOTE: Para fazer com que qualquer configuração de impressão, o servidor CUPS deve estar em execução. O mesmo é iniciado quando inicia o Slint se o serviço `cups` estiver selecionado entre os Serviços do Sistema (é selecionado por padrão no Slint).

=== Configuração do som

No Slint as aplicações enviam a saída do som para o ALSA ou para o PulseAudio.

Neste último caso, o PulseAudio, por sua vez, envia o fluxo de saída para um misturador ALSA que o direciona para as placas de som.

Como resultado, uma regulação como um volume de som de saída pode sempre ser feita por um misturador ALSA e também por um misturador PulseAudio, mas apenas no caso da aplicação enviar a saída sonora para o PulseAudio.

Apresentaremos agora aplicações que podem ser utilizadas para modificar as definições do som

==== pavucontrol (para o PulseAudio)

`pavucontrol` significa PulseAudio Volume Control e é uma aplicação gráfica. Pode iniciá-la a partir de um menu de terminal ou aplicação, ou fazer um clique no ícone do misturador do som no painel superior do Mate. Na verdade, ele permite mais definições do que apenas o controle de volume, reserve um tempo para explorar todas as suas funcionalidades.

Também pode usar o ícone de controlo de volume na área de notificação do painel: um clique com o botão esquerdo permite ajustar o volume, um clique com o botão direito dá acesso a outras definições e permite iniciar o misturador do pavucontrol.

[[Sound_on_the_command_line]]

==== alsamixer (para o ALSA)

alsamixer é uma aplicação "ncurses", fornecendo uma interface(UI) semigráfica.

Para o utilizar, escreva numa consola ou num terminal gráfico:
----
alsamixer
----
depois:

* Utilize a tecla PgUp para aumentar o volume em 5%
* Utilize a tecla PgDn para diminuir o volume em 5%
* prima Esc para sair da aplicação.

==== amixer (para o ALSA)
O comando é da forma:
----
amixer <arguments>
----
Por exemplo, para definir o volume principal para 70% escreva:
----
amixer sset Master 70%
----
Para saber mais, escreva um destes comandos:
----
man amixer
amixer -h
----
==== sam (o misturador Alsa de voz amigável)
O sam permite que a seleção da placa de som funcione quando há mais de um dispositivo desse tipo na sua máquina. +
Quando há apenas um, ele apresenta diretamente os diferentes misturadores para configuração.

Todas as seleções, sejam placas de som, misturadores ou uma determinada funcionalidade de um misturador específico
 são selecionadas deslocando-se pelas opções disponíveis utilizando as setas para cima e para baixo, depois, entrando na desejada: +
`q` deixe a lista de seleção e/ou sai. +
`Shift-q` sai do programa de qualquer local. +
`F1` Mostra qualquer informação extra, se disponível.

Quando o nome da opção desejada for conhecida, pode-se premir a sua primeira letra. A navegação em primeira letra é insensível a maiúsculas. Isso então o levará à primeira seleção começando com a letra pressionada. Premir a mesma letra novamente, irá deslocá-lo para a opção seguinte, começando com essa letra, se existir mais do que uma opção como essa. A repetição da letra percorrerá entre todas as opções que começam com essa letra.

As funcionalidades configuráveis de um misturado podem ser listadas premindo F1. +
Eles são apresentados como uma lista de seleção, mostrando brevemente toda a informação relevante, por e.x. "volume de reprodução abaixo de 84 por cento" é a opção de reduzir a definição do volume de reprodução. Como pode ver, também lhe diz qual é a definição atual.

NOTE: o sam não funciona corretamente num terminal gráfico. Use-o numa consola.

==== pamixer e ponymix (para PulseAudio)
Estes utilitários são semelhantes, com comandos nesta forma:
----
pamixer <arguments>
ponymix <arguments>
----
Por exemplo, para definir o volume para 70% para o predefinido, escreva um destes comandos:
----
pamixer --set-volume 7
ponymix set-volume 7O
----
Para saber mais, escreva:
----
pamixer -h
ponymix --help
----

==== pacmd e pactl (para o PulseAudio)

Ambas as aplicações de linha de comandos controlam um daemon PulseAdio em execução.

WARNING: O pacmd introduzido invoca uma janela interativa. Prima Ctrl+d para sair, mas não escreva exit, pois isso iria terminar o PulseAudio!

Para saber mais:
----
man pactl
man pacmd
pactl --help
pacmd --help
----

==== Guardar e restaurar o nível de som

Apenas torne o ficheiro /etc/rc.d/rc.alsa executável. Como root:
----
chmod /etc/rc.d/rc.alsa
----
Ao arrancar, este script irá restaurar as definições de som anteriores se guardadas, caso contrário irá definir volumes predefinidos e armazená-los, para que sejam restaurados no próximo reinício.

Se não quiser que este script defina o tipo de volume predefinido, escreva como root:
----
touch /var/lib/alsa/no.asound.state
----

Pode alterar estes níveis predefinidos de som com o alsamixer ou amixer e depois escreva como root:
----
alsactl store
----
Depois no próximo arranque o script irá restaurá-los.

Para saber mais:
----
man alsactl
----

=== Configuração de rede

Se não configurou as suas definições de rede durante a instalação do Slint, primeiro torne-se root escrevendo `su -' numa consola ou num terminal gráfico como o mate-terminal, depois introduza a palavra-passe do root.

A instalação da rede é feita pelo script `netsetup`. Assim, basta escrever o comando `netsetup` nesse mesmo terminal, onde acabou de adquirir privilégios de root. Ser-lhe-á pedido primeiro o nome da sua máquina. Pode escolher qualquer nome, mas lembre-se de que deve ser uma única palavra. Depois perguntam-lhe o nome do domínio. Se a máquina não é um servidor pode escolher qualquer um. Depois disso, será perguntado como a máquina se liga à rede. A menos que tenha uma boa razão para não (e sabe o que está a fazer), manter o `NetworkManager` predefinido para configurar automaticamente a rede.

Para ligações por cabo de rede, isso deve ser suficiente para estar ligado automaticamente no próximo arranque.

Para configurar uma ligação sem fios, dois comandos estão disponíveis ao usar a linha de comandos.

Novamente, pode escrever os comandos diretamente na consola ou num terminal gráfico como o mate-terminal. Escreva-os como utilizador, não como root. Se já seguiu essas instruções e se tornou root, apenas escreva `exit` para voltar ao estado de utilizador.

Os dois comandos mencionados são `nmtui` (caixas de diálogo) ou `nmcli` (linha de comando pura), ambos são acessíveis.

Se prefere trabalhar na linha de comandos, lembre-se de ler primeiro a documentação do nmcli. Basta escrever `nmcli --help` e `man nmcli` para descobrir todos os detalhes. Embora o `nmcli` ofereça mais possibilidades, na maioria dos casos, a funcionalidade do `nmtui` será suficiente para configurar a sua rede sem fios, por isso vamos descrevê-lo aqui:

Ao usar o `nmtui`, pode navegar com as teclas Tab e setas. Serão propostas três opções: +
`Edit a connection` +
`Activate a connection` +
`Set system hostname` +

Se nenhuma ligação sem fios foi definida, escolha `Activate a connection`. A partir de cima para baixo, primeiro as ligações por cabo de rede (se houver) serão propostas, depois disso todas as redes sem fios acessíveis serão listadas. Navegue com as setas para baixo e para cima para selecionar a rede que deseja, depois, prima Enter: provavelmente será solicitada a chave encriptada. Introduza-a, use a tecla Tab para confirmar e depois saia para concluir.

Apenas no modo gráfico, ao invés de `nmcli` ou `nmtui` , pode usar a aplicação `nm-connection-editor`.

=== Configuração dos serviços

É possível alterar as definições padrão de várias maneiras:

* Executando como root o comando `servicesetup` (TUI)
* Apenas no modo gráfico, utilizando o `gtkervicesetup`, acessível a partir do Centro de Controlo Slint, na categoria Sistema ou premindo Alt+F2 para invocar uma janela "Executar..." e depois, escrever *gtksetrvicesetup*.
* Como root, tornando o script executável relevante (chmod 755 <path to the script> ou não executável (chmod 644 <path to the script>). Por exemplo, para tornar o fail2ban executável fail2ban escreveria: `chmod 755 /etc/rc.d/rc.fail2ban`

IMPORTANT: Apenas altere as definições predefinidas se souber o que está a fazer.

Os serviços são geridos por scripts cujo nome começa com `rc.` no diretório /etc/rc.d/. Por exemplo, o serviço de acpi é gerido pelo shell script /etc/rc.d/rc.acpi. A maioria dos serviços são ativados no arranque, se o script correspondente é executável. Na tabela abaixo, indicamos se ele foi ativado no arranque (`on` na coluna A) ou não (`off` na coluna A). Se a coluna estiver em branco a ativação dos serviços depende de uma escolha feita durante a instalação. Um `A` na coluna indica que o serviço está ativado no modo de instalação Auto, caso contrário é ativado se escolhido pelo utilizador durante a instalação. A coluna do pacote indica qual pacote de software fornece o script correspondente ao serviço, caso ocorra

[options="autowidth"]
|====
| *Service* | *A* | *Package* | *Purpose and comments*
| acpi | on | acpid | Advanced Configuration and Power Interface, allows for instance to manage power or reboot pressing a button
| alsa | on | alsa-utils | Provide default sound settings or restore those saved
| alsa-oss | off | alsa-utils | ALSA OSS kernel modules. Not useful in most cases, not enabled by default in Slint.
| atalk | off | netatalk | Allows Unix-like operating systems to serve as file, print and time servers for Macintosh computers.
| atd | off | at | at and batch read shell commands from standard input (or a specified file) storing them as a job to be scheduled for execution at a later time
| autofs | off | autofs | AutoFS provides automounting of removable media or network shares when they are inserted or accessed.
| bind | off | bind | Name server. Most users will rely on a remote one. Enable it if you want to run a name server in this system.
| bitlbee | on | bitlbee | BitlBee is an IRC daemon that can talk to instant messaging networks
       and acts as a gateway. Users can connect to the server with any normal
       IRC client and see their 'buddy list' in bitlbee.
| bluetooth | on | bluez | Allows to communicate with bluetooth devices
| brltty| | brltty | Allows to communicate with Braille terminal or screen reader. Activated if requested during installation
| cgconfig | on | libcgroups | Runs the cgconfigparser utility that parses /etc/cgconfig.conf to setup the control group hierarchy, including setting the permissions (UID and GID) of the groups and possibly tunable parameters of the controllers. This alleviates doing that ourselves at every startup, for instance running a separate shell script. This script is executable by default but anyway won't do anything until /etc/cgconfig.conf be edited (all lines are commented out as shipped)
| cgred | on | libcgroups | The control groups are a way to control the allocation of system resources like CPU or RAM to "groups" of users and/or processes. This script starts the cgroups rules engine daemon that automatically distributes to appropriate control groups the processes that changes their effective UID or GID. It is executable by default but to make it work you need to set rules in /etc/cgrules.conf.
| consolekit | on | ConsoleKit2 | This daemon is used by polkit's auth agent, to check privileges of user wanting to reboot or shutdown the system, for instance.
| cpufreq | on | sysvinit-scripts | Settings for CPU frequency and voltage scaling in the kernel.
| crond | on | crond |The cron daemon runs in the background and executes tasks on behalf of users at the appropriate time.
| cups | on | cups | Startup/shutdown script for the CUPS print server.
| cups-browsed | off | cups-filters | Makes remote printers available locally.
| dnsmask | off | dnsmask | Start/stop/restart dnsmasq (a small DNS/DHCP server)
| dovecot | off | dovecot | Dovecot is an open source IMAP and POP3 server for Linux/UNIX-like systems, written with security foremost in mind. 
| elogind | on | elogind | elogind is the systemd project's logind, extracted to a standalone  package.
| espeakup | | espeakup | starts/stop/restart the espeakup console screen reader. On if user requested speech during installation or later typed speak-with espeakup
| fail2ban | off | fail2ban | start/stops fail2ban which scans log files like /var/log/pwdfail and bans IP that makes too many password failures, and also updates firewall rules to reject the IP address.
| fenrir | off | fenrir | starts/stop/restart the fenrir screen reader, which can be started after installation typing speak-with fenrir.
| font | off | kbd | Sets the console font (used in Console mode, not in Graphical mode)
| fuse | on | fuse | Load the fuse module and mount the fuse control filesystem. FUSE is a simple interface for userspace programs to export a virtual filesystem to the Linux kernel. FUSE also aims to provide a secure method for non privileged users to create and mount their own filesystem implementations.
| fuse3 | on | fuse3 | Like fuse, but version 3 
| gpm | on | gpm | The General Purpose Mouse server allows to cut and paste text from the screen on a Linux console.
| haveged | on | haveged | The haveged project is an attempt to provide an easy-to-use, unpredictable random number generator based upon an adaptation of the HAVEGE algorithm.
| httpd | off | httpd | Starts or stop the Apache web server
| icecc-scheduler | off | icecream | Start/stop/restart the icecream (distributed compiler) scheduler
| iceccd | off | icecream | Start/stop/restart the icecream (distributed compiler) daemon
| inet1 | on | network-scripts | This script is used to bring up the various network interfaces.
| inet2 | on | network-scripts | This shell script boots up the entire network system.
| inetd | on | inetd | BSD "super-server" daemon. The user needs to edit /etc/inetd.conf for the services to be actually used.
| ip_forward | off | network-scripts | Start/stop IP packet forwarding, needed for your computer to act as a router.
| kadmind | off | krb5 | Start the Kerberos administration server
| kprprod | off | krb5 | Start the Kerberos V5 slave KDC update server. 
| krb5kdc |off | krb5 | Start krb5kdc, which is the Kerberos version 5 Authentication Service and Key Distribution Center (AS/KDC). This needs to run first on both master and secondary KDCs.
| local | off | sysvinit-scripts | starts daemons not started by /etc/rc.d/rc.M at boot time.
| loop | on | sysvinit-scripts | Loads the loop device kernel module.
| lxc | off | lxc | This scripts starts (if configured to be auto-started) and stops lxc containers.
| mcelog | off | mcelog | Starts the mcelog hardware error logging. This logs and handles CPU hardware errors on x86 systems
| messagebus | on | dbus | The D-BUS systemwide message bus. This is a daemon which broadcasts notifications of system events and other messages, providing inter-processes communication.
| modules | on | sysvinit-scripts | Compute the kernel modules dependencies and start other scripts that load modules not automatically loaded by eudev, possibly for specific kernel versions
| modules.local | on | sysvinit-scripts | Load modules not automatically loaded by eudev
| mysqld | off | mariadb | Starts/stop the MariaDB server. MariaDB is a fork of MySQL fully compatible with it
| networkmanager| | NetworkManager | This is a daemon for automatically switching network connections to the best available connection. Activated if NetworkManager is chosen to configure the network, during or after installation
| nfsd | off | nfs-utils | Starts/stop a nfs (Network File Server)
| ntpd | on | ntp | Starts stop an ntp ( Net'work Time Protocol) daemon.
| numlock| | salixtools | Activate numlock on the console
| openldap | off | openldap | Start the ldap (Lightweight Directory Access Protocol) server
| openvpn | off | openvpn | Start the OpenVPN (secure IP tunnel) daemon
| pcmcia | off | pcmciautils | Script to initialize PCMCIA subsystem.
| php-fpm | off | php | Starts the PHP FastCGI Process Manager daemon.
| postfix | off | postfix | start Postfix, mail transport and submission agent.
| pulseaudio | off | pulseaudio | Starts pulseaudio system-wide. This is not recommended in Slint.
| rpc | off | rpcbind | Start/stop/restart RPC (remote process communications) daemons needed to use NFS. To run an NFS server, starting these is mandatory.
| samba | off | samba | Start/stop/restart the Samba SMB CIFS file and print server for CIFS clients. It allows you to manage a file space or printers on a Samba host available to CIFS clients (such as PCs running Windows).
| saslauthd | off | cyrus-sasl | saslauthd is a daemon process that handles plaintext authentication requests on behalf of the SASL library. The CMU Cyrus SASL library is mostly used to authenticate to mail servers.
| serial | off | util-linux | Initializes and sets the serial ports on your system
| setterm | on |util-linux | Provides the command line for the setterm utility to set the terminal attributes (primarily used for screen blanking and power management).
| smartd | off | smartmontools | Start/stop/restart the smartd daemon, which monitors the status of S.M.A.R.T. compatible hard drives and reports any problems.
| snmpd | off | net-snmp |Start/stop the net-snmp SNMP (Simple Network Management Protocol) daemon
| speechd-up | | speechd-up | starts/stop/restart the speechd-up screen reader, which can be started after installation typing speak-with speechd-up.
| sshd | on | openssh | Start/stop/restart the secure shell daemon.
| swapinzram | on | swapinzram | Configure a swap block device in RAM using zram
| syslog | on | sysklogd | Start/stop/restart the system logging daemons, that logs both kernel and system's messages.
| sysstat | off | systat | Reset the system activity logs, used to compute performance statistics
| sysvinit | on | sysvinit-scripts | This file provides basic compatibility with SystemV style startup scripts found in many binary packages
| timidity | off | TiMidity++ | Start/stop/restart the TiMidity++ daemon. TiMidity++ is a software synthesizer. It can play MIDI files by converting them into PCM waveform data or other various audio file formats.
| udev | on | eudev | This script initializes udev, which populates the /dev directory with device nodes, scans for devices,
loads the appropriate kernel modules, and configures the devices.
| ulogd | on | ulogd | starts the userspace ulogd daemon for netfilter/iptables related logging.
| vde2 | on | vde2 | Start/stop/restart the VDE daemon. VDE is an ethernet compliant virtual network which includes tools such as 'vde_switch' and 'vdeqemu'.
| wireless | on | wireless-tools|This script sets up PCI, USB, and 32-bit Cardbus wireless devices. Normally this script is called from rc.inet1 rather than run directly
| yp | on | yptools | Start NIS (Network Information Services). NIS provides network-wide distribution of hostname, username, and other information databases.
|====

Pode iniciar ou parar um serviço usando como root o comando `service`. Para saber mais escreva `man service`.
// Glossary

== Glossário

Várias definições neste glossário são tiradas ou adaptadas da https://en.wikipedia.org/wiki/Main_Page[Wikipédia] e https://pubs.opengroup.org/onlinepubs/9699919799/[POSIX]

[[application]]Aplicação:: Um programa de aplicação (aplicação por abreviatura) é um programa de computador projetado para realizar uma tarefa específica normalmente solicitada por utilizadores.
+
As aplicações não são geralmente consideradas como parte do sistema operativo, o que significa que elas podem ser adicionadas ao sistema após a sua instalação. Elas executam funções não relacionadas com o sistema, tais como processamento de texto, desenho de arquitetura, desenho mecânico, publicações, ou análise financeira.


[[boot]]Arranque::
Arranque significa ligar um computador para iniciar um sistema operativo. Vários sistemas operativos podem ser instalados no mesmo computador. Selecione qual para carregar na RAM e executar pode ser feito pelo firmware ou por um software chamado gestor de arranque (GRUB no caso do Slint). O firmware de um computador pode suportar um dos seguintes modos de arranque, ou ambos:
+
* No modo Legacy ou BIOS, o sistema operativo é carregado executando as instruções gravadas num sector de arranque(boot).
* No modo EFI, o carregador do sistema operativo é um programa armazenado num ficheiro executável, localizado num diretório de uma partição do sistema EFI (ESP).

[[CPU]]CPU::
A Unidade de Processamento Central ou CPU executa as instruções dos programas.

[[command]]Comando:: O comando é definido por https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_104[POSIX] como "uma diretiva para uma <<shell,shell>> para executar uma tarefa específica".
+
A tarefa a ser executada pode ser uma <<application,aplicação>> ou um <<utility,utilitário>>.
+
A estrutura básica dos comandos da shell é definida no capítulo https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09[2.9 Shell Commands] da especificação POSIX.
+
Exemplos de comandos são fornecidos em <<bash shell>>.

[[console]]Consola:: A palavra "consola" refere-se ao início dos sistemas de computador, quando o administrador de sistema escreveu comandos num dispositivo, incluindo um teclado e uma impressora, ligados ao computador, aos comandos introduzidos e resultado do computador sendo impresso na consola, fornecendo um registo de ambos.
+
Em computadores pessoais, o utilizador escreve os comandos no teclado e o seu resultado é impresso num ecrã, que podem ser separados ou integrados no computador como num portátil.

[[device]]Dispositivo::

Um periférico do computador ou um objeto que aparece na aplicação como tal.[POSIX]

[[directory]]Diretório::
Um diretório é outro nome para uma pasta. Sistemas de ficheiros usam diretórios para organizar ficheiros dentro de partições.
+
Os diretórios podem conter ficheiros e também outros diretórios. A estrutura resultante pode ser representada como uma árvore invertida. O diretório de nível superior de uma unidade é nomeado como diretório root. No Linux, o carácter / separa os níveis da árvore. A / sozinha representa o diretório root, /home hospeda os ficheiros pertencentes a utilizadores, /home/hugo hospeda os ficheiros que pertencem ao diretório do utilizador hugo. /root hospeda os ficheiros root nomeados pelo utilizador (o administrador do sistema). Nota: 'root' pode se referir ao diretório de nível superior ou ao administrador do sistema.

[[drive]]Unidade::
Uma unidade é um dispositivo que armazena dados não voláteis, o que significa que os dados não são apagados quando a energia é desligada. Exemplos: discos rígidos, SSD, dispositivos USB, leitores de cartões, eMMC.
+
O meio de armazenamento dos dados pode ser permanentemente ligado à unidade ou removível como cartões SD, dispositivos USB e discos ligados através de USB.
+
Um sistema operativo instalado num suporte removível ou numa unidade externa é dito portátil: o mesmo pode ser movido de um computador para outro.

[[display_manager]]Gestor de ecrã::
Um gestor de ecrã (ou gestor de acesso) é um software que mostra uma janela no qual pede o nome de acesso e a palavra-passe do utilizador, depois inicia o ambiente gráfico escolhido pelo referido utilizador.

[[encryption]]Encriptação::
A encriptação é o processo de conversão de dados numa forma não reconhecida ("encriptado"). É normalmente usado para proteger informações confidenciais para que apenas pessoas autorizadas possam visualizá-las. Um único ficheiro ou diretório, uma partição também como uma unidade inteira pode ser encriptada, que o tornam acessível apenas após ter escrito um pequeno texto chamado de palavra-passe, mantido em segredo.

[[file]]Ficheiro::
Um ficheiro de computador é um conjunto de dados digitais reunidos com o mesmo nome, gravados num meio de armazenamento permanente, chamado de armazenamento em massa, como um disco rígido, um SSD, um DVD, um cartão SD ou uma pen USB e tratado como uma unidade.
+
Os ficheiros podem conter dados como textos, imagens, sons, vídeos ou programas de computador.

[[file_system]]Sistema de ficheiros::
Um sistema de ficheiros é um software que gere os ficheiros e diretórios de uma partição. Memoriza o local no suporte físico dos dados contidos nos ficheiros, permitindo lê-los ou grava-los. Exemplos de sistemas de ficheiros usados são vfat, ntfs, ext4, f2fs. Este comando lista todos os sistemas de ficheiros que permitem ler os dados contidos numa partição do Linux:
+
----
cat /proc/filesystems|grep -v nodev
----

[[firmware]]Firmware::
Um firmware é um software que inicializa e verifica o hardware, depois ou é selecionado e carregado na RAM do sistema operativo, ou inicia um software chamado gestor de arranque que fará isso. O firmware é mantido em memórias não-voláteis dispositivos como ROM, EPROM ou flash memória. É o primeiro software executado ao arrancar um computador. Fornece um menu permitindo configurar o hardware e selecionar em que modo (Legacy ou EFI) arranca e em que ordem procura o sistema operativo ou outra aplicação (como o Gestor de arranque GRUB) a executar.

[[kernel]]Kernel::
Um kernel Linux é o software no núcleo de um sistema Slint que lida com as interações entre as aplicações e o hardware.
+
Apresenta-se como um único ficheiro, instalado no diretório /boot. Por exemplo, o ficheiro /boot/vmlinuz-generic-5.12.11 é um kernel, vindo de um pacote genérico.
+
No arranque o kernel é copiado para a RAM.

[[initrd]]Initrd::
Um initrd (mais precisamente uma initramfs ou sistema e ficheiros inicial RAM para o Slint) é um sistema Linux fornecido como um ficheiro comprimido. No arranque, logo após o kernel ser carregado na RAM, o inird também é carregado na RAM. O seu ficheiro /init executa: carrega os módulos kernel necessários na RAM, regista os dispositivos, possivelmente desbloqueia o dispositivo root, monta o pseudo sistema de ficheiros e depois muda para o sistema de ficheiros root para iniciar o sistema de verdade.
+
Um initrd apresenta-se como um único ficheiro, instalado no diretório boot. Por exemplo, o ficheiro initrd-generic-5.12.11 é um initrd

[[live_system]]Sistema "live"::
Um sistema 'live' é um sistema operativo que, ao invés de ser instalado num dispositivo como um disco rígido ou SSD, encontra-se inteiramente na <<RAM>>.
+
Um initrd é também um sistema "live", assim como um instalador do Slint que é basicamente um initrd.

[[partition]]Partição::
Uma partição é uma secção de um meio de armazenamento, como um disco rígido ou SSD. É tratada pelo sistema operativo como um volume lógico separado, o que o faz funcionar de forma semelhante a um suporte separado.

[[partition_table]]Tabela de partições::
Uma tabela de partições é a estrutura permanente que regista como as informações são posicionadas num suporte, principalmente gravar o início e o fim de cada partição no suporte.
+
Os tipos mais comuns de tabelas de partições são a tabela de partições DOS, inicialmente usada pelo sistema operativo MS-DOS, e a tabela de partições do GUID ou GPT, que permite lidar com mais partições e unidades maiores.

[[program]]Programa::
Uma sequência de instruções preparada para o sistema realizar uma tarefa definida. O termo "programa" engloba aplicações escritas na Linguagem de Comando Shell, linguagens de entrada de utilidade complexa (por exemplo, awk, lex, e assim por diante) e linguagens de alto nível. [POSIX]

[[RAM]]RAM::
RAM significa Memória de Acesso Aleatório. Este tipo de dispositivo armazena dados voláteis, o que significa que os dados são apagados quando a energia é desligada.

[[shell]]Shell:: Um programa que interpreta sequências de entrada de texto como comandos. Pode operar num fluxo de entrada ou pode alertar e ler comandos de um terminal de forma interativa. A sintaxe dos comandos que podem ser interpretados pela shell pode variar dependendo da shell em uso, mas são principalmente definidos no capítulo https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html[2. Shell Command Language] da especificação POSIX.
+
O Slint vem com vários programas atuando como shell, listados no ficheiro /etc/shells. A shell *bash* é usada por padrão.

[[swap]]Swap::
Um espaço swap é utilizado para armazenar dados previamente na RAM num dispositivo como um disco rígido ou SSD, quer porque caso contrário a RAM ficaria cheia, quer para espaço livre na RAM para armazenar ali os dados mais frequentemente utilizados. O espaço swap pode ser uma partição numa unidade do tipo 'Linux swap' ou um ficheiro comum armazenado numa partição existente. Há também a 'swap in zram': neste caso, os dados são armazenados na RAM, mas em formato comprimido.

[[terminal]]Terminal::
Historicamente, um terminal é um dispositivo físico composto por um teclado e um ecrã usado para escrever comandos e receber respostas de um computador remoto.
+
Hoje em dia os comandos podem ser introduzidos no modo consola (ou texto) ou no modo gráfico.

[[utility]]Utilitário::
Um utilitário é um programa que pode ser chamado pelo nome de uma shell (este também é o caso de algumas <<application,aplicações>>).
+
Os utilitários são parte do sistema operativo (mas não do kernel).Executam funções relacionadas com o sistema, como listar conteúdo de diretórios, verificação do sistema de ficheiros, reparação do sistemas de ficheiros ou extração de informações do estado do sistema.
+
Um utilitário pode ser invocado como um programa separado que executa num programa diferente do que o intérprete de linguagem de comando, ou pode ser implementado como uma parte do intérprete de linguagem de comando.
+
Por exemplo, o comando echo (a diretiva para executar uma tarefa específica) pode ser implementado de tal forma que o utilitário echo (a lógica que executa a tarefa de echoing) esteja num programa separado; portanto, é executado num processo diferente do interpretador de linguagem de comando. Praticamente isto significa que neste caso o utilitário é um programa distinto da shell
+
Por outro lado, a lógica que executa o utilitário echo poderia ser embutida no interpretador de linguagem de comando; portanto, poderia executar no mesmo processo que o interpretador de linguagem de comandos. Diz-se que tal utilitário é "embutido" na shell.

[[virtual_terminal]]Terminal virtual::
Um terminal virtual é um software que simula um terminal físico, dispositivo composto por um teclado e um ecrã que permite comunicar remotamente com um computador.
