
= Руководство пользователя Slint (версия 15.0)
:toc: left
:toclevels: 2
:toc-title: Content
:pdf-themesdir: themes
:pdf-theme: default

Note: this document will be updated to reflect recent changes - 21/06/2024

== Введение в Slint

=== О Slint

Slint — это https://en.wikipedia.org/wiki/Linux_distribution[дистрибутив Linux], основанный на http://www.slackware.com/[Slackware], многоязычный, простой в установке, универсальный, удобный для начинающих и доступный для людей с ограниченным зрением.

Система Slint функционирует "из коробки" и может быть адаптирована к большинству требований пользователя компьютера.

==== Возможности

Предлагаются два режима установки: Автоматический (программа установки подготавливает диск, выбранный пользователем, и устанавливает на него Slint) и Ручной (программа установки форматирует раздел Linux, выбранный пользователем, и устанавливает на него Slint). Программа установки включает в себя документацию.

Slint доступен для пользователей с ограниченным зрением благодаря речевому синтезу и поддержке дисплеев Брайля, начиная с процесса установки и заканчивая использованием как в консольном, так и в графическом окружении.

Широкий ассортимент программного обеспечения для серверов, настольных компьютеров и ноутбуков установлен во всех системах Slint и включает в себя две графические среды рабочего стола: MATE и LXQt, а также легкие оконные менеджеры. MATE и LXQt обеспечивают простой доступ ко всем приложениям и системным операциям, автоматическое монтирование съемных устройств, уведомления о доступных обновлениях установленного программного обеспечения, немедленный доступ в Интернет, выключение, перезагрузку и перевод системы в спящий режим.

Выбранный язык будет использоваться для многоязычных приложений.

Панель приборов Slint обеспечивает централизованный доступ к аппаратным и системным настройкам, пакетам, системным инструментам, документации и утилитам.

Slint поставляется с множеством приложений для создания, редактирования, просмотра и преобразования документов в различных форматах, общения по электронной почте, участия в текстовых и аудиочатах, воспроизведения аудио и видео, отправки и приема документов, редактирования аудио, видео и графических документов, разработки приложений. Его можно использовать в качестве сервера в консольном режиме или выбрав одно из нескольких окружений рабочего стола.

Многие приложения доступны для слабовидящих пользователей, включен широкий выбор речевых синтезаторов и связанных с ними голосов. При необходимости могут быть установлены дополнительные инструменты и приложения, используемые как в текстовом (консоль), так и в графическом окружении.

Несколько встроенных инструментов облегчают администрирование и настройку вашей системы Slint.

Многие другие приложения легко собираются или устанавливаются в виде программных пакетов с помощью простой команды или нескольких кликов. Доступ к тысячам пакетов программного обеспечения находится у вас под рукой!

Slint уведомляет пользователей об обновлениях для установленных пакетов, как только они становятся доступны, и позволяет легко установить их по запросу. Это обеспечивает безопасность системы.

Для приложений предоставляются рекомендуемые настройки по умолчанию, которые могут быть легко изменены.

==== Состав, версии и модель выпуска

Программа установки Slint обеспечивает только полную установку.

Slint частично следует непрерывной модели выпуска. Это означает, что в течение жизненного цикла определенной версии, помимо обновлений безопасности и исправлений серьезных ошибок, некоторые программы выборочно обновляются для внесения усовершенствований или добавляются для внесения новых возможностей. Это относится к программному обеспечению, позволяющему сделать Slint доступным для слепых, например к программам для чтения с экрана.

Мы рекомендуем пользователям переходить на новую версию как можно скорее после ее выпуска. Мы рекомендуем выполнять полную резервную копию всех данных, которые пользователь хотел бы сохранить, с последующей установкой новой системы и восстановлением этой резервной копии.

=== Об этой книге, другие источники информации

Эта книга предназначена для новичков и помогает им в процессе установки и использования Slint. В книге представлены понятия и соглашения, специфичные для Slint и распространенные среди дистрибутивов Linux, также прилагается глоссарий.

Мы стараемся помочь людям, переходящим с Windows или MacOS, а также пользователям других дистрибутивов, например, Ubuntu.

Документация на установленное программное обеспечение, как правило, доступна в системе Slint. Мы расскажем в этой книге, как к ней обратиться.

Имеются и другие источники информации:

* Авторы программного обеспечения, включенного в Slint, часто предоставляют информацию на своем сайте.
* http://docs.slackware.com/[Проект документации Slackware] и, в частности, его http://docs.slackware.com/howtos:start[статьи HOWTO]. Многие из них применимы к Slint непосредственно, в некоторых случаях может потребоваться адаптация и доработка.
* Помимо информации о дистрибутиве Arch, ArchWiki часто содержит полезные статьи о программном обеспечении, поставляемом в Slint. Например поиск "arch wiki mate" позволяет найти https://wiki.archlinux.org/index.php/MATE[эту страницу о MATE]. Предупреждение: предоставленная информация может потребовать адаптации, так как Slint и Arch различаются в ряде аспектов. Например, Arch использует systemd в качестве подсистемы init, и настройки по умолчанию для конкретной программы могут отличаться в Slint и Arch.
* И, конечно, поисковая система в Интернете часто помогает найти ответы на вопросы и решения проблем.
// Support

=== Поддержка

Вы можете получить помощь по следующим каналам:

* Список рассылки Slint является основным каналом поддержки. Чтобы зарегистрироваться, отправьте письмо с темой 'subscribe' на адрес slint-request@freelists.org, затем ответьте на письмо с подтверждением, которое вы получите. Чтобы узнать больше, отправьте письмо с темой 'commands' или 'help' на адрес slint-request@freelists.org. После регистрации вы сможете отправлять письма на slint@freelists.org.
* Архивы списка рассылки доступны https://www.freelists.org/archive/slint[здесь].
* Посредством IRC: общайтесь на канале #slint, сервер irc.libera.chat, регистрация не требуется.
* Mumble: сервер slint.fr (по приглашению, полученному через другой канал).
* https://forum.salixos.org/viewforum.php?f=44[Форум Slint] поддерживается нашими друзьями в Salix (еще один дистрибутив, основанный на Slackware). Необходима регистрация.


To find out more, see the links under Information in the Slint Dashboard or just type: slint-doc in a terminal after installation.

=== Перевод и другая помощь проекту Slint

Slint нуждается в переводчиках! Если вы хотите принять участие в работе над переводом, прочитайте инструкции на странице https://slint.fr/doc/translate_slint.html[Translate Slint].

Файлы перевода размещены на https://crowdin.com/project/slint[Crowdin].

Если вы хотите внести свой вклад в Slint по другим направлениям, просто отправьте письмо в список рассылки или напишите на адрес didieratslintdotfr. Разумеется, переводчики также приглашаются в список рассылки!
// Acknowledgments

=== Благодарности

Проект Slint существует в основном за счет усердной работы переводчиков Slint и других участников, спасибо всем вам!

Выражаем благодарность Джорджу Влахавасу за его советы и инструменты, участникам проекта SlackBuilds.org, которые помогают в сборке большого числа дополнительных программных пакетов.

Slint основан на Slackware, созданном Патриком Дж. Фолькердингом и другими участниками. Спасибо! Я призываю всех пользователей Slint внести вклад в финансирование Slackware, а также пожертвовать проекту Salix.

Репозитории Slint размещаются бесплатно благодаря Darren 'Tadgy' Austin. Я призываю всех пользователей Slint внести свой вклад в финансирование https://slackware.uk/

Ссылки для финансовых пожертвований: +
https://www.patreon.com/slackwarelinux[Стать спонсором Slackware] или https://paypal.me/volkerdi[Поддержать Slackware] +
Перейдите по ссылкам в начале http://slackware.uk/slint/x86_64/slint-15.0/[этой страницы], чтобы поддержать Slackware UK +
https://salixos.org/donations.html[Пожертвования для Salix]

== Установка Slint

Данный раздел Руководства освещает процесс загрузки Slint, проверку ISO-образа с помощью контрольной суммы, запись ISO на установочный носитель, разметку жесткого диска, а также кратко описывает процесс установки.

=== Требования

Текущая версия Slint может быть установлена на компьютеры, отвечающие следующим требованиям:

* Архитектура: x86_64 (64-битный процессор), также известная как AMD64
* В режиме автоматической разметки: диск размером не менее 50 Гб
* In Manual partitioning mode a partition of type Linux of size at least 50G, an EFI system partition and/or a BIOS boot partition on the same disk drive. The EFI partition is mandatory if the machine boots in EFI mode, the BIOS boot partition if the machine boots in Legacy mode, having both is better to allow swictching between EFI and Legacy modes.
* Slint может быть установлен на следующие типы носителей: жесткие диски, SSD, NVME, eMMC, USB-флэш-накопители, SD-карты (желательно в USB-корпусах).
* ОЗУ: не менее 2 Гб
* DVD-привод или разъем USB с возможностью загрузки с диска DVD или USB-накопителя. В качестве установочного носителя можно использовать пустой диск DVD или USB-накопитель размером 5 Гб и более.

NOTE: Функция Secure boot должна быть отключена для установки Slint.

=== Особенности программы установки

* Программа установки является "Live-системой", работающей в памяти: она не изменит установленную систему до тех пор, пока вы не подтвердите внесение изменений.
* Для слепых пользователей программа установки полностью доступна с помощью дисплея Брайля и программы чтения с экрана Speakup.
* Она включает в себя все необходимые утилиты для подготовки дисковых разделов перед установкой в режиме ручной разметки.
* В режиме автоматической разметки пользователю предлагается просто ответить на вопросы, для которых предусмотрена контекстная справка.
* В случае установки на съемное устройство, подключенное через USB, Slint становится переносимым, т.е. может быть запущен на любом другом компьютере, поддерживающем загрузку с USB. Например, после установки на USB-флэш-накопитель достаточно будет просто подключить его к компьютеру для запуска Slint.
* Программа установки может зашифровать диск, на котором Slint установлен в качестве единственной ОС. Это предотвращает кражу данных в случае потери или кражи устройства или съемного диска.
* Slint может быть установлен на выделенный для него накопитель или (в режиме ручной разметки) вместе с другой системой.

=== Подготовка

<<download_and_verify,Загрузка и проверка ISO-образа Slint>> +
<<write_the_iso,Запись ISO-образа на установочный носитель>> +
<<prepare_partitions_for_Slint,Подготовка разделов для Slint (опционально)>>

[[download_and_verify]]
==== Загрузка и проверка ISO-образа Slint

Последняя версия дистрибутива Slint - 15.0.

Последний установочный ISO-образ всегда доступен в https://slackware.uk/slint/x86_64/slint-15.0/iso[этом каталоге].

This ISO image can also be downloaded using a Torrent Client from this page:

https://seedbox.slackware.uk/

The link to the torrent, after the label "Slint Torrents", is:

https://seedbox.slackware.uk/torrents/slint64-15.0-5-iso.torrent

A magnet is also provided.

[TIP]
====
Если вы уже используете Slint версии 15.0, переустанавливать систему с каждым выпуском нового ISO не требуется, так как новые образы лишь расширяют возможности программы установки и добавляют пакеты, которые вы можете получить, обновляя систему по сети.
====

Имя файла ISO, указанное ниже, является лишь примером, при загрузке его необходимо заменить на текущее имя.

Если вы работаете в Windows, поиск в Интернете с запросом "проверка sha256 windows" подскажет, что делать дальше.

Если вы используете Linux, вы можете загрузить ISO-образ и его контрольную сумму sha256, введя:
----
wget https://slackware.uk/slint/x86_64/slint-15.0/iso/slint64-15.0-5.iso
wget https://slackware.uk/slint/x86_64/slint-15.0/iso/slint64-15.0-5.iso.sha256
----

Для проверки целостности загруженных файлов введите следующую команду:
----
sha256sum -c slint64-15.0-5.iso.sha256
----

Результат должен быть: OK +
В противном случае повторите загрузку.

[[write_the_iso]]
==== Запись ISO-образа на установочный носитель

В качестве установочного носителя можно использовать DVD или USB-флэш-накопитель.

[TIP]
====
You can just store the ISO image in the first partition of a Ventoy USB stick.

In this case at the beginning of installation the installer will request that you mount this partition, then mount the ISO itself.
====

[[make_a_bootable_usb_stick]]
===== Создание загрузочного USB-флэш-накопителя

В системе ++Linux++ подключите USB-накопитель и проверьте его имя следующей командой:

----
lsblk -o model,name,size,fstype,mountpoint
----

[WARNING]
====
Внимательно прочитайте вывод команды, чтобы убедиться, что вы не введете имя раздела жесткого диска вместо имени вашего USB-накопителя. Всё предыдущее содержимое USB-накопителя или ошибочно введенного раздела жесткого диска будет **БЕЗВОЗВРАТНО УТЕРЯНО**.
====

Предположим, что имя USB-накопителя - /dev/sdb. Он может быть назван иначе, поэтому не копируйте следующую команду вслепую. Синтаксис команды для записи ISO-образа Slint на USB-накопитель /dev/sdb выглядит следующим образом:

----
dd if=slint64-15.0-5.iso of=/dev/sdb bs=1M status=progress && sync
----

[NOTE]
====
Приведенная выше команда предполагает, что **if=** указывает на путь к ISO-образу Slint, а **of=** указывает на имя USB-накопителя. Эти значения могут отличаться в вашей системе.
====

В ++Windows++ используйте такие приложения, как, например, http://rufus.akeo.ie/[Rufus]. Rufus является свободным программным обеспечением с открытым исходным кодом.

[[make_a_bootable_DVD_disc]]
===== Создание загрузочного DVD-диска

В системе ++Linux++ вставьте диск DVD и введите следующую команду:

----
xorriso -as cdrecord -v dev=/dev/sr0 -eject slint64-15.0-5.iso
----

Обязательно введите полный путь к ISO-образу Slint в вашей файловой системе.

В ++Microsoft Windows 2000/XP/Vista/7++ вы можете записать DVD с помощью приложения http://infrarecorder.org/[InfraRecorder]. Это свободное программное обеспечение с открытым исходным кодом.

On ++Microsoft Windows 7/8/10++ you can use the utility that is shipped with Microsoft Windows.

* Right-click the ISO file and select Burn disk image (if on Windows 11, select Show more options first (Shift+f10)
* To make sure the ISO was burned without any errors, select Verify disc after burning.

[NOTE]
====
Instructions not checked by the writer.
====

// Prepare
[[prepare_partitions_for_Slint]]
==== Подготовка разделов для Slint (опционально)

В этом документе 'форматирование' раздела означает создание на нем файловой системы для управления файлами, которые она будет содержать.

Если после ввода 'start' вы ввели 'm' для ручной разметки, вам будет предложено выбрать корневой системный раздел, который будет смонтирован как "/", а затем тип файловой системы: btrfs, ext4 или xfs.

Программа установки предлагает для выбора только незашифрованные разделы размером не менее 50G с типом Linux (тип раздела также может называться Linux filesystem). Такой раздел может быть отформатирован или нет, но в любом случае его содержимое будет уничтожено и новая файловая система будет создана программой установки.

Кроме того, на диске с корневым системным разделом режим ручной разметки требует наличия:

* A partition of type BIOS boot partition, of size at least 3M and not formatted if the machine boots in Legacy mode and the drive has a partition table of type GPT.
* A partition of type EFI system, with at least 32M free space in it, formatted with a 'fat' (or 'vfat') file system as required by the UEFI specification if the machine boots in EFI mode

It is better to set up both partitions to allow switching between Legacy and EFI modes if the drive has a partition table of type GPT.

Using for Slint existing partitions or creating them is up to the user. Already installed systems using the BIOS boot and the EFI partitions will not be affected, only the root partition will be (re)formatted, and an existing /home partition only if requested.

Программа установки включает в себя несколько приложений для разметки: cfdisk, fdisk, sfdisk, cgdisk, gdisk, sgdisk, parted. Приложения с "g" в их имени могут работать только с GPT, parted может работать как с таблицами разделов DOS, так и GPT. fdisk, cfdisk и sfdisk могут работать с таблицами разделов DOS. Кроме того, доступны wipefs (для удаления предыдущей таблицы разделов и сигнатур файловых систем) и partprobe (для информирования ядра об изменениях в таблице разделов). Приложения blkid и lsblk отображают информацию о блочных устройствах и разделах.

Конечно, вы также можете создать разделы в другой системе перед запуском программы установки.
// Installation

=== Установка Slint
<<Start_of_the_installation,Начало установки>> +
<<Overview_of_Slint_Installation,Обзор процесса установки>> +
<<Usage_of_the_installer,Использование программы установки>> +
<<Encryption,Slint с зашифрованным корневым разделом>> +
<<Speakup,Сочетания клавиш для программы чтения с экрана Speakup>> +
<<first_steps_after_installation,Первые шаги после установки>>

[[Start_of_the_installation]]
==== Начало установки

При необходимости настройте системное ПО компьютера для загрузки с подготовленного DVD или USB-флэш-накопителя.

Вставьте установочный носитель (DVD или USB-накопитель) и перезагрузите компьютер. Для удобства незрячих пользователей при отображении загрузочного меню поступит звуковой сигнал.

Запустите программу установки, просто нажав Enter.

Программа установки сначала проверит ваши звуковые карты.

Это может помочь выбрать рабочую карту по умолчанию, а также позволит слепым пользователям использовать озвучку во время установки.

Если программа установки обнаружит более одной звуковой карты, она произнесет на английском языке для каждой карты: +
press Enter to choose this sound board <идентификатор звуковой карты> +
Нажмите Enter, как только услышите эту фразу, чтобы подтвердить, что предлагаемая звуковая карта работает. Этот выбор будет сохранен в устанавливаемой системе в файле /etc/asound.conf.

На следующем шаге вы сможете подтвердить (введя s) или отказаться (просто нажав Enter) от использования речевой озвучки во время установки. Дисплей Брайля всегда доступен во время установки.

Затем вы выберете, подтвердив или изменив, язык, используемый в процессе установки. В дальнейшем все экраны будут отображаться на выбранном языке, если перевод на этот язык завершен.

Если вам нужно добавить дополнительные параметры ядра в загрузочную командную строку, перед нажатием клавиши Enter выполните следующие действия:
[NOTE]
====
Обратите внимание, что при вводе будет использоваться раскладка клавиатуры США. +
Ctrl+x означает "Нажмите и удерживайте клавишу Ctrl или Control так, как если бы это была клавиша Shift, после чего нажмите клавишу X".
====
----
Нажмите клавишу e
Нажмите стрелку вниз три раза
Нажмите клавишу End
Нажмите пробел
Введите параметры ядра (примеры приведены ниже)
Нажмите Ctrl+X для загрузки (не нажимайте Enter!)
Нажмите Enter для загрузки.
----

Например, для настройки драйвера speakup для вашего аппаратного синтезатора речи можно ввести параметр ядра следующего вида:
----
speakup.synth=apollo
----
Вы также можете включить в загрузочную командную строку настройки для вашего устройства Брайля в следующей форме:
-----
brltty=<driver code>,<device>,<text table>
-----
Например, для установки с устройством Papenmeier с французской текстовой таблицей, подключенным через USB, введите:
-----
brltty=pm,usb:,fr_FR
-----
NOTE: Устройство Брайля, подключенное через USB, всегда должно быть распознано, однако текстовая таблица может оказаться неподходящей, если вы сначала не ввели настройки.

В любом случае действия в загрузочном меню не ограничены по времени, и загрузка начнется только после нажатия [Enter].

Речевой синтез и дисплей Брайля доступны с начала установки.
// Overview
[[Overview_of_Slint_Installation]]
==== Обзор процесса установки

Программа установки сначала проверяет существующие диски и разделы для оценки возможностей и вариантов установки и позволяет выбрать между автоматической или ручной подготовкой разделов, используемых Slint.

Если вы выберете 'ручная', вам будут предложены разделы Linux, на которые может быть установлен Slint (размером не менее 50 Гб), выберите один из них и выберите тип файловой системы, которая будет создана программой установки: btrfs, ext4 или xfs, как указано в разделе <<prepare_partitions_for_Slint,Подготовка разделов для Slint (опционально)>>.

Если вы выберете 'автоматическая', вам будут предложены диски, на которые может быть установлен Slint (размером не менее 50 Гб), и файловая система будет иметь тип btrfs.

In case of btrfs sub-volumes will created for "/" and "/home" with files compressed, and /swap to host a swap file. 'Copy on write' will ease making snapshots and possibly revert a faulty system update. Tools to manage the snapshots are included in Slint.

В обоих режимах разметки пользователь выбирает, какие существующие разделы Linux и Windows будут автоматически монтироваться после загрузки Slint, а также имена их точек монтирования, что позволяет облегчить доступ к существующим системам и данным из Slint.

Далее пользователю предлагается зашифровать корневой системный раздел, чтобы предотвратить кражу данных в случае потери или кражи устройства или накопителя, на котором установлен Slint. Получив подтверждение, программа установки записывает пароль, позволяющий разблокировать этот раздел. Пользователь будет вводить его во время загрузки в ответ на запрос от GRUB для отображения загрузочного меню.

В конце концов программа установки подытожит ваш выбор и позволит вам подтвердить его. До этого момента в существующие системы и данные не будет внесено никаких изменений, поэтому вы можете отказаться, заново ввести "start" или просто перезагрузиться, не нанеся им никакого вреда.

После этого при необходимости происходит автоматическая разметка диска и шифрование корневого раздела Slint, форматируется корневой раздел и устанавливаются первые программные пакеты.

Если вы выбрали шифрование диска, потребуется ввести пароль, который будет использоваться для разблокировки диска при каждой загрузке.

Далее вы выбираете пароль для пользователя "root". Это системный администратор, у которого есть все полномочия.

Вы также выбираете имя и пароль для обычного пользователя.

Далее вы указываете, требуется ли вывод на дисплей Брайля и хотите ли вы входить в систему в текстовом или графическом режиме. Если во время установки использовался язык "Английский (США)", вам будет предложено выбрать язык, который будет использоваться в установленной системе, иначе автоматически выбирается язык, на котором осуществлялась установка.

Программа установки попытается установить соединение с Интернетом, и, в случае успеха, предложит часовой пояс, соответствующий вашему географическому расположению. Вы можете подтвердить предложенный вариант или выбрать другой из списка.

Программа установки уточнит, нужна ли вам поддержка дисплея Брайля, а также предпочитаете ли вы запускать систему в текстовом или графическом режиме. Если вы использовали речевую озвучку во время установки или нуждаетесь в поддержке дисплея Брайля, то после перезагрузки вы попадете в консоль, для безопасности.

Затем программа установки создаст файл подкачки. Это может занять много времени, пожалуйста, наберитесь терпения.

Программные пакеты устанавливаются на диск. При наличии соединения с Интернет будут загружены и установлены последние версии всех пакетов, в том числе те, что были выпущены после выхода ISO-образа.

Установка всех пакетов занимает от 10 до 40 минут в зависимости от оборудования.

Вам будет предложено выбрать окружение рабочего стола (даже если вы выбрали запуск в текстовом режиме) среди fvm, lxqt, mate и wmaker. Другие варианты будут доступны после установки с помощью команды 'xwmconfig', если вы загрузились в консоль.

Затем система будет настроена, и будет установлен менеджер загрузки GRUB. Slint может загружаться как в режиме Legacy, так и в режиме EFI. Меню загрузки будет включать в себя загрузочную запись "rescue" для обнаружения и запуска любой установленной ОС.

Вы можете отобразить предварительный просмотр загрузочного меню перед перезагрузкой.

Затем извлеките установочный носитель и перезагрузитесь, чтобы запустить вашу новую систему Slint.
// Usage_installer
[[Usage_of_the_installer]]
==== Использование программы установки

Если вы знакомы с командной строкой, вы можете пропустить этот раздел.

Главное меню установки показано ниже:
....
Добро пожаловать в программу установки Slint! (версия 15)

Вы можете ввести (без кавычек):

'doc' для информации об особенностях и использовании установщика.
'start' для запуска установки.

Программа установки может подготовить накопитель для установки Slint,
создав необходимые разделы. При желании вы можете сделать
это самостоятельно с помощью утилит командной строки, доступных
в программе установки, после чего ввести 'start'. Вы также можете покинуть
программу установки и использовать инструмент наподобие gparted,
после чего запустить программу установки еще раз.

В этом случае, а также если вы хотите зашифровать корневой раздел Slint,
рекомендуем сперва ввести 'doc'. По завершении чтения это меню будет
показано снова.
....

Как только на экране появляется это меню, процесс установки оказывается под вашим контролем.

Вы читаете экран и вводите команды в <<virtual_terminal,виртуальном терминале>>. Программа установки включает в себя 4 виртуальных терминала, которые имеют доступ к одним и тем же физическим клавиатуре и экрану и могут использоваться одновременно.

Программа установки запускается в виртуальном терминале 1 под названием *tty1*, но вы можете переключиться на другой. Например, вы можете переключиться на *tty2*, нажав *Alt-F2*, затем Enter, чтобы активировать его, а потом вернуться к *tty1*, нажав *Alt-F1*. Эти действия не приводят к стиранию отображаемой на обоих терминалах информации. *Alt-F1* означает: нажмите и удерживайте клавишу *Alt*, затем нажмите клавишу *F1*.

This can be useful to continue reading the documentation during installation: for instance you can switch to *tty2* to begin installation, switch to *tty1* to continue reading the documentation, then switch to *tty1* again to proceed to the next installation step.

Эту возможность также можно использовать для ознакомления с глоссарием при чтении других документов.

Программа установки имеет несколько режимов взаимодействия с пользователем:

* Вы вводите команды в ответ на приглашение командной строки и читаете их вывод.
* Программа установки задает вопрос, вы вводите ответ и подтверждаете его нажатием Enter.
* Программа установки отображает меню с вариантами для выбора, вы выбираете один из них, используя клавиши со стрелками вверх и вниз, затем подтверждаете свой выбор нажатием Enter или отменяете нажатием Escape.
* Программа установки отображает информацию с помощью пейджера (утилиты для постраничного вывода текста на экран). Используйте клавиши со стрелками для чтения следующей или предыдущей строки, нажмите пробел для отображения следующей страницы, Q для прекращения чтения документа.

// Encryption
[[Encryption]]
==== Slint с зашифрованным корневым разделом

В автоматическом режиме разметки программа установки предлагает зашифровать корневой системный раздел. Если вы согласитесь, то при каждом запуске, перед тем как отобразить загрузочное меню, загрузчик GRUB будет запрашивать пароль, который вы ввели во время установки, чтобы разблокировать диск. Обратите внимание, что разблокирование накопителя занимает несколько секунд (около десяти секунд).

Наличие зашифрованной корневой файловой системы предотвращает кражу содержащихся в ней данных в случае потери или кражи устройства или съемного накопителя. Но это не защитит вас, если компьютер не был полностью выключен и остался работать без присмотра!

Во время установки системный раздел Slint будет зашифрован, по вашему запросу могут быть зашифрованы дополнительные разделы.

Системный (или корневой) раздел Slint будет носить имя /dev/mapper/cryproot после разблокировки, если он был зашифрован.

Это можно продемонстрировать следующей командой:

----
lsblk -lpo name,fstype,mountpoint | grep /$
----

вывод которой будет иметь вид:
----
/dev/mapper/cryptroot ext4    /
----

Тогда как следующая команда:

----
lsblk -lpo name,fstype,mountpoint | grep /dev/sda3
----

отобразит:

----
/dev/sda3             cryptoLUKS
----

/dev/sda3 теперь является "сырым" разделом, содержащим так называемый "заголовок LUKS", к которому никогда не следует обращаться напрямую. В нем находится всё, что необходимо для шифрования и расшифровки раздела /dev/mapper/cryptroot, который на самом деле содержит ваши данные (в данном примере - систему Slint).

[WARNING]
====
Если вы забудете пароль, все данные на диске будут безвозвратно утеряны! Как можно скорее запишите пароль и сохраните его в надежном месте.

Диски выходят из строя. Если это произойдет и диск зашифрован, ваши данные будут утеряны. Поэтому регулярное резервное копирование важных данных является обязательным.

Кроме того, создайте резервную копию заголовка LUKS, которую можно восстановить в случае, если раздел LUKS поврежден по какой-либо причине. Пример команды, которую можно использовать для этого:
----
luksHeaderBackup /dev/sda3 --header-backup-file <файл>
----
где <файл> — это имя файла резервной копии, который вы будете хранить в надежном месте.

В дальнейшем, если вам понадобится восстановить резервную копию, введите:
----
luksHeaderRestore /dev/sda3 --header-backup-file <файл>
----

Не изменяйте размер раздела зашифрованного диска, так как после этого он будет окончательно заблокирован, и все содержащиеся на нем данные будут потеряны! Если вам действительно нужно больше места, необходимо создать резервные копии всех файлов, которые вы хотите сохранить, а затем повторить установку заново и восстановить эти файлы.

Придумайте достаточно надежный пароль, чтобы время, необходимое злоумышленнику для его подбора, было неоправданно велико.

Никогда не проводите никаких манипуляций с так называемым "заголовком LUKS", расположенном на "сыром" разделе (например, на /dev/sda3, представляющем собой "сырой" системный раздел для Slint). Фактически: не создавайте на этом разделе файловую систему, не делайте его частью массива RAID и, в целом, не пишите на него, иначе все данные будут безвозвратно утеряны!
====

Чтобы избежать слабых паролей, программа установки требует, чтобы пароль включал в себя:

. Не менее 8 символов.
. Только строчные и прописные латинские буквы без диакритических знаков, цифры от 0 до 9, пробелы и следующие знаки препинания:
+
----
 ' ! " # $ % & ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~
----
+
Это гарантирует, что даже новая клавиатура будет содержать все символы, необходимые для ввода пароля.

. По крайней мере одну цифру, одну строчную букву, одну прописную букву и один знак препинания.

GRUB предполагает, что при вводе пароля используется раскладка клавиатуры "us". По этой причине, если во время установки вы используете другую раскладку, перед запросом пароля программа установки переключит раскладку на "us" и восстановит ее обратно после того, как пароль будет сохранен. В этом случае программа установки также будет произносить вслух каждый вводимый символ пароля, так как он может отличаться от нанесенного на клавишу.

Для шифрования диска используется программа cryptsetup. Чтобы узнать о ней больше, введите после установки: +
-----
man cryptsetup
-----
// Speakup
[[Speakup]]
==== Сочетания клавиш для программы чтения с экрана Speakup

Этот раздел предназначен для пользователей, которым требуется программа чтения с экрана, но которые не знакомы со Speakup.

Оставьте numlock выключенным для использования Speakup.

Клавиша CapsLock используется как клавиша Shift. Например, "CapsLock 4" означает: +
зажмите клавишу CapsLock так, как вы обычно зажимаете Shift, и нажмите клавишу 4.

 Сочетания клавиш, которые необходимо запомнить в первую очередь:
 PrintScreen         Включить/выключить Speakup.
 CapsLock F1         Справка по Speakup (нажмите пробел, чтобы покинуть справку).

 Сочетания клавиш для изменения настроек:
 CapsLock 1/2        Уменьшить/увеличить громкость.
 CapsLock 5/6        Уменьшить/увеличить скорость речи.

 Сочетания клавиш для чтения содержимого экрана:
 CapsLock j/k/l      Произнести предыдущее/текущее/следующее слово.
 CapsLock k (дважды)  Проговорить текущее слово по буквам.
 CapsLock u/i/o      Произнести предыдущую/текущую/следующую строку.
 CapsLock y          Прочитать экран от верхней границы до курсора чтения.
 CapsLock p          Прочитать экран от курсора чтения до нижней границы.
// First_steps
[[first_steps_after_installation]]
==== Первые шаги после установки

Ниже приведены первые действия, которые необходимо выполнить после установки.

В этом документе весь текст после символа # является комментарием для предлагаемой команды, который не нужно вводить.

===== Начальное обновление программного обеспечения

После установки система должна быть обновлена для получения последних версий каждого программного пакета, а также для получения нового ПО, предоставленного после выпуска ISO-образа. Это особенно необходимо, если сетевое подключение отсутствовало во время установки, так как в таком случае были установлены только пакеты, включенные в дистрибутив, и они могут быть устаревшими.

Большинство приведенных ниже команд требуют административных прав, связанных с конкретной учетной записью под названием 'root', для которой вы создали пароль в ходе установки.

Чтобы выполнить команду от имени 'root', сначала введите
----
su -
----
затем введите пароль для root и нажмите Enter, прежде чем вводить команду.

Когда вы закончите выполнение команд от имени 'root', нажмите Ctrl+d или введите 'exit', чтобы вернуть ваш статус "обычного пользователя".

В качестве альтернативы пользователь, зарегистрированный во время установки, и другие участники группы 'wheel' могут ввести:
----
sudo <команда>
----
а затем так же ввести пароль для root.

Для обновления введите от имени root в консоли или графическом терминале:
----
slapt-get --add-keys # получить ключи для аутентификации пакетов
slapt-get -u # обновить список пакетов на зеркалах
slapt-get --install-set slint # получить новые пакеты
slapt-get --upgrade # получить новые версии установленных пакетов
dotnew # отобразить список изменений в файлах конфигурации
----
При выполнении dotnew согласитесь заменить все старые файлы конфигурации новыми. Это безопасно, так как вы еще не вносили в них никаких изменений.

В качестве альтернативы вы можете использовать графические интерфейсы: gslapt вместо slapt-get и dotnew-gtk вместо dotnew.

Чтобы узнать больше о slapt-get, введите:
----
man slapt-get
----
или, от имени root:
----
slapt-get --help
----
и прочитайте /usr/doc/slapt-get*/README.slaptgetrc.Slint

// Usage
== Использование Slint

В этой главе рассказывается о том, как вы можете взаимодействовать с системой Slint, чтобы сделать то, что вы хотите.

=== Что такое система Slint?

Slint — это набор программ, которые примерно подпадают под эти категории:

* Операционная система создана из Linux <<kernel, ядра>> и <<utilities, утилит>>. Он действует как интерфейс между пользователем, приложениями и аппаратным обеспечением
* <<Applications, приложений,>> выполняющих задачи, которые хотят выполнить пользователи.

Слайт может быть использован в двух режимах, отличающихся внешностью экрана и способом взаимодействия с системой:

* В текстовом режиме вы вводите команды, интерпретируемые <<shell, оболочкой>>. Эти команды могут запускать утилиту или приложение. Текстовый режим также называется режимом <<console, консоль>>. В этом режиме экран отображает только команды и их вывод в (обычно черном) фоне.
* В графическом режиме графические элементы, такие как окна, панели или иконки, отображаются на экране, обычно связанные с приложениями или утилитами. Пользователь взаимодействует с этими элементами с помощью мыши или клавиатуры.

Команды также могут быть введены в графическом режиме внутри окна, связанного с a <<terminal, терминалом>> , в котором запускается оболочка.

=== Utilities provided

Beyond the utilities found in most Linux distributions, Slint includes tools written for it, inherited from Slackware and borrowed to Salix.

Here are the utilities that you can use to (re)configure your Slint system after installation. Usage of simpler ones is self-explanatory, most have an associated --help option, some are presented in further details in chapter <<Manage_your_system,Manage your system>>.

Если не указано иное, эти утилиты должны использоваться в качестве корневого каталога. Чтобы стать root, , то есть получите статус 'admin' и привилегии типа 'su -', а затем root's пароль. Чтобы вернуть статус обычного пользователя pres Ctrl+d или введите выход.

Alternatively you can run commands needing root's privileges typing "sudo <command>"

Большинство утилит имеют командную строку и графическую версию. Первая версия командной строки перечислена ниже. Если не указано иное, все команды должны быть типами как root.

*General settings*

* Для управления пользователями: настройка пользователя или gtkusersetup
* Изменить язык и регион: localesetup или gtklocalesetup
* Для изменения настроек клавиатуры и метода ввода: настройка клавиатуры или настройка gtkkeyboard
* Для настройки даты, времени или часового пояса: настройка часов и установка gtkclocp.
* Для того чтобы выбрать, какие сервисы запускаются при загрузке: сервисы и gtkservicesetup.
* Для (пере)настройки сети: сетевая установка.
* Чтобы выбрать запуск в текстовом или графическом режиме и в более позднем случае графический менеджер логинов: выбор логина
* To choose a desktop among FVWM, i3, LXQt, MATE and WindowMaker: session-chooser (as regular user)
* To choose one of these desktops or one of the standalone window managers: xwmconfig (as regular user)
* To display or not the applications specific to a desktop in other desktops: show-desktop or hide-desktop (as regular user)
* To enable or not speech in graphical mode: orca-on or orca-off (as regular user)
* To choose and enable a console screen reader or disable all of them: speak-with
* To display or not boot entries specific to MATE and/or LXQt in other graphical environments: display-desktop or hide-desktop (as regular user)
* To enable or disable emacspeak or speechd-el: switch-on or switch-off (as regular user)
* To view the layout of the GRUB boot menu as it will be displayed at next boot: list_boot_entries
* To write a rescue boot stick, allowing to boot if failing otherwise: rescuebootstick
* To save/restore the speakup settings: speakup-save or speakup-restore
* To list the voices for espeak-ng, including the mbrola ones: list-espeak-ng-voices (as regular user)
* To list the sound cards as : list-cards (as regular user)
* To list the speech synthesizers and associated languages available through speech-dispatcher: spd-list (as regular user)
 
=== Как старт Slint

После установки программное обеспечение, поставляемое в установочном ISO или скачанное из удаленных репозиториев, устанавливается в <<drive, диске>>.

Когда вы загружаете слепота, <<firmware, прошивка>> сначала проверяет аппаратное обеспечение, а затем ищет программу, называемую операционным загрузчиком (обычно именуемым системным загрузчиком), который запускается.

В машине может быть несколько системных загрузчиков. В этом случае прошивка позволяет пользователю выбрать, какой из них запускается в меню.

В Slint программа , которая делает и устанавливает системный загрузчик, это GRUB. на самом деле системный загрузчик , собранный GRUB также является менеджером загрузки, так как позволяет выбрать, какая ОС запускается, если установлены несколько.

The OS loader built by GRUB can be installed in a boot sector (in case of Legacy booting) or in an EFI System Partition or ESP (in case of EFI booting).

Целью загрузчика Slint является запуск системы Slint. Чтобы сделать это, первый загружается в ОЗУ <<kernel, ядро>>, затем <<initrd, initrd>>, который в свою очередь инициализирует систему Slint.

На последнем этапе инициализации пользователю предлагается "войти", в других словах, чтобы соединиться с системой и взять руку на нее. Чтобы сделать , сначала введите одно'с пользователем (или войти) имя, а затем пароль, действие которого проверяется. Slint as other Linux distributions being multi-users this allows this user to access one's files but not those of other users.

Во время установки вы решили запустить Slint в текстовом или графическом режиме.

* Если вы выбрали C для <<console, консоли>> после инициализации системы, вы введете имя пользователя (или войти), то ваш пароль, каждый входной файл будет подтверждён нажатием клавиши Enter, затем вы можете ввести команды.
* Если вы выбрали G (графический), вы введете такую же информацию в <<display_manager, менеджере отображения>> или менеджере входа в систему, , который затем запускает графическое окружение <<graphical_environment, >>.

After installation, you can change the mode typing as root `login-chooser`, in console mode as well as in graphical mode (in a <<terminal, terminal>>). Эта команда позволяет выбрать `текст` (синоним консольного режима), или, для графического режима, среди нескольких менеджеров. Ваш выбор будет эффективным при следующей загрузке компьютера.

Теперь мы представим графическую среду, а затем как использовать оболочку.

=== Графические окружения

<<the_windows, The windows>> +
<<the_work_spaces,The work spaces>> +
<<the_desktop,The desktop>> +
<<the_top_panel,The top panel>> +
<<the_bottom_panel, The bottom panel>> +
<<the_slint_control_center,The Slint Control Center>> +
<<graphical_terminals,Graphical terminals>> +
<<key_bindings,Key bindings>>

Полная графическая среда включает в себя несколько компонентов, Среди которых оконный менеджер, рисующий окна на экране, ассоциированные с приложениями, перемещает, изменяет размер и закрывает эти окна.

Slint includes several graphical environments: BlackBox, Fluxbox, FVWM, i3, LXQt, MATE, TWM, and WindowMaker. It is a matter of preference which one you choose.

LXQt MATE and XFCE are are full featured desktops, FVWM and WindowMaker offer unique features and can be selected with the graphical lightdm login as well and also started from a console typing "startx". The other ones are mainly window managers that can only be started from a console. All allow you to access your documents and applications, generally opened in a window.

You can choose among FVWM, i3, LXQt, MATE and WindowMaker typing as regular user `session-chooser`. In Graphical mode you also can choose one when logging in.

To choose one of the other graphical environments you need to use the command "xwmconfig".

[NOTE]
====
if you want to use i3 and need speech we recommend that you login in text mode and run **i38** before **startx**.
====

We will now briefly describe the components of the Mate desktop, which is the default and is also the most accessible with speech and braille.

С помощью мыши вы можете обнаружить возможности каждого компонента, делая или имитируя правый щелчок по центру или влево. Переместить или удалить большинство компонентов, изменить их и добавить новые могут быть выполнены таким же образом.

Эти компоненты могут достигать перемещения мыши, а также нажатия клавиш. Ниже мы указываем в скобках сочетания клавиш, позволяющие достичь, другими словами, сосредоточить внимание на каждом элементе. Мы также кратко опишем <<key_bindings, привязки кнопок>> для рабочего стола Mate (используя менеджер по умолчанию Marco Windows) и для менеджера окон Compiz.

[TIP]
====
You can discover most of the features of applications and other components of Slint with a right, middle, or left click of the mouse. For instance by clicking on the panel, the title bar, the left and right buttons of any window, an icon in the panel, or on an empty space of the screen.
====
[[the_windows]]
==== Окна

Окно - это прямоугольная область, связанная с приложением. Окна могут быть перемещены, изменены, размер, восстановлены, закрыты (заканчивая приложением, которое оно управляет) с помощью клавиш мыши или клавиатурных клавиш.

[[the_work_spaces]]
==== Рабочие места

Для того, чтобы можно было открыть много окон упорядоченно, графическая среда обеспечивает несколько рабочих мест и позволяет переключаться между ними. Каждое рабочее место отобразит один и тот же рабочий стол и панели, но окна могут быть помещены в определенное рабочее место или во всем. Эта настройка доступна правой кнопкой мыши по верхнему краю окна. Щелкнув на его позицию на нижней панели экрана, вы сможете переключиться на другую рабочую область, в области изменения рабочего пространства, как указано ниже.

[[the_desktop]]
==== Рабочий стол

Рабочий стол охватывает весь экран, на котором могут быть установлены другие компоненты, в случае Мат и как поставляются в стебель верхней и нижней панелях, и четыре значка, которые сверху внизу позволяют открывать в окнах:

* корневой каталог в файловом менеджере
* ваш домашний каталог в файловом менеджере
* центр управления слепотой
* корзина может быть там, где размещены файлы, которые вы собираетесь удалить, но не'т.

Окна приложения, которые вы запускаете, как и положить на рабочий стол.

Мат состоит из двух панелей, которые представляются как тонкие прямоугольные горизонтальные области, одна сверху и одна внизу экрана.

Нажатие клавиши Ctrl+Alt+Tab позволяет переключаться между рабочим столом, верхним и нижним панелями

Нажатие Alt+Tab позволяет перемещаться между окнами на рабочем столе.

[[the_top_panel]]
==== Верхняя панель

#-#-#-#-# ru_RU.HandBook.adoc:933 #-#-#-#-# Он представляет, слева направо, #-#-#-#-# ru_RU.HandBook.adoc:956 #-#-#-#-# Оно представляет, слева направо:

* Три меню:
** An Applications menu which can be opened pressing Alt+F1. From there you can open the other menus using the right arrow key. You can use the down and up arrow keys to navigate in each menu.
** Меню Метки.
** Системное меню, которое дает доступ к подменю настроек, центру управления Mate и кнопкам, чтобы получить справку о рабочем столе, Заблокируйте экран, закройте сессию и выключите компьютер.
* Программа запускает для mate-terminal, файловый менеджер caja, почтовый клиент thunderbird, веб-браузер firefox, текстовый редактор Geany.
* Уведомление, которое может собирать апплеты, такие как менеджер Bluetooth, звуковой микшер, менеджер сети и «доступное обновление» оповещение.
* Часы и календарь.
* Блокировщик экрана.
* Диалог о закрытии сессии.
* Выключение диалога.

[TIP]
====
* Чтобы настроить панель по своему вкусу: щелкните правой кнопкой мыши на пустом месте на панели.
* Если вы хотите переместить элемент на панели: щелкните по элементу средней кнопки, перетащите мышь, и она будет следовать за мышкой, пока не будет отпущена центральная кнопка.
* Для контекстной справки нажмите F1
====

[[the_bottom_panel]]
==== Нижняя панель

#-#-#-#-# ru_RU.HandBook.adoc:933 #-#-#-#-# Он представляет, слева направо, #-#-#-#-# ru_RU.HandBook.adoc:956 #-#-#-#-# Оно представляет, слева направо:

* Список окон, который можно настроить правой кнопкой мыши по строке из трех вертикальных точек в начале и при выборе предпочтений. Это также позволяет запускать системный монитор в окне.
* *Показать рабочий стол*. Слева от него будет сворачиваться или скрывать все окна, нажимая снова, вы восстановите окна в их предыдущем состоянии.
* Переключатель рабочего пространства или пейджер. Он позволяет переключаться с рабочего пространства на другое и перемещать окна с рабочего пространства на другое путем перетаскивания и перетаскивания.

[[the_slint_control_center]]
==== Центр управления слепотой

Мы закончим введение в Slint's, представив Центр управления Slint. Вы можете отобразить его из меню приложения на верхней панели или щелкнуть на его иконке на рабочем столе или напечатать qcontrolcenter в диалоге "Выполнить..." с Alt+F2

The goal of the control panel is to gather applications that are useful for system administration, documentation, and settings in a consistent fashion in all window managers. By clicking on a category in the left menu, you can display the corresponding applications in the right pane. We will present them in table format. This will give us the opportunity to present the administration tools that have a graphical user interface as well.

Most administrative tools should be used with administrative privileges. You will be asked for the root account password in order to launch a tool.

[options="autowidth"]
|====
<|**Category** <|**Tool** <|**Purpose and comments**
<|Applications <|Dotnew <|This tool allows you to manage the new (named __something.new__ hence the name of the tool) vs old configuration files after having upgraded some packages. It's a good habit to run if after an upgrade. It will tell you if there is something to take care of and then present you a choice of actions.
<|Applications <|Gslapt Package Manager <|Gslapt is a graphical front-end to slapt-get. It is a handy tool to perform <<software_management,software management in Slint>>. It allows you to search for, install, remove, upgrade, and configure software packages.
<|Applications <|Sourcery SlackBuild Manager <|Sourcery is a graphical front-end to slapt-src. It allows you to search for SlackBuilds scripts that it can then use to automate the build process and installation of software packages. It can also remove and reinstall packages on your system.
<|Applications <|Application Finder <|Find and launch the applications installed on your system. The search field is very handy to find applications in comparison to manually searching the application menu.
<|Information <|SlackDocs Website <|The documents in this wiki are primarily intended for a Slackware user, but many of them are useful for a Slint user. **Caution:** Some of the listed tools, like slackpkg, should **not** be used in Slint.
<|Information <|Slackware Documentation <|This documentation can be also useful for Slint users. Slint is based on Slackware.
<|Information <|MATE system monitor <|This tool displays information about the system, like the process, resources usage (RAM, CPU, network traffic) and file systems usage.
<|Information <|Slint Documentation <|This gives local access to documents also available on Slint's website.
<|Information <|Slint Forum <|People whose native language is not English may also post in the localized Salix forums.
<|Information <|Slint Website <|The Slint website provides documentation, links, and a way to find the ISOs and packages.
<|Information <|System Information <|This tool collects information about your computer, such as its connected devices (internal and external), and displays it all in one place. It can also do system bench marking.
<|System <|Display boot menu <|Display the layout of the boot menu as it will be presented at next boot
<|System <|System clock <|This tool allows you to set system clock.
<|System <|Keyboard <|This tool allows you to setup the keyboard layout.
<|System <|System Language <|This tool allows you to set the system locale (language and geographic peculiarities), so that the applications you use will display information in this locale (if available).
<|System <|System Clock <|This tools allows you to set the time zone, choose if the clock should be synchronized with Internet servers (this is recommended but of course needs an Internet connection), and if not, set the date and time.
<|System <|System Services <|This tool allows you to choose which services will be enabled at startup. For instance, Bluetooth, the CUPS print server, or a web server. Only use it to change the defaults settings if you know what you are doing.
<|System <|Users and Groups <|This tool allows you to add, remove, and set up user accounts and groups. It is mostly useful on multi-user systems.
<|System <|GUEFI Boot Manager <|This tool is a graphical front end to the efibootmanager command. It allows editing of the EFI firmware's boot menu with actions like adding, removing items or changing menu items order.
<System <|Rescue boot stick <|This tool allows to put in an USB stick all that is needed to boot Slint if not possible the usual way

|====

[[graphical_terminals]]
==== Терминалы

Команды можно вводить в графическом режиме как в консольном режиме, если вы открываете окно с терминалом в нем. В Mate можно просто нажать Ctrl+Alt+t или на значке mate-terminal на верхней панели, или откройте диалог "Выполнить... ", нажав Alt+F2, а затем набрав `mate-terminal` в открывшемся небольшом окне.

Большая часть информации ниже о командной строке и оболочке в режиме Консоль также применима к набору команд в терминале. Вы можете закрыть mate-terminal нажав Alt+F4 как и в любом другом окне.

[[key_bindings]]
==== Привязки клавиш

Здесь представлены сочетания клавиш по умолчанию для оконного менеджера Compiz и рабочего стола Mate и как их настраивать.

[NOTE]
====
Когда привязка ключей включает в себя один или более знаков *+* , затем удерживайте клавиши слева направо до последней клавиши, например клавишу `Shift` , затем нажмите последнюю клавишу.
====
===== Привязки клавиш для рабочего стола Mate

При использовании Mate в Slint, некоторые сочетания клавиш совпадают с использованием либо оконных менеджеров Marco или Compiz. Они перечислены ниже:
----
Alt+Tab Цикл между окнами
Shift+Alt+Tab Цикл назад между окнами
Control+Alt+Tab Цикл между панелями и рабочим столом
Shift+Control+Alt+Tab Цикл назад между панелями и рабочим столом
----
Once in a graphical environment, you can toggle between it and a console. Let's say you want to use tty2 (tty1 being busy): Press `Ctrl+Alt+F2`, then login. +
Press `Alt+F7` to go back to the graphical environment.

Такие же общие сочетания клавиш используются во всех графических средах, за несколькими исключениями, Модуль1 обычно является левым клавишей Alt: +
----
Mod1+F1 отображает меню приложений панели.
Mod1+F2 вызывает диалог 'run..., но во Fluxbox (запускает lxterminal вместо него).
----
Также в Fluxbox:
----
Mod1+F3 restarts Fluxbox.
Mod1+F4 закрывает выделенное окно.
----

In Mate, partially sighted users can use the Compiz window manager instead or Marco which is the default.

Как обычный пользователь, тип:
----
gsettings set org.mate.session.required-components windowmanager compiz
----
Чтобы вернуться к марко:
----
gsettings set org.mate.session.required-components windowmanager marco
----
Эта настройка вступит в силу при следующем запуске сеанса.

Или внести изменения только для текущего типа сессии:
----
compiz --replace &
----
и вернуться к марко:
----
marco --заменить &
----
Замена будет произведена немедленно

Этот параметр также доступен графически из mate-tweak, в категории Windows .

Вы можете получить доступ к определенным настройкам Compiz просто набрав:
----
ccsm &
----
===== Привязки клавиш для оконного менеджера Compiz

In the default settings indicated below the key or mouse buttons are named like this:

Super: Windows key on most keyboards +
Button1: Left Mouse Button (if used with the right hand) +
Button2: Centre Mouse Button, or click with the scroll wheel) +
Button3: Right Mouse Button (if used with the right hand) +
Button4: Scroll Wheel Up +
Button5: Scroll Wheel Down Button6: (I don't know, I thought that was on mouses for gamers) +

The default settings listed below by category can be changed from the CCSM. We indicate the short name of the plugin between square brackets.

. Category General
+
[core] General options, tab "key bindings": +
close_window_key = Alt+F4 +
raise_window_button = Control+Button6 +
lower_window_button = Alt+Button6 +
minimize_window_key = Alt+F9 +
maximize_window_key = Alt+F10 +
unmaximize_window_key = Alt+F5 +
window_menu_key = Alt+space +
window_menu_button = Alt+Button3 +
show_desktop_key = Control+Alt+d +
toggle_window_shaded_key = Control+Alt+s +
+
[matecompat] Mate Compatibility +
main_menu_key = Alt+F1 +
run_key = Alt+F2 +

. Category Accessibility
+
[addhelper] Dim inactive (less light on non focused windows) +
toggle_key = Super+p +
+
[colorfilter] (Filter color for accessibility purposes) +
toggle_window_key = Super+Alt+f +
toggle_screen_key = Super+Alt+d +
switch_filter_key = Super+Alt+s +
+
[ezoom] Enhanced Zoom Desktop +
zoom_in_button = Super+Button4 +
zoom_out_button = Super+Button5 +
zoom_box_button = Super+Button2 (zoom out to go back to normal) +
+
[neg] Negative (toggle inverse colors of the window or screen) +
window_toggle_key = Super+n +
screen_toggle_key = Super+m +
+
[obs] Opacity, Brightness and Saturation adjustments +
opacity_increase_button = Alt+Button4 +
opacity_decrease_button = Alt+Button5 +
+
[showmouse] (Increase visibility of the mouse pointer) +
initiate = Super+k +

. Category Window Management
+
[move] Move window +
initiate_button = Alt+Button1 (hold Button1 while moving the mouse) +
initiate_key = Alt+F7 (Esc to stop moving) +
+
[resize] Resize window +
initiate_button = Alt+Button 2 (hold Button2 while moving the mouse) +
initiate_key = Alt+F8 (Esc to stop moving) +
+
[switcher] Application switcher (switch between windows or panels and
                                 the desktop) +
next_window_key = Alt+Tab (cycle between windows) +
prev_window_key = Shift+Alt+Tab +
next_panel_key = Control+Alt+Tab (cycle between panels and desktop) +
prev_panel_key = Shift+Control+Alt+Tab +

===== Как добавить пользовательскую комбинацию ключей для Mate.

Let's take an example: we want that Alt+F3 starts firefox. введите терминал или команду Run (нажмите Alt+F2):
----
mate-keybinding-свойства
----
В новом окне вы можете использовать клавиши со стрелками вниз и вверх для навигации в списке существующих привязок.

Чтобы установить новую привязку, дважды нажмите Tab для добавления курсора, затем нажмите Enter. В небольшом диалоговом окне введите имя пользовательской привязки клавиш , как firefox, нажмите Tab, введите имя для ассоциированной команды , в этом случае firefox, затем дважды нажмите Tab для поместите курсор на Apply и нажмите Enter.

Чтобы активировать привязку новой клавиши, перейдите до тех пор, пока вы не найдете ее в нижней части списка, предварительно введите нажатие Alt+F3.

В следующий раз вы pres Alt+F3, которые должны запускать firefox

=== Оболочка

NOTE: Настоящая глава представляет собой краткое введение. Более подробная информация представлена в документе https://slint.fr/doc/shell_and_bash_scripts.html[Shell и bash скриптах], в основном заимствованном из SUSE.

When the computer starts in console mode, after having logged in typing your user name and password, the <<shell,shell>> displays a "prompt" like the one below: +
`didier@darkstar:~$` +
In this example:

* `dididier` это имя пользователя
* `темная звезда` имя машины
* tilde `~` представляет домашнюю директорию пользователя, в данном примере `/home/didier`
* знак доллара `$` указывает, что пользователь является "обычным", а не "супер пользователем" (см. ниже).

Затем курсор позиционируется после подсказки.

Теперь пользователь может ввести в строке команду (отсюда и название "командной строки") и подтвердить ее нажатием клавиши Enter. Оболочка then analyzes the command and execute it if valid, else output a message like for instance "command not found". Вы можете отредактировать команду перед нажатием клавиши Enter с помощью стрелок влево и вправо и клавиш Backspace, Home, End и Del.

Во время выполнения команды могут отображать вывод на экране или нет. Во всех случаях после выполнения запроса будет отображено снова в новой строке , что shell ждет ввода следующей команды.

Для этого пользователю необходимо знать, какие команды доступны и их синтаксис. Некоторые команды выполняются самой оболочкой, другие запускают внешние программы. Ниже приведено несколько примеров команд, больше перечислены в https://slint.fr/doc/shell_and_bash_scripts.html[Shell и bash скриптах]

Для Linux доступно несколько оболочек; в Slint оболочке, используемой по умолчанию, называется *bash*.

Чтобы позволить запускать несколько программ одновременно, Linux предоставляет несколько "виртуальных консолей", а затем одну и ту же клавиатуру и экран, нумерованные с одного. Первоначально система запускается в консоли (или виртуальном терминале) номер 1 также называется *tty1* (название tty является аббревиатура "teletype"). Оттуда пользователь может переключиться на другую консоль или tty; например переключиться на Tty number 2, нажав Alt+F2, где другая оболочка снова попросит пользователя'с именем пользователя и паролем. Чтобы вернуться в tty1, просто нажмите Alt+F1. По умолчанию в Slint доступны шесть тонов, но это может быть изменено при редактировании файла /etc/inittab.

When the shell is used in a graphical environment (in a graphical terminal), its behaves the same way but the prompt is slightly different, as illustrated below: +
`didier[~]$` +

Вы можете переключаться между консолью и графическим окружением:

* Из графического окружения нажмите кнопку Ctrl+Alt+F3, чтобы перейти в tty3. В первый раз вам придется ввести свой логин и пароль.
* С консоли или tty нажатием Alt+F7, если графическая среда уже запущена, иначе введите `startx` , чтобы запустить ее.

==== Набрав команды как root

*root* is the conventional name of the "super user" which have all rights to do administrative tasks, including those that could harm or even destroy the system.

You can (but this is not recommended for beginners) log in directly as root. To do this type *root* as user, then root's password. To inform you (and warn you about the associated risks and responsibilities), the prompt will look like this: +
*root@darkstar:s~#* +
the character # (number sign, also commonly named hash) indicates that the commands will be typed as root (not as regular user), with the associated rights, but also risks and responsibilities.

If you are already logged as regular user, you can "become root" typing: +
*su -* +
then pressing Enter. In this command, `su` (which stands for "Super User") is the name of the command, and the character *-* (hyphen-minus, also named minus) tells that you are opening a "login shell": you will first be asked root's password, then be directed to its home directory /home/root as if you had logged in as root at startup. This will avoid that you inadvertently write files in your home directory as regular user (/home/didier in the example) which cause issues later.

The regular user registered during installation and other users members of the 'wheel' group can also type commands reserved to root preceding the name of the command by 'sudo' like this for instance: +
*sudo update-grub*

=== Как решить блокирующие задачи

Под "блокированием вопросов" мы понимаем "проблему, которая не позволяет использовать Slint", как то:

* Не удалось загрузить систему.
* Система загружается, но последовательность запуска прерывается перед завершением. Это может произойти, например, если корневой раздел может't смонтирован из-за ошибки в /etc/fstab, поврежденная корневая файловая система или отсутствующий модуль ядра для монтирования корневого раздела, или система успешно загружается, но вы don't помните пароль для root.

Если система полностью не сможет загрузиться, попробуйте каждое из нижеперечисленных решений последовательно до тех пор, пока не будет работать.

. Если это происходит после обновления ядра, попробуйте вторую загрузку вместо первой.
. Попробуйте загрузиться с спасательной загрузочной карты, которую вы запросили в конце установки.
. Перейдите к крестоносцу для его ремонта, как описано ниже.

You can always get help emailing slint@freelists.org providing all information that could help investigate the issue. If not already done, first subscribe to the list emailing slint-request@freelists.org with the subject 'subscribe', then answer the email you will receive. Only if you have an issue using email, request help in the IRC channel #slint, server irc.libera.chat and stay in the channel until someones answer.

We will now explain how to jump into Slint to repair it.

<<Start_the_installer,Start the installer and identify Slint's root partition>> +
<<Issue_the_needed_commands,Issue the needed commands to jump into Slint>>. +
<<Repair_Slint,Repair Slint from Slint.>>

[[Start_the_installer]]
==== Start the installer and identify Slint's root partition

If the start-up up sequence is interrupted, jump into Slint from its installer to try to solve the issue. Insert or plug-in the installation media (USB stick or DVD where you have written the installation ISO) then follow the instructions below.

. Запустить установщик.
. Как только вы вошли в систему как root, для списка дисков и разделов, наберите следующее:
+
----
lsblk -lpo name,size,fstype
----
. Найдите в выходе имя корневого раздела Slint, проверьте его размер и тип файловой системы, помеченные FSTYPE.
. Mount this partition
+
----
mount /dev/sda3 /mnt
----
+
[NOTE]
====
If Slint's root file system is btrfs (as indicated by the output of "lsblk") you need to mount it using the options mentioned in its /etc/fstab.

In this case you need to use the same options as in Slint on btrfs, so type instead:
----
mount /dev/sda3 /mnt -o subvol=/@,compress=zstd:3
----
====
. Check that the partition be the right one. For instance if it is /dev/sda3, type:
+
----
cat /etc/mnt/etc/slint-version
----
+
Assuming that you installed Slint64-15.0 the output should be: *Slint 15.0*
+
Если вывод "file not найден", то раздел не является тем разделом, который вы искали. Только в этом случае набери:
+
----
umount /mnt
----
+
а затем попробуйте еще один, перейдя обратно к списку дисков и разделов.

[[Issue_the_needed_commands]]
==== Issue the needed commands to jump into Slint

. mount the file systems /proc /sys and /dev typing:
+
----
монтировать -B /dev /mnt/dev
монтировать -B /proc /mnt/proc
монтировать -B /dev /mnt/sys
----
+
. Issue the next commands to "jump into" your Slint and mount all devices mentioned in its /etc/fstab:
+
----
chroot /mnt
mount -a
----

[[Repair_Slint]]
==== Repair Slint from Slint

From Slint you can modify the system to solve the issue. Here are some examples:

* Run "update-grub". +
* Run "grub-emu" or "list_boot_entries" +
* Re-install GRUB using the command "grub-install drivename", drivename being the drive where to install Slint. +
* Type "passwd" to change the password for root. +
* Удалять, установить или обновить пакеты.

. После завершения удалите установочный носитель, затем тип:
+
----
выйти из
перезагрузки
----

[[Accessibility]]
== Accessibility

Если вы решили сохранить речь при первой установке, он будет включен с запуска в консоли, как в графических средах.

=== Использование Slint с терминалом Брайля

Slint включает в себя программное обеспечение brltty для работы с дисплеями Брайля.

Ваши настройки, сделанные перед загрузкой в командной строке или позже, записываются в установленную систему в /etc/brltty.conf.

Полное руководство по бритве доступно на английском языке, Французский и португальский в нескольких форматах, включая простой текст (txt) по этому URL: https://mielke.cc/brltty/doc/Manual-BRLTTY/

Если Брайль не был включен во время установки или был отключен, для его включения:

. Сделайте /etc/rc.d/rc.brltty исполняемым типом как root:
+
----
chmod 755 /etc/rc.d/rc.brltty
----
. Сделайте себя членом группы Брайля, набрав в качестве root:
+
----
usermod -G braille -a имя пользователя
----
+
В команде выше замените имя пользователя с логином.

Чтобы отключить тип Брайля как root:
----
chmod 644 /etc/rc.d/rc.brltty
----

=== Речь в графических средах

Для напоминания в графических средах с помощью экранного чтения Orca включена печатание:
----
орка
----

Чтобы узнать, как использовать Orca, включая специфические ключевые ссылки, наберите:
----
мужчина орка
----

In short, in a graphical environment:
----
Insert+Space: display the Orca Preferences dialog.
Insert+S: activate or deactivate the vocal synthesis.
Insert+H: activate the learning mode. In this mode:
   Press a key to hear its function
   F1: to hear the documentation of the screen reader
   F2: list the keyboard shortcuts for Orca
   F3: list the keyboard for the current application
   Esc: end of the learning mode
----

=== Voices and TTS in Slint

Following TTS (Text to Speech synthesizers) are shipped in Slint64-15.0, each with a set of voices, namely: +
espeak-ng +
flite +
pico +
mbrola +
RHVoice +

Чаще всего эти TTS и связанные с ними голоса и языки управляются голосовым диспетчером через его так называемые "модули" (резко, резко, модуль связан с TTS).

The custom utility spd-list can answer several questions about the available synthesizers, voices and languages. Typing spd-list displays this:
----
В этом скрипте перечислены языки и синтезаторы, доступные для приложений
на основе диспетчера речи, например, Orca или речи. Каждая команда ниже отвечает на следующий за ней вопрос.
Не вводите кавычки вокруг команды.
Использование "/usr/bin/spd-list"?
"/usr/bin/spd-list -s" доступны синтезаторы?
"/usr/bin/spd-list -l" доступны языковые коды?
"/usr/bin/spd-list -ls <synthesizer>" доступны для этого синтезатора?
"/usr/bin/spd-list -sl <language code>" синтезаторы, предоставляющие голоса на этом языке?
Код языка чаще всего содержит два символа, такие как 'ru' или 'fr'
----
Все перечисленные голоса доступны в Orca и речи, а также fenrir если настроен на использование рече-диспетчера.

Вы можете получить дополнительные голоса за flite и mbrola, связанные с модулями flite-generic и espeak-ng-mbrola-generic.

Вы всегда можете знать, какие из этих команд установлены или не набраны как root-файлы:
----
slapt-get --search mbrola-voice
slapt-get --search flite-voice
----
затем установите один из неустановленных например один из них, как напр.
----
slapt-get -i mbrola-voice-it2
----
In addition to the free (as in free beer) voices shipped in Slint, you can buy voices for: +
voxin, https://oralux.org/voice.php +
voxygen, sending an email to contact@hypra.fr

More voices and synthesizers could be made available later, this will be announced on the Slint mailing list and this http://slackware.uk/slint/x86_64/slint-15.0/ChangeLog.txt[ChangeLog]

Горячие клавиши для графических окружений перечислены в <<key_bindings, сочетаниях клавиш>>.

=== Use the lightdm login manager with speech

В lightdm нажатие F4 переключает звук вкл. или выкл. Изначально курсор находится в поле пароля. Нажмите Tab приводит к "login push кнопку", а затем пользователю'S список или "combo box". В этом списке нажатие на пробел показывает текущего выбранного пользователя. Используйте клавиши со стрелками для выбора другого и введите соответствующий пароль. Вместо этого, выбрав "Другое..." добавляет поле, где вы можете ввести имя входа пользователя без списка. Еще в lightdm, F10 вызовет меню, позволяющее перезагрузить или выключить, и Alt+F4 вызывает пользовательский интерфейс с кнопками выключения или отмены.

=== Выберите консольный считыватель экрана

Slint provides these console screen readers: +
espeakup +
speehchd-up +
fenrir

Кроме того, в консольном режиме можно использовать несколько аппаратных синтезаторов речи.

Для выбора программы чтения с экрана выполните эту команду:
----
говорить с
----
Вот его вывод без аргументов:
----
root[~]# speak-with
Usage: /usr/sbin/speak-with <screen reader> or <hard synthesizer> or none
Choose a console screen reader to talk with among:
  espeakup (Console screen reader connecting espeak-ng and speakup)
  fenrir (Modular, flexible and fast console screen reader)
  speechd-up (Console screen reader connecting Speech Dispatcher and speakup)
or use one of the supported hard synthesizers:
  acntsa apollo audptr bns dectlk decext ltlk soft spkout txprt
or type "/usr/sbin/speak-with none" to mute all screen readers.
root[~]#
----
Список аппаратных синтезаторов речи доступен в запущенном ядре или поставляемом в виде модулей.

Пример команд и связанных с ними выводов:

----
root[~]# громкоговоритель
Стартовое выступление
Должно быть также запущено при следующей загрузке? [Y/n]
ОК
корень[~]# Готово.
----
As soon as you type the command, the previously used screen reader will be stopped and speechd-up will begin talking.

If you answer Y (the default) to the question: +
Should speechd-up be also started at next boot? +
spechd-up will continue to be used at next boot. +
If instead you answer n the screen reader used before typing speak-with speechd-up will be used after next boot.

Другие примеры:

----
root[~]# громко с аполисом
Остановка речи...
Следует ли использовать apollo при следующей загрузке? [Y/n]
ОК
корень[~]# Готово.

root[~]# не говорит ни с кем
Хотите заглушить консоль при следующей загрузке? [Y/n]
OK
root[~]#
----

=== Настроить консольный считыватель экранов.

Аппаратные синтезаторы речи, использующие озвучивание и воспроизведение , а также чтение речи на экране воспроизведения.

Вы можете сохранить параметры, например, увеличить частоту пика или громкость звука или уменьшить частоту звука. Просто введите как root: громкости-сохранить. Это сохраняет все текущие настройки, в том числе настройки , используемого аппаратного синтезатора.

Все эти настройки будут восстановлены при следующей загрузке: скрипты запуска rc.espeakup и rc.speechd-up запустить команду Speup-restore для вас.

If you don't to want to restore the saved settings, type as root: +
chmod -x /usr/sbin/speakup-restore

If you want to have them restored again type as root: +
chmod +x /usr/sbin/speakup-restore

Вот некоторые сочетания клавиш для настройки произношения, а также речь:
----
spk_f9   punctuation_level_decrease
spk_f10  punctuation_level_increase
spk_f11  reading_punctuation_decrease
spk_f12  reading_punctuation_increase
spk_1    volume_decrease (doesn't work with speechd-up)
spk_2    volume_increase (doesn't work with speechd-up)
spk_3    pitch_decrease (doesn't work with speechd-up)
spk_4    pitch_increase (doesn't work with speechd-up)
spk_5    rate_decrease
spk_6    rate_increase
----
В таблице выше spk это клавиша CapLock, или Ins/0 на числовой клавише. Например, чтобы увеличить скорость, вы можете нажать и удерживать клавишу CapsLock, а затем нажмите клавишу 6.

Некоторые настройки доступны только на конкретных аппаратных синтезаторах не имеют привязки к ним. Затем установите новое значение в /sys/accessibility/speakup/<synth>/<parameter>

For instance to change the voice in use by an apollo 2 you could write: +
echo 2 > /sys/accessibility/speakup/apollo/voice

Speup-save также сохранит эту настройку.

Caveat: I never used a hardware speech synthesizer, so the explanation below is only an assumption based in the speakup_apollo driver, consistent with this manual, found in: +
https://archive.org/stream/DolphinApollo2Manual/Dolphin_Apollo_2_Manual_djvu.txt

[[desktop_keys]]
==== Выражение клавиш рабочего стола

Почти все перечисленные ниже ключи находятся на числовой клавиатуре. Клавиша Вставить или 0 на клавиатуре действует как клавиша Shift (Shift клавиши). Например, Ins 2 означает, что "удерживайте клавишу Вставки, как клавиша Shift и нажмите 2". Оставьте numlock выключенным, чтобы использовать Speakup.

Scope: these key bindings can be used with hard synthesizers and with espeakup, and also with speechd-up.

Первые ключи для запоминания:
----
Вкл/выкл кнопки "Вкл/выкл" экрана печати
Ins F1 Help (нажмите "Пробел", чтобы выйти из справки)
----

Ключи, используемые для просмотра экрана:
----
1/2/3          Say Previous/Current/Next character
Shift PageUp   Say first character
Shift PageDown Say last character
4/5/6          Say Previous/Current/Next word
5 twice        Spell current word
Ins 5          Spell Current Word phonetically
7/8/9          Say Previous/Current/Next line
Ins 4          Say from left edge of line to reading cursor
Ins 6          Say from reading cursor to right edge of line
Ins 8          Say from top of screen to reading cursor
Ins plus       Say from reading cursor line to bottom of screen
plus           Say entire screen.
Ins r          Say all document
dot            Say position
Ins dot        Say attributes
Ins minus      Say character hex and decimal value.
minus          Park reading cursor (toggle)
Ins 9          Move reading cursor to top of screen (insert pgup)
Ins 3          Move reading cursor to bottom of screen (insert pgdn)
Ins 7          Move reading cursor to left edge of screen (insert home)
Ins 1          Move reading cursor to right edge of screen (insert end)
Control 1      Move reading cursor to last character on current line.
asterisk       Toggle cursoring
Ins asterisk   n<x|y go to line (y) or column (x). Where 'n' is any
               allowed value for the row or column for your current screen.
Ins f2         Set window
Ins f3         Clear window
Ins f4         Enable window
----

Другие ключи:
----
Ins f5 Edit some
Ins f6 Edit most
Ins f7 Edit delim
Ins f8 Edit repeat
Ins f9 Edit exnum

Enter Shut up (until another key is hit) and sync reading cursor.
Ins Enter Shut Up (до переключения назад)

slash Mark and Cut screen region.
Регион экрана для слэш-вставки в любую консоль.
----
==== Вызов кнопок ноутбука

Эти сочетания клавиш (для американской клавиатуры) don't требуют числового типа. Если у вас есть, используйте клавиши <<desktop_keys, для рабочего стола>> легче в использовании, особенно если вы используете другую раскладку клавиатуры, чем США.

The CapsLock key acts like a Shift key. +
For instance, CapsLock 2 means "hold down the CapsLock key like a shift key and press 2". +
Keep numlock off to use Speakup.

Scope: these key bindings can be used with hard synthesizers and with espeakup, and also with speechd-up.

Первые ключи для запоминания:
----
Переключение экрана при вкл/выкл
CapsLock F1 Help (нажмите пробел для выхода)
----

Ключ, используемый для просмотра экрана:
----
CapsLock m/comma/dot Say Previous/Current/Next character
CapsLock PageUp      Say First character
CpasLock PageDown    Say Last character
CapsLock j/k/l       Say Previous/Current/Next word
CpasLock k twice     Spell current word
CapsLock u/i/o       Say Previous/Current/Next line
CapsLock h           Say from left edge of line to reading cursor.
CapsLock semicolon   Say from reading cursor to right edge of line
CapsLock y           Say from top of screen to reading cursor
CapsLock p           Say from reading cursor line to bottom of screen
CapsLock apostrophe  Say entire screen.
Capslock r           Read all document
CapsLock n           Say position
CapsLock slash       Say attributes
CapsLock minus       park reading cursor (toggle)
CapsLock f2          Set window
CapsLock f3          Clear window
CapsLock f4          Enable window
----
Другие ключи:
----
CapsLock f5 Редактировать некоторые
CapsLock f6 Изменить максимум
CapsLock f7 Редактировать разделитель
CapsLock f8 Repeat редактировать
смещение CapsLock f9 Edit exnum
----

=== Позволить эмакам

Вы можете использовать произношение или речь. Чтобы включить или выключить один из ввести одну из этих команд:

switch-on emacspeak +
switch-on speechd-el +
switch-off emacspeak +
switch-off speechd-el +

Then just type: +
emacs

Включение одного из этих программ отключает другой.

[[Manage_your_system]]
== Manage your system

[[software_management]]
=== Управление программным обеспечением в Slint.

<<The_basics,The basics>> +
<<Keep_your_system_up_to_date,Keep your system up to date>> +
<<Kernel_upgrades,Kernel upgrades>> +
<<Get_additional_applications,Get additional applications>> +
<<slapt_src,Usage of slapt-src>>

[[The_basics]]
==== Основы

В Slint программное обеспечение предоставляется в виде пакетов. Пакет - это набор файлов из сжатого архива, собранных вместе, чтобы обеспечить все, что необходимо для запуска программы. Пакеты включены в установочный ISO и хранятся в удаленных серверах, с которых они могут быть загружены и установлены. Установка пакета означает извлечь файлы из архива и скопировать их в директорию системы.

Установка и удаление программного обеспечения записываются в базу данных, состоящую из текстовых файлов в этих каталогах:
----
/var/lib/pkgtools/packages
/var/log/removed_packages
/var/lib/pkgtools/scripts
/var/log/removed_scripts
----
The files in /var/lib/pkgtools/packages record information about the packages, mainly their content: the list of files they include and where they are installed.

Ниже перечислены основные команды для управления пакетами. Все они имеют связанные страницы справки.

Эти команды требуют административных прав, связанных с конкретной учетной записью под названием 'root', для которой вы указали пароль при установке Slint.

To issue a command as 'root', first type su - then enter the password for root and type the command.+ or use sudo.

Ниже приведенные команды могут быть запущены с графического терминала или в консоли, но gslapt работает только в графической среде.
----
installpkg # для установки пакета, хранимого локально.
removepkg # для удаления установленного пакета.
upgradepkg # для замены установленного пакета другим (обычно с тем же именем, но с другой версией).
slapt-get # для установки, удаления, обновления пакетов, хранящихся в репозиториях, перечисленных в /etc/slapt-get/slap-getrc
----
Отправленные в установке пакеты из репозиториев, перечисленных в /etc/slapt-get/slapt-getrc

Прочитайте комментарии в /etc/slapt-get/slapt-getrc и /usr/doc/slapt-get-0.10.2t/README.slapgetrc.Slint в установленной системе.

После установки Slint, вы'будете уведомлены об обновлениях установленных пакетов из репозиториев, перечисленных в /etc/slapt-get/slapt-getrc

Вы можете установить дополнительные пакеты, используя команду slapt-get или gslapt, если они хранятся в репозитории в /etc/slapt-get/slapt-getrc

slapt-get и gslapt предоставляют функцию поиска, которая помогает вам найти пакеты.

WARNING: вы можете использовать slapt-get, gslapt и removepkg для удаления установленных пакетов, но не удалять пакеты, отправленные в Slint ISO, даже если вы не используете их вообще. Удаление включенного пакета не приведет к увеличению производительности и может предотвратить запуск других приложений. Также, если вы добавили пакет, не входящий в состав Slint, вы можете удалить его, но будьте осторожны, что удаленный пакет не является зависимым от других установленных вами пакетов и будет продолжать использовать.

[[Keep_your_system_up_to_date]]
==== Держите вашу систему в актуальном состоянии

Держите вашу систему в безопасности устанавливать обновления программного обеспечения, предоставляемые Slint, как только они'будут доступны.

All updates are listed in the ChangeLog: http://slackware.uk/slint/x86_64/slint-15.0/ChangeLog.txt

После установки Slint или любых изменений в файле /etc/slapt-get/slapt-getr запустите эту команду один раз:
----
slapt-get --add-keys
----

Чтобы синхронизировать локальный список доступных пакетов с репозиторием, эта команда автоматически запускается каждые два часа:
----
slapt-get -u
----
You can also run it manually.

Это, конечно, требует подключения машины к Интернету.

Чтобы загрузить и установить обновленные или пересобранные пакеты запустите с правами root следующую команду:
----
шлак-получить --upgrade
----
Кроме того, вы можете использовать gslapt, графический интерфейс для slapt-get.

Чтобы получить новые пакеты, перечисленные в Журнале изменений как "Добавленные", наберите:
----
slapt-get -i <package name>
----
или убедиться, что вы установили все пакеты, отправленные в Slint, включая те, которые добавлены в репозиторий после установки Slint, наберите:
----
slapt-get --install-set slint
----

На настольных компьютерах небольшая иконка отображается в области уведомлений панели (верхней панели в MATE) для уведомления о доступных обновлениях программного обеспечения. Просто щелкните левой кнопкой мыши и следуйте инструкциям, указанным там.

Имейте в виду, что некоторые пакеты перечислены в черном списке /etc/slapt-get/slapt-getrc, то есть не могут быть автоматически обновлены или установлены.

[[Kernel_upgrades]]
==== Обновление ядра

При необходимости предоставляются новые ядра либо для исправления требований безопасности, либо для улучшений.

Как правило, при возникновении такой ситуации ручное вмешательство пользователя не требуется, но может быть полезно знать, как осуществляется обновление ядра и что делать, если произойдет что-то неожиданное.

Несколько пакетов включают файлы, связанные с каждым ядром, а именно: kernel-generic, kernel-modules, kernel-source, kernel-headers. kernel-source и kernel-headers включают файлы, используемые при сборке программ, для запуска системы Slint необходимы только kernel-generic и kernel-headers.

Файлы kernel-модулей поставляются с помощью модулей, , которые являются частями кода, которые "подключены" ядро, чтобы предоставить определенную функцию или справиться с определенным оборудованием.

Как только установлен пакет с ядром и соответствующий пакет с модулями ядра, скрипт /sbin/wrapupgradepkg собирает <<initrd, initrd>> связанный с этим ядром (с модулями, взятыми из пакета kernel-modules) и устанавливает его вместе с ядром в каталог /boot.

Затем удаляются предыдущие ядра (не используемые при обновлении).

Then the script updates the GRUB configuration file /boot/grub/grub.cfg, read by the OS loader to build the boot menu.

Это загрузочное меню включает как минимум два элемента загрузки, указывающие ядро и связанный с ним initrd. Сверху:

* Запуск Slint с использованием только что установленного ядра загрузочного элемента.
* Запуск Slint с использованием ядра, используемого во время обновления.

Это обеспечивает тип "безопасной сети" на случай, если Slint не должен't загрузки с новым ядром: в этом случае просто стрелка вниз после того, как отображается меню загрузки для запуска Slint с предыдущим ядром

Вы можете просмотреть новое загрузочное меню перед перезагрузкой, набрав его как root:
----
grub-emu
----
Then an emulated or "fake" boot menu is displayed, with the same layout as the real one which will displayed at next boot.

Вы можете перемещаться в ней с помощью клавиш со стрелками вниз и вверх, чтобы выделить (поставить фокус) загрузочную запись, в которой вы можете отобразить подробности нажатия 'e'. Вы можете вернуться в меню, нажав Escape.

Чтобы выйти из grub-emu нажмите c, затем *exit* и нажмите Enter.

Alternatively you can type as root:
----
list_boot_entries
----

[[Get_additional_applications]]
==== Получить дополнительные приложения

The easiest and recommended way to get additional applications not shipped in Slint is to use slapt-get or its graphical front-end gslapt. This gives you access to all packages in repositories enabled in /etc/slapt-get/slapt-getrc by default in addition to the Slint repository: +

* The Slackware repository, with dependency information: SOURCE=https://slackware.uk/salix/x86_64/slackware-15.0/:OFFICIAL
* The Salix extra repository, fed for Salix distribution by its maintainer George Vlahavas aka gapan but usable in Slint as well: SOURCE=https://slackware.uk/salix/x86_64/extra-15.0/:OFFICIAL

Если приложение, которое вы хотите, не установлено и не доступно в одном из репозиториев, включенных в /etc/slapt-get/slapt-getrc, вы можете сделать для него пакет, использование материалов от волонтеров @ https://slackbuilds.org. Чтобы узнать, как продолжить, прочитайте https://slackbuilds.org/howto/ и https://slackbuilds.org/faq/

Пакеты, собранные таким образом, должны быть совместимы с Slint.

The application *slapt-src* and its graphical front-end *sourcery* allows you to build and install packages using the build material provided at https://slackbuilds.org, to be used as root or using sudo.

Подробнее мы опишем slapt-src .

[NOTE]
====
Pre-built packages for most applications that can be built with slap-src or sourcery are available in the Salix extra repository. Preferably install these pre-built packages using slapt-get or gslapt, unless you need specific build options or a different version than the one provided.
====

[[slapt_src]]
===== Использование slapt-srcrc

The default configuration script for slapt-src is /etc/slapt-get/slap-srcrc and has this content:
----
BUILDDIR=/var/lib/slapt-src
PKGEXT=txz
SOURCE=https://slackbuilds.org/slackbuilds/15.0/
----
Итак:

* All build material and packages will go in /var/lib/slapt-src
* Названия пакетов заканчиваются .txz
* The build material is fetched from the repository https://slackbuilds.org/slackbuilds/15.0/

Вот вывод команды *slapt-src --help*:
----
Используйте: slapt-src [option(s)] [action] [slackbuild(s)]
  -u, --update обновить локальный кэш удаленных сборок слайдов
  -U, --upgrade-все обновить все установленные сборочные сборки
  -l, --list доступные сборки со слайдами
  -e, --clean очистить каталог сборки
  -с, --search в доступных slackbuild'ах
  -w, --show specified slackbuild
  -i, --установить выборку, построить и установить указанную сборку(и) slackbuild(s)
  -b, --build только получить и построить указанную сборку(и) со шлаком
  -f, --fetch только получить указанную сборку(и) слаксбол(ов)
  -v, --version
  -h, --help
 Опции:
  -y, --Да не запрашивать
  -т, --simulate показывать что будет сделано
  -c, --config=ФАЙЛ использовать указанный файл конфигурации
  -n, --no-dep не искать зависимости
  -p, --postprocess=CMD запускает указанную команду в сгенерированном пакете
  -B, --build-only применимо только к --upgrade-all
  -F, --fetch-only применимо только к --upgrade-all
----

Позвольте'комментировать некоторые из этих опций:

* Используйте -u или --update каждый раз, чтобы обновить список пакетов, которые можно собрать и установить. Эта команда записывает файл /tmp/slapt-src/slackbuilds_data, заменяя предыдущий регистр.
* Use -e to save space on disk, removing most files in /tmp/slapt-src/
* do *not* use -U except to list the possible upgrades or downgrades, without confirming: confirming would lead to replace all Slint packages by one at another version if available in the remote repository, possibly breaking software not compatible with this other version.
* -i также может обновить пакет, уже установленный с https://slackbuilds.org, если сопровождающий сценария SlackBuild обновил его, изменив переменную VERSION.
* Используйте -f для загрузки файлов только в https://slackbuilds.org для целевой программы. Это может быть полезно, если вы хотите проверить материал для сборки или настроить сборку. Например, пусть'с предполагают, что вы хотите получить строительный материал для программного обеспечения *mxml*. Команда ниже дает некоторую информацию о программном обеспечении и какие файлы хранятся в https://slackbuilds.org для него:
+
----
slapt-src --show mxml
Название SlackBuild : mxml
SlackBuild Version: 3.
SlackBuild Категория: библиотеки/mxml/
SlackBuild Описание: mxml (библиотека парсинга)
SlackBuild файлы:
 README
 mxml. lackBuild
 mxml.info
 slack-desc
----
+
Загрузите эти файлы, а также архив исходных текстов из исходного репозитория со следующей командой:
+
----
slapt-get -f mxml
----
+
зная из вывода предыдущей команды о том, что файлы хранятся в подкаталогах/mxml, вы можете проверить, какие файлы были загружены с помощью этой команды:
+
----
ls -1 /var/lib/slapt-src/libraries/mxml
mxml-3.1.tar.gz
mxml.SlackBuild
mxml.info
slack-desc
----
* Используйте -b, если вы хотите построить пакет, но не установите его. В приведенном выше примере он будет сохранен в /tmp/slapt-src/libraries/mxml, так что вы сможете установить его после нажатия:
+
----
upgradepkg --install-new /tmp/slapt-src/libraries/mxml/xml*txz
----
+
* Используйте -c, если вы хотите использовать пользовательский файл конфигурации вместо стандартного файла /etc/slapt-get/slap-getrc

=== Управление пользователями и группами.

Для управления пользователями и группами предоставляются две команды:

* Команда _usersetup_ (TUI)
* Команда _gtkusersetup_ (GUI), с иконкой в Системной категории Slint)

Эти команды позволяют добавлять или удалять пользователей и группы пользователей и добавлять пользователей в группы.

Имейте в виду, что каждая учетная запись по умолчанию связана с ее областью в каталоге /home . Например, если вы добавите пользователя *leonie*, будет создана папка /home/leonie, к которым только этот пользователь (и root) будет иметь доступ.

=== Изменить язык системы по умолчанию

Две команды предусматривают следующее:

* Команда _localesetup_ (TUI).
* Команда _gtklocalesetup_ (GUI), с иконкой в группе Slint Control Center.

Имейте в виду, что эти параметры изменяют язык, используемый интерфейсами приложений, если они интернационализированы, а не раскладку клавиатуры (см. ниже).

Также, локализованные пакеты (если имеются), соответствующие выбранному языку, уже установлены в конце установки Slint. Если позже вы измените язык по умолчанию, то вам нужно будет установить соответствующие локализованные пакеты, если хотите.

Локализованные означает «предоставляемые в данном месте», локаль является языком плюс особенности, связанные с географическим районом. Например, на португальском языке в Португалии и Бразилии разные. В локализованных именах пакетов l10n это аббревиатура "локализация", означающая "буква l, 10 других букв, буква n".

Локализованные пакеты включены для многих языков. Их имя включает в себя имя базового пакета, дефис, затем код языка. Ниже перечислены базовые имена локализованных пакетов:
[options="autowidth"]
|====
| Base package name | Description
| aspell | word lists for spell check
| libreoffice-l0n | localized LibreOffice office suite
| libreoffice-help | localized help for LibreOffice
|====

To find a localized package, type in a terminal emulator as root (example for libreoffice-l10n): +
`spi libreoffice-l10n`

This will display the list of all localized LibreOffice package. Find the one you want and install it. For instance for Persian the language code is `fa` (short for Farsi), so to install it type: +
`spi -i libreoffice-l0n-fa`

Если вы предпочитаете, вы можете использовать `gslapt`. Затем введите имя пакета в поле поиска для отображения всех локализованных пакетов libreOffice.

=== Изменить клавиатуру

Вы можете изменить раскладку по умолчанию, используемую в графическом режиме с помощью:

* Команда _настройки клавиатуры_ (TUI)
* Команда _gtkkeyboardsetup_ (GUI), с иконкой в Центре управления Slint Center, категории фурнитура.

Эти команды также позволяют выбирать, следует ли включать numlock при запуске системы, и если SCIM (метод ввода) должен быть включен при загрузке системы.

If you use a window manager with a panel, you can also make this setting through a right click on the keyboard applet (displayed by default as the two letters language code of the keyboard map in use).

On the command line but still for the graphical mode use instead the command `setxbmap`

For instance to set the keyboard layout to Ukrainian in graphical mode, just type as regular user: +
`setxkbmap -layout ua`

Чтобы узнать больше, прочтите страницу man для setxkbmap.

=== Установить принтер

В Slint CUPS сервер печати управляет задачами печати и принтеров. В конфигурации по умолчанию, записанная в файле /etc/cups/cupsd. если только пользователям, принадлежащим к `sys` (короткий для _системы_) группе разрешено выполнять административные задачи, как добавление или удаление принтера.

For a simple setup (printer attached to a desktop or laptop and not shared between machines), you just need to add one user (who will manage the printers) to the `sys` group. For instance adding the user didier_to the group `sys` can be done two ways:

* In console mode or using a terminal emulator, become root with `su -` then type:
+
`gpasswd --add didier sys`
+
* В графическом режиме из центра управления слепой щелкните на Пользователи и Группы (категория Система), выберите пользователя и нажмите Свойства, затем на вкладке Группы отметьте `sys`. Или другой раунд линии (выберите группу, затем добавьте пользователя в нее).

Есть несколько способов добавления и настройки принтера (это должно быть сделано пользователем из группы `sys`):

* Нажмите кнопку Настроить принтер из центра управления слепом, чтобы отобразить графический интерфейс, позволяющий простую установку...
* ... Или нажмите на Cups Print Control the display web interface to the CUPS server. Вы также можете отобразить веб-интерфейс на сервере CUPS набрав `localhost:631` в поле адреса веб-браузера.
* Если у вас устройство Hewlett Packard, щелкните правой кнопкой мыши на логотипе *hp* в области уведомлений панели.

NOTE: Чтобы выполнить любой параметр печати, сервер CUPS должен быть запущен. Запускается при запуске Slint, если сервис `чашки` проверены системными службами (проверено по умолчанию в Slint).

=== Настройка звука

В Slint приложения либо посылают звуковой сигнал ALSA или PulseAudio.

В последнем случае PulseAudio в свою очередь посылает выходной поток на микшер ALSA, который направляет его на звуковые карты.

Как следствие, установка как громкости выходного звука всегда может выполняться микшером ALSA, , а также микшером PulseAudio , но только в том случае, если приложение посылает звуковой сигнал в PulseAudio.

We will present now applications that can be used to modify the sound settings

==== pavucontrol (для PulseAudio)

`pavucontrol` означает управление громкостью PulseAudio и графическое приложение. Вы можете запустить его из меню терминала или приложения, или щелкните правой кнопкой мыши значок звукового микшера на верхней панели Mate. На самом деле он позволяет больше параметров, чем просто управление громкостью, потратьте время на изучение всех его функций.

Вы также можете использовать апплет управления громкостью в области уведомлений панели: щелчок левой кнопкой мыши позволяет настроить громкость, Щелчок правой кнопкой мыши дает доступ к другим настройкам и позволяет запускать микшер павильона.

[[Sound_on_the_command_line]]

==== alsamixer (for ALSA)

alsamixer — приложение для ncurses, обеспечивающее полуграфический пользовательский интерфейс.

To use it type in a console or in a graphical terminal:
----
alsamixer
----
затем:

* Используйте клавишу вверх для увеличения громкости на 5%
* Используйте клавишу вниз, чтобы уменьшить громкость на 5%
* нажмите Esc для выхода из приложения.

==== amixer (для ALSA)
Эта команда имеет форму:
----
amixer <arguments>
----
Например, для установки главного громкости на 70% тип:
----
amixer sset Master 70%
----
Чтобы узнать больше, введите одну из следующих команд:
----
amixer man
amixer -h
----
==== Сэм (смеситель с дружественным отношением к речи)
sam allows selection of the sound card to work on when there are more than one such device in your machine. +
When there is only one, it directly presents the different mixers for configuration.

Все выделения, будь то звуковые карты, Микширы или данная особенность
 конкретного микшера выбираются прокруткой доступных параметров с помощью стрелок вверх и вниз, затем введите желаемый один: +
`q` оставить список выбора и/или quits. +
`Shift-q` выходит из программы отовсюду. +
`F1` Отображает любую дополнительную информацию, если таковая имеется.

When the name of the desired option is known, one can instead press its first letter. First-letter navigation is case-insensitive. That will then take you to the first selection starting with the pressed letter. Pressing the same letter again, will move you to the next option starting with that letter if more than one option like that exists. Repeating the letter will cycle among all those options starting with that letter.

The settable features of a mixer can be listed pressing F1. +
They are presented as a selection list, showing briefly all relevant information, e.g. "playback volume down from 84 percent" is the option to lower the playback volume setting. As you can see, it also tells you what the current setting is.

NOTE: sam не работает корректно в графическом терминале. Используйте его в консоли.

==== pamixer и ponymix (для PulseAudio)
These utilities are similar, with commands in this form:
----
pamixer <arguments>
ponymix <arguments>
----
Например, для раскрашивания типа, используемого по умолчанию, необходимо установить громкость в 70%:
----
pamixer --set-volume 7
ponymix set-volume 7O
----
Чтобы узнать больше, наберите:
----
pamixer -h
ponymix --help
----

==== pacmd и pactl (для PulseAudio)

Both of these command line applications control a running PulseAudio daemon.

WARNING: WАRNING: Однажды pacmd набрал интерактивный диалог. Нажмите Ctrl+d, чтобы выйти из него, но не вводите выход, так как это может убить PulseAudio!

Чтобы узнать больше:
----
man pactl
man pacmd
pactl --help
pacmd --help
----

==== Сохранить и восстановить уровень звука

Просто сделайте файл /etc/rc.d/rc.alsa исполняемым. Как корень:
----
chmod /etc/rc.d/rc.alsa
----
At startup, this script will restore the previous sound settings if saved, else will set default volumes and store them, so that they will be restored at next reboot.

Если вы don't хотите, чтобы этот скрипт установил тип тома по умолчанию как root:
----
касание /var/lib/alsa/no.asound.state
----

Вы можете изменить уровни звука по умолчанию с помощью alsamixer или amixer , а затем ввести как root:
----
alsactl магазин
----
Затем при следующем запуске скрипт восстановит их.

Чтобы узнать больше:
----
man alsactl
----

=== Конфигурация сети

Если вы не установили't настройки сети во время установки Slint, первый станет root'ом, набрав `su -` либо в консоли, либо в графическом терминале, например mate-terminal, затем введите пароль администратора.

Настройка сети осуществляется скриптом `netsetup`. Таким образом, вы просто наберите команду `netsetup` на этом том же терминале, где вы've просто требует root-привилегий. Сначала вам будет предложено имя хоста вашей машины. вы можете выбрать любое имя , но имейте в виду, что оно должно быть одним словом. Тогда вас попросят доменное имя. Если машина не является сервером , вы можете выбрать любого. После этого вам будет задан вопрос о том, как ваша машина подключается к сети. Если у вас , у вас есть некая причина (и вы знаете, что делаете), храните по умолчанию `NetworkManager` для автоматической настройки сети.

Для проводных соединений, которые должны быть достаточно для подключения при следующей загрузке автоматически.

Для настройки беспроводного соединения доступны две команды с помощью командной строки.

Опять же, вы можете напечатать команды прямо на консоли или в графическом терминале типа mate-terminal. Напечатайте их как обычных пользователей не как root. Если вы следовали этим инструкциям и уже стали суперпользователями, вы просто напечатаете `выход` , чтобы вернуть статус обычного пользователя.

Две упомянутые команды - `nmtui` (диалоговое окно) или `nmcli` (чистая командная строка), доступны для обоих.

If you prefer working on a command line, make sure to read the nmcli documentation first. Just type `nmcli --help` and `man nmcli` to find out all the details. While `nmcli` offers more possibilities, in most use-cases the functionality of `nmtui` will be sufficient for setting up your wireless network, so we will describe it here:

Using `nmtui`, you can navigate with the Tab and arrow keys. You will be proposed three options: +
`Edit a connection` +
`Activate a connection` +
`Set system hostname` +

Если беспроводное соединение еще не установлено, выберите `Активировать соединение`. Начиная с сверху вниз, сначала проводные соединения (если таковые имеются) будут предложены, после чего все доступные беспроводные сети будут перечислены. Перейдите с помощью клавиш со стрелками вниз и вверх, чтобы выбрать нужную вам сеть, затем просто введите Enter: вы, вероятно, попросят ввести пароль или ключ шифрования. Введите его, используйте клавишу Tab для подтверждения, а затем выйдите и вы закончите.

Только в графическом режиме вместо `nmcli` или `nmtui` вы можете использовать приложение `nm-connection-editor`.

=== Конфигурация сервисов

You can change the default settings several ways:

* Запуск как root команды `servicesetup` (TUI)
* In graphical mode only, using `gtkervicesetup`, accessible from the Slint Control Center, category System or typing Alt+F2 to raise a "Run..." dialog then typing *gtkservicesetup*.
* В качестве корневого создания соответствующего скрипта (chmod 755 <path to the script> или не исполняемый файл (chmod 644 <path to the script>). Например, чтобы сделать fail2ban исполняемым файлом вы введете: `chmod 755 /etc/rc.d/rc.fail2ban`

IMPORTANT: Изменять настройки по умолчанию, только если вы знаете, что вы делаете.

Сервисы управляются скриптами, имя которых начинается с `rc.` в каталоге /etc/rc.d/. Например, сервис acpi управляется скриптом оболочки /etc/rc.d/rc.acpi. Большинство сервисов включаются при запуске, если соответствующий скрипт исполняется. В нижеследующей таблице мы указываем, активируется ли она при запуске (`на` в колонке А) или нет (`выкл` в колонке А). Если столбец пуст, то активация сервисов зависит от выбора, сделанного во время установки. `A` в столбце означает, что служба активирована в режиме автоустановки, активируется если пользователь выбран во время установки. Столбец Пакета указывает, какой программный пакет предоставляет сценарий, соответствующий службе, случается

[options="autowidth"]
|====
| *Service* | *A* | *Package* | *Purpose and comments*
| acpi | on | acpid | Advanced Configuration and Power Interface, allows for instance to manage power or reboot pressing a button
| alsa | on | alsa-utils | Provide default sound settings or restore those saved
| alsa-oss | off | alsa-utils | ALSA OSS kernel modules. Not useful in most cases, not enabled by default in Slint.
| atalk | off | netatalk | Allows Unix-like operating systems to serve as file, print and time servers for Macintosh computers.
| atd | off | at | at and batch read shell commands from standard input (or a specified file) storing them as a job to be scheduled for execution at a later time
| autofs | off | autofs | AutoFS provides automounting of removable media or network shares when they are inserted or accessed.
| bind | off | bind | Name server. Most users will rely on a remote one. Enable it if you want to run a name server in this system.
| bitlbee | on | bitlbee | BitlBee is an IRC daemon that can talk to instant messaging networks
       and acts as a gateway. Users can connect to the server with any normal
       IRC client and see their 'buddy list' in bitlbee.
| bluetooth | on | bluez | Allows to communicate with bluetooth devices
| brltty| | brltty | Allows to communicate with Braille terminal or screen reader. Activated if requested during installation
| cgconfig | on | libcgroups | Runs the cgconfigparser utility that parses /etc/cgconfig.conf to setup the control group hierarchy, including setting the permissions (UID and GID) of the groups and possibly tunable parameters of the controllers. This alleviates doing that ourselves at every startup, for instance running a separate shell script. This script is executable by default but anyway won't do anything until /etc/cgconfig.conf be edited (all lines are commented out as shipped)
| cgred | on | libcgroups | The control groups are a way to control the allocation of system resources like CPU or RAM to "groups" of users and/or processes. This script starts the cgroups rules engine daemon that automatically distributes to appropriate control groups the processes that changes their effective UID or GID. It is executable by default but to make it work you need to set rules in /etc/cgrules.conf.
| consolekit | on | ConsoleKit2 | This daemon is used by polkit's auth agent, to check privileges of user wanting to reboot or shutdown the system, for instance.
| cpufreq | on | sysvinit-scripts | Settings for CPU frequency and voltage scaling in the kernel.
| crond | on | crond |The cron daemon runs in the background and executes tasks on behalf of users at the appropriate time.
| cups | on | cups | Startup/shutdown script for the CUPS print server.
| cups-browsed | off | cups-filters | Makes remote printers available locally.
| dnsmask | off | dnsmask | Start/stop/restart dnsmasq (a small DNS/DHCP server)
| dovecot | off | dovecot | Dovecot is an open source IMAP and POP3 server for Linux/UNIX-like systems, written with security foremost in mind. 
| elogind | on | elogind | elogind is the systemd project's logind, extracted to a standalone  package.
| espeakup | | espeakup | starts/stop/restart the espeakup console screen reader. On if user requested speech during installation or later typed speak-with espeakup
| fail2ban | off | fail2ban | start/stops fail2ban which scans log files like /var/log/pwdfail and bans IP that makes too many password failures, and also updates firewall rules to reject the IP address.
| fenrir | off | fenrir | starts/stop/restart the fenrir screen reader, which can be started after installation typing speak-with fenrir.
| font | off | kbd | Sets the console font (used in Console mode, not in Graphical mode)
| fuse | on | fuse | Load the fuse module and mount the fuse control filesystem. FUSE is a simple interface for userspace programs to export a virtual filesystem to the Linux kernel. FUSE also aims to provide a secure method for non privileged users to create and mount their own filesystem implementations.
| fuse3 | on | fuse3 | Like fuse, but version 3 
| gpm | on | gpm | The General Purpose Mouse server allows to cut and paste text from the screen on a Linux console.
| haveged | on | haveged | The haveged project is an attempt to provide an easy-to-use, unpredictable random number generator based upon an adaptation of the HAVEGE algorithm.
| httpd | off | httpd | Starts or stop the Apache web server
| icecc-scheduler | off | icecream | Start/stop/restart the icecream (distributed compiler) scheduler
| iceccd | off | icecream | Start/stop/restart the icecream (distributed compiler) daemon
| inet1 | on | network-scripts | This script is used to bring up the various network interfaces.
| inet2 | on | network-scripts | This shell script boots up the entire network system.
| inetd | on | inetd | BSD "super-server" daemon. The user needs to edit /etc/inetd.conf for the services to be actually used.
| ip_forward | off | network-scripts | Start/stop IP packet forwarding, needed for your computer to act as a router.
| kadmind | off | krb5 | Start the Kerberos administration server
| kprprod | off | krb5 | Start the Kerberos V5 slave KDC update server. 
| krb5kdc |off | krb5 | Start krb5kdc, which is the Kerberos version 5 Authentication Service and Key Distribution Center (AS/KDC). This needs to run first on both master and secondary KDCs.
| local | off | sysvinit-scripts | starts daemons not started by /etc/rc.d/rc.M at boot time.
| loop | on | sysvinit-scripts | Loads the loop device kernel module.
| lxc | off | lxc | This scripts starts (if configured to be auto-started) and stops lxc containers.
| mcelog | off | mcelog | Starts the mcelog hardware error logging. This logs and handles CPU hardware errors on x86 systems
| messagebus | on | dbus | The D-BUS systemwide message bus. This is a daemon which broadcasts notifications of system events and other messages, providing inter-processes communication.
| modules | on | sysvinit-scripts | Compute the kernel modules dependencies and start other scripts that load modules not automatically loaded by eudev, possibly for specific kernel versions
| modules.local | on | sysvinit-scripts | Load modules not automatically loaded by eudev
| mysqld | off | mariadb | Starts/stop the MariaDB server. MariaDB is a fork of MySQL fully compatible with it
| networkmanager| | NetworkManager | This is a daemon for automatically switching network connections to the best available connection. Activated if NetworkManager is chosen to configure the network, during or after installation
| nfsd | off | nfs-utils | Starts/stop a nfs (Network File Server)
| ntpd | on | ntp | Starts stop an ntp ( Net'work Time Protocol) daemon.
| numlock| | salixtools | Activate numlock on the console
| openldap | off | openldap | Start the ldap (Lightweight Directory Access Protocol) server
| openvpn | off | openvpn | Start the OpenVPN (secure IP tunnel) daemon
| pcmcia | off | pcmciautils | Script to initialize PCMCIA subsystem.
| php-fpm | off | php | Starts the PHP FastCGI Process Manager daemon.
| postfix | off | postfix | start Postfix, mail transport and submission agent.
| pulseaudio | off | pulseaudio | Starts pulseaudio system-wide. This is not recommended in Slint.
| rpc | off | rpcbind | Start/stop/restart RPC (remote process communications) daemons needed to use NFS. To run an NFS server, starting these is mandatory.
| samba | off | samba | Start/stop/restart the Samba SMB CIFS file and print server for CIFS clients. It allows you to manage a file space or printers on a Samba host available to CIFS clients (such as PCs running Windows).
| saslauthd | off | cyrus-sasl | saslauthd is a daemon process that handles plaintext authentication requests on behalf of the SASL library. The CMU Cyrus SASL library is mostly used to authenticate to mail servers.
| serial | off | util-linux | Initializes and sets the serial ports on your system
| setterm | on |util-linux | Provides the command line for the setterm utility to set the terminal attributes (primarily used for screen blanking and power management).
| smartd | off | smartmontools | Start/stop/restart the smartd daemon, which monitors the status of S.M.A.R.T. compatible hard drives and reports any problems.
| snmpd | off | net-snmp |Start/stop the net-snmp SNMP (Simple Network Management Protocol) daemon
| speechd-up | | speechd-up | starts/stop/restart the speechd-up screen reader, which can be started after installation typing speak-with speechd-up.
| sshd | on | openssh | Start/stop/restart the secure shell daemon.
| swapinzram | on | swapinzram | Configure a swap block device in RAM using zram
| syslog | on | sysklogd | Start/stop/restart the system logging daemons, that logs both kernel and system's messages.
| sysstat | off | systat | Reset the system activity logs, used to compute performance statistics
| sysvinit | on | sysvinit-scripts | This file provides basic compatibility with SystemV style startup scripts found in many binary packages
| timidity | off | TiMidity++ | Start/stop/restart the TiMidity++ daemon. TiMidity++ is a software synthesizer. It can play MIDI files by converting them into PCM waveform data or other various audio file formats.
| udev | on | eudev | This script initializes udev, which populates the /dev directory with device nodes, scans for devices,
loads the appropriate kernel modules, and configures the devices.
| ulogd | on | ulogd | starts the userspace ulogd daemon for netfilter/iptables related logging.
| vde2 | on | vde2 | Start/stop/restart the VDE daemon. VDE is an ethernet compliant virtual network which includes tools such as 'vde_switch' and 'vdeqemu'.
| wireless | on | wireless-tools|This script sets up PCI, USB, and 32-bit Cardbus wireless devices. Normally this script is called from rc.inet1 rather than run directly
| yp | on | yptools | Start NIS (Network Information Services). NIS provides network-wide distribution of hostname, username, and other information databases.
|====

Вы можете запустить или остановить службу, используя в качестве root службу ``. Чтобы узнать больше типа `man service`.
// Glossary

== Glossary

Several definitiвклs in this glossary are taken or adapted from https://en.wikipedia.org/wiki/Main_Page[Wikipedia] and https://pubs.opengroup.org/onlinepubs/9699919799/[POSIX]

[[applicatiвкл]]Приложение:: An applicatiвкл program (applicatiвкл for short) is a computer program designed to carry out a specific task typically requested by end-users.
+
Applications are not generally considered as part of the operating system, meaning that they can be added to the system after its installation. They perform non-system-related functions, such as word processing, architectural design, mechanical design, publishing, or financial analysis.


[[boot]]Засада::
Boot means switch-вкл a computer to start an operating system. Несколько операционных систем могут быть установлены на одном компьютере. Select which one to load into RAM and run can be dвклe either by the firmware or by a software named boot manager (GRUB in Slint's case). The firmware of a computer can support вклe of following booting mode, or both:
+
* In the Legacy or BIOS mode the OS is loaded executing the instructiвклs written in a boot sector.
* В режиме EFI оператор ОС представляет собой программу, хранящуюся в исполняемом файле, расположенную в каталоге системного раздела EFI (ESP).

[[ЦП]]CPU::
Группа ЦП или ЦП выполняет инструкции по программам.

[[command]]Команда:: Команда определяется https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_104[POSIX] как «директива к <<shell, оболочке>> для выполнения конкретной задачи».
+
Задачей для выполнения может быть <<application, приложение>> или утилита <<utility, >>.
+
Основная структура команд оболочки определена в главе https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09[2.9 Shell Commands] спецификации POSIX.
+
Примеры команд приведены в <<bash shell>>.

[[console]]Консоль:: Слово "console" относится к началу компьютерных систем, когда системный администратор набрал команды на устройстве, включая клавиатуру и принтер, , введенные команды и вывод с компьютера, который печатается на консоли, обеспечивая лог того и другого.
+
В персональных компьютерах пользователь вводит команды на клавиатуре и их вывод на экране, которые могут быть отделены от компьютера или интегрированы в компьютер, как на ноутбуке.

[[device]]Устройство::

Компьютерная периферия или объект, который кажется приложению как таковый.[POSIX]

[[directory]]Каталог::
Каталог - это другое имя папки. Файловые системы используют каталоги для упорядочения файлов внутри разделов.
+
Directories can contain files and also other directories. The resulting structure can be represented as an upside-down tree. The top-level directory of a drive is named the root directory. In Linux the character / separates the levels of the tree. / alone represents the root directory, /home hosts the files belonging to users, /home/didier hosts the files belonging to user didier. /root hosts the files of the user named root (the system's administrator). Note: 'root' can refer to the top-level directory or the system's administrator.

[[drive]]Диск::
Диск - это устройство, сохраняющее неволатильные данные, что означает, что данные не стираются при отключении питания. Примеры: жесткие диски, SSD, USB-стики, SD карты считыватели, eMMC.
+
Хранение данных можно подключить к накопителю или съемному например к SD-картам, USB-накопителям и накопителям, подключенным к USB.
+
Операционная система, установленная в съемном носителе или на внешнем накопителе, портативная: она может быть перемещена с компьютера на другой.

[[display_manager]]Дисплей менеджера::
Дисплей менеджер (или диспетчер логинов) — это программа, которая отображает окно на экране , на котором запрашивается имя пользователя и пароль пользователя, затем запускает графическое окружение, выбранное указанным пользователем.

[[encryption]]Шифрование::
Шифрование - это процесс преобразования данных в неузнаваемую форму ("зашифрованную"). Он обычно используется для защиты конфиденциальной информации, чтобы только уполномоченных лиц могли ее просматривать. Один файл или каталог, раздел также в целом может быть зашифрован, , что делает его доступным только после того, как набрал небольшой текст под названием ключевая фраза, хранится в секрете.

[[file]]Файл::
Компьютерный файл - это набор цифровых данных, собранных под тем же именем, записанных на постоянном носителе, — массовое хранилище, например жесткий диск, SSD, DVD, SD-карта или USN палка и обрабатывается в качестве единицы.
+
Файлы могут содержать такие данные, как тексты, изображения, звуки, видео или компьютерные программы.

[[file_system]]Файловая система::
Файловая система — это программа, которая управляет файлами и каталогами в разделе. Он запоминает местоположение в физическом носителе данных содержащихся в файлах, позволяя их читать или записывать. Примерами распространенных файловых систем являются vfat, ntfs, ext4, f2fs. В этой команде перечислены все файловые системы , позволяющие читать данные, содержащиеся в разделе Linux:
+
----
cat /proc/filesystems|grep -v nodev
----

[[firmware]]Прошивка::
Прошивка — это программное обеспечение, инициализирующее и проверяющее аппаратное обеспечение, затем выбирает и загружает ОЗУ операционной системы, или запускает программу, называемую системным менеджером , который будет делать это. Прошивка хранится в неизменяемой памяти таких устройств, как ROM, EPROM или флэш-памяти. Это первое программное обеспечение, запускаемое при загрузке компьютера. Он предоставляет меню, позволяющее настроить аппаратное обеспечение и выбрать в каком режиме (Legacy или EFI) загрузиться, и в каком порядке искать операционную систему или другие приложения (например, загрузочный менеджер GRUB).

[[kernel]]Kernel::
Ядро Linux — это программное обеспечение в ядре системы Slint, которая обрабатывает взаимодействия между приложениями и оборудованием.
+
Он представляет себя как один файл, установленный в каталоге /boot. Например, файл /boot/vmlinuz-generic-5.12.11 представляет собой ядро из пакета kernel-generic.
+
При запуске ядро копируется в ОЗУ.

[[initrd]]Initrd::
An initrd (more accurately an initramfs or initial RAM file system for Slint) is a Linux system provided as a compressed archive file. At boot, just after the kernel has been loaded in RAM the initrd is loaded in RAM too. Its file /init runs: it loads needed kernel modules in RAM, register the devices, possibly unlock the root device, mount the pseudo file systems then switch to the root file system to actually start the system.
+
initrd представляет себя как один файл, установленный в каталоге загрузки. Например, файл initrd-generic-5.12.11 является initrd

[[live_system]]Онлайн система::
Онлайновая система — это операционная система, которая, вместо того, чтобы устанавливаться на устройстве, например на жестком диске или SSD, находится целиком в <<RAM>>.
+
An initrd is also a live system, and so is a Slint установщик wich is basically an initrd.

[[partition]]Разделы::
A partition is a section of a storage media, such as a hard disk or SSD. It is treated by the operating system as a separate logical volume, which makes it function similar to a separate device.

[[partition_table]]Таблица разделов::
A partition table is the permanent structure recording how information is laid out on a media, mainly recording the beginning and end of each partition on the media.
+
The most common types of partition tables are the DOS partition table, initially used by the MS-DOS operating system, and the GUID Partition Table or GPT, which allows to handle more partitions and larger drives.

[[program]]Программа::
A prepared sequence of instructions to the system to accomplish a defined task. The term "program" encompasses applications written in the Shell Command Language, complex utility input languages (for example, awk, lex, sed, and so on), and high-level languages. [POSIX]

[[RAM]]RAM::
ОЗУ означает память случайного доступа. Этот тип устройства сохраняет волатильные данные, что означает, что данные стираются при выключенном питании.

[[shell]]Ракушка:: A program that interprets sequences of text input as commands. It may operate on an input stream or it may interactively prompt and read commands from a terminal. The syntax of the commands that can be interpreted by the shell can vary depending on the shell in use but are mainly defined in the chapter https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html[2. Shell Command Language] of the POSIX specification.
+
Slint ships several programs acting as shell, listed in the file /etc/shells. The *bash* shell is used by default.

[[swap]]Поменять::
A swap space is used to tentatively store data previously in RAM on a device like a hard disk or SSD, either because else the RAM would become full, or to free space in RAM to store there most frequently used data. The swap space can be a partition on a drive of type 'Linux swap' or a regular file stored in an an existing partition. There is also the 'swap in zram': in this case the data is stored in RAM but in compressed form.

[[terminal]]Терминал::
Historically a terminal was a physical device composed of a keyboard and a screen used to type commands and receives responses from a remote computer.
+
Nowadays the commands can be typed in console (or text) mode or in graphical mode.

[[utility]]Утилита::
An utility is a program that can be invoked by name from a shell (this is also the case of some <<application,applications>>).
+
Utilities are a part of the operating system (but not of the kernel). They perform system-related functions, such as listing directory contents, checking file systems, repairing file systems, or extracting system status information.
+
An utility may be invoked as a separate program that executes in a different process than the command language interpreter, or it may be implemented as a part of the command language interpreter.
+
For example, the echo command (the directive to perform a specific task) may be implemented such that the echo utility (the logic that performs the task of echoing) is in a separate program; therefore, it is executed in a process that is different from the command language interpreter. Practically this means that in this case the utility is a program distinct from the shell
+
Conversely, the logic that performs the echo utility could be built into the command language interpreter; therefore, it could execute in the same process as the command language interpreter. Such an utility is said "built-in" the shell.

[[virtual_terminal]]Виртуальный терминал::
Виртуальный терминал — это программное обеспечение, моделирующее физический терминал, устройство , состоящее из клавиатуры и экрана, позволяющее удаленно общаться с компьютером .
