
= Slint Handbok (version 15.0)
:toc: left
:toclevels: 2
:toc-title: Content
:pdf-themesdir: themes
:pdf-theme: default

Note: this document will be updated to reflect recent changes - 21/06/2024

== Introduktion till Slint

=== Om Slint

Slint är en https://en.wikipedia.org/wiki/Linux_distribution[Linux distribution], baserad på http://www.slackware.com/[Slackware], flerspråkig, lätt att installera, mångsidig, nybörjarvänlig och tillgänglig för synskadade.

Ett Slint-system fungerar direkt och kan skräddarsys för att passa de flesta datorkrav.

==== Funktioner

Två installationslägen föreslås: Automatisk (Installationsprogrammet förbereder den enhet som valts av användaren och installerar Slint på den) och Manuell (Installationsprogrammet formaterar Linux-partitionen som valts av användaren, och installerar Slint på den). Installationsprogrammet innehåller en dokumentation.

Slint är tillgängligt för synskadade användare, med tal och braille, från installation till användning i en konsol och i grafiska miljöer.

Ett stort antal program för servrar, stationära datorer och bärbara datorer är installerade i alla slint-system, som innehåller två grafiska skrivbordsmiljöer: MATE och LXQt, och lättviktiga fönsterhanterare. MATE och LXQt ger enkel åtkomst till alla program och systemåtgärder, med automatisk montering av flyttbara enheter, plus aviseringar om tillgängliga uppdateringar av installerad programvara, omedelbar internetåtkomst, stoppa, starta om och sätta systemet i viloläge.

Det valda språket kommer att användas för internationaliserade program.

Slint Instrumentbräda centraliserar åtkomst till hårdvara och systeminställningar, paket, systemverktyg, dokumentation och verktyg.

Slint skickar med många program för att skriva och läsa och konvertera dokument i olika format, kommunicera via E-post, text och ljudchatt, spela upp ljud och video, skicka och ta emot dokument peer to peer, redigera ljud, video och grafiska dokument, utveckla program. Det är fullt användbart som en server på en konsol och använda en av de flera inkluderade skrivbord.

Många program är tillgängliga för synskadade användare, ett brett utbud av TTS och tillhörande röster ingår, om du fortfarande behöver andra är det lätt att installera, kan användas både i en textuell miljö (konsol) samt på skrivbordet.

Flera interna verktyg underlättar administrationen och konfigurationen av ditt Slint-system.

Många fler program är lätt att bygga som programvarupaket genom ett enkelt kommando eller några klick. Tusentals mjukvarupaket ligger nära till hands!

Slint-användare meddelas om uppgraderingar av installerade paket så snart som de är tillgängliga, enkelt installerat på begäran. Detta håller ditt system säkert.

Standardinställningar för program tillhandahålls och kan enkelt anpassas.

==== Innehåll, versioner och releasemodell.

Installationsprogrammet Slint tillhandahåller endast en fullständig installation.

Slint följer en "halvrullande" releasemodell, vilket innebär att under livscykeln för en viss version, förutom uppdateringar som säkerhetsfixar och stora felrättningar, uppdateras vissa program för att skapa förbättringar och lägga till nya funktioner. Detta är fallet när det gäller programvara som bidrar till att göra Slint tillgängligt för blinda, t. ex. skärmläsare.

Vi rekommenderar att användare byter till en ny version så snart som möjligt efter dess release. Vi rekommenderar att de gör en fullständig backup av alla data de vill behålla följt av en ny installation och en återställning av säkerhetskopian.

=== Om denna bok, och andra informationskällor

Denna bok är avsedd för Slint nybörjare som guidas genom sin installationsprocess och användning. De begrepp och konventioner som är specifika för Slint och vanliga i Linuxdistributioner presenteras och en ordlista bifogas.

Vi försöker att tillmötesgå folk som kommer från Windows eller MacOS och användare av en annan distribution så som Ubuntu.

Dokumentation om installerad programvara är generellt tillgängligt i ett Slint-system. Vi kommer att i denna bok ange hur man får tillgång till den.

Andra informationskällor finns tillgängliga:

* Den information som ofta tillhandahålls på deras hemsida av författarna till programvara som ingår i Slint.
* http://docs.slackware.com/[Dokumentationsprojektet Slackware] och särskilt dess http://docs.slackware.com/howtos:start[HOWTO-artiklar]. Många är direkt tillämpliga på Slint, vissa anpassningar och uppdateringar kan vara nödvändiga.
* Utöver Arch distributionen, ger ArchWiki ofta användbara artikel om programvara som också levereras i Slint. Till exempel att söka på "arch wiki mate" leder till https://wiki.archlinux.org/index.php/MATE[denna sida om MATE]. Förbehåll: den information som ges kan behöva anpassas eftersom Slint och Arch skiljer sig åt på vissa områden. Till exempel använder Arch systemd som init-system och en viss programvara kan konfigureras på olika sätt som standard i Slint och Arch.
* Och naturligtvis kan en sökmotor på Internet ofta hjälpa till att hitta svar på frågor och lösningar på problem.
// Support

=== Support

Du kan få hjälp genom dessa kanaler:

* Slints sändlista är den primära supportkanalen. För att registrera dig, skicka E-post till slint-request@freelists.org med ämnet: "subscribe" svara sedan på bekräftelsemeddelandet som du kommer att få. Sedan, för att veta mer skicka E-post till slint-request@freelists.org med ämne såsom 'commands' eller 'help'. Efter registrering, skicka E-post till slint@freelists.org.
* Arkiven för sändlistan finns https://www.freelists.org/archive/slint[här].
* På IRC: chatta på #slint kanalen, server irc.libera.chat, ingen registrering behövs.
* Mumble: server slint.fr (efter överenskommelse tas kontakt via en annan kanal).
* https://forum.salixos.org/viewforum.php?f=44[Slint forumet] som vänligen hostas av våra vänner på Salix (en annan Slackware derivat). Registrering krävs.


För att ta reda på mer, se länkarna under Information i Slint Instrumentbräda, eller starta en terminal och skriv: slint-doc i en terminal efter installation.

=== Översättning och andra bidrag till Slint-projektet

Slint behöver översättare! Om du vill delta i översättningsarbetet, läs instruktionerna i https://slint.fr/doc/translate_slint.html[Translate Slint].

Översättningsfilerna finns på https://crowdin.com/project/slint[Crowdin].

Om du vill bidra till Slint för andra uppgifter, posta bara i sändlistan eller skriv en rad till: didieratslintdotfr. Självklart är även översättare välkomna på sändlistan!
// Acknowledgments

=== Erkännanden

Slint-projektet existerar främst genom det hårda arbetet hos Slint-översättare och andra bidragsgivare, tack till er alla!

Tack till George Vlahavas för hans råd och verktyg, till bidragsgivarna till SlackBuilds.org projektet, som hjälper till att bygga så många ytterligare programvaror.

Slint är baserat på Slackware, som Patrick J. Volkerding och bidragsgivare skapat. Tack! Jag uppmuntrar alla Slint-användare att bidra till Slackware-finansiering, och även att donera till Salix-projektet.

Slint´s paketförråd är vänligen hostad gratis av Darren 'Tadgy' Austin. Jag uppmuntrar alla Slint-användare att bidra till att finansiera värden https://slackware.uk/

Länkar till finansiella bidrag: +
https://www.patreon.com/slackwarelinux[Bli en Slackware patreon] eller https://paypal.me/volkerdi[Support Slackware] +
Följ länkarna överst http://slackware.uk/slint/x86_64/slint-15.0/[på sidan] för att stödja Slackware UK +
https://salixos.org/donations.html[Donationer till Salix]

== Installera Slint

Denna del av HandBook går genom processen att ladda ner Slint, verifiera ISO-avbilden med en kontrollsumma, skriva ISO till ett installationsmedium, partitionera din hårddisk, och beskriver kort installationsprocessen.

=== Krav

Den aktuella Slint-versionen kan installeras på datorer som uppfyller följande krav:

* Arkitektur: x86_64 (64-bitars CPU), även känd som AMD64
* En diskenhet med en storlek på minst 50G behövs i autopartitioneringsläge
* In Manual partitioning mode a partition of type Linux of size at least 50G, an EFI system partition and/or a BIOS boot partition on the same disk drive. The EFI partition is mandatory if the machine boots in EFI mode, the BIOS boot partition if the machine boots in Legacy mode, having both is better to allow swictching between EFI and Legacy modes.
* Slint kan installeras på följande typer av enheter: hårddiskar, SSD, NVME, eMMC, USB-stickor, SD-kort (helst i USB-kabinett).
* RAM: minst 2G
* en DVD-enhet eller en USB-plats, med kapacitet för den inbyggda programvaran att starta en DVD eller ett USB-minne. En tom dvd eller en USB-minne på 5G eller mer kan användas som installationsmedium

NOTE: Secure boot bör inaktiveras för att installera Slint.

=== Funktioner i installationsprogrammet

* Installationsprogrammet är ett "live-system" som körs i minnet: det kommer inte att ändra ett installerat system, om inte och tills du säger till det.
* För blinda användare är installationsprogrammet fullt användbart med Braille och tal med Speakup-skärmsläsaren.
* Den innehåller alla nödvändiga verktyg för att förbereda de nödvändiga partitionerna före en installation i manuellt partitioneringsläge.
* I autoläget ges en kontextuell hjälp och användaren behöver bara svara på några frågor.
* Om den är installerad på en flyttbar enhet som är ansluten via USB, Slint är portabel, dvs. kan användas på alla datorer som kan starta en USB-enhet utöver den dator som används för att installera den. Om du t.ex. installerar på en USB-sticka kan du bara plugga in stickan i en dator för att kunna köra den.
* Installationsprogrammet kan kryptera enheten där Slint är installerat ensam. Detta förhindrar stöld av data som den innehåller i händelse av förlust eller stöld av maskinen, eller av en flyttbar enhet.
* Slint kan installeras på en egen enhet, och i manuellt partitioneringsläge vid sidan av ett annat system.

=== Förberedelse

<<download_and_verify,Ladda ner och verifiera en Slint ISO-avbild>> +
<<write_the_iso,Skriv ISO-avbilden på ett installationsmedium>> +
<<prepare_partitions_for_Slint,Valfritt, förbered partitioner för Slint>>

[[download_and_verify]]
==== Ladda ner och verifiera en Slint ISO-avbild

Den senaste versionen av Slint-distributionen är 15.0

Den senaste installations ISO-avbilden finns alltid i https://slackware.uk/slint/x86_64/slint-15.0/iso[denna katalog]

This ISO image can also be downloaded using a Torrent Client from this page:

https://seedbox.slackware.uk/

The link to the torrent, after the label "Slint Torrents", is:

https://seedbox.slackware.uk/torrents/slint64-15.0-5-iso.torrent

A magnet is also provided.

[TIP]
====
Så länge som du kör Slint version 15.0 behöver du inte installera om när en ny ISO tillhandahålls, eftersom den bara innehåller nya funktioner i installeraren och nya eller uppgraderade paket som du också kan få genom att hålla ditt system uppdaterat.
====

Filnamnet på den ISO som anges nedan är bara ett exempel, som du behöver anpassa till det aktuella namnet när du laddar ner.

Om du kör Windows, kommer en sökning på Internet med en sökfras som "kontrollera sha256sum windows" att berätta för dig hur du skall gå vidare.

Om du kör Linux kan du ladda ner ISO-avbildningen och dess sha256-kontrollsumma genom att skriva:
----
wget https://slackware.uk/slint/x86_64/slint-15.0/iso/slint64-15.0-5.iso
wget https://slackware.uk/slint/x86_64/slint-15.0/iso/slint64-15.0-5.iso.sha256
----

För att kontrollera integriteten för de nedladdade filerna skriv detta kommando:
----
sha256sum -c slint64-15.0-5.iso.sha256
----

Resultatet bör vara : OK +
Annars, ladda ner på nytt.

[[write_the_iso]]
==== Skriv ISO-avbilden till ett installationsmedium

Du kan använda antingen en DVD eller ett USB-minne som installationsmedia.

[TIP]
====
You can just store the ISO image in the first partition of a Ventoy USB stick.

In this case at the beginning of installation the installer will request that you mount this partition, then mount the ISO itself.
====

[[make_a_bootable_usb_stick]]
===== Skapa en startbar USB-minne

På ett ++Linux++-system, sätt i USB-minnet och kontrollera namnet med följande kommando:

----
lsblk -o modell,namn,storlek,fstyp,monteringspunkt
----

[WARNING]
====
Granska noggrant resultatet av kommandot för att se till så att du inte kommer att skriva namnet på en hårddisk-partition istället för namnet på ditt USB-minne. Allt tidigare innehåll på USB-minnet eller en felaktig hårddiskpartition kommer att vara *FÖRLORAT* och *OÅTERKALLELIGT*.
====

Låt oss anta att namnet på USB-minnet är /dev/sdb. Det kan namnges annorlunda, så kopiera inte blint följande kommando. Kommandosyntaxen för att skriva Slint ISO till ett USB-minne som finns på /dev/sdb är följande:

----
dd if=slint64-15.0-5.iso of=/dev/sdb bs=1M status=progress && sync
----

[NOTE]
====
Kommandot ovan antar **if=** pekar mot sökvägen till Slint ISO och **of=** pekar till namnet på USB-minnet. Dessa värden kan skilja sig på ditt system.
====

På ++Windows++ kan du använda ett program som t.ex. http://rufus.akeo.ie/[Rufus]. Det är gratis och öppen källkod.

[[make_a_bootable_DVD_disc]]
===== Skapa en startbar DVD-skiva

På ett ++Linux++-system sätt in en DVD och skriv följande kommando:

----
xorriso -as cdrecord -v dev=/dev/sr0 -eject slint64-15.0-5.iso
----

Var noga med att ange hela sökvägen till Slint ISO-filen på ditt filsystem.

På ++Microsoft Windows 2000 /XP/Vista/7++ kan du skriva till en DVD med hjälp av programmet http://infrarecorder.org/[InfraRecorder]. Den är fri och öppen källkod.

På ++Microsoft Windows 7/8/10++ kan du använda verktyget som levereras med Microsoft Windows.

* Right-click the ISO file and select Burn disk image (if on Windows 11, select Show more options first (Shift+f10)
* För att se till att ISO brändes utan några fel, välj Verifiera disk efter bränning.

[NOTE]
====
Instruktioner som inte kontrolleras av författaren.
====

// Prepare
[[prepare_partitions_for_Slint]]
==== Valfritt: Förbered partitioner för Slint

I det här dokument betyder 'format' en partition: skapa ett filsystem i den för att hantera de filer den kommer att innehålla.

Om du efter att ha skrivit "start" skriver "m" för manuell partitionering väljer du först root-systempartitionen, som kommer att monteras som "/", sedan typ av filsystem t.ex.: btrfs, ext4, xfs.

Installationsprogrammet listar enbart partitioner för val med minst 50G och Linux (kan också kallas Linux-filsystem), inte krypterade. Den här partitionen kan formateras eller inte, men dess innehåll kommer i alla händelser att rensas bort och ett nytt filsystem genereras av installationsprogrammet.

Dessutom krävs i manuell partitioneringsläge på samma enhet som rotsystempartitionen:

* A partition of type BIOS boot partition, of size at least 3M and not formatted if the machine boots in Legacy mode and the drive has a partition table of type GPT.
* A partition of type EFI system, with at least 32M free space in it, formatted with a 'fat' (or 'vfat') file system as required by the UEFI specification if the machine boots in EFI mode

It is better to set up both partitions to allow switching between Legacy and EFI modes if the drive has a partition table of type GPT.

Using for Slint existing partitions or creating them is up to the user. Already installed systems using the BIOS boot and the EFI partitions will not be affected, only the root partition will be (re)formatted, and an existing /home partition only if requested.

Installationsprogrammet innehåller flera partitioneringsprogram: cfdisk, fdisk, sfdisk, cgdisk, gdisk, sgdisk, partad. Programmen med "g" i deras namn kan hantera endast gpt, parted kan hantera DOS-partitionstabeller samt GPT. fdisk, cfdisk och sfdisk kan hantera DOS partitionstabeller. Dessutom, wipefs (för att radera tidigare partitionstabell och filsystem signaturer) och partprobe (för att informera kärnan om en partitionstabelländringar) är tillgängliga. Programmet lsblk visar information om blockenheter och partitioner.

Naturligtvis kan du också skapa partitionerna från ett annat system innan du startar installationsprogrammet.
// Installation

=== Slint installation
<<Start_of_the_installation,Starta installationen>> +
<<Overview_of_Slint_Installation,Översikt över installationsprocessen>> +
<<Usage_of_the_installer,Användning av installationsprogrammet>> +
<<Encryption,Slint med en krypterad rotpartition>> +
<<Speakup,Tangentbindningar för Speakup-skärmläsaren>> +
<<first_steps_after_installation,Första stegen efter installationen>>

[[Start_of_the_installation]]
==== Start av installationen

Om du behöver det, ställ in maskinens inbyggda programvara för att starta upp den på DVD eller USB-minne som du har förberett.

Sätt i installationsmediet (DVD-eller USB-minnet) och starta om datorn. För att hjälpa blinda användare hörs en melodi när startmenyn visas.

Starta installationsprogrammet genom att trycka på Enter.

Installationsprogrammet kommer först söka efter ett ljudkort.

Detta kan hjälpa till att ställa in en fungerande som standard, och används även för tal under installation som används av vissa blinda användare.

Om installationsprogrammet hittar mer än ett ljudkort så kommer det att sägas på engelska för varje: +
tryck Enter för att välja det här ljudkortet <sound card id> +
Tryck på enter så snart det hörs, för att bekräfta att det föreslagna ljudkortet fungerar. Denna inställning kommer att sparas i det nya systemet i /etc/asound.conf.

Vid nästa steg, när du blir tillfrågad kommer du att bekräfta (skriv s) eller neka (trycka bara på Enter) att du vill ha tal under installationen. Braille finns alltid tillgängligt under installationen.

Du kommer då att välja, bekräfta eller ändra språket som används under installationen. Då kommer alla skärmar att vara i det valda språket om översättningen till detta språk är klar.

Om du behöver lägga till ytterligare kärnparametrar till kommandoraden för uppstart innan du trycker på Enter gör det som följer:
[NOTE]
====
Var medveten om att den amerikanska tangentbordslayouten kommer att användas när du skriver. +
Ctrl+x betyder "Tryck och håll ned Ctrl- eller Control-tangenten som om det var en Shift-tangent och tryck sedan på X-tangenten"
====
----
Tryck på e-tangenten
Tryck på nerpilen tre gånger
Tryck på End-tangenten
Tryck på mellanslagstangenten
Skriv in kärnparametrarna (exempel nedan)
Tryck på Ctrl+X för att starta (tryck inte Enter!)
Tryck på Enter för att starta.
----

Till exempel för att konfigurera speakup-drivrutinen för din maskinvarusynt kan du skriva en kärnparameter i stil med:
----
speakup.synth=apollo
----
Du kan även inkludera inställningarna för din punktskriftsenhet i kommandoraden för uppstartskommandot, i denna form:
-----
brltty=<driver code>,<device>,<text table>
-----
Till exempel för att installera med en Papenmeier-enhet ansluten via USB med en fransk texttabell skriv in:
-----
brltty=pm,usb:,sv_SE
-----
NOTE: En punktskriftsenhet ansluten via USB ska alltid kännas igen, kanske kommer inte texttabellen att vara bra om du inte gick in i inställningarna först.

I vilket fall som helst, eftersom det inte finns någon timeout, startar du först när du trycker på [Enter].

Tal och punktskrift kommer att finnas tillgängliga i början av installationen.
// Overview
[[Overview_of_Slint_Installation]]
==== Översikt över installationsprocessen

Installationsprogrammet söker först på befintliga enheter och partitioner för att bedöma möjligheterna och alternativen för installation och låter dig välja mellan en automatisk eller manuell förberedelse av de partitioner som används av Slint.

Om du väljer "manuell" visas de Linux-partitioner där Slint kan installeras (storlek minst 50G), välj en av dem och välj den typ av filsystem som installationsprogrammet ska skapa på den: btrfs, ext4 eller xfs enligt vad som anges i <<prepare_partitions_for_Slint,Förbered eventuellt partitioner för Slint>>

Om du väljer "auto" visas de enheter där Slint kan installeras (storlek minst 50G), och filsystemet kommer att vara av typen btrfs.

In case of btrfs sub-volumes will created for "/" and "/home" with files compressed, and /swap to host a swap file. 'Copy on write' will ease making snapshots and possibly revert a faulty system update. Tools to manage the snapshots are included in Slint.

I båda lägen väljer användaren vilka befintliga Linux-och Windows-partitioner som ska monteras automatiskt efter uppstart av Slint, och deras monteringspunkt-namn, underlättar åtkomsten till existerande system och data från Slint.

Sedan föreslås användaren att kryptera rotsystems-partitionen, för att förhindra att data stjäls vid förlust eller stöld av maskinen eller enheten där Slint är installerat. Om det accepteras kommer installationsprogrammet att lagra lösenordsfrasen som tillåter att låsa upp denna partition. Användaren kommer när han skriver det vid uppstart när GRUB begär att få visa uppstartsmenyn.

Efter allt det kommer installationsprogrammet att sammanfatta dina val och låter dig bekräfta dem eller inte. Fram till denna punkt kommer ingen ändring att ha gjorts på det installerade systemet och data så att du säkert kan avbryta, skriv sedan start igen eller bara reboot utan att något skadas.

Därefter utförs automatisk partitionering, Slint rotpartitionen krypteras om så önskas, rotpartitionen är formateras och de första programpaketen installeras.

Om du väljer en krypterad disk skriver du lösenordsfrasen som kommer att användas för att låsa upp disken vid varje uppstart.

Du väljer ett lösenord för användaren "root". Det här är systemadministratören som har alla behörigheter.

Du anger också inloggningsnamnet och lösenordet för en vanlig användare.

Du anger om du vill ha åtkomst till Braille och om du vill logga in i text eller grafiskt läge. Om du använder språket engelska (USA) under installationen väljer du det språk som ska användas i det installerade systemet, annars anger installationsprogrammet samma språk som under installationen.

Installationsprogrammet försöker upprätta en Internetuppkoppling, och om det föreslås en tidszon som motsvarar den geografiska plats som du bekräftar, annars väljer du en annan i en lista.

Du blir tillfrågad om du behöver Braille, sen om du föredrar att starta i en konsol eller i ett grafiskt såvida du inte använt tal under installationen eller behöver punktskrift: då kommer du att landa i en konsol efter omstart, för säkerhets skull.

Installationsprogrammet skapar sedan en swap-fil. Det här kan ta en lång tid, var tålmodig.

Paketen installeras på enheten. Om en Internetanslutning har upprättats hämtas den och installerar den senaste versionen av varje paket, inklusive de som tillhandahålls sedan versionen av ISO-avbilden.

Installationen av alla paket tar ca 10 till 40 minuter beroende på maskinvaran.

Du kommer att bli ombedd att välja ett skrivbord (även om du startar i en konsol först) mellan fvm, lxqt, mate och wmaker. Andra alternativ kommer att vara tillgängliga efter installationen av xwmconfig om du startar i en konsol

Sedan är systemet konfigurerat och GRUB-starthanteraren är installerad. Slint kan starta i både Legacy och EFI-lägen. Startmenyn kommer att innehålla en "Rescue"-startpost för att upptäcka och tillåta att alla installerade operativsystem kan startas.

Du kan visa en förhandsgranskning av startmenyn innan du startar om.

Ta sedan bort installationsmediet och starta om för att starta ditt nya Slint-system.
// Usage_installer
[[Usage_of_the_installer]]
==== Användning av installationsprogrammet

Om du är bekant med kommandoraden, kan du hoppa över detta ämne.

Huvudinstallationsmenyn visas nedan:
....
Välkommen till Slint-installeraren! (version 15)

Du kan nu skriva (utan citattecken):

'doc' för att känna till funktionerna och användningen av installationsprogrammet.
'start' för att starta installationen.

Installationsprogrammet kan förbereda enheten där Slint kommer att installeras,
och skapa de nödvändiga partitionerna. Om du föredrar att du vill göra det själv kan du göra det
med hjälp av kommandoradsverktyg som är tillgängliga i installationsprogrammet och sedan skriva "start"
när det är klart. Du kan också lämna installationsprogrammet och använda ett verktyg som gparted
för att göra det och starta sedan installationsprogrammet igen.

Vi rekommenderar att du skriver 'doc' först i det här fallet, eller om du vill 
kryptera Slint`s rotpartition.
När du har läst färdigt kommer den här menyn att visas igen.
....

Så snart denna meny visas, har du handen på installationsprocessen.

Du läser på skärmen och skriver kommandon i en <<virtual_terminal, virtuell terminal>>. Installationsprogrammet innehåller 4 virtuella terminaler som delar samma fysiska tangentbord och skärm, och som kan användas parallellt.

Installationsprogrammet startar i den virtuella terminalen 1 som heter *tty1* men du kan byta till en annan. Till exempel kan du växla till *tty2* genom att trycka *Alt-F2* och sedan Enter för att aktivera den och senare gå tillbaka till *tty1* genom att trycka på *Alt-F1*, utan att radera information som visas i båda terminalerna. *Alt-F1* betyder: tryck och håll nere *Alt* -tangenten och tryck sedan på *F1* tangenten.

Detta kan vara användbart för att fortsätta läsa dokumentationen under installationen: till exempel kan du växla till *tty2* för att påbörja installationen. växla till *tty1* för att fortsätta läsa dokumentationen, växla sedan till *tty2* igen för att fortsätta till nästa installationssteg.

Detta kan också användas för att konsultera ordlistan när du läser andra dokument.

Installationsprogrammet har flera typer av interaktion med dig, användaren:

* Du skriver kommandon på prompten och läser dess utdata.
* Installationsprogrammet ställer en fråga, du skriver in svaret och bekräftar det genom att trycka på Enter.
* Installationsprogrammet visar en meny med val eller alternativ: du väljer en av dem med hjälp av upp och ner piltangenterna, bekräfta sedan ditt val genom att trycka på Enter, eller avbryt genom att trycka på Escape.
* Installationsprogrammet visar information i en pager. Använd piltangenterna för att läsa nästa eller föregående rad, tryck på mellanslag för att visa nästa sida, Q för att sluta läsa dokumentet.

// Encryption
[[Encryption]]
==== Slint med en krypterad rotpartition.

I Auto-läge föreslår installationsprogrammet att kryptera rotsystemspartitionen. Om du samtycker, kommer GRUB starthanteraren vid varje uppstart att fråga efter lösenordsfrasen som du angav under installationen för att låsa upp enheten, innan uppstartsmenyn visas. Var medveten om att upplåsning av enheten kommer att ta några sekunder (cirka tio sekunder).

Att ha ett krypterat rotsystem förhindrar stöld av data som den innehåller vid förlust eller stöld av maskinen, eller av en flyttbar enhet. Men detta kommer inte att skydda dig om datorn förblir igång och obevakad, bara om maskinen har stängts av helt!

Under installationen kommer Slint systempartitionen att krypteras, och även ytterligare partitioner som du begär.

Ett Slint-system (eller root) partition kommer att namnges: /dev/mapper/cryproot när den öppnas, om den har krypterats.

Detta visas av detta kommando:

----
lsblk -lpo namn,fstype,monteringspunkt | grep /$
----

Vilket ger en utmatning liknande:
----
/dev/mapper/cryptroot ext4 /
----

Detta kommando istället:

----
lsblk -lpo namn,fstype,monteringspunkt | grep /dev/sda3
----

ger:

----
/dev/sda3             cryptoLUKS
----

/dev/sda3 är nu en "rå" partition som innehåller det så kallade "LUKS header" som du aldrig kommer att behöva eller någonsin bör komma åt direkt. Den är värd för allt som behövs för att kryptera eller dekryptera partitionen /dev/mapper/cryptroot, som faktiskt är värd för dina data (i detta exempel Slint-systemet).

[WARNING]
====
Om du glömmer lösenordsfrasen kommer all data i enheten att vara oåterkalleligt förlorad! Så skriv ner eller spela in denna lösenordsfras och placera den på en säker plats så snart som det är gjort.

Enheter dör. Om det händer och den är krypterad kommer dina data att gå förlorade. Så, säkerhetskopiera regelbundet dina viktiga data, detta är inte frivilligt.

Gör också en säkerhetskopia av den luks header så att du kan återställa ifall luks partition skadas av någon anledning. Kommandot kan finnas i vårt exempel:
----
luksHeaderBackup /dev/sda3 --header-backup-file <fil>
----
där <fil> är namnet på backupfilen, som du skall lagra på en säker plats.

Om du skulle du behöva återställa säkerhetskopian, skriv:
----
luksHeaderRestore /dev/sda3 --header-backup-file <fil>
----

Ändra inte storlek på en partition på en krypterad enhet som efter det skulle definitivt bli låst och alla data som den innehåller kommer att förloras! Om du verkligen behöver mer utrymme måste du säkerhetskopiera alla filer som du vill behålla, installera sedan på nytt och återställa säkerhetskopierade filer.

Välj ett starkt lösenordsfras, så att det skulle ta för mycket tid för en tjuv att upptäcka att det ska vara värt besväret.

Fiddla aldrig någonsin med den så kallade "LUKS header" som ligger på den råa partitionen (den tredje, t.ex. /dev/sda3 för den råa partitionen ovanpå systempartitionen Slint). I praktiken: skapa inte ett filsystem i denna partition, gör inte det till en del av en RAID array och skriv generellt inte till den: alla data skulle bli oåterkalleligt förlorade!
====

För att undvika svaga lösenordsfraser kräver installationsprogrammet att lösenordsfrasen inkluderar:

. Minst 8 tecken.
. Endast icke-accenttecken små och stora bokstäver, siffror från 0 till 9, mellanslag och följande skiljetecken:
+
----
 -" ! " # $% & () * +,-. /: ; < = >? @ [ \ ] ^ _ " { | } ~
----
+
Detta garanterar att även ett nytt tangentbord kommer att ha alla tecken som behövs för att skriva lösenordsfrasen.

. Minst en siffra, en liten bokstav, en stor bokstav och en skiljetecken.

GRUB förutsätter att "us"-tangentbordet används när du skriver lösenordsfrasen. Av denna anledning, om du under installationen använder en annan tangentbordslayout, innan installationsprogrammet frågar efter lösenordsfrasen kommer den att ställa in tangentbordslayouten till "us", och efter att ha spelat in det återställa den till den tidigare använda. I det här fallet kommer installationsprogrammet även att stava varje typ av lösenordsfras, eftersom det kan skiljer sig från den skrivna på tangenten.

Programmet cryptsetup används för att kryptera enheten. För att veta mer skriv in efter installation: +
-----
man cryptsetup
-----
// Speakup
[[Speakup]]
==== Tangentbindningar för skärmläsaren Speakup

Detta kapitel är avsett för användare som behöver en skärmläsare men inte känner till Speakup.

Behåll numlock avaktiverad för att använda Speakup.

CapsLock-tangenten används som en shift-tangent. Till exempel "CapsLock 4" betyder: +
håll ned CapsLock-tangenten som en shift-tangent och tryck på 4.

 Första tangentbindning att komma ihåg:
 PrintScreen         Växla Speakup till/från.
 CapsLock F1         Speakup Hjälp (tryck på mellanslag för att avsluta hjälpen).

 Tangentbindningar för att ändra inställningar:
 CapsLock 1/2        Minska/Öka ljudvolymen.
 CapsLock 5/6        Minska/Öka talhastigheten.

 Tangentbindningar för att granska skärmen:
 Caps Lock j/k/l      Säg Föregående/Nuvarande/Nästa ord.
 Caps Lock k (två gånger)  Stava nuvarande ord.
 Caps Lock u/i/o     Säg Föregående/Nuvarande/Nästa rad.
 Caps Lock y         Säg från toppen av skärmen till läsmarkören.
 CapsLock p          Säg från läsmarkören till botten av skärmen.
// First_steps
[[first_steps_after_installation]]
==== Första steg efter installation

Här är de första uppgifterna att utföra efter installationen

I detta dokument är all text efter ett # tecken kommentarer till de föreslagna kommandona, och skall inte skrivas.

===== Initial programuppdatering

Efter installationen bör systemet uppdateras för att få den senast tillhandahållna versionen av varje programvara, samt ny programvara som tillhandahålls sedan lanseringen av ISO-avbilden. Detta är särskilt nödvändigt om ingen nätverksanslutning var tillgänglig under installationen, som då bara installerade paket som ingår i distributionsmediat, och de kan vara föråldrade.

De flesta kommandon som skrivs nedan kräver administrativ rättighet kopplad till ett specifikt konto som heter 'root', för vilket du har registrerat ett lösenord under installationen.

För att köra ett kommando som "root", skriv först
----
su -
----
ange sedan lösenordet för root och tryck på Enter innan du skriver kommandot.

När du är klar med att utfärda kommandon som 'root', tryck på Ctrl+d eller skriv 'exit' för att få tillbaka din "vanliga användar"-status.

Alternativt kan den användare som är registrerad under installationen och andra medlemmar av typen "wheel" gruppen skriva:
----
sudo <kommando>
----
och sedan också lösenordet för root.

För att uppdatera, skriv som root i en konsol eller en grafisk terminal:
----
slapt-get --add-keys # hämta nycklarna för att autentisera paketet
slapt-get -u # uppdatera listan över paket i paketförråden
slapt-get --install-set slint # hämta de nya paketen
slapt-get --upgrade # hämta de nya versionerna av installerade paket
dotnew # listar ändringarna i konfigurationsfilerna
----
När du kör dotnew, acceptera att ersätta alla gamla konfigurationsfiler med nya. Detta är säkert eftersom du inte gjort någon anpassning ännu.

Alternativt kan du använda dessa grafiska front-ends: gslapt istället för slapt-get och dotnew-gtk istället för dotnew.

För att lära dig mer om slapt-get, skriv:
----
man slapt-get
----
eller som root:
----
slapt-get --help
----
och läs /usr/doc/slapt-get*/README.slaptgetrc.Slint

// Usage
== Slint användning

Detta kapitel presenterar hur du kan interagera med ditt Slint-system för att få att gjort vad du vill.

=== Vad är ett Slint-system?

Slint är en uppsättning programvara som ungefär faller in i dessa kategorier:

* Operativsystemet, gjort av Linux <<kernel,kärnan>> och <<utility,verktyg>>. Det fungerar som ett gränssnitt mellan användaren, programmen och hårdvaran.
* <<program, Program>> som utför de uppgifter som användarna vill utföra.

Slint kan användas i två lägen som kännetecknas av utseendet på skärmen och sättet att interagera med systemet:

* I textläge skriver du kommandon som tolkas av ett <<shell, skal>>. Dessa kommandon kan starta ett verktyg eller ett program. Textläget kallas också <<console, konsoll>>-läge. I detta läge visar skärmen bara kommandon och deras utdata i en (vanligtvis svart) bakgrund.
* I grafiskt läge visas grafiska element som fönster, paneler eller ikoner på skärmen, vanligtvis associerade till program eller verktyg. Användaren interagerar med dessa element med hjälp av en mus eller ett tangentbord.

Kommandon kan också skrivas i grafiskt läge inuti ett fönster som associeras med en <<terminal, terminal>> där ett skal körs.

=== Verktyg som tillhandahålls

Utöver de verktyg som finns i de flesta Linux-distributioner innehåller Slint verktyg som är skrivna för det, ärvda från Slackware och lånade till Salix.

Här är de verktyg som du kan använda för att (åter)konfigurera ditt Slint system efter installation. De är presenteras mer detaljerat i kapitel <<Manage_your_system, Hantera ditt system>>.

Om inte annat anges bör dessa verktyg användas som root. För att bli root, dvs få 'admin' status och privilegier skriver "su -" och root's lösenord. För att få tillbaka den vanliga användarstatusen tryck Ctrl+d eller skriv exit.

Alternativt kan du köra kommandon som behöver root's privilegier genom att skriva "sudo <kommando>"

De flesta verktyg har en kommandorad och en grafisk version. Kommandorads versionen listas först nedan. Om inget annat anges ska alla kommandon skrivas som root.

*General settings*

* För att hantera användare: usersetup eller gtkusersetup
* Ändra språk och region: localesetup eller gtklocalesetup
* För att ändra tangentbordskonfigurationen och inmatningsmetoden: keyboardsetup eller gtkkeyboardsetup
* För att konfigurera datum, tid eller tidszon: clocksetup och gtkclocksetup.
* För att välja vilka tjänster som startar vid start: servicesetup och gtkservicesetup.
* För att (åter)konfigurera nätverket: netsetup.
* För att välja att starta i text eller grafiskt läge och i det senare fallet den grafiska inloggningshanteraren: login-chooser
* To choose a desktop among FVWM, i3, LXQt, MATE and WindowMaker: session-chooser (as regular user)
* Om du vill välja en av dessa skrivbord eller en fristående fönsterhanterare: xwmconfig (som vanlig användare)
* Visa eller inte visa program som är specifika för ett skrivbord i andra skrivbord: show-desktop eller hide-desktop (som vanlig användare)
* För att aktivera eller avaktivera tal i grafiskt läge: orca-on eller orca-off (som vanlig användare)
* Om du vill välja och aktivera en konsolläsare eller inaktivera dem alla: speak-with
* För att visa eller inte visa startposter som är specifika för MATE och/eller LXQt i andra grafiska miljöer: display-desktop eller hide-desktop (som vanlig användare)
* Aktivera eller inaktivera emacspeak eller speechd-el: switch-on eller switch-off (som vanlig användare)
* För att se layouten för startmenyn GRUB som den visas vid nästa start: list_boot_entries
* För att skapa ett räddnings USB-minne, så att du kan starta om något annat misslyckas: rescuebootstick
* Spara eller återställ inställningarna för speakup: speakup-save eller speakup-restore
* För att lista rösterna för espeak-ng, inklusive mbrola-rösterna: list-espeak-ng-voices (som en vanlig användare)
* För att lista ljudkorten : list-cards (som vanlig en användare)
* För att lista talsynthesizers och tillhörande språk tillgängliga via speech-dispatcher: spd-list (som en vanlig användare)
 
=== Hur Slint startar

Vid installationen installeras programvaran i installationen ISO eller laddas ner från fjärransluten i en <<drive, enhet>>.

När du startar Slint, kontrollerar först <<firmware, firmware>> hårdvaran och söker sedan efter ett program som heter OS-laddare (vanligen benämnd en boot loader) som sen startar.

Det kan finnas flera OS-laddare i maskinen. I detta fall låter den inbyggda programvaran användaren välja vilken som ska startas i en meny.

I Slint är mjukvaran som skapar och installerar en boot loader GRUB. I själva verket boot loader skapad av GRUB är också en starthanterare, som gör det möjligt att välja vilket operativsystem som ska startas om flera är installerade.

OS-laddaren som skapas av GRUB kan installeras i en boot-sektor (i händelse av äldre uppstart) eller i en EFI-systempartition eller ESP (vid EFI-start).

Målet för Slint-inläsningsprogrammet är att starta Slint-systemet. För att göra det laddar den först <<kernel, kärnan>> i RAM-minnet, sedan <<initrd, initrd>>, som i sin tur initierar Slint-systemet.

I det sista steget i denna initiering är användaren inbjuden att "logga in", med andra ord att ansluta sig till systemet och ta hand om det. För att göra det skriver först en användare (eller inloggning) namn sedan lösenord, varav giltighet kontrolleras. Slint som andra Linuxdistributioner är multianvändare denna ger användaren tillgång till ens egna filer men inte andra användares filer.

Vid tidpunkten för installationen valde du att starta Slint i antingen text eller grafiskt läge.

* Om du valde C för <<console, konsol>> efter initiering av systemet skriver du in ditt användarnamn (eller inloggnings namn) sedan lösenordet, varje inmatning bekräftas genom att trycka på Enter tangenten, sen kan du skriva kommandon.
* Om du väljer G (grafiskt) skriver du samma information i en <<display_manager, bildskärmshanterare>> eller inloggningshanterare, som sedan startar den <<graphical_environment, grafiska miljön>>.

Efter installationen, kan du ändra läge genom att skriva som root `login-chooser`, i konsolläge såväl som i grafiskt läge (i en <<terminal, terminal>>). Detta kommando låter dig välja `text` (synonym av konsolläge) eller, för grafiskt läge, bland flera bildskärmshanterare. Ditt val kommer att vara effektivt vid nästa uppstart av datorn.

Vi kommer nu att presentera de grafiska miljöerna, sedan hur man använder ett skal.

=== De grafiska miljöerna

<<the_windows, Fönstren>> +
<<the_work_spaces, Arbetsytor>> +
<<the_desktop, Skrivbordet>> +
<<the_top_panel, Överstapanelen>> +
<<the_bottom_panel, Nedersta panelen>> +
<<the_slint_control_center,Slint kontrollcenter>> +
<<graphical_terminals, Grafiska terminaler>> +
<<key_bindings, Tangentbindningar>>

En fullfjädrad grafisk miljö innehåller flera komponenter, bland vilka en fönsterhanterare som ritar fönster på skärmen i samband med program, flytta, ändra storlek och stänga dessa fönster.

Slint includes several graphical environments: BlackBox, Fluxbox, FVWM, i3, LXQt, MATE, TWM, and WindowMaker. It is a matter of preference which one you choose.

LXQt MATE and XFCE are are full featured desktops, FVWM and WindowMaker offer unique features and can be selected with the graphical lightdm login as well and also started from a console typing "startx". The other ones are mainly window managers that can only be started from a console. All allow you to access your documents and applications, generally opened in a window.

You can choose among FVWM, i3, LXQt, MATE and WindowMaker typing as regular user `session-chooser`. In Graphical mode you also can choose one when logging in.

To choose one of the other graphical environments you need to use the command "xwmconfig".

[NOTE]
====
if you want to use i3 and need speech we recommend that you login in text mode and run **i38** before **startx**.
====

Vi kommer nu kort att beskriva komponenterna i Mate skrivbordet, som är standard och är också det mest tillgängliga med tal och brailleskrift.

Med hjälp av musen kan du upptäcka vad funktionerna i varje komponent gör eller simulera en höger, mitten eller vänster klick. Flytta eller ta bort de flesta komponenter, ändra dem och lägga till nya kan göras på samma sätt.

Dessa komponenter kan nås genom att flytta musen och även via kortkommandon. Vi anger nedan inom parentes tangentbordskommandon som gör det möjligt att nå, med andra ord placera fokus på varje element. Vi kommer också att sammanfatta <<key_bindings, tangentbindningar>> för Mate-skrivbordet (med hjälp av standard Marco windows-hanterare) och de som gäller för Compiz Windows Manager.

[TIP]
====
Du kan upptäcka de flesta funktioner i program och andra komponenter i Slint med en höger, mitten, eller vänsterklick på musen. Till exempel genom att klicka på panelen, namnlisten, vänster och höger knappar i alla fönster, en ikon i panelen eller på ett tomt utrymme på skärmen.
====
[[the_windows]]
==== Fönster

Ett fönster är ett rektangulärt område som associeras med ett program. Fönster kan flyttas, storleksändras, maximeras, återställa, minimeras, stängas (avsluta programmet den hanterar) med musen eller kortkommandon.

[[the_work_spaces]]
==== Arbetsytor

För att tillåta att många fönster öppnas på ett ordnat sätt, ger den grafiska miljön flera arbetsytor och möjlighet att växla mellan dem. Varje arbetsyta kommer att visa samma skrivbord och paneler, men fönster kan placeras i specifika arbetsytor eller i alla. Denna inställning är tillgänglig med ett högerklick på den övre kanten av fönstret. Växla till en annan arbetsyta kan göras genom att klicka på dess position på den nedre panelen av skärmen, i arbetsytans växlare, som anges nedan.

[[the_desktop]]
==== Skrivbordet

Skrivbordet omfattar hela skärmen, på vilka andra komponenter kan sättas, i fallet med Mate som levereras i Slint finns en topp och en nedre panel, och fyra ikoner som uppifrån och ner tillåter att öppna i fönster:

* rotkatalogen i filhanteraren
* din hemkatalog i filhanteraren
* slint Control Center
* papperskorgen, där placeras filer som du tänker ta bort men inte gjort ännu.

Fönster av program du startar som också visas på skrivbordet.

Mate innehåller två paneler, som visar sig som små, rektangulära horisontella områden, en överst och en längst ner på skärmen.

Genom att trycka på Ctrl+Alt+Tab kan du växla mellan skrivborden, översta och nederst panelerna

Tryck på Alt+Tab gör det möjligt att växla mellan fönstren på skrivbordet.

[[the_top_panel]]
==== Den översta panelen

Den presenterar, från vänster till höger:

* Tre menyer:
** En programmeny som kan öppnas genom att trycka på Alt+F1. Därifrån kan du öppna de andra menyerna med hjälp av högerpilen. Du kan navigera i varje meny med hjälp av piltangenterna och upp- och ner-piltangenterna.
** En platsmeny.
** En System-meny som ger tillgång till inställnings-undermeny, Mate Control Center och knappar för att få hjälp om skrivbordet, låsa skärmen, stänga sessionen och stänga av datorn.
* Programstartare för mate-terminal, filhanteraren caja, E-postklienten thunderbird, webbläsaren firefox, textredigeraren Geany.
* En aviseringsyta som kan samla in applets som Bluetooth-hanterare, ljudmixer, nätverkshanterare och en "uppdatering tillgänglig" avisering.
* En klocka och kalender.
* Ett skärmlås.
* En dialogruta för att stänga sessionen.
* En avstängningsdialog.

[TIP]
====
* Anpassa panelen efter dina önskemål: högerklicka på ett tomt utrymme på panelen.
* Om du vill flytta ett objekt på panelen: Mitt-klicka på elementet, dra musen, och det kommer att följa musen tills mittknappen släpps.
* För en kontextuell hjälp tryck på F1
====

[[the_bottom_panel]]
==== Den nedre panelen

Den presenterar, från vänster till höger:

* En fönsterlista som kan konfigureras med ett högerklick på raden av tre vertikala prickar i början och välja inställningar. Detta gör det också möjligt att starta systemmonitorn i ett fönster.
* En *visa skrivbordet*-knapp. Ett vänsterklick på den kommer att minimera eller dölja alla fönster, klicka igen kommer att återställa fönstren i sitt tidigare tillstånd.
* En växlare dör arbetsytor eller pager. Det gör det möjligt att växla från en arbetsyta till en annan och även att flytta fönster från en arbetsyta till en annan genom att dra och släppa.

[[the_slint_control_center]]
==== Slint Control Center

Vi kommer att avsluta denna introduktion till Slint's användning genom att presentera Slint Control Center. Du kan visa den från programmenyn på den övre panelen eller klicka på ikonen på skrivbordet eller skriva qcontrolcenter i en "Kör..." dialog aktiverad med Alt+F2

Målet med kontrollpanelen är att samla in program som är användbara för systemadministration, dokumentation och inställningar på ett konsekvent sätt i alla fönsterhanterare. Genom att klicka på en kategori i den vänstra menyn kan du visa motsvarande program i den högra rutan. Vi kommer att presentera dem i tabellformat. Detta kommer att ge oss möjlighet att presentera de administrativa verktyg som har ett grafiskt användargränssnitt också.

De flesta administrativa verktyg bör användas med administrativa privilegier. Du kommer att bli ombedd om root-kontots lösenord för att starta ett verktyg.

[options="autowidth"]
|====
<|**Kategori:** <|**Verktyg** <|**Syfte och kommentarer**
<|Program <|Dotnew <|Detta verktyg låter dig hantera de nya (som heter __something.new__ därav verktygets namn) kontra gamla konfigurationsfiler efter att ha uppgraderat några paket. Det är en god vana att köra den efter en uppgradering. Den kommer att berätta om det finns något att ta hand om och sedan presentera ett val av åtgärder.
<|Program <|Gslapt Package Manager <|Gslapt är ett grafiskt gränssnitt för slapt-get. Det är ett praktiskt verktyg för att utföra <<software_management,programvaruhantering i Slint>>. Det låter dig söka efter, installera, ta bort, uppgradera och konfigurera mjukvarupaket.
<|Program <|Sourcery SlackBuild Manager <|Sourcery är ett grafiskt gränssnitt till slapt-src. Det låter dig söka efter SlackBuilds-skript som det sedan kan använda för att automatisera byggprocessen och installationen av mjukvarupaket. Det kan också ta bort och installera om paket på ditt system.
<|Program <|Programstartare <|Hitta och starta de program som är installerade på ditt system. Sökfältet är mycket praktiskt för att hitta applikationer i jämförelse med att manuellt söka i programmenyn.
<|Information <|SlackDocs hemsida <|Dokumenten i denna wiki är främst avsedda för en Slackware-användare, men många av dem är användbara för en Slint-användare. **Varning:** Vissa av de listade verktygen, som slackpkg, bör **inte** användas i Slint.
<|Information <|Slackware Dokumentation <|Denna dokumentation kan också vara användbar för Slint-användare. Slint är baserat på Slackware.
<|Information <|MATE systemmonitor <|Det här verktyget visar information om systemet, som processer, resursanvändning (RAM, CPU, nätverkstrafik) och filsystemanvändning.
<|Information <|Slint Dokumentation <|Detta ger lokal tillgång till dokument som även finns på Slints hemsida.
<|Information <|Slint Forum <|Personer vars modersmål inte är engelska kan också göra inlägg i de lokaliserade Salix-forumen.
<|Information <|Slint hemsida <|Slint-hemsidan tillhandahåller dokumentation, länkar och ett sätt att hitta ISO och paket.
<|Information <|System Information <|Det här verktyget samlar in information om din dator, såsom dess anslutna enheter (interna och externa), och visar allt på ett ställe. Den kan också göra systembenchmarking.
<|System <|Display boot menu <|Visa layouten för startmenyn så som den kommer att presenteras vid nästa uppstart
<|System <|System klocka <|Detta verktyg låter dig ställa in systemklockan.
<|System <|Tangentbord <|Detta verktyg låter dig ställa in tangentbordslayouten.
<|System <|System Språk <|Med det här verktyget kan du ställa in systemspråk (språk och geografiska särdrag), så att programmen du använder kommer att visa information på detta språk (om tillgänglig).
<|System <|System Klocka <|Det här verktyget låter dig ställa in tidszonen, välja om klockan ska synkroniseras med internetservrar (detta rekommenderas men kräver naturligtvis en internetanslutning), och om inte, ställa in datum och tid.
<|System <|System Tjänster <|Detta verktyg låter dig välja vilka tjänster som ska aktiveras vid uppstart. Till exempel Bluetooth, CUPS-skrivarservern eller en webbserver. Använd den bara för att ändra standardinställningarna om du vet vad du gör.
<|System <|Användarfe och grupper <|Detta verktyg låter dig lägga till, ta bort och konfigurera användarkonton och grupper. Det är mest användbart på fleranvändarsystem.
<|System <|GUEFI starthanterare <|Detta verktyg är ett grafiskt gränssnitt för kommandot efibootmanager. Det tillåter redigering av EFI-firmwarens startmeny med åtgärder som att lägga till, ta bort objekt eller ändra menyalternativens ordning.
<System <|Rescue boot stick <|Detta verktyg gör det möjligt att sätta i ett USB-minne med allt som behövs för att starta Slint om det inte är möjligt på vanligt sätt

|====

[[graphical_terminals]]
==== Terminaler

Du kan skriva kommandon i grafiskt läge som i konsolläge, om du öppnar ett terminal-fönster. I Mate kan du bara trycka på Ctrl+Alt+t, eller klicka på på mate-terminalikonen på den övre panelen, eller öppna en "Kör... " dialogruta genom att trycka Alt+F2 och sedan skriva `mate-terminal` i det lilla fönstret som öppnas.

Merparten av informationen nedan om kommandoraden och skalet i konsoll gäller även för att skriva kommandon i en terminal. Du kan stänga mate-terminal genom att trycka på Alt+F4 som med alla andra fönster.

[[key_bindings]]
==== Kortkommandon

Vi presenterar här standard kortkommandon för Compiz fönsterhanteraren och Mate skrivbordet, och hur man anpassar dem.

[NOTE]
====
När ett kortkommando innehåller en eller flera *+* tecken, Tryck på och håll från vänster till höger tangenterna innan den sista som en `Shift` tangent, tryck sedan på den sista tangenten.
====
===== Tangentbindningar för Mate-skrivbordet

Vid användning av Mate i Slint är vissa kortkommandon desamma med antingen Marco eller Compiz fönsterhanteraren. De listas nedan:
----
Alt+Tab Växlar mellan fönster
Shift+Alt+Tab Växlar bakåt mellan fönster
Control+Alt+Tab Växla mellan paneler och skrivbordet
Shift+Control+Alt+Tab Växla bakåt mellan panelerna och skrivbordet
----
Väl i en grafisk miljö kan du växla mellan den och en konsol. Låt oss säga att du vill använda tty2 (tty1 är upptagen): Tryck på `Ctrl+Alt+F2`, och logga in. +
Tryck på `Alt+F7` för att gå tillbaka till den grafiska miljön.

Samma allmänna kortkommandon används i alla grafiska miljöer, med några få undantag, Mod1 är generellt sett den vänstra Alt-tangenten: +
----
Mod1+F1 visar panelens programmeny.
Mod1+F2 visar en "kör..." dialog, men i Fluxbox (startar lxterminal istället).
----
Även i Fluxbox:
----
Mod1+F3 startar om Fluxbox.
Mod1+F4 stänger det fokuserade fönstret.
----

I Mate kan delvis synskadade användare använda fönsterhanteraren Compiz i stället eller Marco, som är standard.

Som en vanlig användare, skriv:
----
gsettings set org.mate.session.required-components windowmanager compiz
----
För att gå tillbaka till marco:
----
gsettings set org.mate.session.required-components windowmanager marco
----
Denna inställning kommer att träda i kraft vid nästa start av en Mate-session.

Eller för att göra ändringen bara för den aktuella sessionen skriv:
----
compiz --replace &
----
och för att gå tillbaka till marco:
----
marco --replace &
----
Utbytet kommer att träda i kraft omedelbart.

Denna inställning är också tillgänglig grafiskt från mate-tweak, i kategorin fönster.

Du kan komma åt specifika Compiz inställningar genom att skriva:
----
ccsm &
----
===== Tangentbindningar för Compiz fönsterhanterare

I standardinställningarna som visas nedan är tangenterna eller musknapparna namngivna så här:

Super: Windows-tangent +
Button1: Vänster Musknapp (om det används med höger hand) +
Button2: Centrummusknappar, eller klicka med rullhjulet) +
Button3: Höger musknapp (om det används med höger hand) +
Button4: Rullhjul Upp +
Button5: Rullhjul Ner Button6: (Jag vet inte, jag trodde att det var på möss för spelare) +

De standardinställningar som anges nedan efter kategori kan ändras från CCSM. Vi anger det korta namnet på insticksprogrammet mellan hakparenteser.

. Kategori Allmänt
+
[core] Allmänna alternativ, tab "key bindings": +
close_window_key = Alt+F4 +
raise_window_button = Control+Button6 +
lower_window_button = Alt+Button6 +
minimize_window_key = Alt+F9 +
maximize_window_key = Alt+F10 +
unmaximize_window_key = Alt+F5 +
window_menu_key = Alt+space +
window_menu_button = Alt+Button3 +
show_desktop_key = Control+Alt+d +
toggle_window_shaded_key = Control+Alt+s +
+
[matecompat] Mate-kompatibilitet +
main_menu_key = Alt+F1 +
run_key = Alt+F2 +

. Kategoritillgänglighet
+
[addhelper] Dim inaktiv (mindre ljus på icke fokuserade fönster) +
toggle_key = Super+p +
+
[colorfilter] (Filterfärg för tillgänglighetssyften) +
toggle_window_key = Super+Alt+f +
toggle_screen_key = Super+Alt+d +
switch_filter_key = Super+Alt+s +
+
[ezoom] Förbättrad Zoom Skrivbord +
zoom_in_button = Super+Button4 +
zoom_out_button = Super+Button5 +
zoom_box_button = Super+Button2 (zooma ut för att gå tillbaka till normal) +
+
[neg] Negativ (växla inverterade färger i fönstret eller skärmen) +
window_toggle_key = Super+n +
screen_toggle_key = Super+m +
+
[obs] Opacitet, ljusstyrka och mättnadsjusteringar +
opacity_increase_button = Alt+Button4 +
opacity_decrease_button = Alt+Button5 +
+
[showmouse] (Öka synligheten för muspekaren) +
initiera = Super+k +

. Kategori Fönsterhantering
+
[move] Flytta fönster +
initiate_button = Alt+Button1 (håll knapp1 vid förflyttning av musen) +
initiate_key = Alt+F7 (Esc för att sluta flytta) +
+
[resize] Ändra storlek på fönster +
initiate_button = Alt+Button1 (håll knapp1 vid förflyttning av musen) +
initiate_key = Alt+F7 (Esc för att avsluta) +
+
[switcher] Applikationsväxlare (växla mellan fönster eller paneler och
                                 skrivbordet) +
next_window_key = Alt+Tab (växla mellan fönster) +
prev_window_key = Shift+Alt+Tab +
next_panel_key = Control+Alt+Tab (växla mellan panelerna och skrivbordet) +
prev_panel_key = Shift+Control+Alt+Tab +

===== Hur du lägger till en anpassad tangentbindning för Mate.

Låt oss ta ett exempel: vi vill att Alt+F3 startar firefox. skriv in i en terminal eller i kommandot Kör (hämtas upp genom att trycka på Alt+F2):
----
mate-keybinding-properties
----
I det nya fönstret kan du använda ned- och uppåtpiltangenterna för att navigera i listan över befintliga tangentbindningar.

För att ställa in en ny tangentbindning, tryck på Tab två gånger för att sätta markören på Lägg till, och tryck sedan på Enter. I den lilla dialogrutan skriv namnet på anpassad tangentbindning, som firefox, tryck på Tab, skriv namnet till det associerade kommandot, i detta fall firefox, tryck sedan på fliken två gånger för att sätta markören på Verkställ och tryck på Enter.

För att aktivera den nya tangentbindningen, navigera tills du hittar den på längst ner i listan, tryck på Enter tryck sen på Alt+F3.

Nästa gång du trycker på Alt+F3 ska firefox starta

=== Skalet

NOTE: Detta kapitel är en kort introduktion. Mer fördjupad information finns i dokumentet https://slint.fr/doc/shell_and_bash_scripts.html[Shell och bash scripts], mestadels lånad från SUSE.

När datorn startar i konsolläge, efter att ha loggat in med ditt användarnamn och lösenord, visas ett <<shell,skal>> en "prompt" som den nedan: +
'didier@darkstar: ~ $' +
I det här exemplet:

* `dididier` är användarnamnet
* `darkstar` maskinnamnet
* tilde `~` representerar hemkatalogen för användaren, i detta exempel `/home/didier`
* dollartecknet `$` indikerar att användaren är en "vanlig" inte en "superanvändare" (se nedan).

Markören är placerad efter prompten.

Användaren kan nu skriva ett kommando på raden (och därav namnet "kommandorad") och bekräfta med att trycka på Enter. Skalet analyserar sedan kommandot och kör den om det är giltigt, annars kommer ett meddelande som till exempel "kommandot finns inte". Du kan redigera kommandot innan du trycker på Enter med vänster-och högerpilarna och tangenterna Backspace, Home, End och Del.

Under dess utförande kan kommandona visa en utmatning på skärmen eller inte. I alla fall efter dess utförande kommer prompten att visas igen i en ny rad, vilket innebär att skalet väntar på att nästa kommando ska skrivas.

För att detta ska fungera behöver användaren veta vilka kommandon som är tillgängliga och deras syntax. Vissa kommandon körs av själva skalet, andra startar externa program. Vi kommer att nedan ge flera exempel på kommandon, fler listas i https://slint.fr/doc/shell_and_bash_scripts.html[Shell och bash skript]

Det finns flera skal tillgängliga för Linux att välja mellan; i Slint är skalet som används som standard *bash*.

För att kunna köra flera program samtidigt tillhandahåller Linux flera "virtuella konsoler" och delar sedan samma tangentbord och skärm, numrerade från en. Inledningsvis startar systemet i konsolen (eller virtuell terminal) nummer ett även kallad *tty1* (namnet är en förkortning av "teletype"). Därifrån användaren kan växla till en annan konsol eller tty; till exempel byta till ganska nummer två trycker Alt + F2, där ett annat skal kommer att fråga igen användaren's användarnamn och lösenord. För att växla tillbaka till tty1, tryck bara på Alt + F1. Som standard i Slint sex tty är tillgängliga men detta kan ändras redigera filen /etc/inittab.

När skalet används i en grafisk miljö (i en grafisk terminal), fungerar dess beteende på samma sätt men promten är något annorlunda, vilket illustreras nedan: +
`didier [~] $` +

Du kan växla fram och tillbaka mellan konsolen och en grafisk miljö:

* Från den grafiska miljön trycker du till exempel Ctrl+Alt+F3 för att gå till tty3. Första gången du går till en tty du kommer du att behöva skriva in din inloggning och lösenord.
* Från en konsol eller tty tryck på Alt+F7 om den grafiska miljön redan körs, annars skriva `startx` för att starta den.

==== Skriva kommandon som root

*root* is the conventional name of the "super user" which have all rights to do administrative tasks, including those that could harm or even destroy the system.

Du kan (men detta är inte rekommenderat för nybörjare) logga in direkt som root. För att göra detta skriv *root* som användare, och sedan root-lösenord. För att informera dig (och varna dig för de associerade riskerna och ansvaret) kommer prompten att se ut så här: +
*root@darkstar-#* +
tecknet # (nummertecknet, även kallad hash) anger att kommandona kommer att skrivas som root (inte som vanlig användare), med tillhörande rättigheter, men också risker och ansvar.

Om du redan är inloggad som vanlig användare kan du "bli root" genom att skriva: +
*su -* +
och sedan trycker du på Enter. I det här kommandot är "su" (som står för "Super User") namnet på kommandot, och tecknet *-* (bindestreck-minus, även kallad minus) anger att du öppnar ett "Inloggningsskal": först måste du ange root-lösenordet, och sedan blir du dirigerad till hemkatalogen /root som om du hade loggat in som root vid start. Detta gör att du undvika att oavsiktligt skriva filer i hemkatalogen som vanlig användare (/home/didier i exemplet) som orsakar problem senare.

Den vanliga användaren som är registrerad under installationen och andra användare av 'wheel-gruppen' kan också skriva kommandon som är reserverade för root före namnet på kommandot genom att skriva 'sudo' t.ex.: +
*sudo update-grub*

=== Hur man löser blockeringsproblem

Med "blockeringsproblem" menar vi "ett problem som förhindrar att använda Slint" som:

* Systemet går inte att starta.
* Systemet startar, men uppstartssekvensen avbryts före slutförandet. Detta kan till exempel hända om rootsystempartitionen inte kan monteras på grund av ett fel i /etc/fstab, ett skadat rootfilssystem eller en saknad kärnmodul för att montera rootpartitionen, eller systemet startar framgångsrikt men du kan inte komma ihåg lösenordet för root.

Om systemet helt misslyckas med att starta, prova var och en av lösningarna nedan i sekvens, tills en fungerar.

. Om detta inträffar efter en kärnuppgradering kan du prova den andra startposten istället för den första.
. Försök att starta upp räddnings USB-minnet som du begärde i slutet av installationen.
. Hoppa in i Slint för att reparera den, som förklaras nedan.

Du kan alltid få hjälp genom att mejla slint@freelists.org och tillhandahålla all information som kan hjälpa till att undersöka problemet. Om du inte redan har gjort det kan du först prenumerera på listan med 'subscribe' som ämne på slint-request@freelists.org och svara på det E-postmeddelande som du kommer att få. Endast om du har ett problem med E-post, begär du hjälp i IRC-kanalen #slint, server irc.libera.chat och stanna kvar i kanalen tills någon svarar.

Vi ska nu förklara hur vi ska ta oss till Slint för att reparera den.

<<Start_the_installer,Starta installationsprogrammet och identifiera Slints rotpartition>> +
<<Issue_the_needed_commands,Ge de nödvändiga kommandona för att hoppa in i Slint>>. +
<<Repair_Slint,Reparera Slint från Slint.>>

[[Start_the_installer]]
==== Starta installationsprogrammet och identifiera Slints rootpartition

Om startsekvensen avbryts kan du hoppa in i Slint från installationsprogrammet för att försöka lösa problemet. Mata in eller plugga in installationsmedia (USB-minne eller DVD där du har skrivit ISO-avbilden) följ sedan instruktionerna nedan.

. Starta installationsprogrammet.
. Så snart du är inloggad som root, för att lista enheter och partitioner, skriv:
+
----
lsblk -lpo namn,storlek,fstyp
----
. Hitta i utmatningen namnet på Slint rootpartition, kontrollera dess storlek och filsystem typ, märkt FSTYPE.
. Montera denna partition
+
----
mount /dev/sda3 /mnt
----
+
[NOTE]
====
Om Slints rotfilsystem är btrfs (som anges av utmatningen från "lsblk") måste du montera den med de alternativ som anges i dess /etc/fstab.

I det här fallet måste du använda samma alternativ som i Slint på btrfs, så skriv i stället:
----
mount /dev/sda3 /mnt -o subvol=/@,compress=zstd:3
----
====
. Kontrollera att partitionen är den rätta. Till exempel om den är /dev/sda3, skriv:
+
----
cat /etc/mnt/etc/slint-version
----
+
Förutsatt att du installerade Slint64-15.0 ska utmatningen vara: *Slint 15.0 *
+
Om utdata är "filen hittades inte" är partitionen inte den du letade efter. Endast i detta fall, skriv:
+
----
umount /mnt
----
+
prova sedan en annan, gå tillbaka till listan över enheter och partitioner.

[[Issue_the_needed_commands]]
==== Kör nästa kommando för att "hoppa in i" din Slint

. montera filsystemen /proc /sys och /dev genom att skriva:
+
----
mount -B /dev /mnt/dev
mount -B /proc /mnt/proc
mount -B /dev /mnt/sys
----
+
. Kör nästa kommando för att "hoppa in i" Slint och montera alla enheter som nämns i dess /etc/fstab:
+
----
chroot /mnt
mount -a
----

[[Repair_Slint]]
==== Reparera Slint från Slint

Från Slint kan du ändra systemet för att lösa problem. Här är några exempel:

* Kör "update-grub". +
* Kör "grub-emu" eller "list_boot_entries" +
* Installera om GRUB med kommandot "grub-install drivename", drivename är var du skall installera Slint. +
* Skriv "passwd" för att ändra lösenordet för root. +
* Ta bort, installera eller uppgradera paket.

. Ta bort installationsmedia när du är klar, skriv sedan:
+
----
exit
reboot
----

[[Accessibility]]
== Tillgänglighet

Om du väljer att behålla tal när du blir tillfrågad vid den första installationen, kommer den att aktiveras från uppstart i en konsol som i grafiska miljöer.

=== Använd slint med brailleskrift

Slint innehåller brltty programvara för att hantera punktskriftsskärmar.

Dina inställningar, gjorda innan du startar på kommandoraden eller senare, registreras i det installerade systemet i /etc/brltty.conf.

En omfattande manual för brltty finns på engelska, Franska och Portugisiska i flera format inklusive ren text (txt) på denna URL: https://mielke.cc/brltty/doc/Manual-BRLTTY/

Om punktskrift inte har aktiverats under installationen eller har inaktiverats, kan du aktivera den så här:

. Gör /etc/rc.d/rc.brltty körbar genom att skriva som root:
+
----
chmod 755 /etc/rc.d/rc.brltty
----
. Gör dig själv medlem i punktskriftsgruppen, skriv som root:
+
----
usermod -G braille -a användarnamn
----
+
I kommandot ovan, ersätt användarnamn med ditt inloggningsnamn.

För att inaktivera punktskriftstyp skriv som root:
----
chmod 644 /etc/rc.d/rc.brltty
----

=== Tal i grafiska miljöer

Som en påminnelse tal i grafiska miljöer med hjälp av Orca skärmläsaren aktiveras genom att skriva:
----
orca-on
----

För att veta hur man använder Orca, inklusive dess specifika tangenbindningar, skriv:
----
man orca
----

Kort sagt, i en grafisk miljö:
----
Insert+Space: display the Orca Preferences dialog.
Insert+S: activate or deactivate the vocal synthesis.
Insert+H: activate the learning mode. In this mode:
   Press a key to hear its function
   F1: to hear the documentation of the screen reader
   F2: list the keyboard shortcuts for Orca
   F3: list the keyboard for the current application
   Esc: end of the learning mode
----

=== Röster och TTS i Slint.

Följande TTS (text till talsynthesizers) skickas med i Slint64-15.0.2, var och en med en uppsättning röster, nämligen: +
espeak-ng +
flite +
pico +
mbrola +
RHVoice +

För det mesta hanteras dessa TTS och tillhörande röster och språk av tal-förmedlare genom dess så kallade "moduler" (ungefär, en modul är kopplad till en TTS).

Det anpassade verktyget spd-list kan svara på flera frågor om tillgängliga synthar, röster och språk. Att skriva spd-list visar detta:
----
Detta skript listar språk och synthesizer tillgängliga för program som
förlitar sig på Speech Dispatcher, som Orca eller speech-up. Varje kommando nedan svarar på frågan efter den.
Skriv inte citationstecken som omger kommandot.
"/usr/bin/spd-list" usage?
"/usr/bin/spd-list -s" tillgängliga synthesizers?
"/usr/bin/spd-list -l" tillgängliga språkkoder?
"/usr/bin/spd-list -ls <synthesizer>" språk tillgängliga för denna synthesizer?
"/usr/bin/spd-list -sl <language code>" synthesizer ger röster på detta språk?
Språkkoden har oftast två tecken, som 'en' 'es' eller 'fr'
----
Alla röster som anges finns i Orca och speechd-up, och även fenrir om konfigurerad att använda speech-dispatcher.

Du kan få ytterligare röster för flite och mbrola, associerade med modulerna flite-generic och espeak-ng-mbrola-generic.

Du kan alltid få veta vilka som är installerade eller inte genom att som root skriva ett av dessa kommandon:
----
slapt-get --search mbrola-voice
slapt-get --search flite-voice
----
installera sedan en av de ännu inte installerade, som t.ex.
----
slapt-get -i mbrola-voice-it2
----
Förutom de fria (som i fri öl) röster som levererades i Slint, kan du köpa röster för: +
voxin, https://oralux.org/voice.php +
voxygen, genom att skicka ett E-postmeddelande till contact@hypra.fr

Fler röster och syntar kan göras tillgängliga senare, detta kommer att tillkännages på Slint sändlistan och denna http://slackware.uk/slint/x86_64/slint-15.0/ChangeLog.txt[ChangeLog]

Kortkommandona för grafiska miljöer listas i <<key_bindings, Kortkommandon>>.

=== Använd lightdm-inloggningshanteraren med tal

I lightdm, tryck F4 för att växla ljud på eller av. Till en början är markören i lösenordsfältet. Ett tryck på Tab leder till "login tryckknappen", sedan till användaren's lista eller "combo box". I denna lista visas den valda användaren genom att trycka på mellanslag. Använd piltangenterna för att välja en annan och skriv sedan in motsvarande lösenord. Väljer du istället "Annat..." läggs ett fält till där du kan skriva in inloggningsnamnet för en icke listad användare. Fortfarande i lightdm, F10 tar upp en meny som gör det möjligt att starta om eller stänga av, och Alt+F4 tar upp ett användargränssnitt direkt med avstängnings- eller avbrytningsknappar.

=== Välj en skärmläsare för konsolen

Slint tillhandahåller dessa konsolskärmsläsare: +
espeakup +
speehchd-up +
fenrir

Dessutom kan flera talsynthesizers användas i konsolläge, med hjälp av speakup.

För att välja en skärmläsare kör du som root detta kommando:
----
speak-with
----
Här är resultatet utan argument:
----
root[~]# speak-with
Usage: /usr/sbin/speak-with <screen reader> eller <hard synthesizer> eller ingen
Välj en skärmläsare att prata med från följande:
  espeakup (Konsol-skärmläsare som ansluter till espeak-ng och speakup)
  fenrir (Modulär, flexibel och snabb skärmläsare för konsoler)
  speechd-up (Konsol-skärmläsare som ansluter till Speech Dispatcher och speakup)
eller använda en av de stödda hårdvaru synthesizers.:
  acntsa apollo audptr bns dectlk decext ltlk soft spkout txprt
eller skriv "/usr/sbin/speak-with none" för att stänga av alla skärmläsare.
root[~]#
----
De hårdvaru-talsynthesizers som listas är de som finns i den körande kärnan eller levereras som moduler.

Exempel på kommandon och tillhörande utdata:

----
root[~]# speak-with speechd-up
Starting speechd-up
Should speechd-up be also started at next boot? [Y/n]
OK
root[~]# Done.
----
Så snart du skriver kommandot kommer den tidigare använda skärmläsaren att stoppas och speechd-up börjar prata.

Om du svarar Y (standard) till frågan: +
Should speechd-up be also started at next boot? +
spechd-up will continue to be used at next boot. +
Om du i stället svarar n komer den skärmläsare som används innan du skrev speak-with speechd-up, att användas efter nästa start.

Andra exempel:

----
root[~]# speak-with apollo
Stopping speechd-up...
Should apollo be also used at next boot? [Y/n]
OK
root[~]# Done.

root[~]# speak-with no
Vill du också ha en tystningskonsol vid nästa start? [Y/n]
OK
root[~]#
----

=== Konfigurera en skärmläsare i konsolen.

Slint hantera talmaskinvarusyntar med hjälp av speakup och ger espeakup och speechd-up talskärmsläsare.

Du kan spara de inställningar du gör, till exempel för att öka eller minska talhastigheten eller ljudvolymen. Skriv bara som root: speakup-save. Detta sparar alla aktuella inställningar, inklusive de som är specifika för den hårdvarusynthesizer som används, om det inträffar.

Alla dessa inställningar kommer att återställas vid nästa start: startskripten rc.espeakup och rc.speakd-up kör kommandot speakup-restore åt dig.

Om du inte vill återställa de sparade inställningarna, skriv som root: +
chmod -x /usr/sbin/speakup-restore

Om du vill att de ska återställas igen skriv som root: +
chmod + x /usr/sbin/speakup-restore

Här är några tangentbindningar för inställningar av speakup och speechd-up:
----
spk_f9   punctuation_level_decrease
spk_f10   punctuation_level_increase
spk_f11   reading_punctuation_decrease
spk_f12   reading_punctuation_increase
spk_1   volume_decrease (fungerar inte med speechd-up)
spk_2   volume_increase (fungerar inte med speechd-up)
spk_3   pitch_decrease (fungerar inte med speechd-up)
spk_4   pitch_increase (fungerar inte med speechd-up)
spk_5   rate_decrease
spk_6   rate_increase
----
I tabellen ovan är spk högtalartangen CapLock, eller Ins/0 på en numerisk knappsats. Till exempel för att öka hastigheten kan du trycka på och hålla CapsLock knappen nertryck sedan på 6 knappen.

Vissa inställningar är endast tillgängliga på specifika maskinvarusynthesizers har inte associerade tangentbindningar. För att sedan sätta ett nytt värde upprepar du det i /sys/accessibility/speakup/<synth>/<parameter>

Till exempel för att ändra rösten som används av en apollo 2 kan du skriva: +
echo 2 > /sys/accessibility/speakup/apollo/voic

speakup-save kommer också att spara denna inställning.

Caveat: Jag har aldrig använt ett maskinvaru talsynthesizer, så förklaringen nedan är endast ett antagande baserat i drivrutinen för speakup_apollo, som överensstämmer med handboken, som finns i: +
https://archive.org/stream/DolphinApollo2Manual/Dolphin_Apollo_2_Manual_djvu.txt

[[desktop_keys]]
==== Speakup skrivbordstangenter

Nästan alla tangenter som anges nedan finns på den numeriska knappsatsen. Ins eller 0 på knappsatsen fungerar som en skiftnyckel. Till exempel, Ins 2 betyder "håll ner Ins tangenten som en skifttangent och tryck på 2". Behåll numlock från för att använda Speakup.

Omfattning: dessa viktiga tangentbindningar kan användas med hårda synthesizers och med espeakup, och även med speechd-up.

Första tangenter att komma ihåg:
----
PrintScreen    Växla speakup på/av
Ins F1         Speakup Hjälp (tryck på mellanslag för att avsluta hjälpen)
----

Tangenter som används för skärmgranskning:
----
1/2/3          Säg Föregående/Aktuell/Nästa tecken
Shift PageUp   Säg första tecknet
Shift PageDown Säg sista karaktären
4/5/6          Säg Föregående/Aktuell/Nästa ord
5 2gr           Stava nuvarande ord
Ins 5          Stava aktuellt ord fonetiskt
7/8/9          Säg Föregående/Aktuell/Nästa rad
Ins 4          Säg från radens vänstra kant till läsmarkören
Ins 6          Säg från läsmarkören till höger kant av raden
Ins 8          Säg från toppen av skärmen till läsmarkören
Ins plus       Säg från läsmarkörraden till botten av skärmen
plus           Säg hela skärmen.
Ins r          Säg alla dokument
punkt        Säg position
Ins punkt     Säg attribut
Ins minus      Säg tecken hex och decimalvärde.
minus          Parkera läsmarkören (växla)
Ins 9          Flytta läsmarkören till toppen av skärmen (insert pgup)
Ins 3          Flytta läsmarkören till botten av skärmen (insert pgdn)
Ins 7          Flytta läsmarkören till vänster kant av skärmen (insert home)
Ins 1          Flytta läsmarkören till höger kant av skärmen (insert end)
Control 1      Flytta läsmarkören till sista tecknet på aktuell rad.
asterisk       Växla markören
Ins asterisk   n<x|y  gå till rad (y) eller kolumn (x). Där 'n' är
               tillåtet värde för raden eller kolumnen för din nuvarande skärm.
Ins f2         Ställ in fönster
Ins f3         Töm fönster
Ins f4         Aktivera fönster
----

Andra tangenter:
----
Ins f5         Redigera några
Ins f6         Redigera mest
Ins f7         Redigera delim
Ins f8         Redigera upprepa
Ins f9         Redigera exnum

Enter          Håll tyst (tills en annan tangent trycks) och synkronisera läsmarkören.
Ins Enter      Håll tyst (tills växlat tillbaka)

snedstreck          Markera och klipp ut skärmregion.
Ins snedstreck      Klistra in skärmregionen i valfri konsol.
----
==== Speakup laptoptangenter

Dessa tangentbindningar (för amerikansk tangentbordslayout) behöver inte en numerisk knappsats. Om du har en, använd <<desktop_keys, speakup skrivbordstangenter>> lättare att använda, speciellt om du använder ett annat tangentbord än US.

CapsLock-tangenten används som en shift-tangent. Till exempel "CapsLock 2" betyder: +
håll ned CapsLock-tangenten som en shift-tangent och tryck på 2.

Omfattning: dessa viktiga tangentbindningar kan användas med hårda synthesizers och med espeakup, och även med speechd-up.

Första tangenter att komma ihåg:
----
PrintScreen          Växla speakup på/av
CapsLock F1          Speakup Hjälp (tryck på mellanslag för att avsluta)
----

Tangent som används för skärmgranskning:
----
CapsLock m/comma/dot Säg Föregående/Aktuell/Nästa tecken
CapsLock PageUp      Säg första tecknet
CpasLock PageDown    Säg sista karaktären
CapsLock j/k/l       Säg Föregående/Aktuellt/Nästa ord
CpasLock k twice     Stava nuvarande ord
CapsLock u/i/o       Säg Föregående/Aktuell/Nästa rad
CapsLock h           Säg från radens vänstra kant till läsmarkören
CapsLock semicolon   Säg från läsmarkören till höger kant av raden
CapsLock y           Säg från toppen av skärmen till läsmarkören
CapsLock p           Säg från läsmarkörraden till botten av skärmen
CapsLock apostrophe  Säg hela skärmen.
Capslock r           Säg alla dokument
CapsLock n           Säg position
CapsLock slash       Säg attribut
CapsLock minus       Säg tecken hex och decimalvärde.
CapsLock f2          Parkera läsmarkören (växla) Set window
CapsLock f3          Töm fönster
CapsLock f4          Aktivera fönster
----
Andra tangenter:
----
CapsLock f5          Redigera några
CapsLock f6          Redigera de flesta
CapsLock f7          Redigera avgränsare
CapsLock f8          Upprepa redigera
Skift CapsLock f9    Redigera exnum
----

=== Få emacs att tala

Du kan använda antingen emacspeak eller speechd-el. För att aktivera eller inaktivera en av dem skriv som vanligt ett av dessa kommandon:

switch-on emacspeak +
switch-on speechd-el +
switch-off emacspeak +
switch-off speechd-el +

Skriv sedan bara: +
emacs

Aktivera en av dessa program inaktiverar den andra.

[[Manage_your_system]]
== Hantera ditt system

[[software_management]]
=== Programvaruhantering i Slint.

<<The_basics,Grunderna>> +
<<Keep_your_system_up_to_date,Håll ditt system uppdaterat>> +
<<Kernel_upgrades,Kärnuppgraderingar>> +
<<Get_additional_applications,Hämta ytterligare program>> +
<<slapt_src,Användning av slapt-src>>

[[The_basics]]
==== Grunderna

I Slint finns programvara i form av paket. Ett paket är ett paket med filer som finns i en komprimerad arkivfil, sammansatt för att tillhandahålla allt som behövs för att köra programvaran. Paket ingår i installations-ISO och lagras i fjärrservrar från vilka de kan laddas ner och installeras. Installera ett paket innebär att extrahera filerna från arkivfilen och kopiera dem till någon katalog i systemet.

Installation och borttagning av programvara registreras i en databas som består av textfiler i dessa kataloger:
----
/var/lib/pkgtools/packages
/var/log/removed_packages
/var/lib/pkgtools/scripts
/var/log/removed_scripts
----
Filerna i /var/lib/pkgtools/packages registrerar information om paketen, huvudsakligen deras innehåll: listan över filer som de innehåller och var de är installerade.

De viktigaste kommandona för att hantera paketen listas nedan. Alla av dem har tillhörande man-sidor.

Dessa kommandon kräver administrativa rättigheter, kopplade till ett specifikt konto som heter "root", för vilket du har angett ett lösenord under installationen av Slint.

För att köra ett kommando som 'root', skriv först su - ange sedan lösenordet för root och skriv kommandot. + eller använd sudo.

Kommandon nedan kan köras från en grafisk terminal eller i en konsol, men gslapt fungerar bara i en grafisk miljö.
----
installpkg # för att installera ett paket som lagras lokalt.
removepkg # för att ta bort ett installerat paket.
upgradepkg # för att ersätta ett installerat paket med ett annat (vanligtvis med samma namn men i en annan version).
slapt-get # för att installera, ta bort, uppgradera paket lagrade i arkiv listade i /etc/slapt-get/slap-getrc
----
Paketen som levereras på installationes-ISO kommer från de arkiv som listas i /etc/slapt-get/slapt-getrc

Gör dig själv en tjänst: läs kommentarerna i /etc/slapt-get/slapt-getrc och /usr/doc/slapt-get-0.10.2t/README.slapgetrc.Slint på det installerade systemet.

Efter att du har installerat Slint, kommer du att underrättas om uppdateringar av installerade paket som kommer från förråd listade i /etc/slapt-get/slapt-getrc

Du kan installera ytterligare paket med kommandot slapt-get eller den grafiska applikationen gslapt, om de lagras i ett arkiv som listas i /etc/slapt-get/slapt-getrc

slapt-get och gslapt tillhandahåller en sökfunktion som hjälper dig att hitta paket.

WARNING: du kan använda slapt-get, gslapt och removepkg för att ta bort installerade paket men ta inte bort paket som levereras i Slint ISO, även om du inte använder dem alls. Att ta bort ett inkluderat paket kommer inte att resultera i någon ökning av prestanda och kan förhindra att andra program körs. Dessutom, om du har lagt till ett paket som inte ingår i Slint kan du ta bort det, men var försiktig med att det borttagna paketet inte är ett beroende av andra som du också har installerat och tänker fortsätta använda.

[[Keep_your_system_up_to_date]]
==== Håll ditt system uppdaterat

Håll ditt system säkert installera de programuppdateringar som tillhandahålls av Slint så snart de är tillgängliga.

Alla uppdateringar visas i ChangeLog: http://slackware.uk/slint/x86_64/slint-15.0/ChangeLog.txt

Efter Slint installation eller någon ändring i filen /etc/slapt-get/slapt-getr kör detta kommando en gång:
----
slapt-get --add-keys
----

För att synkronisera den lokala listan över tillgängliga paket med utvecklingskatalogen körs detta kommando automatiskt varannan timme:
----
slapt-get -u
----
Du kan också köra det manuellt.

Detta kräver naturligtvis att maskinen är ansluten till internet.

För att hämta och installera de uppgraderade eller ombyggda paketen kör följande kommando som root:
----
slapt-get --upgrade
----
Alternativt kan du också använda gslapt, en grafisk front-end för slapt-get.

För att få nya paket listade i ChangeLog som "Added", skriv:
----
slapt-get -i <paketnamn>
----
eller för att se till att du har installerat alla paket som levereras i Slint, inklusive de som lagts till i förrådet efter att du installerat Slint, skriv:
----
slapt-get --install-set slint
----

På skrivborden, visas en liten ikon i meddelandeområdet i en panel (översta panelen i MATE) för att meddela om tillgängliga programuppdateringar. Bara gör en vänsterklick på den och följ instruktionerna som nämns där.

Tänk på att vissa paket är svartlistade i /etc/slapt-get/slapt-getrc, dvs. de kan inte uppgraderas automatiskt eller installeras.

[[Kernel_upgrades]]
==== Kernel uppgraderingar

Nya kärnor tillhandahålls när det behövs, antingen för att få säkerhetsrättelser eller förbättringar.

Vanligtvis ingen manuell intervention från användaren är nödvändig när detta händer, men det kan vara användbart att veta hur uppgraderingen av kärnan görs och vad man ska göra om något oväntat inträffar.

Flera paket inkluderar filer som är associerade med varje kärna, nämligen: kernel-generic, kernel-modules, kernel-source, kernel-headers. kernel-source och kernel-headers inkluderar filer som används för att bygga programvara, endast kernel-generic och kernel-modules behövs för att köra ett Slint-system.

Paketets kärnmoduler skickar filer som kallas moduler, vilka är bitar av kod som är "inkopplade" i kärnan för att tillhandahålla en specifik funktion eller hantera en specifik hårdvara.

Så snart både ett kärnpaket och det tillhörande kärnmodulspaketet är installerat, bygger skriptet /sbin/wrapupgradepkg en <<initrd, initrd>> som är associerad med denna kärna (med moduler tagna från paketet kernel-modules) och installerar den tillsammans med kärnan i katalogen /boot.

Sedan tas tidigare kärnor (ej i bruk vid tidpunkten för uppgraderingen) bort.

Därefter uppdaterar skriptet konfigurationsfilen GRUB /boot/grub/grub.cfg, läst av OS-laddaren för att skapa bootmenyn vid uppstart.

Denna uppstartsmeny kommer sedan att innehålla minst två uppstartsposter, för att indikera en kärna och dess tillhörande initrd att använda. Från toppen:

* En startpost för att starta Slint med den nya kärnan som just har installerats.
* En startpost för att starta Slint med hjälp av kärnan som används vid uppgraderingen.

Detta ger typ av ett "säkerhetsnät" om Slint inte skulle kunna starta med den nya kärnan: i detta fall tryck bara pil ner en gång när uppstartsmenyn visas för att starta Slint med den tidigare kärnan

Du kan förhandsgranska den nya uppstartsmenyn innan du startar om, skriva som root:
----
grub-emu
----
Sedan visas en emulerad eller "falsk" uppstartsmeny, med samma layout som den verkliga som kommer visas vid uppstart.

Du kan navigera i det med ned- och uppåtpiltangenterna för att markera (sätta fokus på) en startpost som du kan visa detaljerna genom att trycka på 'e'. Du kan gå tillbaka till menyn genom att trycka på Escape.

För att avsluta från grub-emu trycker du på c och skriver *exit* och trycker på Enter.

Alternativt kan du skriva som root:
----
list_boot_entries
----

[[Get_additional_applications]]
==== Skaffa ytterligare program

Det enklaste och rekommenderade sättet att få ytterligare program som inte levereras i Slint är att använda slapt-get eller dess grafisk front-end gslapt. Detta ger dig åtkomst till alla paket i förrådet som är aktiverade i /etc/slapt-get/slapt-getrc som standard förutom Slint-förrådet: +

* Slackware-förrådet, med beroendeinformation: SOURCE=https://slackware.uk/salix/x86_64/slackware-15.0/:OFFICIAL
* Salix extraförråd, förrådför Salix distribution av dess utvecklare George Vlahavas alias gapan men användbar i Slint, liksom: SOURCE=https://slackware.uk/salix/x86_64/extra-15.0/:OFFICIAL

Om programmet du vill ha inte är installerat och inte heller tillgängligt i något av de förråd som är aktiverat i /etc/slapt-get/slapt-getrc kan du skapa ett paket för det, användning av byggmaterial från volontärer @ https://slackbuilds.org. För att veta hur du fortsätter, läs https://slackbuilds.org/howto/ och https://slackbuilds.org/faq/

Paketen som byggts på detta sätt bör vara kompatibla med Slint.

Programmen *slapt-src* och dess grafiska front-end *sourcery* låter dig bygga och installera paket med hjälp av byggmaterialet som finns på https://slackbuilds.org, som ska användas som root eller användning av sudo.

Vi kommer att beskriva slapt-src i mer detaljer.

[NOTE]
====
Förbyggda paket för de flesta program som kan byggas med slap-src eller sourcery finns i Salix extra förråd. Installera helst dessa färdiga paket med hjälp av slapt-get eller gslapt, såvida du inte behöver specifika byggalternativ eller en annan version än den som tillhandahålls.
====

[[slapt_src]]
===== Användning av slapt-srcrc

Standardkonfigurationsskriptet för slapt-src är /etc/slapt-get/slap-getrc och har detta innehåll:
----
BUILDDIR=/var/lib/slapt-src
PKGEXT=txz
SOURCE=https://slackbuilds.org/slackbuilds/15.0/
----
Så:

* Allt byggmaterial och paket kommer att hamna i /tmp/slapt-src
* Namnen på paket som byggts slutar med .txz
* Byggmaterialet hämtas från arkivet https://slackbuilds.org/slackbuilds/15.0/

Här är resultatet av kommandot *slapt-src --help*:
----
Användning: slapt-src [option(s)] [action] [slackbuild(s)]
  -u, --update           uppdatera lokal cache av remote slackbuilds
  -U, --upgrade-all      uppgradera alla installerade slackbuilds
  -l, --list             lista tillgängliga slackbuilds
  -e, --clean            rensa byggkatalogen
  -s, --search           Sök tillgängliga slackbuilds
  -w, --show             visa angivna slackbuilds
  -i, --install          hämta, bygga och installera de angivna slackbuild(s)
  -b, --build            hämta bara och bygg de angivna slackbuild(s)
  -f, --fetch            hämta endast de angivna slackbuild(s)
  -v, --version
  -h, --help
 Alternativ:
  -y, --yes              bekräfta inte
  -t, --simulate         visa vad som ska göras
  -c, --config=FILE      Använd den angivna konfigurationsfilen
  -n, --no-dep           leta inte efter beroenden
  -p, --postprocess=CMD  köra det angivna kommandot på genererade paket
  -B, --build-only       gäller endast för --upgrade-all
  -F, --fetch-only       gäller endast för --upgrade-all
----

Låt oss kommentera några av dessa alternativ:

* Använd -u eller --update varje gång för att uppdatera listan över paket som kan byggas och installeras. Detta kommandon skriver filen /tmp/slapt-src/slackbuilds_data, ersätter det tidigare fallet som inträffar.
* Använd -e för att spara utrymme på disken, tar bort de flesta filer i /tmp/slapt-src/
* använd *inte* -U förutom för att lista möjliga uppgraderingar eller nedgraderingar, utan att bekräfta: bekräftandet skulle leda till att ersätta alla Slint-paket med en i en annan version om det finns tillgängligt i fjärranförrådet, eventuellt bryta programvara som inte är kompatibel med denna version.
* -i kan även uppgradera ett paket som redan är installerat från https://slackbuilds.org, om en utvecklare av SlackBuild-skriptet har uppgraderat den, ändrat VERSION-variabeln.
* Använd -f för att endast ladda ner filerna i https://slackbuilds.org för målprogramvaran. Detta kan vara användbart om du vill kontrollera byggmaterial, eller anpassa bygget. Till exempel låt oss antar att du vill hämta byggmaterial för programvaran *mxml*. Kommandot nedan ger lite information om programvaran och vilka filer som lagras i https://slackbuilds.org för det:
+
----
slapt-src --show mxml
SlackBuild Name: mxml
SlackBuild Version: 3.1
SlackBuild Category: libraries/mxml/
SlackBuild Description: mxml (Lightweight xml parsing library)
SlackBuild Files:
 README
 mxml.SlackBuild
 mxml.info
 slack-desc
----
+
Hämta nu dessa filer och även källkodsarkivet från uppströmsförrådet med nästa kommando:
+
----
slapt-get -f mxml
----
+
För att veta från utdata från det tidigare kommandot att filerna lagras i underkatalogens libraries/mxml, kan du kontrollera vilka filer som har laddats ner med detta kommando:
+
----
ls -1 /var/lib/slapt-src/libraries/mxml
mxml-3.1.tar.gz
mxml.SlackBuild
mxml.info
slack-desc
----
* Använd -b om du vill bygga ett paket men inte installera det ännu. I exemplet ovan kommer den att lagras i /tmp/slapt-src/libraries/mxml, så du kommer att kunna installera den efteråt genom att skriva:
+
----
upgradepkg --install-new /tmp/slapt-src/libraries/mxml/xml*txz
----
+
* Använd -c om du vill använda en anpassad konfigurationsfil istället för standardfilen /etc/slapt-get/slap-getrc

=== Hantera användare och grupper.

Två kommandon tillhandahålls för att hantera användare och grupper:

* Kommandot _usersetup_ (TUI)
* Kommandot _gtkusersetup_ (GUI), med en ikon i kategorin Slint Control Center, System)

Dessa kommandon låter dig lägga till eller ta bort användare och grupper av användare och lägga till användare till grupper.

Tänk på att varje användarkonto är associerat som standard till dess på plats i /home katalogen. Till exempel om du lägger till en användare *leonie*, kommer en /home/leonie katalog att skapas, till vilken endast denna användare (och root) kommer att tillåtas att komma åt.

=== Ändra standardspråket i systemet

Det finns två kommandon för det:

* Kommandot _localesetup_ (TUI).
* Kommandot _gtklocalesetup_ (GUI), med en ikon i kategorin Slint Control Center, Inställningar.

Tänk på att inställningarna ändrar språket som används av programmens gränssnitt om de är internationaliserade, inte tangentbordslayouten (se nedan).

Lokaliserade paket (om tillgängligt) som matchar det valda språket har redan installerats i slutet av Slint-installationen. Om du ändrar standardspråket efteråt måste du installera motsvarande lokaliserade paket om du vill.

Lokaliserade betyder "tillhandahållen i en given lokal", att lokalen är ett språk plus egenheter som associeras till ett geografiskt område. Till exempel portugisiska som talas i Portugal och Brasilien skiljer sig åt. I de lokala paketnamnen är l10n en förkortning av "lokalisering" som betyder "bokstaven l, 10 andra bokstäver, bokstaven n".

Lokaliserade paket ingår för många språk. Deras namn inkluderar baspaketets namn, ett bindestreck och sedan språkkoden. Vi listar under basnamnen på de lokaliserade paketen:
[options="autowidth"]
|====
| Baspaketnamn | Beskrivning
| aspell | ordlistor för stavningskontroll
| libreoffice-l0n | localiserade LibreOffice Office-paket
| libreoffice-hjälp | localiserad hjälp för LibreOffice
|====

För att hitta ett lokaliserat paket, skriv i en terminalemulator som root (till exempel för kde-l10n):  +
`spi libreoffice-l10n`

Detta kommer att visa en listan över alla lokala LibreOffice-paket. Hitta den du vill ha och installera den. Till exempel för persiska språket är koden `fa` (kort för Farsi), så att installera det skriv: +
`spi -i libreoffice-l0n-fa`

Om du föredrar kan du använda `gslapt`. Skriv sedan in paketnamnet i sökfältet för att visa alla lokaliserade libreoffice-paket.

=== Ändra tangentbordslayouten

Du kan ändra standard nyckelkarta som används i grafiskt läge med:

* Kommandot _keyboardsetup_ (TUI)
* Kommandot _gtkkeyboardsetup_ (GUI), med en ikon i Slint Control Center, hårdvarukategorin.

Dessa kommandon låter dig också välja om numlock ska aktiveras när systemet startas, och om SCIM (inmatningsmetod) ska aktiveras vid systemstart.

Om du använder en fönsterhanterare med en panel, du kan också göra denna inställning genom ett högerklick på tangentbordet applet (visas som standard som två bokstävers språkkod för tangentbordslayouten i bruk). Kde och Xfce har specifika verktyg för detta.

På kommandoraden men fortfarande för det grafiska läget använd istället `setxbmap`

Till exempel för att ställa in tangentbordslayout till ukrainska i grafiskt läge, skriv bara som vanlig användare: +
`setxkbmap -layout ua`

För att veta mer, läs mansidan för setxkbmap.

=== Installera en skrivare

I Slint hanterar CUPS-skrivarservern skrivare och utskriftsuppgifter. I dess standardkonfiguration, skrivna i filen /etc/cups/cupsd.conf, endast användare som tillhör `sys` (kort för _system_) gruppen är tillåtna att utföra administrativa uppgifter, som att lägga till eller ta bort en skrivare.

För en enkel installation (skrivare ansluten till en stationär eller bärbar dator och inte delad mellan maskiner), behöver du bara lägga till en användare (som kommer att hantera skrivarna) till `sys` gruppen. Till exempel att lägga till användaren _dididier_ till gruppen `sys` kan göras två sätt:

* I konsolläge eller med hjälp av en terminalemulator, bli root med `su` och skriv sedan:
+
`gpasswd --add didier sys`
+
* I grafiskt läge från Slint Control Center klicka på Användare och Grupper (Systemkategori), välj användaren och klicka på Egenskaper, sedan i fliken Grupper kontrollera `sys`. Eller tvärtom (välj gruppen och lägg sedan till användaren i den).

Det finns flera sätt att lägga till och konfigurera en skrivare (detta måste göras av en användare i gruppen `sys`):

* Från Slint Control Center, Kategori Hårdvara, klicka på Printer Setup för att visa ett GUI som tillåter en enkel installation...
* ... Eller klicka på Cups Print Control displayen ett webbgränssnitt till CUPS-servern. Du kan också visa webbgränssnittet till CUPS-servern genom att skriva `localhost:631` i adressfältet för en webbläsare.
* Om du har en Hewlett Packard enhet, gör ett högerklick på *hp* logotypen i meddelandefältet i panelen.

NOTE: För att göra en utskriftsinställning bör CUPS-servern köras. Det startas när du startar Slint om tjänsten `cups` är markerad bland Systemtjänsterna (den är markerad som standard i Slint).

=== Ljudkonfiguration

I Slint skickar program antingen sin ljudutgång till ALSA eller till PulseAudio.

I det senare fallet sänder PulseAudio i sin tur utflödet till en ALSA-mixer som skickar det till ljudkorten.

Som ett resultat, en inställning som en utsignal ljudvolym kan alltid göras av en ALSA-mixer, och även genom en PulseAudio mixer men endast i fall programmet skickar sin ljudutgång till PulseAudio.

Vi kommer nu att presentera programmet som kan användas för att ändra ljudinställningarna

==== pavucontrol (för PulseAudio)

`pavucontrol` står för PulseAudio Volume Control och är en grafisk applikation. Du kan starta den från en terminal eller programmenyn, eller göra ett högerklick på ljudmixerikonen på den övre panelen i Mate. Egentligen tillåter det fler inställningar än bara volymkontrollen, så ta dig tid att utforska alla dess funktioner.

Du kan också använda volymkontrollapplet i panelens meddelandeområde: ett vänsterklick gör det möjligt att justera volymen, ett högerklick ger åtkomst till andra inställningar och gör det möjligt att starta pavukontroll-mixern.

[[Sound_on_the_command_line]]

==== alsamixer (for ALSA)

alsamixer är ett ncursesprogram, vilket ger ett semi-grafiskt användargränssnitt.

För att använda den skriv: i en konsol eller i en grafisk terminal:
----
alsamixer
----
sedan:

* Använd page Up-tangenten för att öka volymen med 5%
* Använd page Down-tangenten för att minska volymen med 5%
* tryck Esc för att lämna programmet.

==== amixer (för ALSA)
Kommandot är av formen:
----
amixer <arguments>
----
Till exempel för att ställa in huvudvolymen till 70% skriv:
----
amixer sset Master 70%
----
För att veta mer, skriv ett av dessa kommandon:
----
man amixer
amixer -h
----
==== sam (Tal-vänlig Alsa Mixer)
sam tillåter val av ljudkortet att fungera på när det finns mer än en sådan enhet i din maskin. +
När det bara finns en, presenterar den direkt de olika mixers för konfiguration.

Alla val, vare sig det är ljudkort, mixers eller en given funktion i en
 specifik mixer väljs genom att bläddra igenom de tillgängliga alternativen med hjälp av upp- och nedpilar, mata sedan in den önskade filen: +
`q` lämna urvalslista och/eller avslut. +
`Shift-q` avslutar programmet var som helst. +
`F1` Visar ytterligare information om tillgängligt.

När namnet på det önskade alternativet är känt, kan man istället trycka på dess första bokstav. Första bokstavs-navigering är skiftläge-okänslig. Det kommer då att ta dig till det första urvalet som börjar med den tryckta bokstaven. Ett tryck på samma bokstav igen, kommer att flytta dig till nästa alternativ som börjar med den bokstaven om mer än ett sådant alternativ finns. Upprepa bokstaven kommer att växla bland alla dessa alternativ som börjar med den bokstaven.

De inställbara funktionerna hos en mixer kan listas genom att trycka på F1. +
De presenteras som en urvalslista, visar kortfattat all relevant information, t.ex. "uppspelningsvolym ner från 84 procent" är alternativet att sänka uppspelningsvolymen. Som du kan se, talar den också om för dig vad nuvarande inställning är.

NOTE: sam fungerar inte korrekt i en grafisk terminal. Använd den i en konsol.

==== pamixer och ponymix (för PulseAudio)
Dessa verktyg är likartade, med kommandon i denna form:
----
pamixer <argument>
ponymix <argument>
----
Till exempel för att ställa in volymen till 70% för standard sink skriv ett av dessa kommandon:
----
pamixer --set-volume 7
ponymix set-volume 7O
----
För att veta mer, skriv:
----
pamixer -h
ponymix --help
----

==== pacmd och paktl (för PulseAudio)

Båda dessa kommandoradsprogram kontrollerar en körande PulseAudio-daemon.

WARNING: pacmd skriven ensam gör att en interaktiv dialog visas. Tryck på Ctrl+d för att avsluta från den, men skriv inte exit, eftersom det skulle döda PulseAudio!

För att få veta mer:
----
man pactl
man pacmd
pactl --help
pacmd --help
----

==== Spara och återställ ljudnivån

Gör filen /etc/rc.d/rc.alsa körbar. Som root skriv:
----
chmod /etc/rc.d/rc.alsa
----
Vid uppstart kommer detta skript att återställa tidigare ljudinställningar om de sparas, annars kommer den att ställa in standardvolymer och lagra dem, så att de kommer att återställas vid nästa omstart.

Om du inte vill att detta skript ska ställa in standardvolym skriv som root:
----
touch /var/lib/alsa/no.asound.state
----

Du kan ändra dessa standard ljudnivåer med alsamixer eller amixer och sedan skriva som root:
----
alsactl store
----
Sedan vid nästa uppstart kommer skriptet att återställa dem.

För att få veta mer:
----
man alsactl
----

=== Nätverkskonfiguration

Om du inte ställde in ditt nätverk under Slint-installationen, bli först root genom att skriva `su -` antingen i en konsol eller i grafisk terminal som mate-terminal, skriv sedan in root-lösenordet.

Konfigurationen av nätverket görs av skriptet `netsetup`. Så du skulle bara skriva kommandot `netsetup` i terminalen, där du har skaffat root-privilegier. Du kommer först att bli ombedd om värdnamnet på din maskin. du kan välja valfritt namn, men tänk på att det måste vara ett enda ord. Sedan blir du tillfrågad om domännamnet. Om maskinen inte är en server kan du välja vad som helst. Därefter kommer du att bli tillfrågad om hur din maskin ansluter till nätverket. Om inte du har en god anledning att inte (och du vet vad du gör), behåll standard `NetworkManager` för att automatiskt konfigurera nätverket.

För trådbundna anslutningar, bör det vara tillräckligt för att automatiskt ansluta vid nästa uppstart.

För att konfigurera en trådlös anslutning finns två kommandon tillgängliga med hjälp av kommandoraden.

Återigen kan du skriva kommandona direkt på konsolen eller i en grafisk terminal som mate-terminal. Skriv dem som vanlig användare inte som root. Om du följde dessa instruktioner och blev root redan, behöver du bara skriva `exit` för att få tillbaka den vanliga användarstatus.

De två nämnda kommandona är `nmtui` (dialogrutor) eller `nmcli` (ren kommandorad), båda är tillgängliga.

Om du föredrar att arbeta på kommandoraden, se till att läsa nmcli dokumentationen först. Skriv bara `nmcli --help` och `man nmcli` för att ta reda på alla detaljer. Medan `nmcli` erbjuder fler möjligheter, i de flesta användningsfall kommer funktionaliteten av `nmtui` räcka för att konfigurera ditt trådlösa nätverk, så vi kommer att beskriva det här:

Genom att använda `nmtui`kan du navigera med Tab och piltangenterna. Du kommer att föreslås tre alternativ: +
`Redigera en anslutning` +
`Aktivera en anslutning` +
`Ange systemvärdnamn` +

Om ingen trådlös anslutning har ställts in ännu väljer du `Aktivera en anslutning`. Med start från topp till botten, först trådbundna anslutningar (om någon) kommer att föreslås, efter det kommer att alla tillgängliga trådlösa nätverk att listas. Navigera med ner och upp piltangenterna för att välja det nätverk du vill, sen trycker du bara på Enter: du kommer förmodligen att bli ombedd om lösenord eller krypteringsnyckel. Skriv den, använd Tab-tangenten för att bekräfta, avsluta och du är klar.

Endast i grafiskt läge, istället för `nmcli` eller `nmtui` kan du använda programmet `nm-connection-editor`.

=== Tjänstkonfiguration

Du kan ändra standardinställningarna på flera sätt:

* Kör kommandot som root `servicesetup` (TUI)
* Endast i grafiskt läge, med hjälp av `gtkervicesetup`, tillgängligt från inställningscentralen, kategori System eller tryck Alt+F2 för att visa en "Kör..."-dialogruta och skriv sen *gtkservicesetup*.
* Som root gör relevant skript körbar (chmod 755 <sökväg till skript> eller icke körbar (chmod 644 <sökväg till skript>). Till exempel för att göra fail2ban körbar skulle du skriva: `chmod 755 /etc/rc.d/rc.fail2ban`

IMPORTANT: Ändra bara standardinställningarna om du vet vad du gör.

Tjänsterna hanteras av skript vars namn börjar med `rc.` i katalogen /etc/rc.d/. Till exempel tjänsten acpi hanteras av skalskriptet /etc/rc.d/rc.acpi. De flesta av tjänsterna aktiveras vid uppstart om motsvarande skript är körbart. I tabellen nedan anger vi om den är aktiverad vid start (`till` i kolumnen A) eller inte (`från` i kolumnen A). Om kolumnen är tom beror aktiveringen av tjänsterna på ett val som gjorts under installationen. Ett `A` i kolumnen anger att tjänsten är aktiverad i Auto installationsläge, annars aktiverad om användaren valde det under installationen. Paketkolumnen anger vilket programpaket som tillhandahåller skriptet som motsvarar tjänsten

[options="autowidth"]
|====
| *Tjänst* | *A* | *Paket* | *Syfte och kommentarer*
| acpi | till | acpid | Avancerad konfiguration och strömgränssnitt, tillåter till exempel att hantera ström eller starta om med en knapptryckning
| alsa | till | alsa-utils | Ange standardljudinställningar eller återställer de sparade
| alsa-oss | från | alsa-utils | ALSA OSS kärnmoduler. Inte användbart i de flesta fall, inte aktiverat som standard i Slint.
| atalk | från | netatalk | Tillåter Unix-liknande operativsystem att fungera som fil-, utskrifts- och tidsservrar för Macintosh-datorer.
| atd | från | at | at och batch läser skalkommandon från standardinmatning (eller en specificerad fil) och lagrar dem som ett jobb som ska schemaläggas för exekvering vid ett senare tillfälle
| autofs | från | autofs | AutoFS ger automatisk montering av flyttbar media eller nätverksresurser när de sätts in eller nås.
| bind | från | bind | Namnserver. De flesta användare kommer att förlita sig på en fjärrserver. Aktivera det om du vill köra en namnserver i detta system.
| bitlbee | till | bitlbee | BitlBee är en IRC-demon som kan prata med snabbmeddelandenätverk
       och fungerar som en inkörsport. Användare kan ansluta till servern med vilken normal
       IRC-klient och se deras 'kompislista' i bitlbee.
| bluetooth | till | bluez | Tillåter att kommunicera med bluetooth-enheter
| brltty| | brltty | Gör det möjligt att kommunicera med punktskriftsterminal eller skärmläsare. Aktiveras om det begärs under installationen.
| cgconfig | till | libcgroups | Kör verktyget cgconfigparser som analyserar /etc/cgconfig.conf för att ställa in kontrollgruppshierarkin, inklusive inställning av gruppernas behörigheter (UID och GID) och eventuellt inställbara parametrar för kontrollanterna. Detta underlättar att göra det själva vid varje start, till exempel köra ett separat skalskript. Detta skript är körbart som standard men kommer ändå inte att göra något förrän /etc/cgconfig.conf redigeras (alla rader är kommenterade vid levererat)
| cgred | till | libcgroups | Kontrollgrupper är ett sätt att kontrollera tilldelningen av systemresurser som CPU eller RAM till "grupper" av användare och/eller processer. Det här skriptet startar daemon cgroups rules engine daemon som automatiskt distribuerar processer som ändrar sitt effektiva UID eller GID till lämpliga kontrollgrupper. Det är körbart som standard, men för att få det att fungera måste du ställa in regler i /etc/cgrules.conf.
| consolekit | till | ConsoleKit2 | Den här daemon används av polkits auth-agent för att kontrollera privilegier för användare som vill starta om eller stänga av systemet, till exempel.
| cpufreq | till | sysvinit-scripts | Inställningar för CPU-frekvens och spänningsskalning i kärnan.
| crond | till | crond | Cron daemon körs i bakgrunden och utför uppgifter för användarnas räkning vid lämplig tidpunkt.
| cups | till | cups | Skript för start/avstängning av CUPS utskriftsserver.
| cups-browsed | från | cups-filters | Gör fjärrskrivare tillgängliga lokalt.
| dnsmask | från | dnsmask | Starta/stoppa/starta om dnsmasq (en liten DNS/DHCP-server)
| dovecot | från | dovecot | Dovecot är en IMAP- och POP3-server med öppen källkod för Linux/UNIX-liknande system, skriven med säkerheten i fokus. 
| elogind | till | elogind | elogind är logind för systemd-projektet, extraherat till ett fristående paket.
| espeakup | | espeakup | startar/stoppar/starta om skärmläsaren för espeakup-konsolen. På om användaren begärde tal under installationen eller senare skrev speak-with espeakup.
| fail2ban | från | fail2ban | startar/stoppar fail2ban som skannar loggfiler som /var/log/pwdfail och förbjuder IP som misslyckas med för många lösenord och uppdaterar även brandväggsregler för att avvisa IP-adressen.
| fenrir | från | fenrir | startar/stoppar/starta om skärmläsaren fenrir, som kan startas efter installationen genom att skriva speak-with fenrir.
| font | från | kbd | Ställer in konsolteckensnittet (används i konsolläget, inte i det grafiska läget).
| fuse | till | fuse | Ladda fuse-modulen och montera filsystemet för fuse-kontrollsystemet. FUSE är ett enkelt gränssnitt för användarprogram för att exportera ett virtuellt filsystem till Linuxkärnan. FUSE syftar också till att tillhandahålla en säker metod för icke privilegierade användare att skapa och montera sina egna filsystemimplementationer.
| fuse3 | till | fuse3 | Som fuse, men version 3 
| gpm | till | gpm | General Purpose Mouse-servern gör det möjligt att klippa och klistra in text från skärmen på en Linux-konsol.
| haveged | till | haveged | Haveged-projektet är ett försök att tillhandahålla en lättanvänd, oförutsägbar slumptalsgenerator baserad på en anpassning av HAVEGE-algoritmen.
| httpd | från | httpd | Startar eller stoppar Apache-webbservern
| icecc-scheduler | från | icecream | Starta/stoppa/starta om schemaläggaren icecream (distribuerad kompilator)
| iceccd | från | icecream | Starta/stoppa/starta om icecream-demon (distribuerad kompilator)
| inet1 | till | network-scripts | Det här skriptet används för att starta de olika nätverksgränssnitten.
| inet2 | till | network-scripts | Det här skalskriptet startar upp hela nätverkssystemet.
| inetd | till | inetd | BSD "super-server" daemon. Användaren måste redigera /etc/inetd.conf för att tjänsterna ska kunna användas.
| ip_forward | från | network-scripts | Starta/avsluta vidarebefordran av IP-paket, vilket behövs för att datorn ska fungera som en router.
| kadmind | från | krb5 | Starta Kerberos-administrationsservern
| kprprod | från | krb5 | Starta uppdateringsservern för Kerberos V5 slave KDC. 
| krb5kdc | från | krb5 | Starta krb5kdc, som är autentiseringstjänsten och nyckeldistributionscentret (AS/KDC) för Kerberos version 5. Detta måste köras först på både huvud- och sekundära KDC:er.
| local | från | sysvinit-scripts | Startar demoner som inte startas av /etc/rc.d/rc.M vid uppstart.
| loop | till | sysvinit-scripts | Laddar in kärnmodulen för loop-enheten.
| lxc | från | lxc | Det här skriptet startar (om det är konfigurerat för automatisk start) och stoppar lxc-behållare.
| mcelog | från | mcelog | Startar mcelog-hårdvarufelsloggningen. Detta loggar och hanterar CPU-hårdvarufel på x86-system.
| messagebus | till | dbus | D-BUS systemövergripande meddelandebuss. Detta är en daemon som sänder ut meddelanden om systemhändelser och andra meddelanden, vilket möjliggör kommunikation mellan processer.
| modules | till | sysvinit-scripts | Beräkna beroenden av kärnmoduler och starta andra skript som laddar moduler som inte laddas automatiskt av eudev, eventuellt för specifika kärnversioner.
| modules.local | till | sysvinit-scripts | Ladda moduler som inte laddas automatiskt av eudev
| mysqld | från | mariadb | Startar/stoppar MariaDB-servern. MariaDB är en förgrening av MySQL som är fullt kompatibel med MySQL.
| networkmanager| | NetworkManager | Detta är en demon för att automatiskt byta nätverksanslutningar till den bästa tillgängliga anslutningen. Aktiveras om NetworkManager väljs för att konfigurera nätverket, under eller efter installationen.
| nfsd | från | nfs-utils | Startar/stoppar en nfs (Network File Server)
| ntpd | till | ntp | Startar och stoppar en ntp-demon (Network Time Protocol).
| numlock| | salixtools | Aktivera numlock på konsolen
| openldap | från | openldap | Starta ldap-servern (Lightweight Directory Access Protocol)
| openvpn | från | openvpn | Starta OpenVPN-demon (säker IP-tunnel)
| pcmcia | från | pcmciautils | Skript för att initialisera PCMCIA-subsystemet.
| php-fpm | från | php | Startar PHP FastCGI Process Manager-demon.
| postfix | från | postfix | Startar Postfix, agent för transport och inlämning av e-post.
| pulseaudio | från | pulseaudio | Startar pulseaudio i hela systemet. Detta rekommenderas inte i Slint.
| rpc | från | rpcbind | Starta/stoppa/starta om RPC-demoner (Remote Process Communications) som behövs för att använda NFS. För att köra en NFS-server är det obligatoriskt att starta dessa.
| samba | från | samba | Starta/stoppa/starta om Samba SMB CIFS-fil och utskriftsserver för CIFS-klienter. Du kan hantera ett filutrymme eller skrivare på en Samba-värd som är tillgänglig för CIFS-klienter (t.ex. datorer med Windows).
| saslauthd | från | cyrus-sasl | saslauthd är en daemonprocess som hanterar autentiseringsbegäranden i klartext för SASL-bibliotekets räkning. CMU Cyrus SASL-biblioteket används främst för att autentisera till e-postservrar.
| serial | från | util-linux | Initialiserar och ställer in de seriella portarna på ditt system.
| setterm | till |util-linux | Ger kommandoraden för verktyget setterm för att ställa in terminalens attribut (används främst för skärmtömning och strömhantering).
| smartd | från | smartmontools | Starta/stoppa/starta om smartd-daemon, som övervakar statusen för S.M.A.R.T.-kompatibla hårddiskar och rapporterar eventuella problem.
| snmpd | från | net-snmp | Starta/stoppa net-snmp SNMP-demon (Simple Network Management Protocol)
| speechd-up | | speechd-up | startar/stoppar/starta om skärmläsaren speechd-up, som kan startas efter installationen genom att skriva speak-with speechd-up.
| sshd | till | openssh | Starta/stoppa/starta om den säkra skaldemonen.
| swapinzram | till | swapinzram | Konfigurera en swapblock-enhet i RAM med hjälp av zram
| syslog | till | sysklogd | Starta/stoppa/starta om systemets loggningsdemoner, som loggar både kärnans och systemets meddelanden.
| sysstat | från | systat | Återställer systemets aktivitetsloggar, som används för att beräkna prestandastatistik.
| sysvinit | till | sysvinit-scripts | Den här filen ger grundläggande kompatibilitet med startskript i SystemV-stil som finns i många binära paket.
| timidity | från | TiMidity++ | Starta/stoppa/starta om TiMidity++-demon. TiMidity++ är en mjukvarusynthesizer. Den kan spela upp MIDI-filer genom att konvertera dem till PCM-vågformdata eller andra olika ljudfilformat.
| udev | till | eudev | Det här skriptet initierar udev, som fyller katalogen /dev med enhetsnoder och söker efter enheter,
laddar lämpliga kärnmoduler och konfigurerar enheterna.
| ulogd | till | ulogd | startar ulogd-demonen i användarutrymmet för loggning av nätfilter/iptables-relaterad loggning.
| vde2 | till | vde2 | Starta/stoppa/starta om VDE-demon. VDE är ett virtuellt nätverk som är kompatibelt med Ethernet och som innehåller verktyg som "vde_switch" och "vdeqemu".
| wireless | till | wireless-tools| Det här skriptet ställer in trådlösa PCI-, USB- och 32-bitars Cardbus-enheter. Normalt anropas det här skriptet från rc.inet1 snarare än att köras direkt.
| yp | till | yptools | Starta NIS (Network Information Services). NIS tillhandahåller nätverksomfattande distribution av värdnamn, användarnamn och andra informationsdatabaser.
|====

Du kan starta eller stoppa en tjänst med hjälp som root av kommandot `service`. För att veta mer typ `man service`.
// Glossary

== Ordlista

Flera definitioner i denna ordlista har tagits eller anpassats från https://en.wikipedia.org/wiki/Main_Page[Wikipedia] och https://pubs.opengroup.org/onlinepubs/9699919799/[POSIX]

[[application]]Program:: Ett program är ett datorprogram som är konstruerat för att utföra en viss uppgift som vanligen begärs av slutanvändare.
+
Program betraktas inte i allmänhet som en del av operativsystemet, vilket innebär att de kan läggas till i systemet efter installationen. De utför icke-systemrelaterade funktioner, t. ex. ordbehandling, arkitektonisk design, mekanisk design, publicering eller finansiell analys.


[[boot]]Boot::
Boot innebär att slå på en dator för att starta ett operativsystem. Flera operativsystem kan installeras i samma dator. Välj vilken som ska laddas in i RAM och köras kan göras antingen av den inbyggda programvaran eller av en programvara som heter boot manager (GRUB i Slints fall). Den inbyggda programvaran i en dator kan stödja en av följande uppstartsläge, eller båda:
+
* I Legacy-eller BIOS-läge laddas OS i exekvering av instruktionerna i en startsektor.
* I EFI-läget är OS-laddaren ett program som lagras i en körbar fil, som finns i en katalog för en EFI System-partition (ESP).

[[CPU]]CPU::
CPU eller Central Processing Unit utför instruktionerna i program.

[[command]]Kommando:: Kommandot definieras av https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_104[POSIX] som "ett direktiv till ett <<shell, skal>> för att utföra en specifik uppgift".
+
Uppgiften att utföra kan vara en <<application, program>> eller ett <<utility, verktyg>>.
+
Grundstrukturen för skalkommandon definieras i kapitlet https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09[2.9 Shell Commands] i POSIX-specifikationen.
+
Exempel på kommandon finns i <<bash shell>>.

[[console]]Konsol:: Ordet "konsol" hänvisar till början av datorn system, när systemadministratören skrev kommandon på en enhet inklusive ett tangentbord och en skrivare, länkad till datorn, kommandona som skrivs in och utdata från datorn som skrivs ut på konsolen, vilket ger en logg över båda.
+
I persondatorer skriver användaren kommandona på tangentbordet och deras utdata skrivs ut på en skärm, som kan separeras från eller integreras med datorn som i en bärbar dator.

[[device]]Enhet::

En datorkringutrustning eller ett objekt som visas för programmet som sådan.[POSIX]

[[directory]]Katalog::
En katalog är ett annat namn för en mapp. Filsystem använder kataloger för att organisera filer inom partitioner.
+
Kataloger kan innehålla filer och andra kataloger. Den resulterande strukturen kan representeras som ett uppochnedträd. Katalogen på toppnivå för en enhet heter root-katalogen. I Linux används tecknet / för att separear nivåerna av trädet. Ett ensamt / representerar rotkatalogen, /home lagrar filerna som tillhör användare, /home/didier lagrar filer som tillhör användare didier. /root lagrar filer för användaren som heter root (systemet's administratör). Obs: "root" kan hänvisa till toppnivåkatalogen eller systemet's administratör.

[[drive]]Enhet::
En enhet är en enhet som lagrar icke flyktiga data, vilket innebär att data inte raderas när strömmen är avstängd. Exempel: hårddiskar, SSD, USB-minnen, SD kortläsare, eMMC.
+
Media som lagrar data kan vara permanent ansluten till enheten eller flyttbar som SD-kort, USB-minnen och enheter anslutna via USB.
+
Ett operativsystem installerat på ett flyttbart media eller en extern enhet sägs var portabel: det kan flyttas från en dator till en annan.

[[display_manager]]Bildskärmshanterare::
En bildskärmshanterare (eller inloggningshanterare) är en programvara som visar ett fönster på skärmen där den frågar användarnamn och lösenord för användaren, startar den grafiska miljö som valts av nämnda användare.

[[encryption]]Kryptering::
Kryptering är processen för att konvertera data till en oigenkännlig ("krypterad") form. Det används ofta för att skydda känslig information så att endast behöriga personer kan se den. En enda fil eller katalog, en partition samt som en hel enhet kan krypteras, som gör den tillgänglig endast efter att skrivit in en liten text som kallas en lösenfras, hålls hemlig.

[[file]]Fil::
En datafil är en uppsättning digitala data som samlats in under samma namn, inspelade på ett permanent lagringsmedium, så kallad masslagring, till exempel en hårddisk, en SSD, en DVD, ett SD-kort eller en USN-pinne och hanteras som en enhet.
+
Filer kan innehålla data som texter, bilder, ljud, videor eller datorprogram.

[[file_system]]Filsystem::
Ett filsystem är ett program som hanterar filer och kataloger i en -partition. Den memorerar platsen i de fysiska medierna av data som finns i filerna, vilket gör det möjligt att läsa eller skriva dem. Exempel på vanliga filsystem är vfat, ntfs, ext4, f2fs. Detta kommando listar alla fil system som tillåter att läsa data som finns i en partition från Linux:
+
----
cat /proc/filsystem|grep -v nodev
----

[[firmware]]Firmware::
En firmware är en programvara som initierar och kontrollerar hårdvara, sedan antingen väljer och ladda i RAM operativsystemet, eller startar en programvara som heter en boot manager som kommer att göra det. Den inbyggda programvaran hålls i icke-flyktiga minne enheter som ROM, EPROM eller flashminne. Det är den första programvaran som körs när startar en dator. Det ger en meny som gör det möjligt att konfigurera hårdvaran och välja i vilket läge (Legacy eller EFI) att starta, och i vilken ordning leta efter operativsystemet eller andra program (som GRUB boot manager) att köra.

[[kernel]]Kernel::
En Linux-kärna är programvaran i kärnan av ett Slint-system som hanterar interaktioner mellan program och hårdvara.
+
Den presenterar sig som en enda fil, installerad i katalogen /boot. Till exempel är filen /boot/vmlinuz-generic-5.12.11 en kärna som kommer från kernel-generiskt paket.
+
Vid uppstart kopieras kärnan till RAM.

[[initrd]]Initrd::
En initrd (mer exakt ett initramfs eller initialt RAM-filsystem för Slint) är ett Linux-system som tillhandahålls som en komprimerad arkivfil. Vid uppstart, precis efter att kärnan har laddats i RAM laddas initrd i RAM också. Dess fil /init körs: den laddar behövda kärnmoduler i RAM, registrera enheterna, möjligen låser upp rootenheten, montera pseudofilsystem växlar sedan till rootfilsystemet för att faktiskt starta systemet.
+
En initrd presenterar sig som en enda fil, installerad i katalogen uppstart. Till exempel filen initrd-generic-5.12.11 är en initrd

[[live_system]]Live-system::
Ett live system är ett operativsystem som, istället för att installeras i en enhet som en hårddisk eller SSD, ligger helt i <<RAM>>.
+
An initrd is also a live system, and so is a Slint installatör wich is basically an initrd.

[[partition]]Partition::
En partition är en del av ett lagringsmedium, till exempel en hårddisk eller SSD. Det behandlas av operativsystemet som en separat logisk volym, vilket gör det fungerar som ett separat media.

[[partition_table]]Partitionstabell::
En partitionstabell är den permanenta strukturen som registrerar hur information läggs ut på ett medium, huvudsakligen inspelning av början och slutet av varje partition på mediat.
+
De vanligaste typerna av partitionstabeller är DOS-partitionstabellen, som initialt används av MS-DOS-operativsystemet, och GUID Partition Table eller GPT, som tillåter att hantera fler partitioner och större enheter.

[[program]]Program::
En förberedd sekvens av instruktioner till systemet för att utföra en definierad uppgift. Termen 'program' omfattar tillämpningar skrivna i Skalkommando-språk, komplexa verktyg för inmatningsspråk (t.ex. awk, lex, sed, osv.) och högnivåspråk. [POSIX]

[[RAM]]RAM::
RAM står för Random Access Memory. Denna typ av enhet lagrar flyktiga data, vilket innebär att data raderas när strömmen är avstängd.

[[shell]]Skal:: Ett program som tolkar sekvenser av textindata som kommandon. Den kan fungera på en indataström eller så kan den interaktivt prompt och läsa kommandon från en terminal. Syntaxen för de kommandon som kan tolkas av skalet kan variera beroende på vilket skal som används, men som i huvudsak definieras i kapitlet https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html[ 2. Shell Command Language] för POSIX-specifikationen.
+
Slint skickar flera program som fungerar som skal, listade i filen /etc/shells. *Bash*-skalet används som standard.

[[swap]]Växlingsutrymme::
Ett växlingsutrymme används för att preliminärt lagra data tidigare i RAM på en enhet som en hårddisk eller SSD, antingen för att RAM annars skulle bli fullt, eller för ledigt utrymme i RAM för att lagra det mest använda data. Växlingsutrymmet kan vara en partition på en enhet av typen "Linux swap" eller en vanlig fil som lagras i en en befintlig partition. Det finns också "swap i zram": i detta fall data lagras i RAM men i komprimerad form.

[[terminal]]Terminal::
Historiskt sett var en terminal en fysisk enhet som består av ett tangentbord och en skärm som används för att skriva kommandon och ta emot svar från en fjärrdator.
+
Numera kan kommandona skrivas i konsolläge (eller textläge) eller i grafiskt läge.

[[utility]]Verktyg::
Ett verktyg är ett program som kan köras med namn från ett skal (detta är också fallet med vissa <<application,program>>).
+
Verktyg är en del av operativsystemet (men inte en del av kärnan). De utför systemrelaterade funktioner, såsom att lista kataloginnehåll, kontrollera filsystem, reparera filsystem eller extrahera systemstatusinformation.
+
Ett verktyg kan anropas som ett separat program som kör i en annan process än kommandospråks tolken, eller så kan den implementeras som en del av kommandotolken.
+
Till exempel, echo-kommandot (direktivet för att utföra en specifik uppgift) kan genomföras så att echo-verktyget (den logik som utför uppgiften att eka ut) är i ett separat program; därför utförs den i en process som skiljer sig från kommando-språktolken. I praktiken innebär detta att verktyget i detta fall är ett program som skiljer sig från skalet
+
Omvänt skulle logiken som utför ekotjänsten kunna byggas in i kommandotolken; därför kunde den köra i samma process som kommandotolken. Ett sådant verktyg sägs vara "inbyggd" i skalet.

[[virtual_terminal]]Virtuell terminal::
En virtuell terminal är en programvara som simulerar en fysisk terminal, enhet består av ett tangentbord och en skärm som gör det möjligt att kommunicera på distans med en dator.
