== Slint mit BTRFS

In diesem Artikel beschreiben wir die einzigartigen Eigenschaften des BTRFS-Dateisystems und wie ein Slint-System bei der Installation konfiguriert wird, um diese zu nutzen.

Um dieses Dokument nicht mit Definitionen zu überladen, verweisen wir den Leser auf das https://slint.fr/de/HandBook.html#_glossary[Glossar] im Slint-Handbuch und speziell für den btrfs "jargon" auf das https://btrfs.readthedocs.io/en/latest/Glossary.html[Glossar] in dessen Dokumentation.

Ein BTRFS-Dateisystem besteht aus einem logischen Datenspeicher, der sich auf mehrere Blockgeräte (Partitionen oder Festplatten) verteilen kann. Anfangs wird Slint auf einer einzigen Partition installiert.

Ein Untervolumen ist ein Unterverzeichnis von Dateien innerhalb des Volumens, dessen Root wie ein unabhängiges Dateisystem gemountet werden kann. Allerdings wird der Speicherplatz, der einem Volumen zugewiesen wird, auch jedem seiner Untervolumen zugewiesen: Es ist daher nicht notwendig, ihn auf die Untervolumina zu verteilen, wie wenn sie in verschiedenen Partitionen wären.

Untervolumen können gleichzeitig mit dem Volumen erstellt werden (durch den Befehl mkfs.btrfs), aber auch später mit den btrfs Tools hinzugefügt oder gelöscht werden.

Als Beispiel erzeugen die folgenden Befehle das Slint "system" Volumen und seine Untervolumen, falls BTRFS verwendet wird. Im folgenden ist $ROOTNAME der Name der Partition, in der Slint installiert wird, und $SLINT der Mount-Punkt des System-Volumens während der Installation.
----
mkdir /SLINT
SLINT="/SLINT"
mkfs.btrfs -L root $ROOTNAME
mount -o compress=zstd:3,noatime $ROOTNAME $SLINT
btrfs subvolume create $SLINT/@
btrfs subvolume create $SLINT/@home
btrfs subvolume create $SLINT/@swap
umount $SLINT
mount -o subvol=/@,compress=zstd:3,noatime $ROOTNAME $SLINT
mkdir $SLINT/home
mkdir $SLINT/swap
----
Die $ROOTNAME Partition (die durch ihre UUUID gekennzeichnet ist, die wir <uuid>nennen) wird dann dreimal (einmal pro Untervolumen) bei jedem Start von Slint eingehängt wie in der Datei /etc/fstab eingetragen:
----
UUID=<uuid> / btrfs subvol=/@,compress=zstd:3,noatime 0 0
UUID=<uuid> /home btrfs subvol=/@home,compress=zstd:3,noatime 0 0
UUID=<uuid> /swap btrfs subvol=/@swap,compress=zstd:3,noatime 0 0
----
Was zum Beispiel (aus der Ausgabe von lsblk /dev/sda5) ergibt:
----
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda5        50G   22G   28G  44% /
/dev/sda5        50G   22G   28G  44% /home
/dev/sda5        50G   22G   28G  44% /swap
----
Wir sehen, dass der Platz für das Volumen (28G) auch für jedes der Untervolumen verfügbar ist. Andererseits bedeutet die Option "compress_zstd:3", dass alle Dateien, die gespeichert werden, durch das Dienstprogramm zstd mit Komprimierungsstufe 3 komprimiert werden. Daher ist die Größe des Systems ungefähr halb so groß wie beim ext4-Dateisystem.

Wenn wir das Gerät im root des Volumens mounten (ohne Angabe eines Untervolumens), wie:
----
mount /dev/sda5 /mnt
----
sehen wir die Untervolumen als Unterverzeichnisse von /mnt:
----
ls /mnt
@ @home @swap
ls /mnt/@home/didier
Bilder Dokumente Downloads Musik Schreibtisch Videos Vorlagen Öffentlich
----
Ein weiteres bemerkenswertes Merkmal von BTRFS ist das "copy-on-write". Beim Bearbeiten einer Datei werden geänderte Teile an einen anderen Ort geschrieben, die Metadaten (die den Speicherort aller Teile der Datei aufzeichnen) werden aktualisiert. Solange auf die vorherigen Daten verwiesen wird, bleiben sie unangetastet.

Dies macht es sehr einfach, Schnappschüsse von BTRFS Untervolumen zu erstellen: Ein neuer Schnappschuss ist "frei", da es sehr wenig Speicherplatz verbraucht: Es werden nur die Metadaten des Schnappschusses geschrieben, die den physikalischen Speicherort aller Teile von Dateien im Untervolumen speichern, und dies geschieht fast sofort. Der vom Schnappschuss verwendete Raum wird nur wachsen, wenn sich das ursprüngliche Untervolumen und der Schnappschuss unterscheiden, dann ruft der Schnappschuss Daten aus dem Original ab. Auf der anderen Seite werden die dem Original hinzugefügten Daten nicht in der Momentaufnahme enthalten: Mit anderen Worten, eine Änderung des ursprünglichen Untervolumens ändert den Schnappschuss nicht.

Slint enthält das Dienstprogramm `absm`, welches Schnappschüsse vom Untervolumen @ macht und es erlaubt zu einem vorherigen Zustand des Systems zurückzukehren, wenn eine Aktualisierung schief geht, durch Booten des Systems auf diesem Schnappschuss, ausgewählt im GRUB Boot-Menü. Um zu erfahren wie es verwendert wird, tippen Sie einfach `absm` als root ein oder verwenden Sie sudo.

BTRFS überprüft auch die Integrität jeder Datei, wenn sie geöffnet wird, mit einer Prüfsumme, was die Überprüfung des Dateisystems beim Systemstart unnötig macht. Darüber hinaus überprüft der Befehl "btrfs scrub" die Integrität aller Dateien, einschließlich derer, die selten gelesen werden. Standardmäßig führt das Dienstprogramm `btrfsmaintenance` in Slint einmal pro Woche "btrtfs scrub" aus.

`btrfsmaintenance` führt standardmäßig auch einmal pro Woche "btrfs balance" aus. Dieser Befehl erlaubt es Ihnen, die Daten zwischen den Geräten zu verteilen, wenn sich das Dateisystem über mehrere erstreckt, aber auch den genutzten Speicherplatz neu zu organisieren, insbesondere um den nicht zugewiesenen Speicherplatz des Dateisystems freizugeben. Dies verbessert insbesondere die Leistung von BTRFS auf einer Festplatte. Um mehr über `btrfsmaintenance` zu erfahren, lesen Sie /usr/doc/btrfsmaintenance*/README.html

Auch andere nützliche und BTRFS-kompatible Werkzeuge sind in Slint enthalten, alle haben eine --help Option und eine man-Seite:

* `jdupes` erkennt doppelte Dateien und erlaubt Ihnen, entsprechend zu handeln, unabhängig vom verwendeten Dateisystem
* `btdu` erlaubt es, präzise genau zu erfahren, wieviel Platz auf den BTRFS-Subvolumen und -Verzeichnissen belegt ist
* `restic` ist eine sehr vielseitige Backup-Software, die für jedes Dateisystem verwendet werden kann.

Empfehlungen.

* BTRFS braucht Platz zum Atmen und Reorganisieren. Halten Sie immer 10-20% Speicherplatz frei.
* Einige Werkzeug-Optionen, die im Paket btrfs-tools enthalten sind, können gefährlich oder kontraproduktiv sein. Verwenden Sie nur diejenigen, deren Wirkung Sie sehr gut kennen und wenn Sie Zweifel haben, zuerst Rat einholen auf der Slint-Mailingliste oder im IRC auf irc. libera.chat, Kanal #btrfs.
* Insbesondere vermeiden Sie die Verwendung von "btrfs filesystem defrag" und vor allem "btrfs check --repair".
* Bevor Sie einen Befehl verwenden, lesen Sie sorgfältig die entsprechende Manpage (beginnend mit "man btrtfs", die die anderen auflistet).
* Wie bei jedem Dateisystem: Erstellen Sie regelmäßige Sicherungen! Dies ist in der Regel die einzige Möglichkeit, Ihre Daten im Falle eines Hardware-Fehlers wiederherzustellen.

Für Weiteres:

* Das Forza wiki: https://wiki.tnonline.net/w/Category:Btrfs
* Die offizielle Dokumentation: https://btrfs.readthedocs.io/en/latest/
* Fragen, Probleme: im irc.libera.chat Channel #btrfs

