== Slint με BTRFS

Σε αυτό το άρθρο περιγράφουμε τα μοναδικά χαρακτηριστικά του συστήματος αρχείων BTRFS και πώς ένα σύστημα Slint έχει ρυθμιστεί κατά την εγκατάσταση για να επωφεληθεί από αυτά.

Για να μην υπερφορτώσουμε αυτό το έγγραφο με ορισμούς, παραπέμπουμε τον αναγνώστη στο https://slint.fr/en/HandBook.html#_glossary[glossary] που περιλαμβάνεται στο εγχειρίδιο Slint και πιο συγκεκριμένα για btrfs "jargon" στο https://btrfs.readthedocs.io/en/latest/Glossary.html[glossary] που περιλαμβάνεται στην τεκμηρίωσή του.

Ένα σύστημα αρχείων BTRFS αποτελείται από έναν λογικό όγκο που μπορεί να καλύπτει πολλαπλές συσκευές (διαμερίσματα ή δίσκους). Αρχικά, το Slint εγκαθίσταται σε ένα ενιαίο διαμέρισμα.

Ένας υποόγκος είναι ένα υποδέντρο αρχείων μέσα στον τόμο, η ρίζα του οποίου μπορεί να τοποθετηθεί σαν να ήταν ένα ανεξάρτητο σύστημα αρχείων. Ωστόσο, ο χώρος που κατανέμεται σε όγκο κατανέμεται επίσης σε καθέναν από τους επιμέρους όγκους του: δεν είναι επομένως αναγκαίο να κατανεμηθεί μεταξύ των υποόγκων, σαν να ήταν σε ξεχωριστά χωρίσματα.

Οι υποόγκοι μπορούν να δημιουργηθούν ταυτόχρονα με τον τόμο (από την εντολή mkfs.btrfs), αλλά και να προστεθούν ή να διαγραφούν αργότερα χρησιμοποιώντας τα εργαλεία btrfs.

Για παράδειγμα, οι παρακάτω εντολές δημιουργούν τον τόμο Slint "system" και τους υποτόμους του, σε περίπτωση που χρησιμοποιείται BTRFS. Στο ακόλουθο $ROOTNAME είναι το όνομα του διαμερίσματος στο οποίο θα εγκατασταθεί το Slint και $SLINT το σημείο προσάρτησης του τόμου του συστήματος κατά την εγκατάσταση.
----
mkdir /SLINT
SLINT="/SLINT"
mkfs. trfs -L root $ROOTNAME
mount -o compress=zstd:3, oatime $ROOTNAME $SLINT
btrfs subvolume create $SLINT/@
btrfs subvolume create $SLINT/@home
btrfs subvolume create $SLINT/@swap
umount $SLINT
mount -o subvol=/@, ompress=zstd:3,noatime $ROOTNAME $SLINT
mkdir $SLINT/home
mkdir $SLINT/swap 
----
Το διαμέρισμα $ROOTNAME (υποδεικνύεται από το UUID το οποίο θα καλέσουμε <uuid>) θα τοποθετηθεί στη συνέχεια τρεις φορές (μία φορά ανά υποτόμο) κάθε φορά που ξεκινά το Slint, όπως αναφέρεται στο αρχείο /etc/fstab:
----
UUID=<uuid> / btrfs subvol=/@,compress=zstd:3,noatime 0
UUID=<uuid> /home btrfs subvol=/@home,compress=zstd:3,noatime 0
UUID=<uuid> /swap btrfs subvol=/@swap,compress=zstd:3,noatime 0 
----
Αυτό δίνει για παράδειγμα (λαμβάνεται από την έξοδο του lsblk /dev/sda5):
----
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda5        50G   22G   28G  44% /
/dev/sda5        50G   22G   28G  44% /home
/dev/sda5        50G   22G   28G  44% /swap
----
Βλέπουμε ότι ο διαθέσιμος χώρος για τον όγκο (28G) είναι επίσης διαθέσιμος για κάθε επιμέρους τόμο. Από την άλλη πλευρά, η επιλογή προσάρτησης "compress_zstd:3" σημαίνει ότι όλα τα αρχεία που θα αποθηκευτούν θα συμπιέζονται από το βοηθητικό πρόγραμμα zstd με το επίπεδο συμπίεσης 3. Έτσι, το μέγεθος του συστήματος είναι περίπου το μισό που θα ήταν με το σύστημα αρχείων ext4.

Εάν προσαρτήσουμε τη συσκευή στη ρίζα του όγκου (χωρίς να αναφέρουμε έναν υποόγκο), όπως αυτό:
----
mount /dev/sda5 /mnt
----
βλέπουμε τους υποτόμους να εμφανίζονται ως υποκατάλογοι του /mnt:
----
ls /mnt
@ @home @swap
ls /mnt/@home/didier
Desktop Documents GNUstep Images Templates Music Audience Downloads Videos 
----
Ένα άλλο αξιοσημείωτο χαρακτηριστικό του BTRFS είναι το "copy-on-write". Κατά την επεξεργασία ενός αρχείου, τα τροποποιημένα μέρη γράφονται σε άλλη τοποθεσία, τα μεταδεδομένα (που καταγράφουν τη θέση όλων των τμημάτων του αρχείου) που ενημερώνονται. Όσο τα προηγούμενα δεδομένα αναφέρονται ακόμη, θα παραμείνουν άθικτα.

Αυτό το καθιστά πολύ εύκολο να δημιουργήσετε στιγμιότυπα του υποτόμου BTRFS: λαμβάνοντας ένα νέο στιγμιότυπο είναι "ελεύθερο", καθώς χρησιμοποιεί πολύ λίγους χώρους στο δίσκο: μόνο τα μεταδεδομένα του στιγμιοτύπου γράφονται, το οποίο αποθηκεύει τη φυσική θέση όλων των τμημάτων των αρχείων στον υποτόμου, και αυτό γίνεται σχεδόν αμέσως. Ο χώρος που χρησιμοποιείται από το στιγμιότυπο θα αυξηθεί μόνο όταν ο αρχικός υποόγκος και το στιγμιότυπο διαφέρουν, καθώς το στιγμιότυπο θα ανακτά τα δεδομένα που αφαιρέθηκαν από το αρχικό. Από τα άλλα δεδομένα που προστίθενται στο αρχικό δεν θα συμπεριληφθούν στο στιγμιότυπο: με άλλα λόγια, η τροποποίηση του αρχικού υποτόμου δεν τροποποιεί το στιγμιότυπο.

Το Slint περιλαμβάνει το βοηθητικό πρόγραμμα `absm`, το οποίο επιτρέπει τη λήψη στιγμιότυπων του υποτόμου @, επιτρέποντας την επιστροφή σε προηγούμενη κατάσταση του συστήματος εάν μια ενημέρωση πάει στραβά, εκκινώντας το σύστημα σε αυτό το στιγμιότυπο, επιλεγμένο στο μενού εκκίνησης GRUB. Για να γνωρίζετε τη χρήση του, απλά πληκτρολογήστε `absm` ως root ή χρησιμοποιώντας sudo.

Το BTRFS επαληθεύει επίσης την ακεραιότητα κάθε αρχείου όταν ανοίγει με τη χρήση αθροίσματος ελέγχου, καθιστώντας περιττό να ελέγξετε το σύστημα αρχείων κατά την εκκίνηση του συστήματος. Επιπλέον, η εντολή "btrfs scrub" επαληθεύει την ακεραιότητα όλων των αρχείων, συμπεριλαμβανομένων εκείνων που σπάνια διαβάζονται. Από προεπιλογή, το βοηθητικό πρόγραμμα `btrfsmaintenance` που περιλαμβάνεται στο Slint τρέχει "btrtfs scrub" μία φορά την εβδομάδα.

Το "btrfsmaintenance" ενεργοποιεί επίσης το "btrfs balance" μία φορά την εβδομάδα από προεπιλογή. Με αυτή την εντολή μπορείτε να κατανείμετε τα δεδομένα μεταξύ των συσκευών αν το σύστημα αρχείων εκτείνεται σε διάφορες, αλλά και να αναδιοργανώσετε το χρησιμοποιούμενο χώρο, ιδίως για να ελευθερώσετε τον αδιάθετο χώρο του συστήματος αρχείων, το οποίο βελτιώνει ιδιαίτερα την απόδοση του BTRFS στην περίπτωση ενός σκληρού δίσκου. Για να μάθετε περισσότερα για το ` btrfsmaintenance` διαβάστε το /usr/doc/btrfsmaintenance*/README.html

Άλλα χρήσιμα και BTRFS-συμβατά εργαλεία περιλαμβάνονται στο Slint, όλα έχουν μια επιλογή βοήθειας και μια σελίδα man:

* "Jdupes" ανιχνεύει τα διπλότυπα αρχεία και σας επιτρέπει να αναλάβετε δράση αναλόγως, ανεξάρτητα από το σύστημα αρχείων που χρησιμοποιείται
* `btdu` επιτρέπει να γνωρίζετε με ακρίβεια τη θέση που καταλαμβάνουν οι υπό-τόμοι και οι κατάλογοι BTRFS
* `restic` είναι ένα πολύ ευέλικτο λογισμικό δημιουργίας αντιγράφων ασφαλείας που μπορεί να χρησιμοποιηθεί για οποιοδήποτε σύστημα αρχείων.

Προτάσεις.

* Το BTRFS χρειάζεται χώρο για να αναπνέει και να αναδιοργανώνεται. Να διατηρείτε πάντα 10-20 % ελεύθερο χώρο.
* Ορισμένες επιλογές εργαλείων που περιλαμβάνονται στο πακέτο btrfs-tools μπορεί να είναι επικίνδυνες ή αντιπαραγωγικές. Χρησιμοποιήστε μόνο εκείνους των οποίων την επίδραση γνωρίζετε πολύ καλά και αν σε αμφιβολία αναζητούν συμβουλές πρώτα, στη λίστα αλληλογραφίας Slint ή από IRC για irc.libera.chat, κανάλι #btrfs.
* Ειδικότερα, αποφύγετε τη χρήση του "btrfs filesystem defrag" και ειδικά όχι "btrfs check --repair".
* Πριν χρησιμοποιήσετε μια εντολή, διαβάστε προσεκτικά την αντίστοιχη man σελίδα (ξεκινώντας με το "man btrtfs" που αναφέρει τα άλλα).
* Όπως συμβαίνει με κάθε σύστημα αρχείων: κάντε κανονικά αντίγραφα ασφαλείας! Αυτός είναι συνήθως ο μόνος τρόπος για να ανακτήσετε τα δεδομένα σας σε περίπτωση βλάβης υλικού.

Περαιτέρω:

* Forza wiki: https://wiki.tnonline.net/w/Category:Btrfs
* Η επίσημη τεκμηρίωση: https://btrfs.readthedocs.io/en/latest/
* Ερωτήσεις, προβλήματα: στο κανάλι irc.libera.chat #btrfs

