:toc: left
:toclevels: 1
:toc-title: 

// Overview
[[Overview_of_Slint_Installation]]
== Aperçu du processus d'installation

Le programme d'installation sonde d'abord les unités et les partitions existantes pour évaluer les possibilités et les options d'installation et vous permet de choisir entre une préparation automatique ou manuelle des partitions utilisées par Slint.

Si vous choisissez 'manuel', les partitions Linux où Slint pourrait être installé (taille d'au moins 50G), vous sont présentées, sélectionnez l'une d'elles et choisissez le type de système de fichiers que l'installateur va créer : btrfs, ext4 ou xfs comme mentionné dans <<prepare_partitions_for_Slint,Facultativement, préparer des partitions pour Slint>>

Si vous choisissez 'auto', vous sont présentés les lecteurs où Slint pourrait être installé (taille d'au moins 50G), et le système de fichiers sera de type btrfs.

Dans le cas de btrf ; les sous-volumes seront créés pour / /home et /snapshots avec des fichiers compressés et /swap pour héberger un fichier de swap. La 'Copier en écriture' facilitera la création d'instantanés et peut-être d'annuler une mise à jour système en échec. Des outils pour gérer les snapshots sont inclus dans Slint.

Dans les deux modes, l'utilisateur choisit les partitions Linux et Windows existantes qui seront automatiquement montées après le démarrage de Slint, et leurs noms de points de montage, facilitant ainsi l'accès aux systèmes existants et aux données de Slint.

Puis il est proposé à l'utilisateur de chiffrer la partition du système racine, pour éviter le vol de données en cas de perte ou de vol de la machine ou du lecteur où Slint est installé. Si accepté, l'installateur enregistre la phrase de passe permettant de déverrouiller cette partition, que vous tapez au démarrage à le demnde de GRUB avant qu'il 'affiche le menu d'amorçage.

Tout ceci fait, le programme d'installation résume vos choix et vous permet de les confirmer ou non. Jusqu'à ce stade, aucune modification n'a été apportée aux systèmes et données installés pour que vous puissiez le refuser en toute sécurité, puis recomencer ou simplement redémarrer sans aucun dommage.

Ensuite, le partitionnement automatique se fait en cas de problème, la partition racine de Slint est chiffrée si demandé, la partition racine est formatée et les premiers paquets logiciels sont installés.

Si vous avez choisi un disque chiffré, vous tapez la phrase de passe qui sera utilisée pour déverrouiller le lecteur à chaque démarrage.

Vous choisissez un mot de passe pour l'utilisateur "root." C'est l'administrateur système, qui a tous les privilèges.

Vous définissez également le nom d'utilisateur et le mot de passe d'un utilisateur normal.

Vous indiquez si vous avez besoin d'une sortie braille accessible et si vous souhaitez vous connecter en mode texte ou graphique. Si vous avez utilisé la langue anglaise (USA) lors de l'installation, vous choisissez la langue à utiliser dans le système installé, sinon le programme d'installation définit la même chose que lors de l'installation.

L'installateur tente d'établir une connexion Internet, et en cas de succès propose un fuseau horaire correspondant à votre position géographique que vous confirmez, sinon vous en sélectionnez un dans une liste.

On vous demande si vous aurez besoin du braille, alors si vous préférez démarrer dans une console ou dans un environnement graphique, à moins que vous n'ayez utilisé la parole pendant l'installation ou que vous ayez besoin de Braille : alors vous atterrissez dans une console après le redémarrage, par sécurité.

L'installateur crée ensuite un fichier de swap, ce qui peut prendre beaucoup de temps, s'il vous plaît soyez patient.

Les paquets sont installés sur le lecteur. Si une connexion Internet a été établie, il télécharge et installe la version la plus récente de chaque paquet, y compris celles fournies depuis la sortie de l'image ISO.

L'installation de tous les paquets prend de 10 à 40 minutes selon le matériel.

On vous demandera de sélectionner un bureau (même si vous démarrez dans une console en premier) parmi fvm, lxqt, mate et wmaker. D'autres choix seront disponibles après l'installation en tapant 'xwmconfig' si vous démarrez dans une console

Ensuite, le système est configuré et le gestionnaire d'amorçage GRUB est installé. Slint peut démarrer à la fois dans les modes "Legacy" et EFI.

Vous pouvez afficher un aperçu du menu de démarrage avant de redémarrer.

Ensuite, retirez le support d'installation et redémarrez pour démarrer votre nouveau système Slint.
// Usage_installer
[[Usage_of_the_installer]]
== Utilisation de l'installateur

Si vous connaissez la ligne de commande, vous pouvez sauter ce sujet.

Le menu principal d'installation est affiché ci-dessous:
....
Bienvenue dans l'installateur de Slint ! (version 15)

Vous pouvez maintenant taper (sans les guillemets):

'doc' pour connaître les fonctionnalités et l'utilisation de l'installateur.
'start' pour démarrer l'installation.

L'installateur peut préparer le lecteur où Slint sera installé,
en créant les partitions nécessaires. Si vous préférez, vous pouvez le faire vous-même
en utilisant les utilitaires en ligne de commande disponibles dans l'installateur, puis tapez 'start'
une fois ceci terminé. Vous pouvez également quitter l'installateur et utiliser un outil comme gparted
pour faire cela puis relancer l'installateur.

Nous vous recommandons de taper 'doc' d'abord dans ce cas, ou si vous voulez
chiffrer la partition Slint racine.
Lorsque vous avez terminé la lecture, ce menu sera affiché à nouveau.
....

Dès que ce menu est affiché, vous avez la main sur le processus d'installation.

Vous avez lu l'écran et tapez les commandes dans un <<virtual_terminal, terminal virtuel>>. L'installateur inclut plusieurs terminaux virtuels partageant le même clavier physique et l'écran, qui peuvent être utilisés en parallèle.

L'installateur démarre dans le terminal virtuel 1 nommé *tty1* mais vous pouvez passer à un autre. Par exemple, vous pouvez passer à *tty2* en appuyant sur *Alt-F2* puis Entrée pour l'activer et plus tard revenir à *tty1* en appuyant sur *Alt-F1*, sans effacer les informations affichées dans les deux terminaux. *Alt-F1* signifie : appuyez et maintenez la touche *Alt* enfoncée puis appuyez sur la touche *F1*.

Cela peut être utile pour continuer à lire la documentation pendant l'installation : par exemple, vous pouvez passer à *tty2* pour commencer l'installation, passez à *tty1* pour continuer à lire la documentation, puis passez à *tty1* à nouveau pour passer à l'étape suivante de l'installation.

Ceci peut également être utilisé pour consulter le glossaire lors de la lecture d'autres documents.

L'installateur a plusieurs modes d'interaction avec vous, l'utilisateur:

* Vous tapez des commandes à l'invite et lisez leur sortie.
* L'installateur pose une question, vous tapez la réponse et confirmez la réponse en appuyant sur Entrée.
* L'installateur affiche un menu de choix ou d'options : vous sélectionnez l'un d'eux en utilisant les touches fléchées haut et bas, puis confirmez votre choix en appuyant sur Entrée, ou annuler en appuyant sur Échap.
* L'installateur affiche des informations dans un pager. Utilisez ensuite les touches fléchées pour lire la ligne suivante ou précédente, appuyez sur l'espace pour afficher la page suivante, Q pour arrêter de lire le document.

// Prepare
[[prepare_partitions_for_Slint]]
== Facultativement, préparer les partitions pour Slint

Dans ce document, « formater » une partition signifie : créer un système de fichiers pour gérer les fichiers qu'elle contient.

Si après avoir tapé 'start' vous tapez 'm' pour le partitionnement manuel, vous devez d'abord sélectionner la partition racine du système, qui sera monté en tant que "/", puis le type de son système de fichiers -: btrfs, ext4, xfs.

Le programme d'installation répertorie uniquement les partitions de taille au moins 50G et Linux (peuvent également être nommées système de fichiers Linux), non chiffrées. Cette partition peut être formatée ou non, mais dans tous les cas son contenu sera effacé et un nouveau système de fichiers généré par le programme d'installation.

En outre, le mode de partitionnement manuel nécessite sur le même disque que la partition racine du système :

* Partition de type partition d'amorçage de type "BIOS boot", de taille au moins 3M et non formatée.
* Une partition de type EFI, avec au moins 32M d'espace libre, formatée avec un système de fichiers "fat" (ou "vfat"), tel que requis par la spécification UEFI

L'utilisation de partitions existantes Slint ou leur création dépend de l'utilisateur. Les systèmes déjà installés utilisant la partition "BIOS boot" et la partition EFI ne seront pas affectées, seule la partition racine sera (re)formatée.

L'installateur inclut plusieurs applications de partitionnement : cfdisk, fdisk, sfdisk, cgdisk, gdisk, sgdisk, parted. Les applications avec "g" dans leur nom ne peuvent gérer que gpt, parted peut gérer les tables de partitions DOS ainsi que le GPT. fdisk, cfdisk et sfdisk peuvent gérer les tables de partitions DOS. De plus, wipefs (pour effacer les tables de partitions précédentes et les signatures du système de fichiers) et partiprobe (pourinformer le noyau des modifications d'une table de partitions) sont disponibles. Les applications blkid et lsblk affichent des informations sur les périphériques de blocage et les partitions.

Bien sûr, vous pouvez aussi créer les partitions à partir d'un autre système avant de démarrer l'installateur.
// Installation
// Encryption
[[Encryption]]
== Slint avec une partition racine chiffrée.

En mode Auto, le programme d'installation propose de chiffrer la partition système racine. Si vous êtes d'accord, à chaque démarrage, le chargeur de démarrage GRUB vous demandera la phrase de passe que vous aurez tapée pendant l'installation pour déverrouiller l'unité, avant d'afficher le menu d'amorçage. Notez que le déverrouillage de l'unité prend quelques secondes (environ dix secondes).

Avoir un système racine chiffré empêche le vol de données qu'il contient en cas de perte ou de vol de la machine, ou d'un lecteur amovible. Mais cela ne vous protégera pas si l'ordinateur reste en marche et sans surveillance, seulement si la machine a été complètement éteinte !

Pendant l'installation, la partition système Slint sera chiffrée, ainsi que la partition supplémentaire que vous pouvez demander.

Une partition Slint (ou racine) sera nommée : /dev/mapper/cryproot une fois ouverte, si elle a été chiffrée.

Ceci est affiché par cette commande :

----
lsblk -lpo name,fstype,mountpoint | grep /$
----

Ce qui donne une sortie comme :
----
/dev/mapper/cryptroot ext4 /
----

Cette commande à la place:

----
lsblk -lpo name,fstype,mountpoint | grep /dev/sda3
----

donnez:

----
/dev/sda3             cryptoLUKS
----

/dev/sda3 est maintenant une partition « raw » qui inclut l'en-tête « LUKS » à laquelle vous n'aurez jamais besoin d'accéder directement et ne devrez jamais faire. Il héberge tout ce qui est nécessaire pour chiffrer ou déchiffrer la partition /dev/mapper/cryptroot, qui héberge effectivement vos données (dans cet exemple le système Slint).

[WARNING]
====
Si vous oubliez le mot de passe, toutes les données du lecteur seront irrémédiablement perdues ! Alors écrivez ou enregistrez cette phrase de asse et mettez l'enregistrement dans un endroit sûr aussitôt fait.

Les lecteurs meurent. Si cela se produit et il est chiffré, vos données seront perdues. Ainsi, la sauvegarde régulière de vos données importantes n'est pas optionnelle.

En outre, faire une sauvegarde de l'en-tête luks que vous serez en mesure de restaurer la partition luks serait endommagée pour n'importe quelle raison. La commande pourrait être dans notre exemple :
----
luksHeaderBackup /dev/sda3 --header-backup-file <fichier>
----
où <fichier> est le nom du fichier de sauvegarde, que vous stockerez dans un endroit sûr.

Ensuite, auriez-vous besoin de restaurer la sauvegarde, tapez :
----
luksHeaderRestore /dev/sda3 --header-backup-file <fichier>
----

Ne redimensionnez pas une partition d'un lecteur chiffré car après ça il sera définitivement verrouillé et toutes les données qu'il contient seront perdues ! Si vous avez vraiment besoin de plus d'espace, vous devrez sauvegarder tous les fichiers que vous voulez garder, puis installer à nouveau et restaurez les fichiers sauvegardés.

Choisissez un mot de passe fort, de sorte qu'il faudrait trop de temps pour qu'un voleur le découvre pour que cela en vaille la peine.

Ne jamais jouer avec l'en-tête dit "LUKS" situé sur la partition brute (la troisième, comme par exemple /dev/sda3 pour la partition brute au-dessus de la partition système Slint). Pratiquement: ne créez un système de fichiers dans cette partition, ne l'incluez pas dans un vecteur RAID et généralement n'y écrivez rien: toutes les données seraient irrémédiablement perdues !
====

Pour éviter les mots de passe faibles, l'installateur requiert que le mot de passe comprenne :

. Au moins 8 caractères.
. Seulement les lettres majuscules et minuscules non accentuées, les chiffres de 0 à 9, l'espace et les caractères de ponctuation suivants :
+
----
 ' ! " # $ %  & ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~
----
+
Cela garantit que même un nouveau clavier aura tous les caractères nécessaires pour taper la phrase de passe.

. Au moins un chiffre, une lettre minuscule, une lettre majuscule et un caractère de ponctuation.

GRUB suppose que le clavier "us" est utilisé lorsque vous tapez la phrase de passe. Pour cette raison, si pendant l'installation vous utilisez un autre plan de clavier, avant de demander le mot de passe l'installateur va configurer le plan du clavier "us", et après l'avoir enregistré restaurer celui précédemment utilisé. Dans ce cas, l'installateur épellera également chaque caractère saisi de la phrase de passe, car il peut différer de celui écrit sur la touche.

L'application cryptsetup est utilisée pour chiffrer le lecteur. Pour en savoir plus taper après installation: +
-----
man cryptsetup
-----
// Speakup
[[Speakup]]
== Raccourcis clavier pour le lecteur d'écran Speakup

Ce chapitre est destiné aux utilisateurs qui ont besoin d'un lecteur d'écran, mais qui ne connaissent pas Speakup.

Désactivez le verrouillage des touches numériques pour utiliser Speakup.

La touche CapsLock est utilisée comme une touche Majuscule. Par exemple, "CapsLock 4" signifie : +
maintenez la touche CapsLock enfoncée comme une touche Majuscule et appuyez sur 4.

 Premièrs raccurcis à se rappeler :
 PrintScreen Activer/désactiver le haut-parleur.
 CapsLock F1 Speakup Help (appuyez sur Espace pour quitter l'aide).

 Raccourcis clavier pour changer les paramètres :
 CapsLock 1/2 Diminuer/Augmenter le volume du son.
 CapsLock 5/6 Diminuez/Augmentez la vitesse de parole.

 Raccourcis clavier pour lire l'écran:
 CapsLock j/k/l      Dire le mot Précédent/Actuel/Suivant.
 CapsLock k (twice)  Épeler le mot actuel.
 CapsLock u/i/o      Dire la ligne Précédente/Actuelle/Suivante.
 CapsLock y          Dire du haut de l'écran au curseur de lecture.
 CapsLock p          Dire du curseur de lecture au bas de l'écran.
// First_steps
[[first_steps_after_installation]]
== Premières étapes après l'installation

Voici les premières tâches à effectuer après l'installation

Dans ce document, tous les textes après un caractère # sont des commentaires des commandes suggérées, à ne pas saisir.

=== Mise à jour initiale du logiciel

Après l'installation, le système devrait être mis à jour pour obtenir la version la plus récente fournie de chaque logiciel, ainsi que les nouveaux logiciels fournis depuis la version de l'ISO. Ceci est particulièrement nécessaire si aucune connexion réseau n'était disponible lors de l'installation comme alors, seuls les paquets inclus dans le média de distribution ont été installés, et ils pourraient être obsolètes.

La plupart des commandes saisies ci-dessous demandent des droits d'administration associés à un compte spécifique nommé 'root', pour lequel vous avez enregistré un mot de passe lors de l'installation.

Pour lancer une commande en tant que 'root', tapez d'abord
----
su -
----
puis tapez le mot de passe pour root et appuyez sur Entrée avant de taper la commande.

Lorsque vous avez terminé d'émettre des commandes en tant que root, appuyez sur Ctrl+d ou tapez « exit » pour récupérer votre statut « utilisateur normal ».

Alternativement, l'utilisateur enregistré lors de l'installation et les autres membres du groupe 'wheel' peuvent taper :
----
sudo <command>
----
puis aussi le mot de passe pour root.

Pour mettre à jour, tapez en tant que root dans une console ou un terminal graphique:
----
slapt-get --add-keys # récupère les clés pour authentifier les paquets
slapt-get -u # mettre à jour la liste des paquets dans les miroirs
slapt-get --install-set slint # obtenir les nouveaux paquets
slapt-get --upgrade # Obtenir les nouvelles versions des paquets installés
dotnew # liste les changements dans les fichiers de configuration
----
Lorsque vous exécutez dotnew, acceptez de remplacer tous les anciens fichiers de configuration par les nouveaux. Ceci est sûr comme vous l'avez fait'vous n'avez pas encore fait de personnalisation.

Alternativement, vous pouvez utiliser ces front-ends: gslapt au lieu de slapt-get, et dotnew-gtk au lieu de dotnew.

Pour en savoir plus sur slapt-get, tapez :
----
man slapt-get
----
ou en tant que racine:
----
slapt-get --help
----
et lire /usr/doc/slapt-get*/README.slaptgetrc.Slint

// Glossary
== Glossaire

Plusieurs définitions dans ce glossaire sont prises ou adaptées de https://fr.wikipedia.org/wiki/Main_Page[Wikipedia] et https://pubs.opengroup.org/onlinepubs/9699919799/[POSIX]

[[application]]Application:: Un programme d'application (application pour abrégé) est un programme informatique conçu pour exécuter une tâche spécifique généralement demandée par les utilisateurs finaux.
+
Les applications ne sont généralement pas considérées comme faisant partie du système d'exploitation, ce qui signifie qu'elles peuvent être ajoutées au système après son installation. Elles remplissent des fonctions non liées au système, telles que le traitement de texte, la conception architecturale, la conception mécanique, la publication ou l'analyse financière.


[[boot]]Démarrer::
L'amorçage consste à allumer un ordinateur pour démarrer un système d'exploitation. Plusieurs systèmes d'exploitation peuvent être installés sur le même ordinateur. Sélectionner celui à charger dans la mémoire vive et l'exécution peut être effectuée soit par le microprogramme, soit par un logiciel nommé gestionnaire d'amorçage (GRUB dans le cas de Slint). Le microprogramme d'un ordinateur peut prendre en charge l'un des modes d'amorçage suivants, ou les deux:
+
* Dans le mode Legacy ou BIOS, l'OS est chargé en exécutant les instructions écrites dans un secteur d'amorçage.
* En mode EFI, le chargeur du système d'exploitation est un programme stocké dans un fichier exécutable, situé dans un répertoire d'une partition EFI System (ou ESP pour EFI System Partition).

[[UC]]CPU::
Le processeur ou l'unité centrale de traitement exécute les instructions des programmes.

[[command]]Commande:: Une commande est définie par https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_104[POSIX] comme "une directive à un shell <<shell, >> pour effectuer une tâche spécifique.
+
La tâche à effectuer peut être une <<application, application>> ou un <<utility, utilitaire>>.
+
La structure de base des commandes shell est définie dans le chapitre https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09[2.9 Commandes Shell] de la spécification POSIX.
+
Des exemples de commandes sont fournis dans <<bash shell, [shell]>>.

[[console]]Console:: Le mot "console" fait référence au début des systèmes de l'ordinateur, lorsque l'administrateur système tapait des commandes sur un périphérique, composé d'un clavier et une imprimante, liés à l'ordinateur, les commandes saisies et la réponse de l'ordinateur étant tous les deux imprimé sur la console.
+
Dans les ordinateurs personnels, l'utilisateur tape les commandes sur le clavier et leur sortie est imprimée sur un écran, qui peuvent être séparés ou intégrés à l'ordinateur comme dans un ordinateur portable.

[[device]]Appareil::

Un périphérique d'ordinateur ou un objet qui apparaît à l'application comme tel.[POSIX]

[[directory]]Répertoire::
Un répertoire est un autre nom pour un dossier. Les systèmes de fichiers utilisent des répertoires pour organiser les fichiers au sein des partitions.
+
Les répertoires peuvent contenir des fichiers et d'autres répertoires. La structure résultante peut être représentée comme une arborescence à l'envers. Le répertoire supérieur de un disque est nommé le répertoire racine. Sous Linux, le caractère / sépare les niveaux de l'arborescence. / représente à lui seul le répertoire racine, /home hénerge les fichiers appartenant aux utilisateurs, /home/didier héberge les fichiers appartenant à l'utilisateur didier. /root héberge les fichiers de l'utilisateur nommé root (l'administrateur du système). Remarque : « root» peut faire référence au répertoire de niveau supérieur ou à l'administrateur du système.

[[drive]]Lecteur (Drive an Anglais)::
Un lecteur est un périphérique qui stocke des données non volatiles, ce qui signifie que les données ne sont pas effacées lorsque l'alimentation est éteinte. Exemples: disques durs, SSD, clés USB, lecteurs de cartes SD, eMMC.
+
Le support stockant les données peut être connecté en permanence au lecteur ou amovible comme les cartes SD, les clés USB et les lecteurs connectés via USB.
+
Un système d'exploitation installé sur un support amovible ou un lecteur externe est dit portable: il peut être déplacé d'un ordinateur à un autre.

[[display_manager]]Gestionnaire d'affichage::
Un gestionnaire d'affichage (ou gestionnaire de connexion) est un logiciel qui affiche une fenêtre sur l'écran dans lequel il demande le nom de connexion et le mot de passe de l'utilisateur, puis démarre le l'environnement graphique choisi par cet utilisateur.

[[encryption]]Chiffrement::
Le cryptage est le processus de conversion de données sous une forme non reconnaissable (« crypté »). Il est communément utilisé pour protéger les informations sensibles afin que seules personnes autorisées puissent les voir. Un seul fichier ou répertoire, une partition aussi bien qu'une unité entière peuvent être cryptés, ce qui le rend accessible seulement après que a tapé un petit texte appelé mot de passe, gardé secret.

[[file]]Fichier::
Un fichier informatique est un ensemble de données numériques collectées sous le même nom, enregistrées sur un support de stockage permanent, appelé stockage de masse, tel qu'un disque dur, un SSD, un DVD, une carte SD ou une clé USB et géré comme une unité.
+
Les fichiers peuvent contenir des données telles que des textes, des images, des sons, des vidéos ou des programmes informatiques.

[[file_system]]Système de fichiers::
Un système de fichiers est un logiciel qui gère les fichiers et répertoires dans une partition. Il mémorise l'emplacement dans le support physique des données contenues dans les fichiers, permettant de les lire ou de les écrire. Des exemples de systèmes de fichiers couramment utilisés sont vfat, ntfs, ext4, f2fs. Cette commande liste tous les systèmes de fichiers permettant de lire les données contenues dans une partition à partir de Linux :
+
----
cat /proc/filesystems|grep -v nodev
----

[[firmware]]Micrologiciel (Firmware en Anglais)::
Un firmware est un logiciel qui initialise et vérifie le matériel, puis sélectionne et charge dans la RAM le système d'exploitation, ou démarre un logiciel appelé un gestionnaire de démarrage qui le fera. Le micrologiciel est contenunu dans des unités de mémoire non volatiles telles que ROM, EPROM ou mémoire flash. C'est le premier logiciel lancé lorsque démarre un ordinateur. Il fournit un menu permettant de configurer le matériel et de sélectionner dans quel mode (Legacy ou EFI) démarrer, et dans quel ordre chercher le système d'exploitation ou une autre application (comme le gestionnaire de démarrage GRUB) à exécuter.

[[kernel]] Noyau::
Un noyau Linux est le logiciel au cœur d'un système Slint qui gère les interactions entre les applications et le matériel.
+
Il se présente comme un seul fichier, installé dans le répertoire /boot. Par exemple, le fichier /boot/vmlinuz-generic-5.12.11 est un noyau provenant du paquet kernel-generic.
+
Au démarrage, le noyau est copié en mémoire vive ou RAM.

[[initrd]]Initrd::
Un initrd (plus précisément un initramfs ou un système de fichiers RAM initial pour Slint) est un système Linux fourni sous forme de fichier archive compressé. Au démarrage, juste après que le noyau ait été chargé en RAM l'initrd est également chargé en mémoire. Son fichier /init s'exécute : il charge les modules du noyau nécessaires en RAM, enregistre les périphériques, éventuellement déverrouille le périphérique hébergeant le système de fichier racine, monte les pseudo systèmes de fichiers puis passe la main au système de fichiers racine pour démarrer le système.
+
Un initrd se présente comme un fichier unique, installé dans le répertoire d'amorçage. Par exemple, le fichier initrd-generic-5.12.11 est un initrd

[[live_system]]Système en mémoire vive (live system en Anglais)::
Un système en mémoire vive est un système d'exploitation qui, au lieu d'être installé dans un appareil comme un disque dur ou SSD, est entièrement en <<RAM>>.
+
An initrd is also a live system, and so is a Slint installateur wich is basically an initrd.

[[partition]]Partition::
Une partition est une section d'un support de stockage, comme un disque dur ou un SSD. Il est traité par le système d'exploitation comme un volume logique séparé, ce qui le rend fonctionnel comme un périphérique séparé.

[[partition_table]]Table de partitions::
Une table de partitions est la structure permanente qui enregistre la façon dont les informations sont disposées sur un média, enregistrant principalement le début et la fin de chaque partition sur le média.
+
Les types les plus courants de tables de partitions sont la table de partitions DOS, initialement utilisée par le système d'exploitation MS-DOS, et la table de partition GUID ou GPT, qui permet de gérer plus de partitions et de disques plus grands.

[[program]]Programmes::
Une séquence préparée d'instructions au système pour accomplir une tâche définie. Le terme "programme" englobe les applications écrites dans le langage de commande Shell, des langages de traitement d'entrées complexes (par exemple, awk, lex, sed et ainsi de suite) et des langages de haut niveau. [POSIX]

[[RAM]]RAM::
RAM signifie Mémoire à accès aléatoire (pour Random Access Memory) plus communément appelée méméoire vive en Français. Ce type de disporitif stocke des données volatiles, ce qui signifie que les données sont effacées lorsque l'alimentation est éteinte.

[[shell]]Shell:: Programme qui interprète les séquences d'entrée de texte en tant que commandes. Il peut fonctionner sur un flux d'entrée ou il peut interactivement demander et lire des commandes à partir d'un terminal. La syntaxe des commandes pouvant être interprétées par la coque peut varier en fonction de celui utilisée, mais elle est principalement définie dans le chapitre https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html [ 2. Shell Command Language ] de la spécification POSIX.
+
Slint fournit plusieurs programmes faisant office de shell, listés dans le fichier /etc/shells. Le shell *bash* est utilisé par défaut.

[[swap]]Swap::
Un espace d'échange (Swap en Anglais) est utilisé pour stocker provisoirement des données précédemment en mémoire vive ou RAM sur un périphérique comme un disque dur ou un SSD, soit parce que sinon la RAM deviendrait pleine, soit pour libérer de l'espace ansd la mémoire vive pour y stocker les données les plus fréquemment utilisées. L'espace d'échange peut être une partition sur un disque de type 'Linux swap' ou un fichier régulier stocké dans une partition existante. Il y a aussi le 'swap en zram': dans ce cas, les données sont stockées en RAM mais sous forme compressée.

[[terminal]]Terminal::
Historiquement, un terminal était un périphérique physique composé d'un clavier et d'un écran utilisé pour taper des commandes et recevoir des réponses d'un ordinateur distant.
+
De nos jours, les commandes peuvent être tapées en mode console (ou texte) ou en mode graphique .

[[utility]]Utilitaire::
Un utilitaire est un programme qui peut être invoqué par son nom à partir d'un shell (c'est aussi le cas de certaines <application,applications>>).
+
Les utilitaires font partie du système d'exploitation (mais pas du noyau). Ils exécutent des fonctions liées au système, telles que la lister contenu du répertoire, vérifier des systèmes de fichiers, réparer des systèmes de fichiers ou extraire des informations sur l'état du système.
+
Un utilitaire peut être invoqé comme un programme séparé qui s'exécute dans un processus différent de celui su shell ou il peut être intégré au shell.
+
Par exemple, la commande echo (la directive pour effectuer une tâche spécifique) peut être implémentée de telle sorte que l'utilitaire echo (la logique qui exécute la tâche d'écho) soit dans un programme séparé ; par conséquent, il sera exécuté dans un processus différent de celui de celui du shell. Pratiquement cela signifie que dans ce cas, l'utilitaire est un programme distinct du shell
+
Inversement, la logique qui exécute l'utilitaire echo pourrait être intégrée dans l'interpréteur du langage de commande ; il pourrait donc s'exécuter dans le même processus que le shell. Un tel utilitaire est dit « intégré » au shell.

[[virtual_terminal]]Terminal virtuel::
Un terminal virtuel est un logiciel qui simule un terminal physique, périphérique composé d'un clavier et d'un écran permettant de communiquer à distance avec un ordinateur .
