
= Handboek Slint (versie 15.0)
:toc: left
:toclevels: 2
:toc-title: Content
:pdf-themesdir: themes
:pdf-theme: default
:sectnums:

== Inleiding

=== Over Slint

Slint is een meertalige, eenvoudig te installeren, veelzijdige en beginnersvriendelijke op http://www.slackware.com/[Slackware] gebaseerde en voor visueel beperkten toegankelijke https://en.wikipedia.org/wiki/Linux_distribution[Linux distributie].

Een Slint systeem is na installatie volledig functioneel en kan worden aangepast om aan de meest uiteenlopende computervereisten te voldoen.

==== Functionaliteit

Je kunt kiezen uit twee installatiemethoden: Automatisch (het installatieprogramma bereidt het door de gebruiker gekozen station voor en installeert hier Slint op) en Handmatig (het installatieprogramma geeft de gebruiker de mogelijkheid zelf het gekozen station te partitioneren en te formatteren en er Slint op te installeren). Het installatieprogramma bevat de eventueel benodigde documentatie.

Slint is door middel van spraak en braille ook toegankelijk voor visueel beperkte gebruikers. Dit geldt voor de installatie maar ook voor het gebruik via een terminal en/of grafische omgevingen.

Op elk Slint systeem wordt een uitgebreide collectie software voor servers, desktops en laptops geïnstalleerd inclusief de volledige grafische desktopomgevingen MATE en LXQt en een aantal lichtgewicht windowmanagers. MATE en LXQt geven gemakkelijk toegang tot alle programma's en systeembewerkingen zoals het automatisch aankoppelen van verwijderbare media, het melden van beschikbare updates voor geïnstalleerde software, directe internettoegang en het afsluiten, herstarten of in slaapstand brengen van het systeem.

Voor geïnternationaliseerde toepassingen zal de gekozen taal worden gebruikt.

Het Slint Dashboard centraliseert de toegang tot hardware- en systeeminstellingen, pakkettenbeheer, documentatie en (systeem)hulpprogramma's.

Slint bevat standaard veel toepassingen om documenten in verschillende formaten te maken, te bekijken en te converteren, te communiceren per e-mail, tekst- en audiochat, audio- en video af te spelen, onderling documenten te verzenden en te ontvangen, audio-, video- en grafische documenten te bewerken en applicaties te ontwikkelen. Slint is te gebruiken als een volwaardige server via een console en/of met behulp van één van de verschillende bijgeleverde desktops.

Veel toepassingen zijn met behulp van een ruime keuze aan TTS en bijbehorende stemmen toegankelijk voor visueel beperkten. Mocht je toch nog andere wensen, dan zijn die voor zowel de console als voor grafische omgevingen eenvoudig te installeren.

Verschillende interne tools vergemakkelijken het beheer en de configuratie van je Slint systeem.

Nog veel meer applicaties zijn eenvoudig als softwarepakket via een eenvoudige opdracht of enkele muisklikken te installeren. Duizenden softwarepakketten zijn binnen handbereik!

Als Slint gebruiker wordt je op de hoogte gehouden van upgrades voor de geïnstalleerde pakketten als deze beschikbaar zijn en indien gewenst worden deze geïnstalleerd. Dit houdt je systeem veilig.

De standaard ingestelde voorkeurstoepassingen kunnen naderhand eenvoudig worden aangepast.

==== Content, versions and release model.

Het Slint installatieprogramma voorziet alleen in een volledige installatie.

Slint volgt een "semi-rolling release model" wat betekent dat gedurende de levenscyclus van een bepaalde softwareversie niet alleen beveiligingsupdates en grote bugfixes maar ook selectieve software-updates met verbeteringen en nieuwe features worden geïnstalleerd. Dit geldt met name voor de software die Slint toegankelijk maakt voor slechtzienden zoals schermlezers.

We adviseren gebruikers zo snel mogelijk naar de laatst beschikbare versie over te stappen. Hierbij raden we aan een volledige backup van je waardevolle gegevens te maken en deze na de installatie weer terug te zetten.

=== Over dit boek en andere informatiebronnen

Dit boek is bedoeld om de beginnende Slint-gebruiker te helpen bij de installatie en het gebruik van Slint. De concepten en afspraken specifiek voor Slint en andere Linux-distributies komen aan bod en er is een woordenlijst.

We proberen gebruikers van Windows en MacOS, maar ook die van andere distributies zoals Ubuntu zo veel mogelijk tegemoet te komen.

Op een Slint systeem is voor de meeste geïnstalleerde softwarepakketten documentatie aanwezig. We zullen in dit boek aangeven waar je die kunt vinden.

Andere informatiebronnen zijn:

* De informatie op de website van de makers van de in Slint opgenomen software.
* http://docs.slackware.com/[Het Slackware documentatieproject] en dan met name de http://docs.slackware.com/howtos:start[HOWTO artikelen]. Veel hiervan zijn rechtstreeks van toepassing op Slint, sommige in aangepaste vorm.
* De ArchWiki biedt behalve voor de Arch distributie zelf veel nuttige artikelen over software die ook in Slint aanwezig is. Het zoeken naar "arch wiki mate" bijvoorbeeld leidt naar https://wiki.archlinux.org/index.php/MATE[deze pagina over MATE]. Let op: de hier aanwezige informatie geldt soms in aangepaste vorm omdat Slint en Arch op sommige punten van elkaar verschillen. Arch gebruikt bijvoorbeeld systemd als init-systeem en het kan zijn dat bepaalde software in Slint en Arch standaard verschillend moet worden geconfigureerd.
* En natuurlijk kan een zoekmachine via internet vaak helpen antwoorden te vinden op vragen en bij het oplossen van problemen.
// Support

=== Ondersteuning

Hulp kun je vinden via deze kanalen:

* De Slint mailing list is het primaire support kanaal. Je kunt je hiervoor registreren door een e-mail te sturen naar slint-request@freelists.org met het onderwerp: 'subscribe' en vervolgens de ontvangen bevestigingsmail te beantwoorden. Stuur voor meer informatie een e-mail naar slint-request@freelists.org met als onderwerp 'commands' of 'help'. Na registratie kun je voor je vragen e-mailen naar slint@freelists.org.
* De archieven van de mailing list die https://www.freelists.org/archive/slint[hier] beschikbaar zijn.
* Op IRC: chat via het #slint kanaal, server irc.libera.chat, registratie hiervoor is niet nodig.
* Mumble: server slint.fr (op afspraak die je maakt via een ander kanaal).
* Het https://forum.salixos.org/viewforum.php?f=44[Slint forum]: gehost door onze vrienden bij Salix (een andere Slackware afgeleide). Hiervoor moet je je wel registreren.


To find out more, see the links under Information in the Slint Dashboard or just type: slint-doc in a terminal after installation.

=== Vertaling en andere bijdragen aan het Slint-project

Slint zoekt vertalers! Lees als je wilt helpen met vertalen de instructies in https://slint.fr/doc/translate_slint.html[Vertaal Slint].

De vertaalbestanden worden gehost op https://crowdin.com/project/slint[Crowdin].

Als je aan het Slint-project wilt bijdragen door te helpen met andere taken kun je posten op de mailing list of stuur je een mail naar: didieratslintdotfr. Uiteraard zijn vertalers ook welkom op de mailing list!
// Acknowledgments

=== Dankwoord

Het Slint-project bestaat vooral dankzij het werk van de vertalers van Slint en andere bijdragers, bedankt allemaal!

Dank ook aan George Vlahavas voor zijn advies en tools en aan de medewerkers van het SlackBuilds.org project, met wiens hulp veel extra software voor Slackware en afgeleiden kan worden gecompileerd.

Slint is gebaseerd op Slackware dat is ontwikkeld door Patrick J. Volkerding en zijn team. Bedankt! Ik moedig alle Slint gebruikers aan door middel van een donatie financieel bij te dragen aan Slackware en Salix.

De Slint repositories worden gratis gehost door Darren 'Tadgy' Austin. Ik moedig alle Slint gebruikers aan bij te dragen aan de financiering van de host https://slackware.uk/

Links voor financiele bijdragen: +
https://www.patreon.com/slackwarelinux[Become a Slackware patron] or https://paypal.me/volkerdi[Support Slackware] +
Volg de links bovenaan http://slackware.uk/slint/x86_64/slint-15.0/[deze pagina] om Slackware UK te steunen +
https://salixos.org/donations.html[Donations to Salix]

== Slint installeren

Dit deel van het handboek doorloopt het proces van het downloaden van Slint, het controleren van het ISO-beeldbestand met een controlesom, het schrijven van het ISO-bestand naar een installatiemedium, het partitioneren van je harde schijf en beschrijft in het kort het installatieproces zelf.

=== Vereisten

De huidige Slint versie kan worden geïnstalleerd op computers die aan de volgende eisen voldoen:

* Architectuur: x86_64 (64-bit CPU), ook bekend als AMD64
* Voor het automatisch partitioneren een harde schijf van minimaal 50G
* Voor het handmatig partitioneren een Linux partitie van minimaal 50G, een EFI systeempartitie en een BIOS partitie op dezelfde schijf.
* Slint kan worden geïnstalleerd op harde schijven, SSD's, NVME's, eMMC's, USB-sticks en SD-cards (bij voorkeur in een USB behuizing).
* RAM: minstens 2G
* Een beschikbare DVD-drive of USB aansluiting met firmware waarmee van DVD of USB-stick kan worden opgestart. Een lege beschrijfbare DVD of een USB-stick van minimaal 5G kunnen als installatiemedium worden gebruikt

NOTE: Secure Boot moet zijn uitgeschakeld om Slint te kunnen installeren.

=== Functies van het installatieprogramma

* Het installatieprogramma is een "live systeem" dat in het geheugen wordt uitgevoerd: er zal niets aan het al geïnstalleerde systeem worden gewijzigd tenzij en totdat jij daar opdracht toe geeft.
* Het installatieprogramma is voor visueel beperkte gebruikers volledig met braille en spraak te gebruiken met behulp van de "Speakup" schermlezer.
* Het beschikt over alle benodigde tools om de vereiste partities tijdens handmatige installatie voor te bereiden.
* In automatische installatiemodus hoeft de gebruiker alleen vragen in contextuele vorm te beantwoorden.
* Als Slint als enige OS op een verwijderbaar medium verbonden via USB wordt geïnstalleerd is het "portable". D. w. z. bruikbaar op iedere computer die vanaf USB kan opstarten.
* Het installatieprogramma kan de schijf waarop Slint als het enige systeem is geïnstalleerd/n versleutelen. Dit voorkomt diefstal van de gegevens die er op aanwezig zijn in geval van verlies/n of diefstal van de machine of van een verwijderbaar apparaat.
* Slint kan op zijn eigen partitie maar tijdens handmatige installatie ook op een bestaande partitie naast een ander hierop aanwezig systeem worden geïnstalleerd.

=== Voorbereiding

<<download_and_verify,Download en controleer Slint ISO image>> +
<<write_the_iso,Schrijf de ISO image naar een installatiemedium>> +
<<prepare_partitions_for_Slint,Optioneel, maak partities voor Slint>>

[[download_and_verify]]
==== Downloaden en controleren van een Slint ISO-beeldbestand

De laatste versie van de Slint-distributie is 15.0

De laatste installatie-image is altijd beschikbaar op https://slackware.uk/slint/x86_64/slint-15.0/iso[deze locatie]

[TIP]
====
Als je Slint versie 15.0 al gebruikt is het niet nodig om helemaal opnieuw te installeren bij het beschikbaar komen van een nieuwe ISO-image omdat deze slechts nieuwe functies aan het installatieprogramma en geüpgradede pakketten toevoegt die ook bij het reguliere up to date houden van je systeem worden geïnstalleerd.
====

De bestandsnaam van onderstaand ISO-beeldbestand is bedoeld als voorbeeld en dien je tijdens het downloaden te wijzigen in de actuele naam.

Een internet zoekopdracht "check sha256sum windows" vertelt je hoe je het ISO-beeldbestand onder Windows kunt controleren.

Als je Linux gebruikt kun je het ISO-beeldbestand en de sha256 checksum met de volgende opdrachten downloaden:
----
wget https://slackware.uk/slint/x86_64/slint-15.0/iso/slint64-15.iso
wget https://slackware.uk/slint/x86_64/slint-15.0/iso/slint64-15.iso.sha256
----

Om de integriteit van de gedownloade bestanden te controleren, typ je de volgende opdracht:
----
sha256sum -c slint64-15.0.iso.sha256
----

Het resultaat moet zijn : OK +
Download anders de bestanden opnieuw.

[[write_the_iso]]
==== Het ISO-beeldbestand naar een installatiemedium schrijven

Je kunt een DVD of een USB-stick als installatiemedium gebruiken.

[[make_a_bootable_usb_stick]]
===== Een opstartbare USB-stick maken

Steek de USB-stick op een ++Linux++ systeem in een USB-poort en controleer de apparaatnaam ervan met de volgende opdracht:

----
lsblk -o model,name,fstype,mountpoint
----

[WARNING]
====
Controleer zorgvuldig de uitvoer van het commando om er zeker van te zijn dat je niet de apparaatnaam van een harde schijfpartitie invoert in plaats van de apparaatnaam van je USB-stick. Alle aanwezige gegevens op de USB-stick of op een foutief gekozen harde schijfpartitie zullen **ONHERSTELBAAR VERLOREN GAAN**.
====

Stel dat de apparaatnaam van de USB-stick /dev/sdb is. Deze naam kan op jouw systeem anders zijn dus neem de volgende opdracht niet blind over. De schrijfwijze van het commando om het Slint ISO-beeldbestand naar een USB-stick te schrijven die zich in /dev/sdb bevindt is als volgt:

----
dd if=slint64-15.0.iso of=/dev/sdb bs=1M status=progress && sync
----

[NOTE]
====
In het bovenstaande commando verwijst **if=** naar het pad van het Slint ISO-beeldbestand en **of=** naar de apparaatnaam van de USB-stick. Die kunnen voor jouw systeem dus anders zijn.
====

Onder ++Windows++ kun je het programma http://rufus.akeo.ie/[Rufus] gebruiken. Het is gratis en open-source.

[[make_a_bootable_DVD_disc]]
===== Een opstartbare DVD maken

Plaats op een ++Linux++ systeem de beschrijfbare DVD in het station en typ de volgende opdracht:

----
xorriso -as cdrecord -v dev=/dev/sr0 -eject slint64-15.0.iso
----

Zorg ervoor dat je het volledige pad naar het Slint ISO-beeldbestand opgeeft.

Onder ++Microsoft Windows 2000/XP/Vista/7++ kun je een DVD maken met het programma http://infrarecorder.org/[InfraRecorder]. Het is gratis en open-source.

Onder ++Microsoft Windows 7/8/10++ kun je het http://windows.microsoft.com/en-US/windows7/Burn-a-CD-or-DVD-from-an-ISO-file[Windows hulpprogramma voor het branden van ISO-bestanden] gebruiken dat met Microsoft Windows wordt meegeleverd.
// Prepare
[[prepare_partitions_for_Slint]]
==== Optioneel het voorbereiden van de Slint partities

Een partitie 'formatteren' betekent hier: het maken van een bestandssysteem om de bestanden die het bevat te kunnen beheren.

Na het typen van 'start' type je 'm' voor handmatig partitioneren en selecteer je als eerste de root systeempartitie aangekoppeld op "/" en het te gebruiken bestandssysteem waaronder btrfs, ext4, xfs.

Het installatieprogramma toont een keuzelijst met alleen niet versleutelde Linux partities (ook wel Linux bestandssysteem genoemd) van minimaal 50G. Deze mag al geformatteerd zijn maar alle bestanden hierop zullen bij het maken van het nieuwe bestandssysteem verloren gaan.

Handmatige partitionering vereist op de schijf met het root bestandssyteem ook de aanwezigheid van:

* Een niet geformatteerde BIOS opstartpartitie van minimaal 3M.
* Een volgens de UEFI specificatie 'fat' (of 'vfat') geformatteerde EFI systeempartitie van minimaal 32M

Het gebruik van bestaande Slint partities of het maken hiervan is aan de gebruiker. Reeds geïnstalleerde systemen met BIOS opstart en EFI partities blijven intact, alleen de root partitie zal (opnieuw) worden geformatteerd.

Het installatieprogramma bevat diverse partioneringsprogramma's: cfdisk, fdisk, sfdisk, cgdisk, gdisk, sgdisk en parted. De programma's met een "g" in hun naam kunnen alleen overweg met GPT schijven, parted met zowel DOS als GPT partities. fdisk, cfdisk en sfdisk kunnen overweg met DOS partities. Ook zijn wipefs (om bestaande partitietabellen en bestandssysteemhandtekeningen te wissen) en partprobe (om de kernel te informeren over partitiewijzigingen) aanwezig. De programma's blkid en lsblk geven informatie weer over block devices en partities.

Uiteraard kun je de partities ook vanaf een ander systeem maken voordat je het installatieprogramma start.
// Installation

=== Slint installatie
<<Start_of_the_installation,De installatie starten>> +
<<Overview_of_Slint_Installation,Overzicht van het installatieproces>> +
<<Usage_of_the_installer,Gebruik van het installatieprogramma>> +
<<Encryption,Slint op een versleutelde root partitie>> +
<<Speakup,Sneltoetsen voor de Speakup schermlezer>> +
<<first_steps_after_installation,Eerste stappen na de installatie>>

[[Start_of_the_installation]]
==== De installatie starten

Stel indien nodig de firmware van de machine in om van een voorbereidde DVD of USB-stick op te kunnen starten.

Plaats het installatiemedium (DVD of USB-stick) en start de computer opnieuw op. Voor slechtzienden klinkt een geluid wanneer het opstartmenu wordt weergegeven.

Start het installatieprogramma door op Enter te drukken.

Het installatieprogramma zal eerst je geluidskaarten proberen te detecteren.

Dit laat je een werkende geluidskaart als standaard instellen en gebruiken voor spraak tijdens de installatie door visueel beperkte gebruikers.

Als het installatieprogramma meer dan één geluidskaart vindt zegt het in het engels voor elke kaart: press Enter to choose this sound board <sound card id> +
Druk Enter zodra je dit hoort om te bevestigen dat je de kaart wilt gebruiken en dat deze werkt. Deze instelling wordt op het nieuwe systeem opgeslagen in /etc/asound.conf.

Bij de volgende stap bevestig je dat je tijdens de installatie spraak wilt gebruiken (typ s en Enter) of niet (alleen Enter). Braille is tijdens de installatie altijd beschikbaar.

Vervolgens kun je de tijdens de installatie te gebruiken taal kiezen of wijzigen. Het installatieprogramma wordt dan verder in de gekozen taal weergegeven mits de vertaling in die taal compleet is.

Als je extra kernel-parameters wilt meegeven aan de boot opdrachtregel doe je het volgende voor je op Enter drukt:
[NOTE]
====
Wees je er van bewust dat tijdens het typen US toetsenbordindeling gebruikt wordt. +
Ctrl+x betekent "Houdt de Ctrl of Control toets ingedrukt alsof het de Shift-toets is en druk de x-toets"
====
----
Druk op de e-toets
Druk drie keer op pijl omlaag
Druk op de End-toets
Druk op de spatiebalk.
Typ vervolgens de kernel parameters (zie voorbeelden hieronder)
Ctrl+x om op te starten (druk nog geen Enter!)
Druk dan pas op Enter om te starten.
----

Om bijvoorbeeld de speakup driver voor je hardware synthesizer te configureren, zou je de volgende kernel parameter kunnen typen:
----
speakup.synth=apollo
----
Je kunt op de boot opdrachtregel ook op de volgende manier de instellingen voor je braille-apparaat opgeven:
-----
brltty=<driver code>,<device>,<text table>
-----
Een Papenmeier apparaat met een Franse teksttabel dat via USB aangesloten is installeer je bijvoorbeeld als volgt:
-----
brltty=pm, usb:,fr_FR
-----
NOTE: Een via USB verbonden braille apparaat zou altijd moeten worden herkend, alleen de taal zou niet goed kunnen zijn als je deze niet vooraf hebt ingesteld.

Aangezien er geen time-out is, zal het opstarten pas beginnen als je op [Enter] drukt.

Spraak en Braille zijn beschikbaar vanaf het begin van de installatie.
// Overview
[[Overview_of_Slint_Installation]]
==== Overzicht van het installatieproces

Het installatieprogramma detecteert als eerste de aanwezige schijven en partities voor mogelijke installatie-opties en laat je kiezen tussen het automatisch of handmatig voorbereiden van de door Slint te gebruiken partities.

Als je "handmatig" kiest krijg je een lijst te zien met Linux partities (van minimaal 50G) waarop Slint kan worden geïnstalleerd. Selecteer de gewenste partitie en het type bestandssysteem dat er op zal wordt gemaakt: btrfs, ext4 of xfs zoals aangegeven in <<prepare_partitions_for_Slint,Optioneel voorbereiden van partities voor Slint>>

Als je 'auto' kiest, krijg je de stations te zien waarop Slint kan worden geïnstalleerd (ten minste 50G groot) en zal het btrfs bestandssysteem worden gebruikt.

In het geval van btrfs worden subvolumes met gecomprimeerde bestanden aangemaakt voor//home en /snapshots en /swap voor een swap bestand. Met 'Copy on write' is het mogelijk snapshots te maken en een mislukte systeem-update ongedaan te maken. Tools voor het beheren van de snapshots zijn in Slint aanwezig.

In beide modi kiest de gebruiker welke bestaande Linux-en Windows-partities automatisch worden aangekoppeld na het opstarten van Slint en de namen van de aankoppelpunten wat de toegang tot bestaande systemen en gegevens vanuit Slint vergemakkelijkt.

Vervolgens wordt de gebruiker voorgesteld om de root systeempartitie te versleutelen waarmee gegevensverlies kan worden voorkomen in geval van verlies of diefstal van de machine of het station waarop Slint is geïnstalleerd. Indien positief bevestigd legt het installatieprogramma de wachtwoordzin vast waarmee deze partitie kan worden ontgrendeld. De gebruiker zal hier tijdens het opstarten door GRUB om worden gevraagd om het opstartmenu weer te geven.

Uiteindelijk toont het installatieprogramma de door jou gemaakte keuzes en vraagt je die al dan niet te bevestigen. Tot nu toe is er nog niets aan het geïnstalleerde systeem gewijzigd zodat je veilig kunt annuleren en zonder gevolgen opnieuw 'start' kunt typen of opnieuw kunt opstarten.

Dan wordt, in geval van auto-partitionering, de Slint rootpartitie versleuteld indien gewenst en geformatteerd en worden de eerste softwarepakketten geïnstalleerd.

Als je voor een versleutelde schijf hebt gekozen, typ je de wachtwoordzin die zal worden gebruikt om de schijf steeds bij het opstarten te ontgrendelen.

Je kiest een wachtwoord voor gebruiker "root". Dit is de systeembeheerder die alle bevoegdheden heeft.

Je geeft ook de gebruikersnaam en het wachtwoord van een gewone gebruiker.

Je geeft aan of je Braille-uitvoer nodig hebt en of je je wilt aanmelden in tekst of grafische modus. Als je tijdens de installatie de Engelse (US) taal hebt gebruikt, kies je de taal die je in het geïnstalleerde systeem wilt gebruiken. Anders stelt het installatieprogramma dezelfde taal in als tijdens de installatie.

Het installatieprogramma probeert nu een internetverbinding te maken om een tijdzone die overeenkomt met je geografische locatie voor te stellen of uit een lijst te laten kiezen.

Er wordt je gevraagd of je Braille nodig hebt en dan of je wilt starten in een console of in een grafische omgeving tenzij je spraak hebt gebruikt tijdens de installatie of dat je Braille nodig hebt. In dat geval belandt je voor alle veiligheid na het opnieuw opstarten in een console.

Dan maakt het installatieprogramma een wisselbestand. Dit kan even duren dus wees geduldig.

Alle andere pakketten worden op de schijf geïnstalleerd. Indien verbonden met internet wordt de meest recente versie van elk pakket inclusief die beschikbaar gekomen zijn na het uitkomen van de ISO-image gedownload en geïnstalleerd.

Afhankelijk van de hardware duurt de installatie van alle pakketten 10 tot 40 minuten.

Er wordt je gevraagd een desktop te selecteren (zelfs als je in een console begonnen bent) waaronder fvm, lxqt, mate en wmaker. Na de installatie krijg je wanneer je bent opgestart in een console door het typen van 'xwmconfig' een nog uitgebreidere keuze

Hierna wordt het systeem geconfigureerd en de GRUB boot manager geïnstalleerd. Slint kan opstarten in zowel Legacy als EFI modus. Het boot- menu heeft een "rescue" keuzemogelijkheid om elk geïnstalleerd OS te herkennen en op te starten.

Voordat je opnieuw opstart is het mogelijk een voorbeeld van het opstartmenu weer te geven.

Verwijder tenslotte het installatiemedium en herstart je nieuwe Slint-systeem.
// Usage_installer
[[Usage_of_the_installer]]
==== Gebruik van het installatieprogramma

Als je bekend bent met de Linux console kun je dit onderwerp overslaan.

Hieronder wordt het hoofdmenu van het installatieprogramma weergegeven:
....
Welkom bij het Slint installatieprogramma! (versie 15)

Je kunt nu typen (zonder de aanhalingstekens):

'doc' om de functies en het gebruik van het installatieprogramma te leren kennen.
'start' om de installatie te starten.

Het installatieprogramma kan de schijf waarop Slint wordt geïnstalleerd voorbereiden/n
en de benodigde partities aanmaken. Je kunt dat ook zelf handmatig doen met behulp van/n
de aanwezige hulpprogramma's. Typ 'start' als je hiermee klaar bent. Je kunt ook het/n
installatieprogramma verlaten en een programma als gparted gebruiken waarna je het/n
installatieprogramma weer start.

We raden je aan eerst 'doc' te typen in geval je de Slint rootpartitie wilt versleutelen.
Wanneer je hier mee klaar bent wordt dit menu weer weergegeven.
....

Zodra dit menu wordt weergegeven kun je beginnen met het installatieproces.

Je leest het scherm en typt commando's in een <<virtual_terminal,virtuele terminal>>. Het installatieprogramma beschikt over 4 virtuele terminals die hetzelfde fysieke toetsenbord en scherm gebruiken en tegelijkertijd naast elkaar gebruikt kunnen worden.

Het installatieprogramma start in virtuele terminal 1 genaamd *tty1* maar je kunt naar een andere terminal overschakelen. Je kunt bijvoorbeeld overschakelen naar *tty2* door op *Alt-F2* te drukken en later weer terug naar *tty1* met *Alt-F1* zonder informatie in beide terminals te verliezen. *Alt-F1* betekent: hou de *Alt* toets ingedrukt en druk tegelijkertijd op de *F1* toets.

Dit kan bijvoorbeeld handig zijn voor het lezen van documentatie tijdens de installatie: je kunt overschakelen naar *tty2* waar je de installatie start, weer terug naar *tty1* om de documentatie te lezen en vervolgens weer naar *tty2* om verder te gaan met de volgende installatiestap.

Zo kun je ook de woordenlijst raadplegen tijdens het lezen van andere documenten.

Het installatieprogramma heeft verschillende manieren van interactie met de gebruiker:

* Je voert opdrachten in bij de prompt en leest hun uitvoer.
* Het installatieprogramma stelt een vraag, je typt het antwoord en je bevestigt dit door op Enter te drukken.
* Het installatieprogramma toont een keuzemenu met meerdere opties: je selecteert er één met de pijltjestoetsen omhoog en omlaag en je bevestigt vervolgens je keuze door op Enter te drukken of op Esc om te annuleren.
* Het installatieprogramma geeft informatie weer in een pager. Gebruik de pijltjestoetsen om de vorige of volgende regel te lezen, druk op de spatiebalk om de volgende pagina weer te geven of q om de pager te verlaten.

// Encryption
[[Encryption]]
==== Slint met een versleutelde rootpartitie.

In automatische modus stelt het installatieprogramma voor om de schijf waarop Slint wordt geïnstalleerd als deze volledig aan Slint is toegewezen te versleutelen. Als je hiermee akkoord gaat zal GRUB je telkens als je opstart de wachtwoordzin vragen die je hebt opgegeven tijdens de installatie om de schijf te ontgrendelen voordat het opstartmenu wordt weergegeven. Wees je ervan bewust dat het ontgrendelen van het station even duurt (ongeveer tien seconden).

Met een versleutelde schijf voorkom je diefstal van gegevens die er op staan in geval van verlies of diefstal van de machine of van een verwijderbare schijf. Het beschermt je echter niet als je de computer onbewaakt aan laat staan en alleen als de computer volledig is uitgeschakeld!

Tijdens de installatie zal de Slint systeempartitie evenals de gewenste extra partities worden versleuteld.

De naam van een versleutelde Slint systeem- (of root) partitie is: /dev/mapper/cryptroot.

Dit kun je zien door het uitvoeren van deze opdracht:

----
lsblk -lpo name,fstype,mountpoint /h grep /$
----

Met het volgende resultaat:
----
/dev/mapper/cryptroot ext4   /
----

Het uitvoeren van deze opdracht:

----
lsblk -lpo name,fstype,mountpoint | grep /dev/sda3
----

geeft:

----
/dev/sda3             cryptoLUKS
----

/dev/sda3 is nu een "raw" partitie die de zogenaamde "LUKS header" bevat waar je nooit direct toegang toe zou moeten of hoeven te hebben. Het bevat alles wat nodig is om de partitie /dev/mapper/cryptroot die eigenlijk jouw gegevens bevat (in dit voorbeeld het Slint-systeem) te versleutelen.

[WARNING]
====
Als je de wachtwoordzin vergeet, zullen alle gegevens in het station onherstelbaar verloren gaan! Dus noteer deze wachtwoordzin of sla hem op en bewaar hem meteen op een veilige plaats.

Schijven gaan vroeg of laat kapot. Als dat gebeurt en de schijf is versleuteld gaan je gegevens verloren. Regelmatig een back-up maken van je waardevolle gegevens is dus niet optioneel maar essentieel!

Maak ook een back-up van de LUKS header zodat je die kunt herstellen als de LUKS partitie om welke reden dan ook zou beschadigen. Het commando hiervoor zou in ons voorbeeld kunnen zijn:
----
luksHeaderBackup /dev/sda3 --header-backup-file <file>
----
waar <file> de naam is van het back-up bestand dat je op een veilige plek bewaart.

Voor het herstellen van de back-up typ je:
----
luksHeaderRestore /dev/sda3 --header-backup-file <file>
----

Wijzig nooit de grootte van een partitie van een versleutelde schijf omdat deze hierna voorgoed ontoegankelijk is en de gegevens die er op staan verloren gegaan zullen zijn! Als je echt meer ruimte nodig hebt moet je een backup maken van alle bestanden die je wilt behouden, Slint opnieuw installeren en de geback-upte bestanden terugzetten.

Kies een sterke wachtwoordzin, zodat die voor een inbreker te lastig is om die te raden en hij het uiteindelijk zal opgeven.

Rommel nooit aan de zogenaamde "LUKS-header" op de 'raw' partitie (in ons voorbeeld /dev/sda3 op de Slint systeempartitie). Maak geen bestandssysteem aan in deze partitie, laat het geen deel uitmaken van een RAID array en schrijf er geen gegevens naar toe: hierdoor zullen alle gegevens namelijk onherstelbaar verloren gaan!
====

Om zwakke wachtwoordzinnen te vermijden vereist het installatieprogramma dat de wachtwoordzin bestaat uit:

. Ten minste 8 tekens.
. Alleen niet-geaccentueerde kleine letters en hoofdletters, cijfers van 0 tot 9, spaties en de volgende leestekens:
+
----
 ' ! " # $ % & ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~
----
+
Dit garandeert dat ook een nieuw toetsenbord alle tekens heeft die nodig zijn om het wachtwoord te typen.

. Ten minste één cijfer, één kleine letter, één hoofdletter en één leesteken.

GRUB gaat ervan uit dat er een "VS" toetsenbord wordt gebruikt wanneer je de wachtwoordzin typt. Om deze reden stelt het installatieprogramma als je tijdens de installatie gebruik maakt van een andere dan een "VS"-toetsenbord deze hierop in voordat je de wachtwoordzin typt en hierna weer terug naar de indeling die je hier voor gebruikte. In dit geval spelt het installatieprogramma ook elk ingetypt teken van de wachtwoordzin omdat dit kan verschillen van het teken dat op de toets geschreven staat.

Om de schijf te versleutelen wordt het programma cryptsetup gebruikt. Voor meer informatie hierover typ je na de installatie: +
-----
man cryptsetup
-----
// Speakup
[[Speakup]]
==== Sneltoetsen voor de Speakup schermlezer

Dit hoofdstuk is bedoeld voor gebruikers die een schermleesprogramma nodig hebben maar niet bekend zijn met Speakup.

Zorg er wel voor dat NumLock is uitgeschakeld als je Speakup wilt gebruiken.

De CapsLock-toets gedraagt zich als een Shift-toets. "CapsLock 4" bijvoorbeeld betekent: +
hou de CapsLock-toets ingedrukt als een Shift-toets en druk op 4.

 De eerste sneltoetsen om te onthouden:
 PrintScreen     Schakel speakup aan of uit.
 CapsLock F1     Speakup Hulp (druk spatie om Hulp te verlaten).

 Sneltoetsen voor het wijzigen van instellingen:
 CapsLock 1/2    Verhogen/verlagen van geluidsvolume.
 CapsLock 5/6    Verhogen/verlagen van de spreeksnelheid.

 Sneltoetsen voor tijdens het lezen zelf:
 CapsLock j/k/l   Zeg vorig/huidig/volgend woord.
 CapsLock k (2x)    Spel het huidige woord.
 CapsLock u/i/o    Zeg de vorige/huidige/volgende regel.
 CapsLock y    Zeg de tekst vanaf bovenaan tot aan de cursor.
 CapsLock p    Zeg de tekst vanaf de cursor tot aan het einde.
// First_steps
[[first_steps_after_installation]]
==== De eerste stappen na de installatie

Hier volgen de eerste taken die na de installatie moeten worden uitgevoerd.

In dit document is alle tekst na een # commentaar op de voorgestelde commando's en dient niet ingetypt te worden.

===== Eerste software-update

Na installatie moet het systeem worden bijgewerkt met de meest recente versie van elk programma, evenals nieuwe software die is uitgekomen sinds de voor de installatie gebruikte versie van het ISO-beeldbestand. Dit is vooral van belang als er geen netwerkverbinding beschikbaar was tijdens de installatie omdat dan alleen de pakketten in het distributiemedium -welke verouderd kunnen zijn- werden geïnstalleerd.

De meeste commando's die hieronder worden weergegeven vereisen administratieve rechten gekoppeld aan een specifiek account genaamd 'root' waarvoor je tijdens de installatie een wachtwoord hebt ingegeven.

Om een opdracht als root uit te voeren typ je eerst
----
su -
----
vervolgens typ je het wachtwoord voor 'root' en druk je op Enter voordat je het commando invoert.

Wanneer je klaar bent met het uitvoeren van commando's als 'root' druk je op Ctrl+d of typ je 'exit' om weer de "gewone gebruiker" status terug te krijgen.

Alternatief kan de tijdens de installatie als lid van 'wheel' groep geregistreerde gebruiker of andere leden hiervan typen:
----
sudo <command>
----
daarna weer het root-wachtwoord.

Om het systeem te updaten typ je als 'root' in een console of een grafische terminal:
----
slapt-get --add-keys # haalt de sleutels op om de pakketten te verifiëren
slapt-get -u # werkt de lijst van pakketten op de mirrors bij
slapt-get --install-set slint # downloadt de nieuwe pakketten
slapt-get --upgrade # installeert de nieuwe versies van geïnstalleerde pakketten
dotnew # toont gewijzigde configuratiebestanden
----
Wanneer je dotnew uitvoert accepteer je dat alle oude configuratiebestanden door nieuwe vervangen worden. Dit kun je nu nog veilig doen omdat je nog niets aan het systeem hebt aangepast.

Je kunt ook de grafische varianten van deze toepassingen gebruiken: gslapt in plaats van slapt-get en dotnew-gtk in plaats van dotnew.

Voor meer informatie over slapt-get typ je:
----
man slapt-get
----
of als 'root':
----
slapt-get --help
----
en lees /usr/doc/slapt-get*/README.slaptgetrc.Slint

// Usage
== Slint gebruiken

Dit hoofdstuk beschrijft de manieren waarop je met je Slint-systeem kunt communiceren zodat het doet wat je wilt.

=== Wat is een Slint-systeem?

Slint is een verzameling software die grofweg uit de volgende categorieën bestaat:

* Het besturingssysteem dat bestaat uit de Linux <<kernel, kernel>> en <<utilities, hulpprogramma's>>. Het fungeert als een interface tussen de gebruiker, de applicaties en de hardware.
* De <<Applications, applicaties>> die de taken uitvoeren die gebruikers gedaan willen krijgen.

Slint kan gebruikt worden in twee modi die zich onderscheiden door het uiterlijk van het scherm en de manier waarop ze met het systeem communiceren:

* In tekstmodus typ je opdrachten die worden geïnterpreteerd door een <<shell, shell>>. Deze commando's kunnen een hulpprogramma of applicatie starten. De tekstmodus wordt ook wel <<console, console>>modus genoemd. In deze modus toont het scherm alleen de commando's en hun uitvoer als tekst op een (meestal zwarte) achtergrond.
* In grafische modus worden grafische elementen zoals vensters, panelen of pictogrammen op het scherm weergegeven, meestal geassocieerd met toepassingen of hulpprogramma's. De interactie met de gebruiker en het systeem gebeurt met behulp van een muis en/of een toetsenbord.

Opdrachten kunnen in grafische modus ook worden getypt in een venster dat is gekoppeld aan een <<terminal, terminal>> waarin een shell wordt uitgevoerd.

=== Beschikbare hulpprogramma's

Behalve de hulpprogramma's die in de meeste Linux distributies aanwezig zijn heeft Slint ook zijn eigen tools die die zijn afgeleid van die in Slackware of geleend van Salix.

Dit zijn de hulpprogramma's die je kunt gebruiken om je Slint-installatie na installatie te (her)configureren. Gebruik van de eenvoudigere programma's is recht toe recht aan en de meeste hebben een --help optie. Andere worden in detail behandeld in het hoofdstuk <<Manage_your_system,Je systeem beheren>>.

Tenzij anders aangegeven moeten deze tools als 'root' worden uitgevoerd. Om 'root' te worden d.w.z. de 'admin' status en machtigingen te krijgen, typ je "su -" en dan het wachtwoord van 'root'. Om naar de standaard gebruikersstatus terug te keren typ je Ctrl+d of exit.

Een alternatieve manier om commando's die root-privileges nodig hebben uit te voeren is het typen van "sudo <command>"

De meeste tools zijn er in een terminal- en een grafische versie. De terminal-versie wordt hieronder als eerste weergegeven.

*Algemene instellingen*

* Voor gebruikersbeheer: usersetup of gtkusersetup
* De taal en regio wijzigen: localesetup of gtklocalesetup
* Om de toetsenbordindeling en de invoermethode te wijzigen: keyboardsetup of gtkkeyboardsetup
* Om de datum, de tijd of de tijdzone te configureren: clocksetup en gtkclocksetup.
* Om te kiezen welke services bij het opstarten moeten starten: servicesetup en gtkservicesetup.
* Om het netwerk te (her)configureren: netsetup.
* Om te kiezen of je wilt starten in de tekst- of grafische modus en in het laatste geval de grafische login manager: login-chooser
* Om de desktop-omgeving FVVM, LXQt, MATE of Windowmaker te kiezen type je (als gewone gebruiker): session-chooser
* Om één van deze desktop-omgevingen of aparte window-managers te kiezen type je (als gewone gebruiker): xwmconfig
* Om de programma's die specifiek zijn voor een bepaalde desktop weer te geven typ je (als gewone gebruiker): show-desktop of hide-desktop
* Om spraak in grafische modus in of uit te schakelen: orca-on of orca-off (als gewone gebruiker)
* Om een console schermlezer te kiezen en in te schakelen of alle uit te schakelen: speak-with
* Om opstart-opties specifiek voor MATE en/of LXQt in andere desktop-omgevingen al dan niet weer te geven: display-desktop of hide-desktop (als gewone gebruiker)
* Om emacspeak of speechd-el in of uit te schakelen: switch-on of switch-off (als gewone gebruiker)
* Om de indeling van het GRUB opstartmenu te zien zoals het zal worden weergegeven tijdens de volgende keer opnieuw opstarten: list_boot_entries
* Om een rescue USB opstartstick te maken voor als normaal opstarten niet meer mogelijk is: rescuebootstick
* Om de speakup instellingen op te slaan of te herladen: speakup-save of speakup-restore
* Om de stemmen voor espeak-ng weer te geven, inclusief de mbrola's: list-espeak-ng-voices (als gewone gebruiker)
* Om de geluidskaarten weer te geven: list-cards (als gewone gebruiker)
* Om spraaksynthesizers en bijbehorende talen te tonen die beschikbaar zijn via speech-dispatcher: spd-list (als gewone gebruiker)
 
=== Hoe Slint opstart

Tijdens de installatie werd de software die meekwam in het installatie ISO-beeldbestand of van de externe repositories geïnstalleerd op een <<drive, schijf>>.

Wanneer je Slint opstart controleert de <<firmware, firmware>> eerst de hardware en vervolgens zoekt het naar een programma dat een OS-loader heet (meestal een boot loader genoemd) en voert dit uit.

Er kunnen meerdere OS-loaders op de machine aanwezig zijn. In dit geval toont de firmware de gebruiker een menu om te kiezen welke OS-loader het moet starten.

In Slint is GRUB de software die een OS-loader maakt en installeert. Feitelijk is de OS-loader gemaakt door GRUB ook een boot manager, omdat het je laat kiezen welk OS je wilt starten als er meerdere zijn geïnstalleerd.

De GRUB OS-loader kan worden geïnstalleerd in een boot sector (in geval van Legacy booten) of in een EFI System Partition of ESP (bij EFI booten).

Het doel van de Slint-loader is het starten van het Slint-systeem. Hiervoor laadt het allereerst de <<kernel, kernel>> in het RAM en daarna de <<initrd, initrd>> die op zijn beurt het Slint-systeem initialiseert.

In de laatste stap van deze initialisatie wordt de gebruiker gevraagd zich aan te melden bij het systeem. Hiertoe typt deze eerst de gebruikersnaam (of inlognaam) en vervolgens het wachtwoord waarvan de geldigheid wordt gecontroleerd. Slint, dat evenals andere Linux distributies multi-user is, geeft deze gebruiker toegang tot zijn eigen bestanden maar niet tot die van andere gebruikers.

Tijdens de installatie heb je gekozen om Slint in tekst- of grafische modus te starten.

* Als je na initialisatie van het systeem c voor <<console, console>> hebt gekozen, typ je je gebruikersnaam (of loginnaam) en je wachtwoord dat je bevestigd door op de Enter toets te drukken. Daarna kun je opdrachten typen.
* Als je g (grafisch) gekozen hebt, typ je dezelfde informatie in een <<display_manager, displaymanager>> of login manager, die op zijn beurt de <<graphical_environment, grafische omgeving>> opstart.

Na installatie kun je als 'root' de login-modus wijzigen door de opdracht `login-chooser` te typen in zowel consolemodus als in een <<terminal, terminal>> in grafische modus. Dit commando stelt je in staat om `tekst` te kiezen (synoniem van consolemodus), of voor grafische modus, tussen verschillende display managers. Je keuze zal bij volgende keer opstarten van de computer worden doorgevoerd.

We zullen nu de grafische omgevingen beschrijven en daarna het gebruik van de shell.

=== De grafische omgevingen

<<the_windows, De Vensters>> +
<<the_work_spaces,De Werkruimten>> +
<<the_desktop,Het Bureaublad>> +
<<the_top_panel,Het Bovenpaneel>> +
<<the_bottom_panel, Het Onderpaneel>> +
<<the_slint_control_center,Het Slint Controlecentrum>> +
<<graphical_terminals,Grafische terminals>> +
<<key_bindings,Sneltoetsen>>

Een volledige grafische omgeving bestaat uit verschillende componenten waaronder een window manager die vensters, geassocieerd met toepassingen, op het scherm tekent en deze kan verplaatsen, aanpassen en sluiten.

Slint beschikt over diverse grafische omgevingen: BlackBox, Fluxbox, FVVM, LXQt, MATE, ratpoison, TWM en WindowMaker. Het is maar net wat je voorkeur heeft welke je kiest.

LXQt en MATE zijn volledige desktops, FVWM en WindowMaker bieden unieke functies en kunnen ook worden gekozen met de grafische lightdm login maar ook gestart door het in een console typen van "startx". De andere zijn voornamelijk vensterbeheerders die alleen vanaf een console kunnen worden gestart. Ze geven je allemaal toegang tot je documenten en toepassingen die meestal in een venster worden geopend.

Je kunt kiezen uit FVWM, LXQt, MATE en WindowMaker door als normale gebruiker 'session-chooser' te typen. In grafische modus kun je een omgeving kiezen tijdens het inloggen.

Om één van de andere grafische omgevingen (BlackBox, FluxBox, ratpoison of TWM) te kiezen moet je het commando "xwmconfig" gebruiken.

We zullen nu kort de onderdelen van de standaard en best met spraak en braille toegankelijke MATE Desktop bespreken.

Met behulp van de muis kun je van elk component de functies ontdekken door rechts, midden of links te klikken of dit te simuleren. Het verplaatsen of verwijderen van de meeste componenten of ze veranderen en nieuwe toevoegen gaat op dezelfde manier.

Deze componenten zijn toegankelijk met muisbewegingen en via sneltoeten. We geven hieronder tussen haakjes de sneltoetsen waarmee je de focus op een bepaald element kunt leggen. We geven ook een samenvatting van de <<key_bindings, sneltoetsen>> voor Mate Desktop (met de standaard Marco windows manager) en voor de Compiz windows manager.

[TIP]
====
Je kunt de functies van toepassingen en andere onderdelen van Slint ontdekken door er met de rechter-, midden- of linkermuisknop op te klikken. Bijvoorbeeld door te klikken op de titelbalk, de linker- of rechter vensterknoppen, een icoon in het paneel of op een lege ruimte van het scherm.
====
[[the_windows]]
==== De vensters

Een venster is een rechthoekig gebied dat met een applicatie is geassocieerd. Vensters kunnen worden verplaatst, herschikt, gemaximaliseerd, hersteld en gesloten (beëindigt ook het programma dat er in wordt uitgevoerd) met de muis of sneltoetsen.

[[the_work_spaces]]
==== De werkbladen

Om een groot aantal open vensters op een ordelijke manier te kunnen beheren biedt de grafische omgeving meerdere werkbladen waar je tussen kunt wisselen. Elk werkblad geeft hetzelfde bureaublad en dezelfde werkbalken weer maar vensters kunnen worden geplaatst op één specifiek werkblad of op alle werkbladen. Deze instelling is te wijzigen door met de rechtermuisknop op de bovenrand van het venster te klikken. Je kunt overschakelen naar een ander werkblad door te klikken op de werkblad-switcher of pager in de onderste werkbalk zoals hieronder aangegeven.

[[the_desktop]]
==== Het bureaublad

Het bureaublad omvat het hele scherm waarop andere componenten kunnen worden geplaatst. In het geval van de met Slint meegeleverde Mate Desktop zijn dat de werkbalken boven- en onderaan het scherm en vier pictogrammen die van boven naar beneden de volgende vensters openen:

* Computer, de hoofdmap in de bestandsbeheerder
* Je Persoonlijke map in de bestandsbeheerder
* Dashboard Slint
* de Prullenbak waar bestanden in terecht komen die je van plan bent te verwijderen maar wat je nog niet daadwerkelijk hebt gedaan.

Vensters van gestarte toepassingen worden ook op het bureaublad weergegeven.

Mate heeft twee panelen die worden weergegeven als slanke rechthoekige horizontale zones, één bovenaan en één onderaan het scherm.

Met het indrukken van Ctrl+Alt+Tab wissel je tussen het bureaublad en de bovenste en onderste werkbalk

Het indrukken van Alt+Tab maakt het mogelijk om te wisselen tussen de vensters op het bureaublad.

[[the_top_panel]]
==== De bovenste werkbalk

Deze bestaat van links naar rechts uit:

* Drie menu's:
** Een Toepassingen menu dat geopend kan worden met Alt-F1. Vanaf hier kun je andere menu's openen met pijltje naar rechts. Met de pijltjes op en neer kun je in elk menu navigeren.
** Het Locaties menu.
** Een systeemmenu dat toegang geeft tot het Voorkeuren submenu, het Mate Control Center en knoppen voor hulp, schermvergrendeling en het afsluiten de sessie of de computer.
* Programmastarters voor de webbrowser Firefox, de e-mailclient Thunderbird, de bestandsmanager Caja en de teksteditor Pluma.
* Een gebied waar meldingen en applets zoals de Bluetooth-manager, de geluidsmixer, de netwerkbeheerder en een melding dat er updates beschikbaar zijn als dat het geval is.
* Een klok en agenda.
* De schermvergrendeling.
* Een dialoogvenster voor het afsluiten van de sessie.
* Een dialoogvenster voor het afsluiten van de computer.

[TIP]
====
* Je kunt de werkbalk naar eigen inzicht aanpassen door met de rechtermuisknop op een lege ruimte op de werkbalk te klikken.
* Als je een item op een werkbalk wilt verplaatsen klik je met de middelste muisknop op het element en sleep je het naar waar je de knop weer loslaat.
* Voor contextuele hulp druk je op F1
====

[[the_bottom_panel]]
==== De onderste werkbalk

Deze bestaat van links naar rechts uit:

* Een vensterlijst die kan worden ingesteld door met de rechtermuisknop op de drie verticaal boven elkaar geplaatste punten te klikken en Voorkeuren te kiezen. Dit maakt het ook mogelijk de systeemmonitor in een venster te starten.
* Een *Bureaublad* knop. Linksklikken hierop minimaliseert of verbergt alle vensters, door opnieuw te klikken worden de vensters in hun vorige status hersteld.
* Een werkbladen-switcher of pager. Hiermee schakel je tussen werkbladen of verplaats je vensters van het ene werkblad naar het andere door ze te verslepen.

[[the_slint_control_center]]
==== Het Slint Control Center

We besluiten deze inleiding met het Slint Control Center of Dashboard Slint. Je kunt het bereiken via het Systeem menu in de bovenste werkbalk of door op het Dashboard Slint pictogram op het bureaublad te klikken of qcontrolcenter te typen in het dialoogvenster "Uitvoeren..." dat je oproept met Alt+F2

Het doel van het Controle Center is het op een consistente manier bijeenbrengen van hulpprogramma's voor systeembeheer, documentatie en instellingen in alle window managers. Door op een categorie in het linkermenu te klikken worden bijbehorende toepassingen in het rechterpaneel weergegeven. Ze worden in de tabel hieronder beschreven. Deze toont tevens de beschrijving van de beheer-tools met een grafische gebruikersinterface.

De meeste beheer-tools moeten worden uitgevoerd met root gebruikersrechten. Om een tool te kunnen starten zal daarom naar het root wachtwoord worden gevraagd.

[options="autowidth"]
|====
<|**Categorie** <|**Hulpprogramma** <|**Doel en commentaar**
<|Toepassingen <|Dotnew <|Dit hulpprogramma helpt je bij het beheer van nieuwe (genaamd __iets.new__ vandaar de naam) versus oude configuratiebestanden na het upgraden van sommige pakketten. Het is een goede gewoonte dit programma na iedere upgrade uit te voeren. Het vertelt je of er iets gedaan moet worden en toont je een lijst met mogelijke uit te voeren acties.
<|Toepassingen <|Gslapt Pakketbeheer <|Gslapt is een grafische front-end voor slapt-get. Het is een handig hulpprogramma voor het uitvoeren van <<software_management,software management in Slint>>. Je kunt er pakketten mee zoeken, installeren, verwijderen, upgraden en configureren.
<|Toepassingen <|Sourcery SlackBuild Manager <|Sourcery is een grafische front-end voor slapt-src. Je kunt er SlackBuild scripts mee zoeken waarmee de compilatie en de installatie van softwarepakketten geautomatiseerd worden. Het kan deze pakketten ook weer verwijderen of opnieuw installeren.
<|Toepassingen <|Toepassingenzoeker <|Vindt en start op je systeem aanwezige toepassingen. Het zoekveld werkt meestal sneller dan het handmatig doorzoeken van het applicatiemenu.
<|Informatie <|SlackDocs Website <|De documenten in deze wiki zijn in principe bedoeld voor Slackware gebruikers, maar veel ervan zijn ook bruikbaar door Slint gebruikers. **Waarschuwing:** Sommige van de vermeldde hulpprogramma's zoals slackpkg kunnen **NIET** in Slint worden gebruikt.
<|Informatie <|Slackware Documentatie <|Deze documentatie kan ook bruikbaar zijn voor Slint gebruikers. Slint is gebaseerd op Slackware.
<|Informatie <|MATE systeembewaker <|Dit hulpprogramma toont informatie over het systeem, zoals processen, gebruik van bronnen (RAM, CPU, netwerkverkeer) en het gebruik van het bestandssysteem.
<|Informatie <|Slint Documentatie <|Dit geeft lokaal toegang tot documenten die ook beschikbaar zijn op de Slint website.
<|Informatie <|Slint Forum <|Mensen met een niet Engelse moedertaal kunnen ook posten in de gelokaliseerde Salix forums.
<|Informatie <|Slint Website <|De Slint website bevat documentatie en links naar de ISO's en pakketten.
<|Informatie <|Systeeminformatie <|Dit hulpprogramma verzamelt informatie over je computer, zoals verbonden apparaten (intern en extern) en toont die op een plek. Je kunt er ook de systeemprestaties meten.
<|Systeem <|Display boot menu <|Toont de indeling van het opstartmenu zoals het er bij de volgende keer opstarten zal uitzien 
<|Systeem <|System clock <|Hiermee stel je de systeemklok in.
<|System <|Keyboard <|Met dit hulpprogramma stel je de toetsenbordindeling in.
<|System <|System Language <|Hier stel je de regionale instellingen in zoals de taal en regionale eigenaardigheden), zodat de gebruikte toepassingen (indien beschikbaar) in de ingestelde taal zullen worden weergegeven.
<|System <|Systeem klok <|Hier stel je de tijdzone in en of je de klok wilt synchroniseren met tijdservers op het internet (dit wordt aanbevolen maar vereist natuurlijk wel een internetverbinding) of stel je handmatig datum en tijd in.
<|Systeem <|Systeemservices <|Met dit hulpprogramma stel je in welke services worden geactiveerd tijdens het opstarten. Zoals bijvoorbeeld Bluetooth, de CUPS print server, of een webserver. Gebruik het alleen om de standaard instellingen te wijzigen als je weet wat je doet.
<|Systeem <|Gebruikers en groepen <|Hier kun je gebruikers en/of groepen toevoegen of verwijderen en gebruikersaccounts of groepen instellen. Met name te gebruiken op multi-user systemen.
<|Systeem <|GUEFI Boot Manager <|Dit is een grafische front-end voor het efibootmanager commando. Het helpt je het EFI firmware's boot menu te wijzigen door het toevoegen of verwijderen van menu items of het wijzigen van de volgorde hiervan.
<System <|Rescue boot stick <|Met dit hulpprogramma maak je een USB stick met alles wat nodig is om Slint op te starten mocht dat om welke reden dan ook op de normale manier niet meer mogelijk zijn

|====

[[graphical_terminals]]
==== Terminals

Je kunt in grafische modus evenals in console modus commando's typen als je een terminalvenster opent. Druk in Mate op Ctrl+Alt+t of klik op het mate-terminal pictogram in de bovenste werkbalk of open een "Run... " dialoog met Alt+F2 en typ `mate-terminal` in het venster dat wordt geopend.

De meeste van de onderstaande informatie over de opdrachtregel en de shell in de Console modus is ook van toepassing op commando's in een terminal. Je kunt mate-terminal sluiten door zoals bij elk ander venster op Alt+F4 te drukken.

[[key_bindings]]
==== Sneltoetsen

In dit hoofdstuk volgt een beschrijving van de standaard sneltoetsen voor Compiz window-manager en Mate Desktop en hoe deze kunnen worden aangepast.

[NOTE]
====
Wanneer een sneltoets één of meer *+* tekens bevat druk je van links naar rechts de toetsen behalve de laatste en houd ze ingedrukt zoals een `Shift` toets en druk dan op de laatste toets.
====
===== Sneltoetsen voor Mate Desktop

Bij het gebruik van Mate in Slint zijn een aantal sneltoetsen voor de Marco of Compiz window-managers gelijk. Ze staan hieronder weergegeven:
----
Alt+Tab Wissel tussen vensters
Shift+Alt+Tab Wissel achteruit tussen vensters
Control+Alt+Tab Wissel tussen panelen en bureaublad
Shift+Control+Alt+Tab Wissel achteruit tussen panelen en bureaublad
----
Eenmaal in een grafische omgeving kun je overschakelen naar een console en weer terug. Stel je wilt naar tty2 overschakelen (omdat tty1 al in gebruik is): druk dan 'Ctrl+Alt+F2' en log hier in. +
Druk 'Alt+F7' om terug te keren naar de grafische omgeving.

In alle grafische omgevingen worden dezelfde algemene sneltoetsen gebruikt met uitzondering van Mod1 dat over het algemeen de linker Alt-toets is: +
----
Mod1+F1 activeert het Toepassingen menu van de bovenste werkbalk.
Mod1+F2 activeert een 'Uitvoeren...' dialoog maar in Fluxbox een lxterminal.
----
Ook geldt in Fluxbox:
----
Mod1+F3 herstart Fluxbox.
Mod1+F4 sluit het actieve venster.
----

In MATE kunnen gedeeltelijk slechtzienden de Compiz window-manager gebruiken in plaats van de standaard Marco.

Typ als een gewone gebruiker:
----
gsettings set org.mate.session.required-components windowmanager compiz
----
En om weer terug te keren naar Marco:
----
gsettings set org.mate.session.required-components windowmanager marco
----
Deze instelling wordt doorgevoerd bij het starten van een nieuwe MATE sessie.

Of om de window-manager alleen voor de huidige sessie te wijzigen:
----
compiz --replace &
----
en weer terug naar Marco:
----
marco --replace &
----
Deze wijziging is meteen effectief.

Deze instelling is ook te wijzigen vanuit het grafische hulpprogramma mate-tweak in de categorie Vensters.

Voor toegang tot specifieke Compiz-instellingen typ je:
----
ccsm &
----
===== Sneltoetsen voor de Compiz window-manager

In de hieronder aangegeven standaardinstellingen worden de toetsen of muisknoppen als volgt aangeduid:

Super: De Windows-toets op de meeste toetsenborden +
Knop1: Linker muisknop (indien met rechts gebruikt) +
Knop2: Middelste muisknop of klik met scrollwiel +
Knop3: Rechter muisknop (indien met rechts gebruikt) +
Knop4: Scrollwiel omhoog +
Knop6: Scrollwiel omlaag +
Knop6: Geen idee (Ik dacht voor muizen voor gamers)+

De hieronder op categorie weergegeven instellingen kunnen worden gewijzigd in het CCSM. Tussen vierkante haken staat de korte naam van de plugin.

. Categorie Algemeen
+
[core] Algemene opties, tab "sneltoetsen": +
close_window_key = Alt+F4 +
raise_window_button = Control+Knop6 +
lower_window_button = Alt+Knop6 +
minimize_window_key = Alt+F9 +
maximize_window_key = Alt+F10 +
unmaximize_window_key = Alt+F5 +
window_menu_key = Alt+spatiebalk +
window_menu_button = Alt+Knop3 +
show_desktop_key = Control Alt+d +
toggle_window_shaded_key = Control+Alt +s +
+
[matecompat] Mate compatibiliteit +
main_menu_key = Alt + F1 +
run_key = Alt + F2 +

. Categorie Toegankelijkheid
+
[addhelper] Dim inactief (niet actieve vensters donkerder) +
toggle_key = Super+p +
+
[colorfilter] (Kleurenfilter voor toegankelijkheidsdoeleinden) +
toggle_window_key = Super+Alt+f +
toggle_screen_key = Super+Alt+d +
switch_filter_key = Super+Alt+s +
+
[ezoom] Verbeterde Zoom Desktop +
zoom_in_button = Super+Knop4 +
zoom_out_button = Super+Knop5 +
zoom_box_button = Super+Knop2 (uitzoomen naar normaal) +
+
[neg] Negatief (inverse kleuren van het venster of het scherm) +
window_toggle_key = Super+n +
screen_toggle_key = Super+m +
+
[obs] Instellingen voor transparantie, helderheid en verzadiging +
opacity_increase_button = Alt+Knop4 +
opacity_decrease_button = Alt+Knop5 +
+
[showmouse] (Verbeter de zichtbaarheid van de muisaanwijzer) +
initiëren = Super + k +

. Categorie Vensterbeheer
+
[move] Venster verplaatsen +
initiate_button = Alt+Knop1 (houd Knop1 ingedrukt tijdens bewegen van de muis) +
initiate_key = Alt+F7 (Esc om beweging te stoppen) +
+
[resize] Venstergroote wijzigen +
initiate_button = Alt+Knop2 (houd Knop2 ingedrukt tijdens het bewegen van de muis) +
initiate_key = Alt+F8 (Esc om beweging te stoppen) +
+
[switcher] Applicatie switcher (schakelen tussen vensters of panelen en het bureaublad) + next_window_key = Alt+Tab (schakelen tussen vensters) + prev_window_key = Shift+Alt+Tab + next_panel_key = Control+Alt+Tab (schakelen tussen panelen en het bureaublad) + prev_panel_key = Shift+Control+Alt+Tab +

===== Een eigen sneltoets aan MATE toevoegen.

Om bijvoorbeeld Firefox te starten met Alt+F3 typ je in een terminal of in de Uitvoeren dialoog (opgeroepen met Alt+F2):
----
mate-keybinding-properties
----
In het venster dat nu verschijnt kun je in de lijst met bestaande sneltoetsen met de pijltjestoetsen omlaag en omhoog navigeren.

Om een nieuwe sneltoets in te stellen druk je twee keer op Tab om de cursor op Toevoegen te zetten en daarna op Enter. In het kleine dialoogvenster dat verschijnt typ je de naam van de nieuwe sneltoets, bijvoorbeeld firefox, druk op Tab, typ het van toepassing zijnde commando, in dit geval firefox, druk dan twee keer op Tab om de cursor op Toepassen te zetten en druk op Enter.

Om de nieuwe onderaan de lijst toegevoegde sneltoets te activeren selecteer je deze en druk je op Enter.

De volgende keer dat je Alt+F3 drukt zal Firefox starten

=== De shell

NOTE: Dit hoofdstuk is slechts een korte inleiding. Meer diepgaande informatie vind je in het document https://slint.fr/doc/shell_and_bash_scripts.html[Shell en bash scripts] dat grotendeels is geleend van SUSE.

Wanneer de computer in de console modus start wordt nadat je bent ingelogd door het typen van je gebruikersnaam en wachtwoord door de <shell,shell> een "prompt" weergegeven zoals hieronder: +
didier@darkstar:~$ +
In dit voorbeeld:

* is `didier` de gebruikersnaam
* `darkstar` de naam van de machine
* de tilde `~` vertegenwoordigt de home directory van de gebruiker, in dit voorbeeld `/home/didier`
* het dollarteken `$` geeft aan dat de gebruiker een "gewone gebruiker" is en geen "super user" (zie onderaan).

Achter de prompt wordt de cursor weergegeven.

De gebruiker kan nu op deze regel een commando typen (vandaar de naam "command line") en bevestigen als hij op Enter drukt. De shell analyseert dit commando en voert het uit als het geldig is of geeft anders een melding als "commando niet gevonden". Je kunt de opdracht voordat je op Enter drukt bewerken met behulp van de linker- en rechter pijltjestoetsen en Backspace, Home, End en Del.

Tijdens de uitvoering kan een commando uitvoer op het scherm weergeven of niet. In alle gevallen zal na de uitvoering de prompt weer op een nieuwe regel worden weergegeven wat betekent dat de shell wacht op het volgende commando.

Hiervoor moet de gebruiker wel weten welke commando's beschikbaar zijn en hoe ze worden geschreven. Sommige commando's worden uitgevoerd door de shell zelf terwijl andere externe programma's starten. Onderaan staan verschillende voorbeelden van commando's. Meer vind je in https://slint.fr/doc/shell_and_bash_scripts.html[Shell en bash scripts]

Er zijn meerdere shells beschikbaar waaruit Linux kan kiezen; de standaard in Slint gebruikte shell heet *bash*.

Om meerdere programma's op hetzelfde moment uit te kunnen voeren biedt Linux meerdere "virtuele consoles", genummerd vanaf 1, die hetzelfde toetsenbord en beeldscherm delen. Aanvankelijk start het systeem in console (of virtuele terminal) nummer 1 die ook *tty1* wordt genoemd (de naam is een afkorting van "teletype"). Van daar kan de gebruiker overschakelen naar een andere console of tty; om bijvoorbeeld over te schakelen naar tty nummer twee druk je Alt+F2, waar een andere shell opnieuw zal vragen naar je gebruikersnaam en wachtwoord. Om terug te gaan naar tty1, druk je op Alt+F1. Standaard zijn in Slint 6 tty's beschikbaar, maar dit kan worden aangepast in het bestand /etc/inittab.

Wanneer de shell wordt gebruikt in een grafische omgeving (in een grafische terminal), gedraagt deze zich op dezelfde manier, maar de prompt wijkt enigszins af zoals hieronder weergegeven: +
`didier[~]$` +

Je kunt heen en weer schakelen tussen de console en een grafische omgeving:

* Vanuit de grafische omgeving druk je bijvoorbeeld op Ctrl+Alt+F3 om naar tty3 te gaan. De eerste keer dat je naar een tty gaat, moet je je gebruikersnaam en wachtwoord invoeren.
* Vanaf een console of tty schakel je door Alt+F7 te drukken over naar de grafische omgeving mits deze al actief is. Anders typ je `startx` om deze te starten.

==== Commando's als root uitvoeren

*root* is de conventionele naam van de "supergebruiker" die alle rechten heeft om administratieve taken uit te voeren, zelfs als die het systeem zouden kunnen beschadigen of zelfs vernietigen.

Je kunt direct als root inloggen (ook al wordt dat voor beginners niet aanbevolen). Je doet dat door *root* als gebruikersnaam in te typen en vervolgens het root wachtwoord. Om je te informeren (en te waarschuwen voor de bijbehorende risico's en verantwoordelijkheden) ziet de prompt er als volgt uit: +
*root@darkstar:s~#* +
het teken # (hekje of hash) geeft aan dat de commando's zullen worden ingevoerd als root (niet als gewone gebruiker) met alle daarmee samenhangende rechten maar ook risico's en verantwoordelijkheden.

Als je al als gewone gebruiker bent ingelogd wordt je root door het typen van: +
*su -* +
en vervolgens op Enter te drukken. In dit commando is `su` (wat staat voor "Super User") de naam van het commando, en het teken *-* (minteken) vertelt je dat je een "login shell" opent: er wordt eerst gevraagd naar het root wachtwoord en vervolgens word je doorgestuurd naar de home directory /home/root alsof je bent ingelogd als root bij het opstarten. Dit voorkomt dat je per ongeluk bestanden in je home directory schrijft als gewone gebruiker (/home/didier in het voorbeeld) wat later problemen kan veroorzaken.

De reguliere gebruiker die tijdens de installatie is geregistreerd en andere gebruikers die lid zijn van de 'wheel' groep, kunnen ook commando's typen die gereserveerd zijn voor root mits voorafgegaan door 'sudo' zoals dit bijvoorbeeld: +
*sudo update-grub*

=== Blokkeringsproblemen oplossen

Met een "blokkeringsprobleem" bedoelen we een probleem waardoor Slint niet of niet volledig kan worden uitgevoerd zoals:

* Het systeem kan niet opstarten.
* Het systeem start op maar het opstarten wordt onderbroken voordat dit is voltooid. Dit kan bijvoorbeeld gebeuren als de root systeempartitie niet kan worden aangekoppeld vanwege een fout in /etc/fstab, een beschadigd root bestandssysteem of een ontbrekende kernelmodule die nodig is om de root partitie aan te koppelen, of het systeem start wel op, maar je weet het root wachtwoord niet.

Als het systeem helemaal niet opstart, probeer dan de onderstaande oplossingen in aangegeven volgorde totdat er één werkt.

. Als dit gebeurt na een kernel upgrade, probeer dan in plaats van het eerste het tweede opstart-item.
. Probeer op te starten met de 'rescue' USB-stick die je hebt laten maken aan het eind van de installatie.
. Probeer Slint vanuit de Slint omgeving zelf te repareren zoals hieronder uitgelegd.

Vraag hulp door te mailen naar slint@freelists.org en geef zo veel mogelijk relevante informatie die kan helpen bij de oplossing van het probleem. Meld je als je dat nog niet gedaan hebt aan bij de mailinglist door een mail te sturen naar slint-request@freelists.org met in het onderwerp 'subscribe' waarna je antwoord op de e-mail die je ontvangt. Alleen als je niet kunt e-mailen kun je hulp vragen in het IRC-kanaal #slint, server irc.libera.chat en wacht tot er iemand antwoord geeft.

We zullen nu uitleggen hoe we in Slint kunnen komen om het te repareren.

<<Start_the_installer,Start het installatieprogramma en identificeer Slint's root-partitie>> +
<<Issue_the_needed_commands,Geef de benodigde commando's om in Slint te komen>>. +
<<Repair_Slint,Repareer Slint vanuit Slint.>>

[[Start_the_installer]]
==== Start het installatieprogramma en identificeer de Slint root-partitie

Als het opstartproces wordt onderbroken kun je vanuit het installatieprogramma naar de Slint omgeving om te proberen het probleem op te lossen. Plaats het installatiemedium (USB-stick of DVD waarop het ISO-beeldbestand is geschreven) en volg de instructies hieronder.

. Start het installatieprogramma.
. Zodra je bent ingelogd als root typ je het volgende om de schijven en partities weer te geven:
+
----
lsblk -lpo name,size,fstype
----
. Vind in de uitvoer de naam van de Slint root-partitie en controleer de grootte en het type bestandssysteem met het label FSTYPE.
. Deze partitie aankoppelen
+
----
mount /dev/sda3 /mnt
----
+
[NOTE]
====
Als Slint het btrfs bestandssysteem gebruikt (weergegeven door het commando "lsblk") moet je het aankoppelen met gebruik van de opties genoemd in /etc/fstab.

In dit geval moet je dezelfde opties gebruiken als in Slint op btrfs, dus type in plaats daarvan:
----
mount /dev/sda3 /mnt -o subvol=/ @, compress=zstd: 3
----
====
. Controleer of dit de juiste partitie is. Als het bijvoorbeeld /dev/sda3 is, typ je:
+
----
cat /etc/mnt/etc/slint-version
----
+
Ervan uitgaande dat je Slint64-15.0 hebt geïnstalleerd zou het resultaat moeten zijn: *Slint 15.0*
+
Als de uitvoer "bestand niet gevonden" is, is dat niet de partitie die je zocht. Alleen in dit geval typ je:
+
----
umount /mnt
----
+
Keer dan terug naar de lijst van schijven en partities en probeer een andere tot je de goede gevonden hebt.

[[Issue_the_needed_commands]]
==== Geef het volgende commando om de Slint omgeving in te gaan

. koppel de bestandssystemen /proc /sys en /dev aan door te typen:
+
----
mount -B /dev /mnt/dev
mount -B /proc /mnt/proc
mount -B /dev /mnt/sys
----
+
. Geef de volgende commando's om je Slint omgeving in te gaan en koppel alle apparaten aan die vermeld staan in /etc/fstab:
+
----
chroot /mnt
mount -a
----

[[Repair_Slint]]
==== Reparatie van Slint vanuit Slint

Vanuit Slint kun je het systeem wijzigen om het probleem op te lossen. Hier zijn enkele voorbeelden:

* Voer "update-grub" uit. +
* Voer "grub-emu" of "list_boot_entries" uit +
* Installeer GRUB opnieuw met behulp van de opdracht "grub-install drivename", waarbij drivename de schijf is waar GRUB op moet worden geïnstalleerd. +
* Typ "passwd" om het wachtwoord voor root te wijzigen. +
* Verwijder, installeer of upgrade softwarepakketten.

. Wanneer je klaar bent verwijder je het installatiemedium en typ je:
+
----
exit
reboot
----

[[Accessibility]]
== Toegankelijkheid

Als je tijdens de installatie hebt aangegeven dat je spraak wilde blijven gebruiken zal dit bij het opstarten zowel in een console als in grafische omgevingen zijn ingeschakeld.

=== Gebruik van Slint met braille

Slint bevat de brltty software om braille displays aan te sturen.

De tijdens het opstarten op de opdrachtregel opgegeven of later gemaakte instellingen hiervoor worden op het geïnstalleerde systeem opgeslagen in /etc/brltty.conf.

Een uitgebreide handleiding voor brltty is in het Engels, Frans en Portugees in verschillende formaten inclusief platte tekst (txt) op deze URL beschikbaar: https://mielke.cc/brltty/doc/Manual-BRLTTY/

Om braille in te schakelen als het is uitgeschakeld of als het niet werd ingeschakeld tijdens de installatie doe je het volgende:

. Maak /etc/rc.d/rc.brltty uitvoerbaar door als 'root' te typen:
+
----
chmod 755 /etc/rc.d/rc.brltty
----
. Maak jezelf lid van de braille groep en typ weer als 'root':
+
----
usermod -G braille -a gebruikersnaam
----
+
In het bovenstaande commando vervang je gebruikersnaam voor je inlognaam.

Om braille uit te schakelen typ je als root:
----
chmod 644 /etc/rc.d/rc.brltty
----

=== Spraak in grafische omgevingen

De Orca schermlezer wordt in grafische omgevingen ingeschakeld door te typen:
----
orca-on
----

Hoe je Orca moet gebruiken inclusief de specifieke sneltoetsen zie je als je typt:
----
man orca
----

Kortom, in een grafische omgeving:
----
Insert+Space: display the Orca Preferences dialog.
Insert+S: activate or deactivate the vocal synthesis.
Insert+H: activate the learning mode. In this m	ode:
   Press a key to hear its function
   F1: to hear the documentation of the screen reader
   F2: list the keyboard shortcuts for Orca
   F3: list the keyboard for the current application
   Esc: end of the learning mode
----

=== Voices and TTS in Slint.

Following TTS (Text to Speech synthesizers) are shipped in Slint64-15.0.2, each with a set of voices, namely: +
espeak-ng +
flite +
pico +
mbrola +
RHVoice +

Meestal worden deze TTS met de bijbehorende stemmen en talen beheerd door speech-dispatcher via zogenoemde "modules" (elke TTS is gekoppeld aan een module).

Het speciale hulpprogramma spd-list geeft informatie over de beschikbare synthesizers, stemmen en talen. Het typen van spd-list toont het volgende:
----
Dit script toont talen en synthesizers die beschikbaar zijn voor applicaties die gebruik maken van Speech Dispatcher zoals Orca en speech-up. Elk commando hieronder beantwoordt de vraag die er achter staat.
Voer de opdrachten in zonder aanhalingstekens.
"/usr/bin/spd-list" hoe te gebruiken?
"/usr/bin/spd-list -s" welke synthesizers zijn beschikbaar?
"/usr/bin/spd-list -l" welke taalcodes zijn beschikbaar?
"/usr/bin/spd-list -ls <synthesizer>" welke talen zijn beschikbaar voor deze synthesizer?
"/usr/bin/spd-list -sl <language code>" welke synthesizers hebben stemmen in deze taal?
De taalcode heeft meestal twee tekens, zoals 'en' 'nl' of 'fr'
----
Alle weergegeven stemmen zijn beschikbaar in Orca en speech-up, maar ook in fenrir wanneer deze speech-dispatcher gebruikt.

Er zijn extra stemmen voor flite and mbrola met de bijbehorende modules flite-generic en espeak-ng-mbrola-generic.

Als je wilt weten welke modules geïnstalleerd zijn typ je als root één van deze commando's:
----
slapt-get --search mbrola-voice
slap-get --search flite-voice
----
en installeer dan een nog niet geïnstalleerde zoals b.v.
----
slapt-get -i mbrola-voice-it2
----
Naast de gratis (zoals in gratis bier) stemmen die bij Slint worden meegeleverd zijn er stemmen te koop voor: +
voxin, https://oralux.org/voice.php +
voxygen, via een e-mail naar contact@hypra.fr

Als er later meer stemmen en synthesizers beschikbaar komen zal dat worden aangekondigd in de Slint mailing list en in deze http://slackware.uk/slint/x86_64/slint-15.0/ChangeLog.txt[ChangeLog]

Sneltoetsen voor grafische omgevingen worden besproken in <<key_bindings, Sneltoetsen>>.

=== lightdm loginmanager met spraak gebruiken

In lightdm schakel je het geluid met F4 aan of uit. In eerste instantie is het invoerveld voor het wachtwoord actief. Een druk op de Tab toets activeert de "login drukknop" en daarna de lijst van gebruikers of "combo box". Door op de spatiebalk te drukken activeer je de momenteel geselecteerde gebruiker. Gebruik de pijltjestoetsen om een andere te kiezen en typ vervolgens het bijbehorende wachtwoord. "Andere..." voegt een veld toe waar je de inlognaam van een niet in de lijst voorkomende gebruiker kunt typen. In lightdm toont F10 een menu om te herstarten of af te sluiten. Alt+F4 opent direct een dialoogvenster met de afsluit of annuleer knoppen.

=== Een console-schermlezer kiezen

Slint levert deze console-schermlezers mee: +
espeakup +
speechd-up +
fenrir

Daarnaast kunnen met behulp van speakup in console modus meerdere hardware spraaksynthesizers gebruikt worden.

Om een schermlezer te kiezen voer je als root deze opdracht uit:
----
speak-with
----
De uitvoer van dit commando zonder argument is:
----
root[~]# speak-with
Gebruik: /usr/sbin/speak-with <screen reader> of <hard synthesizer> of none
Kies één van de volgende console schermlezers:
  espeakup (Console schermlezer die espeak-ng met speakup verbindt)
  fenrir (Modulaire, flexibele en snelle console schermlezer)
  speechd-up (Console schermlezer die Speech Dispatcher met speakup verbindt)
of gebruik één van de ondersteunde hardware synthesizers:
  acntsa apollo audptr bns dectlk decext ltlk soft spkout txprt
of typ  "/usr/sbin/speak-with none" om alle schermlezers het zwijgen op te leggen.
root[~]#
----
De getoonde hardware spraaksynthesizers zijn reeds beschikbaar in de draaiende kernel of als geïnstalleerde modules.

Voorbeeld van commando's en bijbehorende uitvoer:

----
root[~]# speak-with speechd-up
Starting speechd-up
Should speechd-up be also started at next boot? [Y/n]
OK
root[~]#Done.
----
Zodra je het commando typt, zullen eerder gebruikte schermlezers worden gestopt en zal speechd-up beginnen te spreken.

Als je Y (standaard) antwoordt op de vraag: Should speechd-up also be started at next boot? +
zal speechd-up ook gebruikt blijven worden bij de volgende keer opnieuw opstarten. +
Als je in plaats daarvan N antwoordt zal na het opstarten de vorige actieve schermlezer worden gebruikt.

Andere voorbeelden:

----
root[~]# speak-with apollo
Stopping speechd-up...
Should apollo be also used at next boot? [Y/n]
OK
root[~]#Done.

root[~]# speak-with none
Do you also want a mute console at next boot? [Y/n]
OK
root[~]#
----

=== Configure a console screen reader.

Slint kan hardware spraaksynthesizers aansturen met behulp van speakup en biedt de espeakup en speechd-up schermlezers.

Je kunt je instellingen zoals de spreeksnelheid of het geluidsvolume opslaan. Typ als root: speakup-save. Dit slaat alle huidige instellingen op inclusief de specifieke instellingen van de hardware synthesizer indien van toepassing.

Deze instellingen worden toegepast bij de volgende keer opstarten: vanuit de opstartscripts rc.espeakup en rc.speechd-up wordt namelijk het commando speakup-restore uitgevoerd.

Als je de opgeslagen instellingen niet wilt laden typ je als root: +
chmod -x /usr/sbin/speakup-restore

Als je ze wel weer wilt toepassen typ je als root: +
chmod +x /usr/sbin/speakup-restore

Hier zijn enkele sneltoetsen voor instellingen in speakup en speechd-up:
----
spk_f9   punctuation_level_decrease
spk_f10  punctuation_level_increase
spk_f11  reading_punctuation_decrease
spk_f12  reading_punctuation_increase
spk_1    volume_decrease (werkt niet met speechd-up)
spk_2    volume_increase (werkt niet met speechd-up)
spk_3    pitch_decrease (werkt niet met speechd-up)
spk_4    pitch_increase (werkt niet met speechd-up)
spk_5    rate_decrease
spk_6    rate_increase
----
In de tabel hierboven is de speakup-toets CapsLock of Ins/0 op een numeriek toetsenblok. Als je bijvoorbeeld de snelheid wilt verhogen houd je de CapsLock-toets ingedrukt en druk je vervolgens op de 6 toets.

Voor sommige instellingen die alleen beschikbaar zijn voor specifieke hardware synthesizers zijn er geen sneltoetsen. Deze stel je in door nieuwe waarden met de opdracht echo te schrijven naar /sys/accessibility/speakup/<synth>/<parameter>

Om bijvoorbeeld de stem gebruikt door een apollo 2 te wijzigen typ je: +
echo 2 > /sys/accessibility/speakup/apollo/voice

speakup-save zal ook deze instelling opslaan.

Let wel: Ik heb nooit een hardware spraaksynthesizer gebruikt, dus de uitleg hieronder is slechts een veronderstelling gebaseerd op de handleiding van de speakup_apollo driver die je kunt vinden op: https://archive.org/stream/DolphinApollo2Manual/Dolphin_Apollo_2_Manual_djvu.txt

[[desktop_keys]]
==== Speakup sneltoetsen voor een desktop computer

Bijna alle hieronder vermelde sneltoetsen bevinden zich op het numerieke toetsenblok. De Insert of 0 toets op het toetsenbord werkt als een Shift-toets. Ins 2 bijvoorbeeld betekent "houd de Insert-toets ingedrukt zoals een Shift-toets en druk op 2". Zorg er wel voor dat NumLock is uitgeschakeld als je Speakup wilt gebruiken.

De sneltoetsen kunnen voor hardware synthesizers worden gebruikt met espeakup evenals met speechd-up.

De eerste sneltoetsen om te onthouden:
----
PrintScreen Speakup aan- of uitzetten
Ins F1 Speakup hulp (druk op de spatieblak om deze weer te verlaten)
----

Sneltoetsen gebruikt voor tijdens het lezen:
----
1/2/3 Zeg de vorige/huidige/volgende letter
Shift PageUp Zeg de eerste letter
Shift PageDown Zeg de laatste letter
4/5/6 Zeg het vorig/huidig/volgend woord
Twee maal 5 Spel het huidige woord
Ins 5 Spel het huidige woord fonetisch
7/8/9 Zeg de vorige/huidige/volgende regel
Ins 4 Zeg van regelbegin tot cursor
Ins 6 Zeg van cursor tot regeleinde
Ins 8 Zeg vanaf de bovenkant van het scherm tot de cursor.
Ins plus Zeg vanaf de cursor tot het eind van het scherm.
plus Zeg het hele scherm.
Ins r Zeg het hele document
punt Zeg positie
Ins punt Zeg kenmerken
Ins min Zeg hex en decimale waarde van karakter.
Minus Parkeer de cursor (schakelt aan of uit)
Ins 9 Verplaats cursor naar bovenkant scherm (Ins PgUp)
Ins 3 Verplaats cursor naar onderkant scherm (Ins PgDn)
Ins 7 Verplaats cursor naar linker schermrand (Ins Home)
Ins 1 Verplaats cursor naar rechter schermrand (Ins End)
Ctrl 1 Verplaats cursor naar het laatste teken op de huidige regel
asterisk schakelt cursor aan of uit
Ins asterisk n<x|y&lt ga naar regel (y) of kolom (x) waar 'n'
              een toegestane waarde is voor een rij of een kolom op het huidige scherm.
Ins f2 Set venster
Ins f3 Wis venster
Ins f4 Venster activeren
----

Andere sneltoetsen:
----
Ins f5 Bewerk iets
Ins f6 Bewerk het meeste
Ins f7 Bewerk scheidingsteken
Ins f8 Bewerken herhalen
Ins f9 Edit exnum

Enter Zeg niets meer (tot een andere toets wordt gedrukt) en zet cursor op de juiste plaats.
Ins Enter Zeg niets meer (tot weer ingeschakeld)

slash Markeer en knip schermgebied.
Ins slash Plak schermgebied in elke console.
----
==== Speakup sneltoetsen voor laptops

Deze sneltoetsen (voor VS-toetsenbordindeling) hebben geen numeriek toetsenblok nodig. Als je er wel één hebt, gebruik dan de <<desktop_keys, speakup desktop sneltoetsen>> omdat die makkelijker in gebruik zijn, vooral als je een andere dan de VS-toetsenbordindeling gebruikt.

De CapsLock-toets gedraagt zich als een Shift-toets. +
CapsLock 2 bijvoorbeeld betekent "Houd de CapsLock-toets ingedrukt zoals een Shift-toets en druk op 2". +
Zorg ervoor dat Numlock is uitgeschakeld als je Speakup gebruikt.

De sneltoetsen kunnen voor hardware synthesizers worden gebruikt met espeakup evenals met speechd-up.

De eerste sneltoetsen om te onthouden:
----
PrintScreen Speakup aan- of uitzetten
Ins F1 Speakup Hulp (druk op de spatieblak om de hulp te verlaten)
----

Sneltoetsen voor tijdens het lezen:
----
CapsLock m/komma/punt Zeg de vorige/huidige/volgende letter
CapsLock PageUp Zeg de eerste letter
CpasLock PageDown Zeg de laatste letter
CapsLock j/k/l Zeg vorig/huidig/volgend woord
CpasLock 2x Zeg het huidige woord
CapsLock u/i/i/o Zeg de vorige/volgende regel
CapsLock h Zeg vanaf regelbegin tot de cursor.
CapsLock puntkomma Zeg vanaf de cursor tot regeleinde
CapsLock y Zeg vanaf de bovenkant van het scherm tot de cursor
CapsLock p Zeg vanaf de cursor tot de onderkant van het scherm.
CapsLock apostrof Zeg het hele scherm
Capslock r Zeg het hele document.
CapsLock n Zeg positie
CapsLock slash Zeg de kenmerken
CapsLock minus Parkeer de cursor (schakel aan of uit)
CapsLock f2 Set Venster
CapsLock f3 Venster wissen
CapsLock f4 Venster activeren
----
Andere sneltoetsen:
----
CapsLock f5 Bewerk iets
CapsLock f6 Bewerk het meeste
CapsLock f7 Bewerk scheidingsteken
CapsLock f8 Herhaal bewerken
shift CapsLock f9 Bewerk exnum
----

=== Emacs laten spreken

Je kunt emacspeak of speechd-el gebruiken. Om ze in of uit te schakelen type je als normale gebruiker één van deze commando's:

switch-on emacspeak +
switch-on speechd-el +
switch-off emacspeak +
switch-off speechd-el +

Typ daarna gewoon: +
emacs

Het inschakelen van het ene programma schakelt het andere uit.

[[Manage_your_system]]
== Je systeem beheren

[[software_management]]
=== Software management in Slint.

<<The_basics, De basis>> +
<<Keep_your_system_up_to_date, Hou je systeem up to date>> +
<<Kernel_upgrades, Kernel upgrades>> +
<<Get_additional_applications, Extra toepassingen>> +
<<slapt_src, Gebruik van slapt-src>>

[[The_basics]]
==== De basis

In Slint wordt software aangeboden in de vorm van pakketten. Een pakket is een bundel van bestanden die worden geleverd als een gecomprimeerd archiefbestand dat alles bevat wat nodig is om het programma uit te voeren. Pakketten staan op de installatie ISO en zijn beschikbaar op externe servers waarvan ze kunnen worden gedownload en geïnstalleerd. Installeren van een pakket betekent dat de bestanden in het archiefbestand worden uitgepakt en naar een map in het systeem worden gekopieerd.

Installatie en verwijdering van software wordt opgeslagen in een database bestaande uit tekstbestanden in de mappen:
----
/var/lib/pkgtools/packages
/var/log/removed_packages
/var/lib/pkgtools/scripts
/var/log/removed_scripts
----
De bestanden in /var/lib/pkgtools/packages bevatten informatie over de pakketten, de lijst met bestanden van de software en waar ze zijn geïnstalleerd.

De belangrijkste commando's om pakketten te beheren worden hieronder weergegeven. Ze hebben allemaal man-pages.

Deze opdrachten vereisen administratieve rechten, gekoppeld aan een specifieke account genaamd 'root', waarvoor je een wachtwoord hebt opgegeven tijdens de installatie van Slint.

Om een opdracht als 'root' te geven, typ je eerst su - waarna je het wachtwoord voor root invoert en vervolgens de opdracht typt.+of gebruik sudo.

Onderstaande commando's kunnen worden uitgevoerd in een grafische terminal of in een console, uitgezonderd gslapt dat alleen in een grafische omgeving werkt.
----
installpkg # om een lokaal opgeslagen pakket te installeren.
removepkg # om een geïnstalleerd pakket te verwijderen.
upgradepkg # om een geïnstalleerd pakket te vervangen door een ander pakket (meestal met dezelfde naam maar met een andere versie).
slapt-get # voor het installeren, verwijderen en upgraden van pakketten opgeslagen in repositories vermeld in /etc/slapt-get/slap-getrc
----
De pakketten in het installatie ISO-beeldbestand zijn afkomstig van de repositories vermeld in /etc/slapt-get/slapt-getrc

Doe jezelf een plezier en lees de commentaren in /etc/slapt-get/slapt-getrc en /usr/doc/slapt-get-0.10.2t/README.slapgetrc.Slint in het geïnstalleerde systeem.

Na installatie van Slint zul je op de hoogte worden gebracht van updates van geïnstalleerde pakketten uit de repositories die zijn vermeld in /etc/slapt-get/slapt-getrc

Je kunt extra pakketten installeren met behulp van de opdracht slapt-get of de grafische applicatie gslapt indien deze aanwezig zijn in een repository vermeld in /etc/slapt-get/slapt-getrc

slapt-get en gslapt hebben een zoekfunctie die je helpt bij het zoeken naar pakketten.

WARNING: je kunt slap-get, gslapt en removepkg gebruiken om zelf geïnstalleerde pakketten te verwijderen, maar niet die zijn meegekomen in het Slint ISO-beeldbestand. Zelfs als je ze nooit gebruikt. Het verwijderen van zo'n pakket zal de prestaties niet verbeteren en kan andere toepassingen onmogelijk maken. Als je een pakket hebt toegevoegd dat niet in Slint is opgenomen, kun je het verwijderen maar let er wel op dat het verwijderde pakket geen afhankelijkheid is van andere pakketten die je ook hebt geïnstalleerd en van plan bent om te blijven gebruiken.

[[Keep_your_system_up_to_date]]
==== Je systeem up-to-date houden

Hou je systeem veilig door de software-updates van Slint te installeren zodra ze beschikbaar zijn.

Alle updates staan in de ChangeLog: http://slackware.uk/slint/x86_64/slint-15.0/ChangeLog.txt

Na de installatie van Slint of na iedere wijziging in het bestand/etc/slapt-get/slapt-getr voer je eenmalig het volgende commando uit:
----
slapt-get --add-keys
----

Om de lokale lijst van beschikbare pakketten te synchroniseren met die van de repository wordt het volgende commando automatisch iedere twee uur uitgevoerd:
----
slapt-get -u
----
Je kunt dit ook handmatig uitvoeren.

Dit vereist natuurlijk wel dat de machine met het internet verbonden is.

Om de bijgewerkte of opnieuw gecompileerde pakketten te downloaden en te installeren voer je als root het volgende commando uit:
----
slapt-get --upgrade
----
Alternatief kun je ook gslapt, een grafische front-end voor slapt-get gebruiken.

Om nieuwe pakketten te downloaden die in de ChangeLog zijn vermeld als "Added" typ je:
----
slapt-get -i <pakketnaam>
----
of om ervoor te zorgen dat je alle pakketten hebt geïnstalleerd die zijn meegekomen met Slint inclusief de pakketten die aan de repository zijn toegevoegd na de installatie van Slint:
----
slapt-get --install-set slint
----

Op de bureaubladen wordt in het notificatiegebied van een werkbalk (de bovenste werkbalk in MATE) een klein pictogram weergegeven dat aangeeft of er software-updates beschikbaar zijn. Klik er met de linkermuisknop op en volg de instructies.

Wees je ervan bewust dat sommige pakketten op de blacklist staan in /etc/slapt-get/slapt-getrc, d.w.z. dat ze niet automatisch kunnen worden geüpgraded of geïnstalleerd.

[[Kernel_upgrades]]
==== Kernel-upgrades

Er komen steeds nieuwe kernels beschikbaar met veiligheids-updates of verbeterde functionaliteit.

Meestal is er geen handmatige interventie van de gebruiker nodig wanneer dit gebeurt maar het kan nuttig zijn om te weten hoe een kernel-upgrade werkt en wat te doen als er iets onverwachts gebeurt.

Er zijn een aantal pakketten met bestanden die op iedere kernel betrekking hebben, namelijk: kernel-generic, kernel-modules, kernel-source en kernel-headers. kernel-source en kernel-headers bevatten bestanden die gebruikt worden om software te kunnen compileren, alleen kernel-generic en kernel-modules zijn nodig om een Slint-systeem te kunnen gebruiken.

Het pakket kernel-modules bevat bestanden genaamd modules. Dat zijn stukjes code die in de kernel kunnen worden "ingeplugd" om een specifieke functie toe te voegen of specifieke hardware te ondersteunen.

Als zowel een kernel-pakket als het bijbehorende kernel-modules pakket zijn geïnstalleerd maakt het script /sbin/wrapupgradepkg een met deze kernel geassocieerde <<initrd, initrd>> (met modules afkomstig uit het pakket kernel-modules) en installeert die naast de kernel in de /boot map.

Vervolgens worden vorige kernels (die niet in gebruik zijn op het moment van de upgrade) verwijderd.

Vervolgens werkt het script het GRUB configuratiebestand /boot/grub/grub.cfg dat door de OS-loader wordt gelezen bij om het opstartmenu-item te maken.

Dit opstartmenu bevat dan ten minste twee boot-items voor een kernel en de bijbehorende initrd. Van bovenaf:

* Een boot-item om Slint te starten met de zojuist geïnstalleerde nieuwe kernel.
* Een boot-item om Slint te starten met behulp van de kernel die in gebruik was op het moment van de kernel-upgrade.

Dit zorgt voor een soort "vangnet" in het geval Slint niet met de nieuwe kernel zou kunnen opstarten: druk in dit geval wanneer het boot-menu wordt weergegeven pijl omlaag om Slint met de vorige kernel op te starten

Voordat je opnieuw opstart kun je een voorbeeld van het nieuwe opstartmenu bekijken door als root te typen:
----
grub-emu
----
Er wordt nu een geemuleerd of "fake" opstartmenu weergegeven met dezelfde lay-out als bij het opstarten daadwerkelijk zal worden weergegeven.

Je kunt er met de pijltjestoetsen omlaag en omhoog in navigeren om een opstart-item te markeren waarvan je de details kunt weergeven door op 'e' te drukken. Je gaat terug naar het menu door op Esc te drukken.

Om grub-emu af te sluiten druk je op c en typ je *exit* en tot slot op Enter.

Als alternatief kun je als root typen:
----
list_boot_entries
----

[[Get_additional_applications]]
==== Extra toepassingen

De makkelijkste en aanbevolen manier om extra toepassingen die niet in Slint zijn opgenomen te verkrijgen is slapt-get of de grafische front-end gslapt te gebruiken. Dit geeft u toegang tot alle pakketten in repository's die standaard zijn ingeschakeld in /etc/slapt-get/slapt-getrc, in aanvulling op de Slint-repository: +

* De Slackware-repository met afhankelijkheidsinformatie: SOURCE=https://slackware.uk/salix/x86_64/slackware-15.0/:official
* De Salix extra repository, samengebracht voor de Salix distributie door zijn onderhouder George Vlahavas aka gapan maar tevens bruikbaar in Slint: SOURCE=https://slackware.uk/salix/x86_64/extra-15.0/:OFFICIAL

Als de applicatie die je wilt installeren niet beschikbaar is in een van de repositories die zijn ingesteld in /etc/slapt-get/slapt-getrc, kun je er zelf een pakket voor maken met behulp van het bouwmateriaal dat door vrijwilligers ter beschikking wordt gesteld op @ https://slackbuilds.org. Hoe dat werkt lees je op https://slackbuilds.org/howto/ en https://slackbuilds.org/faq/

De op deze manier gemaakte pakketten zouden compatibel met Slint moeten zijn.

De toepassing * slapt-src * en zijn grafische front-end *sourcery* stelt je in staat om als root of met sudo pakketten te compileren en te installeren met behulp van het materiaal beschikbaar op https://slackbuilds.org.

We zullen slapt-src in meer detail beschrijven.

[NOTE]
====
Voor de meeste toepassingen zijn kant en klare pakketten die met slapt-src of sourcery gecompileerd kunnen worden in de Salix extra repository beschikbaar. Installeer bij voorkeur deze voorgecompileerde pakketten met behulp van slapt-get of gslapt, tenzij je specifieke build-opties of een andere versie nodig hebt dan die beschikbaar is.
====

[[slapt_src]]
===== Gebruik van slapt-src

Het standaard configuratie-script voor slapt-src is /etc/slapt-get/slap-getrc dat er als volgt uit ziet:
----
BUILDDIR=/var/lib/slapt-src
PKGEXT=txz
SOURCE=https://slackbuilds.org/slackbuilds/15.0/
----
Dus:

* Al het uitgangsmateriaal en pakketten gaan in de map /tmp/slapt-src
* De namen van de gebouwde pakketten eindigen op .txz
* Het uitgangsmateriaal wordt gedownload uit de repository https://slackbuilds.org/slackbuilds/15.0/

De uitvoer van de opdracht *slapt-src --help* is:
----
Gebruik: slapt-src [option(s)] [action] [slackbuild(s)]
  -u, --update         update de lokale cache van de remote slackbuilds
  -U, --upgrade-all     upgrade alle geïnstalleerde slackbuilds
  -l, --list           overzicht van beschikbare slackbuilds
  -e, --clean       schoon de compilatie-map op
  -s, --search      zoek beschikbare slackbuilds
  -w, --show       toon de gespecificeerde slackbuilds
  -i, --install        download, compileer en installeer de gespecificeerde slackbuild(s)
  -b, --build         download en compileer de gespecificeerde slackbuild(s)
  -f, --festch        download de gespecificeerde slackbuild(s)
  -v, --version
  -h, --help
 Opties:
  -y, --yes           toon geen prompt
  -t --simulate         toon wat gedaan zal worden
  -c, --config=FILE         gebruik het opgegeven configuratiebestand
  -n, --no-dep             negeer afhankelijkheden
  -p, --postprocess=CMD       voer het gespecificeerde commando uit op het gegenereerde pakket
  -B, --build-only           alleen van toepassing op --upgrade-all
  -F, --fetch-only           alleen van toepassing op --upgrade-all
----

Enige opmerkingen betreffende deze opties:

* Gebruik -u of --update om de lijst van pakketten die gecompileerd en geïnstalleerd kunnen worden bij te werken. Deze commando's overschrijven het bestand /tmp/slapt-src/slackbuilds_data.
* Gebruik -e om schijfruimte te besparen door de meeste bestanden in /usrc/src/slapt-src/ te verwijderen
* gebruik -U *alleen* om een overzicht van mogelijke upgrades of downgrades weer te geven zonder bevestiging: bevestiging zou alle Slint-pakketten door de versie in de externe repository vervangen waardoor mogelijk software die niet compatibel is met deze versie zou kunnen beschadigen.
* -i kan een pakket upgraden dat al is geïnstalleerd vanaf https://slackbuilds.org, als een maintainer van het SlackBuild script het heeft geüpgraded en de variabele VERSION heeft gewijzigd.
* Gebruik -f om alleen de bestanden voor een bepaald softwarepakket van https://slackbuilds.org te downloaden. Dit kan handig zijn als je het bouwmateriaal wilt controleren of het bouwmateriaal wilt aanpassen. Laten we bijvoorbeeld aannemen dat je het bouwmateriaal voor de software *mxml* wilt downloaden. Het onderstaande commando geeft dan informatie over de software en welke bestanden hiervoor beschikbaar zijn op https://slackbuilds.org:
+
----
slapt-src --show mxml
SlackBuild Name: mxml
SlackBuild Version: 3.
SlackBuild Category: libraries/mxml/
SlackBuild description: mxml (Lightweight xml parsing library)
SlackBuild Files:
 README
 mxml.SlackBuild
 mxml.info
 slack-desc
----
+
Je kunt deze bestanden inclusief het bronarchief uit de upstream-repository ophalen met de volgende opdracht:
+
----
slapt-get -f mxml
----
+
Met de kennis van de uitvoer van de vorige opdracht dat de bestanden worden opgeslagen in de subdirectory libraries/mxml, kun je met deze opdracht controleren welke bestanden zijn gedownload:
+
----
ls -1 /var/lib/slapt-src/libraries/mxml
mxml-3.1.tar.gz
mxml.SlackBuild
mxml.info
slack-desc
----
* Gebruik -b als je een pakket wilt maken maar het nog niet wilt installeren. In het bovenstaande voorbeeld zal het worden opgeslagen in /tmp/slapt-src/libraries/mxml, zodat je het later kunt installeren met:
+
----
upgradepkg --install-new /tmp/slapt-src/libraries/mxml/xml*txz
----
+
* Gebruik -c als je een aangepast configuratiebestand wilt gebruiken in plaats van de standaard /etc/slapt-get/slap-getrc

=== Manage users and groups.

Er zijn twee commando's voor het beheren van gebruikers en groepen:

* Het _usersetup_ commando (TUI)
* De _gtkusersetup_ opdracht (GUI), via een pictogram dat in de categorie Systeem in het Slint Control Center aanwezig is

Met deze opdrachten kun je gebruikers en gebruikersgroepen toevoegen of verwijderen en gebruikers aan groepen toevoegen.

Bedenk dat elk gebruikersaccount standaard is gekoppeld aan zijn eigen map in de /home directory. Als je bijvoorbeeld een gebruiker *leonie* toevoegt, zal er een /home/leonie map worden gemaakt, waar alleen leonie (en root) toegang toe heeft.

=== Standaardtaal van het systeem wijzigen

Daarvoor zijn twee commando's voorzien:

* De _localesetup_ commando (TUI).
* De _gtklocalesetup_ commando (GUI), via een pictogram in de categorie Instellingen in het Slint Control Center.

Onthoud dat deze instellingen de taal veranderen die gebruikt wordt door de interfaces van geïnternationaliseerde applicaties, niet de toetsenbordindeling (zie hieronder).

Gelokaliseerde pakketten (indien beschikbaar) die overeenkomen met de tijdens de installatie gekozen taal zijn al geïnstalleerd. Als je de standaardtaal nadien wijzigt, moet je de bijbehorende gelokaliseerde pakketten hier voor installeren.

Gelokaliseerd betekent "verstrekt in een bepaalde locale", de locale is een taal plus bijzondere eigenschappen geassocieerd met een geografisch gebied. In Portugal en Brazilië wordt bijvoorbeeld verschillend Portugees gesproken. In de naam van de gelokaliseerde pakketten is l10n een afkorting van "localization" die staat voor "letter l + 10 andere letters + letter n".

Gelokaliseerde pakketten zijn er al voor veel talen. Ze hebben de naam van het basispakket, een koppelteken, en vervolgens de taalcode. Hieronder worden de basisnamen van de gelokaliseerde pakketten getoond:
[options="autowidth"]
|====
| Base package name | Omschrijving
| aspell | woordenlijst voor spellingscontrole
| libreoffice-l0n | gelokaliseerde LibreOffice office suite
| libreoffice-help | gelokaliseerde hulp voor LibreOffice
|====

Om een gelokaliseerd pakket te vinden, typ je in een terminal als root (bijvoorbeeld voor libreoffice-l10n): +
'spi libreoffice-l10n`

Dit geeft een overzicht van alle gelokaliseerde LibreOffice pakketten. Wanneer je het gewenste hebt gevonden kun je het installeren. Voor Perzisch bijvoorbeeld is de taalcode `fa` (kort voor Farsi), dus om het te installeren typ je: +
`spi -i libreoffice-l0n-fa`

Als je dat wilt kun je hier ook `gslapt` voor gebruiken. Typ de pakketnaam in het zoekveld om alle gelokaliseerde libreoffice pakketten weer te geven.

=== De toetsenbordindeling wijzigen

Je kunt de in grafische modus gebruikte standaard toetsenbordindeling wijzigen met:

* Het _keyboardsetup_ commando (TUI)
* Het _gtkkeyboardsetup_ commando (GUI), via een pictogram in de categorie Hardware in het Slint Control Center.

Met deze commando's kunt je ook kiezen of NumLock of SCIM (invoermethode) moet worden ingeschakeld bij het opstarten van het systeem.

Als je een window manager gebruikt met een paneel, kun je dit ook instellen door te rechtsklikken op de toetsenbord-applet (standaard weergegeven als de twee letters van de taalcode van de huidige toetsenbordindeling).

Op de opdrachtregel - maar nog steeds in grafische modus - gebruik je in plaats daarvan het commando 'setxkbmap`

Om bijvoorbeeld de toetsenbordindeling in grafische modus op Oekraïens in te stellen typ je als gewone gebruiker: +
'setxkbmap -layout ua`

Zie voor meer informatie de man page voor setxkbmap.

=== Een printer installeren

In Slint beheert de CUPS print server printers en afdruktaken. Standaard mogen alleen gebruikers die tot de`sys`(afkorting voor _systeem_) groep behoren - wat is vastgelegd in het bestand /etc/cups/cupsd - administratieve taken uitvoeren zoals het toevoegen of verwijderen van een printer.

Voor een eenvoudige configuratie (een printer gekoppeld aan een desktop pc of laptop en niet gedeeld met andere machines), hoef je slechts één gebruiker (die de printers zal beheren) aan de groep`sys`toe te voegen. Het toevoegen van de gebruiker _didier_ aan de groep`sys`kan op twee manieren:

* In console modus of in een virtuele terminal word je root met `su` en typ je:
+
` gpasswd --add didier sys `
+
* In grafische modus klik je in het Slint Control Center op Gebruikers en Groepen (categorie Systeem), selecteer je de gebruiker en klik je op 'Eigenschappen', vervolgens vink je`sys`aan op de tab Groepen. Of andersom: selecteer de groep en voeg er de gewenste gebruiker aan toe.

Er zijn verschillende manieren om een printer toe te voegen en te configureren (dit moet worden gedaan door een lid van de`sys`groep):

* Vanuit het Slint Control Center klik je in de categorie Hardware op Printer Setup om een GUI weer te geven waarin je een eenvoudige opstelling kunt instellen...
* ... of klik je op Cups Print Control dat de webinterface van de CUPS print server opent. Je kunt de webinterface ook in een webbrowser weergeven door`localhost:631` in de adresbalk te typen.
* Als je een Hewlett Packard printer hebt, klik dan met de rechtermuisknop op het *hp* logo in het notificatiegebied van het paneel.

NOTE: Om afdrukinstellingen te wijzigen moet de CUPS-server worden uitgevoerd. Deze wordt gestart als Slint wordt opgestart als de service`cups`is aangevinkt bij de System Services (wat het standaard is in Slint).

=== Geluid instellen

In Slint sturen applicaties hun geluidsuitvoer naar ALSA of PulseAudio.

In het laatste geval stuurt PulseAudio op zijn beurt de output stream naar een ALSA-mixer die het naar de geluidskaarten leidt.

Als gevolg daarvan kan een instelling zoals het geluidsvolume altijd worden gewijzigd door een ALSA mixer, maar ook door een PulseAudio mixer als de applicatie de geluidsuitvoer naar PulseAudio stuurt.

We bespreken nu de applicaties die kunnen worden gebruikt om de geluidsinstellingen te wijzigen

==== pavucontrol (voor PulseAudio)

`pavucontrol` staat voor PulseAudio Volume Control en is een grafische applicatie. Je kunt het starten vanuit een terminal of het Toepassingen menu, of door in de bovenste werkbalk van MATE met de rechtermuisknop op het pictogram van de geluidsmixer te klikken. Er zijn meer instellingen mogelijk dan alleen de volumeregeling, neem de tijd om alle functies te ontdekken.

Je kunt ook de volume control applet gebruiken in het meldingengebied van het paneel: met de linkermuisknop kunt u het volume aanpassen en de rechtermuisknop geeft toegang tot andere instellingen en geeft de mogelijkheid om de pavucontrol mixer te starten.

[[Sound_on_the_command_line]]

==== alsamixer (voor ALSA)

alsamixer is een ncurse-applicatie met een semi-grafische gebruikersinterface.

Je gebruikt ze door in een console of in een grafische terminal te typen:
----
alsamixer
----
vervolgens:

* Gebruik je de PgUp-toets om het volume met 5% te verhogen
* Gebruik je de PgDn-toets om het volume met 5% te verlagen
* Druk je op Esc om de applicatie te verlaten.

==== amixer (voor ALSA)
Dit commando heeft de volgende schrijfwijze:
----
amixer <arguments>
----
Om bijvoorbeeld het hoofdvolume in te stellen op 70% typ je:
----
amixer set Master 70%
----
Voor meer informatie typ je een van deze commando's:
----
man amixer
amixer -h
----
==== sam (de Speech-Friendly Alsa Mixer)
met sam kun je een geluidskaart selecteren als je er meer dan één in je machine hebt zitten. Als er maar één is, worden direct de verschillende mixers voor configuratie weergegeven.

Alle items of het nu geluidskaarten of mixers zijn of een bepaalde functie of een specifieke mixer is worden geselecteerd door de lijst door te bladeren met de op en neer pijltjestoetsen en Enter te drukken op de gewenste optie: + `q` verlaat de lijst en/of sluit af. + `Shift-q` sluit het programma af. + `F1` toont extra informatie indien beschikbaar.

Als je de naam van de gewenste optie weet, kun je ook op de eerste letter hier van drukken. Deze zgn. Eerste letter navigatie is hoofdlettergevoelig. Het toont je de eerste optie die begint met de ingedrukte letter. Als je nogmaals op dezelfde letter drukt, ga je naar de volgende optie beginnend met die letter als die aanwezig is. Het herhaald indrukken van deze toets laat je wisselen tussen alle opties die beginnen met die letter.

De mogelijke instellingen van een mixer kunnen worden weergegeven door op F1 te drukken. +
Ze worden weergegeven als een keuzelijst, met een verkorte weergave van alle relevante informatie. "Verlaag het volume vanaf 84 procent" bijvoorbeeld, is de optie om het afspeelvolume te verlagen. Zoals je kunt zien wordt ook de huidige instelling getoond.

NOTE: sam werkt niet goed in een grafische terminal. Gebruik het daarom alleen in een console.

==== pamixer en ponymix (voor PulseAudio)
Deze tools lijken op elkaar met commando's met deze schrijfwijze:
----
pamixer <argumenten>
ponymix <argumenten>
----
Typ om bijvoorbeeld het volume op 70% in te stellen voor de standaard sink type één van deze commando's:
----
pamixer --set-volume 7
ponymix set-volume 7O
----
Voor meer informatie typ je:
----
pamixer -h
ponymix --help
----

==== pacmd en pactl (voor PulseAudio)

Deze twee console-toepassingen controleren een draaiende PulseAudio daemon.

WARNING: typ pacmd en er verschijnt een interactieve dialoog. Druk op Ctrl+d om de toepassing te verlaten maar typ geen exit omdat dit PulseAudio in zijn geheel zou afsluiten!

Voor meer informatie typ je:
----
man pactl
man pacmd
pactl --help
pacmd --help
----

==== Het geluidsvolume opslaan en herstellen

Maak het bestand /etc/rc.d/rc.alsa uitvoerbaar. Typ als root:
----
chmod +x /etc/rc.d/rc.alsa
----
Tijdens het opstarten zal dit script eerder opgeslagen geluidsinstellingen herstellen of als die ontbreken standaard volumes instellen en opslaan, zodat ze weer kunnen worden herladen bij de volgende keer opstarten.

Als je niet wilt dat dit script het standaard volume instelt typ je als root:
----
touch /var/lib/alsa/no.asound.state
----

Je kunt de standaard geluidsniveaus nu wijzigen met alsamixer of amixer en ze bewaren door als root te typen:
----
alsactl store
----
Het script zal ze bij de volgende keer opstarten weer op dat ingestelde niveau herstellen.

Voor meer informatie typ je:
----
man alsactl
----

=== Netwerkconfiguratie

Als je het netwerk niet hebt ingesteld tijdens de installatie van Slint wordt je eerst root door het typen van `su-` in een console of een grafische terminal zoals mate-terminal, en het intypen van het root-wachtwoord.

Het netwerk wordt ingesteld met behulp van het `netsetup` script. Typ de opdracht `netsetup` in dezelfde terminal, waar je zojuist root geworden bent. Als eerste wordt je om de hostnaam van je machine gevraagd. Hier kun je iedere naam voor kiezen als het maar één woord is. Dan wordt je gevraagd om de domeinnaam. Als de machine geen server is kun je iedere naam kiezen. Daarna wordt je gevraagd hoe je machine verbinding maakt met het netwerk. Tenzij je een goede reden hebt om dat niet te doen (en je weet wat je doet), gebruik je de standaard `NetworkManager` om het netwerk automatisch te configureren.

Voor bekabelde verbindingen moet dat genoeg zijn om automatisch met het netwerk te worden verbonden bij de volgende keer opstarten.

Om een draadloze verbinding te configureren zijn twee commando's via de opdrachtregel beschikbaar.

Je kunt de commando's weer rechtstreeks in de console typen of in een grafische terminal zoals mate-terminal. Typ ze in dit geval als gewone gebruiker niet als root. Als je deze instructies opvolgde en al root bent typ je `exit` om de normale gebruikersstatus terug te krijgen.

De twee genoemde commando's zijn `nmtui` (via dialoogvenster) of `nmcli` (alleen opdrachtregel).

Als je liever via de opdrachtregel werkt, lees dan eerst de nmcli documentatie. Typ `nmcli --help` of `man nmcli` voor meer gedetailleerde informatie. Hoewel `nmcli` meer mogelijkheden biedt, zal de functionaliteit van `nmtui` in de meeste gevallen voldoende zijn voor het instellen van je draadloze netwerk, dus zullen we dit hier beschrijven:

In `nmtui`kun je navigeren met de Tab en pijltjestoetsen. Er worden je drie opties voorgesteld: +
`Een verbinding wijzigen` +
`Een verbinding activeren` +
`Hostnaam van het systeem instellen` +

Als er nog geen draadloze verbinding is ingesteld kies dan voor `Een verbinding activeren`. Van boven naar beneden worden eerst de bekabelde verbindingen (indien aanwezig) getoond, daarna alle toegankelijke draadloze netwerken. Navigeer met de pijltjestoetsen omhoog en omlaag om het gewenste netwerk te selecteren en typ dan Enter: waarschijnlijk wordt u nu gevraagd naar het wachtwoord of de encryptiesleutel. Voer deze in, bevestig het met de Tab-toets, sluit dan af en je bent klaar.

Alleen in grafische modus kun je in plaats van `nmcli` of `nmtui` de applicatie `nm-connection-editor` gebruiken.

=== Services instellen

Je kunt de standaard instellingen op meerdere manieren wijzigen:

* Voer als root het `servicesetup` commando (TUI) uit
* Alleen in grafische modus met `gtkervicesetup`dat toegankelijk is vanuit het Slint Control Center in categorie Systeem of het typen van Alt+F2 om het dialoogvenster "Uitvoeren..." te openen en vervolgens *gtksetrvicesetup* te typen.
* Door als root het relevante script uitvoerbaar (chmod 755 <path to the script> of niet uitvoerbaar (chmod 644 <path to the script>) te maken. Om bijvoorbeeld rc.fail2ban uitvoerbaar te maken typ je: `chmod 755 /etc/rc.d/rc.fail2ban`

IMPORTANT: Verander alleen de standaardinstellingen als je weet wat je doet.

Services worden beheerd door scripts waarvan de naam begint met `rc.` en die zich in de map /etc/rc.d/ bevinden. De service acpi bijvoorbeeld wordt beheerd door het shell script /etc/rc.d/rc.acpi. De meeste diensten worden bij het opstarten geactiveerd als het bijbehorende script uitvoerbaar is. In onderstaande tabel geven we in kolom A aan of de service bij het opstarten geactiveerd is (`aan`) of niet (`uit`). Als de kolom leeg is, is de activering van de service afhankelijk van een keuze die tijdens de installatie is gemaakt. Een `A` in de kolom geeft aan dat de service is geactiveerd in de automatische installatiemodus of anders als de gebruiker dit zelf heeft gekozen tijdens de installatie. De Pakket kolom geeft bij welk softwarepakket het script hoort

[options="autowidth"]
|====
| *Service* | *A* | *Pakket* | *Doel en commentaar*
| acpi | on | acpid | Advanced Configuration and Power Interface, zorgt onder andere voor energiebeheer of opnieuw opstarten met een druk op een knop
| alsa | on | alsa-utils | Zorgt voor standaard geluidsinstellingen of het laden van eerder opgeslagen instellingen
| alsa-oss | off | alsa-utils | ALSA OSS kernel modules. Meestal niet gebruikt en daarom in Slint standaard niet ingeschakeld.
| atalk | off | netatalk | Om Unix-achtige OS-en te kunnen inzetten als bestands-, print- en tijdservers voor Macintosh computers.
| atd | off | at | at en batch leest shell commando's van de standaard invoer (of een opgegeven bestand) en slaat deze op als een geplande taak om op een later tijdstip uit te voeren
| autofs | off | autofs | AutoFS zorgt voor het automatisch aankoppelen van verwijderbare media of gedeelde netwerklokaties wanneer deze worden aangesloten of benaderd.
| bind | off | bind | Naamserver. De meeste gebruikers vertrouwen op een externe. Schakel in als je een eigen naamserver wilt draaien op je systeem.
| bitlbee | on | bitlbee | BitlBee is een IRC daemon die met  instant  messaging  netwerken kan praten en fungeert als een gateway. Gebruikers kunnen met de server verbinden met elke normale IRC client en hun 'buddy list' in bitlbee zien.
| bluetooth | on | bluez | Maakt communicatie met bluetooth apparaten mogelijk
| brltty|  | brltty | Zorgt voor communicatie met een Braille terminal of schermlezer. Geactiveerd als dit tijdens de installatie is ingesteld.
| cgconfig | on | libcgroups | Voert cgconfigparser uit die /etc/cgconfig.conf leest om de control group hierarchie in te stellen, inclusief de permissies (UID and GID) van de groups en eventuele instelbare parameters van de controllers. Dit ontlast ons dit steeds zelf te moeten doen na het opstarten door middel van het uitvoeren van een speciaal shell script. Dit script is standaard uitvoerbaar maar zal pas echt iets doen als /etc/cgconfig.conf wordt aangepast (alle regels zijn standaard als commentaar gemarkeerd)
| cgred | on | libcgroups | De control groups zorgen voor de toekenning van systeembronnen zoals CPU-tijd or RAM aan "groups" van gebruikers en/of processen. Dit script start de cgroups rules engine daemon die automatisch de processen die hun effectieve UID or GID wijzigen aan de juiste control groups toewijst. Alhoewel het standaard uitvoerbaar is moeten er wel regels aanwezig zijn in /etc/cgrules.conf om het te laten werken.
| consolekit | on | ConsoleKit2 | Deze daemon wordt gebruikt door polkit's auth agent om de privileges te controleren van gebruikers die bijvoorbeeld het systeem willen afsluiten of opnieuw opstarten.
| cpufreq | on | sysvinit-scripts | Instellingen voor CPU frequentie en voltage voltage in de kernel.
| crond | on | crond |De cron daemon draait op de achtergrond en voert gebruikerstaken uit op de ingestelde tijd.  
| cups | on | cups | Start/stop script voor de CUPS printserver.
| cups-browsed | off | cups-filters | Maakt printers op afstand lokaal beschikbaar.
| dnsmask | off | dnsmask | Start/stopt/herstart dnsmasq (een kleine DNS- en DHCP-server)
| dovecot | off | dovecot |  Dovecot is een open source IMAP en POP3 server voor Linux/UNIX-achtige systemen, geschreven met veiligheid op de eerste plaats. 
| elogind | on | elogind | elogind is de logind van het systemd project, overgenomen als een opzichzelfstaand pakket.
| espeakup | | espeakup | starts/stopt/herstart de espeakup console schermlezer. Is actief als spraak tijdens de installatie werd ingeschakeld of later door het typen van speak-with espeakup
| fail2ban | off | fail2ban | start/stopt fail2ban die logbestanden zoals /var/log/pwdfail scant, blokkeert IP-adressen die teveel foute wachtwoorden geven en update hiervoor firewall regels.
| fenrir | off | fenrir | starts/stopt/herstart de fenrir schermlezer welke na installatie met speak-with fenrir gestart kan worden.
| font | off | kbd | Stelt het lettertype voor de console in (in Console modus, niet in Grafische modus)
| fuse | on | fuse | Laadt de fuse module en koppelt het fuse control bestandssysteem aan. FUSE is een eenvoudige interface voor userspace programma's om een virtueel bestandssysteem naar de kernel te kunnen exporteren. FUSE laat niet gemachtigde gebruikers op een veilige manier hun eigen bestandssystemen maken en aankoppelen.
| fuse3 | on | fuse3 | Versie 3 van FUSE
| gpm | on | gpm | The General Purpose Mouse server laat je tekst van en in een console met de muis kopieren, knippen en plakken.
| haveged | on | haveged |  Het haveged project is een eenvoudig te gebruiken onvoorspelbare random number generator gebaseerd op het HAVEGE algoritme.
| httpd | off | httpd | Starts of stopt de Apache webserver
| icecc-scheduler | off | icecream | Start/stopt/herstart de icecream (distributed compiler) scheduler
| iceccd | off | icecream | Start/stopt/herstart de icecream (distributed compiler) daemon
| inet1 | on | network-scripts | Dit script wordt gebruikt om de verschillende netwerkinterfaces te starten.
| inet2 | on | network-scripts | Dit shell script start het gehele netwerksysteem.
| inetd | on | inetd | BSD "super-server" daemon. De gebruiker dient /etc/inetd.conf aan te passen voor de daadwerkelijk te gebruiken diensten.
| ip_forward | off | network-scripts | Start/stopt IP packet forwarding, is nodig als je je computer als router wilt gebruiken.
| kadmind | off | krb5 | Start de Kerberos administratie server
| kprprod | off | krb5 | Start de Kerberos V5 slave KDC update server.  
| krb5kdc |off | krb5 |  Start krb5kdc, de Kerberos versie 5 Authentication Service en Key Distribution Center (AS/KDC). Dit moet als eerste draaien op zowel master als secundaire KDCs.
| local | off | sysvinit-scripts | start daemons die niet worden gestart door /etc/rc.d/rc.M tijdens het opstarten.
| loop | on | sysvinit-scripts | Laadt de loop device kernel module.
| lxc | off | lxc | Dit scripts start (indien ingesteld om automatisch te starten) en stopt lxc containers.
| mcelog | off | mcelog | Start de mcelog hardware error logging. Dit logt en verwerkt CPU hardware fouten op x86 systemen
| messagebus | on | dbus | De systeembrede D-BUS message bus. Dit is een daemon die notificaties uitzendt van systeemgebeurtenissen en andere meldingen en zorgt voor communicatie tussen processen onderling.
| modules | on | sysvinit-scripts | Bepaalt afhankelijkheden voor kernel modules en start andere scripts die modules laden die niet automatisch door uedev worden geladen voor bijvoorbeeld specifieke kernel versies
| modules.local | on | sysvinit-scripts | Laadt modules die niet automatisch door uedev worden geladen
| mysqld | off | mariadb | Start/stopt de MariaDB server. MariaDB is een volledig compatibele afsplitsing van MySQL
| networkmanager|  | NetworkManager | Deze daemon schakelt automatisch over naar de beste netwerkverbinding. Is actief als NetworkManager gekozen werd tijdens of na de installatie om het netwerk te configureren
| nfsd | off | nfs-utils | Start/stopt een nfs (Network File Server)
| ntpd | on | ntp | Start/stopt een ntp ( Network Time Protocol) daemon.
| numlock|  | salixtools | Activeert numlock in de console
| openldap | off | openldap | Start de ldap (Lightweight Directory Access Protocol) server
| openvpn | off | openvpn | Start de OpenVPN (secure IP tunnel) daemon
| pcmcia | off | pcmciautils | Script om het PCMCIA subsysteem de configureren.
| php-fpm | off | php | Start de PHP FastCGI Process Manager daemon.
| postfix | off | postfix | start Postfix, mail transport en submission agent.
| pulseaudio | off | pulseaudio | Start pulseaudio systeembreed. Dit wordt niet aanbevolen  in Slint.
| rpc | off | rpcbind | Start/stop/herstart RPC (remote process communications) daemons nodig voor NFS. Deze moeten worden gestart om een NFS server te kunnen draaien.
| samba | off | samba | Start/stopt/herstart de Samba SMB CIFS bestands- en printserver voor CIFS clients.  It allows you to manage a file space or printers on a Samba host available to CIFS clients (such as PCs running Windows).
| saslauthd | off | cyrus-sasl | saslauthd is a daemon process that handles plaintext authentication requests on behalf of the SASL library.  The CMU Cyrus SASL library is mostly used to authenticate to mail servers.
| serial | off | util-linux | Initializes and sets the serial ports on your system
| setterm | on |util-linux |  Provides the command line for the setterm utility to set the terminal attributes (primarily used for screen blanking and power management).
| smartd | off | smartmontools | Start/stop/restart the smartd daemon, which monitors the status of S.M.A.R.T. compatible hard drives and reports any problems.
| snmpd | off | net-snmp |Start/stop the net-snmp SNMP (Simple Network Management Protocol) daemon
| speechd-up |  | speechd-up | starts/stop/restart the speechd-up screen reader, which can be started after installation typing speak-with speechd-up.
| sshd | on | openssh | Start/stop/restart the secure shell daemon.
| swapinzram | on | swapinzram | Configure a swap block device in RAM using zram
| syslog | on | sysklogd | Start/stop/restart the system logging daemons, that logs both kernel and system's messages.
| sysstat | off | systat | Reset the system activity logs, used to compute performance statistics
| sysvinit | on | sysvinit-scripts | This file provides basic compatibility with SystemV style startup scripts found in many binary packages
| syslog | on | syslogd | Start/stop/restart the system logging daemons.
| sysstat | off | sysstat | Reset the system activity logs.
| timidity | off | TiMidity++ | Start/stop/restart the TiMidity++ daemon. TiMidity++ is a software synthesizer. It can play MIDI files by converting them into PCM waveform data or other various audio file formats.
| udev | on | eudev | This script initializes udev, which populates the /dev directory with device nodes, scans for devices,
loads the appropriate kernel modules, and configures the devices.
| ulogd | on | ulogd | starts the userspace ulogd daemon for netfilter/iptables related logging.
| vde2 | on | vde2 | Start/stop/restart the VDE daemon. VDE is an ethernet compliant virtual network which includes tools such as 'vde_switch' and 'vdeqemu'.
| wireless | on | wireless-tools|This script sets up PCI, USB, and 32-bit Cardbus wireless devices. Normally this script is called from rc.inet1 rather than run directly
| yp | on | yptools | Start NIS (Network Information Services). NIS zorgt voor distributie van hostname, gebruikersnaam en andere informatie over het netwerk.
|====

Je kunt een service starten of stoppen door als root de opdracht `service` te gebruiken. Voor meer informatie type je `man service`.
// Glossary
== Woordenlijst

Several definitiaans in this glossary are taken or adapted from https://en.wikipedia.org/wiki/Main_Page[Wikipedia] and https://pubs.opengroup.org/onlinepubs/9699919799/[POSIX]

[[applicatiaan]]Applicatie:: An applicatiaan program (applicatiaan for short) is a computer program designed to carry out a specific task typically requested by end-users.
+
Toepassingen worden in het algemeen niet beschouwd als onderdeel van het besturingssysteem, wat betekent dat ze na installatie aan het systeem kunnen worden toegevoegd. Ze voeren niet-systeemgerelateerde functies uit, zoals tekstverwerking, architectuurontwerp, mechanisch ontwerp, publicatie of financiële analyse.


[[boot]]Opstarten of booten::
Boot means switch-aan a computer to start an operating system. Op dezelfde computer kunnen meerdere besturingssystemen worden geïnstalleerd. Select which one to load into RAM and run can be daane either by the firmware or by a software named boot manager (GRUB in Slint's case). The firmware of a computer can support aane of following booting mode, or both:
+
* In the Legacy or BIOS mode the OS is loaded executing the instructiaans written in a boot sector.
* In EFI-modus wordt het besturingssysteem geladen door een OS-loader, opgeslagen in een uitvoerbaar bestand op een EFI-systeempartitie (ESP).

[[CPU]]CPU::
De CPU of Central Processing Unit voert de instructies van programma's uit.

[[command]]Opdracht of commando:: Een commando of opdracht is gedefinieerd door https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_104[POSIX] als "een opdracht aan een <<shell, shell>> om een specifieke taak uit te voeren".
+
Die uit te voeren taak kan een <<application, programma>> of een <<utility, hulpprogramma>> zijn.
+
De basisstructuur van shell-commando's is gedefinieerd in het hoofdstuk https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09[2.9 Shell-commando's] van de POSIX-specificatie.
+
De <<bash shell>> bevat voorbeelden van commando's.

[[console]]Console:: Het woord "console" verwijst naar vroegere computersystemen waarbij op dit apparaat - bestaande uit een toetsenbord en een printer gekoppeld aan een computer - door de systeembeheerder commando's werden getypt en de uitvoer werd afgedrukt, zo een log producerend.
+
In personal computers typt de gebruiker de commando's op het toetsenbord waarvan de uitvoer wordt afgedrukt op een scherm gescheiden van of geïntegreerd met de computer zoals in een laptop.

[[device]]Apparaat::

Een randapparaat of een object dat als zodanig aan de applicatie verschijnt.[POSIX]

[[directory]]Directory::
Een directory is een andere naam voor een map. Bestandssystemen gebruiken mappen om bestanden binnen partities te organiseren.
+
Mappen kunnen bestanden maar ook andere mappen bevatten. De resulterende structuur kan worden weergegeven als een omgekeerde boom. De map op het hoogste niveau van een station heet de hoofdmap. In Linux scheidt het teken / de niveaus van de boom. / alleen representeert de root directory, /home bevat de bestanden van alle gebruikers dus /home/didier bevat de bestanden van didier. /root bevat de bestanden van de gebruiker root (de systeembeheerder). Opmerking: 'root' kan verwijzen naar de map op het hoogste niveau maar ook naar de systeembeheerder.

[[drive]]Schijf::
Een schijf is een apparaat dat niet-vluchtige gegevens opslaat, wat betekent dat de gegevens niet verloren gaan wanneer het apparaat of de computer wordt uitgeschakeld. Voorbeelden: harde schijven, SSD's, USB-sticks, SD kaarten en eMMC's.
+
Het medium waarop de gegevens zijn opgeslagen kan permanent met de machine verbonden zijn of verwijderbaar zoals SD-kaarten, USB-sticks en schijven die via USB zijn aangesloten.
+
Een besturingssysteem dat is geïnstalleerd op een verwijderbaar medium of een externe schijf is draagbaar: het kan van de ene computer naar de andere worden verplaatst.

[[display_manager]]Display Manager::
Een display-manager (of login-manager) is een programma dat een venster toont waarin wordt gevraagd naar de gebruikersnaam en het wachtwoord van de gebruiker en start vervolgens de door deze gebruiker gekozen grafische omgeving.

[[encryption]]Versleuteling::
Versleuteling is het proces van het converteren van gegevens naar een onherkenbare ("gecodeerde") vorm. Het wordt vaak gebruikt om gevoelige informatie te beschermen, zodat alleen geautoriseerde personen die kunnen bekijken. Een enkel bestand of directory, een partitie maar ook een hele schijf kan worden versleuteld die dan alleen toegankelijk is nadat een geheime korte tekst genaamd een wachtwoordzin is ingetypt.

[[file]]Bestand::
Een computerbestand is een reeks digitale gegevens die zijn verzameld onder dezelfde naam en behandeld als een eenheid, opgeslagen op een permanent opslagmedium, genaamd massa-opslag, zoals een harde schijf, een SSD, een DVD, een SD-kaart of een USB-stick.
+
Bestanden kunnen gegevens zoals teksten, afbeeldingen, geluiden, video's of computerprogramma's bevatten.

[[file_system]]Bestandssysteem::
Een bestandssysteem is software die de bestanden en mappen in een partitie beheert. Het onthoudt de locatie van de gegevens in de bestanden op het fysieke medium waardoor het mogelijk is ze te lezen of te schrijven. Voorbeelden van veel gebruikte bestandssystemen zijn vfat, ntfs, ext4, f2fs. Deze opdracht geeft een overzicht van alle bestandssystemen die gegevens op een Linux-partitie bevatten:
+
----
cat /proc/filesystems|grep -v nodev
----

[[firmware]]Firmware::
De firmware is de software die de hardware initialiseert en controleert en daarna het geselecteerde besturingssysteem in het RAM laadt of start een programma genaamd boot-manager die dat zal doen. De firmware is opgeslagen in niet-vluchtige geheugens zoals ROM, EPROM, of flashgeheugen. Het is het eerste stukje software dat wordt uitgevoerd wanneer een computer opstart. Het toont een menu dat het mogelijk maakt om de hardware te configureren en de opstartmodus te selecteren (Legacy of EFI) en in welke volgorde te zoeken naar het besturingssysteem of een andere toepassing (zoals de GRUB boot manager).

[[kernel]]Kernel::
Een Linux kernel is de software die de kern van een Slint systeem vormt en dat alle interacties afhandelt tussen de applicaties en de hardware.
+
Het is een enkel bestand dat is geïnstalleerd in de map /boot. Het bestand /boot/vmlinuz-generic-5.12.11 is bijvoorbeeld een kernel uit het kernel-generic pakket.
+
Bij het opstarten wordt de kernel naar het RAM gekopieerd.

[[initrd]]Initrd::
Een initrd (of iets preciezer een initramfs of eerste RAM bestandssysteem voor Slint) is een Linux systeem in de vorm van een gecomprimeerd archiefbestand. Bij het opstarten wordt vlak nadat de kernel in RAM geladen is ook de initrd in het RAM geladen. Het bestand /init wordt uitgevoerd: het laadt benodigde kernel modules in het RAM, registreert de apparaten, ontgrendelt eventueel de root-partitie en de pseudo-bestandssystemen worden aangekoppeld waarna wordt overgeschakeld naar het root bestandssysteem om het systeem daadwerkelijk te starten.
+
Een initrd is een enkel bestand dat ook in de map /boot is geïnstalleerd. Het bestand initrd-generic-5.12.11 is een initrd

[[live_system]]Live systeem::
Een live systeem is een besturingssysteem dat zich in plaats van geïnstalleerd te worden op een apparaat zoals een harde schijf of SSD geheel in het <<RAM>> bevindt.
+
Een initrd is ook een live systeem zoals het Slint installatieprogramma in de basis ook een initrd is.

[[partition]]Partitie::
Een partitie is een deel van een opslagmedium, zoals een harde schijf of SSD. Het wordt door het besturingssysteem gezien als een afzonderlijk logisch volume, waardoor het functioneert als een opzichzelfstaand apparaat.

[[partition_table]]Partitietabel::
Een partitietabel is de permanente structuur waarin is vastgelegd hoe gegevens op het medium worden opgeslagen, met name het begin en het einde van elke partitie op dat medium.
+
De meest voorkomende typen partitietabellen zijn de DOS-partitietabel, aanvankelijk gebruikt door het MS-DOS-besturingssysteem, en de GUID-partitietabel of GPT, die het mogelijk maakt om meer partities en grotere schijven te kunnen gebruiken.

[[program]]Programma::
Een voorbereide reeks instructies voor het systeem om een gedefinieerde taak uit te voeren. De term "programma" omvat toepassingen die zijn geschreven in de shell Command Language, complexe utility-invoertalen (bijvoorbeeld awk, Lex, sed, enzovoort), en zogenaamde high-level languages. [POSIX]

[[RAM]]RAM::
RAM staat voor Random Access Memory. Dit type geheugen slaat vluchtige gegevens op, wat betekent dat de gegevens worden gewist wanneer de stroom wordt uitgeschakeld.

[[shell]]Shell:: Een programma dat opeenvolgende tekstinvoer als opdrachten interpreteert. Het kan werken op een invoerstroom of het kan interactief commando's lezen vanuit een terminal. De schrijfwijze van de commando's die door de shell kunnen worden geïnterpreteerd verschilt per shell maar zijn hoofdzakelijk gedefinieert in het hoofdstuk https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html[2. Shell Command Language] van de POSIX specificatie.
+
Slint bevat verschillende shells weergegeven in het bestand /etc/shells. Standaard wordt de *bash* shell gebruikt.

[[swap]]Wisselgeheugen of swap::
Een swap-ruimte wordt gebruikt om gegevens uit het RAM op te slaan op een apparaat zoals een harde schijf of SSD ofwel omdat het RAM anders te vol zou worden of om RAM vrij te maken voor het opslaan van de vaakst gebruikte gegevens. De swap-ruimte kan een partitie van het type 'Linux swap' zijn op een schijf of een standaard wisselgeheugenbestand op een bestaande partitie. Er is ook zo iets als 'swap in zram': in dit geval worden de gegevens opgeslagen in RAM maar in gecomprimeerde vorm.

[[terminal]]Terminal::
Historisch was een terminal een fysiek apparaat bestaande uit een toetsenbord en een beeldscherm dat gebruikt werd om commando's te typen en uitvoer te lezen van een externe computer.
+
Tegenwoordig kunnen de opdrachten zowel in console (of tekst) modus als in grafische modus worden getypt.

[[utility]]Hulpprogramma of tool::
Een hulpprogramma of tool is een programma dat met zijn naam kan worden aangeroepen vanuit een shell (dit geldt ook voor sommige <application,applications>>).
+
Hulpprogramma's maken deel uit van het besturingssysteem (maar niet van de kernel). Ze voeren systeemgerelateerde functies uit, zoals het weergeven van directory-inhoud en bestandssystemen, het repareren van bestandssystemen of het vergaren van informatie over de systeemstatus.
+
Een hulpprogramma kan worden opgeroepen als een afzonderlijk programma dat wordt uitgevoerd in een ander proces dan de command language interpreter, of het kan worden geïmplementeerd als een onderdeel van de command language interpreter.
+
De echo opdracht (de instructie om een bepaalde taak uit te voeren) bijvoorbeeld kan zodanig worden geïmplementeerd dat deze opdracht (de code waarmee de taak van het echo-en wordt uitgevoerd) in een apart programma staat en daarom wordt uitgevoerd in ander proces dan de command language interpreter. In de praktijk betekent dit dat in dit geval het hulpprogramma niet in de shell wordt uitgevoerd
+
Omgekeerd kan de code waarmee het echo-programma wordt uitgevoerd, worden ingebouwd in de command language interpreter. Het wordt dan uitgevoerd in hetzelfde proces als de command language interpreter. Van een dergelijk hulpprogramma wordt gezegd dat het in de shell is ingebouwd ("built-in").

[[virtual_terminal]]Virtuele terminal::
Een virtuele terminal is software die een fysieke terminal bestaande uit een toetsenbord en een beeldscherm simuleert om met een computer op afstand te communiceren.
