:toc: left
:toclevels: 1
:toc-title: 

// Overview
[[Overview_of_Slint_Installation]]
== Overzicht van het installatieproces

Het installatieprogramma detecteert als eerste de aanwezige schijven en partities voor mogelijke installatie-opties en laat je kiezen tussen het automatisch of handmatig voorbereiden van de door Slint te gebruiken partities.

Als je "handmatig" kiest krijg je een lijst te zien met Linux partities (van minimaal 50G) waarop Slint kan worden geïnstalleerd. Selecteer de gewenste partitie en het type bestandssysteem dat er op zal wordt gemaakt: btrfs, ext4 of xfs zoals aangegeven in <<prepare_partitions_for_Slint,Optioneel voorbereiden van partities voor Slint>>

Als je 'auto' kiest, krijg je de stations te zien waarop Slint kan worden geïnstalleerd (ten minste 50G groot) en zal het btrfs bestandssysteem worden gebruikt.

In het geval van btrfs worden subvolumes met gecomprimeerde bestanden aangemaakt voor//home en /snapshots en /swap voor een swap bestand. Met 'Copy on write' is het mogelijk snapshots te maken en een mislukte systeem-update ongedaan te maken. Tools voor het beheren van de snapshots zijn in Slint aanwezig.

In beide modi kiest de gebruiker welke bestaande Linux-en Windows-partities automatisch worden aangekoppeld na het opstarten van Slint en de namen van de aankoppelpunten wat de toegang tot bestaande systemen en gegevens vanuit Slint vergemakkelijkt.

Vervolgens wordt de gebruiker voorgesteld om de root systeempartitie te versleutelen waarmee gegevensverlies kan worden voorkomen in geval van verlies of diefstal van de machine of het station waarop Slint is geïnstalleerd. Indien positief bevestigd legt het installatieprogramma de wachtwoordzin vast waarmee deze partitie kan worden ontgrendeld. De gebruiker zal hier tijdens het opstarten door GRUB om worden gevraagd om het opstartmenu weer te geven.

Uiteindelijk toont het installatieprogramma de door jou gemaakte keuzes en vraagt je die al dan niet te bevestigen. Tot nu toe is er nog niets aan het geïnstalleerde systeem gewijzigd zodat je veilig kunt annuleren en zonder gevolgen opnieuw 'start' kunt typen of opnieuw kunt opstarten.

Dan wordt, in geval van auto-partitionering, de Slint rootpartitie versleuteld indien gewenst en geformatteerd en worden de eerste softwarepakketten geïnstalleerd.

Als je voor een versleutelde schijf hebt gekozen, typ je de wachtwoordzin die zal worden gebruikt om de schijf steeds bij het opstarten te ontgrendelen.

Je kiest een wachtwoord voor gebruiker "root". Dit is de systeembeheerder die alle bevoegdheden heeft.

Je geeft ook de gebruikersnaam en het wachtwoord van een gewone gebruiker.

Je geeft aan of je Braille-uitvoer nodig hebt en of je je wilt aanmelden in tekst of grafische modus. Als je tijdens de installatie de Engelse (US) taal hebt gebruikt, kies je de taal die je in het geïnstalleerde systeem wilt gebruiken. Anders stelt het installatieprogramma dezelfde taal in als tijdens de installatie.

Het installatieprogramma probeert nu een internetverbinding te maken om een tijdzone die overeenkomt met je geografische locatie voor te stellen of uit een lijst te laten kiezen.

Er wordt je gevraagd of je Braille nodig hebt en dan of je wilt starten in een console of in een grafische omgeving tenzij je spraak hebt gebruikt tijdens de installatie of dat je Braille nodig hebt. In dat geval belandt je voor alle veiligheid na het opnieuw opstarten in een console.

Dan maakt het installatieprogramma een wisselbestand. Dit kan even duren dus wees geduldig.

Alle andere pakketten worden op de schijf geïnstalleerd. Indien verbonden met internet wordt de meest recente versie van elk pakket inclusief die beschikbaar gekomen zijn na het uitkomen van de ISO-image gedownload en geïnstalleerd.

Afhankelijk van de hardware duurt de installatie van alle pakketten 10 tot 40 minuten.

Er wordt je gevraagd een desktop te selecteren (zelfs als je in een console begonnen bent) waaronder fvm, lxqt, mate en wmaker. Na de installatie krijg je wanneer je bent opgestart in een console door het typen van 'xwmconfig' een nog uitgebreidere keuze

Hierna wordt het systeem geconfigureerd en de GRUB boot manager geïnstalleerd. Slint kan opstarten in zowel Legacy als EFI modus. Het boot- menu heeft een "rescue" keuzemogelijkheid om elk geïnstalleerd OS te herkennen en op te starten.

Voordat je opnieuw opstart is het mogelijk een voorbeeld van het opstartmenu weer te geven.

Verwijder tenslotte het installatiemedium en herstart je nieuwe Slint-systeem.
// Usage_installer
[[Usage_of_the_installer]]
== Gebruik van het installatieprogramma

Als je bekend bent met de Linux console kun je dit onderwerp overslaan.

Hieronder wordt het hoofdmenu van het installatieprogramma weergegeven:
....
Welkom bij het Slint installatieprogramma! (versie 15)

Je kunt nu typen (zonder de aanhalingstekens):

'doc' om de functies en het gebruik van het installatieprogramma te leren kennen.
'start' om de installatie te starten.

Het installatieprogramma kan de schijf waarop Slint wordt geïnstalleerd voorbereiden/n
en de benodigde partities aanmaken. Je kunt dat ook zelf handmatig doen met behulp van/n
de aanwezige hulpprogramma's. Typ 'start' als je hiermee klaar bent. Je kunt ook het/n
installatieprogramma verlaten en een programma als gparted gebruiken waarna je het/n
installatieprogramma weer start.

We raden je aan eerst 'doc' te typen in geval je de Slint rootpartitie wilt versleutelen.
Wanneer je hier mee klaar bent wordt dit menu weer weergegeven.
....

Zodra dit menu wordt weergegeven kun je beginnen met het installatieproces.

Je leest het scherm en typt commando's in een <<virtual_terminal,virtuele terminal>>. Het installatieprogramma beschikt over 4 virtuele terminals die hetzelfde fysieke toetsenbord en scherm gebruiken en tegelijkertijd naast elkaar gebruikt kunnen worden.

Het installatieprogramma start in virtuele terminal 1 genaamd *tty1* maar je kunt naar een andere terminal overschakelen. Je kunt bijvoorbeeld overschakelen naar *tty2* door op *Alt-F2* te drukken en later weer terug naar *tty1* met *Alt-F1* zonder informatie in beide terminals te verliezen. *Alt-F1* betekent: hou de *Alt* toets ingedrukt en druk tegelijkertijd op de *F1* toets.

Dit kan bijvoorbeeld handig zijn voor het lezen van documentatie tijdens de installatie: je kunt overschakelen naar *tty2* waar je de installatie start, weer terug naar *tty1* om de documentatie te lezen en vervolgens weer naar *tty2* om verder te gaan met de volgende installatiestap.

Zo kun je ook de woordenlijst raadplegen tijdens het lezen van andere documenten.

Het installatieprogramma heeft verschillende manieren van interactie met de gebruiker:

* Je voert opdrachten in bij de prompt en leest hun uitvoer.
* Het installatieprogramma stelt een vraag, je typt het antwoord en je bevestigt dit door op Enter te drukken.
* Het installatieprogramma toont een keuzemenu met meerdere opties: je selecteert er één met de pijltjestoetsen omhoog en omlaag en je bevestigt vervolgens je keuze door op Enter te drukken of op Esc om te annuleren.
* Het installatieprogramma geeft informatie weer in een pager. Gebruik de pijltjestoetsen om de vorige of volgende regel te lezen, druk op de spatiebalk om de volgende pagina weer te geven of q om de pager te verlaten.

// Prepare
[[prepare_partitions_for_Slint]]
== Optioneel het voorbereiden van de Slint partities

Een partitie 'formatteren' betekent hier: het maken van een bestandssysteem om de bestanden die het bevat te kunnen beheren.

Na het typen van 'start' type je 'm' voor handmatig partitioneren en selecteer je als eerste de root systeempartitie aangekoppeld op "/" en het te gebruiken bestandssysteem waaronder btrfs, ext4, xfs.

Het installatieprogramma toont een keuzelijst met alleen niet versleutelde Linux partities (ook wel Linux bestandssysteem genoemd) van minimaal 50G. Deze mag al geformatteerd zijn maar alle bestanden hierop zullen bij het maken van het nieuwe bestandssysteem verloren gaan.

Handmatige partitionering vereist op de schijf met het root bestandssyteem ook de aanwezigheid van:

* Een niet geformatteerde BIOS opstartpartitie van minimaal 3M.
* Een volgens de UEFI specificatie 'fat' (of 'vfat') geformatteerde EFI systeempartitie van minimaal 32M

Het gebruik van bestaande Slint partities of het maken hiervan is aan de gebruiker. Reeds geïnstalleerde systemen met BIOS opstart en EFI partities blijven intact, alleen de root partitie zal (opnieuw) worden geformatteerd.

Het installatieprogramma bevat diverse partioneringsprogramma's: cfdisk, fdisk, sfdisk, cgdisk, gdisk, sgdisk en parted. De programma's met een "g" in hun naam kunnen alleen overweg met GPT schijven, parted met zowel DOS als GPT partities. fdisk, cfdisk en sfdisk kunnen overweg met DOS partities. Ook zijn wipefs (om bestaande partitietabellen en bestandssysteemhandtekeningen te wissen) en partprobe (om de kernel te informeren over partitiewijzigingen) aanwezig. De programma's blkid en lsblk geven informatie weer over block devices en partities.

Uiteraard kun je de partities ook vanaf een ander systeem maken voordat je het installatieprogramma start.
// Installation
// Encryption
[[Encryption]]
== Slint met een versleutelde rootpartitie.

In automatische modus stelt het installatieprogramma voor om de schijf waarop Slint wordt geïnstalleerd als deze volledig aan Slint is toegewezen te versleutelen. Als je hiermee akkoord gaat zal GRUB je telkens als je opstart de wachtwoordzin vragen die je hebt opgegeven tijdens de installatie om de schijf te ontgrendelen voordat het opstartmenu wordt weergegeven. Wees je ervan bewust dat het ontgrendelen van het station even duurt (ongeveer tien seconden).

Met een versleutelde schijf voorkom je diefstal van gegevens die er op staan in geval van verlies of diefstal van de machine of van een verwijderbare schijf. Het beschermt je echter niet als je de computer onbewaakt aan laat staan en alleen als de computer volledig is uitgeschakeld!

Tijdens de installatie zal de Slint systeempartitie evenals de gewenste extra partities worden versleuteld.

De naam van een versleutelde Slint systeem- (of root) partitie is: /dev/mapper/cryptroot.

Dit kun je zien door het uitvoeren van deze opdracht:

----
lsblk -lpo name,fstype,mountpoint /h grep /$
----

Met het volgende resultaat:
----
/dev/mapper/cryptroot ext4   /
----

Het uitvoeren van deze opdracht:

----
lsblk -lpo name,fstype,mountpoint | grep /dev/sda3
----

geeft:

----
/dev/sda3             cryptoLUKS
----

/dev/sda3 is nu een "raw" partitie die de zogenaamde "LUKS header" bevat waar je nooit direct toegang toe zou moeten of hoeven te hebben. Het bevat alles wat nodig is om de partitie /dev/mapper/cryptroot die eigenlijk jouw gegevens bevat (in dit voorbeeld het Slint-systeem) te versleutelen.

[WARNING]
====
Als je de wachtwoordzin vergeet, zullen alle gegevens in het station onherstelbaar verloren gaan! Dus noteer deze wachtwoordzin of sla hem op en bewaar hem meteen op een veilige plaats.

Schijven gaan vroeg of laat kapot. Als dat gebeurt en de schijf is versleuteld gaan je gegevens verloren. Regelmatig een back-up maken van je waardevolle gegevens is dus niet optioneel maar essentieel!

Maak ook een back-up van de LUKS header zodat je die kunt herstellen als de LUKS partitie om welke reden dan ook zou beschadigen. Het commando hiervoor zou in ons voorbeeld kunnen zijn:
----
luksHeaderBackup /dev/sda3 --header-backup-file <file>
----
waar <file> de naam is van het back-up bestand dat je op een veilige plek bewaart.

Voor het herstellen van de back-up typ je:
----
luksHeaderRestore /dev/sda3 --header-backup-file <file>
----

Wijzig nooit de grootte van een partitie van een versleutelde schijf omdat deze hierna voorgoed ontoegankelijk is en de gegevens die er op staan verloren gegaan zullen zijn! Als je echt meer ruimte nodig hebt moet je een backup maken van alle bestanden die je wilt behouden, Slint opnieuw installeren en de geback-upte bestanden terugzetten.

Kies een sterke wachtwoordzin, zodat die voor een inbreker te lastig is om die te raden en hij het uiteindelijk zal opgeven.

Rommel nooit aan de zogenaamde "LUKS-header" op de 'raw' partitie (in ons voorbeeld /dev/sda3 op de Slint systeempartitie). Maak geen bestandssysteem aan in deze partitie, laat het geen deel uitmaken van een RAID array en schrijf er geen gegevens naar toe: hierdoor zullen alle gegevens namelijk onherstelbaar verloren gaan!
====

Om zwakke wachtwoordzinnen te vermijden vereist het installatieprogramma dat de wachtwoordzin bestaat uit:

. Ten minste 8 tekens.
. Alleen niet-geaccentueerde kleine letters en hoofdletters, cijfers van 0 tot 9, spaties en de volgende leestekens:
+
----
 ' ! " # $ % & ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~
----
+
Dit garandeert dat ook een nieuw toetsenbord alle tekens heeft die nodig zijn om het wachtwoord te typen.

. Ten minste één cijfer, één kleine letter, één hoofdletter en één leesteken.

GRUB gaat ervan uit dat er een "VS" toetsenbord wordt gebruikt wanneer je de wachtwoordzin typt. Om deze reden stelt het installatieprogramma als je tijdens de installatie gebruik maakt van een andere dan een "VS"-toetsenbord deze hierop in voordat je de wachtwoordzin typt en hierna weer terug naar de indeling die je hier voor gebruikte. In dit geval spelt het installatieprogramma ook elk ingetypt teken van de wachtwoordzin omdat dit kan verschillen van het teken dat op de toets geschreven staat.

Om de schijf te versleutelen wordt het programma cryptsetup gebruikt. Voor meer informatie hierover typ je na de installatie: +
-----
man cryptsetup
-----
// Speakup
[[Speakup]]
== Sneltoetsen voor de Speakup schermlezer

Dit hoofdstuk is bedoeld voor gebruikers die een schermleesprogramma nodig hebben maar niet bekend zijn met Speakup.

Zorg er wel voor dat NumLock is uitgeschakeld als je Speakup wilt gebruiken.

De CapsLock-toets gedraagt zich als een Shift-toets. "CapsLock 4" bijvoorbeeld betekent: +
hou de CapsLock-toets ingedrukt als een Shift-toets en druk op 4.

 De eerste sneltoetsen om te onthouden:
 PrintScreen     Schakel speakup aan of uit.
 CapsLock F1     Speakup Hulp (druk spatie om Hulp te verlaten).

 Sneltoetsen voor het wijzigen van instellingen:
 CapsLock 1/2    Verhogen/verlagen van geluidsvolume.
 CapsLock 5/6    Verhogen/verlagen van de spreeksnelheid.

 Sneltoetsen voor tijdens het lezen zelf:
 CapsLock j/k/l   Zeg vorig/huidig/volgend woord.
 CapsLock k (2x)    Spel het huidige woord.
 CapsLock u/i/o    Zeg de vorige/huidige/volgende regel.
 CapsLock y    Zeg de tekst vanaf bovenaan tot aan de cursor.
 CapsLock p    Zeg de tekst vanaf de cursor tot aan het einde.
// First_steps
[[first_steps_after_installation]]
== De eerste stappen na de installatie

Hier volgen de eerste taken die na de installatie moeten worden uitgevoerd.

In dit document is alle tekst na een # commentaar op de voorgestelde commando's en dient niet ingetypt te worden.

=== Eerste software-update

Na installatie moet het systeem worden bijgewerkt met de meest recente versie van elk programma, evenals nieuwe software die is uitgekomen sinds de voor de installatie gebruikte versie van het ISO-beeldbestand. Dit is vooral van belang als er geen netwerkverbinding beschikbaar was tijdens de installatie omdat dan alleen de pakketten in het distributiemedium -welke verouderd kunnen zijn- werden geïnstalleerd.

De meeste commando's die hieronder worden weergegeven vereisen administratieve rechten gekoppeld aan een specifiek account genaamd 'root' waarvoor je tijdens de installatie een wachtwoord hebt ingegeven.

Om een opdracht als root uit te voeren typ je eerst
----
su -
----
vervolgens typ je het wachtwoord voor 'root' en druk je op Enter voordat je het commando invoert.

Wanneer je klaar bent met het uitvoeren van commando's als 'root' druk je op Ctrl+d of typ je 'exit' om weer de "gewone gebruiker" status terug te krijgen.

Alternatief kan de tijdens de installatie als lid van 'wheel' groep geregistreerde gebruiker of andere leden hiervan typen:
----
sudo <command>
----
daarna weer het root-wachtwoord.

Om het systeem te updaten typ je als 'root' in een console of een grafische terminal:
----
slapt-get --add-keys # haalt de sleutels op om de pakketten te verifiëren
slapt-get -u # werkt de lijst van pakketten op de mirrors bij
slapt-get --install-set slint # downloadt de nieuwe pakketten
slapt-get --upgrade # installeert de nieuwe versies van geïnstalleerde pakketten
dotnew # toont gewijzigde configuratiebestanden
----
Wanneer je dotnew uitvoert accepteer je dat alle oude configuratiebestanden door nieuwe vervangen worden. Dit kun je nu nog veilig doen omdat je nog niets aan het systeem hebt aangepast.

Je kunt ook de grafische varianten van deze toepassingen gebruiken: gslapt in plaats van slapt-get en dotnew-gtk in plaats van dotnew.

Voor meer informatie over slapt-get typ je:
----
man slapt-get
----
of als 'root':
----
slapt-get --help
----
en lees /usr/doc/slapt-get*/README.slaptgetrc.Slint

// Glossary
== Woordenlijst

Several definitiaans in this glossary are taken or adapted from https://en.wikipedia.org/wiki/Main_Page[Wikipedia] and https://pubs.opengroup.org/onlinepubs/9699919799/[POSIX]

[[applicatiaan]]Applicatie:: An applicatiaan program (applicatiaan for short) is a computer program designed to carry out a specific task typically requested by end-users.
+
Toepassingen worden in het algemeen niet beschouwd als onderdeel van het besturingssysteem, wat betekent dat ze na installatie aan het systeem kunnen worden toegevoegd. Ze voeren niet-systeemgerelateerde functies uit, zoals tekstverwerking, architectuurontwerp, mechanisch ontwerp, publicatie of financiële analyse.


[[boot]]Opstarten of booten::
Boot means switch-aan a computer to start an operating system. Op dezelfde computer kunnen meerdere besturingssystemen worden geïnstalleerd. Select which one to load into RAM and run can be daane either by the firmware or by a software named boot manager (GRUB in Slint's case). The firmware of a computer can support aane of following booting mode, or both:
+
* In the Legacy or BIOS mode the OS is loaded executing the instructiaans written in a boot sector.
* In EFI-modus wordt het besturingssysteem geladen door een OS-loader, opgeslagen in een uitvoerbaar bestand op een EFI-systeempartitie (ESP).

[[CPU]]CPU::
De CPU of Central Processing Unit voert de instructies van programma's uit.

[[command]]Opdracht of commando:: Een commando of opdracht is gedefinieerd door https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_104[POSIX] als "een opdracht aan een <<shell, shell>> om een specifieke taak uit te voeren".
+
Die uit te voeren taak kan een <<application, programma>> of een <<utility, hulpprogramma>> zijn.
+
De basisstructuur van shell-commando's is gedefinieerd in het hoofdstuk https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09[2.9 Shell-commando's] van de POSIX-specificatie.
+
De <<bash shell>> bevat voorbeelden van commando's.

[[console]]Console:: Het woord "console" verwijst naar vroegere computersystemen waarbij op dit apparaat - bestaande uit een toetsenbord en een printer gekoppeld aan een computer - door de systeembeheerder commando's werden getypt en de uitvoer werd afgedrukt, zo een log producerend.
+
In personal computers typt de gebruiker de commando's op het toetsenbord waarvan de uitvoer wordt afgedrukt op een scherm gescheiden van of geïntegreerd met de computer zoals in een laptop.

[[device]]Apparaat::

Een randapparaat of een object dat als zodanig aan de applicatie verschijnt.[POSIX]

[[directory]]Directory::
Een directory is een andere naam voor een map. Bestandssystemen gebruiken mappen om bestanden binnen partities te organiseren.
+
Mappen kunnen bestanden maar ook andere mappen bevatten. De resulterende structuur kan worden weergegeven als een omgekeerde boom. De map op het hoogste niveau van een station heet de hoofdmap. In Linux scheidt het teken / de niveaus van de boom. / alleen representeert de root directory, /home bevat de bestanden van alle gebruikers dus /home/didier bevat de bestanden van didier. /root bevat de bestanden van de gebruiker root (de systeembeheerder). Opmerking: 'root' kan verwijzen naar de map op het hoogste niveau maar ook naar de systeembeheerder.

[[drive]]Schijf::
Een schijf is een apparaat dat niet-vluchtige gegevens opslaat, wat betekent dat de gegevens niet verloren gaan wanneer het apparaat of de computer wordt uitgeschakeld. Voorbeelden: harde schijven, SSD's, USB-sticks, SD kaarten en eMMC's.
+
Het medium waarop de gegevens zijn opgeslagen kan permanent met de machine verbonden zijn of verwijderbaar zoals SD-kaarten, USB-sticks en schijven die via USB zijn aangesloten.
+
Een besturingssysteem dat is geïnstalleerd op een verwijderbaar medium of een externe schijf is draagbaar: het kan van de ene computer naar de andere worden verplaatst.

[[display_manager]]Display Manager::
Een display-manager (of login-manager) is een programma dat een venster toont waarin wordt gevraagd naar de gebruikersnaam en het wachtwoord van de gebruiker en start vervolgens de door deze gebruiker gekozen grafische omgeving.

[[encryption]]Versleuteling::
Versleuteling is het proces van het converteren van gegevens naar een onherkenbare ("gecodeerde") vorm. Het wordt vaak gebruikt om gevoelige informatie te beschermen, zodat alleen geautoriseerde personen die kunnen bekijken. Een enkel bestand of directory, een partitie maar ook een hele schijf kan worden versleuteld die dan alleen toegankelijk is nadat een geheime korte tekst genaamd een wachtwoordzin is ingetypt.

[[file]]Bestand::
Een computerbestand is een reeks digitale gegevens die zijn verzameld onder dezelfde naam en behandeld als een eenheid, opgeslagen op een permanent opslagmedium, genaamd massa-opslag, zoals een harde schijf, een SSD, een DVD, een SD-kaart of een USB-stick.
+
Bestanden kunnen gegevens zoals teksten, afbeeldingen, geluiden, video's of computerprogramma's bevatten.

[[file_system]]Bestandssysteem::
Een bestandssysteem is software die de bestanden en mappen in een partitie beheert. Het onthoudt de locatie van de gegevens in de bestanden op het fysieke medium waardoor het mogelijk is ze te lezen of te schrijven. Voorbeelden van veel gebruikte bestandssystemen zijn vfat, ntfs, ext4, f2fs. Deze opdracht geeft een overzicht van alle bestandssystemen die gegevens op een Linux-partitie bevatten:
+
----
cat /proc/filesystems|grep -v nodev
----

[[firmware]]Firmware::
De firmware is de software die de hardware initialiseert en controleert en daarna het geselecteerde besturingssysteem in het RAM laadt of start een programma genaamd boot-manager die dat zal doen. De firmware is opgeslagen in niet-vluchtige geheugens zoals ROM, EPROM, of flashgeheugen. Het is het eerste stukje software dat wordt uitgevoerd wanneer een computer opstart. Het toont een menu dat het mogelijk maakt om de hardware te configureren en de opstartmodus te selecteren (Legacy of EFI) en in welke volgorde te zoeken naar het besturingssysteem of een andere toepassing (zoals de GRUB boot manager).

[[kernel]]Kernel::
Een Linux kernel is de software die de kern van een Slint systeem vormt en dat alle interacties afhandelt tussen de applicaties en de hardware.
+
Het is een enkel bestand dat is geïnstalleerd in de map /boot. Het bestand /boot/vmlinuz-generic-5.12.11 is bijvoorbeeld een kernel uit het kernel-generic pakket.
+
Bij het opstarten wordt de kernel naar het RAM gekopieerd.

[[initrd]]Initrd::
Een initrd (of iets preciezer een initramfs of eerste RAM bestandssysteem voor Slint) is een Linux systeem in de vorm van een gecomprimeerd archiefbestand. Bij het opstarten wordt vlak nadat de kernel in RAM geladen is ook de initrd in het RAM geladen. Het bestand /init wordt uitgevoerd: het laadt benodigde kernel modules in het RAM, registreert de apparaten, ontgrendelt eventueel de root-partitie en de pseudo-bestandssystemen worden aangekoppeld waarna wordt overgeschakeld naar het root bestandssysteem om het systeem daadwerkelijk te starten.
+
Een initrd is een enkel bestand dat ook in de map /boot is geïnstalleerd. Het bestand initrd-generic-5.12.11 is een initrd

[[live_system]]Live systeem::
Een live systeem is een besturingssysteem dat zich in plaats van geïnstalleerd te worden op een apparaat zoals een harde schijf of SSD geheel in het <<RAM>> bevindt.
+
Een initrd is ook een live systeem zoals het Slint installatieprogramma in de basis ook een initrd is.

[[partition]]Partitie::
Een partitie is een deel van een opslagmedium, zoals een harde schijf of SSD. Het wordt door het besturingssysteem gezien als een afzonderlijk logisch volume, waardoor het functioneert als een opzichzelfstaand apparaat.

[[partition_table]]Partitietabel::
Een partitietabel is de permanente structuur waarin is vastgelegd hoe gegevens op het medium worden opgeslagen, met name het begin en het einde van elke partitie op dat medium.
+
De meest voorkomende typen partitietabellen zijn de DOS-partitietabel, aanvankelijk gebruikt door het MS-DOS-besturingssysteem, en de GUID-partitietabel of GPT, die het mogelijk maakt om meer partities en grotere schijven te kunnen gebruiken.

[[program]]Programma::
Een voorbereide reeks instructies voor het systeem om een gedefinieerde taak uit te voeren. De term "programma" omvat toepassingen die zijn geschreven in de shell Command Language, complexe utility-invoertalen (bijvoorbeeld awk, Lex, sed, enzovoort), en zogenaamde high-level languages. [POSIX]

[[RAM]]RAM::
RAM staat voor Random Access Memory. Dit type geheugen slaat vluchtige gegevens op, wat betekent dat de gegevens worden gewist wanneer de stroom wordt uitgeschakeld.

[[shell]]Shell:: Een programma dat opeenvolgende tekstinvoer als opdrachten interpreteert. Het kan werken op een invoerstroom of het kan interactief commando's lezen vanuit een terminal. De schrijfwijze van de commando's die door de shell kunnen worden geïnterpreteerd verschilt per shell maar zijn hoofdzakelijk gedefinieert in het hoofdstuk https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html[2. Shell Command Language] van de POSIX specificatie.
+
Slint bevat verschillende shells weergegeven in het bestand /etc/shells. Standaard wordt de *bash* shell gebruikt.

[[swap]]Wisselgeheugen of swap::
Een swap-ruimte wordt gebruikt om gegevens uit het RAM op te slaan op een apparaat zoals een harde schijf of SSD ofwel omdat het RAM anders te vol zou worden of om RAM vrij te maken voor het opslaan van de vaakst gebruikte gegevens. De swap-ruimte kan een partitie van het type 'Linux swap' zijn op een schijf of een standaard wisselgeheugenbestand op een bestaande partitie. Er is ook zo iets als 'swap in zram': in dit geval worden de gegevens opgeslagen in RAM maar in gecomprimeerde vorm.

[[terminal]]Terminal::
Historisch was een terminal een fysiek apparaat bestaande uit een toetsenbord en een beeldscherm dat gebruikt werd om commando's te typen en uitvoer te lezen van een externe computer.
+
Tegenwoordig kunnen de opdrachten zowel in console (of tekst) modus als in grafische modus worden getypt.

[[utility]]Hulpprogramma of tool::
Een hulpprogramma of tool is een programma dat met zijn naam kan worden aangeroepen vanuit een shell (dit geldt ook voor sommige <application,applications>>).
+
Hulpprogramma's maken deel uit van het besturingssysteem (maar niet van de kernel). Ze voeren systeemgerelateerde functies uit, zoals het weergeven van directory-inhoud en bestandssystemen, het repareren van bestandssystemen of het vergaren van informatie over de systeemstatus.
+
Een hulpprogramma kan worden opgeroepen als een afzonderlijk programma dat wordt uitgevoerd in een ander proces dan de command language interpreter, of het kan worden geïmplementeerd als een onderdeel van de command language interpreter.
+
De echo opdracht (de instructie om een bepaalde taak uit te voeren) bijvoorbeeld kan zodanig worden geïmplementeerd dat deze opdracht (de code waarmee de taak van het echo-en wordt uitgevoerd) in een apart programma staat en daarom wordt uitgevoerd in ander proces dan de command language interpreter. In de praktijk betekent dit dat in dit geval het hulpprogramma niet in de shell wordt uitgevoerd
+
Omgekeerd kan de code waarmee het echo-programma wordt uitgevoerd, worden ingebouwd in de command language interpreter. Het wordt dan uitgevoerd in hetzelfde proces als de command language interpreter. Van een dergelijk hulpprogramma wordt gezegd dat het in de shell is ingebouwd ("built-in").

[[virtual_terminal]]Virtuele terminal::
Een virtuele terminal is software die een fysieke terminal bestaande uit een toetsenbord en een beeldscherm simuleert om met een computer op afstand te communiceren.
