:toc: left
:toclevels: 1
:toc-title: 

// Overview
[[Overview_of_Slint_Installation]]
== Resumo do processo de instalação

O instalador analisa primeiro as unidades e partições existentes para avaliar as possibilidades e opções de instalação e deixa-lhe escolher entre uma preparação automática ou manual das partições utilizadas pelo Slint.

Se escolher 'manual' são-lhe apresentadas as partições Linux onde o Slint poderia ser instalado (tamanho mínimo 50G), selecione uma delas e escolha o tipo de sistema de ficheiros que o instalador irá criar no mesmo: btrfs, ext4 ou xfs como mencionado em <<prepare_partitions_for_Slint,Opcionalmente prepare partições para o Slint>>

Se escolher 'auto' são-lhe apresentadas as unidades onde o Slint poderia ser instalado (com o tamanho de pelo menos 50G), e o sistema de ficheiros será do tipo btrfs.

Em caso de btrfs; sub-volumes serão criados para / /home e /snapshots com ficheiros comprimidos, e /swap para hospedar um ficheiro swap. 'Copy on write' facilitará a realização de 'snapshots' e possivelmente reverterá uma atualização defeituosa do sistema. Ferramentas para gerir os 'snapshots' estão incluídas no Slint.

Em ambos os modos, o utilizador escolhe quais as partições Linux e Windows existentes que serão automaticamente montadas após o arranque do Slint, e os seus nomes dos pontos de montagem, facilitando o acesso aos sistemas de saída e aos dados do Slint.

Depois é proposto ao utilizador encriptar a partição root do sistema, para evitar o roubo de dados em caso de perda ou roubo da máquina, ou da unidade onde Slint está instalado. Se aceite, o instalador regista a palavra-passe que permite desbloquear esta partição. O utilizador irá ao introduzi-la no momento do arranque quando solicitado pelo GRUB para exibir o menu de arranque.

Depois de tudo, o instalador resume as suas escolhas e deixa-lhe confirmá-las ou não. Até este ponto, nenhuma modificação terá sido feita aos sistemas e dados instalados que possa negar em segurança, depois escreva start novamente ou apenas reinicie sem qualquer dano.

Depois o particionamento auto é feito caso ocorra, a partição root do Slint é encriptada se solicitada, a partição root é formatada e os primeiros pacotes de software são instalados.

Se optou por um disco encriptado, escreva a palavra-passe que será usada para desbloquear a unidade em cada arranque.

Escolhe uma palavra-passe para o utilizador "root". Este é o administrador do sistema, que tem todos os privilégios.

Também se define o nome de acesso e palavra-passe de um utilizador padrão.

Indica se necessitará de uma saída em Braile acessível, e se deseja entrar no modo texto ou gráfico. Se utilizou o idioma Inglês (EUA) durante a instalação, escolha o idioma a utilizar no sistema instalado, caso contrário o instalador define o mesmo que durante a instalação.

O instalador tenta estabelecer uma ligação à Internet, e se tiver sucesso, propõe um fuso horário correspondente à sua localização geográfica que confirma, caso contrário selecione uma numa lista.

É-lhe perguntado se vai precisar de Braille, depois se prefere começar numa consola ou num gráfico, a menos que tenha usado a voz durante a instalação ou precise de Braille: de seguida será deixado numa consola após reiniciar, por segurança.

O instalador cria então um ficheiro swap. Isto pode demorar muito tempo. Seja paciente.

Os pacotes são instalados na unidade. Se tiver sido estabelecida uma ligação à Internet, descarrega e instala a versão mais recente de cada pacote, incluindo os fornecidos desde o lançamento da imagem ISO.

A instalação de todos os pacotes leva cerca de 10 a 40 minutos, dependendo do equipamento.

Ser-lhe-á pedido que selecione um ambiente de trabalho (mesmo que comece numa consola no início) entre fvm, lxqt, mate e wmaker. Outras escolhas estarão disponíveis após a instalação, escrevendo 'xwmconfig', se iniciar numa consola

Em seguida, o sistema é configurado e o gestor de arranque GRUB instalado. O Slint pode arrancar nos modos Legacy e EFI. O menu de arranque incluirá uma entrada de arranque "rescue" para detetar e permitir que qualquer SO instalado seja iniciado.

Pode obter uma pré-visualização do menu de arranque antes de reiniciar.

Depois, remova o meio de instalação e reinicie para iniciar o seu novo sistema Slint.
// Usage_installer
[[Usage_of_the_installer]]
== Utilização do instalador

Se está à vontade na linha de comandos, pode ignorar este tópico.

O menu principal da instalação é apresentado abaixo:
....
Bem-vindo ao instalador Slint! (versão 15)

Pode agora introduzir (sem os apóstrofos):

'doc' para conhecer as funcionalidades e utilização do instalador.
'start' para iniciar a instalação.

O instalador pode preparar a unidade onde o Slint será instalado criando,
as partições necessárias. Se preferir, pode fazê-lo sozinho/a usando
utilitários de linha de comandos disponíveis no instalador, e depois
escreva 'start' quando concluído. Também pode deixar o instalador e usar uma
ferramenta como o gparted para o fazer, depois inicie o instalador novamente.

Recomendamos que escreva 'doc' primeiro neste caso, ou se quiser
encriptar a partição root do Slint.
Quando terminar de ler, este menu será novamente exibido.
....

Assim que este menu for apresentado, fica responsável do processo de instalação.

Leia o ecrã e escreva comandos num <<virtual_terminal,terminal virtual>>. O instalador inclui 4 terminais virtuais que partilham o mesmo teclado físico e ecrã, que podem ser usados em paralelo.

O instalador começa no terminal virtual 1 chamado *tty1* mas pode trocar para outro. Por exemplo, pode mudar para *tty2* ao premir *Alt-F2,* depois prima Enter para ativá-lo e depois voltar para *tty1* ao premir *Alt-F1,* sem apagar informações apresentadas em ambos os terminais. *Alt-F1* significa: pressione e mantenha a tecla *Alt* e depois prima a tecla *F1*.

Isso pode ser útil para continuar a ler a documentação durante a instalação: por exemplo, pode trocar para *tty2* para iniciar a instalação, trocar para *tty1* para continuar a ler a documentação, depois troque novamente para *tty1* para prosseguir para a próxima etapa de instalação.

Isso também pode ser usado para consultar o glossário ao ler outros documentos.

O instalador tem vários modos de interação consigo, o utilizador:

* Ecreva comandos no "prompt" e leia o resultado.
* O instalador faz uma pergunta, escreva a resposta e a confirme premindo Enter.
* O instalador mostra um menu de escolhas ou opções: selecione uma delas usando as setas para cima ou para baixo, depois confirme sua escolha premindo Enter, ou cancele premindo Esc.
* O instalador apresenta informações num paginador. Depois, utilize teclas de setas para ler a linha seguinte ou anterior, prima espaço para visualizar a página seguinte, Q para parar de ler o documento.

// Prepare
[[prepare_partitions_for_Slint]]
== Opcionalmente, prepare as partições para o Slint

Neste documento 'formatar' uma partição significa: criar nela um sistema de ficheiros para gerir os ficheiros que irá conter.

Se depois de ter introduzido 'start' escreva 'm' para particionamento manual, primeiro selecionará a partição root do sistema, que será montada como "/", depois o tipo do seu sistema de ficheiros entre: btrfs, ext4, xfs.

O instalador lista para seleção apenas partições de tamanho mínimo de 50G e de Linux (também pode ser nomeado sistema de ficheiros Linux), não encriptados. Esta partição pode ser formatada ou não, mas em qualquer caso o seu conteúdo será eliminado e um novo sistema de ficheiros gerado pelo instalador.

Além disso, o modo de particionamento Manual requer na mesma unidade que a partição root do sistema:

* Uma partição do tipo BIOS boot, com tamanho mínimo de 3M e não formatada.
* Uma partição do tipo sistema EFI, com pelo menos 32M de espaço livre, formatada com um sistema de ficheiro 'fat' (ou 'vfat'), conforme requerido pela especificação UEFI

Usado para partições existentes do Slint ou criá-las é da responsabilidade do utilizador. Os sistemas já instalados que utilizam o BIOS boot e as partições EFI não serão afetadas, apenas a partição root será (re)formatada.

O instalador inclui várias aplicações de partição: cfdisk, fdisk, sfdisk, cgdisk, gdisk, sgdisk, parted. As aplicações com "g" no seu nome só podem lidar com gpt, parted pode lidar com tabelas de partição DOS assim como GPT. fdisk, cfdisk e sfdisk podem lidar com tabelas de partição DOS. Além disso, estão disponíveis wipefs (para apagar as assinaturas anteriores da tabela de partições e do sistema de ficheiros) e partprobe (para informar o kernel das alterações de uma tabela de partições). As aplicações blkid e lsblk exibem informação sobre dispositivos e partições de blocos.

Claro que também pode criar as partições a partir de outro sistema antes de iniciar o instalador.
// Installation
// Encryption
[[Encryption]]
== Slint com uma partição root encriptada.

No modo Auto, o instalador propõe encriptar a partição root do sistema. Se estiver de acordo, em cada arranque o carregador de arranque GRUB irá perguntar-lhe a palavra-passe que terá introduzido durante a instalação para desbloquear a unidade, antes de mostrar o menu de arranque. Tenha em atenção que o desbloqueio da unidade demorará alguns segundos (cerca de dez segundos).

Ter um sistema root encriptado impede o roubo de dados que contém em caso de perda ou roubo da máquina, ou de uma unidade removível. Mas isto não o protegerá se o computador continuar a funcionar e sem vigilância, apenas se a máquina tiver sido completamente desligada!

Durante a instalação, a partição do sistema Slint será encriptada e também a partição adicional que poderá solicitar.

Uma partição Slint (ou root) será nomeada: /dev/mapper/cryproot uma vez aberta, se ela tiver sido encriptada.

Isso é mostrado por este comando:

----
lsblk -lpo name,fstype,mountpoint | grep /$
----

Que dá um resultado como:
----
/dev/mapper/cryptroot ext4    /
----

Em vez disso, este comando:

----
lsblk -lpo name,fstype,mountpoint | grep /dev/sda3
----

dá:

----
/dev/sda3             cryptoLUKS
----

/dev/sda3 é agora uma partição "raw" que inclui o chamado "LUKS header" que nunca precisará nem nunca deverá aceder diretamente. Aloja tudo que é necessário para encriptar ou desencriptar a partição /dev/mapper/cryptroot, que na verdade aloja os seus dados (neste exemplo, o sistema Slint).

[WARNING]
====
Se se esquecer da palavra-passe, todos os dados na unidade serão irreversivelmente perdidos! Por isso, anote ou grave esta palavra-passe e coloque o registo num lugar seguro, assim que terminar.

As unidades falham. Se isso acontecer e forem encriptados, os seus dados serão perdidos. Por isso, fazer cópias de segurança dos seus dados regularmente não é opcional.

Além disso, faça uma cópia de segurança do luks header da qual poderá restaurar no caso da partição luks se danificar por qualquer motivo. O comando pode ser como no nosso exemplo:
----
luksHeaderBackup /dev/sda3 --header-backup-file <file>
----
onde <file> é o nome do ficheiro da cópia de segurança, que guardará num local seguro.

Depois, precisaria de restaurar a cópia de segurança, escreva:
----
luksHeaderRestore /dev/sda3 --header-backup-file <file>
----

Não redimensione uma partição de uma unidade encriptada porque depois disso seria definitivamente bloqueada e todos os dados que contém serão perdidos! Se realmente precisa de mais espaço, precisará de fazer uma cópia de segurança de todos os ficheiros que deseja manter, por isso instale novamente e restaure os ficheiros da cópia de segurança.

Escolha uma palavra-passe forte, para que um ladrão demore demasiado tempo a descobrir para que valha a pena.

Nunca mexa com o chamado "LUKS header" localizado na partição raw (a terceira, como por ex. /dev/sda3 para a partição raw em cima da partição do sistema Slint). Na prática: não crie um sistema de ficheiros nesta partição, não o faça parte de uma matriz RAID e por norma, não grave: todos os dados seriam irreversivelmente perdidos!
====

Para evitar palavras-passe fracas o instalador requer que a palavra-passe inclua:

. Pelo menos 8 caracteres.
. Apenas letras minúsculas e maiúsculas não acentuadas, dígitos de 0 a 9, espaço e os seguintes caracteres de pontuação:
+
----
 ' ! " # $ % & ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~
----
+
Isso garante que até mesmo um novo teclado tenha todos os caracteres necessários para introduzir a palavra-passe.

. Pelo menos um dígito, uma letra minúscula, uma letra maiúscula e um carácter de pontuação.

O GRUB assume que o teclado "us" está em uso quando introduz a palavra-passe. Por esta razão, se durante a instalação usar um outro mapa de teclado, antes de perguntar a palavra-passe o instalador irá definir o mapa do teclado como "us" e depois de ter gravado ele restaura o usado anteriormente. Neste caso o instalador também introduzirá cada carácter digitado da palavra-passe, como pode ser diferente daquela apresentada na tecla.

A aplicação criptsetup é usada para encriptar a unidade. Para saber mais, escreva após a instalação: +
-----
man cryptsetup
-----
// Speakup
[[Speakup]]
== Combinação de teclas para o leitor de ecrã Speakup

Este capítulo destina-se a utilizadores que necessitam de um leitor de ecrã mas não conhecem o Speakup.

Mantenha o numlock desligado para usar o Speakup.

A tecla CapsLock é utilizada como uma tecla shift. Por exemplo, "CapsLock 4" significa: +
manter premida a tecla CapsLock como uma tecla shift e premir 4.

 Primeiras combinações de teclas a lembrar:
 PrintScreen         Alternar speakup on/off.
 CapsLock F1         Ajuda do Speakup (prima Espaço para sair da ajuda).

 Combinação de teclas para alterar definições:
 CapsLock 1/2        Diminuir/Aumentar o volume de som.
 CapsLock 5/6        Diminuir/Aumentar a frequência da voz.

 Combinação de teclas para rever o ecrã:
 CapsLock j/k/l      Dizer Anterior/Atual/Seguinte palavra.
 CapsLock k (twice)  Soletrar palavra atual.
 CapsLock u/i/o      Dizer Anterior/Atual/Seguinte linha.
 CapsLock y          Dizer do topo do ecrã para o cursor de leitura.
 CapsLock p          Dizer da leitura da linha do cursor ao fundo do ecrã.
// First_steps
[[first_steps_after_installation]]
== Primeiros passos após a instalação

Aqui estão as primeiras tarefas a serem executadas após a instalação

Neste documento, todo o texto depois de um carácter # são comentários dos comandos sugeridos, não a serem introduzidos.

=== Atualização inicial do software

Após a instalação, o sistema deve ser atualizado para obter a mais recentemente fornecida versão de cada software, assim como o novo software fornecido desde a versão da ISO. Isto é especialmente necessário se nenhuma ligação de rede estiver disponível durante a instalação, como então apenas os pacotes incluídos no suporte da distribuição foram instalados, e eles podem estar desatualizados.

A maioria dos comandos introduzidos abaixo solicita um direito administrativo associado a uma conta específica chamada 'root', para o qual gravou uma palavra-passe durante a instalação.

Para emitir um comando como 'root', primeiro escreva
----
su -
----
de seguida, emita a palavra-passe para o root e prima Enter antes de escrever o comando.

Quando terminar de emitir comandos como 'root', pressione Ctrl+d ou escreva 'exit' para obter de volta o estado de "utilizador".

Em alternativa, o utilizador registado durante a instalação e outros membros do grupo 'wheel' podem escrever:
----
sudo <command>
----
depois também a palavra-passe para o root.

Para atualizar, escreva como root numa consola ou terminal gráfico:
----
slapt-get --add-keys # recupera as chaves para autenticar os pacotes
slapt-get -u # atualiza a lista de pacotes nos "mirrors"
slapt-get --install-set slint # obtêm os novos pacotes
slapt-get --upgrade # obtêm as novas versões dos pacotes instalados
dotnew # mostra as alterações nos ficheiros de configuração
----
Quando estiver a executar o dotnew, aceite substituir todos os ficheiros de configuração antigos pelos novos. Isto é seguro, pois ainda não fez nenhuma personalização.

Em alternativa, pode usar estes front-ends gráficos: gslapt em vez do slapt-get, e dotnew-gtk em vez do dotnew.

Para saber mais sobre o slapt-get, escreva:
----
man slapt-get
----
ou como root:
----
slapt-get --help
----
e leia o /usr/doc/slapt-get*/README.slaptgetrc.Slint

// Glossary
== Glossário

Várias definições neste glossário são tiradas ou adaptadas da https://en.wikipedia.org/wiki/Main_Page[Wikipédia] e https://pubs.opengroup.org/onlinepubs/9699919799/[POSIX]

[[application]]Aplicação:: Um programa de aplicação (aplicação por abreviatura) é um programa de computador projetado para realizar uma tarefa específica normalmente solicitada por utilizadores.
+
As aplicações não são geralmente consideradas como parte do sistema operativo, o que significa que elas podem ser adicionadas ao sistema após a sua instalação. Elas executam funções não relacionadas com o sistema, tais como processamento de texto, desenho de arquitetura, desenho mecânico, publicações, ou análise financeira.


[[boot]]Arranque::
Arranque significa ligar um computador para iniciar um sistema operativo. Vários sistemas operativos podem ser instalados no mesmo computador. Selecione qual para carregar na RAM e executar pode ser feito pelo firmware ou por um software chamado gestor de arranque (GRUB no caso do Slint). O firmware de um computador pode suportar um dos seguintes modos de arranque, ou ambos:
+
* No modo Legacy ou BIOS, o sistema operativo é carregado executando as instruções gravadas num sector de arranque(boot).
* No modo EFI, o carregador do sistema operativo é um programa armazenado num ficheiro executável, localizado num diretório de uma partição do sistema EFI (ESP).

[[CPU]]CPU::
A Unidade de Processamento Central ou CPU executa as instruções dos programas.

[[command]]Comando:: O comando é definido por https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_104[POSIX] como "uma diretiva para uma <<shell,shell>> para executar uma tarefa específica".
+
A tarefa a ser executada pode ser uma <<application,aplicação>> ou um <<utility,utilitário>>.
+
A estrutura básica dos comandos da shell é definida no capítulo https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09[2.9 Shell Commands] da especificação POSIX.
+
Exemplos de comandos são fornecidos em <<bash shell>>.

[[console]]Consola:: A palavra "consola" refere-se ao início dos sistemas de computador, quando o administrador de sistema escreveu comandos num dispositivo, incluindo um teclado e uma impressora, ligados ao computador, aos comandos introduzidos e resultado do computador sendo impresso na consola, fornecendo um registo de ambos.
+
Em computadores pessoais, o utilizador escreve os comandos no teclado e o seu resultado é impresso num ecrã, que podem ser separados ou integrados no computador como num portátil.

[[device]]Dispositivo::

Um periférico do computador ou um objeto que aparece na aplicação como tal.[POSIX]

[[directory]]Diretório::
Um diretório é outro nome para uma pasta. Sistemas de ficheiros usam diretórios para organizar ficheiros dentro de partições.
+
Os diretórios podem conter ficheiros e também outros diretórios. A estrutura resultante pode ser representada como uma árvore invertida. O diretório de nível superior de uma unidade é nomeado como diretório root. No Linux, o carácter / separa os níveis da árvore. A / sozinha representa o diretório root, /home hospeda os ficheiros pertencentes a utilizadores, /home/hugo hospeda os ficheiros que pertencem ao diretório do utilizador hugo. /root hospeda os ficheiros root nomeados pelo utilizador (o administrador do sistema). Nota: 'root' pode se referir ao diretório de nível superior ou ao administrador do sistema.

[[drive]]Unidade::
Uma unidade é um dispositivo que armazena dados não voláteis, o que significa que os dados não são apagados quando a energia é desligada. Exemplos: discos rígidos, SSD, dispositivos USB, leitores de cartões, eMMC.
+
O meio de armazenamento dos dados pode ser permanentemente ligado à unidade ou removível como cartões SD, dispositivos USB e discos ligados através de USB.
+
Um sistema operativo instalado num suporte removível ou numa unidade externa é dito portátil: o mesmo pode ser movido de um computador para outro.

[[display_manager]]Gestor de ecrã::
Um gestor de ecrã (ou gestor de acesso) é um software que mostra uma janela no qual pede o nome de acesso e a palavra-passe do utilizador, depois inicia o ambiente gráfico escolhido pelo referido utilizador.

[[encryption]]Encriptação::
A encriptação é o processo de conversão de dados numa forma não reconhecida ("encriptado"). É normalmente usado para proteger informações confidenciais para que apenas pessoas autorizadas possam visualizá-las. Um único ficheiro ou diretório, uma partição também como uma unidade inteira pode ser encriptada, que o tornam acessível apenas após ter escrito um pequeno texto chamado de palavra-passe, mantido em segredo.

[[file]]Ficheiro::
Um ficheiro de computador é um conjunto de dados digitais reunidos com o mesmo nome, gravados num meio de armazenamento permanente, chamado de armazenamento em massa, como um disco rígido, um SSD, um DVD, um cartão SD ou uma pen USB e tratado como uma unidade.
+
Os ficheiros podem conter dados como textos, imagens, sons, vídeos ou programas de computador.

[[file_system]]Sistema de ficheiros::
Um sistema de ficheiros é um software que gere os ficheiros e diretórios de uma partição. Memoriza o local no suporte físico dos dados contidos nos ficheiros, permitindo lê-los ou grava-los. Exemplos de sistemas de ficheiros usados são vfat, ntfs, ext4, f2fs. Este comando lista todos os sistemas de ficheiros que permitem ler os dados contidos numa partição do Linux:
+
----
cat /proc/filesystems|grep -v nodev
----

[[firmware]]Firmware::
Um firmware é um software que inicializa e verifica o hardware, depois ou é selecionado e carregado na RAM do sistema operativo, ou inicia um software chamado gestor de arranque que fará isso. O firmware é mantido em memórias não-voláteis dispositivos como ROM, EPROM ou flash memória. É o primeiro software executado ao arrancar um computador. Fornece um menu permitindo configurar o hardware e selecionar em que modo (Legacy ou EFI) arranca e em que ordem procura o sistema operativo ou outra aplicação (como o Gestor de arranque GRUB) a executar.

[[kernel]]Kernel::
Um kernel Linux é o software no núcleo de um sistema Slint que lida com as interações entre as aplicações e o hardware.
+
Apresenta-se como um único ficheiro, instalado no diretório /boot. Por exemplo, o ficheiro /boot/vmlinuz-generic-5.12.11 é um kernel, vindo de um pacote genérico.
+
No arranque o kernel é copiado para a RAM.

[[initrd]]Initrd::
Um initrd (mais precisamente uma initramfs ou sistema e ficheiros inicial RAM para o Slint) é um sistema Linux fornecido como um ficheiro comprimido. No arranque, logo após o kernel ser carregado na RAM, o inird também é carregado na RAM. O seu ficheiro /init executa: carrega os módulos kernel necessários na RAM, regista os dispositivos, possivelmente desbloqueia o dispositivo root, monta o pseudo sistema de ficheiros e depois muda para o sistema de ficheiros root para iniciar o sistema de verdade.
+
Um initrd apresenta-se como um único ficheiro, instalado no diretório boot. Por exemplo, o ficheiro initrd-generic-5.12.11 é um initrd

[[live_system]]Sistema "live"::
Um sistema 'live' é um sistema operativo que, ao invés de ser instalado num dispositivo como um disco rígido ou SSD, encontra-se inteiramente na <<RAM>>.
+
Um initrd é também um sistema "live", assim como um instalador do Slint que é basicamente um initrd.

[[partition]]Partição::
Uma partição é uma secção de um meio de armazenamento, como um disco rígido ou SSD. É tratada pelo sistema operativo como um volume lógico separado, o que o faz funcionar de forma semelhante a um suporte separado.

[[partition_table]]Tabela de partições::
Uma tabela de partições é a estrutura permanente que regista como as informações são posicionadas num suporte, principalmente gravar o início e o fim de cada partição no suporte.
+
Os tipos mais comuns de tabelas de partições são a tabela de partições DOS, inicialmente usada pelo sistema operativo MS-DOS, e a tabela de partições do GUID ou GPT, que permite lidar com mais partições e unidades maiores.

[[program]]Programa::
Uma sequência de instruções preparada para o sistema realizar uma tarefa definida. O termo "programa" engloba aplicações escritas na Linguagem de Comando Shell, linguagens de entrada de utilidade complexa (por exemplo, awk, lex, e assim por diante) e linguagens de alto nível. [POSIX]

[[RAM]]RAM::
RAM significa Memória de Acesso Aleatório. Este tipo de dispositivo armazena dados voláteis, o que significa que os dados são apagados quando a energia é desligada.

[[shell]]Shell:: Um programa que interpreta sequências de entrada de texto como comandos. Pode operar num fluxo de entrada ou pode alertar e ler comandos de um terminal de forma interativa. A sintaxe dos comandos que podem ser interpretados pela shell pode variar dependendo da shell em uso, mas são principalmente definidos no capítulo https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html[2. Shell Command Language] da especificação POSIX.
+
O Slint vem com vários programas atuando como shell, listados no ficheiro /etc/shells. A shell *bash* é usada por padrão.

[[swap]]Swap::
Um espaço swap é utilizado para armazenar dados previamente na RAM num dispositivo como um disco rígido ou SSD, quer porque caso contrário a RAM ficaria cheia, quer para espaço livre na RAM para armazenar ali os dados mais frequentemente utilizados. O espaço swap pode ser uma partição numa unidade do tipo 'Linux swap' ou um ficheiro comum armazenado numa partição existente. Há também a 'swap in zram': neste caso, os dados são armazenados na RAM, mas em formato comprimido.

[[terminal]]Terminal::
Historicamente, um terminal é um dispositivo físico composto por um teclado e um ecrã usado para escrever comandos e receber respostas de um computador remoto.
+
Hoje em dia os comandos podem ser introduzidos no modo consola (ou texto) ou no modo gráfico.

[[utility]]Utilitário::
Um utilitário é um programa que pode ser chamado pelo nome de uma shell (este também é o caso de algumas <<application,aplicações>>).
+
Os utilitários são parte do sistema operativo (mas não do kernel).Executam funções relacionadas com o sistema, como listar conteúdo de diretórios, verificação do sistema de ficheiros, reparação do sistemas de ficheiros ou extração de informações do estado do sistema.
+
Um utilitário pode ser invocado como um programa separado que executa num programa diferente do que o intérprete de linguagem de comando, ou pode ser implementado como uma parte do intérprete de linguagem de comando.
+
Por exemplo, o comando echo (a diretiva para executar uma tarefa específica) pode ser implementado de tal forma que o utilitário echo (a lógica que executa a tarefa de echoing) esteja num programa separado; portanto, é executado num processo diferente do interpretador de linguagem de comando. Praticamente isto significa que neste caso o utilitário é um programa distinto da shell
+
Por outro lado, a lógica que executa o utilitário echo poderia ser embutida no interpretador de linguagem de comando; portanto, poderia executar no mesmo processo que o interpretador de linguagem de comandos. Diz-se que tal utilitário é "embutido" na shell.

[[virtual_terminal]]Terminal virtual::
Um terminal virtual é um software que simula um terminal físico, dispositivo composto por um teclado e um ecrã que permite comunicar remotamente com um computador.
