#!/bin/sh
export TEXTDOMAIN=slint-scripts
if [ ! "$(id -u)" -eq 0 ]; then
	gettext "Please run this command as root."; echo
	exit
fi
if [ ! -f /boot/grub/grub.cfg ]; then
	gettext "The file /boot/grub/grub.cfg does not exist."; echo
	gettext "Prior to runninng this command you should install grub and run either:"; echo
	echo "update-grub"
	gettext "or if this command does not exist:"; echo
	echo "grub-mkconfig -o /boot/grub/grub.cfg"
fi
sed -n "/^[[:space:]]*\menuentry /s%[^']*'\([^']*\)'.*%\1%p" /boot/grub/grub.cfg > /tmp/list_boot_entries 
for i in $(find /boot/grub/* -prune -name "*.cfg"|grep -v grub.cfg); do
	sed -n "/^[[:space:]]*\menuentry /s%[^']*'\([^']*\)'.*%\1%p" "$i" >> /tmp/list_boot_entries
done
{
echo
gettext "After booting, the boot menu will be displayed as above."
echo
echo
gettext "To navigate in the menu you will use the down and up arrow keys, then
press Enter to use the selected boot entry."
echo
gettext "To boot directly the most recent snapshot (if any), just press 1."
echo
echo
gettext "Press q quit this display."
echo
} >> /tmp/list_boot_entries
w3m -o confirm_qq=false /tmp/list_boot_entries
rm /tmp/list_boot_entries
