:toc: left
:toclevels: 1
:toc-title: 

// Overview
[[Overview_of_Slint_Installation]]
== Επισκόπηση της διαδικασίας εγκατάστασης

Το πρόγραμμα εγκατάστασης ελέγχει πρώτα τις υπάρχουσες μονάδες και διαμερίσματα για να αξιολογήσει τις δυνατότητες και τις επιλογές εγκατάστασης και να σας επιτρέψει να επιλέξετε μεταξύ μιας αυτόματης ή μη αυτόματης προετοιμασίας των διαμερισμάτων που χρησιμοποιούνται από το Slint.

Αν επιλέξετε το 'εγχειρίδιο' παρουσιάζονται τα διαμερίσματα Linux όπου μπορεί να εγκατασταθεί το Slint (μέγεθος τουλάχιστον 50G), επιλέξτε ένα από αυτά και επιλέξτε το είδος του συστήματος αρχείων που θα δημιουργήσει το πρόγραμμα εγκατάστασης σε αυτό: btrfs, ext4 ή xfs όπως αναφέρεται στο <<prepare_partitions_for_Slint,Optionally prepare partitions for Slint>>

Αν επιλέξετε 'auto' παρουσιάζονται οι μονάδες όπου θα μπορούσε να εγκατασταθεί το Slint (μέγεθος τουλάχιστον 50G), και το σύστημα αρχείων θα είναι τύπου btrfs.

Σε περίπτωση btrfs; υποτόμοι θα δημιουργηθούν για το / /home και /snapshots με συμπιεσμένα αρχεία, και /swap για να φιλοξενήσει ένα αρχείο swap. 'Αντιγραφή κατά την εγγραφή' θα διευκολύνει την πραγματοποίηση στιγμιότυπων και ενδεχομένως θα επανέλθει μια ελαττωματική ενημέρωση του συστήματος. Τα εργαλεία για τη διαχείριση των στιγμιότυπων περιλαμβάνονται στο Slint.

Και στις δύο λειτουργίες, ο χρήστης επιλέγει ποια υπάρχοντα διαμερίσματα Linux και Windows θα προσαρτηθούν αυτόματα μετά την εκκίνηση του Slint και τα ονόματα των σημείων προσάρτησής τους, διευκολύνοντας την πρόσβαση σε υπάρχοντα συστήματα και δεδομένα από το Slint.

Στη συνέχεια προτείνεται ο χρήστης να κρυπτογραφήσει το κύριο διαμέρισμα του συστήματος, για να αποτρέψει την κλοπή δεδομένων σε περίπτωση απώλειας ή κλοπής του μηχανήματος ή της μονάδας όπου είναι εγκατεστημένο το Slint. Αν γίνει αποδεκτό το πρόγραμμα εγκατάστασης καταγράφει τη φράση πρόσβασης που επιτρέπει το ξεκλείδωμα αυτού του διαμερίσματος. Ο χρήστης θα το πληκτρολογεί κατά την πληκτρολόγηση όταν ζητηθεί από τo GRUB για την εμφάνιση του μενού εκκίνησης.

Μετά από όλα αυτά ο εγκαταστάτης συνοψίζει τις επιλογές σας και σας επιτρέπει να τις επιβεβαιώσετε ή όχι. Μέχρι αυτό το σημείο δεν θα έχει γίνει καμία τροποποίηση στα εγκατεστημένα συστήματα και δεδομένα ώστε να μπορείτε να αρνηθείτε με ασφάλεια, στη συνέχεια πληκτρολογήστε να ξεκινήσετε ξανά ή απλά επανεκκινήστε χωρίς βλάβη.

Στη συνέχεια, η αυτόματη κατάτμηση γίνεται με περίπτωση, το διαμέρισμα Slint root κρυπτογραφείται αν ζητηθεί, το διαμέρισμα ρίζας είναι διαμορφωμένο και τα πρώτα πακέτα λογισμικού έχουν εγκατασταθεί.

Αν επιλέξατε έναν κρυπτογραφημένο δίσκο πληκτρολογείτε τη φράση πρόσβασης που θα χρησιμοποιηθεί για να ξεκλειδώσετε τη μονάδα δίσκου σε κάθε εκκίνηση επάνω.

Επιλέξτε έναν κωδικό πρόσβασης για το χρήστη "root". Αυτός είναι ο διαχειριστής συστήματος, ο οποίος έχει όλα τα δικαιώματα.

Μπορείτε επίσης να ορίσετε το όνομα σύνδεσης και τον κωδικό πρόσβασης ενός κανονικού χρήστη.

Δηλώνετε αν θα χρειαστείτε πρόσβαση στη γραφή Braille, και αν θέλετε να συνδεθείτε σε κείμενο ή σε κατάσταση γραφικών. Εάν χρησιμοποιήσατε την αγγλική γλώσσα (ΗΠΑ) κατά τη διάρκεια της εγκατάστασης, επιλέγετε τη γλώσσα που θα χρησιμοποιηθεί στο εγκατεστημένο σύστημα, διαφορετικά το πρόγραμμα εγκατάστασης ορίζει το ίδιο όπως κατά την εγκατάσταση.

Ο εγκαταστάτης προσπαθεί να δημιουργήσει μια σύνδεση στο Διαδίκτυο, και αν είναι επιτυχής προτείνει μια ζώνη ώρας που αντιστοιχεί στη γεωγραφική σας θέση που επιβεβαιώνετε, αλλιώς επιλέξτε ένα σε μια λίστα.

Θα σας ζητηθεί αν θα χρειαστείτε Braille, στη συνέχεια, αν προτιμάτε να ξεκινήσετε σε μια κονσόλα ή σε ένα γραφικό εκτός αν χρησιμοποιήσατε λόγο κατά την εγκατάσταση ή χρειάζεστε Braille: τότε θα προσγειωθεί σε μια κονσόλα μετά την επανεκκίνηση, για την ασφάλεια.

Ο εγκαταστάτης δημιουργεί ένα αρχείο swap. Αυτό μπορεί να διαρκέσει πολύ, παρακαλώ να είστε υπομονετικοί.

Τα πακέτα είναι εγκατεστημένα στη μονάδα. Αν έχει δημιουργηθεί σύνδεση στο Internet, μεταφορτώνει και εγκαθιστά την πιο πρόσφατη έκδοση κάθε πακέτου, συμπεριλαμβανομένων αυτών που παρέχονται από την έκδοση της εικόνας ISO.

Η εγκατάσταση όλων των πακέτων διαρκεί περίπου 10 έως 40 λεπτά ανάλογα με το υλικό.

Θα σας ζητηθεί να επιλέξετε μια επιφάνεια εργασίας (ακόμα και αν ξεκινήσετε σε μια κονσόλα πρώτα) μεταξύ fvm, lxqt, mate και wmaker. Άλλες επιλογές θα είναι διαθέσιμες μετά την πληκτρολόγηση της εγκατάστασης 'xwmconfig' αν ξεκινήσετε σε μια κονσόλα

Στη συνέχεια, το σύστημα έχει ρυθμιστεί και ο διαχειριστής εκκίνησης GRUB εγκατεστημένος. Το Slint μπορεί να εκκινήσει σε λειτουργίες Legacy και EFI. Το μενού εκκίνησης θα περιλαμβάνει μια καταχώρηση εκκίνησης "διάσωση" για να εντοπίσει και να επιτρέψει την εκκίνηση οποιουδήποτε εγκατεστημένου λειτουργικού συστήματος.

Μπορείτε να εμφανίσετε μια προεπισκόπηση του μενού εκκίνησης πριν την επανεκκίνηση.

Στη συνέχεια, αφαιρέστε τα μέσα εγκατάστασης και επανεκκινήστε το νέο σύστημα Slint.
// Usage_installer
[[Usage_of_the_installer]]
== Χρήση του εγκαταστάτη

Αν είστε εξοικειωμένοι με τη γραμμή εντολών, μπορείτε να παραλείψετε αυτό το θέμα.

Το κύριο μενού εγκατάστασης εμφανίζεται παρακάτω:
....
Καλώς ήλθατε στο πρόγραμμα εγκατάστασης του Slint! (έκδοση 15)

Μπορείτε τώρα να πληκτρολογήσετε (χωρίς τα εισαγωγικά):

'doc' για να γνωρίζετε τα χαρακτηριστικά και τη χρήση του εγκαταστάτη.
'start' για να ξεκινήσετε την εγκατάσταση.

Ο εγκαταστάτης μπορεί να προετοιμάσει τη μονάδα δίσκου όπου θα εγκατασταθεί το Slint,
δημιουργώντας τα απαραίτητα διαμερίσματα. Αν προτιμάτε να μπορείτε να το κάνετε μόνοι σας
χρησιμοποιώντας βοηθητικά προγράμματα γραμμής εντολών διαθέσιμα στο πρόγραμμα εγκατάστασης, στη συνέχεια, πληκτρολογήστε 'έναρξη'
όταν τελειώσετε. Μπορείτε επίσης να αφήσετε τον εγκαταστάτη και να χρησιμοποιήσετε ένα εργαλείο όπως το gparted
για να το κάνετε και στη συνέχεια να εκκινήσετε ξανά το πρόγραμμα εγκατάστασης.

Σας συνιστούμε να πληκτρολογήσετε πρώτα το 'doc' σε αυτή την περίπτωση ή αν θέλετε να
κρυπτογραφήσετε το ριζικό διαμέρισμα Slint.
Όταν ολοκληρώσετε την ανάγνωση αυτού του μενού θα εμφανιστεί ξανά.
....

Μόλις εμφανιστεί αυτό το μενού, έχετε το χέρι στη διαδικασία εγκατάστασης.

Μπορείτε να διαβάσετε την οθόνη και πληκτρολογήστε εντολές σε ένα <<virtual_terminal,virtual terminal>>. Ο εγκαταστάτης περιλαμβάνει 4 εικονικά τερματικά που μοιράζονται το ίδιο φυσικό πληκτρολόγιο και οθόνη, που μπορούν να χρησιμοποιηθούν παράλληλα.

Ο εγκαταστάτης ξεκινά στο εικονικό τερματικό 1 που ονομάζεται *tty1* αλλά μπορείτε να μεταβείτε σε άλλο. Για παράδειγμα, μπορείτε να αλλάξετε σε *tty2* πατώντας *Alt-F2* και έπειτα Enter για να το ενεργοποιήσετε και αργότερα να επιστρέψετε στο *tty1* πατώντας *Alt-F1*, χωρίς διαγραφή πληροφοριών που εμφανίζονται και στα δύο τερματικά. *Alt-F1* σημαίνει: πατήστε και κρατήστε πατημένο το πλήκτρο *Alt* και μετά πατήστε το πλήκτρο *F1*.

Αυτό μπορεί να είναι χρήσιμο για να συνεχίσετε να διαβάζετε την τεκμηρίωση κατά τη διάρκεια της εγκατάστασης: για παράδειγμα μπορείτε να μεταβείτε σε *tty2* για να ξεκινήσετε την εγκατάσταση, άλλαξε σε *tty1* σε συνεχίστε να διαβάζετε την τεκμηρίωση, στη συνέχεια αλλάξτε σε *tty1* ξανά για να προχωρήσετε στο το επόμενο βήμα εγκατάστασης.

Αυτό μπορεί επίσης να χρησιμοποιηθεί για να συμβουλευτείτε το γλωσσάριο κατά την ανάγνωση άλλων εγγράφων.

Ο εγκαταστάτης έχει διάφορους τρόπους αλληλεπίδρασης με εσάς, τον χρήστη:

* Πληκτρολογείτε εντολές στην προτροπή και διαβάστε την έξοδο.
* Ο εγκαταστάτης κάνει μια ερώτηση, πληκτρολογείτε την απάντηση και την επιβεβαιώνετε πατώντας Enter.
* Το πρόγραμμα εγκατάστασης εμφανίζει ένα μενού επιλογών ή επιλογών: επιλέγετε μία από αυτές χρησιμοποιώντας τα βελάκια πάνω και κάτω, στη συνέχεια, επιβεβαιώστε την επιλογή σας πατώντας Enter, ή ακυρώστε πατώντας Escape.
* Ο εγκαταστάτης εμφανίζει πληροφορίες σε μια σελίδα. Στη συνέχεια, χρησιμοποιήστε τα πλήκτρα βέλους για να διαβάσετε την επόμενη ή προηγούμενη γραμμή, πατήστε το πλήκτρο διαστήματος για να εμφανίσετε την επόμενη σελίδα, Q για να σταματήσετε την ανάγνωση του εγγράφου.

// Prepare
[[prepare_partitions_for_Slint]]
== Προαιρετικά, ετοιμάστε διαμερίσματα για το Slint

Σε αυτό το έγγραφο 'format' ένα διαμέρισμα σημαίνει: δημιουργήστε ένα σύστημα αρχείων σε αυτό για να διαχειριστείτε τα αρχεία που θα περιέχει.

Εάν αφού πληκτρολογήσετε 'start' πληκτρολογήσετε 'm' για χειροκίνητη κατάτμηση, θα επιλέξετε πρώτα το διαμέρισμα ριζικού συστήματος, το οποίο θα προσαρτηθεί ως "/", μετά τον τύπο του συστήματος αρχείων του μεταξύ: btrfs, ext4, xfs.

Το πρόγραμμα εγκατάστασης εμφανίζει μόνο διαμερίσματα μεγέθους τουλάχιστον 50G και Linux (μπορεί επίσης να ονομάζεται σύστημα αρχείων Linux), όχι κρυπτογραφημένο. Αυτό το διαμέρισμα μπορεί να διαμορφωθεί ή όχι, αλλά σε κάθε περίπτωση το περιεχόμενό του θα διαγραφεί και ένα νέο σύστημα αρχείων που θα δημιουργηθεί από το πρόγραμμα εγκατάστασης.

Επιπλέον, η χειροκίνητη λειτουργία διαχωρισμού απαιτεί την ίδια μανάδα δίσκου με το διαμέρισμα του ριζικού συστήματος:

* Ένα διαμέρισμα τύπου κατάτμησης εκκίνησης BIOS, μεγέθους τουλάχιστον 3M και μη μορφοποιημένο.
* Ένα διαμέρισμα συστήματος τύπου EFI, με τουλάχιστον 32M ελεύθερο χώρο σε αυτό, μορφοποιημένο με σύστημα αρχείων 'fat' (ή 'vfat') όπως απαιτείται από την προδιαγραφή UEFI

Χρησιμοποιώντας τις υπάρχουσες κατατμήσεις για το Slint ή η δημιουργία τους είναι στο χέρι του χρήστη. Τα ήδη εγκατεστημένα συστήματα που χρησιμοποιούν την εκκίνηση του BIOS και τα διαμερίσματα EFI δεν θα επηρεαστούν, μόνο το διαμέρισμα root θα (επανα)μορφοποιηθεί.

Το πρόγραμμα εγκατάστασης περιλαμβάνει διάφορες εφαρμογές διαμερισμού: cfdisk, fdisk, sfdisk, cgdisk, gdisk, sgdisk, parted. Οι εφαρμογές με "g" στο όνομά τους μπορούν να χειριστείτε μόνο gpt, το parted μπορεί να χειριστεί πίνακες χωρισμάτων DOS, καθώς και GPT. Τα fdisk, cfdisk και sfdisk μπορoύν να χειριστουν πίνακες χωρισμάτων DOS. Επιπλέον, είναι διαθέσιμες οι wipefs (για τη διαγραφή των προηγούμενων υπογραφών του πίνακα χωρισμάτων και των υπογραφών του συστήματος αρχείων) και το patprobe (για την ενημέρωση του πυρήνα για τις αλλαγές ενός πίνακα χωρισμάτων). Οι εφαρμογές blkid και lsblk εμφανίζουν πληροφορίες σχετικά με συσκευές μπλοκ και χωρίσματα.

Φυσικά, μπορείτε επίσης να δημιουργήσετε τα διαμερίσματα από ένα άλλο σύστημα πριν από την έναρξη του εγκαταστάτη.
// Installation
// Encryption
[[Encryption]]
== Το Slint με ένα κρυπτογραφημένο ριζικό διαμέρισμα.

Σε λειτουργία Auto, το πρόγραμμα εγκατάστασης προτείνει την κρυπτογράφηση του κεντρικού διαμερίσματος του συστήματος. Εάν συμφωνείτε, σε κάθε εκκίνηση ο φορτωτής εκκίνησης GRUB θα σας ρωτήσει τη φράση πρόσβασης που θα έχετε πληκτρολογήσει κατά τη διάρκεια της εγκατάστασης για να ξεκλειδώσετε τη μονάδα, πριν εμφανιστεί το μενού εκκίνησης. Έχετε υπόψη ότι το ξεκλείδωμα της μονάδας θα διαρκέσει μερικά δευτερόλεπτα (περίπου δέκα δευτερόλεπτα).

Έχοντας ένα κρυπτογραφημένο ριζικό σύστημα αποτρέπει την κλοπή δεδομένων που περιέχει σε περίπτωση απώλειας ή κλοπής του μηχανήματος, ή μιας αφαιρούμενης κίνησης. Αλλά αυτό δεν θα σας προστατεύσει αν ο υπολογιστής παραμείνει σε λειτουργία και χωρίς παρακολούθηση, μόνο αν το μηχάνημα έχει απενεργοποιηθεί εντελώς!

Κατά την εγκατάσταση, η κατάτμηση του συστήματος Slint θα κρυπτογραφηθεί και επίσης η πρόσθετη κατάτμηση που μπορείτε να ζητήσετε.

Ένα διαμέρισμα συστήματος (ή root) θα ονομαστεί ως εξής: /dev/mapper/cryproot μία φορά το άνοιξε, αν έχει κρυπτογραφηθεί.

Αυτό φαίνεται από αυτήν την εντολή:

----
lsblk -lpo όνομα,fstype,σημείο ανάρτησης - grep /$
----

Ποια δίνει ένα ouptut όπως:
----
/dev/mapper/cryptroot ext4 /
----

Αυτή η εντολή:

----
lsblk -lpo όνομα,fstype,mountpoint ±grep /dev/sda3
----

δόσεις:

----
/dev/sda3             cryptoLUKS
----

/dev/sda3 είναι τώρα ένα "raw" διαμέρισμα που περιλαμβάνει την λεγόμενη "κεφαλίδα LUKS" που δεν θα χρειαστείτε ποτέ ούτε θα πρέπει ποτέ να έχετε άμεση πρόσβαση. Φιλοξενεί όλα όσα απαιτούνται για την κρυπτογράφηση ή αποκρυπτογράφηση του διαμερίσματος /dev/mapper/cryptroot, που φιλοξενεί πραγματικά τα δεδομένα σας (σε αυτό το παράδειγμα το σύστημα Slint).

[WARNING]
====
Εάν ξεχάσετε τη συνθηματική φράση όλα τα δεδομένα στη μονάδα δίσκου θα χαθούν ανεπανόρθωτα! Έτσι γράψτε ή καταγράψτε αυτό το συνθηματικό και βάλτε το ρεκόρ σε ασφαλές μέρος όσο μόλις γίνεται.

Δίσκοι πεθαίνουν. Αν συμβεί αυτό και είναι κρυπτογραφημένο τα δεδομένα σας θα χαθούν. Έτσι, τακτικά αντίγραφα ασφαλείας σημαντικά δεδομένα σας δεν είναι προαιρετικό.

Επίσης, κάντε ένα αντίγραφο ασφαλείας της κεφαλίδας luks που θα είστε σε θέση να επαναφέρετε το διαμέρισμα luks να καταστραφεί για οποιοδήποτε λόγο. Η εντολή θα μπορούσε να είναι στο παράδειγμα μας :
----
luksHeaderBackup /dev/sda3 --header-backup-file <file>
----
όπου <file> είναι το όνομα του αρχείου αντιγράφων ασφαλείας, που θα αποθηκεύσετε σε ασφαλές μέρος.

Τότε θα πρέπει να επαναφέρετε το αντίγραφο ασφαλείας, πληκτρολογήστε:
----
luksHeaderRestore /dev/sda3 --header-backup-file <file>
----

Don't να αλλάξετε το μέγεθος ενός διαμερίσματος κρυπτογραφημένης μονάδας δίσκου όπως μετά από αυτό θα ήταν οριστικά κλειδωμένο και όλα τα δεδομένα που περιέχει θα χαθούν! Αν χρειάζεστε πραγματικά περισσότερο χώρο, θα πρέπει να δημιουργήσετε αντίγραφα ασφαλείας όλων των αρχείων που θέλετε να κρατήσετε, στη συνέχεια εγκαταστήστε εκ νέου και να επαναφέρετε τα αντίγραφα ασφαλείας.

Επιλέξτε μια ισχυρή φράση πρόσβασης, έτσι ώστε θα πάρει πάρα πολύ χρόνο για έναν ληστή να ανακαλύψετε για να αξίζει τον κόπο.

Ποτέ ποτέ βιολί με τη λεγόμενη "κεφαλίδα LUKS" που βρίσκεται στην πρώτη κατάτμηση (η τρίτη, όπως π.χ. /dev/sda3 για την πρώτη κατάτμηση πάνω από το διαμέρισμα του συστήματος Slint). Πρακτικά: μην δημιουργήσετε ένα σύστημα αρχείων σε αυτό το χώρισμα, μην το κάνετε μέρος ενός RAID πίνακα και γενικά δεν γράφουν σε αυτό: όλα τα δεδομένα θα χαθούν ανεπανόρθωτα!
====

Για να αποφύγετε τις αδύναμες φράσεις πρόσβασης, ο εγκαταστάτης απαιτεί η φράση πρόσβασης να περιλαμβάνει:

. Τουλάχιστον 8 χαρακτήρες.
. Μόνο μη τονισμένα πεζά και κεφαλαία γράμματα, ψηφία από 0 έως 9, κενό και τους ακόλουθους χαρακτήρες στίξης:
+
----
 ' ! " # $ % & ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~
----
+
Αυτό εγγυάται ότι ακόμη και ένα νέο πληκτρολόγιο θα έχει όλους τους χαρακτήρες που απαιτούνται για να πληκτρολογήστε τη φράση πρόσβασης.

. Τουλάχιστον ένα ψηφίο, ένα πεζό γράμμα, ένα κεφαλαίο γράμμα και ένα χαρακτήρα στίξης.

Το GRUB υποθέτει ότι το πληκτρολόγιο "εμάς" χρησιμοποιείται όταν πληκτρολογείτε τη φράση πρόσβασης. Για το λόγο αυτό, εάν κατά τη διάρκεια της εγκατάστασης χρησιμοποιείτε άλλο χάρτη πληκτρολογίου, πριν από ζητώντας τη φράση συνθηματικού ο εγκαταστάτης θα ορίσει το χάρτη πληκτρολογίου σε "εμάς", και αφού την καταγράψουν, επαναφέρετε το παλαιότερα χρησιμοποιούμενο. Σε αυτή την περίπτωση ο εγκαταστάτης θα ορθογραφήσει επίσης κάθε πληκτρολογημένο χαρακτήρα της φράσης πρόσβασης, καθώς μπορεί να διαφέρει από εκείνη που γράφτηκε στο κλειδί.

Η εφαρμογή cryptsetup χρησιμοποιείται για την κρυπτογράφηση του δίσκου. Για να μάθετε περισσότερους τύπους μετά την εγκατάσταση: +
-----
man cryptsetup
-----
// Speakup
[[Speakup]]
== Συντομεύσεις πλήκτρων για τον αναγνώστη οθόνης Speakup

Αυτό το κεφάλαιο προορίζεται για χρήστες που χρειάζονται αναγνώστη οθόνης αλλά δεν είναι εξοικειωμένοι με το Speakup.

Κρατήστε το numlock απενεργοποιημένο για να χρησιμοποιήσετε το Speakup.

Το πλήκτρο CapsLock χρησιμοποιείται ως πλήκτρο shift. Για παράδειγμα, το "CapsLock 4" σημαίνει: +
κρατήστε πατημένο το πλήκτρο CapsLock όπως ένα πλήκτρο shift και πατήστε 4.

 Πρώτες συνδέσεις πλήκτρων για να θυμάστε:
 PrintScreen Toggle speakup on/off.
 CapsLock F1 Speakup Help (πατήστε το πλήκτρο Space για έξοδο από τη βοήθεια).

 Συντομεύσεις πλήκτρων για να αλλάξετε τις ρυθμίσεις:
 CapsLock 1/2 Μείωση/Αύξηση της έντασης του ήχου.
 CapsLock 5/6 Μείωση/Αύξηση του ρυθμού ομιλίας.

 Βασικοί δεσμοί για να ελέγξετε την οθόνη:
 CapsLock j/k/l Πείτε Προηγούμενη/Τρέχουσα/Επόμενη λέξη.
 CapsLock k (δύο φορές) Ορθογραφική τρέχουσα λέξη.
 CapsLock u/i/o Πείτε Προηγούμενη/Τρέχουσα/Επόμενη γραμμή.
 CapsLock y Πείτε από το πάνω μέρος της οθόνης στην ανάγνωση του δρομέα.
 CapsLock p Πείτε από την ανάγνωση γραμμής δρομέα στο κάτω μέρος της οθόνης.
// First_steps
[[first_steps_after_installation]]
== Πρώτα βήματα μετά την εγκατάσταση

Εδώ είναι οι πρώτες εργασίες που θα εκτελεστούν μετά την εγκατάσταση

Σε αυτό το έγγραφο, όλο το κείμενο μετά από ένα χαρακτήρα # είναι σχόλια από τις προτεινόμενες εντολές, για να μην πληκτρολογηθεί.

=== Αρχική ενημέρωση λογισμικού

Μετά την εγκατάσταση, το σύστημα πρέπει να ενημερωθεί για να πάρει την πιο πρόσφατη παρεχόμενη έκδοση του κάθε λογισμικού, καθώς και νέο λογισμικό που παρέχεται από την έκδοση του ISO. Αυτό είναι ιδιαίτερα απαραίτητο αν δεν υπήρχε σύνδεση δικτύου κατά την εγκατάσταση, ως τότε εγκαταστάθηκαν μόνο τα πακέτα που περιλαμβάνονταν στα μέσα διανομής και θα μπορούσαν να είναι ξεπερασμένα.

Οι περισσότερες εντολές που πληκτρολογήθηκαν κάτω από το δικαίωμα διαχείρισης αίτησης που σχετίζεται με έναν συγκεκριμένο λογαριασμό που ονομάζεται 'root', για τον οποίο έχετε καταγράψει έναν κωδικό πρόσβασης κατά την εγκατάσταση.

Για να εκδώσετε μια εντολή ως 'ρίζα', πρώτος τύπος
----
su -
----
στη συνέχεια, εκδίδει τον κωδικό πρόσβασης για το root και πατήστε Enter πριν πληκτρολογήσετε την εντολή.

Όταν τελειώσετε την έκδοση εντολών ως 'ρίζα', πατήστε Ctrl+d ή πληκτρολογήστε 'έξοδο' για να λάβετε πίσω την κατάσταση του "κανονικού χρήστη".

Εναλλακτικά, ο χρήστης που έχει εγγραφεί κατά την εγκατάσταση και τα άλλα μέλη της ομάδας "wheel" μπορούν να πληκτρολογήσουν:
----
sudo <command>
----
τότε επίσης ο κωδικός για τον root.

Για ενημέρωση, πληκτρολογήστε ως ρίζα σε μια κονσόλα ή ένα γραφικό τερματικό:
----
slapt-get --add-keys # ανακτήστε τα πλήκτρα για τον έλεγχο ταυτότητας των πακέτων
slapt-get -u # να ενημερώσετε τη λίστα των πακέτων στους καθρέπτες
slapt-get --install-set slint # να πάρει τα νέα πακέτα
slapt-get --upgrade # Πάρτε τις νέες εκδόσεις των εγκατεστημένων πακέτων
dotnew # απαριθμεί τις αλλαγές στα αρχεία ρυθμίσεων
----
Όταν εκτελείτε dotnew, αποδεχτείτε να αντικαταστήσετε όλα τα παλιά αρχεία ρύθμισης παραμέτρων με νέα. Αυτό είναι ασφαλές όπως κάνατε't κάνει οποιαδήποτε προσαρμογή ακόμα.

Εναλλακτικά, μπορείτε να χρησιμοποιήσετε αυτά τα γραφικά μπροστινά άκρα: gslapt αντί slapt-get, και dotnew-gtk αντί dotnew.

Για να μάθετε περισσότερα για το slapt-get, πληκτρολογήστε:
----
man slapt-get
----
ή ως ρίζα:
----
slapt-get --help
----
και διαβάστε το /usr/doc/slapt-get*/README.slaptgetrc.Slint

// Glossary
== Γλωσσάριο

Several definitiενεργόs in this glossary are taken or adapted from https://en.wikipedia.org/wiki/Main_Page[Wikipedia] and https://pubs.opengroup.org/onlinepubs/9699919799/[POSIX]

[[applicatiενεργό]]Εφαρμογή:: An applicatiενεργό program (applicatiενεργό for short) is a computer program designed to carry out a specific task typically requested by end-users.
+
Οι εφαρμογές δεν θεωρούνται γενικά ως μέρος του λειτουργικού συστήματος, πράγμα που σημαίνει ότι μπορούν να προστεθούν στο σύστημα μετά την εγκατάστασή του. Εκτελούν λειτουργίες που δεν σχετίζονται με το σύστημα, όπως επεξεργασία κειμένων, αρχιτεκτονικός σχεδιασμός, μηχανικός σχεδιασμός, έκδοση ή οικονομική ανάλυση.


[[boot]]Εκκίνηση::
Boot means switch-ενεργό a computer to start an operating system. Αρκετά λειτουργικά συστήματα μπορούν να εγκατασταθούν στον ίδιο υπολογιστή. Select which one to load into RAM and run can be dενεργόe either by the firmware or by a software named boot manager (GRUB in Slint's case). The firmware of a computer can support ενεργόe of following booting mode, or both:
+
* In the Legacy or BIOS mode the OS is loaded executing the instructiενεργόs written in a boot sector.
* Στη λειτουργία EFI το OS loader είναι ένα πρόγραμμα που αποθηκεύεται σε ένα εκτελέσιμο αρχείο, που βρίσκεται σε έναν κατάλογο ενός διαμερίσματος συστήματος EFI (ESP).

[[Επεξεργαστής]]CPU::
Η CPU ή Κεντρική Μονάδα Επεξεργασίας εκτελεί τις οδηγίες των προγραμμάτων.

[[command]]Εντολή:: Η εντολή ορίζεται από τον https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_104[POSIX] ως "οδηγία για ένα <<shell, κέλυφος>> για να εκτελέσει μια συγκεκριμένη εργασία".
+
Η εργασία που θα εκτελεστεί μπορεί να είναι μια <<application, εφαρμογή>> ή ένα <<utility, βοηθητικό πρόγραμμα>>.
+
Η βασική δομή των εντολών κελύφους ορίζεται στο κεφάλαιο https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09[2.9 Εντολές κελύφους] της προδιαγραφής POSIX.
+
Παραδείγματα εντολών παρέχονται στο <<bash shell, [κελύφος bash]>>.

[[console]]Κονσόλα:: Η λέξη "κονσόλα" αναφέρεται στην αρχή του υπολογιστή συστήματα, όταν ο διαχειριστής του συστήματος πληκτρολόγησε εντολές σε μια συσκευή, συμπεριλαμβανομένου ενός πληκτρολογίου και ενός εκτυπωτή, συνδεδεμένες με τον υπολογιστή, τις εντολές που πληκτρολογήθηκαν και την έξοδο από τον υπολογιστή που εκτυπώνεται στην κονσόλα, παρέχοντας ένα αρχείο καταγραφής και των δύο.
+
Σε προσωπικούς υπολογιστές, ο χρήστης πληκτρολογεί τις εντολές στο πληκτρολόγιο και η έξοδος τους εκτυπώνεται σε μια οθόνη, που μπορούν να διαχωριστούν από τον υπολογιστή ή να ενσωματωθούν στον υπολογιστή όπως σε ένα φορητό υπολογιστή.

[[device]]Συσκευή::

Ένας υπολογιστής περιφερειάρχης ή ένα αντικείμενο που εμφανίζεται στην εφαρμογή ως τέτοιο.[POSIX]

[[directory]]Κατάλογος::
Ένας κατάλογος είναι ένα άλλο όνομα για ένα φάκελο. Τα συστήματα αρχείων χρησιμοποιούν καταλόγους για να οργανώσουν αρχεία μέσα σε κατατμήσεις.
+
Οι κατάλογοι μπορούν να περιέχουν αρχεία καθώς και άλλους καταλόγους. Η δομή που προκύπτει μπορεί να αναπαρίσταται ως ανεστραμμένο δέντρο. Ο κατάλογος πρώτου επιπέδου μιας μονάδας ονομάζεται κεντρικός κατάλογος. Στο Linux ο χαρακτήρας / χωρίζει τα επίπεδα του δέντρου. / Μόνο αντιπροσωπεύει τον κεντρικό κατάλογο, /home φιλοξενεί τα αρχεία που ανήκουν στους χρήστες, /home/didier φιλοξενεί τα αρχεία που ανήκουν στο χρήστη didier. /root φιλοξενεί τα αρχεία του χρήστη root (ο διαχειριστής του συστήματος). Σημείωση: 'root' μπορεί να παραπέμπει στον κατάλογο πρώτου επιπέδου ή στο διαχειριστή του συστήματος.

[[drive]]Οδηγός::
Μια μονάδα δίσκου είναι μια συσκευή που αποθηκεύει μη πτητικά δεδομένα, πράγμα που σημαίνει ότι τα δεδομένα δεν είναι σβησμένα όταν η ισχύς είναι απενεργοποιημένη. Παραδείγματα: σκληροί δίσκοι, SSD, USB sticks, SD κάρτες αναγνώστες, eMMC.
+
Τα μέσα αποθήκευσης των δεδομένων μπορεί να συνδεθεί μόνιμα με τη μονάδα δίσκου ή αφαιρούμενα όπως κάρτες SD, USB sticks και δίσκους που συνδέονται μέσω USB.
+
Ένα λειτουργικό σύστημα εγκατεστημένο σε αφαιρούμενο μέσο ή μια εξωτερική μονάδα δίσκου λέγεται φορητό: μπορεί να μετακινηθεί από έναν υπολογιστή σε άλλο.

[[display_manager]]Διαχειριστής οθόνης::
Ένας διαχειριστής εμφάνισης (ή διαχειριστής σύνδεσης) είναι ένα λογισμικό που εμφανίζει ένα παράθυρο στην οθόνη στο οποίο ζητά το όνομα σύνδεσης και τον κωδικό πρόσβασης του χρήστη, ξεκινά το γραφικό περιβάλλον που επιλέγεται από τον εν λόγω χρήστη.

[[encryption]]Κρυπτογράφηση::
Η κρυπτογράφηση είναι η διαδικασία μετατροπής δεδομένων σε μια μη αναγνωρίσιμη («κρυπτογραφημένη») μορφή. Χρησιμοποιείται συνήθως για την προστασία ευαίσθητων πληροφοριών, έτσι ώστε μόνο εξουσιοδοτημένα πρόσωπα να μπορούν να τις δουν. Ένα ενιαίο αρχείο ή κατάλογος, ένα διαμέρισμα καθώς και ως ολόκληρη μονάδα δίσκου μπορεί να κρυπτογραφηθεί, which make it accessible only after having typed a small text called a passphrase, kept secret.

[[file]]Αρχείο::
Ένα αρχείο υπολογιστή είναι ένα σύνολο ψηφιακών δεδομένων που συλλέγονται με το ίδιο όνομα, που καταγράφονται σε ένα μόνιμο μέσο αποθήκευσης, ονομάζεται μαζική αποθήκευση, όπως ένας σκληρός δίσκος, ένα SSD, ένα DVD, μια κάρτα SD ή ένα USN stick και χειρίζεται ως μονάδα.
+
Τα αρχεία μπορούν να περιέχουν δεδομένα όπως κείμενα, εικόνες, ήχους, βίντεο ή προγράμματα υπολογιστών.

[[file_system]]Σύστημα Αρχείων::
Ένα σύστημα αρχείων είναι ένα λογισμικό που διαχειρίζεται τα αρχεία και τους καταλόγους σε μια κατάτμηση. Απομνημονεύει τη θέση στα φυσικά μέσα των δεδομένων που περιέχονται στα αρχεία, επιτρέποντας να τα διαβάσει ή να τα γράψει. Παραδείγματα κοινώς χρησιμοποιούμενων συστημάτων αρχείων είναι vfat, ntfs, ext4, f2fs. Αυτή η εντολή εμφανίζει όλα τα συστήματα αρχείων που επιτρέπουν την ανάγνωση δεδομένων που περιέχονται σε ένα διαμέρισμα από το Linux:
+
----
cat /proc/filesystems±grep -v nodev
----

[[firmware]]Υλικολογισμικό::
Ένα υλικολογισμικό είναι ένα λογισμικό που αρχικοποιεί και ελέγχει το υλικό, τότε είτε επιλέγει και φορτώνει σε RAM το λειτουργικό σύστημα, ή ξεκινά ένα λογισμικό που ονομάζεται διαχειριστής εκκίνησης που θα το κάνει αυτό. Το υλικολογισμικό διατηρείται σε μη-πτητική μνήμη συσκευές, όπως ROM, EPROM, ή μνήμη flash. Είναι το πρώτο λογισμικό που εκτελείται κατά την εκκίνηση ενός υπολογιστή. Παρέχει ένα μενού που επιτρέπει να ρυθμίσετε το υλικό και επιλέξτε σε ποια κατάσταση (Legacy ή EFI) για εκκίνηση, και με την οποία να αναζητήσετε το λειτουργικό σύστημα ή άλλη εφαρμογή (όπως ο διαχειριστής εκκίνησης GRUB) για να εκτελέσετε.

[[kernel]]Πυρήνας::
Ένας πυρήνας Linux είναι το λογισμικό στον πυρήνα ενός συστήματος Slint που χειρίζεται τις αλληλεπιδράσεις μεταξύ των εφαρμογών και του υλικού.
+
Παρουσιάζεται ως ένα μόνο αρχείο, εγκατεστημένο στον κατάλογο /boot. Για παράδειγμα το αρχείο /boot/vmlinuz-generic-5.12.11 είναι ένας πυρήνας, που προέρχεται από το γενικό πακέτο πυρήνα.
+
Κατά την εκκίνηση ο πυρήνας αντιγράφεται στη μνήμη RAM.

[[initrd]]Initrd::
Ένα initrd (ακριβέστερα ένα initramfs ή ένα αρχικό σύστημα αρχείων RAM για Slint) είναι ένα σύστημα Linux που παρέχεται ως συμπιεσμένο αρχείο αρχείου. Κατά την εκκίνηση, αμέσως μετά την φόρτωση του πυρήνα στη μνήμη RAM το initrd φορτώνεται και στη μνήμη RAM. Το αρχείο /init τρέχει: φορτώνει τις απαιτούμενες ενότητες πυρήνα στη μνήμη RAM, καταχωρεί τις συσκευές, ενδεχομένως ξεκλειδώνει τη root συσκευή, προσαρτά τα ψευδο-συστήματα αρχείων έπειτα μεταβαίνει στο ριζικό σύστημα αρχείων για να ξεκινήσετε πραγματικά το σύστημα.
+
Ένα initrd παρουσιάζεται ως ένα μόνο αρχείο, εγκατεστημένο στην εκκίνηση του καταλόγου. Για παράδειγμα, το αρχείο initrd-generic-5.12.11 είναι initrd

[[live_system]]Ζωντανό σύστημα::
Ένα ζωντανό σύστημα είναι ένα λειτουργικό σύστημα που, αντί να εγκατασταθεί σε μια συσκευή όπως ένας σκληρός δίσκος ή SSD, βρίσκεται εξ ολοκλήρου σε <<RAM>>.
+
An initrd is also a live system, and so is a Slint εγκαταστάτης wich is basically an initrd.

[[partition]]Διαμέρισμα::
Ένα διαμέρισμα είναι ένα τμήμα ενός μέσου αποθήκευσης, όπως ένας σκληρός δίσκος ή SSD. Αντιμετωπίζεται από το λειτουργικό σύστημα ως ξεχωριστός λογικός τόμος, ο οποίος καθιστά τη λειτουργία παρόμοια με μια ξεχωριστή συσκευή.

[[partition_table]]Πίνακας χωρισμάτων::
Ένας πίνακας διαμερισμάτων είναι η μόνιμη δομή που καταγράφει τον τρόπο με τον οποίο οι πληροφορίες παρέχονται σε ένα μέσο, κυρίως καταγραφή της αρχής και του τέλους κάθε διαμερίσματος στα μέσα ενημέρωσης.
+
Οι πιό κοινοί τύποι πινάκων κατατμήσεων είναι ο πίνακας κατατμήσεων DOS, που χρησιμοποιήθηκε αρχικά από το λειτουργικό σύστημα MS-DOS, και ο πίνακας κατατμήσεων GUID ή GPT, το οποίο επιτρέπει να χειριστεί περισσότερες κατατμήσεις και μεγαλύτερες κινήσεις.

[[program]]Πρόγραμμα::
Μια προετοιμασμένη ακολουθία οδηγιών προς το σύστημα για να ολοκληρώσει μια καθορισμένη εργασία. Ο όρος "πρόγραμμα" περιλαμβάνει εφαρμογές που είναι γραμμένες στη γλώσσα εντολών της Shell, σύνθετες γλώσσες εισαγωγής βοηθητικών προγραμμάτων (για παράδειγμα, awk, lex, sed, και ούτω καθεξής), και υψηλού επιπέδου γλώσσες. [POSIX]

[[RAM]]RAM::
RAM σημαίνει μνήμη τυχαίας πρόσβασης. Αυτό το είδος συσκευής αποθηκεύει πτητικά δεδομένα, που σημαίνει ότι τα δεδομένα διαγράφονται όταν η ισχύς είναι απενεργοποιημένη.

[[shell]]Κέλυφος:: Ένα πρόγραμμα που ερμηνεύει ακολουθίες από την είσοδο κειμένου ως εντολές. Μπορεί να λειτουργεί σε μια ροή εισόδου ή μπορεί να παρακινεί και να διαβάζει εντολές από ένα τερματικό. Η σύνταξη των εντολών που μπορούν να ερμηνευτούν από το κέλυφος μπορεί να διαφέρει ανάλογα με το κέλυφος που χρησιμοποιείται αλλά ορίζεται κυρίως στο κεφάλαιο https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html [2. Γλώσσα εντολών κελύφη] των προδιαγραφών POSIX.
+
Το Slint στέλνει διάφορα προγράμματα που ενεργούν ως κέλυφος, που απαριθμούνται στο αρχείο /etc/shells. Το κέλυφος *bash* χρησιμοποιείται από προεπιλογή.

[[swap]]Εναλλαγή::
Ένας χώρος ανταλλαγής swap space χρησιμοποιείται για την αποθήκευση δεδομένων προγενέστερα στο RAM σε μια συσκευή όπως ένας σκληρός δίσκος ή SSD, είτε επειδή αλλιώς η RAM θα γινόταν πλήρης, είτε για να ελευθερώσει χώρο στο RAM για να αποθηκεύσει εκεί τα πιο συχνά χρησιμοποιούμενα δεδομένα. Ο χώρος ανταλλαγής μπορεί να είναι ένα διαμέρισμα σε μια μονάδα τύπου 'Linux swap' ή ένα κανονικό αρχείο που αποθηκεύεται σε ένα υπάρχον διαμέρισμα. Υπάρχει επίσης το "swap in zram": σε αυτή την περίπτωση τα δεδομένα αποθηκεύονται στο RAM αλλά σε συμπιεσμένη μορφή.

[[terminal]]Τερματικό::
Ιστορικά ένα τερματικό ήταν μια φυσική συσκευή που αποτελείται από ένα πληκτρολόγιο και μια οθόνη που χρησιμοποιείται για τον τύπο εντολών και λαμβάνει απαντήσεις από έναν απομακρυσμένο υπολογιστή.
+
Σήμερα οι εντολές μπορούν να πληκτρολογηθούν σε λειτουργία κονσόλας (ή κειμένου) ή σε γραφική λειτουργία.

[[utility]]Εργαλείο::
Ένα βοηθητικό πρόγραμμα είναι ένα πρόγραμμα που μπορεί να κληθεί από ένα κέλυφος (αυτό είναι επίσης η περίπτωση του <<application,applications>>).
+
Τα βοηθητικά προγράμματα αποτελούν μέρος του λειτουργικού συστήματος (αλλά όχι του πυρήνα). Εκτελούν λειτουργίες που σχετίζονται με το σύστημα, όπως περιεχόμενο καταλόγου καταλόγου, έλεγχο συστημάτων αρχείων, επισκευή συστημάτων αρχείων, ή εξαγωγή πληροφοριών κατάστασης συστήματος.
+
Ένα βοηθητικό πρόγραμμα μπορεί να κληθεί ως ξεχωριστό πρόγραμμα που εκτελεί σε διαφορετική διαδικασία από το διερμηνέα της γλώσσας εντολής, ή μπορεί να υλοποιηθεί ως μέρος του διερμηνέα της γλώσσας εντολής.
+
Για παράδειγμα, η εντολή echo (η οδηγία για την εκτέλεση μιας συγκεκριμένης εργασίας) μπορεί να υλοποιηθεί έτσι ώστε το βοηθητικό πρόγραμμα echo (η λογική που εκτελεί την εργασία της απήχησης) να βρίσκεται σε ένα ξεχωριστό πρόγραμμα. Ως εκ τούτου, εκτελείται σε μια διεργασία που διαφέρει από τον ερμηνευτή γλώσσας εντολών. Πρακτικά αυτό σημαίνει ότι σε αυτή την περίπτωση το βοηθητικό πρόγραμμα είναι ένα πρόγραμμα διαφορετικό από το κέλυφος
+
Αντιστρόφως, η λογική που εκτελεί το βοήθημα echo θα μπορούσε να ενσωματωθεί στον ερμηνευτή γλώσσας εντολών. Ως εκ τούτου, θα μπορούσε να εκτελεστεί στην ίδια διεργασία με τον ερμηνευτή γλώσσας εντολών. Ένα τέτοιο βοηθητικό πρόγραμμα λέγεται "ενσωματωμένη" το κέλυφος.

[[virtual_terminal]]Εικονικό τερματικό::
Ένα εικονικό τερματικό είναι ένα λογισμικό που προσομοιώνει ένα φυσικό τερματικό, συσκευή που αποτελείται από ένα πληκτρολόγιο και μια οθόνη που επιτρέπει την απομακρυσμένη επικοινωνία με έναν υπολογιστή .
