:toc: left
:toclevels: 1
:toc-title: 

// Overview
[[Overview_of_Slint_Installation]]
== Översikt över installationsprocessen

Installationsprogrammet söker först på befintliga enheter och partitioner för att bedöma möjligheterna och alternativen för installation och låter dig välja mellan en automatisk eller manuell förberedelse av de partitioner som används av Slint.

Om du väljer "manuell" visas de Linux-partitioner där Slint kan installeras (storlek minst 50G), välj en av dem och välj den typ av filsystem som installationsprogrammet ska skapa på den: btrfs, ext4 eller xfs enligt vad som anges i <<prepare_partitions_for_Slint,Förbered eventuellt partitioner för Slint>>

Om du väljer "auto" visas de enheter där Slint kan installeras (storlek minst 50G), och filsystemet kommer att vara av typen btrfs.

När det gäller btrfs, skapas undervolymer för / /home och /snapshots med filer komprimerade och /swap för att hålla en swap-fil. 'Copy on write' kommer att underlätta att göra statusbilder och eventuellt återställa en felaktig systemuppdatering. Verktyg för hantering av ögonblicksbilder ingår i Slint.

I båda lägen väljer användaren vilka befintliga Linux-och Windows-partitioner som ska monteras automatiskt efter uppstart av Slint, och deras monteringspunkt-namn, underlättar åtkomsten till existerande system och data från Slint.

Sedan föreslås användaren att kryptera rotsystems-partitionen, för att förhindra att data stjäls vid förlust eller stöld av maskinen eller enheten där Slint är installerat. Om det accepteras kommer installationsprogrammet att lagra lösenordsfrasen som tillåter att låsa upp denna partition. Användaren kommer när han skriver det vid uppstart när GRUB begär att få visa uppstartsmenyn.

Efter allt det kommer installationsprogrammet att sammanfatta dina val och låter dig bekräfta dem eller inte. Fram till denna punkt kommer ingen ändring att ha gjorts på det installerade systemet och data så att du säkert kan avbryta, skriv sedan start igen eller bara reboot utan att något skadas.

Därefter utförs automatisk partitionering, Slint rotpartitionen krypteras om så önskas, rotpartitionen är formateras och de första programpaketen installeras.

Om du väljer en krypterad disk skriver du lösenordsfrasen som kommer att användas för att låsa upp disken vid varje uppstart.

Du väljer ett lösenord för användaren "root". Det här är systemadministratören som har alla behörigheter.

Du anger också inloggningsnamnet och lösenordet för en vanlig användare.

Du anger om du vill ha åtkomst till Braille och om du vill logga in i text eller grafiskt läge. Om du använder språket engelska (USA) under installationen väljer du det språk som ska användas i det installerade systemet, annars anger installationsprogrammet samma språk som under installationen.

Installationsprogrammet försöker upprätta en Internetuppkoppling, och om det föreslås en tidszon som motsvarar den geografiska plats som du bekräftar, annars väljer du en annan i en lista.

Du blir tillfrågad om du behöver Braille, sen om du föredrar att starta i en konsol eller i ett grafiskt såvida du inte använt tal under installationen eller behöver punktskrift: då kommer du att landa i en konsol efter omstart, för säkerhets skull.

Installationsprogrammet skapar sedan en swap-fil. Det här kan ta en lång tid, var tålmodig.

Paketen installeras på enheten. Om en Internetanslutning har upprättats hämtas den och installerar den senaste versionen av varje paket, inklusive de som tillhandahålls sedan versionen av ISO-avbilden.

Installationen av alla paket tar ca 10 till 40 minuter beroende på maskinvaran.

Du kommer att bli ombedd att välja ett skrivbord (även om du startar i en konsol först) mellan fvm, lxqt, mate och wmaker. Andra alternativ kommer att vara tillgängliga efter installationen av xwmconfig om du startar i en konsol

Sedan är systemet konfigurerat och GRUB-starthanteraren är installerad. Slint kan starta i både Legacy och EFI-lägen. Startmenyn kommer att innehålla en "Rescue"-startpost för att upptäcka och tillåta att alla installerade operativsystem kan startas.

Du kan visa en förhandsgranskning av startmenyn innan du startar om.

Ta sedan bort installationsmediet och starta om för att starta ditt nya Slint-system.
// Usage_installer
[[Usage_of_the_installer]]
== Användning av installationsprogrammet

Om du är bekant med kommandoraden, kan du hoppa över detta ämne.

Huvudinstallationsmenyn visas nedan:
....
Välkommen till Slint-installeraren! (version 15)

Du kan nu skriva (utan citattecken):

'doc' för att känna till funktionerna och användningen av installationsprogrammet.
'start' för att starta installationen.

Installationsprogrammet kan förbereda enheten där Slint kommer att installeras,
och skapa de nödvändiga partitionerna. Om du föredrar att du vill göra det själv kan du göra det
med hjälp av kommandoradsverktyg som är tillgängliga i installationsprogrammet och sedan skriva "start"
när det är klart. Du kan också lämna installationsprogrammet och använda ett verktyg som gparted
för att göra det och starta sedan installationsprogrammet igen.

Vi rekommenderar att du skriver 'doc' först i det här fallet, eller om du vill 
kryptera Slint`s rotpartition.
När du har läst färdigt kommer den här menyn att visas igen.
....

Så snart denna meny visas, har du handen på installationsprocessen.

Du läser på skärmen och skriver kommandon i en <<virtual_terminal, virtuell terminal>>. Installationsprogrammet innehåller 4 virtuella terminaler som delar samma fysiska tangentbord och skärm, och som kan användas parallellt.

Installationsprogrammet startar i den virtuella terminalen 1 som heter *tty1* men du kan byta till en annan. Till exempel kan du växla till *tty2* genom att trycka *Alt-F2* och sedan Enter för att aktivera den och senare gå tillbaka till *tty1* genom att trycka på *Alt-F1*, utan att radera information som visas i båda terminalerna. *Alt-F1* betyder: tryck och håll nere *Alt* -tangenten och tryck sedan på *F1* tangenten.

Detta kan vara användbart för att fortsätta läsa dokumentationen under installationen: till exempel kan du växla till *tty2* för att påbörja installationen. växla till *tty1* till fortsätta läsa dokumentationen, växla sedan till *tty1* igen för att fortsätta till nästa installationssteg.

Detta kan också användas för att konsultera ordlistan när du läser andra dokument.

Installationsprogrammet har flera typer av interaktion med dig, användaren:

* Du skriver kommandon på prompten och läser dess utdata.
* Installationsprogrammet ställer en fråga, du skriver in svaret och bekräftar det genom att trycka på Enter.
* Installationsprogrammet visar en meny med val eller alternativ: du väljer en av dem med hjälp av upp och ner piltangenterna, bekräfta sedan ditt val genom att trycka på Enter, eller avbryt genom att trycka på Escape.
* Installationsprogrammet visar information i en pager. Använd piltangenterna för att läsa nästa eller föregående rad, tryck på mellanslag för att visa nästa sida, Q för att sluta läsa dokumentet.

// Prepare
[[prepare_partitions_for_Slint]]
== Valfritt: Förbered partitioner för Slint

I det här dokument betyder 'format' en partition: skapa ett filsystem i den för att hantera de filer den kommer att innehålla.

Om du efter att ha skrivit "start" skriver "m" för manuell partitionering väljer du först root-systempartitionen, som kommer att monteras som "/", sedan typ av filsystem t.ex.: btrfs, ext4, xfs.

Installationsprogrammet listar enbart partitioner för val med minst 50G och Linux (kan också kallas Linux-filsystem), inte krypterade. Den här partitionen kan formateras eller inte, men dess innehåll kommer i alla händelser att rensas bort och ett nytt filsystem genereras av installationsprogrammet.

Dessutom krävs i manuell partitioneringsläge på samma enhet som rotsystempartitionen:

* En partition av typen BIOS boot partition, med storleken minst 3M och inte formaterad.
* En partition av typen EFI-system, med minst 32M ledigt utrymme, formaterad med ett 'fat' (eller 'vfat')-filsystemet som krävs enligt UEFI-specifikationen

Använda Slint på befintliga partitioner eller skapa dem är upp till användaren. Redan installerade system som använder BIOS boot och EFI-partitionerna kommer inte att påverkas, endast root-partitionen kommer att bli (om)formaterad.

Installationsprogrammet innehåller flera partitioneringsprogram: cfdisk, fdisk, sfdisk, cgdisk, gdisk, sgdisk, partad. Programmen med "g" i deras namn kan hantera endast gpt, parted kan hantera DOS-partitionstabeller samt GPT. fdisk, cfdisk och sfdisk kan hantera DOS partitionstabeller. Dessutom, wipefs (för att radera tidigare partitionstabell och filsystem signaturer) och partprobe (för att informera kärnan om en partitionstabelländringar) är tillgängliga. Programmet lsblk visar information om blockenheter och partitioner.

Naturligtvis kan du också skapa partitionerna från ett annat system innan du startar installationsprogrammet.
// Installation
// Encryption
[[Encryption]]
== Slint med en krypterad rotpartition.

I Auto-läge föreslår installationsprogrammet att kryptera rotsystemspartitionen. Om du samtycker, kommer GRUB starthanteraren vid varje uppstart att fråga efter lösenordsfrasen som du angav under installationen för att låsa upp enheten, innan uppstartsmenyn visas. Var medveten om att upplåsning av enheten kommer att ta några sekunder (cirka tio sekunder).

Att ha ett krypterat rotsystem förhindrar stöld av data som den innehåller vid förlust eller stöld av maskinen, eller av en flyttbar enhet. Men detta kommer inte att skydda dig om datorn förblir igång och obevakad, bara om maskinen har stängts av helt!

Under installationen kommer Slint systempartitionen att krypteras, och även ytterligare partitioner som du begär.

Ett Slint-system (eller root) partition kommer att namnges: /dev/mapper/cryproot när den öppnas, om den har krypterats.

Detta visas av detta kommando:

----
lsblk -lpo namn,fstype,monteringspunkt | grep /$
----

Vilket ger en utmatning liknande:
----
/dev/mapper/cryptroot ext4 /
----

Detta kommando istället:

----
lsblk -lpo namn,fstype,monteringspunkt | grep /dev/sda3
----

ger:

----
/dev/sda3             cryptoLUKS
----

/dev/sda3 är nu en "rå" partition som innehåller det så kallade "LUKS header" som du aldrig kommer att behöva eller någonsin bör komma åt direkt. Den är värd för allt som behövs för att kryptera eller dekryptera partitionen /dev/mapper/cryptroot, som faktiskt är värd för dina data (i detta exempel Slint-systemet).

[WARNING]
====
Om du glömmer lösenordsfrasen kommer all data i enheten att vara oåterkalleligt förlorad! Så skriv ner eller spela in denna lösenordsfras och placera den på en säker plats så snart som det är gjort.

Enheter dör. Om det händer och den är krypterad kommer dina data att gå förlorade. Så, säkerhetskopiera regelbundet dina viktiga data, detta är inte frivilligt.

Gör också en säkerhetskopia av den luks header så att du kan återställa ifall luks partition skadas av någon anledning. Kommandot kan finnas i vårt exempel:
----
luksHeaderBackup /dev/sda3 --header-backup-file <fil>
----
där <fil> är namnet på backupfilen, som du skall lagra på en säker plats.

Om du skulle du behöva återställa säkerhetskopian, skriv:
----
luksHeaderRestore /dev/sda3 --header-backup-file <fil>
----

Ändra inte storlek på en partition på en krypterad enhet som efter det skulle definitivt bli låst och alla data som den innehåller kommer att förloras! Om du verkligen behöver mer utrymme måste du säkerhetskopiera alla filer som du vill behålla, installera sedan på nytt och återställa säkerhetskopierade filer.

Välj ett starkt lösenordsfras, så att det skulle ta för mycket tid för en tjuv att upptäcka att det ska vara värt besväret.

Fiddla aldrig någonsin med den så kallade "LUKS header" som ligger på den råa partitionen (den tredje, t.ex. /dev/sda3 för den råa partitionen ovanpå systempartitionen Slint). I praktiken: skapa inte ett filsystem i denna partition, gör inte det till en del av en RAID array och skriv generellt inte till den: alla data skulle bli oåterkalleligt förlorade!
====

För att undvika svaga lösenordsfraser kräver installationsprogrammet att lösenordsfrasen inkluderar:

. Minst 8 tecken.
. Endast icke-accenttecken små och stora bokstäver, siffror från 0 till 9, mellanslag och följande skiljetecken:
+
----
 -" ! " # $% & () * +,-. /: ; < = >? @ [ \ ] ^ _ " { | } ~
----
+
Detta garanterar att även ett nytt tangentbord kommer att ha alla tecken som behövs för att skriva lösenordsfrasen.

. Minst en siffra, en liten bokstav, en stor bokstav och en skiljetecken.

GRUB förutsätter att "us"-tangentbordet används när du skriver lösenordsfrasen. Av denna anledning, om du under installationen använder en annan tangentbordslayout, innan installationsprogrammet frågar efter lösenordsfrasen kommer den att ställa in tangentbordslayouten till "us", och efter att ha spelat in det återställa den till den tidigare använda. I det här fallet kommer installationsprogrammet även att stava varje typ av lösenordsfras, eftersom det kan skiljer sig från den skrivna på tangenten.

Programmet cryptsetup används för att kryptera enheten. För att veta mer skriv in efter installation: +
-----
man cryptsetup
-----
// Speakup
[[Speakup]]
== Tangentbindningar för skärmläsaren Speakup

Detta kapitel är avsett för användare som behöver en skärmläsare men inte känner till Speakup.

Behåll numlock avaktiverad för att använda Speakup.

CapsLock-tangenten används som en shift-tangent. Till exempel "CapsLock 4" betyder: +
håll ned CapsLock-tangenten som en shift-tangent och tryck på 4.

 Första tangentbindning att komma ihåg:
 PrintScreen         Växla Speakup till/från.
 CapsLock F1         Speakup Hjälp (tryck på mellanslag för att avsluta hjälpen).

 Tangentbindningar för att ändra inställningar:
 CapsLock 1/2        Minska/Öka ljudvolymen.
 CapsLock 5/6        Minska/Öka talhastigheten.

 Tangentbindningar för att granska skärmen:
 Caps Lock j/k/l      Säg Föregående/Nuvarande/Nästa ord.
 Caps Lock k (två gånger)  Stava nuvarande ord.
 Caps Lock u/i/o     Säg Föregående/Nuvarande/Nästa rad.
 Caps Lock y         Säg från toppen av skärmen till läsmarkören.
 CapsLock p          Säg från läsmarkören till botten av skärmen.
// First_steps
[[first_steps_after_installation]]
== Första steg efter installation

Här är de första uppgifterna att utföra efter installationen

I detta dokument är all text efter ett # tecken kommentarer till de föreslagna kommandona, och skall inte skrivas.

=== Initial programuppdatering

Efter installationen bör systemet uppdateras för att få den senast tillhandahållna versionen av varje programvara, samt ny programvara som tillhandahålls sedan lanseringen av ISO-avbilden. Detta är särskilt nödvändigt om ingen nätverksanslutning var tillgänglig under installationen, som då bara installerade paket som ingår i distributionsmediat, och de kan vara föråldrade.

De flesta kommandon som skrivs nedan kräver administrativ rättighet kopplad till ett specifikt konto som heter 'root', för vilket du har registrerat ett lösenord under installationen.

För att köra ett kommando som "root", skriv först
----
su -
----
ange sedan lösenordet för root och tryck på Enter innan du skriver kommandot.

När du är klar med att utfärda kommandon som 'root', tryck på Ctrl+d eller skriv 'exit' för att få tillbaka din "vanliga användar"-status.

Alternativt kan den användare som är registrerad under installationen och andra medlemmar av typen "wheel" gruppen skriva:
----
sudo <kommando>
----
och sedan också lösenordet för root.

För att uppdatera, skriv som root i en konsol eller en grafisk terminal:
----
slapt-get --add-keys # hämta nycklarna för att autentisera paketet
slapt-get -u # uppdatera listan över paket i paketförråden
slapt-get --install-set slint # hämta de nya paketen
slapt-get --upgrade # hämta de nya versionerna av installerade paket
dotnew # listar ändringarna i konfigurationsfilerna
----
När du kör dotnew, acceptera att ersätta alla gamla konfigurationsfiler med nya. Detta är säkert eftersom du inte gjort någon anpassning ännu.

Alternativt kan du använda dessa grafiska front-ends: gslapt istället för slapt-get och dotnew-gtk istället för dotnew.

För att lära dig mer om slapt-get, skriv:
----
man slapt-get
----
eller som root:
----
slapt-get --help
----
och läs /usr/doc/slapt-get*/README.slaptgetrc.Slint

// Glossary
== Ordlista

Flera definitioner i denna ordlista har tagits eller anpassats från https://en.wikipedia.org/wiki/Main_Page[Wikipedia] och https://pubs.opengroup.org/onlinepubs/9699919799/[POSIX]

[[application]]Program:: Ett program är ett datorprogram som är konstruerat för att utföra en viss uppgift som vanligen begärs av slutanvändare.
+
Program betraktas inte i allmänhet som en del av operativsystemet, vilket innebär att de kan läggas till i systemet efter installationen. De utför icke-systemrelaterade funktioner, t. ex. ordbehandling, arkitektonisk design, mekanisk design, publicering eller finansiell analys.


[[boot]]Boot::
Boot innebär att slå på en dator för att starta ett operativsystem. Flera operativsystem kan installeras i samma dator. Välj vilken som ska laddas in i RAM och köras kan göras antingen av den inbyggda programvaran eller av en programvara som heter boot manager (GRUB i Slints fall). Den inbyggda programvaran i en dator kan stödja en av följande uppstartsläge, eller båda:
+
* I Legacy-eller BIOS-läge laddas OS i exekvering av instruktionerna i en startsektor.
* I EFI-läget är OS-laddaren ett program som lagras i en körbar fil, som finns i en katalog för en EFI System-partition (ESP).

[[CPU]]CPU::
CPU eller Central Processing Unit utför instruktionerna i program.

[[command]]Kommando:: Kommandot definieras av https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_104[POSIX] som "ett direktiv till ett <<shell, skal>> för att utföra en specifik uppgift".
+
Uppgiften att utföra kan vara en <<application, program>> eller ett <<utility, verktyg>>.
+
Grundstrukturen för skalkommandon definieras i kapitlet https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09[2.9 Shell Commands] i POSIX-specifikationen.
+
Exempel på kommandon finns i <<bash shell>>.

[[console]]Konsol:: Ordet "konsol" hänvisar till början av datorn system, när systemadministratören skrev kommandon på en enhet inklusive ett tangentbord och en skrivare, länkad till datorn, kommandona som skrivs in och utdata från datorn som skrivs ut på konsolen, vilket ger en logg över båda.
+
I persondatorer skriver användaren kommandona på tangentbordet och deras utdata skrivs ut på en skärm, som kan separeras från eller integreras med datorn som i en bärbar dator.

[[device]]Enhet::

En datorkringutrustning eller ett objekt som visas för programmet som sådan.[POSIX]

[[directory]]Katalog::
En katalog är ett annat namn för en mapp. Filsystem använder kataloger för att organisera filer inom partitioner.
+
Kataloger kan innehålla filer och andra kataloger. Den resulterande strukturen kan representeras som ett uppochnedträd. Katalogen på toppnivå för en enhet heter root-katalogen. I Linux används tecknet / för att separear nivåerna av trädet. Ett ensamt / representerar rotkatalogen, /home lagrar filerna som tillhör användare, /home/didier lagrar filer som tillhör användare didier. /root lagrar filer för användaren som heter root (systemet's administratör). Obs: "root" kan hänvisa till toppnivåkatalogen eller systemet's administratör.

[[drive]]Enhet::
En enhet är en enhet som lagrar icke flyktiga data, vilket innebär att data inte raderas när strömmen är avstängd. Exempel: hårddiskar, SSD, USB-minnen, SD kortläsare, eMMC.
+
Media som lagrar data kan vara permanent ansluten till enheten eller flyttbar som SD-kort, USB-minnen och enheter anslutna via USB.
+
Ett operativsystem installerat på ett flyttbart media eller en extern enhet sägs var portabel: det kan flyttas från en dator till en annan.

[[display_manager]]Bildskärmshanterare::
En bildskärmshanterare (eller inloggningshanterare) är en programvara som visar ett fönster på skärmen där den frågar användarnamn och lösenord för användaren, startar den grafiska miljö som valts av nämnda användare.

[[encryption]]Kryptering::
Kryptering är processen för att konvertera data till en oigenkännlig ("krypterad") form. Det används ofta för att skydda känslig information så att endast behöriga personer kan se den. En enda fil eller katalog, en partition samt som en hel enhet kan krypteras, som gör den tillgänglig endast efter att skrivit in en liten text som kallas en lösenfras, hålls hemlig.

[[file]]Fil::
En datafil är en uppsättning digitala data som samlats in under samma namn, inspelade på ett permanent lagringsmedium, så kallad masslagring, till exempel en hårddisk, en SSD, en DVD, ett SD-kort eller en USN-pinne och hanteras som en enhet.
+
Filer kan innehålla data som texter, bilder, ljud, videor eller datorprogram.

[[file_system]]Filsystem::
Ett filsystem är ett program som hanterar filer och kataloger i en -partition. Den memorerar platsen i de fysiska medierna av data som finns i filerna, vilket gör det möjligt att läsa eller skriva dem. Exempel på vanliga filsystem är vfat, ntfs, ext4, f2fs. Detta kommando listar alla fil system som tillåter att läsa data som finns i en partition från Linux:
+
----
cat /proc/filsystem|grep -v nodev
----

[[firmware]]Firmware::
En firmware är en programvara som initierar och kontrollerar hårdvara, sedan antingen väljer och ladda i RAM operativsystemet, eller startar en programvara som heter en boot manager som kommer att göra det. Den inbyggda programvaran hålls i icke-flyktiga minne enheter som ROM, EPROM eller flashminne. Det är den första programvaran som körs när startar en dator. Det ger en meny som gör det möjligt att konfigurera hårdvaran och välja i vilket läge (Legacy eller EFI) att starta, och i vilken ordning leta efter operativsystemet eller andra program (som GRUB boot manager) att köra.

[[kernel]]Kernel::
En Linux-kärna är programvaran i kärnan av ett Slint-system som hanterar interaktioner mellan program och hårdvara.
+
Den presenterar sig som en enda fil, installerad i katalogen /boot. Till exempel är filen /boot/vmlinuz-generic-5.12.11 en kärna som kommer från kernel-generiskt paket.
+
Vid uppstart kopieras kärnan till RAM.

[[initrd]]Initrd::
En initrd (mer exakt ett initramfs eller initialt RAM-filsystem för Slint) är ett Linux-system som tillhandahålls som en komprimerad arkivfil. Vid uppstart, precis efter att kärnan har laddats i RAM laddas initrd i RAM också. Dess fil /init körs: den laddar behövda kärnmoduler i RAM, registrera enheterna, möjligen låser upp rootenheten, montera pseudofilsystem växlar sedan till rootfilsystemet för att faktiskt starta systemet.
+
En initrd presenterar sig som en enda fil, installerad i katalogen uppstart. Till exempel filen initrd-generic-5.12.11 är en initrd

[[live_system]]Live-system::
Ett live system är ett operativsystem som, istället för att installeras i en enhet som en hårddisk eller SSD, ligger helt i <<RAM>>.
+
An initrd is also a live system, and so is a Slint installatör wich is basically an initrd.

[[partition]]Partition::
En partition är en del av ett lagringsmedium, till exempel en hårddisk eller SSD. Det behandlas av operativsystemet som en separat logisk volym, vilket gör det fungerar som ett separat media.

[[partition_table]]Partitionstabell::
En partitionstabell är den permanenta strukturen som registrerar hur information läggs ut på ett medium, huvudsakligen inspelning av början och slutet av varje partition på mediat.
+
De vanligaste typerna av partitionstabeller är DOS-partitionstabellen, som initialt används av MS-DOS-operativsystemet, och GUID Partition Table eller GPT, som tillåter att hantera fler partitioner och större enheter.

[[program]]Program::
En förberedd sekvens av instruktioner till systemet för att utföra en definierad uppgift. Termen 'program' omfattar tillämpningar skrivna i Skalkommando-språk, komplexa verktyg för inmatningsspråk (t.ex. awk, lex, sed, osv.) och högnivåspråk. [POSIX]

[[RAM]]RAM::
RAM står för Random Access Memory. Denna typ av enhet lagrar flyktiga data, vilket innebär att data raderas när strömmen är avstängd.

[[shell]]Skal:: Ett program som tolkar sekvenser av textindata som kommandon. Den kan fungera på en indataström eller så kan den interaktivt prompt och läsa kommandon från en terminal. Syntaxen för de kommandon som kan tolkas av skalet kan variera beroende på vilket skal som används, men som i huvudsak definieras i kapitlet https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html[ 2. Shell Command Language] för POSIX-specifikationen.
+
Slint skickar flera program som fungerar som skal, listade i filen /etc/shells. *Bash*-skalet används som standard.

[[swap]]Växlingsutrymme::
Ett växlingsutrymme används för att preliminärt lagra data tidigare i RAM på en enhet som en hårddisk eller SSD, antingen för att RAM annars skulle bli fullt, eller för ledigt utrymme i RAM för att lagra det mest använda data. Växlingsutrymmet kan vara en partition på en enhet av typen "Linux swap" eller en vanlig fil som lagras i en en befintlig partition. Det finns också "swap i zram": i detta fall data lagras i RAM men i komprimerad form.

[[terminal]]Terminal::
Historiskt sett var en terminal en fysisk enhet som består av ett tangentbord och en skärm som används för att skriva kommandon och ta emot svar från en fjärrdator.
+
Numera kan kommandona skrivas i konsolläge (eller textläge) eller i grafiskt läge.

[[utility]]Verktyg::
Ett verktyg är ett program som kan köras med namn från ett skal (detta är också fallet med vissa <<application,program>>).
+
Verktyg är en del av operativsystemet (men inte en del av kärnan). De utför systemrelaterade funktioner, såsom att lista kataloginnehåll, kontrollera filsystem, reparera filsystem eller extrahera systemstatusinformation.
+
Ett verktyg kan anropas som ett separat program som kör i en annan process än kommandospråks tolken, eller så kan den implementeras som en del av kommandotolken.
+
Till exempel, echo-kommandot (direktivet för att utföra en specifik uppgift) kan genomföras så att echo-verktyget (den logik som utför uppgiften att eka ut) är i ett separat program; därför utförs den i en process som skiljer sig från kommando-språktolken. I praktiken innebär detta att verktyget i detta fall är ett program som skiljer sig från skalet
+
Omvänt skulle logiken som utför ekotjänsten kunna byggas in i kommandotolken; därför kunde den köra i samma process som kommandotolken. Ett sådant verktyg sägs vara "inbyggd" i skalet.

[[virtual_terminal]]Virtuell terminal::
En virtuell terminal är en programvara som simulerar en fysisk terminal, enhet består av ett tangentbord och en skärm som gör det möjligt att kommunicera på distans med en dator.
